"""Write parts/32_js_data.js: the chat data (from the root's src/sql/data.json, compacted the same way as the root's
playground so its loader parts/31_js_sql_c_run.js can be reused), the Reading-tab examples with their recorded PostgreSQL
and Python-SQLite results, the exercises with their expected results, and every measurement in inputs/.
Run: python3 gen_js.py   (plain Python 3; after the scripts in pg/ and ex/check.py)"""
import os, sys, json, datetime
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE); sys.path.insert(0, os.path.join(HERE, 'ex'))
ROOT_SQL = os.path.join(HERE, '..', '..', 'src', 'sql')
sys.path.insert(0, ROOT_SQL)
from examples import EX
from exercises import X
import ast
# the message text pools, read from the root's generator source (importing it would re-run it and rewrite the root's files)
_src = ast.parse(open(os.path.join(ROOT_SQL, 'gen_data.py')).read())
POOLS = {t.id: ast.literal_eval(n.value) for n in _src.body if isinstance(n, ast.Assign) for t in n.targets if isinstance(t, ast.Name) and t.id in ('USER_MSG', 'ASSIST_MSG')}

INP = os.path.join(HERE, 'inputs')
J = lambda n: json.load(open(os.path.join(INP, n)))
D = json.load(open(os.path.join(ROOT_SQL, 'data.json')))
T0 = datetime.datetime(2026, 1, 1)
pool = [POOLS['USER_MSG'], POOLS['ASSIST_MSG']]
msgs = []
for m in D['messages']:
    r = 1 if m[2] == 'assistant' else 0
    secs = int((datetime.datetime.strptime(m[5], '%Y-%m-%d %H:%M:%S') - T0).total_seconds())
    msgs.append([m[0], m[1], r, pool[r].index(m[3]), m[4], secs])
PARENT = ["ALTER TABLE messages ADD COLUMN parent_id INTEGER REFERENCES messages(id)",
          "UPDATE messages SET parent_id = (SELECT MAX(p.id) FROM messages p WHERE p.chat_id = messages.chat_id AND p.id < messages.id)"]

def slim(lst):
    out = []
    for r in lst:
        o = {k: v for k, v in r.items() if k in ('sql', 'cols', 'rows', 'n', 'error', 'status', 'changes')}
        if 'rows' in o: o['rows'] = o['rows'][:30]
        out.append(o)
    return out

E = J('examples.json')
ex = {}
for k, e in EX.items():
    run = E['runs'][k]
    ex[k] = {'sql': e['sql'], 'pg': e['pg'], 'only': e['only'], 'cmp': e['cmp'], 'pgres': slim(run['pg']), 'pyres': slim(run.get('sqlite_py', []))}
XE = J('ex_expected.json')['expected']
xs = [dict(x, exp=XE[x['id']]) for x in X]

A = J('alter.json')
alter = {k: A[k] for k in ('date', 'postgres', 'reps', 'table', 'settings')}
alter['ops'] = [{k: o.get(k) for k in ('id', 'grp', 'label', 'sql', 'locks', 'strongest', 'rewrite', 'blocks_read', 'blocks_write', 'median_s', 'times')} for o in A['ops']]
Q = J('queue.json')
K = J('keys.json'); K.pop('settings', None)
N = J('n1.json'); NR = J('n1_repeat.json')
for RR in (N, NR):
    for r in RR['runs']:
        for w in r['ways'].values(): w.pop('second_sql', None)
N['repeat'] = [{'path': r['path'], 'n': r['n'], 'ms': {k: v['median_ms'] for k, v in r['ways'].items()}} for r in NR['runs']]
AL = J('alembic.json')

# display numbers quoted in the text (filled into <span data-m="...">); recompute.py derives the same values independently
def mb(b): return f'{b / 2**20:.1f} MB'
def kr(kind, n, mode='bulk'):
    return next(r for r in K['runs'] if r['kind'] == kind and r['n'] == n and r['mode'] == mode)
ops = {o['id']: o for o in A['ops']}
M = {
  'alter_rows': f"{A['table']['rows']:,}", 'alter_size': A['table']['table_size'],
  'add_const_ms': f"{ops['add_const']['median_s'] * 1000:.1f}", 'add_volatile_s': f"{ops['add_volatile']['median_s']:.1f}",
  'type_bigint_s': f"{ops['type_bigint']['median_s']:.1f}", 'index_s': f"{ops['index']['median_s']:.2f}", 'index_conc_s': f"{ops['index_conc']['median_s']:.2f}",
  'q_long_max': f"{Q['scenarios']['long']['summary']['max_read_wait']:.2f}", 'q_timeout_max': f"{Q['scenarios']['timeout']['summary']['max_read_wait']:.2f}",
  'q_quick_max_ms': f"{Q['scenarios']['quick']['summary']['max_read_wait'] * 1000:.1f}",
  'k10_v4_idx': mb(kr('uuid_v4', 10_000_000)['index_bytes']), 'k10_v7_idx': mb(kr('uuid_v7', 10_000_000)['index_bytes']), 'k10_big_idx': mb(kr('bigint', 10_000_000)['index_bytes']),
}
out = {'schema': open(os.path.join(ROOT_SQL, 'schema_sqlite.sql')).read(), 'cols': D['cols'], 'users': D['users'], 'chats': D['chats'], 'msgs': msgs,
       'credits': D['credits'], 'pool': pool, 'parent_sql': PARENT,
       'exmeta': {'date': E['date'], 'postgres': E['postgres'], 'python_sqlite': E['python_sqlite']}, 'ex': ex, 'xs': xs,
       'alter': alter, 'queue': Q, 'keys': K, 'n1': N, 'alembic': AL, 'M': M}
s = json.dumps(out, separators=(',', ':'), ensure_ascii=False)
assert '—' not in s and '{{' not in s and '</' not in s.replace('<\\/', ''), 'forbidden text in data'
p = os.path.join(HERE, 'parts', '32_js_data.js')
open(p, 'w').write('// ---- generated by src/gen_js.py from the root\'s data, examples.py, exercises.py and inputs/*.json; do not edit ----\nwindow.SM_DATA=' + s + ';\n')
print('wrote', p, os.path.getsize(p), 'bytes')
