"""Writes parts/22_js_data.js (window.SV: measured data the page's JavaScript draws) and facts.json (every measured number
quoted in the prose, substituted for @@key@@ by build.sh) from inputs/*.json. Run: python3 build_data.py"""
import json, os
H = os.path.dirname(os.path.abspath(__file__)); I = os.path.join(H, 'inputs')
m1 = json.load(open(f'{I}/m1_ann.json')); m2 = json.load(open(f'{I}/m2_fts.json')); m3 = json.load(open(f'{I}/m3_tiny.json'))
emb = json.load(open(f'{I}/embed_log.json'))
rag = json.load(open(os.path.join(H, '../../../../measurement/topic_evaluation_and_llm_judges/rag_and_retrieval_evaluation/src/inputs/beir_summary.json')))
N = m1['env']['rows']
ex = m1['exact']['cos_w2']
ann = {'rows': N, 'dims': m1['env']['dims'], 'queries': m1['env']['queries'],
       'exact': {'recall': ex['recall10'], 'p50_ms': ex['p50_ms'], 'p95_ms': ex['p95_ms']},
       'hnsw': {k: {kk: v[kk] for kk in ['m', 'ef_construction', 'build_s', 'bytes', 'curve']} for k, v in m1['hnsw'].items()},
       'ivf': {k: {kk: v[kk] for kk in ['lists', 'build_s', 'bytes', 'curve']} for k, v in m1['ivf'].items()},
       'quant': {k: v for k, v in m1['quant'].items() if k != 'sizes_note'},
       'filter': {c: {k: v for k, v in f.items() if k != 'planner_default_plan'} for c, f in m1['filter'].items()}}
for s in ann['hnsw'].values():
    for c in s['curve']: c.pop('mean_ms', None); c.pop('n', None); c.pop('rows_mean', None)
for s in ann['ivf'].values():
    for c in s['curve']: c.pop('mean_ms', None); c.pop('n', None); c.pop('rows_mean', None)
rel = {}
for corp in ['quora', 'scifact']:
    r = m2[corp]
    # two randomly drawn Quora questions on adult topics are left out of the gallery (they stay in every average)
    smp = [x for x in json.loads(json.dumps(r['samples'])) if not any(w in x['query'].lower() for w in ('porn', 'virginity'))]
    for x in smp:
        for k in x['top']:
            for d in x['top'][k]: d['text'] = d['text'][:160] + ('...' if len(d['text']) > 160 else ''); d.pop('id', None)
        x['relevant'] = [t[:200] + ('...' if len(t) > 200 else '') for t in x['relevant']]
    rel[corp] = {'scores': r['scores'], 'samples': smp, 'latency': r['latency'], 'docs': r['docs'], 'queries': r['queries']}
rs = rag['scifact']['systems']
rel['cross'] = {'bm25': f"{rs['bm25_lucene']['ndcg@10']:.3f}", 'dense': f"{rs['dense_minilm']['ndcg@10']:.3f}", 'hybrid': f"{rs['hybrid_rrf']['ndcg@10']:.3f}"}
demo = m2['demo']
tiny = {k: m3[k] for k in ['query', 'docs', 'query_lexemes', 'first_dims', 'norm']}
SV = {'ann': ann, 'rel': rel, 'demo': {k: demo[k] for k in ['ts_debug', 'to_tsvector', 'plainto', 'phraseto', 'websearch', 'show_trgm', 'typo_trgm_top']}, 'tiny': tiny}
open(os.path.join(H, 'parts/22_js_data.js'), 'w').write('// generated by build_data.py from inputs/*.json; do not edit\nwindow.SV=Object.assign(window.SV||{},' + json.dumps(SV, separators=(',', ':')) + ');\n')

# ---- facts quoted in the prose ----
MB = lambda b: f'{b / 1e6:,.0f}'
h16 = m1['hnsw']['m16_efc64']; c16 = {c['ef_search']: c for c in h16['curve']}
h8 = m1['hnsw']['m8_efc32']; c8 = {c['ef_search']: c for c in h8['curve']}
h32 = m1['hnsw']['m32_efc128']; c32 = {c['ef_search']: c for c in h32['curve']}
iv = m1['ivf']['lists523']; ci = {c['probes']: c for c in iv['curve']}
Q = m1['quant']; F = m1['filter']; O = m1['ops']; L = m1['load']
qs = m2['quora']['scores']; ss = m2['scifact']['scores']
bpv = h16['bytes'] / N; link = bpv - 1544
def buf(plan):
    for l in plan:
        if 'Buffers: shared hit=' in l: return int(l.split('shared hit=')[1].split()[0])
f = {}
f['embed_s'] = f"{emb['quora']['embed_s']:.0f}"
f['rows'] = f'{N:,}'
f['copy_s'] = f"{L['copy_s']:.1f}"
f['vec_mb'] = MB(L['vector_column_bytes']); f['heap_mb'] = MB(L['heap_bytes']); f['vec_share'] = f"{100 * L['vector_column_bytes'] / L['heap_bytes']:.0f}"
f['exact_p50'] = f"{ex['p50_ms']:.0f}"; f['exact_p95'] = f"{ex['p95_ms']:.0f}"; f['exact_ip_p50'] = f"{m1['exact']['ip_w2']['p50_ms']:.0f}"
f['exact_buf'] = f"{buf(m1['exact']['plan']):,}"; f['hnsw_buf'] = f"{buf(h16['plan']):,}"
f['hnsw40_p50'] = f"{c16[40]['p50_ms']:.2f}"; f['hnsw40_p95'] = f"{c16[40]['p95_ms']:.2f}"
f['hnsw40_rec'] = f"{c16[40]['recall10']:.3f}"; f['hnsw40_rec_pct'] = f"{100 * c16[40]['recall10']:.1f}"
f['hnsw10_rec'] = f"{c16[10]['recall10']:.3f}"; f['hnsw640_rec'] = f"{c16[640]['recall10']:.3f}"
f['ef_growth'] = f"{c16[640]['p50_ms'] / c16[10]['p50_ms']:.0f}"
f['speedup'] = f"{ex['p50_ms'] / c16[40]['p50_ms']:.0f}"
f['hnsw_mb'] = MB(h16['bytes']); f['hnsw_build'] = f"{h16['build_s']:.0f}"; f['hnsw_bpv'] = f'{bpv:,.0f}'; f['link_bytes'] = f'{link:,.0f}'
f['mem10m'] = f"{1e7 * (6152 + link) / 1e9:.0f}"; f['mem100m'] = f"{1e8 * (6152 + link) / 1e9:.0f}"
f['m8_build'] = f"{h8['build_s']:.0f}"; f['m8_640'] = f"{c8[640]['recall10']:.3f}"; f['m8_10_p50'] = f"{c8[10]['p50_ms']:.2f}"; f['m8_10_rec'] = f"{c8[10]['recall10']:.2f}"
f['m32_build'] = f"{h32['build_s']:.0f}"; f['m32_40'] = f"{c32[40]['recall10']:.3f}"
f['ivf1_rec'] = f"{ci[1]['recall10']:.3f}"; f['ivf23_rec'] = f"{ci[23]['recall10']:.3f}"; f['ivf23_p50'] = f"{ci[23]['p50_ms']:.1f}"
f['ivf_build'] = f"{iv['build_s']:.0f}"; f['ivf_mb'] = MB(iv['bytes'])
bc = Q['binary']['curve']
f['bin_rec'] = f"{bc[0]['recall10']:.3f}"; f['bin100_rec'] = f"{bc[2]['recall10']:.3f}"; f['bin400_rec'] = f"{bc[3]['recall10']:.3f}"
f['plan_rows'] = f"{F['tenant']['planner_default']['rows_mean']:.2f}"
f['post1_rows'] = f"{F['tenant']['hnsw_post_filter']['rows_mean']:.2f}"
f['b200_s'] = f"{O['build_200k_s']:.0f}"; f['b200_64_s'] = f"{O['build_200k_64MB_s']:.0f}"
f['notice'] = (O['notices_64MB'][0] if O['notices_64MB'] else 'none printed').replace('"', '')
f['ins_h'] = f"{O['insert_5000_single_rows_with_hnsw_s']:.1f}"; f['ins_n'] = f"{O['insert_5000_single_rows_no_vector_index_s']:.1f}"
f['vac_s'] = f"{O['vacuum_after_10pct_delete_s']:.0f}"; f['reidx_s'] = f"{O['reindex_s']:.0f}"
qi = m2['quora']['index']
f['add_tsv_s'] = f"{qi.get('add_tsv_s', 0):.0f}"; f['tsv_mb'] = MB(qi['tsv_column_bytes']); f['gin_s'] = f"{qi['gin_build_s']:.1f}"; f['gin_mb'] = MB(qi['gin_bytes']); f['lexemes'] = f"{qi['distinct_lexemes']:,}"
lg = m3['like_vs_gin']
f['like_ms'] = f"{lg['ilike_seqscan']['ms_median_of_5']:.0f}"; f['like_par_ms'] = f"{lg['ilike_seqscan_parallel']['ms_median_of_5']:.0f}"
f['like_trgm_ms'] = f"{lg['ilike_trigram_index']['ms_median_of_5']:.2f}"; f['like_rows'] = f"{lg['ilike_seqscan']['rows']:,}"
f['fts_ms'] = f"{lg['fts_gin']['ms_median_of_5']:.2f}"; f['fts_rows'] = f"{lg['fts_gin']['rows']:,}"
f['phrase_hits'] = f"{demo['phrase_hits']:,}"; f['and_hits'] = f"{demo['and_hits']:,}"; f['typo_fts_hits'] = f"{demo['typo_fts_hits']:,}"
f['trgm_s'] = f"{demo['trgm_build_s']:.0f}"; f['trgm_mb'] = MB(demo['trgm_bytes']); f['trgm_ms'] = f"{demo['typo_trgm_ms']:.0f}"
f['q_fts_or'] = f"{qs['fts_or']['ndcg10']:.3f}"; f['q_bm25'] = f"{qs['bm25_pg']['ndcg10']:.3f}"; f['q_rrf_sql'] = f"{qs['rrf_sql']['ndcg10']:.3f}"
f['q_and_empty'] = f"{100 * qs['fts_and']['empty_share']:.0f}"
f['rrf_sql_p50'] = f"{m2['quora']['latency']['rrf_sql']['p50_ms']:.1f}"
f['bm25_q'] = f"{qs['bm25_pg']['ndcg10']:.3f}"; f['vec_q'] = f"{qs['vector']['ndcg10']:.3f}"; f['hyb_q'] = f"{qs['rrf_bm25_vec']['ndcg10']:.3f}"
f['s_hyb'] = f"{ss['rrf_bm25_vec']['ndcg10']:.3f}"; f['s_bm25'] = f"{ss['bm25_pg']['ndcg10']:.3f}"; f['s_vec'] = f"{ss['vector']['ndcg10']:.3f}"
f['qnorm'] = f"{m3['norm']:.4f}"
t = m1['truth']; f['ex_q'] = t['example_query']
for i in range(3): f[f'ex{i+1}'] = t['example_top3'][i]; f[f'ex{i+1}c'] = f"{t['example_top3_cos'][i]:.3f}"

# ---- two prose summaries generated from the numbers ----
def fr(c):
    x = F[c]; pf, st, rl, pre = x['hnsw_post_filter'], x['hnsw_strict'], x['hnsw_relaxed'], x['btree_prefilter_exact']
    pct = f"{100 * x['share_of_rows']:.0f}%"
    return (f"With a {pct} filter and iterative scans off, the HNSW scan returned {pf['rows_mean']:.2f} rows on average instead of 10 "
            f"({100 * pf['zero_rows_share']:.0f}% of queries returned nothing; recall {pf['recall10']:.2f}). strict_order returned {st['rows_mean']:.2f} rows "
            f"at recall {st['recall10']:.3f} in {st['p50_ms']:.1f} ms; relaxed_order {rl['rows_mean']:.2f} rows at recall {rl['recall10']:.3f} in {rl['p50_ms']:.1f} ms; "
            f"the B-tree pre-filter with exact search was always right (recall {pre['recall10']:.3f}) in {pre['p50_ms']:.1f} ms.")
f['filt_text'] = fr('tenant') + ' ' + fr('tenant10') + (' Iterative scans fix the empty results; the price is latency and, at the 1% filter, the 20,000-tuple scan limit. '
    'Pre-filtering wins when the filter is selective, because exact search over about 5,230 rows is cheap; at 10% it must compute about 52,300 distances per query.')
def hy(name, sc):
    b, v, h = sc['bm25_pg']['ndcg10'], sc['vector']['ndcg10'], sc['rrf_bm25_vec']['ndcg10']
    lead = f'vectors beat BM25 (nDCG@10 {v:.3f} against {b:.3f})' if v > b else f'BM25 beat vectors (nDCG@10 {b:.3f} against {v:.3f})'
    res = 'fusion beat both' if h > max(b, v) else ('fusion landed between them' if h > min(b, v) else 'fusion was worst')
    return f"On {name}, {lead} and {res} ({h:.3f})."
w = m2['quora']['wins']
f['hyb_text'] = (hy('Quora', qs) + ' ' + hy('SciFact', ss) + f" Per question on Quora, BM25 was better on {w['bm25_better_than_vector']}, vectors on {w['vector_better_than_bm25']}, and they tied on {w['tie']}: "
    'the two retrievers fail on different questions, which is what fusion exploits when both are comparably strong (SciFact) and why an equal-weight fusion costs a little when one is much stronger (Quora). Requiring every word (fts_and) or ranking without idf (fts_or) costs the most; '
    'the HNSW index (ef_search 100) gave up little against exact vector search.')
json.dump(f, open(os.path.join(H, 'facts.json'), 'w'), indent=1)
print('facts', len(f), 'data bytes', os.path.getsize(os.path.join(H, 'parts/22_js_data.js')))
