#!/usr/bin/env python3
"""Write parts/20_js_data.js (window.SD) from inputs/sims_*.json and expected.json. Run after sims.py and recompute.py."""
import json, os
H = os.path.dirname(os.path.abspath(__file__))
SD = {k: json.load(open(os.path.join(H, "inputs", "sims_%s.json" % k)))
      for k in ("grid", "anim", "clt", "boot", "entropy", "dd", "conc", "peek", "cv")}
E = json.load(open(os.path.join(H, "expected.json")))
# ridge keys as JavaScript writes them: String(0) is "0", String(1) is "1"
for kind, res in SD["dd"]["betas"].items():
    for k in list(res):
        if k != "theory":
            res[str(int(float(k))) if float(k).is_integer() else str(float(k))] = res.pop(k)
SD["tcrit"] = {"5": E["anim"]["lognormal5"]["tcrit"], "30": E["anim"]["normal30"]["tcrit"]}
SD["tiny"] = {"p": E["tiny_p"], "L": E["tiny_L"], "mu": E["tiny_mu"], "sd": E["tiny_sd"]}
with open(os.path.join(H, "parts", "20_js_data.js"), "w") as f:
    f.write("// Generated by src/mk_data.py from inputs/sims_*.json (sims.py, seeded) and expected.json. Do not edit.\n")
    f.write("window.SD=" + json.dumps(SD, separators=(",", ":")) + ";\n")
print(os.path.getsize(os.path.join(H, "parts", "20_js_data.js")))
