#!/bin/sh
# Assemble ../index.html from parts/ (parts listed explicitly, so shell sort order never matters).
# HTML: head and CSS, header and tab bar, Reading (a, b), Boundary lab, Further reading.
# JS: every script in its own <script>, the tab wiring (99_js_tabs.js) last, after the hidden error box and handler.
# Links may be written {{text|url}} (url may be n:<notion id>, or #t-<tab> for a link to a tab); plain <a> tags pass through.
# Data: parts/31_js_data.js is generated by data/mk_data.py from inputs/.
cd "$(dirname "$0")"
{ cat parts/01_head.html parts/10_header.html parts/20_read_a.html parts/20_read_b.html parts/50_tab_lab.html parts/59_tab_more.html
  echo '<div id="jsErr" hidden style="margin:12px 0;padding:10px 12px;border:1px solid #c2703a;border-radius:8px;font:13px/1.5 ui-monospace,Menlo,monospace;white-space:pre-wrap"></div>'
  cat parts/05z_errbox.js.html
  for f in parts/21_js_common.js parts/30_js_ml.js parts/31_js_data.js parts/32_js_plot.js parts/33_js_models.js parts/40_js_rd_tree.js parts/41_js_rd_ens.js parts/42_js_rd_bench.js parts/43_js_rd_svm.js parts/44_js_rd_knn.js parts/45_js_rd_clu.js parts/46_js_rd_pca.js parts/47_js_rd_hp.js parts/51_js_lab.js; do echo "<script>/* $(basename $f) */"; cat "$f"; echo '</script>'; done
  echo "<script>/* 99_js_tabs.js */"; cat parts/99_js_tabs.js; echo '</script>'
  echo '</div></body></html>'; } | perl -CSD -pe '
s/\{\{([^|{}]+)\|([^{}]+)\}\}/my($t,$u)=($1,$2);if($u=~m{^#(t-[\w-]+)$}){"<a href=\"#\" data-tab=\"$1\">$t<\/a>"}else{$u=~s{^n:}{https:\/\/app.notion.com\/p\/};"<a href=\"$u\" target=\"_blank\" rel=\"noopener noreferrer\">$t<\/a>"}/ge;
' > ../index.html
if grep -q '{{' ../index.html; then echo "unexpanded link"; grep -o '{{[^}]*}}' ../index.html | head; fi
ED=$(printf '\342\200\224')
if grep -q "$ED" ../index.html; then echo "EM DASH FOUND"; grep -n -o ".\{30\}$ED.\{30\}" ../index.html | head; fi
wc -c ../index.html
