"""The Failure lab's teaching text, one entry per reproduced failure. make_data.py joins it with out/<id>.json.

Fields: id (= out/<id>.json), t title, layer, sym (the symptom as a user or a log first meets it), tools (where the
recorded runs show it), q (the drill scenario), a (what to check first, and why), cause, fix, ml (how it shows up in
ML work), src [[label, url]] primary sources, sim (set when part of the setup is simulated, saying which part).
"""

RFC = "https://www.rfc-editor.org/rfc/"
NGX = "https://nginx.org/en/docs/http/ngx_http_proxy_module.html"
CURLERR = ["curl exit codes (libcurl-errors)", "https://curl.se/libcurl/c/libcurl-errors.html"]
MCPT = ["MCP spec 2025-11-25, Transports", "https://modelcontextprotocol.io/specification/2025-11-25/basic/transports"]

CASES = [
# ---------------- TCP connection ----------------
dict(id="refused", t="Connection refused", layer="TCP", sym="curl: (7) Failed to connect ... Couldn't connect to server / ECONNREFUSED / [Errno 61]",
  tools=["curl", "requests", "httpx", "node", "nc", "lsof"],
  q="Your client fails instantly (under 100 ms) with 'connection refused' to 127.0.0.1:27099. What do you check first?",
  a="Whether anything is listening on that port on that host: <code>lsof -iTCP:27099 -sTCP:LISTEN</code> (or <code>ss -ltnp</code> on Linux). A refusal is an answer: the machine was reached and its kernel replied with a reset because no socket was bound there. Wrong port, server not started yet, or bound to another address (127.0.0.1 versus 0.0.0.0).",
  cause="No process listens on the port, so the destination's kernel answers the connection request (SYN) with a reset (RST). It is fast because the packet got there and back.",
  fix="Start the server, fix the port, or bind to an address the client can reach (a server inside a container bound to 127.0.0.1 is unreachable from outside it).",
  ml="A notebook calling a local vLLM or Ollama server before the model finished loading (the port opens only after weights are in memory); a training job's rank 0 not yet listening when other ranks try to rendezvous.",
  src=[CURLERR, ["RFC 9293 section 3.5.2 (reset generation)", RFC + "rfc9293#section-3.5.2"]]),
dict(id="conn_timeout", t="Connect timeout", layer="TCP", sym="curl: (28) Failed to connect ... Timeout was reached / ConnectTimeout / UND_ERR_CONNECT_TIMEOUT",
  tools=["curl", "requests", "httpx", "node", "nc", "route"],
  q="Connecting to 192.0.2.1:8080 hangs for exactly as long as your timeout, then fails. Nothing in the server's logs. What do you check first?",
  a="Whether packets reach the host at all: the route (<code>route -n get</code> / <code>ip route get</code>), then firewalls and security groups. Silence, not a refusal, means the SYN or its reply was dropped somewhere: a firewall, a wrong IP, a host that is down, a private address with no route.",
  cause="The connection request got no answer. 192.0.2.1 is TEST-NET-1 (RFC 5737), reserved for documentation, so nothing on the Internet answers it: the default gateway forwards the SYN and it vanishes. Each client gives up at its own deadline: 3 s here for curl, requests and httpx because the run set it; Node's fetch (undici) waits its default 10 s.",
  fix="Fix the address, route or firewall rule; and always set a connect timeout well below the request timeout, so a dead host fails in seconds rather than minutes.",
  ml="A job in one VPC calling a model endpoint in another without peering; a security group that allows 443 but not the custom port of a Triton or Ray endpoint.",
  sim="The unreachable host is a reserved documentation address (one SYN from this machine to its gateway per attempt), standing in for a firewalled one.",
  src=[["RFC 5737 (TEST-NET-1)", RFC + "rfc5737"], ["undici Client options: connectTimeout 10e3", "https://github.com/nodejs/undici/blob/main/docs/docs/api/Client.md"], CURLERR]),
dict(id="reset", t="Connection reset by peer (and the empty reply)", layer="TCP", sym="curl: (56) Recv failure: Connection reset by peer / ECONNRESET / ConnectionResetError(54)",
  tools=["curl", "requests", "httpx", "node"],
  q="A request is accepted, then fails with 'connection reset by peer' and no HTTP status. What do you check first?",
  a="The other end's logs at that moment: a crash, an out-of-memory kill, a proxy or load balancer closing the connection, or a TLS/protocol mismatch on that port. A reset (RST) is an abort: the peer threw away the connection. A clean close with no bytes shows as curl (52) Empty reply / RemoteDisconnected instead.",
  cause="The server read the request and closed the socket with SO_LINGER 0, which makes the kernel send RST instead of the normal FIN. The second server closes normally (FIN) without answering: same lost request, different words.",
  fix="Find who closes: server crash logs, OOM-killer messages, idle timeouts on proxies. Retry only if the request is idempotent (a POST that may have run should not be blindly resent).",
  ml="A model server killed by the OOM killer mid-request (the kernel tears down its sockets); a GPU worker restarting behind a load balancer.",
  src=[["RFC 9293 section 3.10.7 (RST)", RFC + "rfc9293"], CURLERR]),
dict(id="read_timeout", t="Read timeout: connected, then nothing", layer="TCP", sym="curl: (28) Operation timed out after 3006 milliseconds with 0 bytes received / ReadTimeout",
  tools=["curl", "requests", "httpx", "node"],
  q="The connection opens at once but no byte of the response arrives before the timeout. What do you check first?",
  a="Split the time: <code>curl -w 'connect %{time_connect} first byte %{time_starttransfer}'</code>. Connect fast plus no first byte means the network is fine and the server (or something it waits on) is stuck. Then look at the server: queue depth, a hung worker, a lock.",
  cause="The server accepted the connection and read the request but never answered: the kernel completed the handshake, the application did not respond.",
  fix="Fix the hang; set separate connect and read timeouts. Know the defaults: requests has none (it waits forever unless you pass timeout=), httpx uses 5 s, Node's fetch waits 300 s for headers (undici headersTimeout).",
  ml="A long prefill on a huge prompt, a model server whose request queue is full, a cold start loading weights: all look like 'connected, then nothing'. Streaming the response makes the first byte arrive early and turns a dead stream into a visible one.",
  src=[["requests: timeouts", "https://requests.readthedocs.io/en/latest/user/advanced/#timeouts"], ["httpx: timeouts (5 s default)", "https://www.python-httpx.org/advanced/timeouts/"], ["undici headersTimeout 300e3", "https://github.com/nodejs/undici/blob/main/docs/docs/api/Client.md"]]),
# ---------------- DNS ----------------
dict(id="nxdomain", t="NXDOMAIN: the name does not exist", layer="DNS", sym="curl: (6) Could not resolve host / ENOTFOUND / [Errno 8] nodename nor servname provided",
  tools=["curl", "requests", "httpx", "node", "dig"],
  q="Every client says it cannot resolve the host. What do you check first?",
  a="Ask DNS directly and read the status: <code>dig name</code>. <code>status: NXDOMAIN</code> means an authoritative 'no such name': a typo, a deleted record, or a name that only exists in another view (see Wrong resolver). NOERROR with no answer means the name exists without that record type.",
  cause="The name has no record. Here the public name ends in .invalid, which RFC 6761 reserves as never resolvable, and the local server holds api.llm.test but not api.llm-typo.test.",
  fix="Fix the name, or create the record. Do not retry: NXDOMAIN is an answer, and resolvers cache it (negative caching, RFC 2308).",
  ml="A typo in HF_ENDPOINT or OPENAI_BASE_URL; a Kubernetes Service name used from outside the cluster, where it does not exist.",
  src=[["RFC 6761 section 6.4 (.invalid)", RFC + "rfc6761#section-6.4"], ["RFC 2308 (negative caching)", RFC + "rfc2308"]]),
dict(id="servfail", t="SERVFAIL: the resolver could not get an answer", layer="DNS", sym="status: SERVFAIL / NoNameservers ... answered SERVFAIL / EAI_AGAIN (temporary failure)",
  tools=["dig", "dnspython"],
  q="dig shows status: SERVFAIL for a name that worked yesterday. What do you check first?",
  a="Whether the authoritative servers for the zone answer: <code>dig +trace name</code>, or ask them directly. SERVFAIL means the resolver tried and failed (authoritative servers down or lame, a DNSSEC validation failure, an upstream timeout); unlike NXDOMAIN it says nothing about whether the name exists.",
  cause="The local authoritative server is configured to answer SERVFAIL for weights.broken.lab.test, standing in for a zone whose servers are failing.",
  fix="Fix the zone or its delegation; with DNSSEC, fix the signatures. Clients may retry: it is a temporary-failure answer.",
  ml="Training jobs that resolve a storage endpoint thousands of times at start-up can turn a short SERVFAIL window into a crash loop across every worker.",
  sim="The failing zone is simulated: the lab's DNS server is told to answer SERVFAIL. A public DNSSEC-broken test domain was tried, but this machine's DNS goes through a filtering resolver that does not validate, so it answered NOERROR (itself a wrong-resolver lesson).",
  src=[["RFC 1035 section 4.1.1 (RCODE 2)", RFC + "rfc1035#section-4.1.1"]]),
dict(id="stale_ttl", t="Stale answer: the cache still holds the old address", layer="DNS", sym="the old IP keeps coming back after a change; TTL counting down",
  tools=["dig"],
  q="You moved an endpoint to a new IP; the authoritative DNS shows it, but clients keep hitting the old one. What do you check first?",
  a="The TTL in the answer clients get from their resolver: <code>dig name</code> through the same resolver they use. The number beside the record is how many seconds that cache will keep serving the old answer. Then check client-side caches and long-lived connections, which never re-resolve.",
  cause="A caching resolver keeps each answer for its TTL (300 s here) and counts it down; changing the authoritative record does nothing to copies already cached.",
  fix="Lower the TTL well before a planned move (to 30 to 60 s), wait out the old TTL, then switch. Recycle long-lived connections (HTTP keep-alive, gRPC channels) so they resolve again.",
  ml="A blue/green switch of an inference endpoint where half the traffic still lands on the old fleet for minutes; gRPC channels that resolved once at start-up and stay pinned to the old IPs.",
  sim="The authoritative server and the cache are the lab's own (dnspython); the last run is the same countdown on a real public name.",
  src=[["RFC 1035 section 3.2.1 (TTL)", RFC + "rfc1035#section-3.2.1"]]),
dict(id="wrong_resolver", t="Wrong resolver: the name exists, but not where you asked", layer="DNS", sym="NXDOMAIN from one machine, an answer from another",
  tools=["dig"],
  q="llm.corp.lab.test resolves on your laptop but not in a CI runner. What do you check first?",
  a="Which resolver each machine actually uses (<code>/etc/resolv.conf</code>; <code>scutil --dns</code> on macOS, where apps and dig can differ) and ask each one directly with <code>dig @server name</code>. Internal names live only on internal resolvers (split-horizon DNS).",
  cause="The internal resolver holds the corp zone; the public resolver has never heard of it and answers NXDOMAIN.",
  fix="Point the client at the right resolver (VPN, VPC DNS, a conditional forwarder for the internal zone).",
  ml="A Docker container on a laptop on VPN using the Docker VM's DNS rather than the VPN's; a SageMaker or Vertex job in a VPC without the private DNS zone attached.",
  sim="Both resolvers are the lab's own on 127.0.0.1 (ports 27353 and 27354).",
  src=[["RFC 9499 (DNS terminology: split DNS)", RFC + "rfc9499"]]),
dict(id="ndots", t="Kubernetes ndots:5: one lookup becomes eight", layer="DNS", sym="slow first requests from pods; DNS servers busy with NXDOMAIN for names like api.example.com.default.svc.cluster.local",
  tools=["resolver", "dns log"],
  q="Pods in a cluster make 8 DNS queries for every external name and CoreDNS is hot. What do you check first?",
  a="The pod's <code>/etc/resolv.conf</code>: with <code>options ndots:5</code>, any name with fewer than five dots is first tried with every search domain appended, each for A and AAAA, before the name as typed.",
  cause="The kubelet writes ndots:5 and three search domains so short Service names work. api.llm.test has two dots, so the resolver tries api.llm.test.default.svc.cluster.local, .svc.cluster.local, .cluster.local, and only then api.llm.test: 6 wasted queries (3 NXDOMAIN pairs) before the 2 that answer.",
  fix="Write external names fully qualified with a trailing dot (api.llm.test.), or set dnsConfig options ndots:1 (or 2) on pods that mostly call external hosts; NodeLocal DNSCache softens the cost.",
  ml="Inference gateways and data loaders in Kubernetes calling external APIs, object storage or Hugging Face turn every external lookup into eight queries.",
  sim="The search-list rule is implemented in ndots_stub.py from resolv.conf(5) (glibc's behaviour); the DNS server that answers and logs every query is real. musl (Alpine) differs in details.",
  src=[["Kubernetes: DNS for Services and Pods", "https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/"], ["resolv.conf(5)", "https://man7.org/linux/man-pages/man5/resolv.conf.5.html"]]),

# ---------------- TLS ----------------
dict(id="tls_expired", t="Expired certificate", layer="TLS", sym="certificate has expired / CERT_HAS_EXPIRED / Verify return code: 10",
  tools=["curl", "requests", "httpx", "node", "openssl"],
  q="Overnight, every client starts failing TLS verification against one host. What do you check first?",
  a="The certificate's dates against the clock: <code>openssl s_client -connect host:443 -servername host | openssl x509 -noout -dates</code>. notAfter in the past means it expired; renewal (often an automated ACME job) failed or the server was not reloaded after renewal.",
  cause="The server presents a certificate whose notAfter (Oct 4) is before now (Oct 5). Every client checks validity dates as part of path validation (RFC 5280 section 6.1.3).",
  fix="Renew and reload the server; monitor expiry (alert at 14 days). Never 'fix' it with verify=False.",
  ml="An internal model gateway's certificate issued by hand a year ago; a self-hosted MLflow or Label Studio behind a forgotten certificate.",
  src=[["RFC 5280 section 4.1.2.5 (validity)", RFC + "rfc5280#section-4.1.2.5"], ["OpenSSL verify error codes", "https://docs.openssl.org/master/man1/openssl-verification-options/"]]),
dict(id="tls_hostname", t="Wrong hostname (SAN mismatch)", layer="TLS", sym="no alternative certificate subject name matches target host name / Hostname mismatch / ERR_TLS_CERT_ALTNAME_INVALID",
  tools=["curl", "requests", "httpx", "node", "openssl"],
  q="TLS fails with a hostname mismatch, but the certificate is valid and trusted. What do you check first?",
  a="The names in the certificate and the name you connect with: <code>openssl x509 -noout -ext subjectAltName</code>. Clients match the name in the URL against the Subject Alternative Name list only (the CN is ignored). Also check SNI: a server with several certificates picks one by the name the client sends (-servername).",
  cause="The certificate lists only other.llm.test; the clients asked for api.llm.test (curl) or localhost (Python, Node).",
  fix="Issue a certificate whose SAN includes every name clients use (including internal ones), or connect with the right name. Connecting by IP needs an IP SAN.",
  ml="Calling an internal endpoint by its load balancer's raw DNS name or IP instead of the name on the certificate; a Kubernetes Service name (svc.cluster.local) not in the ingress certificate.",
  src=[["RFC 9525 (service identity in TLS)", RFC + "rfc9525"], ["RFC 6066 section 3 (SNI)", RFC + "rfc6066#section-3"]]),
dict(id="tls_unknown_ca", t="Unknown CA: the issuer is not trusted here", layer="TLS", sym="unable to get local issuer certificate / UNABLE_TO_VERIFY_LEAF_SIGNATURE / Verify return code: 21",
  tools=["curl", "requests", "httpx", "node", "openssl"],
  q="curl and Python fail with 'unable to get local issuer certificate'; the browser on the same machine works. What do you check first?",
  a="Who issued the certificate (<code>openssl s_client ... | grep 'i:'</code>) and whether that issuer is in the trust store this client uses. Python requests uses certifi's bundle, not the OS store; Node uses its own; corporate TLS inspection and private CAs are trusted by the OS and browser but not by these.",
  cause="The server's certificate is signed by the lab's private 'Wire Lab Root CA', which is in no default trust store.",
  fix="Give the client the CA: curl --cacert, REQUESTS_CA_BUNDLE or SSL_CERT_FILE for Python, NODE_EXTRA_CA_CERTS for Node, pip --cert. The last run shows the same request succeeding once the CA is trusted.",
  ml="pip install, Hugging Face downloads (which use requests) and API SDKs failing on a corporate network that inspects TLS, while the browser works.",
  src=[["RFC 5280 section 6 (path validation)", RFC + "rfc5280#section-6"], ["requests: CA certificates", "https://requests.readthedocs.io/en/latest/user/advanced/#ca-certificates"], ["Node: NODE_EXTRA_CA_CERTS", "https://nodejs.org/api/cli.html#node_extra_ca_certsfile"]]),
dict(id="tls_intermediate", t="Missing intermediate certificate", layer="TLS", sym="unable to get local issuer certificate (only depth 0 sent) / works in the browser",
  tools=["curl", "requests", "httpx", "node", "openssl"],
  q="A newly deployed certificate fails in curl and Python with 'unable to get local issuer', even though the root CA is trusted. What do you check first?",
  a="How many certificates the server sends: <code>openssl s_client -showcerts</code> lists depth 0, 1, ... A lone 'depth 0' whose issuer is an intermediate means the server sends the leaf without its chain. Browsers often hide this by fetching or caching intermediates; command-line clients do not.",
  cause="The leaf is signed by 'Wire Lab Issuing CA 1', which is signed by the root. The server on port 27447 sends only the leaf, so a client holding just the root cannot build the path; port 27448 sends leaf plus intermediate (fullchain.pem) and verifies.",
  fix="Configure the server with the full chain (leaf first, then intermediates; never the root).",
  ml="A model endpoint certificate installed from the CA's 'cert.pem' instead of 'fullchain.pem'.",
  src=[["RFC 8446 section 4.4.2 (certificate_list order)", RFC + "rfc8446#section-4.4.2"]]),
dict(id="tls_clock", t="Clock skew: certificate not yet valid", layer="TLS", sym="certificate is not yet valid / Verify return code: 9",
  tools=["curl", "requests", "httpx", "node", "openssl"],
  q="Only one machine fails TLS, with 'certificate is not yet valid'. What do you check first?",
  a="That machine's clock: <code>date -u</code> against a trusted source, and whether NTP or chrony is running. 'Not yet valid' means the client's now is before the certificate's notBefore.",
  cause="The certificate's notBefore is tomorrow, which is exactly what a client whose clock is a day behind sees for a certificate issued today.",
  fix="Fix time synchronisation. Freshly issued certificates fail first on machines with drifting clocks.",
  ml="Fresh VMs or containers restored from a snapshot, edge devices without a real-time clock, and laptops after a long suspend; the same skew breaks JWTs (see Auth).",
  sim="Instead of turning this machine's clock back (needs root), the certificate starts tomorrow; to the verifier the two are identical.",
  src=[["RFC 5280 section 4.1.2.5", RFC + "rfc5280#section-4.1.2.5"]]),
dict(id="tls_noaki", t="Python 3.13 rejects a certificate that curl and Node accept", layer="TLS", sym="certificate verify failed: Missing Authority Key Identifier",
  tools=["curl", "requests", "httpx", "node", "openssl"],
  q="After upgrading to Python 3.13, calls to an internal service fail with 'Missing Authority Key Identifier'; curl and Node still work. What do you check first?",
  a="The certificate's extensions: <code>openssl x509 -noout -text</code>. Python 3.13 turned on strict X.509 checking by default (VERIFY_X509_STRICT, in the flags value 557088 printed here), which requires the Authority Key Identifier that RFC 5280 says CA-issued certificates must carry. Older or hand-made internal CAs often omit it.",
  cause="The leaf on port 27453 was issued without the Authority Key Identifier extension. curl (LibreSSL) and Node (OpenSSL) do not insist on it; Python 3.13's default context does.",
  fix="Reissue the certificate (or the CA) with Authority and Subject Key Identifiers. Clearing ssl.VERIFY_X509_STRICT from a context works but weakens checking everywhere that context is used.",
  ml="Internal model gateways, MLflow or vector databases with certificates from an old in-house CA break when a training image moves to Python 3.13.",
  src=[["Python ssl: create_default_context (changed in 3.13)", "https://docs.python.org/3/library/ssl.html#ssl.create_default_context"], ["RFC 5280 section 4.2.1.1 (Authority Key Identifier)", RFC + "rfc5280#section-4.2.1.1"]]),
dict(id="dns_intercept", t="A TLS error caused by DNS: the name was answered by a filter", layer="DNS", sym="unable to get local issuer certificate, for a big public site that works elsewhere",
  tools=["curl", "openssl", "dig"],
  q="On one managed laptop, curl to a well-known public HTTPS site fails with 'unable to get local issuer certificate'. Other machines are fine. What do you check first?",
  a="Who issued the certificate you actually received: <code>openssl s_client -connect host:443 | grep 'i:'</code>. If the issuer is not the site's CA but a filtering or inspection product, your DNS (or a proxy) sent you to a block page or an intercepting device. Then ask which resolver really answers you: <code>dig @1.1.1.1 id.server CH TXT</code> returns a Cloudflare data-centre code only if Cloudflare answered.",
  cause="Recorded on this laptop: its DNS traffic is intercepted by a device-management filter. The name resolves to the filter's block page, whose certificate is issued by the filter's own CA chain (vendor name redacted here), which curl does not trust. A query 'to 1.1.1.1' is answered by a resolver that is not Cloudflare's.",
  fix="Not a certificate problem: use the network's approved path (allow-list the domain, trust the inspection CA if policy says so, or use another network). Never disable verification.",
  ml="Package and model downloads (pip, Hugging Face, container registries) failing only on corporate or managed machines; DNS-over-HTTPS endpoints blocked by policy.",
  sim="Real, on this machine, read-only, against a public name. The filter's vendor, location and resolver name are redacted.",
  src=[["RFC 5280 section 6 (path validation)", RFC + "rfc5280#section-6"], ["Cloudflare: id.server and the data-centre code", "https://developers.cloudflare.com/1.1.1.1/troubleshooting/"]]),
dict(id="tls_alpn", t="ALPN mismatch: gRPC needs h2", layer="TLS", sym="TLSV1_ALERT_NO_APPLICATION_PROTOCOL / Cannot check peer: missing selected ALPN property",
  tools=["grpc", "openssl", "curl"],
  q="A gRPC client fails to connect through a TLS endpoint that serves HTTPS fine to curl. What do you check first?",
  a="What the server negotiates with ALPN: <code>openssl s_client -alpn h2</code> prints 'ALPN protocol: h2' or 'No ALPN negotiated'. gRPC requires HTTP/2, chosen in the TLS handshake by ALPN; curl silently falls back to HTTP/1.1, gRPC cannot.",
  cause="nginx on 27450 has http2 off, so it offers only http/1.1 and rejects a client that offers only h2 with the no_application_protocol alert (RFC 7301 section 3.2). The bare TLS server on 27451 ignores ALPN; gRPC refuses a connection where no protocol was selected.",
  fix="Enable HTTP/2 on the TLS terminator (http2 on in nginx; an HTTP/2-capable listener on cloud load balancers) or terminate TLS somewhere that speaks h2.",
  ml="Serving a model over gRPC (Triton, TF Serving, a custom service) behind an ingress or load balancer configured for HTTP/1.1 only.",
  src=[["RFC 7301 (ALPN)", RFC + "rfc7301"], ["gRPC over HTTP/2 protocol spec", "https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md"]]),
dict(id="tls_mtls", t="mTLS: client certificate missing", layer="TLS", sym="400 No required SSL certificate was sent / tlsv13 alert certificate required / reason(1116)",
  tools=["curl", "requests", "httpx", "node", "openssl"],
  q="Calls to an internal service fail with 'certificate required' or a 400 about a client certificate. What do you check first?",
  a="Whether the server asks for a client certificate and which CAs it accepts: <code>openssl s_client</code> prints 'Acceptable client certificate CA names'. Then whether your client is configured to send a certificate signed by one of them.",
  cause="In mutual TLS the server also verifies the client. nginx completes the handshake and answers HTTP 400; a server that enforces it in the handshake (Python ssl with CERT_REQUIRED here, as Envoy or Go do) sends the TLS 1.3 certificate_required alert (116). LibreSSL 3.3.6, which macOS curl uses, has no name for it and prints reason(1116), which is 1000 + 116.",
  fix="Configure the client certificate and key (curl --cert/--key, requests cert=(cert, key), an Envoy or service-mesh sidecar).",
  ml="Service-mesh (Istio, Linkerd) traffic between a feature store and a model server; a client outside the mesh calling in without the sidecar's certificate.",
  src=[["RFC 8446 section 4.3.2 and 6.2 (certificate_required)", RFC + "rfc8446#section-6.2"], ["nginx ssl_verify_client", "https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client"]]),
# ---------------- HTTP and proxies ----------------
dict(id="http_413", t="413 Content Too Large", layer="HTTP", sym="HTTP 413 Request Entity Too Large (from the proxy, not the API)",
  tools=["curl", "httpx", "node", "nginx log"],
  q="Requests with images fail with 413 but small ones work. What do you check first?",
  a="Which hop answered: the Server header and body (an nginx error page means the proxy, before your app ever saw the request), then that hop's body limit. nginx logs 'client intended to send too large body'.",
  cause="nginx's client_max_body_size is 1k here (its default is 1m); the 2,240-byte request with a base64 image exceeds it.",
  fix="Raise the limit on every hop (proxy, ingress, app server), or send large inputs by reference (upload first, pass an ID or URL).",
  ml="Base64-encoded images, PDFs or audio in vision and speech requests; batch embedding calls; default ingress-nginx limits in Kubernetes.",
  src=[["RFC 9110 section 15.5.14 (413)", RFC + "rfc9110#section-15.5.14"], ["nginx client_max_body_size", "https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size"]]),
dict(id="http_429", t="429 Too Many Requests with Retry-After", layer="HTTP", sym="HTTP 429, retry-after: 2 / rate_limit_error",
  tools=["curl", "httpx", "requests"],
  q="A batch job gets bursts of 429s. What do you check first?",
  a="The response headers: <code>retry-after</code> says how many seconds to wait, and rate-limit headers say which limit you hit. Then whether your client retries with backoff and honours Retry-After, rather than hammering.",
  cause="The lab server allows one request per 2 s; the second call answers 429 with retry-after: 2. The retry script waits exactly that and succeeds at +2.01 s.",
  fix="Honour Retry-After, add jittered exponential backoff, and cap concurrency. Anthropic's API returns a retry-after header with 429s (no retry-after on the spend-cap 429, which retries cannot fix).",
  ml="Evaluation sweeps and synthetic-data generation fanning out hundreds of concurrent calls; tokens-per-minute limits hit by long prompts even at low request rates.",
  src=[["RFC 6585 section 4 (429)", RFC + "rfc6585#section-4"], ["RFC 9110 section 10.2.3 (Retry-After)", RFC + "rfc9110#section-10.2.3"], ["Anthropic: rate limits (retry-after)", "https://platform.claude.com/docs/en/api/rate-limits"]]),
dict(id="http_502", t="502 Bad Gateway", layer="HTTP", sym="HTTP 502 with a proxy's HTML page",
  tools=["curl", "requests", "nginx log"],
  q="Clients get 502 from the gateway. What do you check first?",
  a="The proxy's error log, which names the upstream and why: here 'connect() failed (61: Connection refused) while connecting to upstream'. 502 means the proxy could not get a valid response from the server behind it: down, refusing, resetting, or speaking the wrong protocol.",
  cause="nginx proxies to 127.0.0.1:27099, where nothing listens: a connection refused one hop further in.",
  fix="Fix the upstream (or its address); health checks so the proxy stops sending to dead backends.",
  ml="A model server pod restarting after OOM while the ingress still routes to it; a sidecar that is up before the model is.",
  src=[["RFC 9110 section 15.6.3 (502)", RFC + "rfc9110#section-15.6.3"]]),
dict(id="http_504", t="504 Gateway Timeout", layer="HTTP", sym="HTTP 504 after exactly the proxy's timeout",
  tools=["curl", "httpx", "nginx log"],
  q="Long requests fail with 504 after a suspiciously round number of seconds. What do you check first?",
  a="The proxy's timeouts against the request's real duration. A round number (3 s here; 60 s is nginx's default proxy_read_timeout, many cloud load balancers default to 60 s too) is a timer, not the application. nginx logs 'upstream timed out ... while reading response header from upstream'.",
  cause="The upstream accepts and never answers; nginx gives up after proxy_read_timeout 3s.",
  fix="Raise the timeout on every hop for legitimately long work, or stream (headers and first bytes early), or make it asynchronous (202 plus a job ID, or a webhook).",
  ml="Non-streaming generation of long outputs, which can take minutes before the first byte; batch inference behind an API gateway with a fixed 30 or 60 s limit.",
  src=[["RFC 9110 section 15.6.5 (504)", RFC + "rfc9110#section-15.6.5"], ["nginx proxy_read_timeout", NGX + "#proxy_read_timeout"]]),
dict(id="sse_cut", t="Idle timeout cuts an SSE stream mid-answer", layer="HTTP", sym="curl: (18) transfer closed with outstanding read data remaining / incomplete chunked read / TypeError: terminated",
  tools=["curl", "httpx", "node", "nginx log"],
  q="Streaming answers stop after one or two tokens, always about the same time after the last token. What do you check first?",
  a="The longest silence in the stream against every idle timeout on the path. A proxy's read timeout is between two reads, not for the whole response, so a pause (a tool call, long thinking) longer than it kills the stream. nginx logs 'upstream timed out ... while reading upstream'.",
  cause="The upstream pauses 2.5 s between tokens; nginx's proxy_read_timeout is 2 s, so after 'The' nginx closes the connection without the final empty chunk, and every client reports a truncated body.",
  fix="Send heartbeats (SSE comment lines ':' or ping events) more often than the shortest idle timeout, and raise the timeouts. The WHATWG spec suggests a comment every 15 s or so for this reason; Anthropic's stream may include ping events. The last run (timeout 10 s) completes.",
  ml="An agent's stream dying while the model runs a slow tool; reasoning models that think silently for a minute behind a 60 s load-balancer idle timeout.",
  src=[["WHATWG HTML: server-sent events (keep-alive comments)", "https://html.spec.whatwg.org/multipage/server-sent-events.html#authoring-notes"], ["nginx proxy_read_timeout", NGX + "#proxy_read_timeout"], ["Anthropic: streaming (ping events)", "https://platform.claude.com/docs/en/build-with-claude/streaming"]]),
dict(id="buffering", t="A buffering proxy delays tokens", layer="HTTP", sym="all tokens arrive at once at the end; time to first token equals total time",
  tools=["httpx (timed)", "nginx"],
  q="Streaming works when you call the model server directly, but through the gateway every token arrives at once at the end. What do you check first?",
  a="Time the events through each hop (the timed client here prints each event's arrival). Then look for anything that holds the body: proxy response buffering, compression (gzip holds bytes until it has enough to compress), an HTTP/1.0 hop.",
  cause="Measured with nginx 1.31.6: with proxy_http_version 1.1 the default buffering did not delay these events; with gzip on and buffering on, or with HTTP/1.0 to the upstream and buffering on, all eight events arrived together at +0.36 s instead of spread from +0.03 s. With buffering off, gzip did not delay them.",
  fix="Turn buffering off for streaming routes (proxy_buffering off, or the upstream sends X-Accel-Buffering: no), exclude text/event-stream from compression, and use HTTP/1.1 to upstreams (nginx's default since 1.29.7; it was 1.0 before).",
  ml="A streaming chat UI that 'freezes then dumps' the answer: users see time to first token equal to total latency.",
  src=[["nginx proxy_buffering and X-Accel-Buffering", NGX + "#proxy_buffering"], ["nginx 1.29.7 changelog (proxy_http_version 1.1 default)", "https://nginx.org/en/CHANGES"]]),
dict(id="keepalive", t="Reused keep-alive connection closed by the server", layer="HTTP", sym="RemoteDisconnected('Remote end closed connection without response') on a reused connection",
  tools=["requests", "curl"],
  q="Sporadic 'Remote end closed connection without response' errors, only on the second or later request of a session, more often after idle periods. What do you check first?",
  a="The server's (or load balancer's) keep-alive idle timeout against the client pool's: if the server closes idle connections first, a request sent on one at that moment is lost. curl -v shows 'Connection died, retrying a fresh connect'.",
  cause="The server answers the first request, then reads the second on the same connection and hangs up without answering, as a server does when its keep-alive timer fires as the request arrives. requests does not retry a POST; curl detected it and retried on a new connection.",
  fix="Make the client's idle timeout shorter than the server's, enable retries for idempotent requests, and use idempotency keys so non-idempotent POSTs can be retried safely.",
  ml="Long-running eval scripts that reuse a requests.Session to a model gateway behind a cloud load balancer and fail every few hundred calls.",
  sim="The race is made deterministic: the toy server always hangs up on the second request instead of only when its timer fires at that instant.",
  src=[["RFC 9112 section 9.5 (closing a persistent connection)", RFC + "rfc9112#section-9.5"], ["urllib3 Retry", "https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html"]]),
dict(id="short_body", t="Body shorter than Content-Length", layer="HTTP", sym="transfer closed with 50 bytes remaining / IncompleteRead / RemoteProtocolError",
  tools=["curl", "requests", "httpx", "node"],
  q="A download of model weights ends with 'IncompleteRead' or 'bytes remaining to read'. What do you check first?",
  a="Content-Length (or the chunked framing) against the bytes received, then who closed the connection early: a proxy timeout, a crashed backend, a size limit. The client is right to fail: the framing promised more.",
  cause="The server declares content-length: 100, sends 50 bytes and closes.",
  fix="Find what truncates; resume large downloads with Range requests and verify a checksum.",
  ml="Truncated safetensors or dataset shards from flaky mirrors or proxies; always verify hashes (Hugging Face exposes them) before loading.",
  src=[["RFC 9112 section 8 (incomplete messages)", RFC + "rfc9112#section-8"]]),

# ---------------- HTTP/2, gRPC and TCP performance ----------------
dict(id="grpc_pinning", t="gRPC behind an L4 load balancer: one backend takes everything", layer="HTTP/2", sym="one replica at 100% while the others idle; adding replicas does not help",
  tools=["grpc", "nginx stream"],
  q="You scaled a gRPC model service from 1 to 3 replicas behind a TCP load balancer; one replica still gets all the traffic. What do you check first?",
  a="Whether the balancer works per connection (L4, TCP) or per request (L7, HTTP/2-aware). gRPC keeps one long-lived HTTP/2 connection per channel and multiplexes every call on it, so an L4 balancer makes one choice per client, once.",
  cause="nginx's stream module balances TCP connections round-robin. One channel opens one connection, so all 30 calls land on backend-1; three separate processes open three connections and spread 10/10/10; client-side round_robin over the three addresses spreads 9/10/11.",
  fix="Use an L7 balancer that understands HTTP/2 (Envoy, nginx grpc_pass, a service mesh, cloud HTTP/2 load balancers), or client-side balancing with a headless Service, or periodic connection recycling (max connection age).",
  ml="A Triton or custom gRPC inference fleet on Kubernetes behind a plain ClusterIP Service: new replicas stay cold until clients reconnect.",
  src=[["gRPC blog: gRPC load balancing (2017)", "https://grpc.io/blog/grpc-load-balancing/"], ["nginx stream upstream", "https://nginx.org/en/docs/stream/ngx_stream_upstream_module.html"]]),
dict(id="max_streams", t="Max concurrent streams: calls queue on the connection", layer="HTTP/2", sym="latency in steps (1 s, 2 s, 3 s) under concurrency; DEADLINE_EXCEEDED for some calls",
  tools=["grpc"],
  q="Six concurrent 1-second gRPC calls take 1, 2 and 3 seconds, in pairs, and some hit their deadline. What do you check first?",
  a="SETTINGS_MAX_CONCURRENT_STREAMS on the server (and any client-side limit): HTTP/2 lets a server cap streams per connection; calls beyond the cap wait for a free stream on that connection.",
  cause="The server advertises max_concurrent_streams 2, so the six calls run two at a time: two finish at 1 s, two at 2 s, two at 3 s. With a 2.5 s deadline the last two fail with DEADLINE_EXCEEDED although the server never saw them fail.",
  fix="Raise the limit if the server can take more, open more connections (channel pools), or spread over more servers; deadlines should include queueing time.",
  ml="Batching inference servers that set a low stream limit to protect GPU memory; clients see tail latency grow with concurrency on a single channel.",
  src=[["RFC 9113 section 6.5.2 (SETTINGS_MAX_CONCURRENT_STREAMS)", RFC + "rfc9113#section-6.5.2"], ["gRPC core channel arguments", "https://grpc.github.io/grpc/core/group__grpc__arg__keys.html"]]),
dict(id="window_rtt", t="One stream's throughput is capped at window / round trip", layer="TCP", sym="a single download crawls on a long link while the link is idle; parallel downloads go faster",
  tools=["h2 client (timed)", "delay proxy"],
  q="Copying a checkpoint across regions over one connection runs at a few MB/s on a 10 Gbit/s link. What do you check first?",
  a="The round-trip time (ping) and the window: at most one window of data can be unacknowledged per round trip, so throughput is at most window / RTT. Check the TCP buffer limits (net.ipv4.tcp_rmem on Linux, autorcvbufmax on macOS) and any protocol window on top (HTTP/2, gRPC, QUIC).",
  cause="The table and chart measure HTTP/2's flow-control window, which works like TCP's receive window one layer up: a 64 KB window over a 100 ms round trip gives 0.61 MB/s; 4 MB gives 36.5 MB/s. Measured values are 70 to 95% of window / RTT, the rest being slow-start round trips and per-frame overhead.",
  fix="Larger windows (autotuning, raised buffer limits; gRPC's BDP probing does this for its HTTP/2 windows), or several parallel streams; for big transfers use tools built for it (parallel range requests, multipart uploads).",
  ml="Pulling weights from object storage in another region; NCCL or gRPC between data centres; one-stream rsync of a dataset over a VPN.",
  sim="RTT comes from a userspace delay proxy, which cannot hold back the kernel's own TCP acknowledgements, so TCP's window is not what it limits here; HTTP/2's window, which lives above it, feels the full round trip.",
  src=[["RFC 9113 section 6.9 (flow control, initial window 65,535)", RFC + "rfc9113#section-6.9"], ["RFC 7323 (TCP window scaling)", RFC + "rfc7323"]]),
dict(id="nagle", t="Nagle plus delayed ACK (not reproduced on macOS loopback)", layer="TCP", sym="small requests take about 40 ms (Linux) instead of under 1 ms; only when a request is sent in two writes",
  tools=["socket probe"],
  q="Small RPCs take a steady 40 ms on Linux, but only from one client library that writes the header and body separately. What do you check first?",
  a="Whether the client sets TCP_NODELAY. Nagle's algorithm holds the second small write until the first is acknowledged; the receiver delays its ACK hoping to piggy-back it on a reply; the reply needs the second write. They wait for each other until the delayed-ACK timer fires.",
  cause="On this machine the effect did not appear: 400 write-write-read requests took a median 0.05 ms with Nagle on or off. macOS acknowledged at once on loopback (net.inet.tcp.delayed_ack=3 is its adaptive mode). On Linux the minimum delayed-ACK timeout is 40 ms (TCP_DELACK_MIN in the kernel), which is the classic symptom.",
  fix="Set TCP_NODELAY (most HTTP and RPC libraries do), or write each message in one call.",
  ml="Hand-written socket protocols for parameter servers or custom inference RPCs; older clients that send headers and body in separate writes.",
  sim="Measured, but the failure did not reproduce here; the Linux 40 ms figure is from the kernel source, not from this run.",
  src=[["RFC 896 (Nagle's algorithm)", RFC + "rfc896"], ["RFC 1122 section 4.2.3.2 (delayed ACK, at most 0.5 s)", RFC + "rfc1122#section-4.2.3.2"], ["Linux include/net/tcp.h (TCP_DELACK_MIN = HZ/25)", "https://github.com/torvalds/linux/blob/master/include/net/tcp.h"]]),
# ---------------- Auth ----------------
dict(id="jwt_expired", t="Expired JWT", layer="Auth", sym="401, WWW-Authenticate: Bearer error=\"invalid_token\", error_description=\"Signature has expired\"",
  tools=["curl", "PyJWT"],
  q="An agent works for an hour, then every call gets 401 invalid_token. What do you check first?",
  a="The token's exp claim against now: decode the payload (it is only base64; jwt_peek.py does it) and compare. A failure exactly one token lifetime after start means the client never refreshes.",
  cause="exp is 400 s in the past; the gateway checks exp with zero leeway and rejects, saying so in WWW-Authenticate as RFC 6750 section 3 specifies.",
  fix="Refresh before expiry (refresh token or client-credentials grant), and retry once on 401 after refreshing.",
  ml="Long training or eval jobs holding a token fetched at start-up to write to a model registry, an experiment tracker or object storage.",
  src=[["RFC 7519 section 4.1.4 (exp)", RFC + "rfc7519#section-4.1.4"], ["RFC 6750 section 3 (WWW-Authenticate errors)", RFC + "rfc6750#section-3"]]),
dict(id="jwt_audience", t="Wrong audience", layer="Auth", sym="401 invalid_token, Audience doesn't match",
  tools=["curl", "PyJWT"],
  q="A token that works on one internal API is rejected by another with 'audience'. What do you check first?",
  a="The aud claim: it names the API the token is for, and each API must accept only tokens minted for itself. Request a token for the right audience (resource indicator).",
  cause="aud is https://other-api.lab.test; the gateway requires https://api.llm.test.",
  fix="Ask the authorization server for a token for this API (OAuth resource indicators, RFC 8707; MCP requires them for remote servers). Never disable the audience check.",
  ml="An agent reusing one access token across tools: audience checks are what stop a token stolen by one tool server from being replayed against another (the MCP spec forbids token passthrough for this reason).",
  src=[["RFC 7519 section 4.1.3 (aud)", RFC + "rfc7519#section-4.1.3"], ["RFC 8707 (resource indicators)", RFC + "rfc8707"], ["MCP authorization: token audience", "https://modelcontextprotocol.io/specification/2025-11-25/basic/authorization"]]),
dict(id="jwt_clock", t="Clock skew: token not yet valid", layer="Auth", sym="401 invalid_token, The token is not yet valid (iat)",
  tools=["curl", "PyJWT"],
  q="Freshly issued tokens are rejected as 'not yet valid' by one server only. What do you check first?",
  a="The clocks of the issuer and that server (date -u on both, NTP status). iat or nbf in the server's future means one clock is off.",
  cause="The token's iat and nbf are 300 s ahead of the gateway's clock, as if the issuer's clock ran 5 minutes fast; zero leeway rejects it.",
  fix="Fix time sync; allow a small leeway (RFC 7519 says 'some small leeway, usually no more than a few minutes').",
  ml="Edge devices and freshly booted VMs; the same skew breaks TLS (see Clock skew in TLS).",
  sim="The issuer's clock is simulated by minting iat and nbf 300 s ahead.",
  src=[["RFC 7519 section 4.1.5 (nbf, leeway)", RFC + "rfc7519#section-4.1.5"]]),
dict(id="jwt_alg", t="Algorithm confusion rejected", layer="Auth", sym="401 invalid_token, The specified alg value is not allowed",
  tools=["curl", "PyJWT", "base64"],
  q="Your security review asks: what stops someone from sending a token with alg 'none', or an HS256 token signed with your public key? What do you check?",
  a="That the verifier pins the algorithm list (algorithms=['RS256']) and the key type, and never takes the algorithm from the token's own header. The header is attacker-controlled input.",
  cause="Two forgeries: an unsigned token (header {\"alg\":\"none\"}) and an HS256 token whose HMAC key is the issuer's public RSA key (the classic confusion: a verifier that trusts the header would check it with that same public key and accept). The gateway allows only RS256 and rejects both; PyJWT also refuses to use a PEM public key as an HMAC secret.",
  fix="Pin algorithms and keys per issuer (RFC 8725 section 3.1); use maintained libraries.",
  ml="Hand-rolled token checks in internal ML platforms and agent tool servers.",
  src=[["RFC 8725 sections 2.1 and 3.1 (JWT BCP)", RFC + "rfc8725"], ["PyJWT: algorithms", "https://pyjwt.readthedocs.io/en/stable/algorithms.html"]]),
dict(id="jwt_scope", t="Missing scope: authenticated but not allowed", layer="Auth", sym="403, WWW-Authenticate: Bearer error=\"insufficient_scope\"",
  tools=["curl", "PyJWT"],
  q="A valid token gets 403 rather than 401. What do you check first?",
  a="401 means 'who are you?' (no or bad credentials); 403 means 'I know who you are, and you may not'. Read the scope claim and the error: insufficient_scope names the scope required.",
  cause="The token carries scope messages:read; the endpoint needs messages:write.",
  fix="Request the scope (and get consent for it); grant least privilege per tool or agent.",
  ml="An agent given a read-only token trying to write results back; MCP servers answering insufficient_scope so the client can step up its authorization.",
  src=[["RFC 6750 section 3.1 (insufficient_scope, 403)", RFC + "rfc6750#section-3.1"]]),
dict(id="oauth_redirect", t="OAuth redirect URI mismatch", layer="Auth", sym="400 invalid_request: redirect_uri does not match a registered URI (the browser shows an error page, no redirect)",
  tools=["curl"],
  q="A CLI's OAuth login opens the browser and stops on an authorization-server error about redirect_uri. What do you check first?",
  a="The redirect_uri the client sent, character by character, against the registered list: scheme, host (localhost is not 127.0.0.1), port, path, trailing slash. Servers must compare exactly.",
  cause="Registered: http://127.0.0.1:8765/callback. localhost and a trailing slash are rejected; a different port on the loopback address is accepted, as RFC 8252 requires for native apps that pick a free port.",
  fix="Register the exact URI the client sends (or make the client send the registered one).",
  ml="Agent CLIs and MCP clients doing OAuth with a local callback server.",
  sim="The authorization server is the lab's own (auth_server.py) implementing the RFC rules; its error wording is ours, not any vendor's.",
  src=[["RFC 9700 section 2.1 (exact redirect matching)", RFC + "rfc9700#section-2.1"], ["RFC 8252 section 7.3 (loopback ports)", RFC + "rfc8252#section-7.3"], ["RFC 6749 section 4.1.2.1 (do not redirect on mismatch)", RFC + "rfc6749#section-4.1.2.1"]]),
# ---------------- Agent protocols ----------------
dict(id="mcp_stdout", t="MCP over stdio: stdout pollution", layer="Agent", sym="ValidationError: Invalid JSON ... input_value='[debug] ...' then the call times out",
  tools=["MCP client", "raw bytes"],
  q="An MCP tool works when you run it by hand but the client hangs until timeout on one tool call. What do you check first?",
  a="What the server writes to stdout: run it with the client's messages piped in and look at the raw lines. On the stdio transport stdout is the protocol channel, one JSON-RPC message per line; anything else corrupts it.",
  cause="Two servers. The SDK server prints one line before mcp.run(): the client logs a parse error and skips that line (while serving, the Python SDK points file descriptor 1 at stderr, so prints inside tools are safe). The hand-rolled server prints a fragment without a newline inside its tool, which glues onto the response; the whole line fails to parse, the response is lost and the call times out after 5 s.",
  fix="Log to stderr (the spec allows stderr for logs); never print to stdout in a stdio server; check libraries and subprocesses that inherit stdout.",
  ml="Tool servers that load a model or tokenizer and print progress; libraries that print warnings to stdout.",
  src=[MCPT, ["python-sdk issue #1933 (stdout diversion)", "https://github.com/modelcontextprotocol/python-sdk/issues/1933"]]),
dict(id="mcp_session", t="MCP Streamable HTTP: session expired", layer="Agent", sym="HTTP 404 {\"code\":-32600,\"message\":\"Session not found\"}",
  tools=["curl", "MCP server"],
  q="A remote MCP server works, then after a quiet period every request returns 404. What do you check first?",
  a="Whether the requests carry an Mcp-Session-Id the server no longer knows (expired, or the server restarted or is a different replica). The spec says the server must then answer 404 and the client must start a new session with a fresh initialize.",
  cause="The server expires sessions after 3 s idle (session_idle_timeout); tools/list right away is 200, after 5 s it is 404 'Session not found'.",
  fix="Clients: on 404 with a session ID, re-initialize. Servers behind several replicas: sticky routing or a shared session store, or stateless mode.",
  ml="Agents that keep an MCP connection across long model calls; autoscaled MCP servers where a request reaches a replica that never saw the session.",
  src=[MCPT, ["MCP python-sdk (session_idle_timeout)", "https://github.com/modelcontextprotocol/python-sdk"]]),
dict(id="prompt_injection", t="A tool result that carries an injected instruction", layer="Agent", sym="the agent does something nobody asked for after reading a web page, file or issue",
  tools=["MCP raw bytes", "MCP client"],
  q="After summarising a web page, an agent tried to call an email tool nobody mentioned. What do you check first?",
  a="The tool results in the transcript: injected text arrives as ordinary data inside a tool result, byte-for-byte indistinguishable from content. Then which tools the agent could call with which permissions after reading untrusted input.",
  cause="The fetch_page tool returns a page whose HTML comment tells 'the AI assistant' to email ~/.netrc to an outside address. On the wire it is just a string in result.content[0].text; nothing in the protocol marks it as untrusted. Nothing in this lab acts on it.",
  fix="Treat every tool result as untrusted input: least privilege per tool, no secrets in reach, human confirmation for consequential actions (sending, deleting, paying), and do not let data from one tool choose the arguments of another without checks.",
  ml="Coding agents reading issues and READMEs, research agents browsing, RAG over user-uploaded documents.",
  src=[["MCP spec: security best practices", "https://modelcontextprotocol.io/specification/2025-11-25/basic/security_best_practices"], ["OWASP Top 10 for LLM applications: LLM01 prompt injection", "https://genai.owasp.org/llmrisk/llm01-prompt-injection/"]]),
]
