"""Merge the three measurement runs, the Triton results and the kernel sources into the page's data file.
Writes ../out/data.json and ../../parts/33_js_lab_0data.js (window.LABD). Run from anywhere."""
import json, os, re, sys, statistics
HERE = os.path.dirname(os.path.abspath(__file__))
LAB = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import k_softmax as KS, k_matmul as KM, k_fused as KF

runs = [json.load(open(os.path.join(LAB, "out", f"run_{i}.json"))) for i in (1, 2, 3)]
order, merged = [], {}
for r in runs:
    for c in r["cases"]:
        k = c["name"]
        if k not in merged:
            order.append(k); merged[k] = []
        merged[k].append(c)
cases = []
for k in order:
    cs = merged[k]
    assert len(cs) == 3, k
    base = {x: cs[0][x] for x in cs[0] if x not in ("median_s", "min_s", "max_s", "trials", "reps", "load", "max_abs_err", "peak_bytes")}
    run_ms = [round(c["median_s"] * 1e3, 4) for c in cs]
    errs = [c["max_abs_err"] for c in cs if c["max_abs_err"] is not None]
    base.update(ms=round(statistics.median(run_ms), 4), ms_min=round(min(c["min_s"] for c in cs) * 1e3, 4),
                ms_max=round(max(c["max_s"] for c in cs) * 1e3, 4), run_ms=run_ms, load=[c["load"] for c in cs],
                reps=[c["reps"] for c in cs], err=max(errs) if errs else None,
                peak_mib=round(max(c["peak_bytes"] for c in cs) / 2 ** 20, 1))
    cases.append(base)

ti = json.load(open(os.path.join(LAB, "out", "triton_interp.json")))
tc = json.load(open(os.path.join(LAB, "out", "triton_compile.json")))
tcomp = {}
for key, r in tc["results"].items():
    if r.get("ok"):
        tcomp[key] = {x: r[x] for x in ("kernel", "arch", "num_warps", "regs", "shared_meta", "ptx_lines", "sass_instructions", "sass", "ptx", "constexprs")}

src = open(os.path.join(LAB, "triton", "lab_tl.py")).read()
tsrc = {}
for blk in src.split("@triton.jit\n")[1:]:
    name = re.match(r"def (\w+)", blk).group(1)
    tsrc[name] = "@triton.jit\n" + blk.rstrip() + "\n"
metal = {"S1": KS.S1_NAIVE, "S2": KS.S2_COALESCED, "S3": KS.S3_SIMD, "S4": KS.S4_VEC, "S5": KS.S5_ONLINE, "S6": KS.S6_ONCHIP,
         "M1": KM.M1_UNCOALESCED, "M2": KM.M2_COALESCED, "M3": KM.M3_TILED, "M5": KM.M5_REG4, "M6": KM.M6_REG8_VEC,
         "M7a": KM.M7A_SIMDMAT_DEVICE, "M7": KM.M7_SIMDMAT, "FUSED": KF.FUSED_SMM, "FLASH": KF.FLASH_ATTN}
metal = {k: v.strip("\n") + "\n" for k, v in metal.items()}
cver = json.load(open(os.path.join(LAB, "..", "compile", "out", "versions.json")))
m0 = runs[0]["meta"]
meta = {"date": m0["date"][:10], "mlx": m0["mlx"], "numpy": m0["numpy"], "python": m0["python"], "device": m0["device"],
        "arch": m0["arch"], "memory_gb": round(m0["memory_bytes"] / 2 ** 30), "runs": 3, "trials": 7,
        "run_dates": [r["meta"]["date"] for r in runs],
        "load_range": [round(min(min(r["meta"]["load_start"][0], r["meta"]["load_end"][0]) for r in runs), 1),
                       round(max(max(r["meta"]["load_start"][0], r["meta"]["load_end"][0]) for r in runs), 1)],
        "triton": ti["triton"], "torch": ti["torch"], "image": cver["image"], "image_id": cver["image_id"][:19],
        "cuda_toolkit": cver["cuda_toolkit"], "triton_ptxas": cver["triton_ptxas"]}
# the hardware root's Roofline lab (same machine, same day): the ceilings this tab measures against
rf = json.load(open(os.path.join(LAB, "..", "..", "..", "topic_hardware", "src", "roof", "out", "data.json")))
byname = {c["name"]: c for c in rf["cases"]}
pick = lambda n, f: round(byname[n][f], 1)
roof = {"peak_fp32_gf": pick("peak FMA fp32 (custom Metal kernel)", "gf"), "peak_fp16_gf": pick("peak FMA fp16 (custom Metal kernel)", "gf"),
        "copy_gbs": pick("stream copy (512 MB in, 512 MB out)", "gbs"), "softmax_gbs": pick("softmax over rows (fp32, 16384 x 4096)", "gbs"),
        "naive_gf": pick("matmul naive, custom (fp32, 2048)", "gf"), "tiled_gf": pick("matmul tiled 16x16, custom (fp32, 2048)", "gf"),
        "mlx_gf": pick("matmul MLX library (fp32, 2048)", "gf"), "date": rf["meta"]["date"]}
data = {"meta": meta, "roof": roof, "cases": cases, "interp": ti["checks"], "tcomp": tcomp, "tsrc": tsrc, "metal": metal}
json.dump(data, open(os.path.join(LAB, "out", "data.json"), "w"), indent=1)
js = "// Generated by src/lab/code/gen_data.py from src/lab/out/. Do not edit.\nwindow.LABD=" + json.dumps(data, separators=(",", ":")) + ";\n"
open(os.path.join(LAB, "..", "parts", "33_js_lab_0data.js"), "w").write(js)
print("cases", len(cases), "bytes", len(js))
