"""Build the Toolchain atlas data: src/tools/atlas.json and parts/33_js_data.js.

Versions come from research/versions_raw.json, versions_extra.json and timeline_raw.json
(fetched by research/fetch_versions.py and fetch_timeline.py on 2026-10-05), referenced by key,
so a version shown on the page is never typed by hand when a registry or release feed has it.
Facts with no registry (compiler releases, schedules) carry their own URL and date in cells_*.py.
Run: python3 build_data.py   (no network; fails loudly on a missing key)."""
import json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
CHECKED = "2026-10-05"
R = json.load(open(os.path.join(HERE, "research/versions_raw.json")))
X = json.load(open(os.path.join(HERE, "research/versions_extra.json")))

def gh_entry(repo, idx=0):
    e = R["gh:" + repo]["entries"][idx]
    return e

def resolve(spec):
    """spec: 'pypi:name' | 'crate:name' | 'npm:name' | 'gh:owner/repo#i' | dict(version,date,url)."""
    if isinstance(spec, dict):
        assert {"version", "date", "url"} <= set(spec), spec
        return dict(spec)
    if spec.startswith("x:"):
        k = spec[2:]; d = X[k]
        if k.startswith("gh:"):
            t, date, link = d[0]
            return {"version": re.sub(r"^v(?=\d)", "", t.split(" ")[0]), "date": date, "url": link, "src": "GitHub release"}
        return {**d, "src": {"pypi": "PyPI", "crate": "crates.io"}[k.split(":")[0]]}
    kind, _, name = spec.partition(":")
    if kind in ("pypi", "crate", "npm"):
        d = R[f"{kind}:{name}"]
        if "error" in d: raise SystemExit(f"missing {spec}")
        src = {"pypi": "PyPI", "crate": "crates.io", "npm": "npm registry"}[kind]
        return {"version": d["version"], "date": d["date"], "url": d["url"], "src": src}
    if kind == "gh":
        repo, _, i = name.partition("#")
        e = gh_entry(repo, int(i or 0))
        v = re.sub(r"^(Release |Version |Published |Bun |Biome CLI |PyO3 |LLVM |TypeScript |pnpm |Rust |Doxygen release )", "", e["title"])
        v = re.sub(r"^v(?=\d)", "", v).split(" ")[0]
        return {"version": v, "date": e["date"], "url": e["link"], "src": "GitHub release"}
    raise SystemExit(f"bad spec {spec}")

from cells_a import CELLS_A
from cells_b import CELLS_B
from cells_c import CELLS_C
from meta import LANGS, JOBS, TIMELINE, NOTES
from walks import WALKS, EXTRA

cells = {}
for part in (CELLS_A, CELLS_B, CELLS_C):
    for job, row in part.items():
        cells[job] = row
missing = [j["id"] for j in JOBS if j["id"] not in cells]
if missing: raise SystemExit(f"jobs without cells: {missing}")
out_cells = {}
n_tools = 0
for job, row in cells.items():
    out_cells[job] = {}
    for lang in LANGS:
        c = row[lang["id"]]
        tools = []
        for t in c["tools"]:
            t = dict(t)
            if "vs" in t:
                parts = []
                for label, spec in t.pop("vs"):
                    r = {"version": "ships with Python", "date": "", "url": ""} if spec == "python" else resolve(spec)
                    parts.append({"label": label, **r})
                t["parts"] = parts
                t["version"] = "; ".join(f"{p['label']} {p['version']}" for p in parts)
                t["date"] = max(p["date"] for p in parts)
                t["url"] = next(p["url"] for p in parts if p["url"])
            elif "v" in t:
                t.update(resolve(t.pop("v")))
            elif "ships" in t:
                t["version"] = "ships with " + t.pop("ships")
            for k in ("n", "what", "cmd"):
                if k not in t: raise SystemExit(f"{job}/{lang['id']} tool lacks {k}: {t}")
            tools.append(t); n_tools += 1
        out_cells[job][lang["id"]] = {**{k: v for k, v in c.items() if k != "tools"}, "tools": tools}

# corrections table from corrections.md (markdown links become [text](url) pairs, rendered by the page)
corr = []
for line in open(os.path.join(HERE, "corrections.md")):
    if not re.match(r"^\| \d+ \|", line): continue
    c = [x.strip() for x in line.strip().strip("|").split(" | ")]
    corr.append({"n": int(c[0]), "page": c[1], "old": c[2], "verdict": c[3], "now": c[4], "src": c[5]})
data = {"corrections": corr, "checked": CHECKED, "langs": LANGS, "jobs": JOBS, "cells": out_cells, "walks": WALKS,
        "timeline": TIMELINE, "notes": NOTES, "extra": EXTRA}
txt = json.dumps(data, ensure_ascii=False, indent=1)
if "\u2014" in txt: raise SystemExit("em dash in data")
open(os.path.join(HERE, "atlas.json"), "w").write(txt)
js = "/* generated by src/tools/build_data.py; do not edit by hand */\nwindow.TA_DATA=" + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
open(os.path.join(HERE, "../parts/33_js_0data.js"), "w").write(js)
print(f"jobs {len(JOBS)}, langs {len(LANGS)}, tools {n_tools}, timeline {sum(len(t['items']) for t in TIMELINE)}, js {len(js)} bytes")
