# Pack the page's data into parts/31_js_data.js (window.CD). Run from src/: python3 data/mk_data.py
import json, csv, re
D = json.load(open("inputs/datasets.json"))
S = json.load(open("inputs/svm_digits_surface.json"))
def lb(path):
    out = []
    for r in csv.DictReader(open(path, encoding="utf-8")):
        m = re.match(r"\[(.*)\]\((.*)\)", r["Model"]); name, url = (m.group(1), m.group(2)) if m else (r["Model"], "")
        reg = "default" if "(default)" in name else ("tuned + ensembled" if "ensembled" in name else "tuned")
        base = re.sub(r"\s*\((default|tuned|tuned \+ ensembled)\)", "", name).replace("[15.49% IMPUTED]", "").replace("[14.65% IMPUTED]", "").strip()
        up, dn = re.match(r"\+(\d+)/-(\d+)", r["Elo 95% CI"]).groups()
        out.append([base, r["TypeName"], reg, float(r["Elo [⬆️]"]), int(up), int(dn), float(r["Median Train Time (s/1K) [⬇️]"] or 0), r["Hardware"], r["License"], float(r["Imputed (%) [⬇️]"] or 0), url])
    return out
T = {"ta_all": lb("inputs/tabarena/lb_all.csv"), "ta_small": lb("inputs/tabarena/lb_small.csv"), "ta_medium": lb("inputs/tabarena/lb_medium.csv")}
for s in ["tiny", "small", "medium", "large", "all"]:
    T["ba_" + s] = lb(f"inputs/tabarena/ba_{s}.csv")
CD = {"lab": D["lab"], "mcycle": D["mcycle"], "faithful": D["faithful"], "wine": D["wine"], "cmoons": D["cmoons"], "cblobs": D["cblobs"], "c6": D["c6"],
      "bo": json.load(open("inputs/recompute.json"))["bo_best_by_budget"], "surf": {"lc": S["log2C"], "lg": S["log2gamma"], "acc": S["acc"]}, "tab": T}
open("parts/31_js_data.js", "w").write("// generated by data/mk_data.py from inputs/\nwindow.CD=" + json.dumps(CD, separators=(",", ":")) + ";\n")
print(len(open("parts/31_js_data.js").read()))
