#!/bin/sh
# Assemble ../index.html from parts/: head and CSS, the HTML parts in order, then the scripts (one <script> each), tabs last.
# Links in any part are written {{text|url}}; url may be an alias (@name, below) or n:<notion id>.
# They expand to <a href="url" target="_blank" rel="noopener noreferrer">text</a>.
# parts/13a_tl_data.js is generated by mk_data.py from src/.
cd "$(dirname "$0")"
{ cat parts/00_top.html parts/01_css.html parts/02_header.html parts/03_read_a.html parts/04_read_b.html parts/06_tabs.html parts/07_more.html
  echo '<div id="jsErr" hidden style="margin:12px 0;padding:10px 12px;border:1px solid #c2703a;border-radius:8px;font:13px/1.5 ui-monospace,Menlo,monospace;white-space:pre-wrap"></div>'
  cat parts/05z_errbox.js.html
  for f in parts/10_js_common.js parts/13a_tl_data.js parts/11_js_flow.js parts/12_js_read.js parts/14_js_log.js parts/15_js_mix.js parts/90_js_tabs.js; do echo "<script>/* $(basename $f) */"; cat "$f"; echo '</script>'; done
  echo '</div></body></html>'; } | perl -CSD -pe '
BEGIN{%A=(
o3r=>"https://arxiv.org/abs/2512.13961",
o3b=>"https://allenai.org/blog/olmo3",
o2r=>"https://arxiv.org/abs/2501.00656",
o232=>"https://allenai.org/blog/olmo2-32B",
o1=>"https://arxiv.org/abs/2402.00838",
dolma=>"https://arxiv.org/abs/2402.00159",
olmoe=>"https://arxiv.org/abs/2409.02060",
molmo=>"https://arxiv.org/abs/2409.17146",
molmo2=>"https://allenai.org/blog/molmo2",
tulu=>"https://arxiv.org/abs/2411.15124",
ladder=>"https://arxiv.org/abs/2412.04403",
ettin=>"https://arxiv.org/abs/2507.11412",
hyb=>"https://allenai.org/blog/olmohybrid",
flex=>"https://allenai.org/blog/flexolmo",
qwen3=>"https://qwenlm.github.io/blog/qwen3/",
ic=>"https://www.interconnects.ai/p/olmo-3-americas-truly-open-reasoning",
icpod=>"https://www.interconnects.ai/p/olmo-2-pod",
rasch=>"https://magazine.sebastianraschka.com/p/the-big-llm-architecture-comparison",
hf=>"https://huggingface.co/allenai",
hf32ref=>"https://huggingface.co/api/models/allenai/Olmo-3-1125-32B/refs",
hf7ref=>"https://huggingface.co/api/models/allenai/Olmo-3-1025-7B/refs",
wbent=>"https://wandb.ai/ai2-llm",
wb32=>"https://wandb.ai/ai2-llm/Olmo-3-1125-32B",
wb7=>"https://wandb.ai/ai2-llm/Olmo-3-1025-7B",
wbo1=>"https://wandb.ai/ai2-llm/OLMo-7B",
wbo2=>"https://wandb.ai/ai2-llm/OLMo-2-1124-7B",
ocore=>"https://github.com/allenai/OLMo-core",
oi=>"https://github.com/allenai/open-instruct",
olmes=>"https://github.com/allenai/olmes",
aalb=>"https://artificialanalysis.ai/leaderboards/models",
aak2=>"https://artificialanalysis.ai/models/k2-horizon-375b-a23b",
aaolmo=>"https://artificialanalysis.ai/models/olmo-3-1-32b-think",
);}
s/\{\{([^|{}]+)\|([^{}]+)\}\}/my($t,$u)=($1,$2);$u=$u=~m{^@(\w+)$}?($A{$1}||die "alias $1"):$u;$u=~s{^n:}{https:\/\/app.notion.com\/p\/};"<a href=\"$u\" target=\"_blank\" rel=\"noopener noreferrer\">$t<\/a>"/ge;
' > ../index.html
if grep -q '{{' ../index.html; then echo "unexpanded link"; grep -o '{{[^}]*}}' ../index.html | head; fi
if grep -q '—' ../index.html; then echo "EM DASH FOUND"; fi
wc -c ../index.html
# Reading time (230 words per minute over the Reading tab's visible text) and the resources total
python3 - <<'PY'
import re
s=open('../index.html').read()
a=s.index('id="t-read"');b=s.index('id="t-log"')
t=re.sub(r'<script.*?</script>|<style.*?</style>','',s[a:b],flags=re.S);t=re.sub(r'<[^>]+>',' ',t)
w=len(t.split());m=round(w/230)
fr=s[s.index('<h3>Best resources</h3>'):]
tot=0
for x in re.findall(r'class="rt">\(([^)]*)\)',fr):
    h=re.search(r'(\d+)h',x);mm=re.search(r'(\d+) ?m(?:in)?\b',x)
    tot+=(int(h.group(1))*60 if h else 0)+(int(mm.group(1)) if mm else 0)
res='%dh %02dm'%(tot//60,tot%60)
s=s.replace('RT_MIN',str(m)).replace('RES_TIME',res)
open('../index.html','w').write(s)
print('reading words',w,'minutes',m,'resources',res)
PY
