"""Build parts/22_js_rd_data.js from the recorded outputs in code/out/ (and the JS/TS page's MCP recording),
so the page embeds exactly what was recorded. Redacts secret-looking strings (none expected).
Usage: python3 gen_data.py"""
import json, pathlib, re
H = pathlib.Path(__file__).parent; O = H / "code" / "out"
TL = H.parents[3] / "engineering_foundations/topic_programming_languages/javascript_and_typescript/src/tl/outputs"
RED = re.compile(r"(glpat-[\w-]+|sk-ant-[\w-]+|Bearer [A-Za-z0-9._-]{20,}|\b2a0a:[0-9a-f:]+)")
red = lambda s: RED.sub("[redacted]", s)
d = {"txt": {}, "json": {}}
for f in sorted(O.glob("*.txt")):
    t = f.read_text()
    if f.name == "t5_lsof.txt":  # kernel object addresses vary per run and teach nothing
        t = re.sub(r" 0x[0-9a-f]+ ", " ", t)
    d["txt"][f.stem] = red(t)
for f in ["tls", "dns", "small", "mcp"]:
    d["json"][f] = json.loads(red((O / f"{f}.json").read_text()))
d["json"]["tl_mcp"] = json.loads((TL / "g3_mcp_http.json").read_text())
d["wire_request"] = (H.parent / "wire/raw/h1_request.bin").read_text()
d["wire_response"] = (H.parent / "wire/raw/h1_response.bin").read_text()
js = "// generated by src/read/gen_data.py from src/read/code/out/ (recorded 2026-10-05); do not edit\nwindow.RDX=" + json.dumps(d, separators=(",", ":"), ensure_ascii=False) + ";\n"
(H.parent / "parts/22_js_rd_data.js").write_text(js)
print(len(js), "bytes")
