"""Turn the training logs (model/runs/*.json), the export report, the probes and the forward check into parts/_gen_runs.js (window.RUNS)."""
import glob, json, os
HERE = os.path.dirname(os.path.abspath(__file__))
runs = {}
for f in sorted(glob.glob(os.path.join(HERE, 'model', 'runs', '*.json'))):
    r = json.load(open(f)); runs[r['name']] = {k: r.get(k) for k in ('name', 'data', 'params', 'batch', 'images', 'lr', 'curve', 'loss', 'test', 'secs', 'logit_scale')}
ld = lambda p: json.load(open(os.path.join(HERE, 'model', p))) if os.path.exists(os.path.join(HERE, 'model', p)) else {}
out = {'runs': runs, 'report': ld('report.json'), 'check': ld('check_forward.json'), 'probe': ld('probe.json'), 'overlap': ld('overlap.json')}
open(os.path.join(HERE, 'parts', '_gen_runs.js'), 'w').write('// Generated by mk_runs.py from model/runs/*.json, model/report.json, model/probe.json and model/check_forward.json.\nwindow.RUNS=' + json.dumps(out, separators=(',', ':')) + ';\n')
print('mk_runs:', len(runs), 'runs', 'wall-clock training minutes %.1f' % (sum(r['secs'] or 0 for r in runs.values()) / 60))
