"""Pull the paper's paired-trajectory example (Appendix A.3) and the two skill-creator prompts (Appendix B.1, B.2)
verbatim from inputs/paper_v1.txt into parts/20_example.js (window.EX). usage: python3 mk_example.py"""
import json, re
L = open('inputs/paper_v1.txt').read().split('\n')
def block(start, end):
    i = next(k for k, l in enumerate(L) if l.startswith(start))
    j = next(k for k in range(i + 1, len(L)) if L[k].startswith(end))
    return [l.rstrip() for l in L[i:j]]
ex = block('Raw execution', 'Outcome.')
arms, cur = {}, None
for l in ex:
    m = re.match(r'(Raw execution|Workflow Memory|Skill)\s+\(reward (\d)\)', l)
    if m: cur = {'Raw execution': 'raw', 'Workflow Memory': 'wf', 'Skill': 'skill'}[m.group(1)]; arms[cur] = {'reward': int(m.group(2)), 'lines': []}; continue
    if cur and l.strip() and l.strip() != '⬇': arms[cur]['lines'].append(l)
# group into entries: a [Header] line starts an entry
for a in arms.values():
    ents = []
    for l in a['lines']:
        if re.match(r'^\[.*\]$', l.strip()): ents.append({'h': l.strip()[1:-1], 'body': []})
        else: ents[-1]['body'].append(l)
    a['ents'] = ents; del a['lines']
outcome = next(l for l in L if l.startswith('Outcome.'))
def prompt(start, end):
    b = block(start, end)[1:]
    return [l for l in b if l.strip() and l.strip() != '⬇']
p1 = prompt('B.1 skill-creator.md', 'B.2 skill-creator-no-hint.md')
p2 = prompt('B.2 skill-creator-no-hint.md', 'B.3 Prompts')
EX = {'arms': arms, 'outcome': outcome, 'creator': p1, 'creator_nohint': [l.strip() for l in p2]}
EX['creator'] = [l.strip() for l in p1]
def esc(o):
    if isinstance(o, str): return o.replace('{', '\x00LB').replace('}', '\x00RB')
    if isinstance(o, list): return [esc(x) for x in o]
    if isinstance(o, dict): return {k: esc(v) for k, v in o.items()}
    return o
js = json.dumps(esc(EX), ensure_ascii=False).replace('\\u0000LB', '\\u007b').replace('\\u0000RB', '\\u007d')
open('parts/20_example.js', 'w').write('// Generated by mk_example.py from inputs/paper_v1.txt (Appendix A.3, B.1, B.2), verbatim; braces escaped so the page build sees no macro.\nwindow.EX=' + js + ';\n')
print({k: [e['h'] for e in v['ents']] for k, v in arms.items()}, len(p1), len(p2))
