# Write parts/36_js_speed_data.js from data/speedrun.json (made by mk_speedrun.py from the fetched README).
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
d = json.load(open(os.path.join(HERE, 'data', 'speedrun.json')))
rows = [[r['n'], r['min'], r['date'], r['desc'], r['url'], r['cat'], r.get('gain', 0)] for r in d['rows']]
open(os.path.join(HERE, 'parts', '36_js_speed_data.js'), 'w').write(
    '// Generated by mk_speedjs.py from data/speedrun.json (do not edit). [record, minutes, date, description, link, category, ln speedup]\n'
    'window.SPEED={source:' + json.dumps(d['source']) + ',fetched:' + json.dumps(d['fetched']) + ',rows:' + json.dumps(rows, ensure_ascii=False, separators=(',', ':')) + '};\n')
print(len(rows))
