# Turn the recorded toy runs (toy/runs/seed*.json, made by toy/train.py) into parts/31_js_toy_data.js.
# Also prints the 2 x 2 summary (final values, mean of seeds) that the tab's text quotes.
import glob, json, os, statistics as st
HERE = os.path.dirname(os.path.abspath(__file__))
R = os.path.join(HERE, 'toy', 'runs')
meta = json.load(open(os.path.join(R, 'meta.json')))
K = ['text', 't_start', 't_inside', 't_space', 'm_operand', 'm_answer', 'acc']
def pack(lst):
    return [[e['step'], round(e['lr'] / meta['peak_lr'], 3)] + [round(e[k], 3) for k in K] for e in lst]
seeds = []
for f in sorted(glob.glob(os.path.join(R, 'seed*.json'))):
    d = json.load(open(f))
    seeds.append({'seed': d['seed'], 'params': d['params'], 'seconds': d.get('seconds'), 'pt': pack(d['pt']),
                  'br': {k: pack(v) for k, v in d['branches'].items()}, 'heat': d['heat'], 'samples': d['samples']})
out = {'meta': meta, 'keys': ['step', 'lr'] + K, 'seeds': seeds}
open(os.path.join(HERE, 'parts', '31_js_toy_data.js'), 'w').write(
    '// Generated by mk_toy.py from toy/runs/ (do not edit). Recorded runs of toy/train.py.\nwindow.TOY=' + json.dumps(out, separators=(',', ':')) + ';\n')
# summary
names = ['const_same', 'decay_same', 'const_maths', 'decay_maths']
summ = {}
for k in K:
    i = 2 + K.index(k)
    ck = [s['pt'][-1][i] for s in seeds]
    row = {'ckpt': round(st.mean(ck), 3)}
    for n in names:
        v = [s['br'][n][-1][i] for s in seeds]
        row[n] = round(st.mean(v), 3); row[n + '_rng'] = [round(min(v), 3), round(max(v), 3)]
    summ[k] = row
json.dump({'n_seeds': len(seeds), 'params': seeds[0]['params'] if seeds else None, 'summary': summ},
          open(os.path.join(HERE, 'data', 'toy_summary.json'), 'w'), indent=1)
print(json.dumps(summ, indent=1))
