// ---- Then and now: one step of the Apple Remote episode in six generations of wire format ----
(function(){
const OBS='Could not find [Front Row]. Similar: [\'Front Row Seat to Earth\', \'Front Row Motorsports\', \'Front Row (software)\', ...]';
const q=s=>esc(s);
const ER=[
 {t:'October 2022: the ReAct paper (PaLM-540B, few-shot text)',c:'The model continues a prompt of six hand-written trajectories. The harness stops generation at "Observation 2:", splits the text at "Action 2:", runs the action and appends the result as plain text. Everything the model knows about the format came from the exemplars ('+A('https://github.com/ysymyth/ReAct/blob/master/hotpotqa.ipynb','released code')+').',
  wire:'<span class="k">Thought 2:</span> Apple Remote was originally designed to control the Front Row media center program. I need to search Front Row next and find what other device can control it.\n<span class="x">Action 2:</span> Search[Front Row]\n<span class="o">Observation 2:</span> '+q(OBS),
  who:['the model, imitating six human exemplars','free text, split on "Action 2:"','string rules in the harness','6 exemplar trajectories ('+fmt(PAPER.rc.prompt_words['HotpotQA ReAct'])+' words)']},
 {t:'November 2022: LangChain\'s zero-shot ReAct agent',c:'The exemplars are replaced by an instruction that lists the tools and the format ("Use the following format: Question / Thought / Action / Action Input / Observation"). Still free text, still parsed, now for any tool a developer registers ('+A('https://github.com/langchain-ai/langchain/blob/v0.0.100/langchain/agents/mrkl/prompt.py','mrkl/prompt.py')+').',
  wire:'<span class="k">Thought:</span> I need to search Front Row next and find what other device can control it.\n<span class="x">Action:</span> Search\n<span class="x">Action Input:</span> Front Row\n<span class="o">Observation:</span> '+q(OBS),
  who:['the model, from a format instruction','free text, tool name and input on two lines','regular expressions in the framework','none: a zero-shot instruction']},
 {t:'June 2023: function calling',c:'The action leaves the text. The model, trained for it, returns a JSON object naming a function and its arguments; the result goes back as a message of its own. The parsing layer and its failures disappear; the free-text thought becomes optional and is often skipped ('+A('https://web.archive.org/web/20230614000000/https://openai.com/blog/function-calling-and-other-api-updates','OpenAI, 13 June 2023')+').',
  wire:'{"role": "assistant", "content": null,\n <span class="x">"function_call"</span>: {"name": "search", "arguments": "{\\"entity\\": \\"Front Row\\"}"}}\n{<span class="o">"role": "function"</span>, "name": "search", "content": "'+q(OBS.replace(/'/g,"\\'"))+'"}',
  who:['optional: the model may emit text first, or not','a JSON object, trained into the model','none: the API returns structured fields','tool schemas in the request']},
 {t:'2024: tool-use content blocks',c:'One assistant message can hold a text block (the thought, visible to the next step) followed by a tool_use block; the harness answers with a tool_result. This is ReAct\'s thought, action, observation as typed blocks ('+A('https://www.anthropic.com/news/tool-use-ga','Claude tool use, generally available 30 May 2024')+'; '+A('https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/overview','docs')+').',
  wire:'{"role": "assistant", "content": [\n  {<span class="k">"type": "text"</span>, "text": "The remote was made for Front Row. I need to search Front Row next."},\n  {<span class="x">"type": "tool_use"</span>, "id": "toolu_01", "name": "search", "input": {"entity": "Front Row"}}]}\n{"role": "user", "content": [\n  {<span class="o">"type": "tool_result"</span>, "tool_use_id": "toolu_01", "content": "'+q(OBS)+'"}]}',
  who:['the model, as a visible text block','a typed tool_use block','none','tool schemas; tool use trained in']},
 {t:'2025: reasoning models think between tool calls',c:'The thought channel is now reasoning tokens trained by reinforcement learning, and the model emits them between tool calls inside one turn: Claude 4\'s "extended thinking with tool use" ('+A('https://www.anthropic.com/news/claude-4','May 2025')+'), interleaved thinking ('+A('https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking','docs')+'), and o3 using tools agentically ('+A('https://web.archive.org/web/20250417000000/https://openai.com/index/introducing-o3-and-o4-mini/','April 2025')+'). ReAct\'s dense thoughts, learned end to end rather than imitated.',
  wire:'{"role": "assistant", "content": [\n  {<span class="k">"type": "thinking"</span>, "thinking": "Front Row is the program the remote was built for. Search it next; if the title is missing, try the software page.", "signature": "..."},\n  {<span class="x">"type": "tool_use"</span>, "id": "toolu_02", "name": "search", "input": {"entity": "Front Row"}}]}\n{"role": "user", "content": [{<span class="o">"type": "tool_result"</span>, "tool_use_id": "toolu_02", "content": "..."}]}\n<span class="k">(the next assistant turn opens with another thinking block)</span>',
  who:['the model, as RL-trained reasoning tokens','a typed tool call','none','reinforcement learning on tasks, no exemplars']},
 {t:'2025 to 2026: the harness loop',c:'The loop the paper wrote in a notebook is now the core of products and SDKs: call the model, run any tool calls, append the results, repeat until it stops calling tools (the finish action). What harnesses add on top is context management, permissions, subagents and memory ('+A('https://openai.github.io/openai-agents-python/running_agents/','OpenAI Agents SDK')+'; '+A('https://code.claude.com/docs/en/how-claude-code-works','How Claude Code works')+'). The pseudo-code is this page\'s summary of those docs.',
  wire:'<span class="k">while True:</span>\n    reply = model(messages, tools)          # thinks, then maybe calls tools\n    messages.append(reply)\n    if not reply.tool_calls: break          # the finish action\n    for call in reply.tool_calls:\n        messages.append(<span class="o">run(call)</span>)        # the observation',
  who:['the model','typed tool calls, often several at once','none','training, plus the harness\'s system prompt']}];
const steps=ER.map(e=>({t:e.t,c:e.c}));
const K=['Who writes the thought','How the action is emitted','Who parses it','What the model learns the format from'];
const draw=(m,k,e)=>{const E=ER[k];return '<pre class="wire" style="opacity:'+(0.3+0.7*e).toFixed(2)+'">'+E.wire+'</pre><dl class="wh2">'+K.map((x,i)=>'<dt>'+x+'</dt><dd>'+esc(E.who[i])+'</dd>').join('')+'</dl>'};
const counters=(m,k)=>stat('Generation',(k+1)+' of '+ER.length,ER[k].t.split(':')[0])+stat('Parsing by the harness',k<2?'string rules':'none','actions arrive '+(k<2?'as text':'as structured calls'))+stat('Exemplars in the prompt',k===0?'6':'0',k===0?'hand-written trajectories':'tools are described instead');
makeAnim({id:'th',modes:{x:steps},mode:'x',draw,counters,dur:4200});
})();
