"""Write parts/22_js_data.js (window.SE) from the measured inputs/*.json. Run: python3 build_data.py"""
import json, os
H = os.path.dirname(os.path.abspath(__file__))
L = lambda n: json.load(open(os.path.join(H, 'inputs', n)))
m1, m2, m3, m4, m5 = L('m1_pages.json'), L('m2_wal.json'), L('m3_indexes.json'), L('m4_pg18.json'), L('m5_lsm.json')
for r in m2['one_insert'].values():
    for k in ('first', 'second'):
        for x in r[k]: x.pop('block_ref', None)
for r in m5['runs']: r.pop('stats_excerpt', None)
m1.pop('pgstatindex', None)
SE = {'m1': m1, 'm2': m2, 'm3': m3, 'm4': m4, 'm5': m5}
s = json.dumps(SE, separators=(',', ':'), default=str)
open(os.path.join(H, 'parts', '22_js_data.js'), 'w').write('// Measured data (generated by build_data.py from inputs/*.json; do not edit)\nwindow.SE=' + s + ';\n')
print('22_js_data.js', len(s), 'bytes')
