"""Write parts/_gen_traces.js: the five released traces, cut down for the page (window.TRACES).
Turn snippets, bank edits and reminders are clipped; the full texts are in inputs/traces.json and in the repository.
usage: python3 mk_traces.py   (build.sh runs it)"""
import json, os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
TR = json.load(open('inputs/traces.json'))['tasks']
LB = json.load(open('inputs/injection_labels.json'))
import re
nodash = lambda t: re.sub(r'\s*\u2014\s*', ', ', t)  # the page has no em-dashes: quoted trace text gets a comma instead
def clip(t, n): t = nodash(' '.join(t.split())); return t if len(t) <= n else t[:n].rstrip() + ' [...]'
def clipk(t, n):  # keep line breaks for reminders
    t = nodash(t.strip()); return t if len(t) <= n else t[:n].rstrip() + ' [...]'
out = {}
for t, v in TR.items():
    trig = []
    for x in v['ma']['trig']:
        ops = [[o[0], clip(o[1], 150)] for o in x['ops'] if o[0] in ('SAVE_KNOWLEDGE', 'SAVE_PROCEDURAL', 'DELETE', 'UPDATE_STATUS')]
        trig.append({'s': x['s'], 'i': 1 if x['inj'] else 0, 'o': ops, 'c': clipk(x['ctx'], 760) if x['ctx'] else '', 'n': len(x['ctx'] or ''),
                     'l': LB[t].get(str(x['s']), '') if x['inj'] else '', 'k': x['k'], 'p': x['pr'], 'q': x['pc']})
    out[t] = {'b': [[y['p'], y['c'], clip(y['a'], 125), y['n']] for y in v['base']['turns']],
              'm': [[y['p'], y['c'], clip(y['a'], 125), y['n']] for y in v['mem']['turns']],
              't': trig, 'bd': v['base']['date'], 'md': v['mem']['date']}
js = '// Generated by mk_traces.py from inputs/traces.json (the five example traces released with the paper).\nwindow.TRACES=' + json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ';\n'
open('parts/_gen_traces.js', 'w').write(js)
print('mk_traces: bytes', len(js.encode()))
