"""Turn the toy's logs and results into the page's data: parts/_gen_toy.js (window.TOY) and inputs/toy_summary.json
(the %%key%% values build.sh substitutes into the prose, so the text always matches the last training run).

  python3 mk_toydata.py      (build.sh runs it)
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
MD = os.path.join(HERE, 'model')
R = json.load(open(os.path.join(MD, 'results.json')))
LR = json.load(open(os.path.join(MD, 'lr.json')))
CF = json.load(open(os.path.join(MD, 'check_forward.json'))) if os.path.exists(os.path.join(MD, 'check_forward.json')) else {}
VARS = ['released', 'causal', 'plain', 'small', 'bigft', 'head']
NAMES = {'released': 'CombinedModel as released (no causal mask)', 'causal': 'CombinedModel, causal mask added',
         'plain': 'causal, plain cross-attention (no adapter, no gate)', 'small': 'small decoder alone (own embeddings)',
         'bigft': 'frozen model fully fine-tuned instead', 'head': 'frozen model + one trained linear layer'}
mean = lambda xs: sum(xs) / len(xs)
toy = {'vars': VARS, 'names': NAMES, 'runs': {}, 'lr': LR, 'big': R.get('big'), 'big_q': R.get('big_quantised'), 'check': CF}
S = {}
for v in VARS:
    runs = [R[f'{v}_s{s}'] for s in range(3) if f'{v}_s{s}' in R]
    if not runs: continue
    toy['runs'][v] = [dict(test=r['test'], train_gen=r['train']['gen_acc'], curve=[[c[0]] + [round(x, 3) for x in c[1:]] for c in r['curve']], lr=r['lr'],
                           test_q=dict(gen_acc=r['test_quantised']['gen_acc']) if r.get('test_quantised') else None) for r in runs]
    for k in ('gen_acc', 'tf_eq', 'tf_eq_scrambled', 'loss'):
        xs = [r['test'][k] for r in runs]
        S[f'{v}_{k}'] = mean(xs)
pct = lambda x: '%d%%' % round(100 * x)
SUB = {}
for v in VARS:
    if f'{v}_gen_acc' not in S: continue
    SUB[f'{v}_gen'] = pct(S[f'{v}_gen_acc']); SUB[f'{v}_tf'] = pct(S[f'{v}_tf_eq']); SUB[f'{v}_scr'] = pct(S[f'{v}_tf_eq_scrambled'])
    SUB[f'{v}_loss'] = '%.2f' % S[f'{v}_loss']
SUB['big_in_trace'] = pct(R['big']['in_trace'])
if 'brief_test' in R['big']:
    SUB['big_brief'] = pct(R['big']['brief_test'])
    bt = [R[f'bigft_s{s}']['brief_test'] for s in range(3) if 'brief_test' in R.get(f'bigft_s{s}', {})]
    if bt: SUB['bigft_brief'] = pct(mean(bt))
for v in ('released', 'causal'):
    lk = [R[f'{v}_s{s}']['leak'] for s in range(3) if R.get(f'{v}_s{s}', {}).get('leak')]
    if lk: SUB[f'{v}_fut_eq'] = pct(mean([l['layer0_future_mass_at_eq'] for l in lk]))
    if lk: SUB[f'{v}_ans_eq'] = pct(mean([l['layer0_mass_on_answer_at_eq'] for l in lk]))
    SUB[f'{v}_trainloss'] = ' to '.join('%.3f' % x for x in sorted([R[f'{v}_s{s}']['curve'][-1][1] for s in range(3)])[::2])
json.dump(dict(means=S, sub=SUB), open(os.path.join(HERE, 'inputs', 'toy_summary.json'), 'w'), indent=1)
open(os.path.join(HERE, 'parts', '_gen_toy.js'), 'w').write('// Generated by mk_toydata.py from model/results.json, lr.json and check_forward.json.\nwindow.TOY=' + json.dumps(toy, separators=(',', ':')) + ';\n')
print('mk_toydata:', ', '.join(f'{k} {v}' for k, v in SUB.items()))
