"""Write parts/21_logs_data.js (window.LOGS), the part of model/logs.json the page ships.
Every event keeps its time, agent and type; quoted text is kept for the first event of each type per agent
(and a few more of the rarer types), cut to 110 characters. usage: python3 mk_logs_js.py"""
import json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
L = json.load(open(os.path.join(HERE, 'model', 'logs.json')))
out = {'agents': L['agents'], 'tools': L['tools'], 'source': L['source'], 'rules': {k: L['rules'][k] for k in ('payload', 'hostile', 'ref', 'dbcode')}, 'w': {}}
for w, W in L['worlds'].items():
    o = {k: W[k] for k in ('raw', 'calls', 'hours', 'stim', 'crimes', 'crime_daily_cum', 'crime_by_agent', 'votes', 'breach', 'last_seen', 'steal_cc')}
    if w in ('claude', 'mixed'): o['share_daily'] = W['share_daily']; o['bookend'] = W['bookend']
    ev = {}
    for k in ('phish', 'breach'):
        seen = {}
        rows = []
        for e in W['ev'][k]:
            key = (e[1], e[2]); seen[key] = seen.get(key, 0) + 1
            txt = e[4] if (e[4] and (seen[key] == 1 or (e[2] in ('fetch', 'act', 'store', 'pass', 'warn') and seen[key] <= 2))) else ''
            txt = re.sub(r'https?://\S+', lambda m: m.group(0)[:48], txt)[:110].replace('\u2014', '-')  # the page carries no em-dashes; quoted agents' em-dashes become hyphens
            rows.append([round(e[0], 2), e[1], e[2], e[3], txt])
        ev[k] = rows
    o['ev'] = ev
    out['w'][w] = o
s = '// Generated by mk_logs_js.py from model/logs.json (mine_logs.py over the released Season 2 tool-call records).\nwindow.LOGS=' + json.dumps(out, separators=(',', ':'), ensure_ascii=False) + ';\n'
open(os.path.join(HERE, 'parts', '21_logs_data.js'), 'w').write(s)
print('21_logs_data.js', len(s.encode()), 'bytes')
