"""Write parts/22_js_data.js (window.MCD) from expected.json and the measurements in inputs/measure/.
Run after recompute.py:  python3 make_data.py  (standard library only)."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
M = os.path.join(HERE, "inputs/measure")
E = json.load(open(os.path.join(HERE, "expected.json")))

def tl(mode, n=240):
    t = json.load(open(os.path.join(M, "memtl_%s.json" % mode)))["timeline"]
    # bucket by op index, keep the maximum in each bucket so peaks survive; phase of the bucket's last sample
    k = max(1, -(-len(t) // n))
    out = []
    for i in range(0, len(t), k):
        b = t[i:i + k]
        out.append([b[-1][0], round(max(s[2] for s in b) / 2 ** 20, 1)])
    return dict(n=len(t), k=k, pts=out, fwd=sum(1 for s in t if s[0] == "f"))

g = json.load(open(os.path.join(M, "graph.json")))
def sint(v):  # PyTorch prints -1 and -2 stored as unsigned 64-bit
    if isinstance(v, int) and v > 2 ** 63:
        return v - 2 ** 64
    if isinstance(v, list):
        return [sint(x) for x in v]
    return v
nodes = []
for r in g["nodes"]:
    sv = []
    for s in r["saved"]:
        if "shape" in s:
            sv.append([s["name"], s["shape"], s["bytes"], s.get("is_param", "")])
        elif "value" in s and s["name"] not in ("self_sym_strides", "mat2_sym_strides"):
            sv.append([s["name"], None, sint(s["value"]), ""])
    nodes.append(dict(i=r["i"], op=r["op"], lb=r["label"], nx=r["next"], sv=sv, seq=r.get("seq"), pm=r.get("param", ""), sh=r.get("shape")))

D = dict(
    tiny=E["tiny"], wb=E["wb"], chain9=E["chain9"],
    flops=dict(fwd=E["flops"]["fwd"], bwd=E["flops"]["bwd"], fwd_by=E["flops"]["fwd_by"], bwd_by=E["flops"]["bwd_by"],
               ckpt1_extra=E["flops"]["ckpt1_extra"]),
    timing=E["timing"], prof=json.load(open(os.path.join(M, "prof.json"))),
    mem={m: dict(held=round(E["memory"][m]["held"] / 2 ** 20, 1), peak=round(E["memory"][m]["peak"] / 2 ** 20, 1), tl=tl(m))
         for m in ["nograd", "none", "ckpt2", "ckpt1"]},
    hvp=[{k: v for k, v in r.items() if k.startswith("t_") or k in ("n", "k", "hessian_bytes")} for r in E["hvp"]],
    jac=E["jac"],
    graph=dict(nodes=nodes, exec=g["exec_order"], loss=g["loss"], torch=g["torch"], git=g["git"], cfg=g["config"], tokens=g["tokens"],
               saved=g["saved_unique_nonparam_bytes"])
)
js = "// ---- Generated by src/make_data.py from src/expected.json and src/inputs/measure/: do not edit by hand ----\nwindow.MCD=" + json.dumps(D, separators=(",", ":")) + ";\n"
open(os.path.join(HERE, "parts/22_js_data.js"), "w").write(js)
print("22_js_data.js", len(js), "bytes")
