"""Write parts/31_js_sql_b_data.js: the generated rows (compacted), the schema, the lessons with every variant's SQL,
and the stored PostgreSQL and SQLite (sql.js) results from results.json.
Run: python3 gen_js.py  (after gen_data.py, recompute.py and node run_sqljs.mjs)"""
import os, sys, json, datetime
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from lessons import LESSONS, variants
import gen_data as G  # re-runs the seeded generator (deterministic) and exposes the content pools

D = json.load(open(os.path.join(HERE, 'data.json')))
T0 = datetime.datetime(2026, 1, 1)
pool = [G.USER_MSG, G.ASSIST_MSG]
msgs = []
for m in D['messages']:
    r = 1 if m[2] == 'assistant' else 0
    secs = int((datetime.datetime.strptime(m[5], '%Y-%m-%d %H:%M:%S') - T0).total_seconds())
    msgs.append([m[0], m[1], r, pool[r].index(m[3]), m[4], secs])
res_path = os.path.join(HERE, 'results.json')
R = json.load(open(res_path)) if os.path.exists(res_path) else {'meta': {}, 'runs': {}}
def slim(lst):
    return [{k: v for k, v in r.items() if k != 'sql'} for r in lst]
lessons = []
for l in LESSONS:
    vs = {}
    for key, sql in variants(l):
        run = R['runs'].get(f"{l['id']}:{key}", {})
        vs[key] = {'sql': sql, 'pg': slim(run.get('pg', [])), 'sqlite': slim(run.get('sqlite', run.get('sqlite_py', [])))}
    lessons.append({'id': l['id'], 'title': l['title'], 'params': [{'name': p['name'], 'label': p['label'], 'options': [o[1] for o in p['options']]} for p in l['params']],
                    'variants': vs})
meta = {k: R['meta'].get(k) for k in ('date', 'postgres', 'python_sqlite', 'sqljs_sqlite', 'machine')}
meta['differ'] = sorted(R['meta'].get('differ', {}).keys())
out = {'schema': open(os.path.join(HERE, 'schema_sqlite.sql')).read(), 'schema_pg': open(os.path.join(HERE, 'schema_pg.sql')).read(),
       'cols': D['cols'], 'users': D['users'], 'chats': D['chats'], 'msgs': msgs, 'credits': D['credits'], 'pool': pool,
       'lessons': lessons, 'meta': meta}
p = os.path.join(HERE, '..', 'parts', '31_js_sql_b_data.js')
s = json.dumps(out, separators=(',', ':'), ensure_ascii=False)
assert '\u2014' not in s and '{{' not in s and '</' not in s
open(p, 'w').write('// ---- SQL playground data: generated by src/sql/gen_js.py from gen_data.py, lessons.py and results.json; do not edit ----\nwindow.SQ_DATA=' + s + ';\n')
print('wrote', p, os.path.getsize(p), 'bytes')
