# Case annotations, part C (architectures and published practices). See annot_a.py for the rules.

CASES_C = [
dict(id="stripe-2017", org="Stripe", type="architecture",
 title="Idempotency keys: retry a payment without charging twice",
 blocks=["retry"],
 system="Stripe's API creates charges. A client (a shop's server) sends \"charge this card $20\" over a network that can fail at any point.",
 happened="If the connection drops, the client cannot tell whether the charge happened. Retrying risks charging twice; not retrying risks not charging. Stripe's answer: the client generates a unique key (a random UUID) per operation and sends it as an Idempotency-Key header. The server remembers the key and its result, so a retry with the same key returns the first result instead of charging again. Its client library retries automatically, with exponential backoff and jitter so many clients do not retry in step.",
 fix="Keys are up to 255 characters; Stripe may remove a key once it is at least 24 hours old, so a retry must come within that window.",
 lesson="Make any operation with side effects safe to repeat before you let anyone retry it.",
 numbers=[dict(v="255", t="maximum key length (characters)", q=5),
          dict(v="24 hours", t="minimum age before a key may be removed", q=6)],
 terms={"idempotent": "doing it twice has the same effect as doing it once",
        "UUID": "a 128-bit random identifier; two clients will practically never pick the same one"}),

dict(id="aws-jitter-2015", org="AWS", type="architecture",
 title="Backoff alone still makes clients retry in lockstep; jitter fixes it",
 blocks=["retry"],
 system="A simulation by Marc Brooker of many clients contending for the same resource (an optimistic-concurrency write) and retrying when they lose.",
 happened="With plain exponential backoff, failed clients wait 1, 2, 4, 8 ... units, all on the same schedule, so their retries still arrive in clusters. Adding randomness, for example \"Full Jitter\" (wait a random time between zero and the backoff), spreads the retries into a roughly constant rate.",
 fix="The post recommends jitter (Full Jitter for least work); the Builders' Library card shows how Amazon applies it.",
 lesson="Backoff decides how long to wait; jitter decides that not everyone waits the same amount.",
 numbers=[dict(v="100", t="contending clients in the simulation", q=3),
          dict(v="more than half", t="fewer calls with jitter than with plain backoff", q=3)],
 terms={"Full Jitter": "sleep = random(0, min(cap, base x 2^attempt))",
        "optimistic concurrency": "write only if nobody else changed the record since you read it; otherwise retry"}),

dict(id="abl-timeouts", org="AWS", type="architecture",
 title="Five layers that each retry three times hit the database 243 times",
 blocks=["retry", "degrade"],
 system="Amazon's internal guidance (the Builders' Library) on timeouts, retries and backoff, by Marc Brooker.",
 happened="Retries multiply across layers. If a request passes through five services and each makes up to three attempts, one failing database call can turn into 3 x 3 x 3 x 3 x 3 = 243 calls, exactly when the database is struggling. Amazon's practices: set a timeout on every remote call (chosen from the dependency's measured latency, for example its p99.9), retry only at one layer, cap retries with a local token bucket, retry only while the dependency looks healthy, and retry only APIs that are idempotent.",
 fix="Published as Amazon's standing practice for its own services.",
 lesson="Retries are load: budget them, and retry at one layer, not at every layer.",
 numbers=[dict(v="243x", t="load on the database with five layers each retrying", q=2),
          dict(v="3^5 = 243", t="three attempts per layer, five layers", f="3 x 3 x 3 x 3 x 3")],
 terms={"timeout": "the longest a caller will wait for an answer before giving up",
        "p99.9": "the latency that 99.9% of requests beat; only 1 in 1,000 is slower",
        "token bucket": "a counter that refills at a steady rate; each retry spends a token, and when it is empty retries stop"}),

dict(id="discord-2023", org="Discord", type="architecture",
 title="Trillions of messages: hot partitions, request coalescing, a new database",
 blocks=["shard", "cache", "repl"],
 system="Discord stores every message in a distributed database partitioned by channel and time bucket; at the start of 2022 it was a 177-node Cassandra cluster.",
 happened="A busy channel's partition becomes hot: thousands of users read the same rows at once. Because reads and writes needed a quorum of replicas, slow nodes for that partition slowed everyone. Discord put data services (written in Rust) between the API and the database: concurrent requests for the same data are coalesced into one database query, and consistent hashing routes all requests for a channel to the same data-service instance so coalescing works. Then it migrated to ScyllaDB, a Cassandra-compatible database without a garbage collector.",
 fix="177 Cassandra nodes became 72 ScyllaDB nodes; the migration ran at up to 3.2 million messages per second and took nine days.",
 lesson="Before buying a bigger database, stop sending it the same query a thousand times.",
 numbers=[dict(v="177", t="Cassandra nodes before", q=0),
          dict(v="72", t="ScyllaDB nodes after", q=5),
          dict(v="15ms", t="p99 to fetch history after (40-125ms before)", q=8),
          dict(v="3.2 million", t="messages per second during the migration", q=6)],
 terms={"partition": "the slice of data stored together on the same replicas, chosen by a key",
        "quorum": "a majority of replicas; a read or write waits for that many to answer",
        "request coalescing": "when many callers ask for the same thing at once, make one backend request and share the answer",
        "consistent hashing": "a way to map keys to servers so that adding a server moves only a small share of keys"}),

dict(id="insta-2012", org="Instagram", type="architecture",
 title="Thousands of logical shards on a few Postgres servers",
 blocks=["shard"],
 system="Instagram stored photos, likes and users in PostgreSQL, and needed IDs that were unique across shards and sortable by time.",
 happened="Data is split by user ID into thousands of logical shards (Postgres schemas), many per physical server. To grow, a set of logical shards moves to a new server; no data is re-bucketed. Each ID is built inside the database: 41 bits of milliseconds since a custom epoch, 13 bits of shard ID, 10 bits of a per-table sequence.",
 fix="IDs sort by time without a central ID service, and the shard is readable from the ID itself.",
 lesson="Split into many small logical shards early; moving them later is cheap, re-splitting is not.",
 note="Checked: 2^41 milliseconds is about 69.7 years, not the 41 years the post states (recomputed in recompute.py). The design is unaffected; the figure in the post is a slip.",
 numbers=[dict(v="41 bits", t="milliseconds since a custom epoch", q=1),
          dict(v="13 bits", t="logical shard ID", q=1),
          dict(v="10 bits", t="sequence, modulus 1024", q=1),
          dict(v="2000", t="logical shards in their worked example", q=2),
          dict(v="1024", t="IDs per shard per millisecond", f="2^10")],
 terms={"shard": "one slice of the data, stored on its own server, chosen by a key such as user ID",
        "logical shard": "a slice that is smaller than a server, so several live on one machine and can be moved"}),

dict(id="notion-2021", org="Notion", type="architecture",
 title="Why 480 shards: a Postgres monolith split by workspace",
 blocks=["shard", "repl"],
 system="Notion's blocks (every paragraph, page and to-do) lived in one PostgreSQL database that had grown through four orders of magnitude.",
 happened="On-call engineers were woken by CPU spikes and even simple schema changes became risky. Notion partitioned by workspace ID, since every block belongs to exactly one workspace, into 480 logical shards on 32 physical databases (15 each). 480 has many divisors, so it can later spread evenly over 40 or 48 hosts. The move used double-writing (new writes go to both), a backfill of old data, verification, then a switch-over.",
 fix="Sharded Postgres with application-level routing.",
 lesson="Pick the shard key that keeps each request on one shard (here, the workspace), and a shard count that divides many ways.",
 numbers=[dict(v="480", t="logical shards", q=3),
          dict(v="32", t="physical databases", q=3),
          dict(v="15", t="logical shards per database", f="480 / 32"),
          dict(v="32 to 40 to 48", t="future host counts that keep shards even", q=4)],
 terms={"partition key": "the field that decides which shard a row goes to",
        "double-write": "during a migration, write every change to both the old and the new store"}),

dict(id="figma-2024", org="Figma", type="architecture",
 title="Sharding Postgres without leaving Postgres",
 blocks=["shard"],
 system="Figma runs on Amazon RDS PostgreSQL. It first split by table (vertical partitioning: groups of tables on separate databases).",
 happened="Some tables reached several terabytes and billions of rows and were heading past the I/O limits (IOPS) of the largest RDS instance. Figma built horizontal sharding itself: a DBProxy service parses each SQL query and routes it to the right shard, related tables share a shard key (\"colos\"), and logical sharding was rolled out before physical sharding so that it could be tested and rolled back.",
 fix="First horizontally sharded table shipped in September 2023.",
 lesson="Vertical partitioning buys time; for the biggest tables only horizontal sharding scales, and a routing layer lets you add it gradually.",
 numbers=[dict(v="100x", t="growth of the database stack since 2020", q=0)],
 terms={"vertical partitioning": "moving whole tables to different databases",
        "horizontal sharding": "splitting the rows of one table across databases",
        "IOPS": "disk reads and writes per second, a hard limit of each database machine"}),

dict(id="shopify-2018", org="Shopify", type="architecture",
 title="Pods: many small isolated Shopifys behind one front door",
 blocks=["shard", "lb", "degrade"],
 system="Shopify hosts many shops on one platform, and one busy shop must not take database time from all the others.",
 happened="Shops are grouped into pods; each pod has its own fully isolated datastores, while app servers, job workers and load balancers are shared. A component in the load balancers called Sorting Hat matches each request to its pod and tags it with a header, so the app connects to that pod's databases. Pods are the unit of failure and of disaster recovery: a whole data center is evacuated pod by pod.",
 fix="A pod failing is meant to stay a pod failure, not a platform outage.",
 lesson="Shard by tenant and isolate the shards, so one customer's bad day stays theirs.",
 numbers=[],
 terms={"tenant": "one customer (here, one shop) sharing a platform with others",
        "blast radius": "how much breaks when one part fails"}),

dict(id="memcache-2013", org="Facebook", type="architecture",
 title="Leases cut a cache stampede from 17,000 to 1,300 queries a second",
 blocks=["cache"],
 system="Facebook put memcached, an in-memory cache, in front of MySQL: the largest memcached installation known, at over a billion requests per second.",
 happened="When a hot key is deleted (because its data changed), every web server that misses it queries the database at once: a thundering herd. Facebook added leases: on a miss, the cache gives one client a token to refill the key (at most one token per key every 10 seconds) and tells the others to wait a short time and retry the cache, by which point the value is usually there. Leases also stop a slow client from writing an old value over a newer one (a stale set).",
 fix="With leases, the peak database query rate fell from 17K/s to 1.3K/s in their measurement.",
 lesson="On a cache miss, let one caller refill and make the rest wait.",
 numbers=[dict(v="17K/s", t="peak database queries without leases", q=2),
          dict(v="1.3K/s", t="with leases", q=3),
          dict(v="13x", t="fewer peak queries", f="17,000 / 1,300")],
 terms={"cache-aside": "the app reads the cache; on a miss it reads the database and writes the answer into the cache",
        "thundering herd": "many clients missing the same key and hitting the database together"}),

dict(id="netflix-2011", org="Netflix", type="architecture",
 title="Chaos Monkey: break production on purpose, during office hours",
 blocks=["degrade", "obs"],
 system="Netflix's streaming service on AWS, built from many services on many instances.",
 happened="Netflix built Chaos Monkey, which randomly kills production instances, and ran it during business hours with engineers watching, so that every service had to survive losing a machine. Its siblings inject latency (Latency Monkey) or simulate losing a whole availability zone (Chaos Gorilla).",
 fix="Practising failures in daylight let teams build automatic recovery for them before a real one arrived.",
 lesson="If you never practise failure, your first practice is the real outage.",
 numbers=[],
 terms={"availability zone": "one or more data centers in a region with separate power and network, so they rarely fail together",
        "chaos engineering": "injecting failures deliberately to check the system copes"}),

dict(id="sre-2016", org="Google", type="architecture",
 title="Error budgets: how much failure you are allowed to spend",
 blocks=["obs", "deploy"],
 system="Google's Site Reliability Engineering book, chapter Embracing Risk.",
 happened="Instead of aiming for 100% uptime, a service picks a target (a Service Level Objective). The gap between the target and 100% is the error budget. While budget remains, teams ship; when it is spent, releases slow down. This turns the argument between shipping fast and staying up into arithmetic both sides agree on.",
 fix="Releases continue while budget remains; the budget gives product and SRE teams a shared incentive.",
 lesson="Pick a reliability target, measure against it, and spend the remainder on change.",
 numbers=[dict(v="99.99%", t="example availability target", q=0),
          dict(v="52.56 minutes", t="down per year that 99.99% allows", q=0),
          dict(v="250", t="errors allowed in a day of 2.5M requests at 99.99%", q=1)],
 terms={"SLO": "Service Level Objective: the reliability target, such as 99.9% of requests succeed in 30 days",
        "error budget": "1 minus the SLO: the failures you can afford"}),

dict(id="twitter-2013", org="Twitter", type="architecture",
 title="A peak 25 times the average: from a Ruby monolith to services",
 blocks=["lb", "queue", "retry"],
 system="Twitter, which in 2013 took in more than 500 million Tweets a day.",
 happened="On 3 August 2013 a TV airing in Japan produced a one-second peak of 143,199 Tweets per second, against an average of about 5,700. Earlier, Twitter had run one of the largest Ruby on Rails apps, where each process handled one request at a time and the answer was to throw more machines at it. It had since moved to services on the JVM (Tweet, timeline and user first), each scaled and tuned independently. On the way it learned that services had no consistent back-pressure signal and that clients aggressively retrying slow services caused thundering herds. During the peak users \"didn't experience a blip\".",
 fix="Service-oriented architecture with independent capacity per service.",
 lesson="Size for the peak, not the average; and know your peak-to-average ratio.",
 numbers=[dict(v="143,199", t="Tweets in one second, peak", q=0),
          dict(v="5,700", t="Tweets per second on average", q=1),
          dict(v="25x", t="peak over average", f="143,199 / 5,700")],
 terms={"monolith": "one big application deployed as a unit",
        "peak-to-average ratio": "how much bigger the busiest second is than a typical second"}),

dict(id="cai-2024", org="Character.AI", type="architecture",
 title="20,000 LLM queries a second: shrink the KV cache, then keep it between turns",
 blocks=["gpu", "cache", "lb"],
 system="Character.AI serves chat with its own LLMs. During generation a model keeps a KV cache: intermediate results for every earlier token of the conversation, held in GPU memory.",
 happened="The KV cache, not the GPU's arithmetic, limited how many chats fit on a GPU. Character.AI shrank it more than 20 times with architecture choices (multi-query attention, sharing the cache across layers, int8). It also keeps each conversation's KV cache in host memory between turns, and uses sticky sessions so the next message of a dialogue reaches the server that holds its cache.",
 fix="A 95% cache hit rate, and serving costs 33 times lower than at the end of 2022.",
 lesson="For LLM serving, memory per conversation is capacity; caching across turns needs routing that keeps a conversation on its server.",
 numbers=[dict(v="20,000", t="inference queries per second", q=0),
          dict(v="20X", t="smaller KV cache", q=1),
          dict(v="95%", t="cache rate", q=4),
          dict(v="33", t="times lower serving cost than late 2022", q=5)],
 terms={"KV cache": "the stored keys and values of earlier tokens, reused so the model does not recompute the whole conversation for each new token",
        "sticky session": "routing all requests of one conversation to the same server"}),

dict(id="vllm-2023", org="vLLM / LMSYS", type="architecture",
 title="PagedAttention: GPU memory managed like an operating system's",
 blocks=["gpu"],
 system="vLLM, an open-source LLM serving engine from UC Berkeley, used to serve LMSYS's Chatbot Arena.",
 happened="Earlier servers reserved one contiguous block of GPU memory per request, sized for the longest possible answer, wasting 60 to 80% of KV-cache memory. PagedAttention stores the cache in small fixed-size pages allocated as the answer grows, like virtual memory in an operating system, so waste falls under 4% and many more requests fit in one batch.",
 fix="Up to 24x the throughput of Hugging Face Transformers in the authors' tests; LMSYS halved the GPUs needed for its traffic.",
 lesson="When GPU memory is the limit, wasted memory is lost throughput.",
 numbers=[dict(v="60% – 80%", t="memory wasted by earlier systems", q=0),
          dict(v="under 4%", t="waste with PagedAttention", q=1),
          dict(v="24x", t="throughput against HF Transformers (authors' benchmark)", q=2),
          dict(v="50%", t="fewer GPUs for LMSYS's traffic", q=3)],
 terms={"throughput": "how many requests (or tokens) are finished per second",
        "batch": "several requests run through the model together, sharing each pass over the weights"}),

dict(id="anyscale-2023", org="Anyscale", type="architecture",
 title="Continuous batching: let a finished answer leave the batch at once",
 blocks=["gpu", "queue"],
 system="An LLM server batches requests so that one pass over the model's weights serves several answers at once. Answers have different lengths.",
 happened="With static batching the server waits until the longest answer in the batch is finished; the slots of answers that ended early sit idle, and new requests queue outside. Continuous batching (iteration-level scheduling, from the Orca paper) re-forms the batch after every generated token: a finished answer leaves and a waiting request joins at once. The benchmark ran on one NVIDIA A100.",
 fix="8x throughput over naive static batching from continuous batching alone, and 23x with vLLM's memory management on top, while median latency also fell (the authors' benchmark).",
 lesson="A batch should be a queue that keeps moving, not a bus that leaves only when full and returns only when empty.",
 numbers=[dict(v="8x", t="throughput from continuous batching over naive static batching", q=3),
          dict(v="23x", t="with vLLM", q=4)],
 terms={"static batching": "the batch is fixed until every request in it has finished",
        "p50": "the median latency: half the requests are faster",
        "iteration": "one step of generation, producing one token for every answer in the batch"}),
]
