# Case annotations, part B (outages 2012--2026). See annot_a.py for the rules.

CASES_B = [
dict(id="gh-2026-04-dns", org="GitHub", type="outage",
 title="DNS failed in one data center; caches kept most of GitHub up",
 blocks=["cache", "lb"],
 system="Inside a data center, GitHub's services find each other by name through internal DNS resolvers. A new traffic-balancing mechanism had been rolled out progressively to spread load.",
 happened="Under one load pattern the new mechanism made the DNS resolvers in one data center fail intermittently. Every service that needed to look up an address (internal APIs, storage, outside providers) started failing at once. Services that had the address cached kept working, which is why only part of the traffic failed.",
 fix="A config rollback did not help; restarting the DNS infrastructure did, within minutes. GitHub is hardening DNS so one data center cannot cascade, testing infrastructure changes against production-like traffic, and reviewing which services share it.",
 lesson="A cache is also a shock absorber: it turned a full outage into a partial one.",
 numbers=[dict(v="5–7%", t="share of all traffic affected", q=0),
          dict(v="1 hour and 27 minute", t="impact window, 23 Apr 2026", q=0)],
 terms={"resolver": "the server a machine asks to turn a name into an address",
        "cascade": "one failure causing failures in everything that depends on it, and so on"}),

dict(id="gh-2026-04-lb", org="GitHub", type="outage",
 title="Scrapers saturated the load balancers in front of search",
 blocks=["lb", "degrade"],
 system="GitHub search sits behind its own tier of load balancers, and public API calls are rate limited per caller.",
 happened="Anonymous scrapers spread their requests over more than 600,000 IP addresses so that no single address hit the rate limit. Their traffic was 30% of the day's search traffic, packed into four hours, and saturated the load balancers. Issues, pull requests, Actions and other features that rely on search saw up to 65% of searches time out or fail.",
 fix="Scaled the load-balancer tier, blocked the traffic, tuned connection handling and reuse, and added controls to restrict anonymous traffic so signed-in users are protected.",
 lesson="A per-caller rate limit fails against callers who split themselves; protect the shared tier with limits by class of user too.",
 numbers=[dict(v="600,000", t="unique IP addresses", q=4),
          dict(v="30%", t="of the day's search traffic, in four hours", q=3),
          dict(v="65%", t="peak share of searches failing for some services", q=1)],
 terms={"saturation": "a resource is at 100% of its capacity, so new work queues or is refused",
        "load balancer": "the machine that receives requests and hands each to one of many servers behind it"}),

dict(id="anth-2025-09", org="Anthropic", type="outage",
 title="Three serving bugs quietly made Claude's answers worse",
 blocks=["gpu", "lb", "obs"],
 system="Claude is served on three hardware platforms (AWS Trainium, NVIDIA GPUs, Google TPUs). A load balancer routes each request to a server pool; some pools were configured for the upcoming 1M-token context window. Routing is sticky: a user's follow-up requests tend to go to the same server.",
 happened="From 5 August some requests were misrouted to the 1M-context servers, which degraded answers. A routine load-balancing change on 29 August made it much worse. Two other bugs (a TPU misconfiguration that corrupted output, and a compiler bug in token selection) overlapped. Nothing went down, so error rates looked fine; users noticed before the evals did, and sticky routing meant the unlucky users kept getting the bad servers.",
 fix="Fixed the routing logic and rolled back or fixed the other two bugs; Anthropic is adding more sensitive evaluations and running quality evaluations continuously on real production systems.",
 lesson="For a model service, wrong answers are an outage that no 5xx counter sees: monitor quality, not only errors.",
 numbers=[dict(v="16%", t="of Sonnet 4 requests affected at the worst hour (31 Aug)", q=4),
          dict(v="30%", t="of Claude Code users with at least one misrouted message", q=6)],
 terms={"sticky routing": "sending a user's requests to the same server each time, usually to reuse its cache",
        "context window": "how much text (in tokens) a model can read in one request"}),

dict(id="oai-2024-12", org="OpenAI", type="outage",
 title="A monitoring tool overloaded the cluster brains, and DNS went with them",
 blocks=["deploy", "obs", "cache"],
 system="OpenAI runs its services on Kubernetes clusters. Each cluster has a control plane (the API servers that track what runs where); services find each other through DNS that depends on that control plane.",
 happened="A new telemetry service was deployed to every node. On large clusters each node made expensive Kubernetes API calls whose cost grew with cluster size, and the control planes fell over. Running pods kept going, but DNS-based service discovery broke. Per-node DNS caches hid the failure for a while, so the rollout kept going fleet-wide. Engineers then could not reach the control plane to remove the change (the locked-out effect).",
 fix="Recovered by scaling down clusters, blocking access to the Kubernetes API and scaling up its servers. Follow-ups: phased rollouts with control-plane health checks for all infrastructure changes, and break-glass access to the API servers in any circumstances.",
 lesson="Test changes at the largest scale you run, and keep a way in that does not depend on the thing that broke.",
 numbers=[dict(v="3:16 PM", t="start (PST, 11 Dec 2024)", q=4),
          dict(v="7:38 PM", t="end", q=4),
          dict(v="4 h 22 min", t="of significant degradation or unavailability", f="7:38 PM minus 3:16 PM")],
 terms={"Kubernetes": "software that decides which machine runs each copy of each service and restarts them when they die",
        "control plane": "the part of a system that manages and configures it, as opposed to the data plane that serves the requests",
        "break-glass": "an emergency access path kept separate from normal tooling"}),

dict(id="crowd-2024-07", org="CrowdStrike", type="outage",
 title="One content update, pushed to everyone at once, crashed 8.5 million PCs",
 blocks=["deploy"],
 system="CrowdStrike's Falcon sensor runs inside the Windows kernel to detect attacks. Besides software releases, it receives frequent content updates (channel files) that tell it what to look for.",
 happened="A new template type expected 21 input fields; the sensor code supplied 20. The validator checked the content against the 21-field definition and passed it. When a content update used the 21st field, the sensor read past the end of its array, and because it runs in the kernel, Windows crashed. The update went to every online machine at once: content updates were not rolled out in stages.",
 fix="Remediated the content 78 minutes after release. CrowdStrike added bounds checks, a validator check for the field count, and staged deployment for content updates.",
 lesson="Content and config can crash code like any release: stage them, and the more privileged the code, the smaller the first stage.",
 numbers=[dict(v="04:09 UTC", t="update released (19 Jul 2024)", q=0),
          dict(v="05:27 UTC", t="update remediated", q=1),
          dict(v="78 min", t="exposure window", f="05:27 minus 04:09"),
          dict(v="21", t="fields the template defined", q=2),
          dict(v="20", t="fields the sensor supplied", q=2),
          dict(v="8.5 million", t="Windows devices affected (Microsoft's estimate)", q=5)],
 terms={"kernel": "the core of the operating system; a crash there takes the whole machine down",
        "out-of-bounds read": "reading memory past the end of an array, which can crash the program"}),

dict(id="roblox-2021-10", org="Roblox", type="outage",
 title="73 hours down: the service directory everything depends on choked",
 blocks=["repl", "obs"],
 system="Roblox runs hundreds of internal services on its own servers. They find each other through HashiCorp Consul, a small replicated cluster that holds the service directory and settings and agrees on writes through leader election (Raft).",
 happened="Roblox had enabled a new Consul streaming feature and added 50% more routing nodes ahead of year-end traffic. Under unusually high read and write load, streaming caused heavy contention, and a pathological performance problem in Consul's storage library (BoltDB) made writes slow. Consul degraded, so almost every service degraded. Roblox's own monitoring depended on the same systems, which slowed diagnosis.",
 fix="Turned off streaming, reset the Consul cluster from a snapshot, and let players back in by percentage, checking database and cache load at each step. Telemetry no longer depends on the systems it monitors.",
 lesson="Find your one shared dependency and keep your monitoring outside it.",
 numbers=[dict(v="73-hour", t="outage, 28 to 31 Oct 2021", q=0),
          dict(v="50%", t="more traffic-routing nodes added before the incident", q=1)],
 terms={"service discovery": "how a service finds the current addresses of the services it calls",
        "leader election": "replicas choosing one of themselves to accept writes, so they agree on order"}),

dict(id="fb-2021-10", org="Meta", type="outage",
 title="One maintenance command disconnected every Facebook data center",
 blocks=["deploy", "lb"],
 system="Facebook's data centers are joined by its own backbone network. Its DNS servers announce themselves to the internet with BGP, and withdraw those announcements if they cannot reach the data centers, a safety rule meant to steer users away from a broken site.",
 happened="A command meant to measure backbone capacity took down all backbone links; a bug in the audit tool let it through. With the backbone gone, every DNS server judged itself unhealthy and withdrew from the internet, so facebook.com stopped resolving at all. Internal tools broke with DNS and remote access was down, so engineers were sent onsite.",
 fix="Restored the backbone on site, then brought traffic back gradually, because switching tens of megawatts of load back on at once could itself break power systems and caches.",
 lesson="A health rule that is correct for one site can take down everything when every site trips it at the same time.",
 numbers=[dict(v="tens of megawatts", t="power dip per data center to be restored carefully", q=3)],
 terms={"backbone": "the private long-distance network linking a company's data centers",
        "BGP": "the protocol networks use to tell the rest of the internet \"send traffic for these addresses to me\""}),

dict(id="slack-2021-01", org="Slack", type="outage",
 title="The first Monday of the year: autoscaling made it worse",
 blocks=["lb", "obs"],
 system="Slack's servers live in many AWS virtual networks joined by AWS Transit Gateways. An autoscaler adds or removes web servers by load, and a provision-service sets up each new server.",
 happened="Traffic on the first working day of 2021 overloaded a Transit Gateway, which dropped packets. Web servers waiting on the network used less CPU, so the autoscaler read them as idle and removed some; then, as worker threads piled up, it tried to add 1,200 servers in 14 minutes. The provisioning service hit the Linux open-files limit and an AWS quota, so new servers did not come up. Slack's dashboards ran in another network and were blind for the same reason.",
 fix="AWS raised the gateway's capacity by hand; Slack fixed provision-service limits, will load test it, revisit health checks and autoscaling, and ask for pre-emptive gateway scaling after holidays.",
 lesson="Autoscaling reads a signal; when the network is the bottleneck, the signal lies. Load-test the scaling path itself.",
 numbers=[dict(v="1,200", t="servers the autoscaler tried to add", q=2),
          dict(v="14 min", t="window for that scale-up", f="7:15 minus 7:01 AM PST")],
 terms={"autoscaling": "software that adds servers when a load metric goes up and removes them when it goes down",
        "quota": "a cap the cloud provider puts on how many of a resource you may use"}),

dict(id="gh-2018-10", org="GitHub", type="outage",
 title="43 seconds of network loss, 24 hours of repair",
 blocks=["repl"],
 system="GitHub stored its data in MySQL clusters with one primary (the copy that accepts writes) and replicas in its East and West Coast data centers. A tool called Orchestrator promotes a replica to primary automatically when the primary looks dead.",
 happened="Network maintenance cut the East Coast data center off for 43 seconds. Orchestrator promoted West Coast replicas to primary. Now both coasts held writes the other did not have, so GitHub could not simply fail back; and East Coast apps writing across the country were too slow. GitHub chose data integrity over a shorter outage: it restored from backups, re-synchronised the replicas and replayed the backlog over a day.",
 fix="Orchestrator was set to stop promoting primaries across regions; GitHub sped up an effort already under way to serve from several data centers at once (active/active/active).",
 lesson="Automatic failover across a slow link trades a short outage for a long consistency repair.",
 numbers=[dict(v="43 seconds", t="network partition", q=1),
          dict(v="24 hours and 11 minutes", t="of degraded service", q=1),
          dict(v="200,000", t="webhook payloads dropped after outliving their TTL", q=4)],
 terms={"primary and replica": "the copy that takes writes, and the copies that receive them a moment later",
        "failover": "promoting a replica to primary when the primary is judged dead",
        "partition": "here, a network split: two parts of a system cannot talk to each other"}),

dict(id="gitlab-2017-01", org="GitLab", type="outage",
 title="Deleted the wrong database, then found the backups did not work",
 blocks=["repl", "obs"],
 system="GitLab.com ran one PostgreSQL primary with a replica, plus supposedly several kinds of backup.",
 happened="Late in the evening (UTC), under heavy load, the replica fell behind. An engineer trying to reset it ran the delete command on the primary. The regular pg_dump backups had been failing silently (a major-version mismatch), and disk snapshots were not enabled. The best copy left was a snapshot taken by hand 6 hours earlier, on a slow staging disk.",
 fix="Restored from that snapshot (copying took about 18 hours), losing about 6 hours of database changes. Follow-ups included a dashboard showing whether backups ran, and owners for testing recovery procedures.",
 lesson="A replica is not a backup, and a backup you have not restored is not a backup.",
 numbers=[dict(v="6 hours", t="age of the only usable snapshot", q=3),
          dict(v="18 hours", t="to copy the data back", q=4),
          dict(v="5,000", t="projects affected (and 5,000 comments, 700 new accounts)", q=5)],
 terms={"pg_dump": "PostgreSQL's tool that writes a database out as a file",
        "snapshot": "a frozen copy of a disk at one moment"}),

dict(id="knight-2012-08", org="Knight Capital", type="outage",
 title="Seven of eight servers got the new code; the eighth lost $460 million",
 blocks=["deploy"],
 system="Knight's order router SMARS ran on eight servers and turned client orders into many smaller orders sent to the stock exchange.",
 happened="New code reused an old flag that once switched on a dead feature called Power Peg. A technician copied the new code to only seven of the eight servers. On the eighth, the reused flag woke the old code, which sent orders without ever stopping. Nothing checked that all eight servers ran the same code, and Knight had no procedure to halt the system in response to its own aberrant activity.",
 fix="The SEC fined Knight $12 million and found it lacked controls to ensure the orderly deployment of new code, to prevent old code from being activated, and to halt the system.",
 lesson="Deploys must be automated and verified on every machine, and dead code with live switches must be removed.",
 numbers=[dict(v="eight", t="servers; one was missed by the deploy", q=0),
          dict(v="45 minutes", t="of runaway trading", q=2),
          dict(v="4 million", t="executions in 154 stocks", q=2),
          dict(v="$460 million", t="loss", q=3)],
 terms={"kill switch": "a control that stops a system immediately, without a new deploy",
        "dead code": "code still shipped but no longer meant to run"}),
]
