# Case annotations, part A (outages 2024--2026). Written by hand from the extracts in inputs/.
# Every number is either quoted (q = index of the quote in inputs/extracts_*.json that states it;
# build_cases.py checks the digits appear in that quote) or derived (f = the formula; recompute.py checks it).
# Plain words for a reader new to running systems; each case defines its own jargon in "terms".

CASES_A = [
dict(id="aws-2025-dwfm", flagship=True, org="AWS", type="outage",
 title="EC2 could not hand out servers: a queue that never drained",
 blocks=["queue", "retry"],
 system="EC2 rents out virtual machines that run on physical servers AWS calls droplets. A manager service (DWFM) keeps a lease, a short-lived claim it must renew, on every droplet; a droplet with no lease cannot take new virtual machines.",
 happened="DWFM's regular check-ins with droplets depend on DynamoDB. While DynamoDB was down (see the DNS card from the same night) those checks failed and leases slowly timed out. When DynamoDB came back at 2:25 AM, every droplet needed a new lease at once. Each attempt now waited so long in line that it timed out before it finished, and each timeout put a fresh attempt back in the line. The line never got shorter: AWS calls this congestive collapse. Customers asking for new machines got \"insufficient capacity\" errors.",
 fix="At 4:14 AM engineers throttled incoming work (let in only as much as could finish) and restarted DWFM hosts, which emptied the queues; every droplet had a lease by 5:28 AM. AWS says it will rate limit incoming work by the size of the waiting queue and test this recovery path at scale.",
 lesson="If work waits longer than its timeout, adding retries adds only waste: cap the queue, not just the workers.",
 numbers=[dict(v="2:25 AM", t="DynamoDB back; lease rebuilding starts (PDT, 20 Oct 2025)", q=1),
          dict(v="4:14 AM", t="throttle plus restarts begin", q=6),
          dict(v="5:28 AM", t="all droplets leased again", q=8),
          dict(v="3 h 3 min", t="from start of rebuilding to all leased", f="5:28 AM minus 2:25 AM")],
 terms={"lease": "a claim that expires unless it is renewed, so a crashed owner cannot hold a resource forever",
        "throttle": "deliberately let in less work than is offered, so the work you accept can finish",
        "congestive collapse": "the state where the system is fully busy but almost nothing useful completes"}),

dict(id="aws-2025-dns", org="AWS", type="outage",
 title="DynamoDB's address went blank: two automated writers raced",
 blocks=["repl", "deploy"],
 system="DynamoDB is AWS's large key-value database. Its address in us-east-1 (dynamodb.us-east-1.amazonaws.com) is kept up to date by automation: a Planner writes DNS plans (which IP addresses to hand out) and several Enactors apply them.",
 happened="One Enactor was running very slowly. Before applying its old plan it had checked that the plan was newer than what was live, but by the time it applied it, that check was stale: a faster Enactor had already applied a newer plan. The slow one overwrote it, and a cleanup step then deleted the old plan, leaving the address with no IP addresses at all. Everything in the region that called DynamoDB failed to find it.",
 fix="AWS disabled the DNS Planner and Enactor automation worldwide and will fix the race and add protections against applying incorrect plans before turning it back on.",
 lesson="A check made on old information is not a check: two writers need the store itself to reject the older write.",
 numbers=[dict(v="11:48 PM", t="start, 19 Oct 2025 PDT", q=3),
          dict(v="2:40 AM", t="DynamoDB errors end", q=4),
          dict(v="2:20 PM", t="last services recovered, 20 Oct", q=3),
          dict(v="14 h 32 min", t="whole event", f="2:20 PM 20 Oct minus 11:48 PM 19 Oct")],
 terms={"DNS": "the internet's phone book: it turns a name like dynamodb.us-east-1.amazonaws.com into IP addresses",
        "race condition": "a bug that appears only when two things happen in an unlucky order",
        "stale": "true when it was read, no longer true when it is used"}),

dict(id="cf-2025-11", org="Cloudflare", type="outage",
 title="A config file that doubled in size crashed the proxy worldwide",
 blocks=["deploy", "degrade"],
 system="Cloudflare's proxy sits in front of millions of websites. Its bot-detection module loads a feature file (the inputs for a machine-learning model) that is regenerated every five minutes and pushed to every server in the world.",
 happened="A permissions change to the ClickHouse database that builds the file made a query return duplicate rows, so the file doubled. The proxy had a hard limit of 200 features (normal use was about 60); the bigger file broke it, and the Rust code treated the error as impossible and crashed (panicked), serving 5xx errors. Because the database was being updated node by node, good and bad files alternated every five minutes, which made it look like an attack.",
 fix="Cloudflare stopped the bad file, pushed a known-good one and restarted services. Its follow-ups: treat its own generated config like untrusted user input, add global kill switches per feature, and (see the 2026 card) roll config out gradually with health checks.",
 lesson="Internal config is input too: validate it, roll it out in stages, and fail to the last good version instead of crashing.",
 numbers=[dict(v="11:20", t="failures begin (UTC, 18 Nov 2025)", q=0),
          dict(v="200", t="feature limit in the proxy", q=3),
          dict(v="~60", t="features in normal use", q=3),
          dict(v="14:30", t="core traffic largely normal", q=6),
          dict(v="17:06", t="all systems normal", q=7)],
 terms={"5xx": "the family of HTTP status codes that mean the server failed (500, 502, 503 ...)",
        "panic": "the program stops itself because it hit a state its author assumed could not happen",
        "kill switch": "a flag that turns one feature off everywhere at once, without a new deploy"}),

dict(id="cf-2025-09", org="Cloudflare", type="outage",
 title="The dashboard attacked its own API",
 blocks=["retry", "deploy"],
 system="Cloudflare's dashboard is a web app; when it loads it calls an internal Tenant Service (a Go service on Kubernetes) to fetch which organisations the user belongs to.",
 happened="A React bug made the page re-run its API call every time it re-rendered, so every open dashboard sent a stream of repeated requests, retries included. A Tenant Service update went out at the same time; together they overwhelmed the service, which then could not recover. Engineers could not even tell retries from new requests in their metrics.",
 fix="A global rate limit on the Tenant Service, much more capacity for it, random delays added to the dashboard's retries, and requests tagged as retry or new. Automatic rollback of the service update would have shortened the second outage.",
 lesson="Your own clients can be your biggest attacker: rate-limit internal APIs and add jitter to client retries.",
 numbers=[],
 terms={"rate limit": "a cap on how many requests a caller may send per second; extra requests are refused quickly",
        "jitter": "a random delay added before each retry so many clients do not retry at the same instant"}),

dict(id="gcp-2025-06", org="Google Cloud", type="outage",
 title="Every region crashed at once, then the restart stampeded the database",
 blocks=["retry", "deploy"],
 system="Service Control is the Google Cloud component that checks every API request against quotas and policies before it is served. It reads policy data that is replicated worldwide within seconds.",
 happened="New quota-check code shipped with no error handling and no feature flag. A policy change with blank fields reached every region, hit the new code path, and crashed Service Control everywhere in a loop. Engineers found it in 10 minutes and flipped the emergency off switch. But in the biggest region, us-central1, all the restarting tasks hit the same database at the same moment (a herd effect), because they had no randomized exponential backoff.",
 fix="Throttled how fast tasks were recreated and moved load to other databases; recovery in us-central1 took about 2 h 40 min. Google will make all changes to critical binaries feature-flag protected and off by default, and audit that its systems use randomized exponential backoff.",
 lesson="Recovery is a load event: restarts need the same backoff and jitter as retries.",
 numbers=[dict(v="10 minutes", t="to identify the root cause", q=2),
          dict(v="~2h 40 mins", t="to fully resolve us-central1", q=5)],
 terms={"feature flag": "a switch in config that turns new code on gradually (one project, one region) and off instantly",
        "exponential backoff": "wait 1 s, then 2 s, then 4 s ... before each retry, so retries slow down as failures continue",
        "herd effect": "many clients doing the same thing at the same instant, so a resource that copes with the average is flattened by the peak"}),

dict(id="cf-2026-02", org="Cloudflare", type="outage",
 title="An empty flag meant \"all\": a cleanup job deleted customers' routes",
 blocks=["deploy", "retry"],
 system="Customers can bring their own IP address ranges (BYOIP) to Cloudflare, which announces them to the internet with BGP. A new automated cleanup task asked an internal API for prefixes pending deletion.",
 happened="The task sent the flag pending_delete with no value. The server read an empty string, took that as \"no filter\", and returned every BYOIP prefix. The task then started withdrawing and deleting all of them until an engineer noticed and stopped it.",
 fix="Reverted the change, re-announced prefixes (800 restored in one step), and gave customers a way to re-advertise themselves. Follow-ups: a typed API schema for such flags, and monitoring that pauses deployments when withdrawals happen too fast or too broadly.",
 lesson="Destructive operations need a blast-radius brake: refuse or pause when a job suddenly touches far more than usual.",
 numbers=[dict(v="1,100", t="prefixes withdrawn", q=2),
          dict(v="6,500", t="BYOIP prefixes in total", q=2),
          dict(v="17%", t="share withdrawn", f="1,100 / 6,500"),
          dict(v="50 min", t="withdrawal window", f="18:46 minus 17:56 UTC")],
 terms={"BGP": "the protocol networks use to tell the rest of the internet \"send traffic for these addresses to me\"",
        "prefix": "a block of IP addresses announced together"}),

dict(id="cf-2026-05", org="Cloudflare", type="architecture",
 title="After two outages: config changes now roll out like code",
 blocks=["deploy"],
 system="Cloudflare's response to the November and December 2025 outages, a programme it called Code Orange: Fail Small.",
 happened="Both 2025 outages were config changes pushed to the whole network in seconds, while software releases already went out gradually. Cloudflare built Snapstone, which packages any unit of configuration and releases it progressively, watching health metrics and rolling back automatically.",
 fix="Health-mediated deployment for configuration by default. Cloudflare says the November bot-file change would now be caught while it affected only a small percentage of traffic.",
 lesson="Treat a config push as a deploy: progressive rollout, health checks, automatic rollback.",
 numbers=[],
 terms={"health-mediated deployment": "release to a small slice, watch error rates, continue only if healthy, roll back automatically if not",
        "progressive rollout": "1% of servers, then 10%, then everything, with a pause to check between steps"}),
]
