"""Build the Case files data: inputs/extracts_*.json (verbatim quotes) + annot_*.py (plain-words cards)
-> cases.json (kept for review) and ../parts/33_js_cases_0data.js (window.CF_DATA).

Checks, failing loudly:
 - every case has extracts and an annotation, ids match one to one;
 - every quoted number's value appears in one of that case's quotes (the quote is linked to the number);
 - every derived number carries its formula (recompute.py checks the arithmetic);
 - every block key is known; no em-dash reaches the page (quotes keep their words; an em-dash is shown as --).
Run: python3 build_cases.py
"""
import glob, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from annot_a import CASES_A
from annot_b import CASES_B
from annot_c import CASES_C

BLOCKS = [
 ("lb", "Load balancing and scaling out", "Spread requests over many identical servers, and add servers as load grows."),
 ("cache", "Caching", "Keep a copy of an answer close by so you do not fetch or compute it again."),
 ("repl", "Replication and consistency", "Keep copies of data on several machines; decide what happens when the copies disagree."),
 ("shard", "Sharding", "Split one database's rows across several machines by a key, such as user or workspace."),
 ("queue", "Queues and backpressure", "Put work in a line for workers, and push back on senders when the line gets too long."),
 ("retry", "Timeouts, retries and idempotency", "Give up after a set wait, try again with growing random gaps, and make repeats harmless."),
 ("degrade", "Circuit breakers and degradation", "Fail small: cut off a sick dependency, shed load, and serve a reduced product."),
 ("deploy", "Deployment and change safety", "Roll changes (code and config) out gradually, watch health, roll back fast."),
 ("obs", "SLOs and observability", "Agree how reliable to be, and see what the system is doing, from outside it."),
 ("gpu", "GPU serving", "Run models: batching, KV cache, memory, routing requests to the right pool."),
]
KEYS = {b[0] for b in BLOCKS}
MONTHS = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()


def norm(s):
    s = s.replace("’", "'").replace("‘", "'").replace("“", '"').replace("”", '"')
    return re.sub(r"\s+", " ", s)


def page_text(s):
    """What the page shows: verbatim except an em-dash, which the knowledge base never prints."""
    return s.replace("—", " -- ").replace("  ", " ")


def nice_date(iso):
    p = iso.split("-")
    if len(p) == 3 and p[2].isdigit():
        return f"{int(p[2])} {MONTHS[int(p[1]) - 1]} {p[0]}"
    if len(p) == 2:
        return f"{MONTHS[int(p[1]) - 1]} {p[0]}"
    return iso


def main():
    ex = {}
    for f in sorted(glob.glob(os.path.join(HERE, "inputs", "extracts_*.json"))):
        ex.update(json.load(open(f)))
    cases = CASES_A + CASES_B + CASES_C
    ids = [c["id"] for c in cases]
    assert len(ids) == len(set(ids)), "duplicate id"
    assert set(ids) == set(ex), (set(ids) ^ set(ex))
    errs, out = [], []
    for c in cases:
        e = ex[c["id"]]
        for b in c["blocks"]:
            if b not in KEYS:
                errs.append(f"{c['id']}: unknown block {b}")
        nums = []
        for n in c["numbers"]:
            if "f" in n:
                nums.append(dict(v=n["v"], t=n["t"], f=n["f"]))
                continue
            hits = [i for i, q in enumerate(e["quotes"]) if norm(n["v"]).lower() in norm(q).lower()]
            if not hits:
                errs.append(f"{c['id']}: number {n['v']!r} not in any quote")
                continue
            qi = n.get("q") if n.get("q") in hits else hits[0]
            nums.append(dict(v=n["v"], t=n["t"], q=qi))
        ev = e["event"]
        out.append(dict(
            id=c["id"], org=c["org"], type=c["type"], title=c["title"], blocks=c["blocks"],
            flagship=bool(c.get("flagship")), date=ev, year=int(ev[:4]), dateText=nice_date(ev),
            system=c["system"], happened=c["happened"], fix=c["fix"], lesson=c["lesson"], note=c.get("note"),
            numbers=nums, terms=[[k, v] for k, v in c["terms"].items()],
            source=e["source"], url=e["url"], url2=e.get("url2"), published=e["published"],
            publishedText=nice_date(e["published"]) if re.match(r"^\d{4}-\d{2}(-\d{2})?$", e["published"]) else e["published"],
            accessed=e["accessed"], quotes=[page_text(q) for q in e["quotes"]]))
    if errs:
        print("\n".join(errs))
        sys.exit(1)
    out.sort(key=lambda c: c["date"], reverse=True)
    data = dict(blocks=[dict(k=k, name=n, def_=d) for k, n, d in BLOCKS], cases=out, accessed="2026-10-04")
    txt = json.dumps(data, ensure_ascii=False, indent=0)
    assert "—" not in txt, "em-dash"
    json.dump(data, open(os.path.join(HERE, "cases.json"), "w"), ensure_ascii=False, indent=1)
    js = ("// ---- Case files (t-cases): data, generated by src/cases/build_cases.py from inputs/extracts_*.json and annot_*.py. Do not edit by hand. ----\n"
          "window.CF_DATA=" + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
    open(os.path.join(HERE, "..", "parts", "33_js_cases_0data.js"), "w").write(js)
    n_out = sum(c["type"] == "outage" for c in out)
    print(f"cases {len(out)} (outages {n_out}, architectures {len(out) - n_out}); numbers {sum(len(c['numbers']) for c in out)}; "
          f"quotes {sum(len(c['quotes']) for c in out)}; js {len(js)} bytes")
    for k, n, _ in BLOCKS:
        print(f"  {k:7s} {sum(k in c['blocks'] for c in out):2d}  {n}")


if __name__ == "__main__":
    main()
