"""Quantise the four toy DDPMs for the browser and measure what quantisation costs.

  uv run --with torch --with numpy python train.py export   (or: python export.py [bits])

Every weight matrix row gets its own scale (max |w| of the row divided by 2^(BITS-1) - 1); each weight is
an integer code of BITS bits (8 by default; codes are offset by 2^(BITS-1) - 1 to be non-negative), packed as bytes and base64-encoded; the row scales are float32, also base64. Writes
parts/20_model_data.js (window.DDPM_W) and model/quant_report.json (bound and sample metrics of the
dequantised models against the float ones, same seeds).
"""
import base64, json, os, sys
import numpy as np
import torch
import toy as Y

HERE = os.path.dirname(os.path.abspath(__file__))
MD = os.path.join(HERE, 'model')
ORDER = ['l1.weight', 'l1.bias', 'p1.weight', 'l2.weight', 'l2.bias', 'p2.weight', 'l3.weight', 'l3.bias', 'p3.weight', 'lo.weight', 'lo.bias']


def quantise(state, bits):
    q = 2 ** (bits - 1) - 1
    enc, deq = {}, {}
    for n in ORDER:
        w = state[n].float().numpy().astype(np.float64)
        w2 = w.reshape(1, -1) if w.ndim == 1 else w
        s = np.abs(w2).max(1, keepdims=True) / q
        s[s == 0] = 1.0
        s = s.astype(np.float32).astype(np.float64)
        c = np.clip(np.round(w2 / s), -q, q).astype(np.int64)
        deq[n] = torch.tensor((c * s).reshape(w.shape), dtype=torch.float32)
        raw = (c + q).astype(np.uint16 if bits > 8 else np.uint8)
        enc[n] = {'shape': list(w.shape), 'scale': base64.b64encode(s[:, 0].astype('<f4').tobytes()).decode(),
                  'q': base64.b64encode(raw.astype('<u2' if bits > 8 else 'u1').tobytes()).decode()}
    return enc, deq


def main(bits=None):
    import train as TR
    bits = bits or int(os.environ.get('BITS', 8))
    out = {'_doc': 'Toy DDPM weights, %d-bit per-row quantised; see src/export.py' % bits, 'bits': bits,
           'T': Y.T, 'beta': [1e-4, 0.02], 'W': Y.W, 'TE': Y.TE, 'variants': {}}
    rep = {'bits': bits, 'variants': {}}
    test = TR.TEST
    for kind in TR.VARIANTS:
        ck = torch.load(os.path.join(MD, kind + '.pt'))
        enc, deq = quantise(ck['ema'], bits)
        out['variants'][kind] = enc
        f = Y.Net(); f.load_state_dict(ck['ema']); f.eval()
        qn = Y.Net(); qn.load_state_dict(deq); qn.eval()
        bf = TR.bound_bpd(f, kind, test[:1000])[0]; bq = TR.bound_bpd(qn, kind, test[:1000])[0]
        sf = TR.sample(f, kind, 1000, 11).numpy(); sq = TR.sample(qn, kind, 1000, 11).numpy()
        rep['variants'][kind] = {'bound_bpd_float': bf, 'bound_bpd_quant': bq,
                                 'samples_float': TR.pr_metrics(sf, test.numpy()), 'samples_quant': TR.pr_metrics(sq, test.numpy()),
                                 'mean_sample_shift_same_seed': float(np.sqrt(((sf - sq) ** 2).sum(1)).mean())}
        print(kind, json.dumps(rep['variants'][kind]), flush=True)
    s = json.dumps(out, separators=(',', ':'))
    open(os.path.join(HERE, 'parts', '20_model_data.js'), 'w').write(
        '// Generated by export.py: the four toy DDPMs of the Run tab (Table 2 variants), %d-bit weights.\nwindow.DDPM_W=%s;\n' % (bits, s))
    json.dump(rep, open(os.path.join(MD, 'quant_report.json'), 'w'), indent=1)
    print('wrote parts/20_model_data.js', len(s), 'bytes')


if __name__ == '__main__':
    main(int(sys.argv[1]) if len(sys.argv) > 1 else None)
