"""Build ../../parts/22_js_rd_data.js (window.RD_DATA) from the recorded outputs in out/.
Every number the Reading tab draws comes from here; check_embed.py verifies the page carries exactly these.
Usage: python3 make_data.py"""
import json, os, re, glob

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
PARTS = os.path.join(HERE, "../../parts")


def kv(name):
    p = os.path.join(OUT, name)
    if not os.path.exists(p):
        return None
    r = {}
    for line in open(p):
        m = re.match(r"(\S+)\s+([-\d.]+)\s*$", line)
        if m:
            r[m.group(1)] = float(m.group(2))
    return r


def text(name, maxlines=None):
    p = os.path.join(OUT, name)
    if not os.path.exists(p):
        return None
    s = open(p).read()
    if maxlines:
        s = "\n".join(s.splitlines()[:maxlines])
    return s


def jload(name):
    p = os.path.join(OUT, name)
    return json.load(open(p)) if os.path.exists(p) else None


def tlb():
    p = os.path.join(OUT, "tlb.txt")
    if not os.path.exists(p):
        return None
    rows = []
    for line in open(p).read().splitlines()[1:]:
        f = line.split("\t")
        rows.append({"lines": int(f[0]), "packed": float(f[1]), "spread": float(f[2]), "thp": float(f[3]), "thp_kb": int(f[4])})
    return rows


CATS = [("shm", r"^/dev/shm/"), ("dataset", r"train\.bin"), ("exe", r"^/usr/bin/python3"), ("heap", r"^\[heap\]"),
        ("stack", r"^\[stack\]"), ("vdso", r"^\[(vdso|vvar)\]"), ("torch", r"/torch/"), ("numpy", r"numpy|openblas|gfortran|scipy"),
        ("clib", r"^/(usr/)?lib/aarch64-linux-gnu/|^/lib/ld-linux"), ("pyext", r"\.so"), ("file", r"^/")]


def cat(perm, name):
    for c, rx in CATS:
        if re.search(rx, name):
            return c
    return "anon_res" if perm.startswith("---") else "anon"


def maps():
    d = os.path.join(OUT, "maps")
    if not os.path.isdir(d):
        return None
    res = {"procs": json.load(open(os.path.join(d, "procs.json")))}
    keyset = {}
    for f in sorted(glob.glob(os.path.join(d, "*.maps"))):
        tag = os.path.basename(f)[:-5]
        regs = []
        for line in open(f):
            p = line.split(None, 5)
            a, b = (int(x, 16) for x in p[0].split("-"))
            regs.append((a, b, p[1], p[5].strip() if len(p) > 5 else ""))
        keyset[tag] = set((r[0], r[1], r[3]) for r in regs)
        totals, runs = {}, []
        for a, b, perm, name in regs:
            c = cat(perm, name)
            t = totals.setdefault(c, [0, 0]); t[0] += 1; t[1] += (b - a) >> 10
            if runs and runs[-1][0] == c and runs[-1][2] == "%x" % a:
                runs[-1][2] = "%x" % b; runs[-1][3] += (b - a) >> 10; runs[-1][4] += 1
            else:
                runs.append([c, "%x" % a, "%x" % b, (b - a) >> 10, 1])
        roll = {}
        for line in open(f[:-5] + ".smaps_rollup").read().splitlines()[1:]:
            k, v = line.split(":")
            roll[k.strip()] = int(v.split()[0])
        # a few real lines to show verbatim: first line of each category in address order
        seen, sample = set(), []
        for line in open(f):
            p = line.split(None, 5)
            c = cat(p[1], p[5].strip() if len(p) > 5 else "")
            if c not in seen or c in ("shm",):
                seen.add(c); sample.append(line.rstrip("\n"))
        res[tag] = {"n": len(regs), "totals": totals, "rollup": roll, "sample": sample}
    m, w = keyset.get("after_fork_main"), keyset.get("after_fork_worker0")
    if m and w:
        res["same_in_worker0"] = len(m & w)
    return res


data = {
    "env": text("env.txt"),
    "syscall": kv("syscall_cost.txt"),
    "ctx": kv("ctxswitch.txt"),
    "tlb": tlb(),
    "counter": text("counter.txt"),
    "futex": text("counter_mutex_futex.txt"),
    "malloc": text("malloc_strace.txt"),
    "epoll": text("asyncio_epoll.txt"),
    "container": text("container_view.txt"),
    "write": jload("write_journey.json"),
    "faults": jload("faults.json"),
    "maps": maps(),
    "vm": text("vm_settings.txt"),
    # measured by the OS simulators tab (src/sim/real/out/), quoted here so both tabs show one set of numbers
    "sim": {k: (open(os.path.join(HERE, "../../sim/real/out", k + ".txt")).read() if os.path.exists(os.path.join(HERE, "../../sim/real/out", k + ".txt")) else None) for k in ("ctxsw", "nice_share", "cow", "race_1cpu", "race_2cpu", "tlb")},
}
js = "// Generated by src/read/code/make_data.py from src/read/code/out/ (recorded 2026-10-05 in kb-os-lab:1). Do not edit.\nwindow.RD_DATA=" + json.dumps(data, separators=(",", ":")) + ";\n"
open(os.path.join(PARTS, "22_js_rd_data.js"), "w").write(js)
print("wrote 22_js_rd_data.js", len(js), "bytes;", {k: (v is not None) for k, v in data.items()})
