"""Write parts/20_js_data.js from inputs/: Anscombe's set III, the CYG OB1 stars, the 141 rivers, and the
real-logit summary (from real_logits.py). Run: python3 mk_data.py"""
import csv, json
a = list(csv.DictReader(open("inputs/anscombe.csv")))
anscombe3 = {"x": [float(r["x3"]) for r in a], "y": [float(r["y3"]) for r in a]}
s = list(csv.DictReader(open("inputs/starsCYG.csv")))
stars = {"x": [float(r["log.Te"]) for r in s], "y": [float(r["log.light"]) for r in s],
         "giants": [11, 20, 30, 34]}  # 1-based observation numbers, robustbase documentation
rivers = [float(r["dat"]) for r in csv.DictReader(open("inputs/rivers.csv"))]
rl = json.load(open("inputs/real_logits.json"))
logits = {"text": rl["text"], "offsets": rl["offsets"], "models": [
    {k: m[k] for k in ("name", "vocab", "tokens", "mean_ce", "mean_logZ", "min_logZ", "max_logZ",
                       "mean_max_logit", "mean_logit", "zloss_1e-4", "logZ_per_token", "bf16_tv_by_offset",
                       "bf16_abs_dce_by_offset")} for m in rl["models"]]}
D = {"anscombe3": anscombe3, "stars": stars, "rivers": rivers, "logits": logits}
open("parts/20_js_data.js", "w").write("// generated by mk_data.py from inputs/ (do not edit)\nwindow.LD=" + json.dumps(D, separators=(",", ":")) + ";\n")
print("ok", len(anscombe3["x"]), len(stars["x"]), len(rivers))
