// ---- The paper's own preprocessed examples (Appendix D, §2.4) and the playground's preset texts ----
const T2T=[
 {k:'EnDe',n:'Translation (EnDe)',i:'translate English to German: That is good.',o:'Das ist gut.',note:'The example of §2.4 and Figure 1.'},
 {k:'MNLI',n:'MNLI',i:'mnli hypothesis: The St. Louis Cardinals have always won. premise: yeah well losing is i mean i’m i’m originally from Saint Louis and Saint Louis Cardinals when they were there were uh a mostly a losing team but',o:'contradiction',note:'Appendix D.3: the label becomes a word; original target 2.'},
 {k:'CoLA',n:'CoLA',i:'cola sentence: John made Bill master of himself.',o:'acceptable',note:'Appendix D.1: original target 1.'},
 {k:'STSB',n:'STS-B',i:'stsb sentence1: Representatives for Puretunes could not immediately be reached for comment Wednesday. sentence2: Puretunes representatives could not be located Thursday to comment on the suit.',o:'3.2',note:'Appendix D.8: the regression score 3.25 is rounded to the nearest 0.2 and written as text.'},
 {k:'WSC',n:'WSC',i:'wsc: The stable was very roomy, with four good stalls; a large swinging window opened into the yard , which made *it* pleasant and airy.',o:'stable',note:'Appendix D.13: the pronoun is marked with asterisks and the model names its referent.'},
 {k:'COPA',n:'COPA',i:'copa choice1: Many citizens relocated to the capitol. choice2: Many citizens took refuge in other territories. premise: Political violence broke out in the nation. question: effect',o:'True',note:'Appendix D.10: original target 1, written True.'},
 {k:'SQuAD',n:'SQuAD',i:'question: What does increased oxygen concentrations in the patient’s lungs displace? context: Hyperbaric (high-pressure) medicine uses special oxygen chambers to increase the partial pressure of O2 around the patient and, when needed, the medical staff. … Increased O2 concentration in the lungs helps to displace carbon monoxide from the heme group of hemoglobin. …',o:'carbon monoxide',note:'Appendix D.15, context shortened here (…); the answer is generated token by token, not pointed to.'},
 {k:'CNNDM',n:'Summarisation',i:'summarize: marouane fellaini and adnan januzaj continue to show the world they are not just teammates but also best mates. the manchester united and belgium duo both posted pictures of themselves out at a restaurant on monday night ahead of their game against newcastle on wednesday . …',o:'the belgian duo took to the dance floor on monday night with some friends . manchester united face newcastle in the premier league on wednesday . …',note:'Appendix D.14, shortened here (…).'},
 {k:'EnRo',n:'Translation (EnRo)',i:'translate English to Romanian: Taco Bell said it plans to add 2,000 locations in the US by 2022.',o:'Taco Bell a afirmat că, până în 2022, intenționează să deschidă 2000 de restaurante în SUA.',note:'Appendix D.18 (Romanian diacritics restored; the HTML extraction garbles them).'}];
const PRESETS=['Thank you for inviting me to your party last week .',
 'Transfer learning , where a model is first pre-trained on a data-rich task before being fine-tuned on a downstream task , has emerged as a powerful technique in natural language processing ( NLP ) . The effectiveness of transfer learning has given rise to a diversity of approaches , methodology , and practice .',
 'We only retained lines that ended in a terminal punctuation mark ( i.e. a period , exclamation mark , question mark , or end quotation mark ) .'];
// The worked examples of Figure 2 and Table 3, on the sentence "Thank you for inviting me to your party last week ."
const FIG_TOK='Thank you for inviting me to your party last week .'.split(' ');
const FIG={bert:{mask:[0,0,1,1,0,0,0,0,1,0,0],inp:['Thank','you','<M>','<M>','me','to','your','party','~apple','week','.'],tgt:FIG_TOK.slice(),full:1},
 iid:{mask:[0,0,1,1,0,0,0,0,1,0,0],inp:['Thank','you','<X>','me','to','your','party','<Y>','week','.'],tgt:['<X>','for','inviting','<Y>','last','<Z>']},
 span:{mask:[0,0,1,1,1,0,1,1,1,0,0],inp:['Thank','you','<X>','to','<Y>','week','.'],tgt:['<X>','for','inviting','me','<Y>','your','party','last','<Z>']}};
