#!/usr/bin/env python3
"""Write the generated data parts from src/inputs and src/recordings (all redacted, all committed):
parts/19_js_data_runs.js (window.HR_DATA: every recorded run, wire view) and
parts/19_js_data_map.js (window.HM_DATA: Aider's repo map lab)."""
import json
from pathlib import Path

S = Path(__file__).resolve().parent
P = S / "parts"


def js(name, var, obj):
    s = json.dumps(obj, separators=(",", ":"), ensure_ascii=False)
    for bad in ("/" + "Us" + "ers/", "Us" + "ers-", Path.home().name, "glp" + "at", "sk-" + "ant", "\u2014", "claude" + "-502"):
        assert bad not in s, (name, bad)
    s = s.replace("</", "<\\/")
    (P / name).write_text(f"// generated by src/build_data.py, do not edit\nwindow.{var}={s};\n")
    print(name, len(s))


js("19_js_data_map.js", "HM_DATA", json.loads((S / "inputs" / "repomap_lab.json").read_text()))

order = json.loads((S / "recordings" / "order.json").read_text()) if (S / "recordings" / "order.json").exists() else []
runs = [json.loads((S / "recordings" / f"{r}.json").read_text()) for r in order]
js("19_js_data_runs.js", "HR_DATA", {"runs": runs})
