#!/usr/bin/env python3
"""Write src/coverage.json: every fact of the two old Notion pages (src/live.md) and where this page carries it,
or why it was dropped. Checked against primary sources on 2026-10-06 (verdicts in the Corrections section)."""
import json
from pathlib import Path

R, OH, CL = "Reading", "old page 'Open-source harnesses'", "old page 'OpenAI and Google harnesses'"
F = [
 # Open-source harnesses
 (OH, "opencode repo and architecture guide as resources", "Further reading: Read the source (opencode) and opencode docs; the Medium guide dropped (secondary, describes the old Go TUI)"),
 (OH, "Aider repo map docs as resource", "Further reading: Aider repository map"),
 (OH, "goose repo and docs as resources", "Reading 10 goose (docs links)"),
 (OH, "SWE-agent ACI docs and paper as resources", "Reading 7; Further reading: SWE-agent paper"),
 (OH, "mini-SWE-agent repo as resource; about 65% SWE-bench Verified", "Reading 7 (corrected: README reports above 74%); Corrections table"),
 (OH, "Cline repo as resource", "Reading 10 Cline"),
 (OH, "open harnesses are readable and where ideas get tested", "Reading 0 (lead)"),
 (OH, "opencode: provider-agnostic, 165k+ stars, about 5M monthly devs, MIT", "Reading 4 (corrected to 211,898 stars, vendor 16M); Corrections"),
 (OH, "opencode client/server: TS/Bun server, Go/Bubble Tea TUI over HTTP/SSE, many frontends", "Reading 4 Architecture (TUI corrected to TypeScript/OpenTUI); Corrections"),
 (OH, "opencode: 75+ providers via models.dev, per-agent tools and permissions, LSP, plugins, share links", "Reading 4 (per-model prompts and tools, LSP diagnostics, plugins, permissions); share links dropped as minor"),
 (OH, "Anthropic blocked third-party OAuth Jan 2026; Claude via API key only", "Reading 4 'Which subscriptions work' (no dated Anthropic statement; terms; opencode v1.3.0); Corrections"),
 (OH, "OpenAI now sponsors opencode", "Dropped: no primary source; Corrections"),
 (OH, "OpenAI ends Cursor model access Nov 12 after SpaceX acquisition, trust clause, ten weeks", "Reading 10 'Model access is a dependency' (corrected mechanism and notice); Corrections"),
 (OH, "model access is allocated rather than sold: supply risk", "Reading 10 (same point, sourced)"),
 (OH, "opencode instructive: server/UI separation, provider abstraction, per-agent permissions", "Reading 4 'What to steal'"),
 (OH, "Aider: 2023, Python, Apache-2.0", "Reading 5"),
 (OH, "Aider: stalled after Aug 2025 tagged release, nothing tagged since", "Reading 5 (corrected: v0.86.1/0.86.2 tags, PyPI Feb 2026, last commit May 2026); Corrections"),
 (OH, "Aider repo map: tree-sitter, dependency graph, PageRank, fixed token budget", "Reading 5; Repo map lab tab (run for real)"),
 (OH, "repo map vs Cursor semantic search vs Claude Code agentic grep", "Repo map lab intro (three answers)"),
 (OH, "edit formats: unified diff vs search/replace vs whole, edit format leaderboard, retry on malformed", "Reading 5 Edits (formats, reflections, 'Did you mean'); leaderboard via edit-formats link"),
 (OH, "Aider git-native: auto-commit, undo is git revert", "Reading 5 Safety (corrected: /undo checks out files and soft-resets); Corrections"),
 (OH, "Aider /architect two-model mode, voice, watch-files", "Reading 5 Extend (architect, watch); voice dropped as minor"),
 (OH, "goose: Rust, CLI and desktop, donated to LF AAIF Apr 2026, 15+ providers", "Reading 10 goose (corrected: founding project 9 Dec 2025); Corrections"),
 (OH, "goose: everything is an MCP extension, first MCP-native harness", "Reading 10 goose ('first' dropped: unverifiable superlative)"),
 (OH, "goose: recipes, scheduled runs, desktop app, more autonomous defaults", "Reading 10 goose (recipes, scheduler, autonomous default)"),
 (OH, "Cline: Apache-2.0, 5M+ installs, Plan/Act, MCP marketplace, diff approval, checkpoints, v3.58 subagents, CLI 2.0, BYOK", "Reading 10 Cline (11M+ claimed; subagents v3.58.0; headless CLI); MCP marketplace, checkpoints, BYOK dropped as product detail (atlas owns)"),
 (OH, "Roo Code: custom modes, cloud/SOC 2, archived May 2026, community-maintained", "Reading 10 (corrected: shut down 15 May 2026); Corrections"),
 (OH, "Kilo Code: merged Cline and Roo, autocomplete, JetBrains, about 300B tokens/day", "Reading 10 (origin; opencode-derived core; Anaconda; 10T+ tokens/month vendor claim)"),
 (OH, "fork lineage insight: forks overtake originals when moat is UX", "Dropped: opinion without evidence; Roo shutdown shown instead"),
 (OH, "SWE-agent ACI: windowed viewer, lint-on-edit, concise output", "Reading 7"),
 (OH, "SWE-agent guardrails only with false-positive rate about 0", "Corrections (not in paper; trade-off quote instead, Reading 7)"),
 (OH, "mini-SWE-agent: about 100 lines, bash only, no tool-calling API, linear history", "Reading 7 (190 lines; v2 defaults to tool calling, text mode opt-in)"),
 (OH, "minimal harnesses close the gap on short tasks; 21 model-harness pairs Sep 2026 study", "Reading 7 'Why it matters' and the parent topic's section 7 (HarnessTax, linked)"),
 (OH, "OpenHands ex-OpenDevin, sandboxed runtime and browser", "Reading 6"),
 (OH, "convergent architecture: loop core, MCP, permissions, plan/act, git undo, headless", "Reading 0 table and the per-harness sections"),
 (OH, "Pizza Bot by AWS, Sep 2026, inbox for background agents on DeepAgents/LangGraph", "Reading 10 (corrected: developed at Amazon, own org, v1.0.0 8 Sep 2026); Corrections"),
 (OH, "read Cline or mini-SWE-agent first; Aider repomap and SWE-agent ACI deepest ideas", "Further reading: Read the source (mini-SWE-agent first)"),
 # OpenAI and Google harnesses
 (CL, "Codex docs, cloud page, repo, Gemini CLI repo, Antigravity posts, Jules extension post as resources", "Further reading and Reading 2, 3, 9 links (docs moved to learn.chatgpt.com)"),
 (CL, "Codex: three surfaces (CLI, cloud, IDE/app) on GPT Codex models; Agents API sells the loop", "Reading 2 and 9"),
 (CL, "Codex CLI: Apache-2.0, TypeScript Apr 2025, Rust rewrite mid-2025, about 114k stars", "Reading 2 (announced 30 May 2025; 127,966 stars); Corrections"),
 (CL, "Codex: kernel sandbox Seatbelt and Landlock+seccomp, workspace-write, network off, approval modes suggest/auto/full-access", "Reading 2 Safety (bubblewrap+seccomp; sandbox modes and approval policies); Corrections"),
 (CL, "Codex started kernel-first while Claude Code enforces at application layer", "Reading 0 table (containment row) and Reading 2; Claude Code side owned by the Claude Code page"),
 (CL, "Codex wire protocol, SDKs, MCP client and server, codex exec, GitHub Action", "Reading 2 Extend (mcp-server removed in 0.154.0); GitHub Action dropped (atlas owns surfaces)"),
 (CL, "Codex config.toml and AGENTS.md; Claude Code reads AGENTS.md from 2.1.277", "Reading 2 Context; Corrections note (confirmed, only without CLAUDE.md)"),
 (CL, "September 2026 release train: 0.154.0, desktop app Sep 11, max/ultra effort, ExternalMessage, resume/fork, service tiers", "Corrections (Python SDK python-v0.154.0; no separate desktop app)"),
 (CL, "Deep Research inside Codex Sep 9; GPT-5.6 and GPT-6 Astra; persistent Codex reported", "Dropped: unconfirmed; Corrections"),
 (CL, "Codex vs Claude Code: fewer extension layers, stronger isolation, ChatGPT bundling", "Reading 2 Extend shows Codex now has hooks, skills, plugins, subagents (old contrast outdated)"),
 (CL, "Codex cloud: containers, start from web, IDE, CLI, GitHub, GitLab, Linear, Slack; best-of-N --attempts; setup scripts, universal image, internet policy", "Reading 9 Codex cloud"),
 (CL, "pattern: local CLI interactive, cloud fleet for burn-down", "Reading 9 Codex cloud"),
 (CL, "Agents API public beta Sep 10 2026, managed sessions, Blaxel/Cloudflare/E2B/Modal, hosted or self-hosted sandboxes", "Reading 9 Hosted loops (nine partners); Corrections"),
 (CL, "harness becomes something you buy; context policy leaves your process", "Reading 9 Hosted loops"),
 (CL, "Anthropic same day: auto permission policies for Managed Agents, terminal attach to live session", "Reading 9 (ant beta:sessions connect, CLI v1.32.0)"),
 (CL, "ARC Prize Provider Adapter harness", "Dropped: sources disagree (recorded in the parent topic and FACTS)"),
 (CL, "Google: Gemini for Windows Sep 10, Alt+Space; Google Home MCP from Sep 16 with Premium Advanced and Cloud project", "Reading 9 small note (Home MCP date unconfirmed); Corrections"),
 (CL, "Gemini CLI: Apache-2.0, Jun 2025, ReAct loop, tools, MCP, GEMINI.md, checkpointing, headless, 1M context, free tier", "Reading 3 (tools and context from source; checkpointing dropped as minor; 1M confirmed for auto model)"),
 (CL, "Gemini CLI extensions: gemini-extension.json bundles", "Reading 3 Extend"),
 (CL, "Gemini CLI free usage moved to Antigravity CLI June 2026", "Reading 3 (confirmed, 18 June 2026)"),
 (CL, "Antigravity: Nov 2025, Gemini 3 Pro, VS Code fork, Agent Manager, browser via Chrome extension", "Reading 9 (VS Code fork not in launch post: Corrections)"),
 (CL, "Antigravity Artifacts: verification at artifact level; cross-surface memory", "Reading 9 Antigravity (memory dropped: not checked)"),
 (CL, "Antigravity model-flexible; 2.0 at I/O 2026 with Gemini 3.5 Flash", "Reading 9 (2.0 is a separate app with no IDE)"),
 (CL, "Jules: async, GA Aug 2025, cloud VM, branch/PR, audio changelogs, Jules Tools CLI and API", "Reading 9 Jules (audio changelogs dropped: not checked)"),
 (CL, "Jules extension for Gemini CLI: delegate background tasks", "Reading 9 Jules"),
 (CL, "comparison table Codex / Google / Claude Code on seven rows", "Reading 0 table (six open harnesses); vendor rows in the parent's Harness atlas"),
 (CL, "convergent evolution: CLI + IDE + cloud + MCP + memory file + hosted loop", "Reading 0 and 9"),
 (CL, "Meta Muse Code Sep 2 2026, terminal and CI, sandbox-and-approval defaults; CI replaces approval with policy", "Reading 9 (date unconfirmed); Corrections"),
 (CL, "transferable ideas: Codex kernel sandbox and wire protocol; Antigravity artifact review; Jules VM per task", "Reading 2 'What to steal', Reading 9"),
]
out = [{"source": s, "fact": f, "where": w} for s, f, w in F]
Path(__file__).resolve().parent.joinpath("coverage.json").write_text(json.dumps(out, indent=1))
print(len(out), "facts;", sum("Dropped" in x["where"] for x in out), "dropped")
