// ---- On the wire tab (t-wire): helpers, numbers in the prose, the request, the waterfall ----
// Every number and byte comes from window.WI_DATA (31_js_wi_0data.js, generated by src/wire/build_data.py from src/wire/raw/).
window.WI=(function(){
  const D=window.WI_DATA,$=id=>document.getElementById(id);
  const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const f1=x=>x==null||isNaN(x)?'n/a':(Math.round(x*10)/10).toFixed(1);
  const f0=x=>x==null||isNaN(x)?'n/a':String(Math.round(x));
  const ms=x=>(x<10?f1(x):f0(x))+' ms';
  const width=el=>{const w=el&&el.clientWidth;return w&&w>40?w:Math.max(280,Math.min(860,(document.documentElement.clientWidth||900)-40))};
  const RM=!!(window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches);
  const renders=[];
  function onRender(f){renders.push(f);window.TAB_RENDER=window.TAB_RENDER||{};(window.TAB_RENDER['t-wire']=window.TAB_RENDER['t-wire']||[]).push(f)}
  let rt=0;addEventListener('resize',()=>{const t=$('t-wire');if(!t||t.hidden)return;clearTimeout(rt);rt=setTimeout(()=>renders.forEach(f=>{try{f()}catch(e){}}),80)});
  const svg=(w,h,body,label)=>'<svg viewBox="0 0 '+w+' '+h+'" width="'+w+'" height="'+h+'" role="img" aria-label="'+esc(label||'')+'">'+body+'</svg>';
  const tx=(x,y,s,o)=>{o=o||{};return '<text x="'+x+'" y="'+y+'"'+(o.a?' text-anchor="'+o.a+'"':'')+' font-size="'+(o.fs||11)+'"'+(o.fill?' fill="'+o.fill+'"':'')+(o.w?' font-weight="'+o.w+'"':'')+(o.cls?' class="'+o.cls+'"':'')+'>'+s+'</text>'};
  const seg=(el,f)=>el.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;el.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));f(b.dataset.m)});
  // the stepper controller is the shared Reading one (RD.anim); it registers its redraw on t-read, so we re-register ours here
  function anim(o){const a=RD.anim(o);onRender(()=>a.redraw());return a}
  return {D,$,esc,f1,f0,ms,width,RM,onRender,svg,tx,seg,anim};
})();

// numbers quoted in the prose: <span data-wi="key">
(function(){
  const {D,f0,f1,ms}=WI,E=D.env,H=D.hol;
  const date=(E.date_utc||'').slice(0,10);
  const V={
    date:()=>date,
    prefill:()=>D.server.first_token_delay_s+' s',gap:()=>D.server.token_gap_s+' s',
  };
  WI.V=V;
  document.querySelectorAll('#t-wire [data-wi]').forEach(el=>{const f=V[el.dataset.wi];el.textContent=f?f():'??'});
})();

// ---- 1. the request and the response ----
(function(){
  const {D,$,esc,f0,f1,svg,tx,width,onRender,seg}=WI,Q=D.request;
  let mode='req';
  function show(){
    const inv=$('wi-req-inv').checked,s=mode==='req'?Q.h1_request:Q.h1_response;
    const h=s.split('\n').map((ln,i,arr)=>{const cr=ln.endsWith('\r'),core=cr?ln.slice(0,-1):ln,last=i===arr.length-1;
      let o=mode==='resp'&&/^[0-9a-f]{1,3}$/.test(core)&&i>0?'<span class="wi-hl">'+esc(core)+'</span>':esc(core);
      if(inv)o+=(cr?'<span class="wi-inv">\u240d</span>':'')+(last?'':'<span class="wi-inv">\u240a</span>');return o}).join('\n');
    $('wi-req-pre').innerHTML=h;
    const body=new TextEncoder().encode(Q.body).length,req=new TextEncoder().encode(Q.h1_request).length,res=new TextEncoder().encode(Q.h1_response).length;
    const head=Q.h1_response.indexOf('\r\n\r\n')+4;
    const sse=sseBytes();
    $('wi-req-cap').innerHTML=mode==='req'
      ?'<b>'+req+' bytes</b> as sent: '+(req-body)+' bytes of HTTP/1.1 head (request line and headers, each line ending in CR LF, then an empty line) and the '+body+'-byte JSON body. The key is a fake placeholder. Source: <code>raw/h1_request.bin</code>.'
      :'<b>'+res+' bytes</b> as received: a '+head+'-byte head, then the body in <b>chunks</b> (highlighted: each chunk starts with its size in hexadecimal, RFC 9112 section 7.1, because the server does not know the length in advance), ending with a zero-size chunk. The SSE text the app actually parses is '+sse+' bytes. Source: <code>raw/h1_response.bin</code>.';
  }
  function sseBytes(){const r=Q.h1_response,b=r.slice(r.indexOf('\r\n\r\n')+4);let p=0,out=0;
    for(let k=0;k<50;k++){const e=b.indexOf('\r\n',p);if(e<0)break;const n=parseInt(b.slice(p,e),16);if(!n)break;out+=n;p=e+2+n+2}return out}
  function arrivals(){
    const el=$('wi-req-arr'),w=width(el),A=Q.arrivals.recv,tmax=Math.max(...A.map(a=>a.t_ms))*1.05,L=40,Rr=14,h=86;
    const x=t=>L+(w-L-Rr)*t/tmax;
    // which text arrived in each read
    const r=Q.h1_response;let off=0;const labels=A.map(a=>{const s=r.slice(off,off+a.bytes);off+=a.bytes;
      const toks=[...s.matchAll(/"text":"([^"]*)"/g)].map(m=>'"'+m[1]+'"');
      if(s.startsWith('HTTP/'))return s.includes('message_start')?'head + message_start':'head';if(s.includes('message_stop')&&!toks.length)return 'message_stop';if(s.includes('message_start'))return 'message_start';
      if(toks.length)return toks.join(' ')+(s.includes('message_stop')?' + stop':'');if(/^0\r\n/.test(s))return 'end';return a.bytes+' B'});
    for(let i=A.length-1;i>0;i--)if(A[i].t_ms-A[i-1].t_ms<3){labels[i-1]+=' + '+labels[i];labels[i]=''}
    let b='<line x1="'+L+'" x2="'+(w-Rr)+'" y1="50" y2="50" stroke="var(--line)"/>';
    for(let t=0;t<=tmax;t+=50){b+='<line x1="'+x(t)+'" x2="'+x(t)+'" y1="47" y2="53" stroke="var(--mute)"/>'+WI.tx(x(t),68,t+(t===0?' ms':''),{a:'middle',fill:'var(--mute)',fs:10})}
    A.forEach((a,i)=>{const X=x(a.t_ms);b+='<rect x="'+(X-2)+'" y="'+(50-Math.min(30,6+a.bytes/12))+'" width="4" height="'+Math.min(30,6+a.bytes/12)+'" fill="var(--acc)"><title>'+WI.esc(labels[i])+': '+a.bytes+' bytes at '+f1(a.t_ms)+' ms</title></rect>';
      const vis=labels.slice(0,i).filter(x=>x).length,up=vis%2===0;if(labels[i])b+=WI.tx(X,up?12:84,WI.esc(labels[i]),{a:X<L+40?'start':X>w-60?'end':'middle',fs:10})});
    el.innerHTML=svg(w,90,b,'Arrival time of each read of the response');
  }
  seg($('wi-req-seg'),m=>{mode=m;show()});$('wi-req-inv').addEventListener('change',show);
  show();arrivals();onRender(arrivals);
})();

// ---- 2. the waterfall ----
(function(){
  const {D,$,esc,f1,f0,ms,svg,tx,width,onRender,seg}=WI,Wf=D.waterfall;
  const PH=[['dns','DNS lookup','var(--wi-dns)'],['tcp','TCP connect','var(--wi-tcp)'],['tls','TLS handshake','var(--wi-tls)'],['fb','Request out, first byte back','var(--wi-wait)'],['ft','Waiting for the first token','var(--wi-pre)'],['lt','Tokens streaming','var(--wi-str)']];
  let mode='local',zoom='all',sel=null;
  const leg=()=>{$('wi-wf-leg').innerHTML=(mode==='public'?PH.slice(0,4).map((p,i)=>i===3?['fb','Request out, first byte back',p[2]]:p):PH).map(p=>'<span><i style="background:'+p[2]+'"></i>'+p[1]+'</span>').join('')+(mode!=='public'?'<span><i style="background:repeating-linear-gradient(45deg,var(--wi-tcp) 0 3px,var(--wi-tls) 3px 6px)"></i>QUIC + TLS together (HTTP/3)</span>':'')};
  function rowsLocal(){const S=Wf[mode],out=[];
    ['h1','h2','h3'].forEach(p=>{const m=S[p].median,b=[];let prev=0;
      const add=(k,end,col)=>{if(end==null)return;end=Math.max(end,prev);b.push({k,a:prev,b:end,col});prev=end};
      if(p==='h3'){add('qt',m.tls,'url(#wi-hatch)')}else{add('dns',m.dns,'var(--wi-dns)');add('tcp',m.tcp,'var(--wi-tcp)');add('tls',m.tls,'var(--wi-tls)')}
      add('fb',m.fb,'var(--wi-wait)');add('ft',m.ft,'var(--wi-pre)');add('lt',m.lt,'var(--wi-str)');
      out.push({id:p,name:{h1:'HTTP/1.1',h2:'HTTP/2',h3:'HTTP/3'}[p],sub:{h1:'TCP + TLS 1.3',h2:'TCP + TLS 1.3',h3:'QUIC (UDP)'}[p],segs:b,n:S[p].n})});return out}
  function rowsPublic(){return Object.keys(Wf.public).sort().map(h=>{const v=Wf.public[h],b=[];let prev=0;
      const add=(k,end,col)=>{end=Math.max(end,prev);b.push({k,a:prev,b:end,col});prev=end};
      const src=zoom==='first'?{dns:v.first.time_namelookup,tcp:v.first.time_connect,tls:v.first.time_appconnect,ttfb:v.first.time_starttransfer}:v;
      add('dns',src.dns,'var(--wi-dns)');add('tcp',src.tcp,'var(--wi-tcp)');add('tls',src.tls,'var(--wi-tls)');add('fb',src.ttfb,'var(--wi-wait)');
      return {id:h,name:h.replace('https://','').replace(/\/.*$/,''),sub:h.replace(/^https:\/\/[^/]+/,'')||'/',segs:b,n:v.n}})}
  function draw(){
    leg();const el=$('wi-wf'),w=width(el),rows=mode==='public'?rowsPublic():rowsLocal();
    let tmax=Math.max(...rows.map(r=>r.segs[r.segs.length-1].b));
    if(mode!=='public'&&zoom==='fb')tmax=Math.max(...rows.map(r=>r.segs.find(s=>s.k==='fb').b));
    tmax*=1.06;
    const narrow=w<520,L=narrow?8:128,Rr=10,rh=narrow?50:36,top=8,h=top+rows.length*rh+30;
    const x=t=>L+(w-L-Rr)*Math.min(t,tmax)/tmax;
    let b='<defs><pattern id="wi-hatch" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="3" height="6" fill="var(--wi-tcp)"/><rect x="3" width="3" height="6" fill="var(--wi-tls)"/></pattern></defs>';
    const step=[1,2,5,10,20,50,100,200,500,1000].find(s=>tmax/s<=(narrow?5:8))||1000;
    for(let t=0;t<=tmax;t+=step){b+='<line x1="'+x(t)+'" x2="'+x(t)+'" y1="'+top+'" y2="'+(h-24)+'" stroke="var(--line)"/>'+tx(x(t),h-10,t+(t===0?'':' ms'),{a:t===0?'start':'middle',fill:'var(--mute)',fs:10})}
    rows.forEach((r,i)=>{const y=top+i*rh,by=narrow?y+18:y+6,bh=narrow?18:20;
      b+=narrow?tx(L,y+12,'<tspan font-weight="600">'+esc(r.name)+'</tspan> <tspan fill="var(--mute)">'+esc(r.sub)+'</tspan>',{fs:11}):tx(L-8,y+15,esc(r.name),{a:'end',w:600})+tx(L-8,y+28,esc(r.sub),{a:'end',fill:'var(--mute)',fs:10});
      r.segs.forEach(s=>{if(s.a>=tmax)return;const X=x(s.a),Wd=Math.max(s.b>s.a?1.5:0,x(s.b)-X);
        b+='<rect data-row="'+i+'" x="'+X+'" y="'+by+'" width="'+Wd+'" height="'+bh+'" fill="'+s.col+'" style="cursor:pointer"'+(sel===i?' stroke="var(--ink)" stroke-width="1.5"':'')+'><title>'+esc(r.name)+': '+s.k+' '+f1(s.a)+' to '+f1(s.b)+' ms</title></rect>'});
      const end=r.segs[r.segs.length-1].b;if(end<=tmax){const lx=x(end)+4,lab=f0(end)+' ms';b+=lx+40<w?tx(lx,by+bh/2+4,lab,{fs:10.5}):''}});
    el.innerHTML=svg(w,h,b,'Waterfall of the request, phase by phase');
    el.querySelectorAll('rect[data-row]').forEach(n=>n.addEventListener('click',()=>{sel=+n.dataset.row;draw()}));
    note(rows);
  }
  function note(rows){
    const n=$('wi-wf-note');let h='';
    if(mode==='public'){
      const P=Wf.public,ks=Object.keys(P).sort();
      h='<h4>Public hosts, '+(zoom==='first'?'first of five runs (cold DNS cache)':'median of '+P[ks[0]].n+' runs')+'</h4><p>Read-only GETs with curl over HTTP/2 from this laptop on '+WI.V.date()+'. The TCP connect time is one round trip to the nearest server of each host; the TLS handshake (TLS 1.3) adds about one more. What comes after depends on the host: these are error or empty pages, not model calls, so the gap to the first byte is the server deciding to say "not found" or "unauthorised".</p>'+
        '<div class="wi-src">Hosts: '+ks.map(k=>'<code>'+esc(k)+'</code>').join(', ')+'. DNS in the first run took '+ks.map(k=>f0(P[k].first.time_namelookup)).join(', ')+' ms (same order): a real lookup costs hundreds of milliseconds through this network\'s filtering resolver, while a few milliseconds means the operating system already had the answer cached (api.anthropic.com had just been asked for by <code>dig</code>). In later runs every host is cached: about '+f1(P[ks[0]].dns)+' ms. Source: <code>raw/public_curl.tsv</code>.</div>';
    }else{
      const S=Wf[mode],m2=S.h2.median,m3=S.h3.median;
      h='<h4>'+(mode==='local'?'Loopback':'Emulated 50 ms round trip')+', median of '+S.h2.n+' runs each</h4>'+
        (mode==='local'?'<p>With no distance to cross, opening TCP takes '+ms(m2.tcp-m2.dns)+' and the whole TLS 1.3 handshake '+ms(m2.tls-m2.tcp)+': the cost of a handshake here is computing, not travel. The answer is dominated by the server: '+ms(m2.ft-m2.fb)+' waiting for the first token, then '+ms(m2.lt-m2.ft)+' for the other four.</p>'
          :'<p>Add 50 ms of round trip and the picture changes: the TLS handshake takes '+ms(m2.tls-m2.tcp)+' (one round trip), sending the request and getting the first byte back another '+ms(m2.fb-m2.tls)+' (one more). HTTP/3 does the transport and TLS handshakes together in '+ms(m3.tls)+'. The TCP connect is near zero here only because our proxy, not the far server, answers it: against a real host it is one more round trip (see Public hosts).</p>')+
        '<div class="wi-src">DNS is not looked up for the local server: its name, <code>api.llm.test</code>, is pinned to 127.0.0.1 (<code>.test</code> is reserved and never resolves, RFC 6761 section 6.2). Clients: <code>wire_client.py</code> (Python '+esc(D.env.python)+', '+esc(D.env.python_ssl)+') for HTTP/1.1 and HTTP/2, <code>h3_client.py</code> (aioquic '+esc((D.env.hypercorn||'').replace(/.*aioquic: ([0-9.]+).*/,'$1'))+') for HTTP/3. Source: <code>raw/client_h1'+(mode==='netem'?'_netem':'')+'.json</code>, <code>raw/client_h2'+(mode==='netem'?'_netem':'')+'.json</code>, <code>raw/h3_'+(mode==='netem'?'netem':'local_runs')+'.json</code>.</div>';
    }
    if(sel!=null&&rows[sel]){const r=rows[sel];
      if(mode==='public'){const v=Wf.public[r.id];h+='<div class="tw"><table class="wi-t"><tr><th>Run</th><th class="num">DNS</th><th class="num">TCP done</th><th class="num">TLS done</th><th class="num">First byte</th></tr>'+v.runs.map((x,i)=>'<tr><td>'+(i+1)+'</td><td class="num">'+f1(x.time_namelookup)+'</td><td class="num">'+f1(x.time_connect)+'</td><td class="num">'+f1(x.time_appconnect)+'</td><td class="num">'+f1(x.time_starttransfer)+'</td></tr>').join('')+'</table></div>'}
      else{const v=Wf[mode][r.id];h+='<div class="tw"><table class="wi-t"><tr><th>'+esc(r.name)+' run</th><th class="num">TCP</th><th class="num">TLS done</th><th class="num">Sent</th><th class="num">First byte</th><th class="num">First token</th><th class="num">Last token</th></tr>'+v.runs.map((x,i)=>'<tr><td>'+(i+1)+'</td><td class="num">'+f1(x.tcp)+'</td><td class="num">'+f1(x.tls)+'</td><td class="num">'+f1(x.sent)+'</td><td class="num">'+f1(x.fb)+'</td><td class="num">'+f1(x.ft)+'</td><td class="num">'+f1(x.lt)+'</td></tr>').join('')+'</table></div><p class="wi-src">Milliseconds from the start of each run. Run 1 is often slower: the first connection of a process also loads certificates and warms caches.</p>'}}
    else h+='<p class="wi-src">Tap a bar to see every run.</p>';
    n.innerHTML=h;
  }
  function curlTab(){
    const rows=[];const add=(lab,o)=>Object.keys(o).sort().forEach(k=>{const v=o[k];rows.push('<tr><td>'+lab+'</td><td>'+esc(k.replace('|',' HTTP/').replace(/\|.*/,''))+'</td><td class="num">'+v.n+'</td><td class="num">'+f1(v.dns)+'</td><td class="num">'+f1(v.tcp)+'</td><td class="num">'+f1(v.tls)+'</td><td class="num">'+f1(v.ttfb)+'</td><td class="num">'+f1(v.total)+'</td></tr>')});
    add('Loopback',Wf.curl_local);add('Emulated',Wf.curl_netem);add('Public',Wf.public);
    $('wi-wf-curl').innerHTML='<table class="wi-t"><tr><th>Path</th><th>Target</th><th class="num">Runs</th><th class="num">DNS</th><th class="num">TCP done</th><th class="num">TLS done</th><th class="num">First byte</th><th class="num">Total</th></tr>'+rows.join('')+'</table>';
  }
  const zs=document.createElement('span');zs.className='seg';zs.id='wi-wf-zoom';
  function zoomUI(){zs.innerHTML=mode==='public'?'<button data-m="all" class="on">Median of 5</button><button data-m="first">First run</button>':'<button data-m="all" class="on">Whole request</button><button data-m="fb">Until the first byte</button>';zoom='all'}
  $('wi-wf-seg').parentNode.appendChild(zs);zoomUI();
  seg(zs,m=>{zoom=m;sel=null;draw()});
  seg($('wi-wf-seg'),m=>{mode=m;sel=null;zoomUI();draw()});
  draw();curlTab();onRender(draw);
})();
