// ---- On the wire: 3. anatomy stepper, and one token in three HTTP versions ----
(function(){
  const {D,$,esc,f1,f0,ms,svg,tx,width,anim}=WI,A=D.anatomy,S=A.setup,CH=A.client_hello,SH=A.server_hello;
  const recs=A.records,app=recs.filter(r=>r.type==='application_data');
  const inApp=app.filter(r=>r.dir==='in'),outApp=app.filter(r=>r.dir==='out');
  const fr=A.h2_frames,data=A.data_frames,msg=n=>A.tls_msgs.filter(m=>m.msg===n);
  const tok=data[1];// the first token's DATA frame ("The")
  const tokRec=inApp.find(r=>r.len===tok.len+9+17);
  const sseLen=tok.len,h2Len=tok.len+9,tlsLen=tokRec?tokRec.len+5:null;
  const ans=D.server.tokens.join('');
  const pre=s=>'<pre class="wrap">'+esc(s)+'</pre>';
  const digAns=(A.dig.match(/;; ANSWER SECTION:\n([^\n]+)/)||[])[1]||'',digT=(A.dig.match(/Query time: (\d+)/)||[])[1];
  const ttl=(digAns.split(/\s+/)[1])||'';
  const chainPub=A.chain_public.split('--').filter(x=>x.trim()).map(x=>{const s=(x.match(/subject= (.*)/)||[])[1],i=(x.match(/issuer= (.*)/)||[])[1],na=(x.match(/notAfter=(.*)/)||[])[1];return {s,i,na}});
  const L=['App','HTTP','TLS','TCP','IP'];
  // each step: d = direction of the arrow (out = client to server), lay = layers lit, t = time (ms from start), html = panel
  const steps=[
    {lab:'The app builds the request',lay:[0],t:0,html:'<p>The SDK turns the chat turn into a '+new TextEncoder().encode(D.request.body).length+'-byte JSON body and asks for <code>POST https://api.llm.test:8443/v1/messages</code>. Nothing has touched the network yet.</p>'+pre(D.request.body)},
    {lab:'DNS: turn the name into an address',lay:[0,4],t:0,html:'<p><b>DNS</b> (Domain Name System) maps a name to an IP address. Our test name is pinned to 127.0.0.1, so here is the same question for a real LLM API, asked with <code>dig</code> on '+WI.V.date()+':</p>'+pre(digAns)+'<p>One address, valid for <b>'+esc(ttl)+' seconds</b> (the TTL, time to live: how long any cache may reuse the answer before asking again). This query took '+esc(digT)+' ms through the local network\'s resolver; in later curl runs the operating system\'s cache answered in about 2 ms (section 2, Public hosts).</p><p class="wi-src">On this laptop every port-53 query is answered by a DNS filter on the way: even a question sent straight to a root server (198.41.0.4, which only ever refers you onward) came back with a final answer. The Failure lab and the Reading tab use this. Source: <code>raw/dig_api.anthropic.com.txt</code>, <code>raw/dig_root_norecurse.txt</code>.</p>'},
    {lab:'TCP: SYN',d:'out',lay:[3,4],t:S.dns_ms,html:'<p>The client\'s kernel picks a free local <b>port</b> ('+A.local_port+') and sends a <b>SYN</b> (synchronise) packet to port 8443: "I want to talk; my byte numbering starts at x". A TCP header is 20 bytes plus options (RFC 9293 section 3.1).</p><p class="wi-src">TCP lives in the operating system kernel, so the SYN itself can only be seen with packet capture (tcpdump), which needs administrator rights we did not use. The times here are measured around the <code>connect()</code> call.</p>'},
    {lab:'TCP: SYN-ACK',d:'in',lay:[3,4],t:S.dns_ms,html:'<p>The server answers <b>SYN-ACK</b>: "agreed; mine starts at y, and I have your x". This is the first <b>round trip</b>: nothing else can happen until it comes back.</p>'},
    {lab:'TCP: ACK, connection open',d:'out',lay:[3,4],t:S.tcp_ms,html:'<p>The client\'s <b>ACK</b> completes the three-way handshake (RFC 9293 section 3.5) and <code>connect()</code> returns, '+ms(S.tcp_ms)+' after the start. The two ends now share a reliable, ordered byte stream: whatever goes in one end comes out the other in order, with losses resent automatically.</p>'},
    {lab:'TLS: ClientHello',d:'out',lay:[2,3,4],t:msg('ClientHello')[0].t_ms,html:'<p>TLS (Transport Layer Security) encrypts that stream and proves who the server is. The client opens with a <b>ClientHello</b> of <b>'+CH.len+' bytes</b>, sent in the clear inside a TLS record whose 5-byte header is <code>'+recs[0].head_hex+'</code> (type 22 handshake, version, length).</p><table class="wi-t"><tr><td class="k">SNI (server name)</td><td><code>'+esc(CH.sni)+'</code>: which site, so one IP can host many</td></tr><tr><td class="k">ALPN</td><td><code>'+esc(CH.alpn.join(', '))+'</code>: the HTTP version it wants</td></tr><tr><td class="k">Versions</td><td>'+esc(CH.versions.join(', '))+'</td></tr><tr><td class="k">Key shares</td><td>'+CH.key_shares.map(k=>'<code>'+esc(k.group)+'</code> ('+k.bytes+' bytes)').join(' and ')+'</td></tr><tr><td class="k">Cipher suites</td><td>'+CH.n_suites+' offered, first '+esc(CH.suites.slice(0,3).join(', '))+'</td></tr></table><p class="wi-src">The client guesses the key exchange and sends its half now: that guess is what saves TLS 1.3 a round trip. <code>X25519MLKEM768</code> is a hybrid of classical X25519 and the post-quantum ML-KEM-768, so most of the '+CH.len+' bytes are its '+CH.key_shares[0].bytes+'-byte share. Parsed from the recorded bytes by <code>build_data.py</code>.</p>'},
    {lab:'TLS: ServerHello',d:'in',lay:[2,3,4],t:msg('ServerHello')[0].t_ms,html:'<p>The <b>ServerHello</b> ('+SH.len+' bytes, still in the clear) picks <code>'+esc(SH.suite)+'</code> and the <code>'+esc(SH.group)+'</code> share, returning its own half ('+SH.key_share_bytes+' bytes). From these two halves both sides compute the same secret, which nobody watching the wire can. Every byte after this one is encrypted.</p>'},
    {lab:'TLS: certificate and proof',d:'in',lay:[2,3,4],t:msg('Finished')[0].t_ms,html:'<p>In the same flight, now encrypted, the server sends EncryptedExtensions ('+msg('EncryptedExtensions')[0].len+' bytes, including the chosen ALPN <code>'+esc(S.alpn)+'</code>), its <b>Certificate</b> ('+msg('Certificate')[0].len+' bytes), <b>CertificateVerify</b> ('+msg('CertificateVerify')[0].len+' bytes: a signature over the handshake so far, proving it holds the certificate\'s private key) and <b>Finished</b>. Each travels in a record 17 bytes longer than the message (1 byte of inner type, 16 of authentication tag).</p><p>The client checks the chain: our server\'s certificate for <code>api.llm.test</code> is signed by "Wire Lab Root CA", which the client was told to trust. A real API\'s chain, recorded the same day:</p>'+pre(chainPub.map((c,i)=>(i?'  '.repeat(i)+'signed by ':'')+c.s+'\n'+'  '.repeat(i+1)+'issuer '+c.i+(c.na?', valid to '+c.na:'')).join('\n'))+'<p class="wi-src">Source: <code>raw/chain_local.txt</code>, <code>raw/chain_api.anthropic.com.txt</code> (openssl s_client -showcerts).</p>'},
    {lab:'TLS: client Finished',d:'out',lay:[2,3,4],t:S.tls_ms,html:'<p>The client sends its own <b>Finished</b> (with a 1-byte ChangeCipherSpec record first, kept only so old middleboxes do not choke, RFC 8446 appendix D.4). The handshake is complete '+ms(S.tls_ms)+' after the start: <code>'+esc(S.tls_version)+'</code>, <code>'+esc(S.cipher)+'</code>, HTTP version <code>'+esc(S.alpn)+'</code>.</p>'},
    {lab:'HTTP/2: the request',d:'out',lay:[1,2,3,4],t:A.h2_timing.start_ms,html:'<p>Now HTTP. HTTP/2 cuts everything into <b>frames</b>, each with a 9-byte header (length, type, flags, stream number; RFC 9113 section 4.1). The client sent:</p><table class="wi-t">'+fr.filter(f=>f.dir==='out'&&f.t_ms<=A.h2_timing.sent_ms+0.01).map(f=>'<tr><td><code>'+f.type+'</code></td><td class="num">'+f.len+' B</td><td>'+(f.type==='PREFACE'?'fixed opening string':f.stream?'stream '+f.stream:'connection')+'</td></tr>').join('')+'</table><p>The headers are <b>'+fr.find(f=>f.dir==='out'&&f.type==='HEADERS').len+' bytes</b> of HPACK (RFC 7541), a compressed binary form, against '+(new TextEncoder().encode(D.request.h1_request).length-new TextEncoder().encode(D.request.body).length)+' bytes of text in HTTP/1.1. All of it left in one encrypted record of '+outApp[1].len+' bytes.</p>'},
    {lab:'Server settings and session tickets',d:'in',lay:[1,2,3,4],t:fr.find(f=>f.dir==='in'&&f.type==='SETTINGS'&&f.flags===1).t_ms,html:'<p>The server sends its SETTINGS (limits such as how many streams may be open at once), acknowledges the client\'s, and, at the TLS layer, hands over '+msg('NewSessionTicket').length+' <b>session tickets</b> ('+msg('NewSessionTicket').map(m=>m.len).join(' and ')+' bytes) that let a later connection skip the certificate (section 6 below).</p>'},
    {lab:'Response headers',d:'in',lay:[0,1,2,3,4],t:fr.find(f=>f.dir==='in'&&f.type==='HEADERS').t_ms,html:'<p>A HEADERS frame on stream 1 ('+fr.find(f=>f.dir==='in'&&f.type==='HEADERS').len+' bytes) carries <code>:status 200</code> and <code>content-type: text/event-stream</code>, then a DATA frame with the <code>message_start</code> event. The app knows the stream is open '+ms(A.h2_timing.first_byte_ms)+' after the start.</p>'},
    {lab:'The first token arrives',d:'in',lay:[0,1,2,3,4],t:A.h2_timing.first_token_ms,big:true,html:'<p>After the server\'s '+D.server.first_token_delay_s+' s pause, the first token "'+esc(D.server.tokens[0])+'" arrives, '+ms(A.h2_timing.first_token_ms)+' after the start. Its journey, layer by layer, drawn to scale:</p><div id="wi-an-scale"></div><p class="wi-src">Measured: the SSE text ('+sseLen+' B), the DATA frame ('+h2Len+' B) and the TLS record on the wire ('+tlsLen+' B, the header\'s length field says '+(tokRec?tokRec.len:'?')+'). From the standards, not captured: TCP 20 bytes plus 12 of timestamp option (RFC 9293, RFC 7323), IPv4 20 (RFC 791).</p>'},
    {lab:'Tokens stream, the stream ends',d:'in',lay:[0,1,2,3,4],t:A.h2_timing.last_token_ms,html:'<p>Each following token is one DATA frame in one TLS record, about '+f0(D.server.token_gap_s*1000)+' ms apart: '+data.slice(1).map(f=>f.len).join(', ')+' bytes of DATA ('+data.length+' frames in all with message_start). The last frame carries the END_STREAM flag, at '+ms(A.h2_timing.last_token_ms)+'. The connection stays open for the next request.</p>'},
    {lab:'The app has the answer',lay:[0],t:A.h2_timing.done_ms,html:'<p>The SDK parsed each SSE event as it arrived and the chat app showed the text growing: <b>"'+esc(ans)+'"</b>. Of the '+ms(A.h2_timing.done_ms)+', the network part on loopback was about '+ms(A.h2_timing.first_byte_ms)+'; the rest was the server thinking. On a real path the network part is a few round trips (section 2).</p>'}
  ];
  let cur=0;
  function scale(){const el=$('wi-an-scale');if(!el)return;const w=width(el.parentNode)-4;
    const parts=[['SSE event',sseLen,'var(--c3)'],['HTTP/2 frame header',9,'var(--c5)'],['TLS record header, type, tag',22,'var(--c4)'],['TCP header (RFC)',32,'var(--c1)'],['IPv4 header (RFC)',20,'var(--c6)']];
    const tot=parts.reduce((a,p)=>a+p[1],0),k=(w-10)/tot;let x=0,b='',y=0;
    parts.forEach((p,i)=>{const Wd=p[1]*k;b+='<rect x="'+x+'" y="0" width="'+Wd+'" height="22" fill="'+p[2]+'"/>';x+=Wd});
    let ly=40;parts.forEach((p,i)=>{b+='<rect x="0" y="'+(ly-9)+'" width="10" height="10" fill="'+p[2]+'"/>'+tx(14,ly,esc(p[0])+': '+p[1]+' B');ly+=15});
    b+=tx(0,ly+4,'Total on the wire: '+tot+' bytes for a '+D.server.tokens[0].length+'-character token',{w:600});
    el.innerHTML=svg(w,ly+10,b,'Bytes added by each layer for one token')}
  function draw(i){cur=i;const s=steps[i],el=$('wi-an-svg'),w=width(el),narrow=w<560;
    const sw=narrow?72:110,h=L.length*26+40,lx=4,rx=w-sw-4,top=26;
    let b=tx(lx+sw/2,14,'Client',{a:'middle',w:600})+tx(rx+sw/2,14,'Server',{a:'middle',w:600});
    L.forEach((n,j)=>{const on=s.lay.includes(j),y=top+j*26;
      [lx,rx].forEach(X=>{b+='<rect x="'+X+'" y="'+y+'" width="'+sw+'" height="22" rx="4" fill="'+(on?'var(--acc2)':'var(--soft)')+'" stroke="'+(on?'var(--acc)':'var(--line)')+'"/>'+tx(X+sw/2,y+15,n,{a:'middle',fs:11,w:on?600:400})})});
    const ly=top+4*26+11;b+='<line x1="'+(lx+sw)+'" x2="'+rx+'" y1="'+ly+'" y2="'+ly+'" stroke="var(--line)" stroke-width="2"/>';
    if(s.d){const a=s.d==='out',x1=a?lx+sw+8:rx-8,x2=a?rx-8:lx+sw+8,yy=ly-16;
      b+='<line x1="'+x1+'" x2="'+x2+'" y1="'+yy+'" y2="'+yy+'" stroke="var(--acc)" stroke-width="2"/><path d="M'+x2+' '+yy+' l'+(a?-8:8)+' -5 v10 z" fill="var(--acc)"/>'+tx((x1+x2)/2,yy-6,esc(s.lab.replace(/^[A-Z0-9/ ]+: /,'')),{a:'middle',fs:narrow?10:11,w:600})}
    b+=tx(w/2,h-6,'t = '+ms(s.t),{a:'middle',fill:'var(--mute)',fs:11});
    el.innerHTML=svg(w,h,b,'Layer stacks of client and server, step '+(i+1));
    $('wi-an-panel').innerHTML='<div class="wi-step">Step '+(i+1)+' of '+steps.length+'</div><h4>'+esc(s.lab)+'</h4>'+s.html;
    if(s.big)scale()}
  anim({card:'wi-an-card',ctl:'wi-an-ctl',n:steps.length,draw,ms:2600,label:'Anatomy step'});

  // one token, three HTTP versions
  function tokens(){const el=$('wi-tok'),w=width(el);
    const h1r=A.h1_records.find(r=>r.dir==='in'&&r.type==='application_data'&&r.len===sseLen+6+17);
    const qp=A.h3_packets.find(p=>p.ptype==='1RTT'&&p.frames.some(f=>f.type==='stream'&&f.stream===0&&f.len===sseLen+3));
    const rows=[
      ['HTTP/1.1',[['SSE',sseLen,'var(--c3)'],['chunk size and CR LF',6,'var(--c5)'],['TLS',22,'var(--c4)'],['TCP*',32,'var(--c1)'],['IPv4*',20,'var(--c6)']],h1r?'TLS record measured: '+(h1r.len+5)+' B':'record not found'],
      ['HTTP/2',[['SSE',sseLen,'var(--c3)'],['frame header',9,'var(--c5)'],['TLS',22,'var(--c4)'],['TCP*',32,'var(--c1)'],['IPv4*',20,'var(--c6)']],'TLS record measured: '+tlsLen+' B'],
      ['HTTP/3',[['SSE',sseLen,'var(--c3)'],['HTTP/3 frame header',3,'var(--c5)'],['QUIC packet and STREAM frame, tag',qp?qp.size-sseLen-3:0,'var(--c4)'],['UDP*',8,'var(--c1)'],['IPv4*',20,'var(--c6)']],qp?'QUIC packet measured: '+qp.size+' B':'packet not found']];
    const tot=r=>r[1].reduce((a,p)=>a+p[1],0),mx=Math.max(...rows.map(tot)),k=(w-70)/mx;let b='',y=4;
    rows.forEach(r=>{b+=tx(0,y+12,r[0],{w:600});let x=70;r[1].forEach(p=>{b+='<rect x="'+x+'" y="'+y+'" width="'+p[1]*k+'" height="16" fill="'+p[2]+'"><title>'+esc(p[0])+': '+p[1]+' B</title></rect>';x+=p[1]*k});
      b+=tx(70,y+30,tot(r)+' B: '+esc(r[2]),{fill:'var(--mute)',fs:10.5});y+=44});
    el.innerHTML=svg(w,y,b,'One token in three HTTP versions, bytes to scale');
    $('wi-tok-src').innerHTML='Same '+sseLen+'-byte SSE event ("'+esc(D.server.tokens[0])+'"). Green: the event; yellow: HTTP framing (RFC 9112 section 7.1; RFC 9113 section 4.1; RFC 9114 section 7.1); purple: encryption and transport framing, measured from <code>raw/client_h1.json</code>, <code>raw/client_h2.json</code> and the HTTP/3 client\'s qlog (<code>raw/qlog_h3/</code>). *From the standards, not captured: TCP 20 + 12 option bytes (RFC 9293, RFC 7323), UDP 8 (RFC 768), IPv4 20 (RFC 791). Per token the three differ by a few bytes; what differs a lot is how they behave when a packet is lost (next section).'}
  tokens();WI.onRender(tokens);WI.onRender(()=>{if(steps[cur].big)scale()});
  $('wi-tok').closest('details').addEventListener('toggle',tokens);
})();
