// ---- Lineage tab: every GLM release on one axis, with a card per release ----
(function(){if(!$('lnSvg'))return;
  // lane: f flagship text, s Flash and small, v vision, d derivative, c corporate. p: total parameters (B), a: active (B)
  const R=[
    {d:'2022-10-05',n:'GLM-130B',l:'f',p:130,a:130,x:'One of the first open bilingual (English and Chinese) 100B-scale models, from Tsinghua KEG and Zhipu; the paper is dated October 2022.',src:'{{GLM-130B paper|@g130}}'},
    {d:'2023-03-13',n:'ChatGLM-6B',l:'s',p:6,a:6,lic:'open weights',x:'A bilingual dialogue model small enough to fine-tune and run locally, which seeded China\'s local-LLM scene; ChatGLM2-6B followed in June 2023 with a 32K context.',src:'{{GitHub|@cglm6}}, {{ChatGLM2-6B|@cglm2}}'},
    {d:'2024-06-04',n:'GLM-4 (GLM-4-9B open)',l:'f',p:9,a:9,x:'The commercial catch-up generation and its first agentic features: GLM-4 All Tools chooses and calls a browser, Python interpreter and other tools on its own. The ChatGLM family paper covers GLM-130B to GLM-4.',src:'{{ChatGLM paper|@cglm}}, {{Hugging Face|@hf}}'},
    {d:'2025-01-15',mo:1,n:'US Entity List',l:'c',x:'The US Commerce Department added Zhipu to the Entity List in January 2025, citing national security; GLM is since trained and served on Chinese accelerators.',src:'{{Wikipedia|@wiki}}'},
    {d:'2025-04-14',n:'GLM-4-32B-0414 and GLM-Z1',l:'s',p:32,a:32,lic:'open weights',x:'Dense 32B chat models and the first open GLM reasoning models (Z1).',src:'{{GitHub|@glm4gh}}'},
    {d:'2025-07-28',n:'GLM-4.5 and GLM-4.5-Air',l:'f',p:355,a:32,ctx:'128K',lic:'MIT',x:'Repositioned around ARC in one model: 355B with 32B active plus the 106B (12B active) Air, hybrid thinking and direct modes, Muon, an MTP layer, slime, 23T pretraining tokens, MIT. 70.1% on TAU-Bench, 91.0% on AIME 24, 64.2% on SWE-bench Verified; third overall and Air sixth across the report\'s ARC benchmarks. Claude Code compatible from launch. The moment GLM became a serious open contender; the report is the best single document on the line. Zhipu rebranded internationally as Z.ai the same month.',src:'{{GLM-4.5 report|@r45}}, {{release notes|@rel}}'},
    {d:'2025-08-11',n:'GLM-4.5V',l:'v',p:108,lic:'MIT',x:'A 100B-scale (107.7B in the checkpoint) vision-language reasoning model with a thinking mode: video understanding, visual grounding, GUI agents. Vision stayed in separate models until GLM-5.3-Flash.',src:'{{release notes|@rel}}, {{Hugging Face|@hf}}'},
    {d:'2025-09-30',n:'GLM-4.6',l:'f',p:355,a:32,ctx:'200K',lic:'MIT',x:'A coding-focused iteration on the 355B base with the context raised from 128K to 200K tokens; the first integration of FP8 and Int4 on Cambricon chips. With the GLM Coding Plan it made GLM the value option for agentic coding and a genuine competitive lever.',src:'{{release notes|@rel}}, {{Wikipedia|@wiki}}'},
    {d:'2025-12-08',n:'GLM-4.6V',l:'v',p:108,ctx:'128K',lic:'MIT',x:'The next vision-language model, with a 128K context.',src:'{{release notes|@rel}}'},
    {d:'2025-12-22',n:'GLM-4.7',l:'f',p:355,a:32,ctx:'200K',lic:'MIT',x:'A further coding, reasoning and agentic iteration on the same 355B architecture (92 layers, 160 experts).',src:'{{release notes|@rel}}, {{Hugging Face|@c47}}'},
    {d:'2026-01-08',n:'Hong Kong listing',l:'c',x:'Zhipu listed on the Hong Kong Stock Exchange, the first major Chinese LLM company to go public, as the "first LLM stock" wave hit China: context for the pricing aggression, since market share is the story being sold.',src:'{{Wikipedia|@wiki}}'},
    {d:'2026-01-19',n:'GLM-4.7-Flash',l:'s',p:30,a:3,ctx:'200K',lic:'MIT',x:'"A 30B-A3B MoE model", the free API tier of GLM-4.7.',src:'{{model card|@c47f}}, {{release notes|@rel}}'},
    {d:'2026-02-12',n:'GLM-5',l:'f',p:744,a:40,ctx:'200K',lic:'MIT',x:'The 744B-class generation targeting frontier parity, and the base that 5.1, 5.2 and 5.3 post-train rather than replace: 256 experts, MLA-256 with DSA, three shared MTP layers, 28.5T tokens, full-stack adaptation to seven Chinese chip platforms. The first open-weight model to score 50 on the Artificial Analysis Intelligence Index (v4.0).',src:'{{GLM-5 report|@r5}}, {{release notes|@rel}}'},
    {d:'2026-04-07',n:'GLM-5.1',l:'f',p:744,a:40,ctx:'200K',lic:'MIT',x:'Post-training on the GLM-5 base for long-horizon agentic engineering, able to work for up to 8 hours in one run; 58.4 on SWE-bench Pro. Released to subscribers in late March, open-sourced on 7 April, when Z.ai also raised API prices by 10%.',src:'{{release notes|@rel}}, {{GLM-5.2 card|@c52}}, {{Wikipedia|@wiki}}'},
    {d:'2026-06-16',n:'GLM-5.2',l:'f',p:744,a:40,ctx:'1M',lic:'MIT',x:'The 1M-token context, IndexShare (2.9x fewer per-token FLOPs at 1M), the improved MTP draft (+20% acceptance length), critic-based PPO and the anti-hack module, under MIT. FrontierSWE 74.4 against GPT-5.5\'s 72.6 and Claude Opus 4.8\'s 75.1, at roughly one sixth of GPT-5.5\'s cost; SWE-bench Pro 62.1; Terminal-Bench 2.1 81.0. Topped the open-weight division of the Artificial Analysis index at release (51 on v4.1), first on Design Arena and second on the frontend-code arena.',src:'{{GLM-5.2 card|@c52}}, {{GLM-5.2 blog|@b52}}, {{Labellerr|@lab}}'},
    {d:'2026-08-14',n:'GLM-5.3',l:'f',p:744,a:40,ctx:'1M',lic:'GLM-5.3 License',x:'Post-training alone on the GLM-5.2 base, no architecture change. 50% better on the in-house Z.ai Code Bench, Terminal-Bench 3.0 from 4.6% to 28.3% (the "six times" of headlines), DeepSWE v1.1 from 46.2 to 66.9, first on CyberGym at 84.5%; Zhipu reports 2,436 vulnerabilities found with security teams, 1,097 of them medium or high severity. Announced 14 August; Z.ai\'s release notes list the API on 18 August. 44.8 on the Intelligence Index v4.3 at $2.01 per task.',src:'{{GLM-5.3 card|@c53}}, {{release notes|@rel}}, {{Wikipedia|@wiki}}, {{AA|@aa53}}'},
    {d:'2026-08-26',n:'GLM-5.3-Flash',l:'s',p:320,a:18,ctx:'1M',lic:'MIT',x:'The line\'s first natively multimodal model and its most strategically aggressive release: 320B with 18B active, 8 of 288 experts, 34 KDA and 11 sparse MLA layers with IndexPool, four mHC streams, 30T multimodal training tokens with MTP, image, video, text and file input, up to 128K output tokens, native FP8 weights, MIT. $0.15 input and $0.50 output per million tokens after a $0.075 input promotion to 9 September. Ran the week before as the stealth model Ox Alpha. 41.8 on the Intelligence Index v4.3 at $0.25 per task; the 57 quoted at launch was on v4.1.1.',src:'{{Z.ai docs|@dfl}}, {{config|@cfgfl}}, {{SiliconANGLE|@sil}}, {{AA|@aafl}}'},
    {d:'2026-09-11',n:'Atria Dawn Preview',l:'d',p:744,ctx:'256K',lic:'MIT',x:'Shanghai Artificial Intelligence Laboratory\'s agentic model post-trained on the GLM-5.2 base; weights on 11 and 12 September with no announcement, a paper on 14 September. 59.6% on SWE-bench Pro against Claude Opus 5\'s 74.7%; CyberGym 86.5%.',src:'{{GitHub|@atria}}, {{paper|@atriap}}'}];
  const LANES=[['f','Flagship'],['s','Flash and small'],['v','Vision'],['d','Built on GLM'],['c','Corporate']],LC={f:'var(--c1)',s:'var(--c3)',v:'var(--c4)',d:'var(--c2)',c:'var(--mute)'};
  const t=s=>new Date(s+'T00:00:00Z').getTime();
  let zoom=false,sel=null;
  function cards(){$('lnCards').innerHTML=R.slice().reverse().map((r,i)=>{const id='ln'+(R.length-1-i);
    return '<div class="tl-item'+(sel===id?' sel':'')+'" id="'+id+'" style="border-left:4px solid '+LC[r.l]+'"><h3>'+r.n+'</h3><div class="dt">'+new Date(t(r.d)).toLocaleDateString('en-GB',r.mo?{month:'long',year:'numeric',timeZone:'UTC'}:{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})
      +(r.p?' · '+fmt(r.p)+'B total'+(r.a&&r.a!==r.p?' / '+fmt(r.a)+'B active':''):'')+(r.ctx?' · '+r.ctx+' context':'')+(r.lic?' · '+r.lic:'')+'</div><p style="margin:4px 0;font-size:14px">'+r.x+'</p><div class="small mute">Sources: '+r.src+'</div></div>'}).join('')}
  function draw(){const el=$('lnSvg'),W=el.clientWidth<520?360:680,nar=W<500,pl=nar?66:104,pr=14,lh=nar?40:44,H=24+LANES.length*lh+24;
    const a=zoom?t('2025-06-15'):t('2022-08-01'),b=t('2026-10-15'),x=v=>pl+(W-pl-pr)*(t(v)-a)/(b-a);
    let s='';LANES.forEach(([k,n],i)=>{const y=24+i*lh+lh/2;s+='<line x1="'+pl+'" x2="'+(W-pr)+'" y1="'+y+'" y2="'+y+'" stroke="var(--line)"/><text x="'+(pl-8)+'" y="'+(y+4)+'" font-size="11" text-anchor="end" fill="var(--mute)">'+n+'</text>'});
    const yrs=zoom?['2025-07-01','2025-10-01','2026-01-01','2026-04-01','2026-07-01','2026-10-01']:['2023-01-01','2024-01-01','2025-01-01','2026-01-01'];
    yrs.forEach(v=>{const X=x(v);s+='<line x1="'+X+'" x2="'+X+'" y1="20" y2="'+(H-20)+'" stroke="var(--line)" stroke-dasharray="2 3"/><text x="'+X+'" y="'+(H-6)+'" font-size="10.5" text-anchor="middle" fill="var(--mute)">'+(zoom?new Date(t(v)).toLocaleDateString('en-GB',{month:'short',year:'2-digit',timeZone:'UTC'}):v.slice(0,4))+'</text>'});
    R.forEach((r,i)=>{if(t(r.d)<a)return;const li=LANES.findIndex(q=>q[0]===r.l),y=24+li*lh+lh/2,X=x(r.d),rad=r.p?Math.max(3.5,13*Math.sqrt(r.p/744)):5,id='ln'+i;
      s+=r.l==='c'?'<path class="lnd" data-id="'+id+'" d="M'+X+' '+(y-6)+'l6 6l-6 6l-6-6z" fill="'+LC[r.l]+'"'+(sel===id?' stroke="var(--ink)" stroke-width="2"':'')+'><title>'+r.n+', '+(r.mo?r.d.slice(0,7):r.d)+'</title></path>'
        :'<circle class="lnd" data-id="'+id+'" cx="'+X.toFixed(1)+'" cy="'+y+'" r="'+rad.toFixed(1)+'" fill="'+LC[r.l]+'" fill-opacity=".75" stroke="'+(sel===id?'var(--ink)':'var(--bg)')+'" stroke-width="'+(sel===id?2:1)+'"><title>'+r.n+', '+r.d+'</title></circle>';
      if(zoom&&!nar&&r.l!=='c')s+='<text x="'+X.toFixed(1)+'" y="'+(y-rad-4).toFixed(1)+'" font-size="9.5" text-anchor="middle" fill="var(--mute)">'+r.n.replace(' and GLM-4.5-Air','').replace(' Preview','')+'</text>'});
    el.innerHTML=svgEl(W,H,s,'GLM releases on a time axis');
    el.querySelectorAll('.lnd').forEach(d=>d.addEventListener('click',()=>{sel=d.dataset.id;draw();cards();const c=$(sel);if(c)c.scrollIntoView({block:'nearest'})}))}
  const seg=$('lnR');seg.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{seg.querySelectorAll('button').forEach(q=>q.classList.toggle('on',q===b));zoom=b.dataset.m==='z';draw()}));
  onTab('t-line',()=>{draw();cards()});
  let w=0;addEventListener('resize',()=>{const n=$('lnSvg').clientWidth<520;if(n!==w){w=n;if(!$('t-line').hidden)draw()}});
})();
