// ---- Review lab: eleven diffs against the page's real code, comments to reveal, run evidence from CD.proofs ----
(function(){
  const P=window.CD.proofs, esc=RD.esc;
  // diff lines: first character is ' ' context, '+' added, '-' removed, '@' hunk header. c: comments by line index.
  const R=[
  {t:'Be safe: catch everything in the retry loop',f:'after.py, HttpChatModel.complete',
   d:'Retries were missing some failures in production logs, so this catches everything and retries it.',
   diff:['@ class HttpChatModel:  def complete(self, system, user)',
    '         for attempt in range(self.attempts):',
    '             try:',
    '                 r = self.client.post(self.url, json=body, headers={"Authorization": f"Bearer {self.key}"})',
    '-            except httpx.TransportError as e:          # connection refused, timeout, reset',
    '-                last: str = repr(e)',
    '-            else:',
    '                 if r.status_code != 429 and r.status_code < 500:',
    '                     r.raise_for_status()               # a 4xx bug of ours: fail loudly, do not retry',
    '                     content: str = r.json()["choices"][0]["message"]["content"]',
    '                     return content',
    '                 last = f"HTTP {r.status_code}"',
    '+            except Exception as e:  # be safe',
    '+                last = repr(e)'],
   c:{12:[['b','This now catches the <code>HTTPStatusError</code> that <code>raise_for_status()</code> raises for a 400 (our own malformed request) and any <code>KeyError</code> from parsing the reply, and retries them. A 400 will fail identically three times; we pay for three calls and wait 1 + 2 seconds before failing anyway. Catch only what retrying can fix: <code>httpx.TransportError</code>, plus the 429/5xx check below.'],
          ['q','Which failures were missing from the logs? If it was timeouts, they are already <code>TransportError</code> subclasses; maybe the logging is what needs fixing.']]},
   proof:()=>'The diff applied to <code>after.py</code> and its unit tests run: <b>'+esc(P.r1_retry_everything.summary)+'</b>. Failing: <code>'+esc(P.r1_retry_everything.failed.join(', '))+'</code>, the test that pins "a 400 is not retried".',
   v:'Request changes'},
  {t:'Tag summaries automatically',f:'after.py (new helper)',
   d:'Adds an "auto" tag to every generated summary so the UI can show it.',
   diff:['@ new function',
    '+def add_tags(summary: dict, tags: list[str] = []) -> dict:',
    '+    tags.append("auto")',
    '+    return {**summary, "tags": tags}'],
   c:{1:[['b','Mutable default argument: the <code>[]</code> is created once, when the function is defined, and shared by every call. Every call appends to the same list. Use <code>tags: Sequence[str] = ()</code> and build a new list: <code>[*tags, "auto"]</code>.'],
         ['n','<code>dict</code> in and out loses the types we have: this could take and return a <code>Summary</code> (add a <code>tags</code> field).']]},
   proof:()=>'Called twice: the first result\'s tags are now <code>'+esc(JSON.stringify(P.r2_mutable_default.first))+'</code>, the second\'s <code>'+esc(JSON.stringify(P.r2_mutable_default.second))+'</code>, and they are the same list object: <b>'+P.r2_mutable_default.same_object+'</b>. Ruff catches this as <code>B006</code> (bugbear), one reason to enable <code>B</code>.',
   v:'Request changes'},
  {t:'Add a force flag to skip the cache',f:'after.py, summarize_chat',
   d:'Support re-summarising on demand. Call site: summarize_chat("c1", store, model, True).',
   diff:['@ def summarize_chat',
    '-def summarize_chat(chat_id: str, *, store: ChatStore, model: ChatModel) -> Summary:',
    '+def summarize_chat(chat_id: str, store: ChatStore, model: ChatModel, force: bool = False) -> Summary:',
    '     messages = store.messages(chat_id)',
    '     if not messages:',
    '         raise ChatNotFound(chat_id)',
    '+    if not force and (cached := store.cached_summary(chat_id)):',
    '+        return cached',
    '     summary = parse_summary(model.complete(SYSTEM, render_transcript(messages)))'],
   c:{2:[['b','Dropping the <code>*</code> makes <code>store</code>, <code>model</code> and <code>force</code> positional. The call site <code>summarize_chat("c1", store, model, True)</code> does not say what <code>True</code> means, and once released we can never reorder these parameters. Keep them keyword-only: <code>summarize_chat("c1", store=s, model=m, refresh=True)</code>.'],['n','<code>refresh</code> says what happens; <code>force</code> says only that something is overridden.']],
      6:[['b','<code>cached_summary</code> is not on the <code>ChatStore</code> protocol, so every store implementation (and every test fake) breaks. Add it to the protocol in its own change, or keep caching outside this function.']]},
   proof:()=>'<code>mypy --strict</code> on the diff: '+P.r3_bool_flag.mypy.map(m=>'<code>'+esc(m)+'</code>').join('; ')+'.',
   v:'Request changes'},
  {t:'Introduce a provider abstraction',f:'llm/providers.py (new, 60 lines)',
   d:'Future-proofing: we will probably support more LLM providers, so this adds a base class and a factory.',
   diff:['@ new file',
    '+class BaseLLMProvider(ABC):',
    '+    @abstractmethod',
    '+    def complete(self, system: str, user: str) -> str: ...',
    '+    @abstractmethod',
    '+    def stream(self, system: str, user: str) -> Iterator[str]: ...',
    '+    @abstractmethod',
    '+    def embed(self, texts: list[str]) -> list[list[float]]: ...',
    '+    @abstractmethod',
    '+    def count_tokens(self, text: str) -> int: ...',
    '+',
    '+class LLMProviderFactory:',
    '+    _registry: dict[str, type[BaseLLMProvider]] = {}',
    '+    @classmethod',
    '+    def register(cls, name: str): ...',
    '+    @classmethod',
    '+    def create(cls, name: str, **kwargs) -> BaseLLMProvider: ...',
    '+',
    '+@LLMProviderFactory.register("openai")',
    '+class OpenAIProvider(BaseLLMProvider): ...   # the only implementation'],
   c:{1:[['q','What is the second provider, and when? With one implementation we cannot know which parts vary (rule of three). The <code>ChatModel</code> protocol already lets us swap providers for the one method we use.'],
         ['b','Four abstract methods, of which we call one. Every future provider must implement <code>embed</code> and <code>count_tokens</code> even if it cannot, and every test fake too. That is a wide, shallow interface; it will grow flags the first time a provider does not fit.']],
      10:[['n','A factory with a string registry hides which class you get from the type checker (<code>create</code> returns the base type). If we need it later, a dict in the composition root does the same job in one line.']]},
   proof:()=>'No run: this one is judgement. The page\'s sections 5 (rule of three, the wrong abstraction, shallow modules) and 8 (composition root) give the reasoning.',
   v:'Request changes (suggest closing; reopen when a second provider is real)'},
  {t:'Better logging for LLM calls',f:'after.py, HttpChatModel.complete',
   d:'Debugging a production issue; this logs each request.',
   diff:['@ def complete',
    '         body = {"model": self.model, "messages": [...]}',
    '+        headers = {"Authorization": f"Bearer {self.key}"}',
    '+        log.info("POST %s headers=%s body=%s", self.url, headers, body)',
    '         for attempt in range(self.attempts):'],
   c:{3:[['b','This writes the API key (the <code>Authorization</code> header) into the logs, and the whole conversation (user content, possibly personal data) with it. Logs are copied to many systems and kept for months. Log what helps debugging without secrets: a request id, the model name, message count and sizes, the attempt number and the status.'],
         ['p','Logging the attempt number would have made the original incident easier to see; worth adding.']]},
   proof:()=>'No run needed: the header holds the key by construction. Observability practice for LLM calls is on {{Observability|n:3ef5c17b0d0d811e8490c54dd42c2b9b}}.',
   v:'Request changes'},
  {t:'Simplify the messages query',f:'after.py, SqliteChatStore.messages',
   d:'Inline the parameter; easier to read and to copy into a SQL console.',
   diff:['@ def messages(self, chat_id)',
    '-        rows = self.conn.execute("select role, content from messages where chat_id=? order by created_at",',
    '-                                 (chat_id,)).fetchall()',
    '+        rows = self.conn.execute(f"select role, content from messages where chat_id=\'{chat_id}\' "',
    '+                                 "order by created_at").fetchall()'],
   c:{3:[['b','SQL injection. <code>chat_id</code> comes from the URL; a value like <code>x\' or \'1\'=\'1</code> turns the filter into "every row". Always pass values as parameters (<code>?</code> placeholders): the database never interprets them as SQL.']]},
   proof:()=>'Run with <code>chat_id = '+esc(P.r6_sql_injection.chat_id)+'</code> on a table with two chats: the f-string query returns <b>'+P.r6_sql_injection.fstring_rows+' rows</b> including <code>'+esc(P.r6_sql_injection.fstring_contents[1])+'</code>; the parameterised query returns '+P.r6_sql_injection.param_rows+'.',
   v:'Request changes'},
  {t:'Call the real model in send_message',f:'steps/step10.py, send_message',
   d:'Replaces the fake reply with a call to the model server.',
   diff:['@ async def send_message(...)',
    '-        await asyncio.sleep(float(os.environ.get("SLOW_S", "0")))     # pretend the model takes a while',
    '-        out = save_reply(owner, chat_id, key, make_reply(body.content))',
    '+        reply = requests.post(MODEL_URL, json={"prompt": body.content}, timeout=30).json()["text"]',
    '+        out = save_reply(owner, chat_id, key, reply)'],
   c:{3:[['b','<code>requests.post</code> is synchronous inside an <code>async def</code>: while it waits for the model (seconds), the event loop is blocked and every other request on this worker waits too. Use an async client (<code>httpx.AsyncClient</code>, created once and injected), or declare the endpoint with plain <code>def</code> so FastAPI runs it in a thread pool.'],
         ['q','What should happen if the model call fails after the key is claimed? With step 10 the key is released, but the client gets a 500; do we want a 502 problem response instead?']]},
   proof:()=>'Ten concurrent requests to a FastAPI endpoint that waits '+P.r7_blocking_in_async.each_s+' s: with <code>await asyncio.sleep</code> they finish in <b>'+P.r7_blocking_in_async.async_total_s+' s</b> in total; with a blocking <code>time.sleep</code> in its place, <b>'+P.r7_blocking_in_async.blocking_total_s+' s</b>, one after another.',
   v:'Request changes'},
  {t:'Rename max_chars to limit (release 0.3.0, "minor cleanup")',f:'chatsummary, render_transcript (public API)',
   d:'limit is a better name. Released as a minor version.',
   diff:['@ def render_transcript (exported in __all__)',
    '-def render_transcript(messages: Sequence[Message], max_chars: int = 8000) -> str:',
    '+def render_transcript(messages: Sequence[Message], limit: int = 8000) -> str:',
    '     """The conversation as plain text, keeping the most recent characters."""',
    '-    return text[-max_chars:]',
    '+    return text[-limit:]'],
   c:{2:[['b','This is a public, exported function: renaming a keyword argument breaks every caller that passes it by name, and a minor release promises it will not. Keep accepting <code>max_chars</code> with a <code>DeprecationWarning</code> naming the version that removes it, for at least two releases (section 9 shows the shim).'],
         ['p','Agree <code>limit</code> is the better name; this is worth doing properly.']]},
   proof:()=>'An existing caller, <code>'+esc(P.r8_breaking_rename.caller)+'</code>, after upgrading: <code>TypeError: '+esc(P.r8_breaking_rename.error)+'</code>.',
   v:'Request changes'},
  {t:'Friendlier summaries',f:'after.py, SYSTEM prompt',
   d:'Product asked for a friendlier tone.',
   diff:['@ SYSTEM',
    '-SYSTEM = \'Reply with JSON: {"title": ..., "summary": ...}\'',
    '+SYSTEM = \'Summarise this conversation in a friendly tone with a short title.\''],
   c:{2:[['b','<code>parse_summary</code> requires a JSON object with <code>title</code> and <code>summary</code>. This prompt no longer asks for JSON, so most replies will become <code>ModelOutputError</code>. Keep the format instruction and add the tone to it.'],
         ['q','What eval covers this? A prompt change is a program change: run it on the golden set of chats and compare parse rate and summary quality before merging.']]},
   proof:()=>'The existing unit test <code>test_parse_rejects_unusable_replies</code> already shows a prose reply without JSON raising <code>ModelOutputError</code>; no unit test can tell how often the model will comply. That needs an eval ({{Production eval engineering|n:3c65c17b0d0d81b39ad9e96193d21adc}}).',
   v:'Request changes'},
  {t:'Add test for summarize_chat (AI-generated)',f:'test_summarize.py (new)',
   d:'Increases coverage of summarize_chat to 100%.',
   diff:['@ new file',
    '+def test_summarize_chat_parses():',
    '+    with patch("after.parse_summary") as p:',
    '+        p.return_value = after.Summary(title="t", summary="s")',
    '+        class M:',
    '+            def complete(self, s, u): return "{}"',
    '+        class S:',
    '+            def messages(self, c): return [after.Message("user", "hi")]',
    '+            def save_summary(self, c, s): pass',
    '+        after.summarize_chat("c", store=S(), model=M())',
    '+        p.assert_called_once()'],
   c:{2:[['b','This replaces the function the test claims to test (<code>parse_summary</code>) with a mock, then checks the mock was called. It would pass with <code>parse_summary</code> deleted. Coverage went up; confidence did not. Use a fake model that returns real reply text and assert on the saved summary (see <code>test_summarize_saves_and_returns</code>).']],
      10:[['n','<code>assert_called_once</code> checks how the code is written, not what it does; such tests break on every refactor and catch no bugs.']]},
   proof:()=>'<code>parse_summary</code> was made to raise <code>NotImplementedError</code> and the test run: <b>'+esc(P.r10_test_the_mock.mocked_test)+'</b>.',
   v:'Request changes'},
  {t:'Skip blank messages in transcripts',f:'after.py, render_transcript, with a test',
   d:'Blank messages (whitespace only) were rendered as "User: " lines and wasted context. Adds a test that fails before the change.',
   diff:['@ def render_transcript',
    '-    text = "".join(f"{SPEAKER[m.role]}: {m.content}\\n" for m in messages if m.role in SPEAKER)',
    '+    text = "".join(f"{SPEAKER[m.role]}: {m.content}\\n" for m in messages',
    '+                   if m.role in SPEAKER and m.content.strip())',
    '@ test_after.py',
    '+def test_transcript_skips_empty_messages():',
    '+    assert render_transcript([Message("user", "  "), *CHAT]) == render_transcript(CHAT)'],
   c:{3:[['p','Small, one behaviour, with a test that fails without the change and passes with it, and a description that says why. This is what a good PR looks like.']],
      5:[['n','The test name could say the rule: <code>test_blank_messages_are_left_out</code>. Not blocking.']]},
   proof:()=>'The new test on the old code: <b>'+esc(P.r11_good_pr.new_test_on_old_code)+'</b>; with the change: <b>'+esc(P.r11_good_pr.with_the_change)+'</b>.',
   v:'Approve (with one nit)'}
  ];
  const LBL={b:'blocking',q:'question',n:'nit',p:'praise'};
  const list=document.getElementById('rv-list'),body=document.getElementById('rv-body');
  let cur=0;const seen=new Set();let shown=false;
  // {{text|n:id}} links inside proofs are expanded here (build.sh only expands HTML parts)
  const link=s=>s.replace(/\x7b\x7b([^|\x7b\x7d]+)\|n:([0-9a-f]+)\x7d\x7d/g,(m,t,id)=>'<a href="https://app.notion.com/p/'+id+'" target="_blank" rel="noopener noreferrer">'+t+'</a>');
  list.innerHTML=R.map((r,i)=>'<button data-i="'+i+'">'+(i+1)+'. '+esc(r.t)+'</button>').join('');
  function draw(){
    const r=R[cur],all=document.getElementById('rv-all').checked,rev=shown||all;
    [...list.children].forEach((b,i)=>{b.classList.toggle('on',i===cur);b.classList.toggle('done',seen.has(i)&&i!==cur)});
    let n=0;
    const rows=r.diff.map((l,i)=>{const k=l[0];let cls=k==='+'?'a':k==='-'?'d':k==='@'?'h':'';
      const g=k==='@'?'':String(++n);
      let h='<span class="r '+cls+'"><span class="g">'+g+'</span>'+esc(k==='@'?l.slice(2):l)+'</span>';
      if(rev&&r.c[i])h+=r.c[i].map(c=>'<div class="cmt '+c[0]+'"><span class="lbl '+c[0]+'">'+LBL[c[0]]+'</span>'+c[1]+'</div>').join('');
      return h});
    body.innerHTML='<div class="rv-pr"><h3>PR '+(cur+1)+' of '+R.length+': '+esc(r.t)+'</h3><div class="meta">'+esc(r.f)+'</div><p style="margin:6px 0 0">'+esc(r.d)+'</p></div>'+
      '<div class="df">'+rows.join('')+'</div>'+
      (rev?'<div class="proof"><div class="t">Evidence</div>'+link(r.proof())+'</div><div class="verdict">Verdict: '+esc(r.v)+'</div>'
          :'<div class="think">What would you comment, and would you approve? Then press <b>Reveal the review</b>.</div>');
    document.getElementById('rv-show').textContent=rev?'Hide the review':'Reveal the review';
    if(rev)seen.add(cur);
  }
  list.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;cur=+b.dataset.i;shown=false;draw()});
  document.getElementById('rv-show').addEventListener('click',()=>{shown=!shown;draw()});
  document.getElementById('rv-prev').addEventListener('click',()=>{cur=(cur+R.length-1)%R.length;shown=false;draw()});
  document.getElementById('rv-next').addEventListener('click',()=>{cur=(cur+1)%R.length;shown=false;draw()});
  document.getElementById('rv-all').addEventListener('change',draw);
  draw();
})();
