// ---- Then and now: the GRPO objective morphing through later work ----
(function(){const TD=TOYDATA,m=a=>a.reduce((x,y)=>x+y,0)/a.length,P=v=>(100*v).toFixed(1)+'%';
  // each term: [id, label, versions by step index (the newest at or before the step applies)]
  const TERMS=[['norm','averaging',[[0,'(1/G) Σ<sub>i</sub> (1/|o<sub>i</sub>|) Σ<sub>t</sub>'],[2,'(1/Σ<sub>i</sub>|o<sub>i</sub>|) Σ<sub>i</sub> Σ<sub>t</sub>'],[3,'(1/(G · L<sub>max</sub>)) Σ<sub>i</sub> Σ<sub>t</sub>']]],
    ['ratio','ratio',[[0,'ρ<sub>i,t</sub> = π<sub>θ</sub>(o<sub>i,t</sub>) / π<sub>old</sub>(o<sub>i,t</sub>)'],[5,'s<sub>i</sub> = (π<sub>θ</sub>(o<sub>i</sub>) / π<sub>old</sub>(o<sub>i</sub>))<sup>1/|o<sub>i</sub>|</sup>']]],
    ['clip','clip',[[0,'clip(ρ, 1 − ε, 1 + ε)'],[2,'clip(ρ, 1 − ε<sub>low</sub>, 1 + ε<sub>high</sub>), 0.2 and 0.28']]],
    ['adv','advantage',[[0,'Â<sub>i</sub> = (r<sub>i</sub> − mean <b>r</b>) / std <b>r</b>'],[3,'Â<sub>i</sub> = r<sub>i</sub> − mean <b>r</b>']]],
    ['kl','KL',[[0,'− β 𝔻<sub>KL</sub> (k3 in the loss), β = 0.04'],[1,'− β 𝔻<sub>KL</sub>, β = 0.001'],[2,'none'],[4,'none, or a correctly differentiated estimator']]],
    ['rew','reward',[[0,'learned reward model (outcome or process)'],[1,'rule: accuracy + format']]],
    ['grp','groups',[[0,'every group, G = 64, one update per batch'],[1,'G = 16, 16 mini-batches per rollout'],[2,'drop groups whose rewards are all equal']]]];
  const STEPS=[{t:'2024, DeepSeekMath: GRPO as printed',c:'Eq. 3 with a learned reward model, z-scored group advantages, per-sequence length averaging, the k3 KL in the loss with β = 0.04, G = 64 and one policy update per batch, so the clip never binds.',toy:'This page\'s toy runs it: '+P(m(TD.runs.grpo.finals))+' after 400 steps (3 seeds).'},
    {t:'January 2025, DeepSeek-R1: rules for rewards',c:'R1 and R1-Zero replace the reward model with rules (accuracy and format, equal weight), sample 16 outputs, set β = 0.001 and reset the reference every 400 steps, and split each rollout into 16 mini-batches, so the clip now matters ("plays a crucial role"). Its supplement is also the first GRPO against PPO comparison: GRPO ahead at λ = 0.95, close at λ = 1.0.',toy:'The toy has used a rule reward all along; β = 0 vs 0.04 makes no difference ('+P(m(TD.beta0.grpo))+' vs '+P(m(TD.runs.grpo.finals))+').',src:['DeepSeek-R1','https://arxiv.org/abs/2501.12948']},
    {t:'March 2025, DAPO: four fixes for long chains',c:'Clip-Higher (ε_low = 0.2, ε_high = 0.28) to keep low-probability tokens rising; Dynamic Sampling, which drops groups whose rewards are all equal because their advantage is zero; a token-level loss (average over all tokens of the batch, so long answers count per token); Overlong Reward Shaping; and the KL term removed ("this restriction is not necessary").',toy:'Zero-signal groups in the toy at G = 8: '+(100*TD.runs.grpo.seeds['5'].zero).toFixed(0)+'% of all groups over a run; dynamic sampling would skip them. Length effects need longer outputs than the toy\'s three tokens.',src:['DAPO','https://arxiv.org/abs/2503.14476']},
    {t:'March 2025, Dr. GRPO: remove two biases',c:'Dividing by |o_i| penalises long wrong answers less, so they grow; dividing by std(r) over-weights questions that are almost always or almost never solved. Dr. GRPO drops both, leaving an unbiased REINFORCE-style estimator with a group-mean baseline, and normalises by a constant such as the generation budget.',toy:'The toy\'s outputs all have 3 tokens, so only the std change is visible: Dr. GRPO '+P(m(TD.runs.drgrpo.finals))+' vs GRPO '+P(m(TD.runs.grpo.finals))+', no difference at this scale.',src:['Dr. GRPO','https://arxiv.org/abs/2503.20783']},
    {t:'June 2025, Tang and Munos: the KL gradient',c:'Differentiating a KL estimate as a loss does not give the KL\'s gradient; for k3, the expected gradient is that of KL(π_ref ‖ π). The fix is either the correct score-function estimator or no KL at all, which most verifiable-reward recipes now choose.',toy:'Exact for one categorical step in the Reading tab\'s KL widget.',src:['Tang and Munos','https://arxiv.org/abs/2506.09477']},
    {t:'July 2025, GSPO: ratios per sequence',c:'GSPO (used for Qwen3) argues the token-level ratio is the wrong unit, since the reward is per sequence: it uses the length-normalised sequence likelihood ratio and clips whole responses, and reports more stable training, notably for mixture-of-experts models.',toy:'Not testable: with one update per batch every ratio is 1 in the toy.',src:['GSPO','https://arxiv.org/abs/2507.18071']}];
  const verAt=(vs,k)=>{let cur=vs[0],prev=null;vs.forEach(v=>{if(v[0]<=k){prev=cur===v?prev:cur;cur=v}});return {cur,prev:cur[0]===k&&k>0?prev:null}};
  makeAnim({id:'obj',mode:'o',modes:{o:STEPS},dur:3200,
    draw(mm,k,e,w){let h='<div style="display:grid;grid-template-columns:'+(w<520?'1fr':'7.5em 1fr')+';gap:4px 10px;font-size:14px">';
      TERMS.forEach(([id,lab,vs])=>{const {cur,prev}=verAt(vs,k),changed=cur[0]===k&&k>0;
        h+='<div class="small mute" style="padding-top:4px">'+lab+'</div><div style="padding:4px 8px;border-radius:6px;'+(changed?'background:var(--hl);':'background:var(--soft);')+'">'+(changed&&prev?'<span style="text-decoration:line-through;opacity:'+(1-0.6*e).toFixed(2)+';margin-right:8px">'+prev[1]+'</span>':'')+'<span style="opacity:'+(changed?Math.max(0.3,e):1).toFixed(2)+'">'+cur[1]+'</span></div>'});
      return h+'</div>'},
    counters(mm,k){const S=STEPS[k];return stat('source',S.src?A(S.src[1],S.src[0]):A(PAPER.meta.ax+'#S4.E3','DeepSeekMath Eq. 3'),'')+stat('in the toy','',S.toy)}});
  const rows=[['Group-relative advantage, no critic','survived','every recipe above; Dr. GRPO drops only the std'],['Outcome rewards from a learned reward model','replaced','rules for verifiable tasks (R1); R1 still uses learned reward models for helpfulness and harmlessness in its last stage'],['Process supervision (GRPO+PS)','rarely used','most large recipes use outcome rewards; R1 lists process reward models among its unsuccessful attempts (hard to define steps, reward hacking, retraining cost)'],
    ['KL to a reference in the loss, k3','weakened or dropped','β = 0.001 (R1); removed (DAPO, many open recipes); estimator criticised (Tang and Munos)'],['1/|o| per-sequence averaging','replaced','token-level averaging (DAPO) or a constant (Dr. GRPO)'],['Symmetric clip, one update per batch','changed','several updates per rollout, so the clip binds; asymmetric Clip-Higher; sequence-level clip (GSPO)'],
    ['Iterative reward-model retraining','mostly gone','with rule rewards there is nothing to retrain; reference resets survive (R1: every 400 steps)'],['G samples per question','survived','16 typical (R1, DAPO) against 64 here; zero-signal groups filtered (DAPO)']];
  $('thenTab').innerHTML='<tr><th>in DeepSeekMath (2024)</th><th>status</th><th>what replaced it, or where it lives on</th></tr>'+rows.map(r=>'<tr><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td></tr>').join('')})();
