// Every toy number the page quotes: 10 methods x 2 settings x 8 seeds, plus the trade-off frontier
// (fixed length weights against saturation exponents), 8 seeds each. About 1 minute in node.
//   node toy_sweep.mjs     -> inputs/toy.json and parts/_gen_toydata.js
import { createRequire } from 'module';
import fs from 'fs';
const require = createRequire(import.meta.url);
const here = new URL('.', import.meta.url).pathname;
const T = require(here + 'parts/22_js_toy.js');
const SEEDS = [1, 2, 3, 4, 5, 6, 7, 8];
const mean = a => a.reduce((x, y) => x + y, 0) / a.length;
const se = a => { const m = mean(a); return Math.sqrt(a.reduce((x, y) => x + (y - m) ** 2, 0) / (a.length - 1) / a.length); };
const r4 = v => Math.round(v * 1e4) / 1e4;
const out = { seeds: SEEDS, steps: 150, B: 32, G: 8, lr: 0.03, settings: {} };
for (const st of ['budget', 'graded']) {
  const S = { init: T.evaluate(T.init(st), st), methods: {}, frontier: { w: [], g: [] } };
  for (const m of Object.keys(T.METHODS)) {
    const runs = SEEDS.map(s => T.train({ setting: st, method: m, seed: s }));
    const fin = k => runs.map(r => r.final[k]);
    const ev = runs[0].log.ev.map(([t], i) => [t, ...['acc', 'len', 'over', 'tok'].map(k => r4(mean(runs.map(r => r.log.ev[i][1][k]))))]);
    const L = k => runs.map(r => mean(r.log[k].slice(0, 20))), Lt = k => runs.map(r => mean(r.log[k].slice(-20)));
    S.methods[m] = {
      n: T.METHODS[m].n,
      acc: r4(mean(fin('acc'))), accSE: r4(se(fin('acc'))), len: r4(mean(fin('len'))), lenSE: r4(se(fin('len'))),
      over: r4(mean(fin('over'))), tok: Math.round(mean(fin('tok'))),
      accs: fin('acc').map(r4), lens: fin('len').map(r4),
      ev,
      mixL0: r4(mean(L('mixL'))), mixL1: r4(mean(Lt('mixL'))), mixC0: r4(mean(L('mixC'))), mixC1: r4(mean(Lt('mixC'))),
      shL0: m === 'grpo' || m === 'conly' ? null : r4(mean(L('shL'))), shL1: m === 'grpo' || m === 'conly' ? null : r4(mean(Lt('shL'))),
      s1: r4(mean(Lt('s1'))), s0: r4(mean(Lt('s0'))), wl1: r4(mean(Lt('w1'))),
    };
    console.log(st, m, S.methods[m].acc, S.methods[m].len);
  }
  for (const wl of [1, 0.75, 0.5, 0.4, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05]) {
    const f = SEEDS.map(s => T.train({ setting: st, method: { agg: 'dec', w: [1, wl], gamma: 0 }, seed: s }).final);
    S.frontier.w.push({ wl, acc: r4(mean(f.map(x => x.acc))), len: r4(mean(f.map(x => x.len))), accSE: r4(se(f.map(x => x.acc))), lenSE: r4(se(f.map(x => x.len))) });
  }
  for (const g of [0, 0.25, 0.5, 0.75, 1, 1.5, 2, 3]) {
    const f = SEEDS.map(s => T.train({ setting: st, method: { agg: 'dec', w: [1, 1], gamma: g }, seed: s }).final);
    S.frontier.g.push({ g, acc: r4(mean(f.map(x => x.acc))), len: r4(mean(f.map(x => x.len))), accSE: r4(se(f.map(x => x.acc))), lenSE: r4(se(f.map(x => x.len))) });
  }
  // paired differences against GDPO (same seeds, so the same question draws at step 1)
  const gd = S.methods.gdpo.accs;
  for (const m of Object.keys(S.methods)) { const d = S.methods[m].accs.map((v, i) => v - gd[i]); S.methods[m].dAcc = r4(mean(d)); S.methods[m].dAccSE = r4(se(d)); }
  out.settings[st] = S;
}
fs.writeFileSync(here + 'inputs/toy.json', JSON.stringify(out, null, 1));
fs.writeFileSync(here + 'parts/_gen_toydata.js', '// Generated by toy_sweep.mjs: every toy number the page quotes (8 seeds per setting).\nwindow.TOYDATA=' + JSON.stringify(out) + ';\n');
console.log('wrote inputs/toy.json', fs.statSync(here + 'inputs/toy.json').size, 'bytes');
