// ---- Then and now: the DDPM recipe card, changed one paper at a time ----
(function(){const F=[['space','Where the chain runs'],['net','Network'],['pred','Network predicts'],['loss','Training loss'],['sched','Noise schedule, variances'],['samp','Sampler'],['cond','Conditioning'],['res','Headline result']];
  const ax=id=>'https://arxiv.org/abs/'+id;
  const S=[
   {y:'June 2020',n:'DDPM (this paper)',u:'https://arxiv.org/abs/2006.11239',set:{space:'pixels, scaled to [−1, 1]',net:'U-Net (PixelCNN++ style), self-attention at 16 × 16, 35.7M parameters',pred:'the noise ε',loss:'L<sub>simple</sub>: unweighted ε MSE, t uniform',sched:'linear β 10<sup>−4</sup> to 0.02, T = 1,000; σ² fixed',samp:'ancestral (Algorithm 2), 1,000 network evaluations',cond:'none (unconditional)',res:'CIFAR10 FID 3.17; NLL ≤ 3.75 bits/dim'},c:'The starting recipe: everything on this card is from §3 and §4 of the paper.'},
   {y:'October 2020',n:'DDIM',u:ax('2010.02502'),set:{samp:'deterministic, non-Markovian sampler on the same trained model, "10× to 50× faster" in wall-clock time'},c:'"The same training procedure as DDPMs": only the sampler changes, so a DDPM checkpoint can be sampled in far fewer steps.'},
   {y:'November 2020',n:'Score-based SDEs',u:ax('2011.13456'),set:{sched:'continuous time: a forward SDE; DDPM and NCSN are special cases',samp:'reverse-time SDE solvers, predictor-corrector, or an equivalent ODE with exact likelihood'},c:'The score connection DDPM made explicit becomes the framework: the reverse process "depends only on the time-dependent gradient field (aka, score)".'},
   {y:'February 2021',n:'Improved DDPM',u:ax('2102.09672'),set:{loss:'L<sub>hybrid</sub>: L<sub>simple</sub> plus a bound term for learned variances',sched:'cosine schedule, T = 4,000; variances learned',samp:'an order of magnitude fewer forward passes with learned variances',res:'CIFAR10 NLL 2.94 bits/dim (their best); the DDPM setup reproduced at FID 3.29, NLL 3.73'},c:'"A few simple modifications" give competitive likelihoods; learned variances, unstable in DDPM\'s Table 2, now work.'},
   {y:'May 2021',n:'Diffusion Models Beat GANs (ADM)',u:ax('2105.05233'),set:{net:'a better U-Net "through a series of ablations"',cond:'class labels, with classifier guidance (gradients of a separate classifier)',res:'ImageNet 256 × 256 FID 4.59; matches BigGAN-deep "with as few as 25 forward passes"'},c:'Guidance trades diversity for fidelity, and diffusion passes GANs on ImageNet.'},
   {y:'July 2021',n:'Variational Diffusion Models',u:ax('2107.00630'),set:{sched:'learned jointly with the model; the continuous-time bound depends only on the end-point signal-to-noise ratios',res:'CIFAR10 2.65 bits/dim, below the 2.80 that DDPM\'s Table 1 lists for the Sparse Transformer (DDPM itself listed at 3.69)'},c:'The paper\'s admitted weakness, likelihood, is closed: diffusion reaches state-of-the-art likelihoods (VDM\'s own table lists an augmented Sparse Transformer at 2.53, so the comparison depends on augmentation).'},
   {y:'December 2021',n:'Latent diffusion (Stable Diffusion)',u:'https://app.notion.com/p/3c65c17b0d0d81bb98adc0daf8462cb6',set:{space:'the latent space of a pretrained autoencoder',cond:'cross-attention layers: text, bounding boxes'},c:'Pixel-space diffusion "often consumes hundreds of GPU days"; running the chain in a compressed latent makes high-resolution text-to-image affordable.'},
   {y:'June 2022',n:'EDM (design space)',u:ax('2206.00364'),set:{net:'preconditioned score network',samp:'improved sampler, 35 network evaluations per image',res:'CIFAR10 FID 1.97 unconditional, 1.79 class-conditional'},c:'Separating the design choices shows how much of DDPM\'s setup was incidental; the same pretrained networks sample better.'},
   {y:'July 2022',n:'Classifier-free guidance',u:ax('2207.12598'),set:{cond:'conditional and unconditional model trained jointly; their estimates combined, no classifier'},c:'Guidance without a separate classifier: the form text-to-image systems use.'},
   {y:'September to October 2022',n:'Rectified flow; Flow Matching',u:ax('2210.02747'),set:{pred:'a velocity field along (straight) paths from noise to data',loss:'regression of the vector field, simulation-free',samp:'an ODE, ideally along straight paths: few steps'},c:'Flow Matching "subsumes existing diffusion paths as specific instances"; rectified flow (#RF#) learns straight paths, which are cheap to simulate.'},
   {y:'December 2022',n:'DiT',u:ax('2212.09748'),set:{net:'a Transformer on latent patches (no U-Net)',res:'ImageNet 256 × 256 FID 2.27'},c:'FID falls consistently as the Transformer\'s Gflops grow: the backbone question is settled in favour of the #VIT# design.'},
   {y:'March 2023',n:'Consistency models',u:ax('2303.01469'),set:{samp:'one step (multistep optional), by distillation or standalone training',res:'CIFAR10 FID 3.55 in one step'},c:'Noise mapped "directly" to data: DDPM\'s 1,000 evaluations become one, at DDPM\'s own CIFAR10 quality.'},
   {y:'March 2024',n:'Stable Diffusion 3',u:ax('2403.03206'),set:{net:'rectified-flow Transformer',pred:'velocity (rectified flow)'},c:'"Scaling Rectified Flow Transformers for High-Resolution Image Synthesis": latent space, a Transformer and a flow objective together; OpenAI\'s Sora report likewise describes a diffusion Transformer for video.'}];
  // accumulate the card at each step
  const cards=[];let cur={};S.forEach(s=>{cur=Object.assign({},cur,s.set);cards.push(cur)});
  const link=s=>s.replace('#RF#','<a href="'+ax('2209.03003')+'" target="_blank" rel="noopener noreferrer">arXiv 2209.03003</a>').replace('#VIT#','<a href="https://app.notion.com/p/3c65c17b0d0d811fa231cfcde6c1954d" target="_blank" rel="noopener noreferrer">ViT</a>');
  const steps=S.map(s=>({t:s.y+': '+s.n,c:link(s.c)+' '+A(s.u,s.u.indexOf('notion')>0?'KB page':'paper')}));
  function draw(m,k,e){const C=cards[k],P=k?cards[k-1]:{},ch=S[k].set;let h='<dl class="recipe">';
    F.forEach(([f,l])=>{const changed=k>0&&(f in ch);h+='<dt>'+l+'</dt><dd'+(changed?' class="chg"':'')+'>'+(changed&&e<.5&&P[f]?'<span class="mute" style="text-decoration:line-through">'+P[f]+'</span>':C[f])+'</dd>'});
    return h+'</dl>'}
  function counters(m,k){const ch=Object.keys(S[k].set).length;return stat('year',S[k].y.replace(/^.* /,''),S[k].n)+stat('lines changed',k?ch+' of '+F.length:'the original',k?'highlighted':'')+stat('still as in DDPM',F.filter(([f])=>cards[k][f]===cards[0][f]).length+' of '+F.length,'lines unchanged since 2020')}
  makeAnim({id:'thx',mode:'a',dur:4200,modes:{a:steps},draw,counters});
})();
