// ---- Reading, "The lifecycle in one screen": stage x axis grid; click a cell for its comparison paragraph and the page that owns the depth ----
(function(){
  const $=id=>document.getElementById(id);
  if(!$('rd-grid'))return;
  const D=' <i class="nl d">derived</i>',R=' <i class="nl r">reported</i>';
  const AX=[{n:'What it changes',s:'#rd-a1'},{n:'Data',s:'#rd-a2'},{n:'Cost',s:'#rd-a3'},{n:'What goes wrong',s:'#rd-a4'}];
  const AXS=['the signal','how much, who makes it','compute, memory, dollars','and the defence'];
  const ST=[
  {g:'Building the base'},
  {n:'Pretraining',k:'next-token, from scratch',page:`{{Pretraining|n:3c65c17b0d0d814f82cffd0d5c0dd5ba}}`,c:[
    ['Every weight, from random',`Every weight, from random initialisation, by predicting the next token over the whole vocabulary. It decides what the model knows and sets the ceiling later stages work under: RL raises pass@1 but base models still solve more problems given many samples (<a href="https://arxiv.org/abs/2504.13837" target="_blank" rel="noopener noreferrer">Yue et al.</a>).`],
    ['Trillions of web tokens',`Llama 3 405B read 15.6T tokens ({{Llama 3|n:3c65c17b0d0d81aca58ccb9d720b474e}}). About 20 tokens per parameter is compute-optimal (Chinchilla: 70B on 1.4T, {{paper|n:3c65c17b0d0d8116b7ddffba5c599f3f}}); serving-bound models go far past it. Made by crawlers and classifiers: filtered web, code, papers. Data improvements gave 12.0 times the compute efficiency of 2019 at a 1e19-FLOP budget, model improvements 3.7 times (<a href="https://www.dwarkesh.com/p/pretraining-progress-is-mostly-data" target="_blank" rel="noopener noreferrer">Dwarkesh Patel and Jerry Han</a>).`],
    ['Most of the compute',`About 6 FLOPs per parameter per token: Llama 3 405B took 3.8 × 10<sup>25</sup> FLOPs at 38 to 43% utilisation of up to 16,384 H100s ({{Llama 3|n:3c65c17b0d0d81aca58ccb9d720b474e}}). DeepSeek-V3's whole official run was 2.788M H800 hours, $5.576M at an assumed $2 an hour, research excluded ({{DeepSeek-V3|n:3c65c17b0d0d815fb8dac9ba1e35ab81}}). Your own numbers: {{Scaling calculator|#t-scale}}; disclosed runs: {{Price list|#t-price}}.`],
    ['Divergence, failing hardware',`Loss spikes and divergence (OLMo 2's initialisation and normalisation changes cut its spike score from 0.40% to 0.03%, {{OLMo 2|n:3c65c17b0d0d81fb9857fb956165ae1c}}), and at scale the cluster: Llama 3 had 419 unexpected interruptions in 54 days, one every 3.1 hours${D}, yet kept over 90% effective training time.`]]},
  {n:'Mid-training, CPT, long context',k:'same objective, shifted mix',page:`{{Continued Pretraining (CPT)|n:3c65c17b0d0d8119b8f0e801caa09474}}`,c:[
    ['Domain, quality, length',`All weights, same next-token objective, on a shifted mix: a high-quality anneal as the learning rate decays (maths, code, instruction-like and synthetic data), a new domain or language, or long documents with rescaled positional encodings for a longer window ({{Positional Encodings|n:3c65c17b0d0d81a5b7c9e578fcdfac00}}).`],
    ['Billions of curated tokens',`OLMo 2 7B anneals on 50B tokens three times and averages the results ({{OLMo 2|n:3c65c17b0d0d81fb9857fb956165ae1c}}); Thomson Reuters kept 200B tokens of a 19T pool (<a href="https://www.deeplearning.ai/the-batch/custom-models-for-law-news-and-finance" target="_blank" rel="noopener noreferrer">The Batch</a>); Llama 3 went from 8K to 128K context in six stages over about 800B tokens ({{Llama 3|n:3c65c17b0d0d81aca58ccb9d720b474e}}). Made by curation: classifiers, data vendors, synthetic generation.`],
    ['A few % of pretraining',`OLMo 2's mid-training took 5 to 10% of the FLOPs and added 9.9 points on its 7B ({{OLMo 2|n:3c65c17b0d0d81fb9857fb956165ae1c}}). Thomson Reuters' final mid-training run on Qwen3.5-397B-A17B cost $450,000; its $40M figure is the whole two-year programme, talent included (see the {{Price list|#t-price}}).`],
    ['Forgetting',`Catastrophic forgetting of general ability, driven mostly by the shift in data (re-warming the learning rate is about a quarter of it in Ibrahim et al.'s Table 12); instruction following breaks until post-training is re-run. Replay of general data (even 1 to 5%) and a lower re-warmed peak are the defences (<a href="https://arxiv.org/abs/2403.08763" target="_blank" rel="noopener noreferrer">Ibrahim et al.</a>). Llama 3 ended each long-context stage only once short-context scores had recovered.`]]},
  {g:'Post-training'},
  {n:'SFT',k:'imitate demonstrations',page:`{{Alignment|n:3c65c17b0d0d81d5bed7e608d4061c7a}}`,c:[
    ['Format and persona',`All weights (or a LoRA adapter), next-token loss on the response tokens only, so the model answers in a chat template instead of continuing the text. It teaches form more than skill: R1's cold-start SFT scored 59.0% on AIME 2024 against 77.9% for pure RL from the same base ({{DeepSeek-R1|n:3c65c17b0d0d813faca4f7a51eaa0c65}}).`],
    ['Thousands of demonstrations',`InstructGPT: about 13k prompts with demonstrations, written by about 40 contractors ({{InstructGPT|n:3c65c17b0d0d8180b958d8299996a063}}); LIMA: 1,000 curated examples (<a href="https://arxiv.org/abs/2305.11206" target="_blank" rel="noopener noreferrer">LIMA</a>). Now mostly written by a stronger model: 400 trajectories from GPT-6 Astra taught a 4B model to plan Postgres queries (<a href="https://rohanbansal.com/qorl" target="_blank" rel="noopener noreferrer">write-up</a>).`],
    ['Small',`InstructGPT's SFT on the 175B model took 4.9 petaflop/s-days against 3,640 for GPT-3's pretraining, 0.13%${D}. With LoRA it fits on consumer GPUs: the whole Postgres planner, SFT and RL, cost $1,200 (<a href="https://rohanbansal.com/qorl" target="_blank" rel="noopener noreferrer">write-up</a>).`],
    ['Imitation without skill',`Off-policy: the model never sees its own mistakes, so it learns the look of an answer. Chat-template mismatches between training and serving are a common silent bug ({{Tokenizers|n:3c65c17b0d0d817187bcd94a1b0f15ea}}).`]]},
  {n:'Preference optimisation',k:'RLHF with PPO, DPO family',page:`{{Alignment|n:3c65c17b0d0d81d5bed7e608d4061c7a}}`,c:[
    ['Which answer is preferred',`Shifts probability towards the answer a judge ranked higher, with a KL term keeping the model near its SFT starting point. PPO learns a reward model and optimises against it; DPO turns the same objective into a classification loss on pairs, with no reward model and no sampling ({{DPO|n:3c65c17b0d0d818bb1d8cafd30e20f9e}}). Labelers preferred the 1.3B InstructGPT to the 175B GPT-3.`],
    ['Tens of thousands of pairs',`InstructGPT: 33k prompts with ranked answers for the reward model, 31k unlabelled prompts for PPO ({{InstructGPT|n:3c65c17b0d0d8180b958d8299996a063}}). Constitutional AI: 182,831 harmlessness comparisons labelled by a model, against 16 written principles, plus 135,296 human helpfulness comparisons ({{Constitutional AI|n:3c65c17b0d0d815a9b31e9443961c700}}). AI feedback is now the norm for most labels.`],
    ['Four models, or two',`PPO holds policy, reference, reward model and critic: 252 GB at 7B before activations, twice DPO's 126 GB${D} (<a href="#rd-a3">Axis 3</a>). InstructGPT's PPO on 175B took 60 petaflop/s-days, 1.6% of GPT-3's pretraining${D}.`],
    ['Reward hacking',`The policy climbs the learned reward while true quality stalls or falls: verbosity, sycophancy, formatting tricks (<a href="https://arxiv.org/abs/2210.10760" target="_blank" rel="noopener noreferrer">Gao et al.</a>; {{Reward Hacking|n:3c65c17b0d0d8196a6f1f29a817aa974}}). Defences: the KL leash (<a href="#rd-a4">animated in Axis 4</a>), reward-model ensembles, mixing pretraining gradients back in against the "alignment tax".`]]},
  {n:'RLVR',k:'RL against a checker: GRPO and successors',page:`{{Alignment|n:3c65c17b0d0d81d5bed7e608d4061c7a}}`,c:[
    ['Reasoning, agency',`The model's own sampled attempts are rewarded by a program (exact answers, unit tests, an environment's outcome). Long, self-checking chains of thought emerge: DeepSeek-R1-Zero went from 15.6% to 77.9% on AIME 2024 with rule rewards only ({{DeepSeek-R1|n:3c65c17b0d0d813faca4f7a51eaa0c65}}). It can also train cost: SWE-2 learned all its effort levels in one RL run (<a href="https://cognition.com/blog/swe-2" target="_blank" rel="noopener noreferrer">Cognition</a>).`],
    ['Problems and environments',`Prompts with checkable answers, and for agents whole environments: MiMo-V2.6 trained across 7,000+ task environments (<a href="https://huggingface.co/XiaomiMiMo/MiMo-V2.6-Pro-RL" target="_blank" rel="noopener noreferrer">card</a>); Mercor and SkyRL on 1,928 expert-made tasks (<a href="https://www.mercor.com/blog/training-frontier-knowledge-work-agents-a-397b-rl-training-guide-with-skyrl/" target="_blank" rel="noopener noreferrer">Mercor</a>). The answers are the model's own; people or tools make the tasks and checkers.`],
    ['Rollouts and environments',`Many samples per prompt (16 for R1-Zero, 64 for DeepSeekMath) make it inference-heavy. R1's RL and SFT data: 147K H800 hours, $294K, 5.3% of V3's official run${D}; MiMo-V2.6-Pro's final RL stage: $2.62M in under six days. The sandboxes are their own infrastructure: DSec runs about 3 million a day <i class="nl r">self-reported</i> ({{DSec|n:3e95c17b0d0d81bd927be047bb0d7b0b}}).`],
    ['Verifier gaming, collapse',`The checker becomes the proxy: hard-coded outputs, edited or skipped tests, exiting before assertions. Long runs lose entropy and stop exploring; large MoE models go unstable (MiMo-V2.6 froze its router). Defences: hidden and mutated tests, a sandboxed grader, an environment that cannot be escaped.`]]},
  {g:'Making it cheaper'},
  {n:'Distillation',k:'a student imitates a teacher',page:`{{Distillation and Small Language Models|n:3c65c17b0d0d81efa2a8c3b3b623eb09}}`,c:[
    ['A smaller model',`A new, smaller student is trained to imitate a teacher: on the teacher's sampled answers (sequence-level), on its full token distributions (logits, which needs a shared tokenizer), or on-policy, where the student writes and the teacher grades every token. It is the main reason 1B to 8B models are useful now.`],
    ['Teacher outputs',`Qwen2.5-32B fine-tuned on 800K samples from R1 scored 72.6% on AIME 2024 against 47.0% after R1-Zero-style RL on the same base ({{DeepSeek-R1|n:3c65c17b0d0d813faca4f7a51eaa0c65}}); Gemma 3 12B trained on 500 ToolGrad examples scored 83.1 on BFCL against Gemini 2.5 Pro's 83.2 (<a href="https://research.google/blog/toolgrad-efficient-tool-use-dataset-generation-with-textual-gradients" target="_blank" rel="noopener noreferrer">Google Research</a>).`],
    ['Cheap per point',`SFT-priced: one pass over teacher outputs, plus the teacher's inference. On-policy distillation is reported to need 9 to 30 times less compute than off-policy SFT on teacher samples, and against reasoning RL about a tenth of the GPU-hours (Qwen3) or 7 to 10 times fewer steps${R} (<a href="https://thinkingmachines.ai/blog/on-policy-distillation/" target="_blank" rel="noopener noreferrer">Thinking Machines</a>).`],
    ['Inherits the teacher',`Off-policy students never see their own mistakes; a teacher far stronger than the student can hurt it; mismatched tokenizers block logit distillation; the student inherits the teacher's quirks and, through terms of service, its legal exposure.`]]},
  {n:'PEFT (LoRA, QLoRA)',k:'train a small add-on',page:`{{PEFT|n:3c65c17b0d0d81eba08eef56b3e3b4eb}}`,c:[
    ['A low-rank add-on',`The base is frozen and a low-rank update <i>W</i><sub>0</sub> + <i>BA</i> is trained, then merged at no inference cost. On GPT-3 175B, 4.7M trainable parameters reached 73.4% on WikiSQL against 73.8% for full fine-tuning, in a 35 MB adapter instead of a 350 GB copy ({{LoRA|n:3c65c17b0d0d81018f15edd19fa5c28a}}).`],
    ['Whatever the stage needs',`PEFT is a way of running SFT, DPO or RL, not a data regime: the data is that stage's. For RL even rank 1 is enough, since policy gradients carry little information per episode (<a href="https://thinkingmachines.ai/blog/lora/" target="_blank" rel="noopener noreferrer">Thinking Machines</a>).`],
    ['One GPU',`No optimiser state for frozen weights: QLoRA fine-tunes LLaMA 65B in under 48 GB (45.0 GB measured) where 16-bit fine-tuning needs more than 780 GB ({{QLoRA|n:3c65c17b0d0d815a8f4edc33f9583671}}). The arithmetic is in <a href="#rd-mach">Machinery</a>.`],
    ['A capacity ceiling',`An adapter cannot absorb billions of tokens of new knowledge (use CPT); LoRA on attention only underperforms; and the claim that LoRA beats full fine-tuning sits inside the noise of the original paper.`]]},
  {n:'Quantization, precision',k:'fewer bits per weight',page:`{{Quantization and Precision|n:3c65c17b0d0d817b8f41ff66fba4cd0e}}`,c:[
    ['How weights are stored',`No learning at all after training (post-training quantization), or fake quantization inside training (quantization-aware training). Weights, and sometimes activations, move from bf16 (2 bytes) to FP8 (1) or about 4 bits plus scales; fine-grained FP8 is now used for training itself ({{DeepSeek-V3|n:3c65c17b0d0d815fb8dac9ba1e35ab81}}).`],
    ['A calibration set, or none',`GPTQ, AWQ and llama.cpp's importance matrix need a small calibration set; dynamic FP8 needs none; quantization-aware training needs training data. A calibration set unlike real use quietly costs capability off its distribution.`],
    ['Saves memory and time',`About 0.6 GB per billion parameters at 4 bits; DeepSeek-V3's FP8 training kept the loss within 0.25% of BF16 in its ablations ({{DeepSeek-V3|n:3c65c17b0d0d815fb8dac9ba1e35ab81}}). llama.cpp's default Q4_K_M is 4.89 effective bits per weight on Llama-3.1-8B (<a href="https://github.com/ggml-org/llama.cpp/blob/master/tools/quantize/README.md" target="_blank" rel="noopener noreferrer">llama.cpp</a>).`],
    ['Outliers, the low-bit cliff',`A few channels with huge values wreck naive scaling; dense models fall off a cliff below about 3 bits, while MoE experts tolerate harder quantization; newer, heavily trained small models lose more at the same bits.`]]}
  ];
  let sel=[4,1];
  const rows=ST.map((r,ri)=>r.g?'<tr class="sep"><th colspan="5">'+r.g+'</th></tr>':
    '<tr><th class="st" scope="row">'+r.n+'<small>'+r.k+'</small></th>'+r.c.map((c,ci)=>'<td><button data-r="'+ri+'" data-c="'+ci+'" aria-label="'+r.n+': '+AX[ci].n+'">'+c[0]+'</button></td>').join('')+'</tr>').join('');
  $('rd-grid').innerHTML='<thead><tr><th class="st">Stage</th>'+AX.map((a,i)=>'<th>'+(i+1)+' · '+a.n+'<small>'+AXS[i]+'</small></th>').join('')+'</tr></thead><tbody>'+rows+'</tbody>';
  function draw(){const [ri,ci]=sel,r=ST[ri],c=r.c[ci];
    $('rd-grid').querySelectorAll('td button').forEach(b=>b.classList.toggle('on',+b.dataset.r===ri&&+b.dataset.c===ci));
    $('rd-gdet').innerHTML='<h3>'+r.n+' · '+AX[ci].n+'</h3><p>'+c[1]+'</p><p class="go">Compared across all stages: <a href="'+AX[ci].s+'">Axis '+(ci+1)+'</a>. In depth: '+r.page+'.</p>'}
  $('rd-grid').addEventListener('click',e=>{const b=e.target.closest('button[data-r]');if(!b)return;sel=[+b.dataset.r,+b.dataset.c];draw()});
  RD.tabLinks($('rd-gdet'));
  draw();
})();
