// ---- Reading: calculators (fan-out, bloom filter) and the measured tables (from SE) ----
(function(){
  const $=id=>document.getElementById(id),F=FMT,mb=v=>(v/1048576).toFixed(v<1048576*10?1:0)+' MB',pct=v=>v.toFixed(0)+'%';
  const tbl=(id,head,rows)=>{const e=$(id);if(e)e.innerHTML='<thead><tr>'+head.map(h=>'<th'+(h[1]?' class="num"':'')+'>'+h[0]+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr'+(r.hl?' class="hl"':'')+'>'+r.c.map((c,i)=>'<td'+(head[i][1]?' class="num"':'')+'>'+c+'</td>').join('')+'</tr>').join('')+'</tbody>'};
  const note=(id,h)=>{const e=$(id);if(e)e.innerHTML=h};
  // ---- fan-out calculator: Postgres B-tree entry = MAXALIGN(8-byte index tuple header + key) + 4-byte line pointer; usable page 8152 bytes
  const ENTRY=k=>Math.ceil((8+k)/8)*8+4,USABLE=8192-24-16;
  window.FANOUT=function(key,n){const per=Math.floor(USABLE/ENTRY(key)),leaf=Math.round(USABLE*0.9/ENTRY(key)),inner=Math.round(USABLE*0.7/ENTRY(key)),leaves=Math.ceil(n/leaf);
    const lv=LAB.levelsFor(n,inner,leaf);return {per,leaf,inner,leaves,levels:lv,bytes:leaves*8192*(1+1/inner)}};
  function fo(){const n=Math.round(Math.pow(10,+$('rd-fo-n').value)),k=+$('rd-fo-k').value,r=FANOUT(k,n);
    $('rd-fo-nv').textContent=F.n(n);
    $('rd-fo-out').innerHTML=RD.stat('Entry size',ENTRY(k)+' bytes','header, key, alignment, pointer')+RD.stat('Keys per leaf',F.n(r.leaf),'at 90% fill')+RD.stat('Fan-out',F.n(r.inner),'internal pages at 70%')+RD.stat('Levels',r.levels)+RD.stat('Index size',F.b(r.bytes),'approximate');
    const m=SE.m3.depth.find(d=>d.key==='bigint'&&d.rows===1e6);
    $('rd-fo-note').innerHTML='Defaults reproduce the measurement independently: for bigint the formula gives '+FANOUT(8,1e6).leaf+' keys per leaf and '+FANOUT(8,1e6).levels+' levels at 1M rows; Postgres reported '+m.leaf_items_first+' keys on the first leaf and '+m.levels+' levels. Text keys are counted as 1 length byte plus the characters (short-string header); real indexes on text also depend on collation and compression.'}
  if($('rd-fo-n')){$('rd-fo-n').addEventListener('input',fo);$('rd-fo-k').addEventListener('change',fo);fo()}
  // ---- bloom calculator
  function bf(){const b=+$('rd-bf-b').value,k=Math.max(1,Math.round(b*Math.LN2)),p=LAB.bloomFP(b);$('rd-bf-bv').textContent=b;
    $('rd-bf-out').innerHTML=RD.stat('Hash functions k',k,'= round(bits x ln 2)')+RD.stat('False positives',(100*p).toFixed(p<0.001?3:2)+'%')+RD.stat('Memory per 1M keys',F.b(b*1e6/8))+RD.stat('Wasted file reads per 100 misses',(100*p).toFixed(2))}
  if($('rd-bf-b')){$('rd-bf-b').addEventListener('input',bf);bf()}
  // ---- B-tree depth table
  const D=SE.m3.depth.filter(d=>d.key==='bigint').sort((a,b)=>a.rows-b.rows);
  tbl('rd-depth',[['Rows',1],['Levels',1],['Root entries',1],['Leaf pages',1],['Internal pages',1],['Index size',1],['Formula: levels',1]],
    D.map(d=>({c:[F.n(d.rows),d.levels,F.n(d.root_items),F.n(d.leaf_pages),F.n(d.internal_pages),F.b(d.index_size),FANOUT(8,d.rows).levels],hl:d.rows===1e8})));
  const big=D[D.length-1],t36=SE.m3.depth.find(d=>d.key==='text36');
  note('rd-depth-note','PostgreSQL 16.2, one bigint column, index built after loading. At 100 million rows the tree has '+big.levels+' levels and its root only '+big.root_items+' entries, so it has room for about '+F.n(Math.floor(FANOUT(8,1).inner/big.root_items))+' times more keys before a fifth level: a billion rows need 4 levels <span class="ill">derived</span>, as the old page said.'+(t36?' A 36-character text key (a UUID stored as text) fits '+t36.leaf_items_first+' entries per leaf instead of 367 and needs '+t36.levels+' levels and '+F.b(t36.index_size)+' at 1M rows, against '+F.b(SE.m3.depth.find(d=>d.key==='bigint'&&d.rows===1e6).index_size)+' for bigint.':''));
  // ---- splits
  const S=SE.m3.splits.concat(SE.m3.splits_built?[SE.m3.splits_built]:[]);
  tbl('rd-splits',[['1M bigint keys',0],['Leaf pages',1],['Average leaf fill',1],['Index size',1],['Insert time',1]],
    S.map(s=>({c:[s.order,F.n(s.leaf_pages),pct(s.avg_leaf_density),F.b(s.index_size),s.insert_s?s.insert_s.toFixed(1)+' s':'-'],hl:s.order==='random'})));
  const sa=SE.m3.splits.find(s=>s.order==='ascending'),sr=SE.m3.splits.find(s=>s.order==='random');
  note('rd-splits-note','Random order needed '+((sr.leaf_pages/sa.leaf_pages-1)*100).toFixed(0)+'% more leaf pages for the same keys ('+pct(sr.avg_leaf_density)+' full on average, close to the textbook 69%) and took '+(sr.insert_s/sa.insert_s).toFixed(1)+' times as long, with everything still in memory.');
  // ---- primary keys (PG 18)
  const P=SE.m4.pk;
  tbl('rd-pk',[['Primary key',0],['Insert 3M rows',1],['WAL written',1],['Index size',1],['Leaf fill',1]],
    P.map(p=>({c:[p.key,p.seconds.toFixed(1)+' s',F.b(p.wal_bytes),F.b(p.index_size),pct(p.avg_leaf_density)],hl:/v4/.test(p.key)})));
  const p4=P.find(p=>/v4/.test(p.key)),p7=P.find(p=>/v7/.test(p.key)),pb=P.find(p=>/bigint/.test(p.key));
  note('rd-pk-note','PostgreSQL 18.6. The random UUID index ended '+pct(p4.avg_leaf_density)+' full against '+pct(p7.avg_leaf_density)+' for UUID v7, so it is '+(p4.index_size/p7.index_size).toFixed(2)+' times the size; it wrote '+((p4.wal_bytes/p7.wal_bytes-1)*100).toFixed(0)+'% more WAL and took '+(p4.seconds/p7.seconds).toFixed(1)+' times as long. Part of the gap to bigint is the cost of generating UUIDs, not the index. Here the 126 MB index still almost fits in the 128 MB buffer pool; once a random-key index is several times larger than memory, each insert also waits for a disk read, which is what made the content index in section 11 about 12 times slower.');
  // ---- dedup, skip scan
  const dd=SE.m3.dedup;if(dd&&$('rd-dedup'))$('rd-dedup').textContent=F.b(dd.on)+' with deduplication and '+F.b(dd.off)+' without ('+(dd.off/dd.on).toFixed(1)+' times larger)';
  const k16=SE.m4.skip_16,k18=SE.m4.skip_18,leaf=x=>x.nodes.find(n=>/Scan/.test(n.node));
  if($('rd-skip')){const a=leaf(k16.default),b=leaf(k18.default),f=leaf(k16.forced_index);
    $('rd-skip').innerHTML='Postgres 16 chose a '+a.node+' reading '+F.n(k16.default.nodes[0].buffers)+' pages ('+k16.default.ms.toFixed(1)+' ms); forced onto the index it read '+F.n(k16.forced_index.nodes[0].buffers)+' pages ('+k16.forced_index.ms.toFixed(1)+' ms), the whole index. Postgres 18 used an '+b.node+' with '+b.index_searches+' index searches, '+F.n(k18.default.nodes[0].buffers)+' pages, '+k18.default.ms.toFixed(2)+' ms.'}
  // ---- RocksDB
  const R5=SE.m5,lv=R5.runs.find(r=>r.style==='leveled'&&r.bloom),un=R5.runs.find(r=>r.style==='universal'),nb=R5.runs.find(r=>!r.bloom);
  if($('rd-rocks-setup'))$('rd-rocks-setup').innerHTML=F.n(R5.N)+' unique random 16-byte keys with 100-byte values ('+F.b(R5.N*116)+' of data), then '+F.n(R5.N)+' overwrites of random existing keys; memtable '+R5.config.write_buffer_size+', level 1 '+R5.config.max_bytes_for_level_base+', ratio 10, no compression, bloom filters 10 bits per key; '+F.n(lv.reads[0].n)+' lookups of present and of absent keys.';
  const ph=(r,i)=>r.phases[i];
  tbl('rd-rocks',[['RocksDB',0],['Write amp, load',1],['Write amp, overwrite',1],['Space amp after overwrite',1],['Files per level (L0 to L6)',0],['Blocks read per absent-key lookup',1],['Per present key',1]],
    [lv,un,nb].map(r=>({c:[r.style+(r.bloom?'':', no bloom filters'),ph(r,0).write_amp.toFixed(1)+'x',ph(r,1).write_amp.toFixed(1)+'x',(ph(r,1).sst_bytes/lv.phases[0].sst_bytes).toFixed(2)+'x',ph(r,1).files_per_level.join(' '),r.reads[1].data_blocks_per_get.toFixed(2),r.reads[0].data_blocks_per_get.toFixed(2)]})));
  note('rd-rocks-note','Write amplification here counts memtable flushes plus compaction writes divided by the bytes the application wrote; the write-ahead log adds 1 more. Space amplification is SST bytes on disk after the overwrites divided by the SST bytes of the same unique keys fully compacted (the leveled run after loading); RocksDB\'s own live-data estimate was unreliable under universal compaction. Absent-key lookups show the bloom filters at work: with them, a lookup for a missing key read '+lv.reads[1].data_blocks_per_get.toFixed(2)+' data blocks on average; without them, '+nb.reads[1].data_blocks_per_get.toFixed(2)+'. Measured false-positive rate on the leveled run: '+(100*lv.reads[1].bloom_full_positive/(lv.reads[1].bloom_full_positive+lv.reads[1].bloom_useful)).toFixed(2)+'% per filter checked (formula: 0.82%).');
  // ---- Postgres amplification
  const W=SE.m3.write_cost.find(w=>w.indexes===1),m1=SE.m1,logical=m1.pgstattuple[0].tuple_len-24*m1.pgstattuple[0].tuple_count;
  const ru=SE.m2.random_updates.runs.find(r=>r.full_page_writes==='on'&&r.wal_compression==='off'),pages=ru.fpi_records_first;
  const rowB=logical/m1.pgstattuple[0].tuple_count;
  window.PGAMP={append:(W.median_wal+W.sizes.heap+W.sizes.t_pkey)/logical,update:(ru.first_bytes+pages*8192)/(1000*rowB),logical,rowB,pages};
  tbl('rd-pgamp',[['Workload',0],['Logical bytes',1],['Written (WAL + pages)',1],['Write amp',1]],[
    {c:['Append 1M messages, primary key only',F.b(logical),F.b(W.median_wal+W.sizes.heap+W.sizes.t_pkey),PGAMP.append.toFixed(1)+'x']},
    {c:['1,000 random-row updates just after a checkpoint (2 indexes)',F.b(1000*rowB),F.b(ru.first_bytes+pages*8192),PGAMP.update.toFixed(0)+'x'],hl:1}]);
  note('rd-pgamp-note','Logical bytes are the rows without their 24-byte headers ('+F.n(rowB)+' bytes per message on average, from pgstattuple). Append: WAL plus the table and index files ('+F.b(W.median_wal)+' + '+F.b(W.sizes.heap)+' + '+F.b(W.sizes.t_pkey)+'). Updates: WAL ('+F.b(ru.first_bytes)+') plus the '+F.n(pages)+' pages the checkpoint will write back, counted as one write each (the number of page images, a lower bound). Read amplification for a point lookup is the tree height (3 here, section 5) plus one table page per row; space amplification of the table is about '+(m1.sizes[0].heap/logical).toFixed(2)+'x (headers, alignment, free space).');
  // ---- BRIN, hash, partial, covering
  const B=SE.m3.brin;
  if(B){
    tbl('rd-brin',[['',0],['Size',1],['Build',1],['1 hour (1,200 rows): pages, ms',1],['1 day (28,800 rows): pages, ms',1]],[
      {c:['B-tree on created_at',F.b(B.btree),B.btree_build_s.toFixed(1)+' s',F.n(B.hour_btree.hit)+', '+B.hour_btree.ms.toFixed(2),F.n(B.day_btree.hit)+', '+B.day_btree.ms.toFixed(1)]},
      {c:['BRIN on created_at',F.b(B.brin),B.brin_build_s.toFixed(1)+' s',F.n(B.hour_brin.hit)+', '+B.hour_brin.ms.toFixed(2),F.n(B.day_brin.hit)+', '+B.day_brin.ms.toFixed(1)],hl:1},
      {c:['No index (sequential scan)','-','-',F.n(B.hour_seq.hit)+', '+B.hour_seq.ms.toFixed(0),F.n(B.day_seq.hit)+', '+B.day_seq.ms.toFixed(0)]}]);
    note('rd-brin-note','PostgreSQL 16.2, '+F.n(B.rows)+' rows ('+F.b(B.heap)+'), warm cache, one worker. The BRIN index is '+F.n(B.btree/B.brin)+' times smaller and reads about as many pages: it returns whole 128-page ranges whose rows are rechecked one by one. On a shuffled copy of 2M rows, where created_at no longer follows the row order, the same one-hour query through BRIN read '+F.n(B.shuffled_hour_brin.hit)+' pages, more than the whole table of '+F.n(B.shuffled_heap_pages)+' pages, and took '+B.shuffled_hour_brin.ms.toFixed(0)+' ms against '+B.shuffled_hour_seq.ms.toFixed(0)+' ms for a plain sequential scan: every block range spans almost all dates.')}
  const K=SE.m3.kinds;
  if($('rd-hash'))$('rd-hash').innerHTML='On the 1M-message table, a hash index on chat_id is '+F.b(K.hash_chat)+' against '+F.b(K.btree_chat)+' for the B-tree <span class="meas">measured</span>: the B-tree is smaller here because deduplication stores each chat once with a list of rows, while a hash index stores one entry per row. Both found chat 42000 by touching '+K.q_hash.hit+' and '+K.q_plain.hit+' pages. Hash indexes pay off only for long keys that B-tree deduplication cannot help.';
  if($('rd-partial'))$('rd-partial').innerHTML='Measured: '+F.n(K.partial_rows)+' of 1M rows qualify; the partial index is '+F.b(K.partial_long)+' against '+F.b(K.btree_tokens)+' for an index on tokens over all rows.';
  if($('rd-cover'))$('rd-cover').innerHTML='Measured: fetching role and tokens of chat 42000 touched '+K.q_plain.hit+' pages with the plain index and '+K.q_covering.hit+' with the covering one (an Index Only Scan, no table pages), at the price of a '+F.b(K.covering)+' index instead of '+F.b(K.btree_chat)+'.';
  // ---- write cost
  const WC=SE.m3.write_cost;
  if($('rd-wc-bars'))BARS($('rd-wc-bars'),WC.map(w=>({n:w.indexes+' index'+(w.indexes===1?'':'es'),v:w.median_s,l:w.median_s.toFixed(1)+' s',c:w.indexes===6?'var(--c2)':'var(--acc)',hl:w.indexes===6})),{title:'Seconds to insert 1M messages (median of 3)'});
  tbl('rd-wc',[['Indexes',0],['Seconds',1],['WAL',1],['Index bytes',1],['Single-row inserts/s',1]],WC.map(w=>{const ib=Object.entries(w.sizes).filter(([k])=>k!=='heap').reduce((a,[,v])=>a+v,0);
    return {c:[w.indexes?w.names.map(n=>n.replace(/^t_/,'')).join(', '):'none',w.median_s.toFixed(1),F.b(w.median_wal),ib?F.b(ib):'-',F.n(w.single_row_tps)]}}));
  note('rd-wc-note','PostgreSQL 16.2, shared_buffers 128 MB. Index names: pkey (id), chat_created (chat_id, created_at), created (created_at), model_tokens, role_chat, content (the message text, random-looking, 30 to 130 characters). Runs: '+WC.map(w=>w.runs.map(r=>r.s.toFixed(1)).join(' / ')).join('; ')+' seconds.');
  // ---- glossary
  const G=[['g-page','Page','A fixed-size block (8 KB in Postgres) that the database reads and writes as a unit.'],['g-tuple','Tuple','One stored version of a row, with a 23-byte header.'],['g-ctid','ctid','A tuple\'s address: (page number, slot number).'],['g-hot','HOT update','An update that stays on the same page and changes no indexed column, so no index is touched.'],['g-toast','TOAST','Compression and out-of-line storage for values over about 2 KB.'],['g-fsm','Free space map','Per-table map of how much room each page has.'],['g-vm','Visibility map','Two bits per page (all-visible, all-frozen); lets VACUUM and index-only scans skip pages.'],['g-bp','Buffer pool','RAM cache of pages (shared_buffers in Postgres).'],['g-clock','Clock sweep','Postgres\'s eviction rule: usage counts lowered by a rotating hand; evict at zero.'],['g-pagecache','Page cache','The operating system\'s cache of file blocks; Postgres pages may sit here too (double buffering).'],['g-wal','Write-ahead log (WAL)','Sequential log of every change, flushed before a commit is acknowledged.'],['g-lsn','LSN','Log sequence number: a byte position in the WAL.'],['g-checkpoint','Checkpoint','Writing all dirty pages so older WAL can be recycled and recovery can start later.'],['g-fpi','Full-page image','A copy of a whole page logged on its first change after a checkpoint, to repair torn pages.'],['g-btree','B-tree','A balanced tree of sorted pages; the default index.'],['g-fanout','Fan-out','Children per internal page; decides the tree height.'],['g-posting','Posting list','One key followed by the list of rows that have it.'],['g-lsm','LSM-tree','Log-structured merge-tree: memtable, flushed sorted files, background compaction.'],['g-sst','SSTable','An immutable sorted file of an LSM-tree.'],['g-bloom','Bloom filter','A bit array answering "certainly not here" or "maybe here".'],['g-tomb','Tombstone','A marker that records a delete in an LSM-tree.'],['g-rum','RUM conjecture','Read, update and memory overheads cannot all be minimised at once.'],['g-wamp','Write amplification','Bytes written to storage per byte the application wrote.'],['g-heap','Heap table','A table whose rows sit in no particular order, found through separate indexes.'],['g-clustered','Clustered index','An index whose leaves are the table rows themselves (InnoDB, SQLite WITHOUT ROWID).'],['g-am','Access method','An index type in Postgres: btree, hash, gin, gist, spgist, brin.'],['g-colstore','Column store','Storage that keeps each column together, compressed; for analytics.'],['g-zonemap','Zone map','Min and max per block, used to skip blocks (BRIN is one).']];
  const gl=$('rd-gl');if(gl)gl.innerHTML=G.map(g=>'<div><b><a href="#'+g[0]+'">'+g[1]+'</a></b>: '+g[2]+'</div>').join('');
})();
