"""Slim inputs/toy.json (written by toy_sweep.mjs) into window.TOYDATA for the page: parts/_gen_toydata.js.
Also adds the decoded figures (inputs/figs.json) as window.FIGS. usage: python3 mk_toydata.py (build.sh runs it)"""
import json
d = json.load(open('inputs/toy.json')); f = json.load(open('inputs/figs.json'))
r3 = lambda x: round(x, 4) if isinstance(x, float) else x
prof = lambda p: {k: ([r3(v) for v in p[k]] if isinstance(p[k], list) else r3(p[k])) for k in ('acc', 'greedy', 'forget', 'step1', 'pass', 'maj', 'bySum')}
out = {'cfg': d['cfg'], 'sft': d['sft'], 'np': d['np'], 'nv': d['nv'], 'base': prof(d['base']), 'basePerq': d['base']['perq'], 'runs': {}, 'lr': d['lr'], 'lam': d['lam'], 'G': {g: {'final': v['final'], 'zero': [r3(z) for z in v['zero']]} for g, v in d['G'].items()}, 'beta0': d['beta0'], 'long': d['long']}
for m, r in d['runs'].items():
    out['runs'][m] = {'finals': r['finals'], 'ms': r['ms'], 'final': prof(r['final']), 'perq': r['final']['perq'],
                      'seeds': {s: {'acc': [h[1] for h in v['hist']], 'kl': [h[3] for h in v['hist']], 'samples': v['hist'][-1][4], 'zero': r3(v['zero']) if v['zero'] is not None else None} for s, v in r['seeds'].items()}}
import os
if os.path.exists('model/check_engine.json'):
    ck = json.load(open('model/check_engine.json')); out['check'] = {'verdict': ck['verdict'], 'worst': ck['worst'], 'methods': {k: v for k, v in ck.items() if isinstance(v, dict)}}
figs = {k: {'figure': v['figure'], 'panels': {b: {'series': P['series'], 'x_ticks': P['x_ticks']} for b, P in v['panels'].items()}} for k, v in f.items()}
open('parts/_gen_toydata.js', 'w').write('// Generated by mk_toydata.py from inputs/toy.json and inputs/figs.json.\nwindow.TOYDATA=' + json.dumps(out, separators=(',', ':')) + ';\nwindow.FIGS=' + json.dumps(figs, separators=(',', ':')) + ';\n')
print('toydata', len(json.dumps(out)), 'figs', len(json.dumps(figs)))
