// Every toy number the page quotes. node toy_sweep.mjs  (about 2 to 3 minutes; run it in the background)
// Writes parts/_gen_toy.js (the base model's weights, float32 in base64) and inputs/toy.json.
import fs from 'fs';import {createRequire} from 'module';const require=createRequire(import.meta.url);
const T=require('./parts/22_js_toy.js');
const t0=Date.now(),log=(...a)=>console.log(((Date.now()-t0)/1000).toFixed(1)+'s',...a);
// 1. the base ("Instruct") model: SFT from scratch on the careless demonstrations
const SFT={steps:2000,lr:0.01,seed:1,batch:32};
const raw=T.trainSFT(T.ALLQ,SFT);const f32=new Float32Array(raw);const b64=Buffer.from(f32.buffer).toString('base64');
const base=T.decode(b64);
fs.writeFileSync('parts/_gen_toy.js','// Generated by toy_sweep.mjs: the toy base model (SFT, '+SFT.steps+' steps), '+T.NP+' float32 weights.\nTOY.BASE=TOY.decode("'+b64+'");\n');
log('base written',b64.length,'chars');
const KS=T.KS,TR=400;
function profile(p){const e=T.evaluate(p,T.ALLQ,{greedy:1});return {acc:e.acc,greedy:e.greedy,forget:e.forget,step1:e.step1,
  pass:KS.map(k=>T.passK(e.per,k)),maj:KS.map(k=>T.majK(e.per,k,TR,99)),
  perq:e.per.map(x=>+x.pc.toFixed(4)),
  bySum:Array.from({length:19},(_,s)=>{const xs=e.per.filter(x=>x.q[0]+x.q[1]===s);return xs.reduce((a,x)=>a+x.pc,0)/xs.length})}}
const out={sft:SFT,np:T.NP,nv:T.NV,base:profile(base),runs:{},lr:{},lam:{},G:{},cfg:null};
log('base acc',out.base.acc.toFixed(4),'pass@64',out.base.pass[5].toFixed(4),'maj@64',out.base.maj[5].toFixed(4));
const CFG={lr:0.003,batch:8,G:8,beta:0.04,dbeta:0.1,lam:0.95,steps:400,every:20};out.cfg=CFG;
const cfgFor=(m,seed,o)=>Object.assign({lr:CFG.lr,batch:CFG.batch,G:CFG.G,beta:m==='dpo'?CFG.dbeta:CFG.beta,lam:CFG.lam,seed},o||{});
function go(m,seed,o,S){const t=Date.now();let zero=0,groups=0;const c=T.makeCtx(base,T.ALLQ,m,cfgFor(m,seed,o));const hist=[];
  const ev=()=>{const e=T.evaluate(c.p,T.ALLQ);hist.push([c.steps,+e.acc.toFixed(4),+e.forget.toFixed(4),+T.klRef(c).toFixed(4),c.samples])};
  ev();for(let s=0;s<(S||CFG.steps);s++){const info=T.grad(c);zero+=info.zero||0;groups+=(T.METHODS[m].online?c.cfg.batch:0);if(info.cg)T.step(c.critic,info.cg,c.copt);T.step(c.p,info.g,c.opt);c.steps++;if((s+1)%CFG.every===0)ev()}
  return {c,hist,zero:groups?zero/groups:null,ms:Date.now()-t}}
const MS=Object.keys(T.METHODS);
for(const m of MS){out.runs[m]={seeds:{}};for(const seed of [5,6,7]){const r=go(m,seed);out.runs[m].seeds[seed]={hist:r.hist,zero:r.zero};
    if(seed===5){out.runs[m].final=profile(r.c.p);out.runs[m].ms=r.ms}}
  const fin=[5,6,7].map(s=>out.runs[m].seeds[s].hist.at(-1)[1]);out.runs[m].finals=fin;log(m,fin.map(v=>v.toFixed(3)).join(' '),'maj64',out.runs[m].final.maj[5].toFixed(3),'pass64',out.runs[m].final.pass[5].toFixed(3),'zero',out.runs[m].seeds[5].zero)}
for(const m of MS){out.lr[m]={};for(const lr of [0.0003,0.001,0.003,0.01]){out.lr[m][lr]=lr===0.003?out.runs[m].seeds[5].hist.at(-1)[1]:go(m,5,{lr}).hist.at(-1)[1]}log('lr',m,JSON.stringify(out.lr[m]))}
for(const lam of [0,0.5,0.95,1]){out.lam[lam]=lam===0.95?out.runs.ppo.seeds[5].hist.map(h=>h[1]):go('ppo',5,{lam}).hist.map(h=>h[1]);log('lam',lam,out.lam[lam].at(-1))}
for(const G of [2,4,8,16]){const rs=[5,6,7].map(seed=>go('grpo',seed,{G,batch:64/G}));out.G[G]={final:rs.map(r=>r.hist.at(-1)[1]),zero:rs.map(r=>r.zero),hist:rs[0].hist.map(h=>h[1])};log('G',G,JSON.stringify(out.G[G].final),JSON.stringify(out.G[G].zero))}
out.beta0={};for(const m of ['grpo','ppo']){out.beta0[m]=[5,6,7].map(seed=>go(m,seed,{beta:0}).hist.at(-1)[1]);log('beta0',m,JSON.stringify(out.beta0[m]))}
out.long={};for(const m of ['rft','onrft','grpo']){out.long[m]=go(m,5,{},1200).hist.map(h=>h[1]);log('long',m,out.long[m].at(-1))}
fs.writeFileSync('inputs/toy.json',JSON.stringify(out));log('done');
