// ---- Then and now: the LDM recipe card, changed one system at a time ----
(function(){const F=[['ae','Autoencoder'],['lat','Latent'],['net','Denoiser'],['obj','Objective'],['text','Text encoder τθ'],['size','Size'],['data','Resolution, data']];
  const ax=id=>'https://arxiv.org/abs/'+id;
  const S=[
   {y:'December 2021',n:'LDM (this paper), text-to-image model',u:ax('2112.10752'),set:{ae:'KL-reg., f = 8, trained once with LPIPS + patch GAN',lat:'32 × 32 × 4 at 256², rescaled by 1 / σ̂ (0.18215)',net:'UNet with cross-attention (spatial transformer blocks)',obj:'ε-prediction, L<sub>LDM</sub> (Eq. 3); classifier-free guidance',text:'transformer on BERT tokens, trained jointly, 32 layers, width 1,280',size:'1.45B parameters in all',data:'256², LAION-400M'},c:'The starting card: Table 15, Table 17 and the released txt2img-1p4B config.'},
   {y:'August 2022',n:'Stable Diffusion v1',u:'https://github.com/CompVis/stable-diffusion',set:{lat:'64 × 64 × 4 at 512², same 0.18215',text:'frozen CLIP ViT-L/14 (123M), context 768',size:'860M UNet',data:'pretrained at 256², fine-tuned at 512²; LAION-5B subsets'},c:'"A Latent Diffusion Model on 512x512 images from a subset of the LAION-5B database", "a frozen CLIP ViT-L/14 text encoder" (SD README; v1-inference.yaml). The architecture is this paper\'s, with open weights.'},
   {y:'late 2022',n:'Stable Diffusion 2.0 / 2.1',u:ax('2307.01952'),set:{text:'OpenCLIP ViT-H, context 1,024',size:'865M UNet'},c:'SDXL\'s Table 1 lists the 2.x line: the same UNet layout with a larger open text encoder (release date not in a fetched source).'},
   {y:'December 2022',n:'DiT',u:ax('2212.09748'),set:{net:'a Transformer on latent patches (no UNet)',text:'class labels (ImageNet)',size:'up to DiT-XL/2',data:'ImageNet 256² and 512²; FID 2.27 at 256²'},c:'"We use an off-the-shelf pre-trained variational autoencoder (VAE) model from Stable Diffusion": the latent is kept and the backbone replaced (#VIT#).'},
   {y:'July 2023',n:'SDXL',u:ax('2307.01952'),set:{net:'UNet with "a three times larger" backbone, more attention blocks',text:'CLIP ViT-L and OpenCLIP ViT-bigG, context 2,048',size:'2.6B UNet, 817M text encoders',data:'multiple aspect ratios, plus a refiner'},c:'Still a latent UNet: "a latent diffusion model for text-to-image synthesis" with a larger cross-attention context.'},
   {y:'November 2023',n:'Stable Video Diffusion',u:ax('2311.15127'),set:{net:'image LDM UNet with temporal layers inserted',data:'video, after text-to-image pretraining'},c:'"Latent diffusion models trained for 2D image synthesis have been turned into generative video models by inserting temporal layers."'},
   {y:'February 2024',n:'Sora',u:'https://openai.com/index/video-generation-models-as-world-simulators/',set:{ae:'a learned video compression network',lat:'spacetime patches of a compressed latent',net:'diffusion Transformer',data:'video of variable length and aspect ratio'},c:'"Sora is trained on and subsequently generates videos within this compressed latent space" (OpenAI report; no paper, sizes undisclosed).'},
   {y:'March 2024',n:'Stable Diffusion 3',u:ax('2403.03206'),set:{ae:'KL autoencoder, f = 8, retrained',lat:'16 channels ("increasing the number of latent channels d significantly boosts reconstruction")',net:'MM-DiT: a Transformer with separate weights for text and image tokens',obj:'rectified flow with noise sampling biased to perceptually relevant scales',text:'two CLIP encoders and T5',size:'up to 8B'},c:'Latent space, a Transformer and a flow objective together; f = 8 is kept for every model in the paper.'},
   {y:'August 2024',n:'FLUX.1',u:'https://huggingface.co/black-forest-labs/FLUX.1-schnell',set:{lat:'16 channels, scale factor 0.3611',net:'rectified flow Transformer',obj:'rectified flow',size:'12B parameters'},c:'"A 12 billion parameter rectified flow transformer" (model card); the autoencoder in the code is ch_mult [1, 2, 4, 4], z_channels 16, the same f = 8 layout as this paper\'s.'}];
  const cards=[];let cur={};S.forEach(s=>{cur=Object.assign({},cur,s.set);cards.push(cur)});
  const link=s=>s.replace('#VIT#','<a href="https://app.notion.com/p/3c65c17b0d0d811fa231cfcde6c1954d" target="_blank" rel="noopener noreferrer">ViT</a>');
  const steps=S.map(s=>({t:s.y+': '+s.n,c:link(s.c)+' '+A(s.u,'source')}));
  function draw(m,k,e){const C=cards[k],P=k?cards[k-1]:{},ch=S[k].set;let h='<dl class="recipe">';
    F.forEach(([f,l])=>{const changed=k>0&&(f in ch);h+='<dt>'+l+'</dt><dd'+(changed?' class="chg"':'')+'>'+(changed&&e<.5&&P[f]?'<span class="mute" style="text-decoration:line-through">'+P[f]+'</span>':C[f])+'</dd>'});
    return h+'</dl>'}
  function counters(m,k){const ch=Object.keys(S[k].set).length;return stat('year',S[k].y.replace(/^.* /,''),S[k].n)+stat('lines changed',k?ch+' of '+F.length:'the original',k?'highlighted':'')+stat('still as in LDM',F.filter(([f])=>cards[k][f]===cards[0][f]).length+' of '+F.length,'lines unchanged since 2021')}
  makeAnim({id:'thx',mode:'a',dur:4200,modes:{a:steps},draw,counters});
})();
