# Writes parts/21_js_data.js: the configs and real weights the page's visuals compute from.
# Runs recompute.py first so inputs/recompute.json is current.
import json, os, subprocess, sys
H = os.path.dirname(os.path.abspath(__file__))
I = os.path.join(H, 'inputs')
subprocess.run([sys.executable, os.path.join(H, 'recompute.py')], check=True, stdout=subprocess.DEVNULL)
R = json.load(open(os.path.join(I, 'recompute.json')))
cfg = lambda f: json.load(open(os.path.join(I, f)))
phi = cfg('phi3_mini_128k_config.json')
t5 = cfg('t5_base_relative_bias.json')
dec = t5['decoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight']
# presets for the RoPE visuals (values from the config.json files in inputs/, see recompute.py)
P = {}
for k, p in R['presets'].items():
    P[k] = dict(name=p['name'], base=p['base'], dim=p['dim'], L=p['L'], s=p['s'], method=p['method'], maxpos=p['maxpos'])
P['llama31'].update(low=1.0, high=4.0)
P['llama4'].update(low=1.0, high=1.0)
P['oss'].update(truncate=False)
P['phi3'].update(long=[round(x, 4) for x in phi['rope_scaling']['long_factor']], short=[round(x, 4) for x in phi['rope_scaling']['short_factor']])
data = dict(presets=P, t5dec=[[round(x, 3) for x in row] for row in dec], R={k: R[k] for k in ('yarn_bands', 'llama31_bands', 'deepseek_temp', 'yarn_temp_table', 'layers', 'partial', 'llama4_temp', 't5_last_bucket_starts')})
js = '// ---- Data: generated by src/export_data.py from inputs/ (config.json files, T5-base relative biases, recompute.json). Do not edit. ----\nwindow.PE_DATA=' + json.dumps(data, separators=(',', ':')) + ';\n'
open(os.path.join(H, 'parts', '21_js_data.js'), 'w').write(js)
print('21_js_data.js', len(js), 'bytes')
