# Writes coverage.json: every fact, number, mechanism step, caveat and link of live.md (the old Notion page), where the
# HTML carries it, and a string that must appear in the built page (checked here), or why it was dropped or corrected.
import json, os, re, html as H
here = os.path.dirname(os.path.abspath(__file__))
page = open(os.path.join(here, '..', 'index.html')).read()
text = H.unescape(re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', ' ', re.sub(r'<script.*?</script>|<style.*?</style>', ' ', page, flags=re.S))))
I = [
 ("Header: 6 min read, +2h 50m resources", "Header line, recomputed", "Reading tab about", "kept, recomputed from the new page (stale counts replaced)"),
 ("Resource: Aman Arora, How LLMs scaled from 512 to 2M context (~50 min)", "Further reading, Best resources", "amaarora.github.io/posts/2025-09-21-rope-context-extension.html", ""),
 ("Resource: EleutherAI, Rotary Embeddings, a relative revolution (~30 min)", "Further reading, Best resources", "blog.eleuther.ai/rotary-embeddings", ""),
 ("Resource: RoFormer page (the RoPE original)", "Reading RoPE; Further reading, Paper pages", "3c65c17b0d0d81cfa5e9f54459720098", ""),
 ("Resource: ALiBi paper (45 min)", "Reading; Further reading", "arxiv.org/abs/2108.12409", ""),
 ("Resource: YaRN paper (45 min)", "Reading; Further reading", "arxiv.org/abs/2309.00071", ""),
 ("Positional embedding: learned vector per position (GPT-2, BERT)", "Absolute or relative; In one screen table", "learned table: row", ""),
 ("Learned embeddings are hard-capped at the trained length, no extrapolation", "Absolute or relative; Six schemes chart (no row past 512)", "no extrapolation at all", ""),
 ("Positional encoding: fixed mathematical function of position", "Absolute or relative", "is a fixed function of position", ""),
 ("Sinusoidal chosen because it 'may allow the model to extrapolate to sequence lengths longer than the ones encountered during training'", "Absolute or relative (quote, linked)", "may allow the model to extrapolate to sequence lengths longer than the ones encountered during training", ""),
 ("In practice extrapolation is still poor, interpolation fine", "Absolute or relative, with ALiBi's measurement", "interpolates well and extrapolates poorly", "now sourced"),
 ("Absolute answers 'where is this token?' and is added to the input embedding once", "Absolute or relative", "where is this token?", ""),
 ("Relative answers 'how far apart?' and acts inside attention, matching what attention needs", "Absolute or relative", "how far apart are these two tokens?", ""),
 ("Shaw et al. 2018: learnable vector per (clipped) relative distance into keys and/or values", "The relative family", "clipped at a maximum", ""),
 ("T5: learnable scalar bias per relative-distance bucket added to the logit", "The relative family; Six schemes (real T5-base biases)", "one learned scalar per distance bucket", ""),
 ("T5: logarithmic bucketing so far distances share buckets", "The relative family", "grow logarithmically up to an offset of 128", ""),
 ("T5: cheap and effective, per-head learned", "The relative family", "Cheap, per-head, and learned", ""),
 ("ALiBi: no embeddings, static non-learned linear penalty m*distance", "The relative family; Six schemes", "fixed, non-learned", ""),
 ("ALiBi: slope m geometric per head", "The relative family (8 and 16-head slopes, MPT's rule)", "1/2, 1/4, ..., 1/256", ""),
 ("ALiBi: closer tokens score higher", "The relative family", "Closer tokens score higher", ""),
 ("ALiBi: extrapolation, train at 1k, run at 2k+ with little degradation", "In one screen; The relative family (abstract quote)", "extrapolates to input sequences of length 2048", ""),
 ("ALiBi used by BLOOM, MPT", "In one screen; The relative family (BLOOM paper, MPT config)", "Used by", ""),
 ("ALiBi largely displaced by RoPE + scaling", "The relative family", "uses RoPE instead, with scaling for long contexts", ""),
 ("DeBERTa: summing content and position entangles them too early", "The relative family", "mixes the two from the first layer", ""),
 ("DeBERTa: separate content vector H and relative position vector P; attention from content-content, content-position, position-content", "The relative family (abstract quote)", "content-to-content, content-to-position and position-to-content", ""),
 ("RoPE rotates instead of adding (adding perturbs magnitude and direction)", "RoPE section", "rotates</b> instead of adding", ""),
 ("RoPE: pairwise 2D subspaces, position m rotated by m*theta_i", "RoPE section (formula box)", "is rotated by the angle", ""),
 ("theta_i = base^(-2i/d), base classically 10000", "RoPE section (formula box)", "10,000 in the paper", ""),
 ("Dot product of rotated vectors depends only on angle difference, i.e. relative distance m-n", "RoPE section", "depends only on the", ""),
 ("RoPE: absolute in form, relative-position-dependent attention", "RoPE section", "absolute in form", ""),
 ("RoPE: no extra parameters, applied at every layer", "RoPE section", "with no parameters", ""),
 ("Long-range decay falls out of the mixed frequencies", "RoPE section, with Barbero's caveat and link to RoFormer's Figure 2", "long-term decay of scores with distance", "qualified: holds for the bound and aligned vectors, not in expectation"),
 ("Every mainstream 2023+ LLM (Llama, Qwen, DeepSeek, Gemma, Mistral) uses RoPE or a variant", "RoPE section (configs)", "Mistral", ""),
 ("Partial RoPE: rotate only a fraction of dims (GLM, DeepSeek MLA decoupled RoPE keys)", "Variants table (GPT-NeoX, Phi-2, GLM-4.5, DeepSeek-V3)", "Partial RoPE", ""),
 ("DeepSeek MLA decoupled RoPE keys", "Variants (DeepSeek-V2 quote), table", "Decoupled RoPE", ""),
 ("2D/multimodal RoPE (Qwen-VL: separate frequencies for image axes)", "Variants (Qwen2-VL M-RoPE quote, mrope_section)", "M-RoPE", ""),
 ("Interleaved vs split-half layouts, implementation gotcha when porting weights", "Variants: layout paragraph; Common mistakes", "Interleaved or split-half layout", ""),
 ("Trained at L, RoPE degrades sharply past L", "What breaks past the trained length; animation", "What breaks past the trained length", ""),
 ("...because high-frequency dims see unseen rotation angles", "Correction box; Common mistakes", "Correction to the old page", "corrected: it is the low-frequency pairs (YaRN section 3.2)"),
 ("PI: divide all positions by s = L_new/L_train, squeezed into the trained range", "Stretching RoPE; animation; Stretch tab", "divide every position by", ""),
 ("PI needs a short fine-tune", "Stretching RoPE (within 1000 steps)", "within 1000 steps", ""),
 ("PI hurts short-context slightly (crowds all frequencies equally)", "Stretching RoPE (2% regressions); animation counter (fastest pair 1/s)", "minor degradation", ""),
 ("NTK-aware: raise the base instead of scaling positions", "Stretching RoPE", "raise the base", ""),
 ("NTK-aware example 'e.g. 10000 -> 500000+'", "Common mistakes", "NTK scaling means a base like 500,000", "corrected: s = 4 at d = 128 gives 40,890; 500,000 is Llama 3's pretraining base (ABF)"),
 ("NTK: high-frequency dims barely touched, low-frequency dims interpolate", "Stretching RoPE; Stretch tab", "Pair 0 is untouched", ""),
 ("NTK works surprisingly well zero-shot", "Stretching RoPE", "works surprisingly well with no fine-tuning", ""),
 ("Dynamic NTK adjusts the base with current sequence length at inference", "Stretching RoPE; animation", "Dynamic NTK", ""),
 ("YaRN: NTK-by-parts, leave high-frequency dims alone, fully interpolate low-frequency dims whose wavelength exceeds the context, ramp in between", "Stretching RoPE (formula box); animation; Stretch tab", "NTK-by-parts", ""),
 ("YaRN: attention temperature (logit scaling) correction", "Stretching RoPE formula box (values per s, DeepSeek variants)", "0.1 ln", ""),
 ("YaRN: best quality per fine-tuning token", "Stretching RoPE (10x fewer tokens, 2.5x fewer steps)", "10x less tokens and 2.5x less training steps", ""),
 ("YaRN used by Qwen, DeepSeek, many 128k+ models", "Stretching RoPE; Recipes; Stretch tab configs", "DeepSeek-V2 and V3, Qwen3, gpt-oss and SmolLM3 use it", ""),
 ("LongRoPE / LongRoPE2: per-dimension rescaling factors via evolutionary search", "Stretching RoPE", "evolutionary search", ""),
 ("LongRoPE: plus mixed-context training", "Stretching RoPE (LongRoPE2's mixed context window training)", "mixed context window training", ""),
 ("LongRoPE behind Phi-3's 2M-token claims", "Stretching RoPE; Common mistakes", "LongRoPE is behind Phi-3", "corrected: 2,048K is the LongRoPE paper's result on LLaMA2 and Mistral; Phi-3-mini uses LongRoPE for 128K"),
 ("Production recipe (Llama 3 style): pretrain at 8k with a large base (500k)", "Recipes table", "8K, base 500,000", ""),
 ("...then continued pretraining on long documents at 128k with scaled RoPE", "Recipes table (six stages, 800B tokens; the llama3 scaling is in the released config, not described in the paper)", "Six stages from 8K to 128K", "qualified: the paper describes the stages, not the scaling"),
 ("...then verify with needle-in-haystack and real long-context evals", "Recipes table", "needle-in-a-haystack retrieval is perfect", ""),
 ("NoPE: decoder-only models with no PE still learn position implicitly through the causal mask", "Beyond RoPE; In one screen; Six schemes (NoPE weights uniform)", "still learns order from the causal mask", ""),
 ("NoPE: some evidence of better length generalisation in theory", "Beyond RoPE (Kazemnejad et al.)", "outperforms other explicit positional encoding methods", ""),
 ("NoPE: weaker in-context retrieval at scale", "Beyond RoPE; Common mistakes", "NoPE layers are worse at retrieval", "corrected: Yang et al. found NoPE put the most attention on the needle; it lags on standard benchmarks"),
 ("Hybrids: interleaving RoPE layers with NoPE layers (every 4th layer global-attention NoPE) in Llama 4-era models", "Variants table with layer strips (Llama 4, Command A, SmolLM3); Beyond RoPE", "every 4th layer", ""),
 ("CoPE (Meta 2024): positions computed by counting selected tokens via sigmoid gates on query-key pairs", "Beyond RoPE", "Positions are counted, not indexed", ""),
 ("CoPE: position can mean i-th sentence or i-th verb", "Beyond RoPE", "the i-th sentence", ""),
 ("CoPE: solves counting/selective-copy tasks standard PEs fail; not yet mainstream at scale", "Beyond RoPE", "selective copy, counting and Flip-Flop", ""),
 ("FoPE, wavelet-based, HoPE: research on robust frequency components for extrapolation", "Beyond RoPE (each linked and summarised)", "FoPE", ""),
 ("Long context also depends on attention: sliding window + few global layers, sparse attention (DeepSeek DSA/NSA)", "Beyond RoPE", "Long context is not only positions", ""),
 ("Link: Topic: inference-and-serving", "Beyond RoPE; Further reading", "3c65c17b0d0d81c08b3bc95ff45c7b13", ""),
 ("Link: Topic: llms (architecture notes)", "Beyond RoPE; Further reading", "3c65c17b0d0d812d9e00f6ec89965286", ""),
]
items, miss = [], []
for fact, where, needle, note in I:
    ok = needle in page or needle in text
    if not ok: miss.append(needle)
    items.append(dict(fact=fact, where=where, check=needle, found=ok, **({'note': note} if note else {})))
json.dump(dict(source='src/live.md (Notion fetch of 2026-09-20 page state)', items=items,
               counts=dict(total=len(items), carried=sum(1 for i in items if i['found']), corrected=sum(1 for i in items if i.get('note', '').startswith('corrected')))),
          open(os.path.join(here, 'coverage.json'), 'w'), indent=1, ensure_ascii=False)
print(len(items), 'items;', len(items) - len(miss), 'found;', 'missing:', miss)
