"""Quantise the toy models for the browser and measure what quantisation costs.

  OMP_NUM_THREADS=2 uv run --with torch --with numpy python export.py [bits]      (bits 6 or 8; default 8)

Each tensor is quantised per output row (the first dimension: an output channel of a conv, a row of a linear layer) with
scale max|w| / (2^(bits-1) - 1). 8-bit codes are bytes in base64; 6-bit codes are one base64 character each. Writes
parts/20_model_data.js (window.LDM_W) and model/quant_report.json: autoencoder PSNR and checker agreement, and diffusion
sample scores, float against dequantised, same seeds.
"""
import base64, json, os, sys
import numpy as np
import torch
import toy as Y
import train as TR

HERE = os.path.dirname(os.path.abspath(__file__))
MD = os.path.join(HERE, 'model')
A64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
SHIP_AE = [int(x) for x in os.environ.get('SHIP_AE', '2,4,8,16').split(',')]
SHIP_DM = os.environ.get('SHIP_DM', 'pix,f4').split(',')


def quantise(state, bits):
    q = 2 ** (bits - 1) - 1
    enc, deq = {}, {}
    for n, w in state.items():
        w = w.float().numpy().astype(np.float64)
        w2 = w.reshape(w.shape[0], -1) if w.ndim > 1 else w.reshape(1, -1)
        s = np.abs(w2).max(1, keepdims=True) / q
        s[s == 0] = 1.0
        s = s.astype(np.float32).astype(np.float64)
        c = np.clip(np.round(w2 / s), -q, q).astype(np.int64)
        deq[n] = torch.tensor((c * s).reshape(w.shape), dtype=torch.float32)
        codes = (c + q).reshape(-1)
        qs = ''.join(A64[k] for k in codes) if bits == 6 else base64.b64encode(codes.astype('u1').tobytes()).decode()
        enc[n] = {'shape': list(w.shape), 's': base64.b64encode(s[:, 0].astype('<f4').tobytes()).decode(), 'q': qs}
    return enc, deq


def ae_eval(m, X, P):
    with torch.no_grad():
        mu, lv = m.encode(X)
        xr = m.decode(mu).clamp(-1, 1)
    a, b = (X + 1) / 2, (xr + 1) / 2
    mse = ((a - b) ** 2).flatten(1).mean(1)
    psnr = float((10 * torch.log10(1 / mse)).mean())
    r0, r1 = Y.check(a.permute(0, 2, 3, 1).numpy()), Y.check(b.permute(0, 2, 3, 1).numpy())
    agree = float(np.mean((r0['colour'] == r1['colour']) & (r0['shape'] == r1['shape']) & (r0['pos'] == r1['pos']) & r1['valid']))
    return dict(psnr=psnr, checker_agree=agree)


def test_images(n=400):
    rng = np.random.default_rng(99)
    P = Y.sample_params(n, rng, Y.all_combos())
    return torch.tensor(Y.render(P), dtype=torch.float32).permute(0, 3, 1, 2) * 2 - 1, P


def main(bits):
    out = {'_doc': 'Toy latent diffusion weights, %d-bit per-row quantised; see src/export.py' % bits, 'bits': bits,
           'T': Y.TSTEPS, 'lin': [Y.LIN_START, Y.LIN_END], 'NULL': Y.NULL, 'vocab': Y.VOCAB, 'held': [list(c) for c in Y.heldout_combos()], 'models': {}}
    rep = {'bits': bits, 'ae': {}, 'dm': {}}
    X, P = test_images()
    for f in SHIP_AE:
        ck = torch.load(TR.ae_path(f))
        enc, deq = quantise(ck['state'], bits)
        c, C = TR.AE_CFG[f]
        out['models']['ae%d' % f] = {'cfg': [f, c, C], 't': enc}
        mf = Y.AE(f, c, C); mf.load_state_dict(ck['state']); mf.eval()
        mq = Y.AE(f, c, C); mq.load_state_dict(deq); mq.eval()
        rep['ae'][f] = dict(float=ae_eval(mf, X, P), quant=ae_eval(mq, X, P), scale=ck['scale'], params=sum(p.numel() for p in mf.parameters()))
        print('ae', f, rep['ae'][f], flush=True)
    held = Y.heldout_combos()
    for name in SHIP_DM:
        ck = torch.load(os.path.join(MD, 'dm_%s.pt' % name))
        enc, deq = quantise(ck['state'], bits)
        mf, f, c = TR.dm_model(name); mf.load_state_dict(ck['state']); mf.eval()
        mq, _, _ = TR.dm_model(name); mq.load_state_dict(deq); mq.eval()
        cfg = dict(res=mf.res, cin=mf.cin, chs=mf.chs, D=mf.D, T=mf.T, attn_max=8, f=f, scale=ck['scale'], ae=('ae%d' % f) if f > 1 else None)
        out['models']['dm_' + name] = {'cfg': cfg, 't': enc}
        ae = None if f == 1 else TR.load_ae(f)[0]
        rep['dm'][name] = dict(float=TR.eval_dm(mf, name, f, ae, ck['scale'], held, 4), quant=TR.eval_dm(mq, name, f, ae, ck['scale'], held, 4),
                               params=sum(p.numel() for p in mf.parameters()), step=ck['step'])
        print('dm', name, rep['dm'][name], flush=True)
    s = json.dumps(out, separators=(',', ':'))
    open(os.path.join(HERE, 'parts', '20_model_data.js'), 'w').write(
        '// Generated by export.py: the toy autoencoders and latent/pixel diffusion models of the Run tab, %d-bit weights.\nwindow.LDM_W=%s;\n' % (bits, s))
    json.dump(rep, open(os.path.join(MD, 'quant_report%d.json' % bits), 'w'), indent=1)
    print('wrote parts/20_model_data.js', len(s), 'bytes')


if __name__ == '__main__':
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 8)
