"""Write parts/21_audit_data.js: the 15 test days of the released GPT-5.3 single-day corpus (2,106 account-days of
the 142 accounts not assigned collusive threats), as integer audit counts, with the two classical monitors' fitted
profiles (Appendix F.2, F.3; fitted here on training days 1 to 12, routine account-days of non-held-out accounts) and
Python's reference results for the in-page check. The page recomputes every score and every R@K/day from these.

Encoding: rows are "acct,n,c1,...,c20" in base 36 with empty fields for zeros, joined by ';', one string per day.
"""
import json, os
import monitors as M

F = M.load('gpt53_single_day')
tr, va, te = M.split_days(F)
col = set(F['collusion'])
accts = sorted({a for a, d, n, raw in F['rows'] if a not in col})
ai = {a: i for i, a in enumerate(accts)}
rows = M.train_rows(F, tr, 'routine')
gmed, gsc = M.fit([v for a, d, v in rows])
groups = sorted({F['group'].get(a, '_global') for a in accts})
byg = {}
for a, d, v in rows: byg.setdefault(F['group'].get(a, '_global'), []).append(v)
prof = {g: M.fit(vs) for g, vs in byg.items()}
lab = {(a, d): (sc, o) for a, d, sc, o in F['labels']}

def _b36(x):
    s = ''
    while x: x, r = divmod(x, 36); s = '0123456789abcdefghijklmnopqrstuvwxyz'[r] + s
    return s
days = []
for d in te:
    toks = []
    for a, dd, n, raw in F['rows']:            # rows are sorted by (account, date): the page keeps this order for ties
        if dd != d or a in col: continue
        toks.append(','.join([_b36(ai[a]) or '0', _b36(n)] + [_b36(x) for x in raw]))
    days.append(';'.join(toks))
pos = {}
for (a, d), (sc, o) in lab.items():
    if d in te and a not in col: pos[a + '|' + d] = [sc, o]
info = []
for a in accts:
    t = F['solo'].get(a) or F['shadow'].get(a)
    info.append([groups.index(F['group'].get(a, '_global')), 1 if a in set(F['holdout']) else 0, t[0] if t else '', t[1] if t else ''])
# Python's reference numbers for the in-page self-check
ref = {}
for mon in ('z', 'peer'):
    s, p = M.run(F, mon, 'routine')
    ref[mon] = {'R': [M.recall_at(s, p, k)[1] for k in range(1, 21)], 'pos': len(p), 'n': len(s), 'bauc': round(M.budget_auc(s, p), 6), 'auroc': round(M.auroc(s, p), 6)}
    for name, use in (('egress', [5, 14, 15, 17]), ('noTime', [j for j in range(20) if j != 2])):
        s2, p2 = M.run(F, mon, 'routine', use=use)
        ref[mon + '_' + name] = {'R10': M.recall_at(s2, p2, 10)[1], 'use': use}
D = {'_doc': 'Generated by mk_audit_data.py from inputs/features_gpt53_single_day.json (released corpus, forgelab/mole on Hugging Face).',
     'features': F['features'], 'accts': accts, 'info': info, 'groups': groups, 'days': te, 'rows': days,
     'pos': pos, 'gmed': gmed, 'gsc': gsc, 'prof': {g: [prof[g][0], prof[g][1]] for g in groups if g in prof},
     'ntrain': len(rows), 'ref': ref}
js = '// Generated by mk_audit_data.py. Do not edit.\nwindow.AUDIT=' + json.dumps(D, separators=(',', ':')) + ';\n'
open('parts/21_audit_data.js', 'w').write(js)
print('audit data bytes', len(js), 'accounts', len(accts), 'test rows', sum(len(x.split(';')) for x in days), 'positives', sum(1 for v in pos.values() if v[1] == 'executed'))
print('ref', {k: (v.get('R', [None] * 10)[9] if 'R' in v else v['R10']) for k, v in ref.items()})
