"""Write parts/20_example.js from inputs/examples.json (mk_example.py): the two example account-days, trimmed for the
page. The harmful session's events keep the full rendered line (arguments already clipped at 600 characters, as the
monitor sees them); other sessions' events are shortened to time, service.action and resource to save space (the page says so)."""
import json
E = json.load(open('inputs/examples.json'))
out = []
for e in E:
    ev = []
    for l in e['events']:
        line = l['line'] if l['atk'] else ('%s %s.%s %s' % (l['ts'], l['svc'], l['act'], l['res'][:48])).rstrip()
        ev.append([l['ts'], line, 1 if l['atk'] else 0, l['argLen'], l['hits']])
    msgs = []
    for m in e['msgs']:
        if m['k'] == 'assistant': msgs.append({'k': 'a', 't': m['t'], 'c': [[c['name'], c['argLen']] for c in m['calls']]})
        elif m['k'] == 'tool': msgs.append({'k': 't', 'n': m['name'], 't': m['t'], 'len': m['len']})
        else: msgs.append({'k': 'u', 't': m['t']})
    out.append({'account': e['account'], 'date': e['date'], 'threat': e['threat'], 'stealth': e['stealth'], 'n': e['n_events'],
                'na': e['n_attack_events'], 'ns': e['n_sessions'], 'turns': e['turns'], 'sys': e['system'], 'ev': ev, 'msgs': msgs})
payload = json.dumps(out, ensure_ascii=False, separators=(',', ':')).replace('\u2014', '--')   # the knowledge base uses no em-dashes; verbatim text shows them as --
js = '// Generated by mk_example_js.py from inputs/examples.json (released GPT-5.3 single-day corpus). Do not edit.\nwindow.EXAMPLES=' + payload + ';\n'
open('parts/20_example.js', 'w').write(js)
print('example bytes', len(js.encode()))
