"""Write parts/20_repo_data.js (window.REPO): the Django excerpt, the Level 2 targets found by the released
extractor, the page's candidate lexicon, the Level 3 run specs, and Python reference results (schro_ref.py,
copies of the released code) for seeds 1 to 10, which check_page.mjs compares with the page's JavaScript port.
usage: python3 mk_repo_data.py"""
import json, re
from schro_ref import tokenize_identifier, create_token_mapping, reconstruct_identifier, random_topological_order

EX = json.load(open('inputs/excerpt.json'))
TG = json.load(open('inputs/level2_targets.json'))
LX = json.load(open('inputs/lexicon.json'))
# glasses/manager.py sacrosanct_words (commit e2eef98), applied by _filter_mapping together with len(k) >= 2
SAC = sorted(set("""class def if else elif try except finally yield return import from as for in while break continue raise is not and or none true false async await pass global nonlocal assert lambda del super isinstance type str int float list dict set tuple bool object open len print diff index --- +++ @@ git a b __init__ __str__ __repr__ __dict__ __class__ __module__ __name__ __file__ to do of by on at up no so be go me my he we it ok an if id run execute process lift get set add put use new old out off all any may can bar base body box case cast cell char city copy core date each edge end find flag form func hook init item join kind last left link load make meta move node only pack page pick pipe plot post push read real rule save scan send show sign size skip sort stop swap sync tail test tree trim unit view walk wrap""".split()))
IDENT = 'django'
keys = sorted(k for k in TG['targets'] if k != IDENT and len(k) >= 2 and k.lower() not in SAC)
tokens = sorted({t.lower() for k in keys for t in tokenize_identifier(k)})
assert all(t in LX['candidates'] for t in tokens), [t for t in tokens if t not in LX['candidates']]


def forward_map(mapping, identity=True):
    fm = {k: reconstruct_identifier(k, mapping) for k in keys}
    fm = {k: v for k, v in fm.items() if k != v}
    return fm


def apply(text, fm, identity):
    if fm:
        pat = re.compile(r'\b(' + '|'.join(re.escape(k) for k in sorted(fm, key=len, reverse=True)) + r')\b')
        text = pat.sub(lambda m: fm[m.group()], text)
    if identity:
        text = re.sub(r'(?<![\w-])django(?![\w-])', LX['identity']['django'], text, flags=re.I)
    return text


ref = []
for seed in range(1, 11):
    mp = create_token_mapping(LX['candidates'], tokens, seed)
    fm = forward_map(mp)
    r = {'seed': seed, 'mapping': [mp[t] for t in tokens]}
    if seed <= 3:   # full texts for three seeds; the mapping and orders for all ten
        r.update({'issue': apply(EX['issue'], fm, True), 'code0': apply(EX['files'][0]['text'], fm, True), 'code1': apply(EX['files'][1]['text'], fm, True),
                  'tree': [apply(p, fm, True) for p in EX['tree']]})
    ref.append(r)
    r.update({'top': random_topological_order({'length': len(EX['top_run']['names']), 'deps': EX['top_run']['deps']}, seed),
                'meth': random_topological_order({'length': len(EX['field_run']['names']), 'deps': EX['field_run']['deps']}, seed)})
# the renamings the paper shows, applied through the same reconstruction
fig = {t: LX['attested'].get(t, t) for t in tokens}
fmf = forward_map(fig)
figv = {'mapping': fig, 'fm': fmf, 'issue': apply(EX['issue'], fmf, True), 'tree': [apply(p, fmf, True) for p in EX['tree']]}
# words of the issue that are also Django identifiers and get renamed in the prose
prose = sorted({w for w in re.findall(r'[A-Za-z_][A-Za-z0-9_]*', EX['issue']) if w in keys})
out = {'ex': EX, 'keys': keys, 'tokens': tokens, 'sac': SAC, 'lex': LX, 'counts': TG['counts'], 'ref': ref, 'fig': figv,
       'prose_renamed': prose, 'not_targets_sample': ['attname', 'db_column', '_get_FIELD_display', 'get_FOO_display', 'foo_bar']}
open('parts/20_repo_data.js', 'w').write('// Generated by mk_repo_data.py\nwindow.REPO=' + json.dumps(out, separators=(',', ':'), ensure_ascii=False).replace('@@', '\\u0040@').replace('{{', '{\\u007b') + ';\n')
print('keys', len(keys), 'tokens', len(tokens), 'prose renamed', prose)
print('fig issue:', figv['issue'][:300])
print('fig tree:', figv['tree'][:12])
print('seed1 issue:', ref[0]['issue'][:300])
print('seed1 code:', ref[0]['code0'][:900])
print('top order seed1', ref[0]['top'][:12])
