"""Collect the toy's training results into parts/_gen_toy.js (window.BTT): per-method test accuracy of every seed,
logged validation curves, learned mixing ratios, the LR sweep, pretraining checks, the forward-pass check and the
train/test overlap. Plain Python; run after train.py finetune/export, check_forward.py and overlap.py."""
import json, os, re, statistics as st
HERE = os.path.dirname(os.path.abspath(__file__)); MD = os.path.join(HERE, 'model')
R = json.load(open(os.path.join(MD, 'results.json')))
meth = sorted({k.rsplit('_s', 1)[0] for k in R})
res = {}
for m in meth:
    seeds = [R[f'{m}_s{s}'] for s in range(3) if f'{m}_s{s}' in R]
    t = [x['test'] for x in seeds]
    res[m] = dict(test=t, mean=st.mean(t), sd=st.stdev(t) if len(t) > 1 else 0, curves=[x['curve'] for x in seeds],
                  alpha=[x['alpha'] for x in seeds], secs=[x['secs'] for x in seeds], lr=seeds[0].get('lr'),
                  test_quantised=seeds[0].get('test_quantised'))
log = [l.split() for l in open(os.path.join(MD, 'pretrain.log'))]
pre = [[int(l[0]), float(l[2]), float(l[4]), float(l[6])] for l in log]
J = lambda f: json.load(open(os.path.join(MD, f))) if os.path.exists(os.path.join(MD, f)) else None
out = dict(results=res, lr=J('lr.json'), pretrain=pre, check=J('check_forward.json'), overlap=J('overlap.json'))
open(os.path.join(HERE, 'parts', '_gen_toy.js'), 'w').write('// Generated by mk_toydata.py from model/*.json and model/pretrain.log.\nwindow.BTT=' + json.dumps(out, separators=(',', ':')) + ';\n')
for m in meth: print(m, [round(x, 4) for x in res[m]['test']], round(res[m]['mean'], 4), round(res[m]['sd'], 4))
