// Compare labs data. Every value is from the source linked in the Reading tab section named by s; read 2026-10-01.
// [id, label, colour var]
const GROUPS=[
 ['data','Data quality per parameter','--c1'],
 ['mem','Memory per token','--c2'],
 ['trust','Auditability, on-prem','--c3'],
 ['dist','Distribution and billing','--c4'],
 ['scale','Open scale, low price','--c5'],
 ['comp','Bits per weight','--c6'],
 ['open','Openness as the product','--acc'],
 ['route','Not a single model','--bad']];
// w: full | open | openr | api | closed | na ; ev: v vendor only | i independent | m mixed
const LABS=[
 {id:'ms',n:'Microsoft',h:'Phi-4, 14B',d:'2024-12-11',dt:'Dec 2024',g:'data',bet:'small models trained on synthetic, textbook-style data',w:'open',lic:'MIT',tot:14.7,act:14.7,arch:'dense transformer',p:'Azure, Foundry',aa:null,ev:'v',evt:'MMLU 84.8 in Microsoft\'s report',why:'The default dense family for local and edge use; weakest on long-tail knowledge and on inputs unlike a textbook exercise. MAI is the separate in-house frontier line.',s:'s-data'},
 {id:'hf',n:'Hugging Face',h:'SmolLM3, 3B',d:'2025-07-08',dt:'Jul 2025',g:'open',bet:'a fully documented recipe',w:'full',lic:'Apache 2.0, recipe and data mix published',tot:3.08,act:3.08,arch:'dense, NoPE in a fraction of layers',p:'·',aa:null,ev:'v',evt:'Hugging Face\'s own ablations',why:'The reference for how a competent 3B-class model is built, every stage published.',s:'s-open'},
 {id:'obmb',n:'OpenBMB',h:'MiniCPM5-2B',d:'2026-09-06',dt:'Sep 2026',g:'data',bet:'on-device dense model',w:'open',lic:'Apache 2.0',tot:2.52,act:2.52,arch:'dense',p:'·',aa:null,ev:'v',evt:'53.9 average over 34 benchmarks',why:'A current reference point for what the small end of the dense ladder buys.',s:'s-data'},
 {id:'nv',n:'NVIDIA',h:'Nemotron 3 Nano, 30B',d:'2025-12-15',dt:'Dec 2025; 3.5 Lightning Aug 2026',g:'mem',bet:'KV cache per token: Mamba-2 hybrids',w:'openr',lic:'NVIDIA Open Model License; OpenMDW-1.1 for 3.5',tot:31.6,act:3.5,arch:'23 Mamba-2, 23 MoE, 6 attention layers',p:'free weights',aa:null,ev:'v',evt:'benchmarks NVIDIA\'s; cache sizes computed here from config.json',why:'6 KiB of cache per token against 96 KiB for a comparable transformer: memory, not FLOPs, decides agentic serving. Also buying Hugging Face.',s:'s-mem'},
 {id:'ibm',n:'IBM',h:'Granite 4.0-H-Small, 32B',d:'2025-10-02',dt:'Oct 2025',g:'trust',bet:'governance paperwork on a hybrid model',w:'open',lic:'Apache 2.0, indemnified',tot:32.2,act:null,arch:'Mamba-2 hybrid MoE, 4 of 40 layers attention',p:'watsonx',aa:null,ev:'v',evt:'IBM\'s own',why:'Chosen for ISO-certified governance, data provenance and indemnification as much as for the model.',s:'s-trust'},
 {id:'liq',n:'Liquid AI',h:'LFM2 and LFM2.5',d:'2026-01-06',dt:'2025 to 2026',g:'mem',bet:'on-device, non-transformer blocks',w:'openr',lic:'LFM Open License 1.0',tot:8.34,act:1.5,arch:'gated short convolutions + few attention layers',p:'·',aa:null,ev:'v',evt:'Liquid\'s own',why:'The most credible of the post-transformer fringe, built for RAM and battery limits.',s:'s-mem'},
 {id:'cohere',n:'Cohere',h:'North Small Translate, 218B',d:'2026-09-10',dt:'Sep 2026',g:'trust',bet:'deploy inside the customer: citations, two-GPU sizing',w:'openr',lic:'CC-BY-NC 4.0 to self-host; Command A+ Apache 2.0',tot:218,act:25,arch:'MoE, 128 experts, 8 per token, 4,096-token sliding window',p:'free on Cohere API to rate limits',aa:null,ev:'v',evt:'WMT26 83.6, Cohere\'s evaluation, GPT-5.6-Sol as judge',why:'Single-task specialists at MoE scale still pay. Command A+ (May 2026) moved the flagship from dense 111B to 218B MoE.',s:'s-trust'},
 {id:'amz',n:'Amazon',h:'Nova 2',d:'2024-12',dt:'Nova Dec 2024; Nova 2 current',g:'dist',bet:'one API, one bill: Bedrock; Trainium chips',w:'closed',lic:'Bedrock only',tot:null,act:null,arch:'undisclosed',p:'priced to undercut',aa:null,ev:'v',evt:'Amazon\'s own',why:'Nova is competent mid-tier; the position is Bedrock as the aggregator and Trainium behind Project Rainier.',s:'s-dist'},
 {id:'tx',n:'Tencent',h:'Hy4 preview, 770B',d:'2026-08-27',dt:'Aug 2026',g:'scale',bet:'frontier band by size, not sparsity',w:'open',lic:'Apache 2.0',tot:770,act:49,arch:'MoE, above 1M context, two reasoning levels',p:'·',aa:null,ev:'v',evt:'163-expert internal blind evaluation',why:'16× sparse, so expensive to serve for its tier; and it helped optimise its own training (31.8% throughput, self-reported).',s:'s-scale'},
 {id:'xm',n:'Xiaomi',h:'MiMo-V2.6-Pro, 1.02T',d:'2026-09-22',dt:'Sep 2026',g:'scale',bet:'open weights, the lowest cost per index task',w:'open',lic:'MIT',tot:1020,act:42,arch:'MoE, 1M context, router frozen in RL',p:'$0.435 / $0.87',aa:46.3,ev:'m',evt:'AA v4.3 measured; benchmarks Xiaomi\'s',why:'The highest open-weight score on AA v4.3, at $0.13 per index task, and a published $2.62M price for its final RL stage.',s:'s-scale'},
 {id:'sf',n:'StepFun',h:'Step 5 Preview, 600B',d:'2026-09-20',dt:'Sep 2026',g:'scale',bet:'27B active at 600B total',w:'api',lic:'weights promised for 15 Oct 2026, no licence named',tot:600,act:27,arch:'MoE, 92 layers, sparse grouped-query attention',p:'$1.00 / $2.70',aa:43.7,ev:'m',evt:'AA v4.3 measured; benchmarks StepFun\'s',why:'Decodes at a mid-size dense model\'s cost; 18% of Kimi K3\'s output price.',s:'s-scale'},
 {id:'nai',n:'NaiveAI',h:'Naive-N0.5-Flash, 309B',d:'2026-09-27',dt:'Sep 2026',g:'scale',bet:'no full-attention layer at all',w:'open',lic:'MIT',tot:309,act:15.5,arch:'39 sliding-window + 9 DSA layers, on MiMo-V2.5',p:'·',aa:null,ev:'v',evt:'NaiveAI\'s own',why:'A startup building on another lab\'s open base; two 309B-class open models in one week.',s:'s-scale'},
 {id:'shl',n:'Shanghai AI Laboratory',h:'Atria Dawn Preview, 744B',d:'2026-09-11',dt:'Sep 2026',g:'scale',bet:'post-training over someone else\'s open base',w:'open',lic:'MIT (repository)',tot:744,act:null,arch:'MoE, on GLM-5.2',p:'·',aa:null,ev:'v',evt:'the lab\'s own',why:'A release shape worth recognising: an agentic layer on an existing open base, not a model from scratch.',s:'s-scale'},
 {id:'prism',n:'Prism ML',h:'Bonsai 2 27B',d:'2026-09-17',dt:'Sep 2026',g:'comp',bet:'ternary weights, 1.76 bits each',w:'open',lic:'Apache 2.0',tot:27,act:27,arch:'ternary rebuild of Qwen3.8 27B',p:'·',aa:null,ev:'v',evt:'98.2% retention, Prism\'s own',why:'5.94 GB instead of 54 GB: how far compression goes before quality breaks.',s:'s-comp'},
 {id:'ifm',n:'Institute of Foundation Models',h:'K2 Horizon, 375B',d:'2026-09-03',dt:'Sep 2026',g:'open',bet:'fully open: weights, data, code',w:'full',lic:'Apache 2.0, data and code released',tot:375,act:23,arch:'MoE, 512K context; MoVA 36B; diffusion adapters',p:'Compass, Cerebras, Nebius',aa:30.5,ev:'m',evt:'AA v4.3 measured; SOTA claims IFM\'s',why:'The second fully open lab after Ai2, on another continent with another funder.',s:'s-open'},
 {id:'pi',n:'Prime Intellect',h:'INTELLECT-1, 10B',d:'2024-11-28',dt:'Nov 2024',g:'open',bet:'training across the internet',w:'full',lic:'Apache 2.0, data and checkpoints released',tot:10.2,act:10.2,arch:'dense, trained with DiLoCo',p:'·',aa:null,ev:'v',evt:'Prime Intellect\'s report',why:'Not competitive on quality; the point is that training need not sit in one datacentre.',s:'s-open'},
 {id:'arcee',n:'Arcee AI',h:'Trinity Large, 398B',d:'2026-01-27',dt:'Jan 2026',g:'open',bet:'a small US team at open frontier scale',w:'openr',lic:'OpenMDW-1.1',tot:398,act:13,arch:'MoE, 4 of 256 experts',p:'·',aa:null,ev:'v',evt:'Arcee\'s own',why:'Evidence about whether a small team can still reach this scale.',s:'s-open'},
 {id:'tii',n:'TII',h:'Falcon-H1, up to 34B',d:'2025-05-01',dt:'May 2025',g:'mem',bet:'hybrid SSM, after early open weights',w:'openr',lic:'Falcon LLM licence',tot:33.6,act:33.6,arch:'hybrid SSM and attention',p:'·',aa:null,ev:'v',evt:'TII\'s own',why:'One of the earliest credible open-weights providers (Falcon 40B, 180B, RefinedWeb), now in the hybrid camp.',s:'s-mem'},
 {id:'ai21',n:'AI21',h:'Jamba 1.5 Large, 399B',d:'2024-08-19',dt:'Aug 2024',g:'mem',bet:'Mamba, attention and MoE in one',w:'openr',lic:'custom licence',tot:398.6,act:null,arch:'Mamba + attention + MoE',p:'·',aa:null,ev:'v',evt:'AI21\'s own',why:'One of the first to ship very long context at a footprint a single node could hold.',s:'s-mem'},
 {id:'up',n:'Upstage',h:'SOLAR 10.7B',d:'2023-12-12',dt:'Dec 2023',g:'open',bet:'depth up-scaling',w:'open',lic:'Apache 2.0 (base)',tot:10.7,act:10.7,arch:'48 layers from two copies of a 32-layer base',p:'·',aa:null,ev:'v',evt:'Upstage\'s paper',why:'Built a larger model from an existing one instead of from scratch.',s:'s-open'},
 {id:'sak',n:'Sakana AI',h:'Fugu Max, Fugu Ultra v2',d:'2026-09-11',dt:'Sep 2026',g:'route',bet:'a learned orchestrator over a model pool',w:'na',lic:'closed; not in the EU or EEA',tot:null,act:null,arch:'routes across other models',p:'Max $2 / $6; Ultra v2 $5 / $30',aa:null,ev:'v',evt:'all Sakana\'s figures',why:'If a routed ensemble holds the Pareto frontier, the question becomes which orchestrator, not which model.',s:'s-route'},
 {id:'ts',n:'TypeSafe AI',h:'Jev',d:'2026-09-15',dt:'Sep 2026, early access',g:'route',bet:'typed decisions with calibrated confidence',w:'na',lic:'closed',tot:null,act:null,arch:'non-autoregressive, parallel sampling',p:'$0.042 / free',aa:null,ev:'v',evt:'vendor only; novelty contested',why:'If many production calls are structured decisions wearing a text interface, this is a different product shape.',s:'s-route'}
];
