"""Export the small real-data sample the page ships (parts/21_js_qdata.js) from Qwen2.5-0.5B layer 8 q_proj.
  uv run --with torch --with transformers --with numpy python export_data.py
  * 4 whole rows of the weight matrix (896 bf16 values each, exact bit patterns): rows 222 and 223 hold the layer's
    largest weights (input column 5), rows 0 and 448 are ordinary;
  * the whole tensor's absmax (sets a per-tensor scale);
  * a slice for the outlier-migration animation: 16 evaluation tokens x 64 input channels (the 8 channels with the largest
    calibration activations plus 56 drawn at random, seed 0) and 8 output rows drawn at random (seed 0), the activations
    as float32, the weights as bf16; with the calibration statistics SmoothQuant and AWQ need for those 64 channels
    (max |x|, mean |x| over 511 calibration tokens) and max |W| per input channel over the whole layer;
  * the whole-layer results of quant_lab.py (inputs/lab_L8_self_attn_q_proj.json)."""
import json, os, base64, torch, numpy as np
from transformers import AutoModelForCausalLM, AutoTokenizer
HERE = os.path.dirname(os.path.abspath(__file__))
M = 'Qwen/Qwen2.5-0.5B'; L = 'model.layers.8.self_attn.q_proj'
tok = AutoTokenizer.from_pretrained(M); model = AutoModelForCausalLM.from_pretrained(M, dtype=torch.float32).eval()
mod = dict(model.named_modules())[L]
def acts(fn):
    t = open(os.path.join(HERE, 'inputs', fn)).read().split('\n', 1)[1]; ids = tok(t, return_tensors='pt').input_ids[:, :512]; b = {}
    h = mod.register_forward_hook(lambda m, i, o: b.__setitem__('x', i[0][0].numpy()))
    with torch.no_grad(): model(ids)
    h.remove(); return b['x'][1:], [tok.convert_tokens_to_string([t]) for t in tok.convert_ids_to_tokens(ids[0])[1:]]
Xc, _ = acts('calib_pride_and_prejudice.txt'); Xe, te = acts('eval_tale_of_two_cities.txt')
Wb = mod.weight.detach().to(torch.bfloat16)
W = Wb.float().numpy()
bits = Wb.view(torch.int16).numpy().astype('<i2')
b64 = lambda a: base64.b64encode(a.tobytes()).decode()
ROWS = [222, 223, 0, 448]
rng = np.random.default_rng(0)
top = np.argsort(-np.abs(Xc).max(0))[:8]
rest = np.setdiff1d(np.arange(896), top)
ch = np.sort(np.concatenate([top, rng.choice(rest, 56, replace=False)])); rw = np.sort(rng.choice(896, 8, replace=False))
lab = json.load(open(os.path.join(HERE, 'inputs', 'lab_L8_self_attn_q_proj.json')))
D = dict(model=M, layer=L, K=896, N=896, w_absmax=float(np.abs(W).max()), rows=ROWS,
         rows_bf16=b64(bits[ROWS]),
         slice=dict(tokens=te[:16], chans=ch.tolist(), top=sorted(top.tolist()), rows=rw.tolist(),
                    x_f32=b64(Xe[:16][:, ch].astype('<f4')), w_bf16=b64(bits[rw][:, ch]),
                    xc_max=np.abs(Xc[:, ch]).max(0).round(5).tolist(), xc_mean=np.abs(Xc[:, ch]).mean(0).round(6).tolist(),
                    w_colmax=np.abs(W[:, ch]).max(0).tolist()),
         lab=lab)
js = '// generated by src/export_data.py from ' + M + ' (' + L + '); do not edit\nwindow.QD=' + json.dumps(D, separators=(',', ':')) + ';\n'
open(os.path.join(HERE, 'parts', '21_js_qdata.js'), 'w').write(js)
print(len(js), 'bytes; slice chans', ch.tolist(), 'rows', rw.tolist())
