"""The Notation decoder's reference panel: conventions that trip people up.
Each: key (filter words), title (HTML), ex (LaTeX, display), text (HTML with inline LaTeX), seen (equation ids).
Worked numbers here are checked in recompute.py (norms of (3, 4), die expectation, argmax of (2, 1, 0), nats to bits).
"""

CONV_INTRO = ("Habits that papers rarely state. Each comes with a tiny example; \"Seen in\" opens the equation above where it appears. "
              "When a paper defines its notation (often in a short section or a footnote), its definition wins over any of these.")

CONV = [
    {"key": "vector column row transpose", "title": "Vectors are columns",
     "ex": r"\mathbf{x}\in\mathbb{R}^{3}=\begin{bmatrix}1\\2\\3\end{bmatrix},\quad \mathbf{x}^{\top}=\begin{bmatrix}1&2&3\end{bmatrix},\quad \mathbf{w}^{\top}\mathbf{x}=\textstyle\sum_i w_i x_i",
     "text": r"A bold lower-case letter is a column vector unless the paper says otherwise, so \(\mathbf{w}^\top\mathbf{x}\) is a single number (a dot product) and \(\mathbf{x}\mathbf{w}^\top\) is a matrix (an outer product).",
     "seen": ["lora", "nce"]},
    {"key": "matrix rows examples batch data shape", "title": "Data matrices: one row per example",
     "ex": r"X\in\mathbb{R}^{n\times d}\quad n\ \text{rows (examples or tokens)}\quad d\ \text{columns (features)},\qquad XW\in\mathbb{R}^{n\times d'}",
     "text": r"Stacked data puts examples in rows, so a layer is applied as \(XW\) with \(W\) of shape \(d\times d'\). The same layer on one column vector is \(W^\top\mathbf{x}\) or, with \(W\) stored the other way, \(W\mathbf{x}\). Check which a paper uses before multiplying.",
     "seen": ["attn", "mha"]},
    {"key": "shape dimension product inner rows columns", "title": "Shapes multiply by the inner sizes",
     "ex": r"(a\times b)(b\times c)=(a\times c),\qquad A\in\mathbb{R}^{a\times b}",
     "text": r"\(\mathbb{R}^{a\times b}\) means \(a\) rows and \(b\) columns of real numbers. A product needs the inner sizes to match and keeps the outer ones. Writing the shape under every symbol catches most misreadings.",
     "seen": ["mha", "lora"]},
    {"key": "transpose hermitian conjugate dagger prime", "title": "Transpose and Hermitian marks",
     "ex": r"A^{T}=A^{\top}=A'\qquad A^{H}=A^{*}=A^{\dagger}=\overline{A}^{\top}",
     "text": r"\(T\), \(\top\) and a prime all mean transpose. \(H\), \(*\) and \(\dagger\) mean conjugate transpose, which matters only for complex numbers (Fourier features, the complex form of RoPE); for real matrices it equals the transpose. Careful: \(*\) can also mean \"optimal\" (\(\theta^*\)) or convolution.",
     "seen": ["attn"]},
    {"key": "layout numerator denominator gradient jacobian derivative transpose autograd", "title": "Numerator versus denominator layout",
     "ex": r"L=\mathbf{u}^{\top}W\mathbf{x},\ \ \mathbf{u}=\begin{bmatrix}1\\2\end{bmatrix},\ \mathbf{x}=\begin{bmatrix}3\\4\\5\end{bmatrix},\ W\in\mathbb{R}^{2\times3}:\quad \underbrace{\frac{\partial L}{\partial W}=\mathbf{u}\mathbf{x}^{\top}=\begin{bmatrix}3&4&5\\6&8&10\end{bmatrix}}_{\text{denominator layout: }2\times3,\ \text{what autograd returns}}\qquad \underbrace{\mathbf{x}\mathbf{u}^{\top}=\begin{bmatrix}3&6\\4&8\\5&10\end{bmatrix}}_{\text{numerator layout: }3\times2}",
     "text": r"Each entry is the same partial derivative, \(\partial L/\partial W_{ij}=u_i x_j\) (nudge \(W_{12}\) by 0.01 and \(L\) moves by \(1\cdot4\cdot0.01\)); the layouts only disagree on how to arrange them. Denominator layout gives the derivative the shape of the thing you differentiate by (\(2\times3\), like \(W\)); numerator layout gives the transposed, Jacobian-style shape (\(3\times2\); for a vector \(\mathbf{x}\in\mathbb{R}^n\), a \(1\times n\) row). Autograd always returns a gradient with the parameter's own shape, so a paper written in numerator layout hands you the transpose of <code>W.grad</code>. Authors mix the two (<a href=\"https://en.wikipedia.org/wiki/Matrix_calculus#Layout_conventions\" target=\"_blank\" rel=\"noopener noreferrer\">Wikipedia, Matrix calculus</a>). Rule: if a derived gradient's shape does not match the parameter, transpose and check one entry.",
     "seen": ["adam", "lora"]},
    {"key": "gradient nabla partial", "title": "\\(\\nabla\\) and \\(\\partial\\)",
     "ex": r"\nabla_{\theta}L=\left(\frac{\partial L}{\partial\theta_1},\ldots,\frac{\partial L}{\partial\theta_n}\right),\qquad \nabla_\theta (\theta_1^2+3\theta_2)=(2\theta_1,\ 3)",
     "text": r"\(\partial L/\partial\theta_i\) is one partial derivative; \(\nabla_\theta L\) collects all of them, one per parameter. The subscript says which variables move; everything else is held fixed.",
     "seen": ["adam"]},
    {"key": "argmax max min argmin", "title": "\\(\\arg\\max\\) versus \\(\\max\\)",
     "ex": r"z=(2,1,0):\quad \max_{j} z_j=2,\qquad \arg\max_{j} z_j=1\ \ (\text{the first entry})",
     "text": r"\(\max\) returns the best value; \(\arg\max\) returns where it is (which token, which parameters). Greedy decoding is an \(\arg\max\); \(\max_{\pi}\) in an RL objective means \"choose the policy that makes this largest\".",
     "seen": ["ppo"]},
    {"key": "expectation E average subscript sample", "title": "\\(\\mathbb{E}_{x\\sim p}\\): the subscript says what is random",
     "ex": r"\mathbb{E}_{x\sim p}[f(x)]=\sum_x p(x)f(x),\qquad \text{fair die: }\mathbb{E}[x]=\tfrac{1+2+\cdots+6}{6}=3.5",
     "text": r"Read \(\mathbb{E}_{x\sim p}[\cdot]\) as \"the average of the bracket when x is drawn from p\". Several variables under the E (\(\mathbb{E}_{t,\mathbf{x}_0,\boldsymbol\epsilon}\)) are all random. A hat, \(\hat{\mathbb{E}}\), or \(\frac1N\sum\), means a sample average you actually compute. When the distribution depends on the parameters (RLHF), you cannot just differentiate inside.",
     "seen": ["nce", "ddpm", "rlhf", "dpo", "ppo"]},
    {"key": "sim distributed sampled tilde", "title": "\\(\\sim\\) means \"drawn from\"",
     "ex": r"\boldsymbol{\epsilon}\sim\mathcal{N}(\mathbf{0},\mathbf{I}),\qquad (x,y_w,y_l)\sim\mathcal{D}",
     "text": r"Between two things, a tilde means \"is distributed as\" or \"is sampled from\". On top of a letter (\(\widetilde{r}\)) it means a modified version. In \(a \sim b\) between numbers, some authors mean \"roughly\".",
     "seen": ["ddpm", "dpo"]},
    {"key": "log ln natural bits nats base", "title": "\\(\\log\\) is the natural log",
     "ex": r"\log x=\ln x\ \ (\text{nats}),\qquad \text{bits}=\frac{\text{nats}}{\ln 2},\qquad 1\ \text{nat}=1.443\ \text{bits}",
     "text": r"ML papers mean base \(e\) unless they say bits or write \(\log_2\). Information theory books often default to base 2. A loss of 0.788 nats per token is 1.137 bits per token.",
     "seen": ["lm", "dpo", "nce"]},
    {"key": "indicator iverson 1 bracket", "title": "The indicator \\(\\mathbb{1}[\\cdot]\\)",
     "ex": r"\mathbb{1}[y=k]=\begin{cases}1&\text{if } y=k\\0&\text{otherwise}\end{cases},\qquad -\sum_k\mathbb{1}[y=k]\log p_k=-\log p_y",
     "text": r"Also written \(\mathbf{1}\{\cdot\}\), \(I(\cdot)\) or \([\cdot]\) (the Iverson bracket). It turns a condition into 0 or 1, which is how one-hot labels pick out a single term of a sum.",
     "seen": ["lm"]},
    {"key": "norm l2 l1 frobenius absolute", "title": "Norms \\(\\|\\cdot\\|\\)",
     "ex": r"\mathbf{x}=(3,4):\ \|\mathbf{x}\|_2=5,\quad \|\mathbf{x}\|_1=7,\quad \|\mathbf{x}\|_\infty=4,\quad \|\mathbf{x}\|_2^2=25",
     "text": r"No subscript usually means the Euclidean (L2) norm; \(\|A\|_F\) is the Frobenius norm, the L2 norm of all a matrix's entries. A squared norm is a sum of squares, so \(\|\boldsymbol\epsilon-\boldsymbol\epsilon_\theta\|^2\) is a squared error. Single bars \(|o|\) mean absolute value, or the size of a set or sequence.",
     "seen": ["ddpm"]},
    {"key": "define := triangleq equiv equal approx", "title": "\\(:=\\), \\(\\triangleq\\) versus \\(=\\)",
     "ex": r"L_{\text{simple}}:=\ldots\qquad \hat{L}\triangleq\ldots\qquad a\equiv b\qquad a\approx b",
     "text": r"\(:=\), \(\triangleq\) and often \(\equiv\) introduce a definition: nothing to check, just a new name. \(=\) claims two things are equal (worth checking). \(\approx\) is an approximation; \(\equiv\) can also mean \"identically equal\" or congruence.",
     "seen": ["ddpm", "chin"]},
    {"key": "proportional propto constant", "title": "\\(\\propto\\) (proportional to)",
     "ex": r"p(\theta\mid D)\propto p(D\mid\theta)\,p(\theta),\qquad \mathrm{softmax}(z)_j\propto e^{z_j}",
     "text": r"Equal up to a factor that does not depend on the variable of interest. The missing factor is usually a normaliser you can compute later (dividing by the sum over j).",
     "seen": ["nce"]},
    {"key": "hat bar tilde star accent estimate", "title": "Hats, bars, tildes, stars",
     "ex": r"\hat{A}_t,\ \hat{\mathbb{E}}_t,\ \hat{L}\quad \bar{x},\ \bar{\alpha}_t\quad \widetilde{r}_i\quad \theta^{*},\ \pi^{*}",
     "text": r"Hat: estimated or predicted (and in Adam, bias-corrected). Bar: a mean, but in DDPM a cumulative product, and in complex maths a conjugate. Tilde: a transformed or approximate version. Star: optimal. Each paper defines its own; these are only the usual readings.",
     "seen": ["adam", "ppo", "chin", "ddpm", "grpo"]},
    {"key": "sg stop gradient detach", "title": "\\(\\mathrm{sg}[\\cdot]\\): stop-gradient",
     "ex": r"L=\log p(x\mid z_q(x))+\|\mathrm{sg}[z_e(x)]-e\|_2^2+\beta\|z_e(x)-\mathrm{sg}[e]\|_2^2",
     "text": r"VQ-VAE (<a href=\"https://arxiv.org/pdf/1711.00937v2#page=4\" target=\"_blank\" rel=\"noopener noreferrer\">van den Oord et al. 2017, Eq. 3, p. 4</a>): \"identity at forward computation time and has zero partial derivatives\". In code, <code>.detach()</code>. PPO's \(\pi_{\theta_{\text{old}}}\) plays the same role: a fixed number the gradient does not flow into.",
     "seen": ["ppo"]},
    {"key": "semicolon bar conditional parameters given", "title": "\\(p(y\\mid x;\\theta)\\): bar versus semicolon",
     "ex": r"p(y\mid x;\theta)=p_\theta(y\mid x)",
     "text": r"The bar conditions on data (\"given x\"); the semicolon, or a subscript, names the parameters that define the distribution. Parameters are settings, not random events, in this notation.",
     "seen": ["lm", "dpo"]},
    {"key": "odot hadamard elementwise otimes kronecker outer circ", "title": "\\(\\odot\\), \\(\\otimes\\), \\(\\circ\\)",
     "ex": r"(1,2)\odot(3,4)=(3,8),\qquad (1,2)^\top\otimes(3,4)=\begin{bmatrix}3&4\\6&8\end{bmatrix}",
     "text": r"\(\odot\) multiplies entry by entry (the Hadamard product; some write \(\circ\)). \(\otimes\) is the Kronecker or outer product. \(\circ\) between functions is composition, \((f\circ g)(x)=f(g(x))\).",
     "seen": ["ln"]},
    {"key": "sum product index range sigma pi", "title": "Sum and product indices",
     "ex": r"\sum_{i=1}^{H}a_i,\qquad \sum_{x_j\in X}f(x_j),\qquad \prod_{s=1}^{t}\alpha_s",
     "text": r"The subscript says what the index runs over: a range, or every member of a set. A bare \(\sum_i\) means over all valid i. \(\prod\) is the same for products. Capital \(\Pi\) is a product; lower-case \(\pi\) is a policy or 3.14159.",
     "seen": ["lm", "nce", "ln", "ddpm"]},
    {"key": "subscript superscript index time layer label power", "title": "Subscripts and superscripts",
     "ex": r"\theta_t\ (\text{step}),\quad h^{(l)}\ (\text{layer}),\quad W^{Q}\ (\text{label}),\quad \beta_1^{t}\ (\text{power}),\quad o_{i,<t}",
     "text": r"A superscript is a power only when nothing else makes sense: it is also a layer (often in brackets), a label, or a time step. A subscript is usually an index or a step; \(<t\) means every position before t.",
     "seen": ["adam", "mha", "kl3"]},
    {"key": "sigma sigmoid std probability P p", "title": "Letters with two jobs",
     "ex": r"\sigma(z)=\frac{1}{1+e^{-z}}\quad \text{vs}\quad \sigma=\sqrt{\mathrm{Var}},\qquad P\ \text{(probability) vs}\ p\ \text{(density)}",
     "text": r"\(\sigma\) is a sigmoid when applied to an argument, a standard deviation when it stands alone. \(\beta\), \(\alpha\), \(\epsilon\), \(\theta\) and \(h\) all change meaning between the papers on this tab.",
     "seen": ["dpo", "ln", "adam"]},
    {"key": "big O complexity order", "title": "Big-O",
     "ex": r"QK^{T}\ \text{costs}\ O(n^{2}d_k)",
     "text": r"How cost grows with size, ignoring constant factors. Doubling the sequence length n quadruples the cost of the score matrix.",
     "seen": ["attn"]},
]
