"""Writes parts/30_js_data.js from data/wine.json, real/real_streams.json and recompute_output.json (run after them)."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
w = json.load(open(os.path.join(HERE, 'data', 'wine.json')))
r = json.load(open(os.path.join(HERE, 'real', 'real_streams.json')))
q = json.load(open(os.path.join(HERE, 'recompute_output.json')))
real = []
for mid, v in r.items():
    if mid.startswith('_'):
        continue
    real.append(dict(id=mid, place=v['place'], L=v['n_layers'], d=v['d_model'], qk=v['qk_norm'],
                     emb=round(v['emb']['rms_med'], 4),
                     rms=[round(x['rms_med'], 4) for x in v['layers']],
                     amax=[round(x['absmax'], 2) for x in v['layers']],
                     tok0=[round(x['tok0'], 3) for x in v['layers']],
                     sum=[round(x['sum_med'], 4) for x in v['layers']] if 'sum_med' in v['layers'][0] else None,
                     logit=[round(x.get('logit_max', 0), 2) for x in v['layers']]))
D = dict(wine=dict(pts=w['pts'], knn2=w['knn2']),
         real=real, realText=r['_meta']['text'], realVer=dict(transformers=r['_meta']['transformers'], torch=r['_meta']['torch']),
         qwenqk=[dict(l=c['layer'], c=round(c['ceiling'], 1), m=round(c['measured'], 2), gq=round(c['gq_max'], 2), gk=round(c['gk_max'], 2)) for c in q['qwen3_qk']['layers']])
s = '// Generated by src/gen_data.py from data/wine.json, real/real_streams.json, recompute_output.json. Do not edit.\nwindow.NID=' + json.dumps(D, separators=(',', ':')) + ';\n'
open(os.path.join(HERE, 'parts', '30_js_data.js'), 'w').write(s)
print('30_js_data.js', len(s), 'bytes;', len(real), 'models')
