// ---- Reading section 2: the running job's real address space, before and after the DataLoader forks ----
(function(){
  const M=window.RD_DATA&&RD_DATA.maps;const host=document.getElementById('rd-as-svg');if(!host||!M)return;
  const cap=document.getElementById('rd-as-cap'),cnt=document.getElementById('rd-as-cnt');
  const B=M.before_fork_main,AM=M.after_fork_main,W0=M.after_fork_worker0,W1=M.after_fork_worker1;
  const NAME={exe:'python3.11 executable',heap:'[heap] (malloc\'s main arena)',anon:'anonymous memory (arenas, thread stacks, tensors, reservations)',anon_res:'guard pages (no access)',
    dataset:'the dataset, train.bin (mmapped, shared)',torch:'PyTorch libraries (libtorch_cpu.so and others)',numpy:'NumPy and BLAS libraries',clib:'C and C++ runtime (libc, libstdc++, libm, ld.so)',
    pyext:'other Python extension modules (.so)',file:'other files (locale data)',vdso:'[vdso] and [vvar] (kernel-provided)',stack:'[stack] (main thread)',shm:'/dev/shm files (batches, semaphores)'};
  const COL={exe:'var(--c1)',heap:'var(--c2)',anon:'var(--c5)',anon_res:'var(--dim)',dataset:'var(--c3)',torch:'var(--c4)',numpy:'var(--c6)',clib:'var(--c1)',pyext:'var(--c6)',file:'var(--dim)',vdso:'var(--c3)',stack:'var(--c2)',shm:'var(--bad)'};
  const mb=k=>k/1024, fm=k=>k>=1048576?(k/1048576).toFixed(2)+' GiB':k>=1024?(k/1024).toFixed(k>=10240?0:1)+' MiB':k+' KiB';
  // RSS split from smaps_rollup
  const PARTS=[['Private_Dirty','private, written','var(--c2)'],['Private_Clean','private, clean (file pages)','var(--c1)'],['Shared_Dirty','shared, written (copy-on-write)','var(--c5)'],['Shared_Clean','shared, clean','var(--c3)']];
  const st=M.procs;
  function rssBar(r,max,hl){return '<div class="sb" style="height:20px">'+PARTS.map(p=>{const v=r[p[0]]||0;const w=100*v/max;return w<.2?'':'<span title="'+p[1]+': '+fm(v)+'" style="width:'+w+'%;background:'+p[2]+(hl&&hl!==p[0]?';opacity:.35':'')+'">'+(w>9?fm(v):'')+'</span>'}).join('')+'</div>'}
  function proc(title,r,max,hl,sub){return '<div style="margin:6px 0"><div class="small"><b>'+title+'</b> <span class="mute">RSS '+fm(r.Rss)+', PSS '+fm(r.Pss)+(sub?', '+sub:'')+'</span></div>'+rssBar(r,max,hl)+'</div>'}
  function cats(S,ref){const keys=Object.keys(S.totals).sort((a,b)=>S.totals[b][1]-S.totals[a][1]);const lg=k=>Math.log2(1+k);const mx=lg(Math.max(...keys.map(k=>S.totals[k][1])));
    return '<div class="bars">'+keys.map(k=>{const t=S.totals[k],d=ref&&ref.totals[k]?t[0]-ref.totals[k][0]:null;return '<div class="row"><div class="nm" title="'+NAME[k]+'">'+NAME[k]+'</div><div class="track"><div class="fill" style="width:'+(100*lg(t[1])/mx)+'%;background:'+COL[k]+'"></div></div><div class="val">'+fm(t[1])+'</div></div>'}).join('')+'</div><p class="small mute">Virtual size per kind of mapping, log scale; '+S.n+' mappings in all. Virtual size is address space reserved, not memory used: compare the RSS bar.</p>'}
  const leg='<div class="leg">'+PARTS.map(p=>'<span style="--sw:'+p[2]+'">'+p[1]+'</span>').join('')+'</div>';
  const sumR=AM.rollup.Rss+W0.rollup.Rss+W1.rollup.Rss,sumP=AM.rollup.Pss+W0.rollup.Pss+W1.rollup.Pss;
  const shmLines=AM.sample.filter(l=>l.indexOf('/dev/shm/')>=0);
  const STEPS=[
    {t:'One process: the job just before the DataLoader starts',p:'The main process has '+B.n+' mappings covering '+fm(Object.values(B.totals).reduce((a,t)=>a+t[1],0))+' of virtual addresses, but only '+fm(B.rollup.Rss)+' is resident (RSS, actually in physical memory). Almost all of it is private: '+fm(B.rollup.Private_Dirty)+' written by this process (heap, tensors, Python objects), '+fm(B.rollup.Private_Clean)+' clean file pages (library code, dataset rows read so far).',
     h:()=>proc('main (pid '+st.before_fork[0].pid+')',B.rollup,AM.rollup.Rss)+leg+cats(B)},
    {t:'fork(): two workers appear with the same address space',p:'iter(DataLoader) forks two workers. Each starts as a copy of the parent\'s map: '+M.same_in_worker0+' of worker 0\'s '+W0.n+' mappings sit at exactly the same addresses as in the parent. Same virtual addresses, and at first the same physical pages too.',
     h:()=>proc('main',AM.rollup,AM.rollup.Rss)+proc('worker 0 (pid '+st.after_fork[1].pid+', parent '+st.after_fork[1].status.PPid+')',W0.rollup,AM.rollup.Rss)+proc('worker 1 (pid '+st.after_fork[2].pid+')',W1.rollup,AM.rollup.Rss)+leg+cats(W0)},
    {t:'Shared, not copied',p:'In the parent, '+fm(B.rollup.Private_Dirty)+' of private written memory became '+fm(AM.rollup.Shared_Dirty)+' of shared written memory: the same physical pages are now mapped by three processes, each marked read-only so the first write to a page triggers a copy.',
     h:()=>proc('main, before fork',B.rollup,AM.rollup.Rss,'Private_Dirty')+proc('main, after fork',AM.rollup,AM.rollup.Rss,'Shared_Dirty')+proc('worker 0',W0.rollup,AM.rollup.Rss,'Shared_Dirty')+leg},
    {t:'Copy-on-write: what the workers wrote',p:'After four training steps each worker owns '+fm(W0.rollup.Private_Dirty)+' and '+fm(W1.rollup.Private_Dirty)+' of private pages: pages it wrote (its own stack, the batches it built, and every Python object whose reference count changed, since a refcount update is a write). This is what grows over a long epoch when the Dataset holds millions of Python objects.',
     h:()=>proc('worker 0',W0.rollup,AM.rollup.Rss,'Private_Dirty')+proc('worker 1',W1.rollup,AM.rollup.Rss,'Private_Dirty')+leg},
    {t:'What top shows against what is used',p:'Adding the RSS of the three processes gives '+fm(sumR)+'; adding their PSS (proportional set size: each shared page divided among the processes that map it) gives '+fm(sumP)+'. RSS counts every shared page once per process; PSS adds up to the real total. Use PSS (smem, or /proc/&lt;pid&gt;/smaps_rollup) when you add up a DataLoader\'s memory.',
     h:()=>'<div class="out">'+RD.stat('Sum of RSS',fm(sumR),'what adding up top\'s RES column gives')+RD.stat('Sum of PSS',fm(sumP),'shared pages divided among sharers')+RD.stat('Overcount',(sumR/sumP).toFixed(1)+'x','RSS sum / PSS sum')+'</div>'+proc('main',AM.rollup,AM.rollup.Rss)+proc('worker 0',W0.rollup,AM.rollup.Rss)+proc('worker 1',W1.rollup,AM.rollup.Rss)+leg},
    {t:'How batches come back: shared memory in /dev/shm',p:'New in the parent after the fork: files in /dev/shm named torch_&lt;worker pid&gt;_..., already deleted and still mapped, and sem.* files (the locks of multiprocessing\'s queues). A worker builds each batch tensor in shared memory and sends the main process only a small handle (with PyTorch\'s default file_descriptor sharing strategy on Linux, the open file descriptor itself, passed over a Unix socket); the main process maps the same pages, so the batch data is not copied again. A small /dev/shm (Docker\'s default is 64 MB) is why DataLoaders crash with "bus error".',
     h:()=>'<pre class="cd out">'+shmLines.map(RD.esc).join('\n')+'</pre>'}];
  function draw(i){const s=STEPS[i];host.innerHTML=s.h();cap.innerHTML='<div class="t">Step '+(i+1)+' of '+STEPS.length+': '+s.t+'</div><p>'+s.p+'</p>';
    cnt.innerHTML=RD.stat('Processes',i===0?'1':'3',i===0?'main only':'main and 2 workers')+RD.stat('Threads in main',st[i===0?'before_fork':'after_fork'][0].status.Threads,'from /proc/&lt;pid&gt;/status')+RD.stat('Main RSS',fm(i===0?B.rollup.Rss:AM.rollup.Rss),'resident')}
  RD.anim({card:'rd-as-card',ctl:'rd-as-ctl',n:STEPS.length,draw:draw,ms:4200,label:'Step'});
  document.getElementById('rd-as-raw').textContent='# before the fork: the first mapping of each kind, from /proc/'+st.before_fork[0].pid+'/maps\n'+B.sample.join('\n')+'\n\n# after: the /dev/shm mappings in the main process\n'+shmLines.join('\n');
  document.getElementById('rd-as-note').innerHTML='<span class="meas">measured here</span> The running job (src/trace/job/train.py, fork start method, 2 workers, batch 64) wrapped by src/read/code/maps_job.py, which saved /proc/&lt;pid&gt;/maps, smaps_rollup and status at the loader_start and step_3 phase markers, in kb-os-lab:1 on 2026-10-05. One run; the split between Private and Shared changes a little from run to run.';
  const fc=RD_DATA.ctx;if(fc){document.getElementById('rd-fork-cost').innerHTML='<span class="meas">measured here</span> fork() then exit() then wait() took '+fc.fork_exit_wait_0MiB_us.toFixed(0)+' &micro;s for a small C process and '+(fc.fork_exit_wait_512MiB_us/1000).toFixed(1)+' ms once it had 512 MiB of memory written (median of 9, <code>src/read/code/ctxswitch.c</code>): about '+Math.round(fc.fork_exit_wait_512MiB_us/fc.fork_exit_wait_0MiB_us)+' times longer, with no data copied.'}
})();
