// ---- Syscall tracer (t-trace): what each system call in the traces asks the kernel ----
// TRD[name] = [kind, man page (man7.org slug), what it asks, OS idea (with OSTEP chapter), who called it in these traces]
// Kinds: proc (processes and signals), mem (memory), file (files and I/O), ipc (IPC and synchronisation), time (time and randomness).
// Man pages: man7.org, Linux man-pages project. "Who called it" comes from the traces and the gdb call stacks in src/trace/raw.
window.TRD = {
execve:["proc","execve.2","Replace this process's program with a new one: load the executable, map it, start at its entry point.","The process API: exec (OSTEP 5)","The shell or docker starting python; multiprocessing's spawn and forkserver start a fresh python with it."],
clone:["proc","clone.2","Create a new task. With CLONE_THREAD it shares the address space (a thread); without it, it gets a copy-on-write copy (a process, like fork).","Processes and threads (OSTEP 5, 26)","threading.Thread, OpenMP and PyTorch thread pools (CLONE_THREAD); os.fork() in multiprocessing's fork start method (glibc fork() is clone without CLONE_THREAD). With CLONE_VM|CLONE_VFORK it is vfork-style: the child borrows the parent's memory and the parent waits until the child calls execve; that is how the spawn and forkserver runs start a new python."],
clone3:["proc","clone.2","Newer form of clone with a struct of arguments.","Processes and threads (OSTEP 26)","glibc 2.34+ pthread_create on kernels that support it."],
wait4:["proc","wait4.2","Wait for a child process to change state and collect its exit status (reaping it, so it is not left a zombie).","wait() and zombies (OSTEP 5)","multiprocessing.Process.join() via os.waitpid."],
waitid:["proc","wait.2","Like wait4, with a different interface.","wait() (OSTEP 5)","Node and Rust process code; multiprocessing's poll."],
exit:["proc","_exit.2","End this thread.","Threads (OSTEP 26)","A thread function returning (pthread_exit)."],
exit_group:["proc","exit_group.2","End every thread of this process; the kernel frees its memory and closes its files.","The process API (OSTEP 5)","sys.exit(), returning from main(), os._exit() in a multiprocessing child."],
kill:["proc","kill.2","Send a signal to a process.","Signals (OSTEP 5)","os.kill(); in production the sender is the kubelet, Slurm or a preemption handler."],
tgkill:["proc","tgkill.2","Send a signal to one thread of a process.","Signals","pthread_kill, raise() in a threaded program."],
getpid:["proc","getpid.2","Return this process's id.","Process identity (OSTEP 5)","os.getpid(); multiprocessing checks it to notice it has been forked."],
gettid:["proc","gettid.2","Return this thread's id.","Threads (OSTEP 26)","threading.get_native_id(), logging, OpenMP runtimes."],
getppid:["proc","getpid.2","Return the parent's process id.","The process tree (OSTEP 5)","DataLoader workers watch their parent so they exit if it dies."],
set_tid_address:["proc","set_tid_address.2","Tell the kernel where to write zero (and wake a futex) when this thread exits.","Threads (OSTEP 26)","glibc start-up and pthread_create."],
set_robust_list:["proc","get_robust_list.2","Register the list of locks this thread holds, so the kernel can mark them if it dies holding one.","Locks (OSTEP 28)","glibc start-up and every new thread."],
rseq:["proc","rseq.2","Register a restartable-sequence area (a per-CPU fast path the kernel restarts if the thread is preempted).","Scheduling, per-CPU data (OSTEP 10)","glibc 2.35+ registers it for every thread."],
prctl:["proc","prctl.2","Change a property of this process or thread (name, death signal, ...).","Process attributes","Thread naming; PR_SET_PDEATHSIG so a child dies with its parent."],
prlimit64:["proc","getrlimit.2","Read or set a resource limit (stack size, open files, ...).","Resource limits","glibc and runtimes reading the stack limit; ulimit -n is RLIMIT_NOFILE."],
getuid:["proc","getuid.2","Return the real user id.","Credentials (part of what a process is)","Python start-up (site.py), Node start-up."],
geteuid:["proc","getuid.2","Return the effective user id.","Credentials","Python and Node start-up."],
getgid:["proc","getgid.2","Return the real group id.","Credentials","Python and Node start-up."],
getegid:["proc","getgid.2","Return the effective group id.","Credentials","Python and Node start-up."],
capget:["proc","capget.2","Read this thread's capabilities (pieces of root's power).","Capabilities (see Reading, containers)","Node start-up checks whether it runs with extra privileges."],
uname:["proc","uname.2","Return the kernel name, version and machine.","What the kernel tells a program about itself","platform.uname(), library start-up probes."],
rt_sigaction:["proc","sigaction.2","Install or read a signal handler.","Signals (OSTEP 5)","signal.signal(); Python installs its own handlers at start-up, Rust and Node too."],
rt_sigprocmask:["proc","sigprocmask.2","Block or unblock signals for this thread.","Signals","Thread creation (new threads start with signals blocked), fork(), Node."],
rt_sigreturn:["proc","sigreturn.2","Return from a signal handler to the code that was interrupted.","Signals, kernel and user mode (OSTEP 6)","Inserted by the kernel after every handler runs."],
sigaltstack:["proc","sigaltstack.2","Set an alternate stack for signal handlers.","Signals","Rust's std installs one to report stack overflows."],
sched_getaffinity:["proc","sched_setaffinity.2","Return the set of CPUs this thread may run on.","CPU affinity, scheduling (OSTEP 10)","os.sched_getaffinity, OpenMP and PyTorch deciding how many threads to start; Rust's available_parallelism."],
restart_syscall:["proc","restart_syscall.2","Resume a system call that a signal interrupted.","Signals","Inserted by the kernel."],
mmap:["mem","mmap.2","Map memory into the address space: anonymous (fresh zeroed memory) or a file (its pages, read on demand through the page cache).","Address spaces, memory-mapped files (OSTEP 13, 14, 23)","The dynamic loader mapping .so files; malloc for big blocks; np.memmap; PyTorch's allocator and shared-memory tensors."],
munmap:["mem","mmap.2","Remove a mapping.","Address spaces (OSTEP 14)","free() of a big block; Python's arena allocator returning an arena; closing a memmap."],
mprotect:["mem","mprotect.2","Change the permissions of mapped pages (read, write, execute).","Protection, page tables (OSTEP 18)","The loader making relocated data read-only (RELRO); guard pages for thread stacks; JIT compilers (V8)."],
brk:["mem","brk.2","Move the end of the heap (the classic way malloc grows small allocations).","The heap, the memory API (OSTEP 14, 17)","glibc malloc for small objects, through Python's allocator."],
madvise:["mem","madvise.2","Give the kernel advice about a range: will need, do not need, use huge pages...","Paging policy, huge pages (OSTEP 19, 22)","glibc releasing an exited thread's stack (MADV_DONTNEED); mimalloc inside libc10.so asking for huge pages on its 1 GiB arena (MADV_HUGEPAGE, gdb stack recorded)."],
mbind:["mem","mbind.2","Set the NUMA memory policy for a range.","NUMA (see Reading, virtual memory)","Called on 32 MiB ranges during import torch; here it fails with ENOSYS because this VM's kernel has no NUMA support, and the job carries on."],
membarrier:["mem","membarrier.2","Issue a memory barrier on all CPUs running this process's threads.","Memory ordering (see C++ page)","Runtimes with JITs or RCU-like schemes."],
openat:["file","open.2","Open a file (relative to a directory) and return a file descriptor, a small integer naming it.","Files and directories (OSTEP 39)","open() in every language; the loader opening .so files; Python's import system opening .pyc files; shm_open for /dev/shm."],
open:["file","open.2","Open a file (older form; arm64 Linux has only openat).","Files and directories (OSTEP 39)",""],
close:["file","close.2","Release a file descriptor.","Files and directories (OSTEP 39)","with-blocks ending, file objects being garbage-collected, the loader after mapping a library."],
read:["file","read.2","Copy up to N bytes from an open file, pipe or socket into a buffer, advancing the offset.","Files (OSTEP 39); the page cache","file.read(); Python reading .pyc files at import; DataLoader receiving pickled batches through a pipe."],
write:["file","write.2","Copy N bytes from a buffer into an open file, pipe or socket.","Files (OSTEP 39); the page cache","print() flushing stdout; torch.save; multiprocessing sending messages through pipes."],
pread64:["file","pread.2","Read at a given offset without moving the file offset.","Files (OSTEP 39)","The loader reading ELF headers; Node reading its snapshot."],
pwrite64:["file","pread.2","Write at a given offset without moving the file offset.","Files (OSTEP 39)","Databases, checkpoint writers that write shards in parallel."],
writev:["file","readv.2","Write several buffers in one call (gather).","Files (OSTEP 39)","glibc stdio and Rust's buffered writers."],
readv:["file","readv.2","Read into several buffers in one call (scatter).","Files (OSTEP 39)",""],
lseek:["file","lseek.2","Move or report a file's offset.","Files (OSTEP 39)","Python's io module asking where it is (tell) when it opens a file; Rust's read_to_string."],
newfstatat:["file","stat.2","Return a file's metadata (size, type, permissions, times), by path or by descriptor.","Files and directories, inodes (OSTEP 39, 40)","Python's import system checking for modules on every sys.path entry (most fail with ENOENT); os.stat; fstat after open."],
fstat:["file","stat.2","Return metadata of an open file.","Inodes (OSTEP 39, 40)",""],
statx:["file","statx.2","Return file metadata (newer, extensible form).","Inodes (OSTEP 39, 40)","Rust's std and libuv (Node) after opening a file, to size the buffer."],
getdents64:["file","getdents.2","Read directory entries.","Directories (OSTEP 39)","Python's import system listing a package directory once and caching it (FileFinder)."],
readlinkat:["file","readlink.2","Read where a symbolic link points.","Directories and links (OSTEP 39)","Python resolving /proc/self/exe and the venv's python symlink."],
faccessat:["file","access.2","Check whether a path exists or is accessible. Our job also uses it as a phase marker: /phase/<name> never exists.","Files (OSTEP 39)","The loader checking /etc/ld.so.preload; train.py's phase() markers."],
faccessat2:["file","access.2","Newer access check with flags.","Files (OSTEP 39)",""],
fcntl:["file","fcntl.2","Control an open descriptor: duplicate it, set close-on-exec or non-blocking, take a lock.","File descriptors (OSTEP 39)","np.memmap duplicating the descriptor; libuv setting non-blocking mode."],
ioctl:["file","ioctl.2","A device-specific request on a descriptor (the catch-all door into drivers).","Devices and drivers (OSTEP 36)","Python asking every newly opened file whether it is a terminal (TCGETS, which fails with ENOTTY); GPU drivers use ioctl for everything (see Reading, GPU stack)."],
fsync:["file","fsync.2","Wait until the file's data and metadata are on the storage device.","Crash consistency (OSTEP 42)","os.fsync in a safe checkpoint; fsync of the directory makes a rename durable."],
fdatasync:["file","fsync.2","Like fsync, skipping metadata not needed to read the data back.","Crash consistency (OSTEP 42)","Databases' write-ahead logs."],
renameat:["file","rename.2","Atomically give a file a new name, replacing any file already there.","Atomic rename, crash consistency (OSTEP 39, 42)","os.replace: the last step of write-then-rename."],
renameat2:["file","rename.2","rename with flags (e.g. do not replace).","Atomic rename (OSTEP 39)",""],
unlinkat:["file","unlink.2","Remove a name from a directory (the file is freed when no name and no descriptor refers to it).","Files and directories (OSTEP 39)","Deleting temporary files; PyTorch unlinking a /dev/shm segment right after creating it, so it vanishes when the last process lets go."],
linkat:["file","link.2","Give an existing file another name.","Hard links (OSTEP 39)","glibc sem_open: it builds a named semaphore in /dev/shm under a temporary name, then links it to its real name (multiprocessing's locks inside every Queue)."],
mkdirat:["file","mkdir.2","Create a directory.","Directories (OSTEP 39)","os.makedirs; Python's __pycache__."],
ftruncate:["file","truncate.2","Set a file's size.","Files (OSTEP 39)","Sizing a new shared-memory segment in /dev/shm before mapping it."],
fallocate:["file","fallocate.2","Reserve space for a file now, so later writes cannot fail for lack of space.","File system allocation (OSTEP 40)","PyTorch's shared-memory allocator reserving a /dev/shm segment (failure here is the classic small-/dev/shm DataLoader error)."],
fadvise64:["file","posix_fadvise.2","Advise the kernel how a file will be read (sequential, random, will need).","The page cache, readahead","Shared-memory and file readers hinting their access pattern."],
getcwd:["file","getcwd.3","Return the current working directory.","Processes (part of a process's state)","Python start-up building sys.path."],
close_range:["file","close_range.2","Close every file descriptor in a range in one call.","File descriptors (OSTEP 39)","A new child process closing the descriptors it must not inherit before it runs (CPython's subprocess and spawn)."],
fchmodat:["file","chmod.2","Change a file's permission bits.","Files and permissions (OSTEP 39)","multiprocessing making its listener socket file private (chmod 0600)."],
dup:["file","dup.2","Duplicate a file descriptor.","File descriptors (OSTEP 39)","Node and multiprocessing duplicating descriptors to hand to children."],
dup3:["file","dup.2","Duplicate onto a chosen number.","File descriptors (OSTEP 39)","Redirecting stdout/stderr in a child."],
pipe2:["ipc","pipe.2","Create a pipe: a one-way byte channel with a read end and a write end.","Interprocess communication (OSTEP 5)","multiprocessing.Pipe and Queue; spawn passing the pickled child state; Node's libuv."],
socketpair:["ipc","socketpair.2","Create a connected pair of Unix sockets.","IPC","multiprocessing on some paths."],
socket:["ipc","socket.2","Create a communication endpoint (here Unix-domain: a local socket, not a network one).","IPC; sockets (see Topic: protocols)","multiprocessing's resource sharer (a listener thread in each worker, Unix sockets under /tmp/pymp-*) and the forkserver; this is how PyTorch hands a shared-memory tensor's descriptor to another process."],
connect:["ipc","connect.2","Connect a socket to an address.","IPC; sockets","The main process connecting to a worker's resource sharer to fetch a batch's shared-memory descriptor; asking the forkserver for a new child."],
bind:["ipc","bind.2","Give a socket an address (here a path).","IPC; sockets","multiprocessing's resource-sharer listener in each worker; the forkserver's socket."],
listen:["ipc","listen.2","Accept incoming connections on a socket.","IPC; sockets","multiprocessing's listener."],
accept4:["ipc","accept.2","Take the next incoming connection.","IPC; sockets","The resource-sharer thread in a worker taking the main process's request."],
sendmsg:["ipc","send.2","Send a message on a socket; can carry file descriptors (SCM_RIGHTS).","IPC: passing descriptors between processes","PyTorch sending a shared-memory tensor's descriptor to another process; forkserver passing pipes to a new child."],
recvmsg:["ipc","recv.2","Receive a message, possibly with file descriptors.","IPC","The receiving side of the above."],
getsockname:["ipc","getsockname.2","Return a socket's own address.","IPC; sockets","multiprocessing's connection setup."],
setsockopt:["ipc","getsockopt.2","Set a socket option.","Sockets",""],
getsockopt:["ipc","getsockopt.2","Read a socket option.","Sockets",""],
poll:["ipc","poll.2","Wait until one of several descriptors is ready.","Event-based concurrency (OSTEP 33)","multiprocessing's connection.wait; DataLoader waiting on a worker's queue with a timeout."],
ppoll:["ipc","poll.2","poll with a precise timeout and a signal mask.","Event-based concurrency (OSTEP 33)","Python's select and multiprocessing waits; Rust's std checking stdio at start-up."],
pselect6:["ipc","select.2","select with a precise timeout and signal mask.","Event-based concurrency (OSTEP 33)",""],
epoll_create1:["ipc","epoll_create.2","Create an epoll instance: a kernel object that watches many descriptors.","Event-based concurrency (OSTEP 33)","libuv's event loop under Node; asyncio and tokio use it too."],
epoll_ctl:["ipc","epoll_ctl.2","Add, change or remove a descriptor in an epoll set.","Event-based concurrency (OSTEP 33)","libuv registering its internal pipes and eventfds."],
epoll_pwait:["ipc","epoll_wait.2","Wait for events on an epoll set.","Event-based concurrency (OSTEP 33)","Node's event loop going idle."],
eventfd2:["ipc","eventfd.2","Create a counter descriptor one thread can use to wake another.","Event-based concurrency, wakeups (OSTEP 33)","libuv's async handles (waking the loop from its thread pool)."],
futex:["ipc","futex.2","Wait until a word in memory changes, or wake threads waiting on it: the kernel half of every lock and condition variable.","Locks and condition variables (OSTEP 28, 30)","Mutexes and condition variables in glibc (pthread), the GIL, queue.Queue, OpenMP barriers, PyTorch's thread pool."],
memfd_create:["ipc","memfd_create.2","Create an anonymous file in memory.","Shared memory","Some allocators and runtimes."],
clock_gettime:["time","clock_gettime.2","Read a clock. Usually answered in user space by the vDSO, so it rarely shows in a trace.","Time; the vDSO avoids a kernel entry","time.perf_counter(), time.time()."],
clock_nanosleep:["time","clock_nanosleep.2","Sleep until a time.","Scheduling: blocking (OSTEP 7)","time.sleep()."],
nanosleep:["time","nanosleep.2","Sleep for a time.","Scheduling: blocking (OSTEP 7)","time.sleep() in older libcs."],
getrandom:["time","getrandom.2","Fill a buffer with random bytes from the kernel's generator.","Kernel services","Python's hash randomisation at start-up, the random module, tempfile names, glibc malloc's start-up."],
sysinfo:["time","sysinfo.2","Return memory and load totals.","Memory accounting (see Reading, memory)","Python's os module and libraries sizing caches; Node at start-up."]
};
window.TR_KIND = {proc:["Processes and signals","var(--c1)"],mem:["Memory","var(--c3)"],file:["Files and I/O","var(--c2)"],ipc:["IPC and synchronisation","var(--c4)"],time:["Time and randomness","var(--c5)"],other:["Other","var(--mute)"],sig:["Signal delivered","var(--bad)"]};
