"""Write parts/22_js_fsdk_data.js from recordings/*.json and data/numbers.json (run recompute.py first).
Texts shown on the page are shortened (tool results to 700 characters, inputs to 400 per field, wire bodies to
700 characters of JSON); every number comes from data/numbers.json."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
REC = os.path.join(HERE, "recordings")
N = json.load(open(os.path.join(HERE, "data", "numbers.json")))
LABELS = ["s1_wire", "s2_deny", "s3_bare", "s4_session", "s5_subagent", "s6_structured", "s8_ts", "s9_rewind"]

def short(s, n):
    if isinstance(s, str) and len(s) > n:
        return s[:n] + " [...]"
    return s

def deep(o, n):
    if isinstance(o, dict): return {k: deep(v, n) for k, v in o.items()}
    if isinstance(o, list): return [deep(v, n) for v in o]
    return short(o, n)

def compact(ev):
    out = []
    for e in ev:
        k = e["k"]; t = e.get("t"); ph = e.get("phase")
        row = None
        if k == "asst":
            for b in e["blocks"]:
                if b["k"] == "thinking": row = ["think", t, e.get("parent"), "", e["model"]]
                elif b["k"] == "text": row = ["text", t, e.get("parent"), short(b["text"], 900), e["model"]]
                elif b["k"] == "call": row = ["call", t, e.get("parent"), b["name"], deep(b["input"], 400), b["id"], e["model"]]
                else: continue
                if ph: row.append(ph)
                out.append(row)
            continue
        if k == "tool_results":
            for b in e["blocks"]:
                if b["k"] != "result": continue
                row = ["res", t, e.get("parent"), short(b["text"], 700), b["id"], b["error"]]
                if ph: row.append(ph)
                out.append(row)
            continue
        if k == "user": row = ["user", t, None, short(e["text"], 600)]
        elif k == "cb":
            d = {x: y for x, y in e.items() if x not in ("t", "k", "phase")}
            row = ["cb", t, None, deep(d, 300)]
        elif k == "denied": row = ["denied", t, None, e["tool"], e["id"], e["subagent"]]
        elif k == "task": row = ["task", t, None, e["sub"], e.get("status")]
        elif k == "init": row = ["init", t, None, e["init"]]
        elif k == "result":
            row = ["result", t, None, {x: e.get(x) for x in ("subtype", "num_turns", "total_cost_usd", "duration_ms", "session")}
                   | {"result": short(e.get("result"), 900)}]
        if row:
            if ph: row.append(ph)
            out.append(row)
    return out

runs = {}
for L in LABELS:
    r = json.load(open(os.path.join(REC, L + ".json")))
    n = N[L]
    diff = (r.get("meta") or {}).get("diff", "")
    diff = "\n".join(l for l in diff.splitlines() if not l.startswith("diff ")) if diff else ""
    diff = "\n".join(l.split("\t")[0] if l.startswith(("---", "+++")) else l for l in diff.splitlines())
    runs[L] = {"n": {k: n[k] for k in ("model", "cli", "n_calls", "first_call_in", "tests_after", "wall_s",
                                     "tests_unchanged", "hooks", "hooks_pre", "permission_calls", "tool_calls",
                                     "sub_tool_calls", "denied_events", "calls")},
               "results": n["results"], "argv": n.get("argv"), "tools": n["tools"], "diff": diff,
               "ev": compact(r["events"]), "other": n.get("other_cb")}

def wire(L):
    r = json.load(open(os.path.join(REC, L + ".json")))
    rows = []
    for w in r.get("wire") or []:
        b = w.get("body")
        bs = json.dumps(b, ensure_ascii=False) if b is not None else ""
        if len(bs) > 700: bs = bs[:700] + " [...]"
        rows.append([w["t"], w["dir"], w["type"], w.get("sub") or w.get("what") or "", w.get("rid") or "",
                     ",".join(w.get("names") or []), bs])
    return rows

red = json.load(open(os.path.join(REC, "_redaction.json")))
DATA = {"runs": runs, "wire": {"s1_wire": wire("s1_wire"), "s3_bare": wire("s3_bare")},
        "conn": N["connectors"], "files": N["session_files"], "emdash": red["emdash_replaced"]}
js = "// Generated by src/gen_data.py from src/recordings (redacted) and src/data/numbers.json. Do not edit.\n"
js += "window.FSDK=" + json.dumps(DATA, ensure_ascii=False, separators=(",", ":")) + ";\n"
open(os.path.join(HERE, "parts", "22_js_fsdk_data.js"), "w").write(js)
print("22_js_fsdk_data.js", len(js.encode()), "bytes")
