// ---- When training goes wrong: content (bands, recorded runs, symptoms, causes) ----
// Links use the build's {{text|url}} form; n:<id> is a Notion page, #t-lab the Training lab tab.
window.DG = window.DG || {};
(function (DG) {
  const NP = {loss: 'n:3c65c17b0d0d8161a72bc8c572f37d55', act: 'n:3c65c17b0d0d819f8049c255e6f206e2', reg: 'n:3c65c17b0d0d81e988b5c3cb5e197f98',
    opt: 'n:3c65c17b0d0d817080bbc90954681d09', norm: 'n:3c65c17b0d0d81369e1cc38ed4e11d48', met: 'n:3c65c17b0d0d81a29acef722e842a29b'};
  DG.NP = NP;
  // the bands of one training step, in the order the step meets them; "code" is not a band but breaks every band
  DG.bands = [
    {k: 'data', n: 'Data', c: 'var(--dg-b1)', page: 'Norm and init (feature scaling)', pid: 'norm'},
    {k: 'init', n: 'Initialisation', c: 'var(--dg-b2)', page: 'Normalisation and initialisation', pid: 'norm'},
    {k: 'act', n: 'Activation', c: 'var(--dg-b3)', page: 'Activations', pid: 'act'},
    {k: 'norm', n: 'Normalisation', c: 'var(--dg-b4)', page: 'Normalisation and initialisation', pid: 'norm'},
    {k: 'loss', n: 'Loss', c: 'var(--dg-b5)', page: 'Loss functions', pid: 'loss'},
    {k: 'opt', n: 'Optimiser and LR', c: 'var(--dg-b6)', page: 'Optimisers', pid: 'opt'},
    {k: 'sched', n: 'Schedule', c: 'var(--dg-b7)', page: 'Optimisers (schedules, warmup)', pid: 'opt'},
    {k: 'reg', n: 'Regularisation', c: 'var(--dg-b8)', page: 'Regularisation', pid: 'reg'},
    {k: 'metric', n: 'Metric', c: 'var(--dg-b9)', page: 'Metrics', pid: 'met'},
    {k: 'code', n: 'Code (any band)', c: 'var(--mute)', page: null, pid: null}
  ];
  // what each recorded run is (data: scikit-learn 8x8 digits, 1,200 train / 597 validation; see src/debug/runs_digits.py)
  DG.runDesc = {
    healthy: 'healthy reference: MLP 64-128-128-10, ReLU, Adam 1e-3, batch 64, standardised pixels',
    nan_lr: 'SGD at 3.0 with momentum 0.9, about 30 times a rate that works',
    nan_lr_fix: 'SGD 0.1, momentum 0.9, 50 warmup steps, gradient clipping at 1.0',
    nan_log: 'loss written by hand as -log(softmax(z)[y]); SGD 0.2, momentum 0.9',
    nan_log_fix: 'same seed, batches and rate, loss computed by F.cross_entropy (log-softmax inside)',
    flat_lowlr: 'Adam at 1e-6, a thousand times too low',
    flat_stale_opt: 'optimiser built for an earlier copy of the model: gradients exist, weights never move',
    flat_double_softmax: 'model ends in Softmax and the loss is cross_entropy, which applies log-softmax again',
    flat_shuffled_labels: 'training labels shuffled once, so they no longer match the images',
    overfit_one_batch_ok: 'overfit one batch (8 images), healthy code',
    overfit_one_batch_stale: 'overfit one batch, stale-optimiser bug',
    overfit_one_batch_shuffled: 'overfit one batch, shuffled labels',
    osc_lr: 'Adam at 0.03, thirty times the usual 1e-3',
    osc_lr_fix: 'Adam at 1e-3',
    osc_bs: 'batch of 2 images instead of 64',
    osc_unscaled: 'raw pixels 0 to 16, not standardised; SGD 0.05, momentum 0.9',
    plateau_dead: 'hidden-layer biases initialised at -3, so most ReLUs are off for most images',
    plateau_dead_fix: 'He initialisation, zero biases',
    plateau_decay: 'cosine schedule sized in epochs but read as steps: the rate reaches 0 at step 30',
    plateau_decay_fix: 'the same cosine schedule over the 600 steps actually run',
    vanish_sigmoid: '20 hidden layers of 64, sigmoid, PyTorch default init, SGD 0.1, momentum 0.9',
    vanish_fix_relu_he: 'same depth, ReLU, He initialisation, SGD 0.01, clipping at 1.0',
    explode_init: '20 hidden layers of 64, ReLU, every weight drawn from N(0, 1)',
    explode_fix_he: 'same depth, He initialisation N(0, 2/64), clipping at 1.0',
    val_scaler_bug: 'healthy run, but the scaler divides by (std + 1e-6) and some pixels are constant in training',
    overfit: '300 images with 30% of labels randomised, MLP 64-512-512-10, no regularisation',
    overfit_fix_reg: 'same data, dropout 0.5 and weight decay 0.5',
    overfit_fix_data: 'same 30% label noise, all 1,200 images',
    underfit_tiny: 'a 2-unit bottleneck, 64-2-10',
    underfit_wd: 'healthy model under weight decay 30',
    underfit_fix: 'MLP 64-128-128-10, Adam 3e-3, no weight decay'
  };

  // causes: b band, t title, w why, ch check, fx fix, run [bug, fix] recorded pair (optional), lab: what to do in the Training lab
  DG.symptoms = [
    {id: 'nan', n: 'Loss is NaN or inf', run: ['nan_log', 'nan_log_fix'],
      lead: 'A loss that climbs from the very first steps, or turns NaN, is the learning rate or exploding gradients until proven otherwise. A single non-finite number anywhere in the step poisons every weight it touches, and the run never recovers. Find the first tensor that went non-finite, not the last.',
      causes: [
        {b: 'opt', t: 'Learning rate too high, or no warmup', run: ['nan_lr', 'nan_lr_fix'],
          w: 'Each update overshoots; activations and logits grow until something overflows. The Tuning Playbook: "Any workload will become unstable if the learning rate is too large."',
          ch: 'Does it go away at a third of the rate? Log the gradient norm every step: it climbs before the loss does.',
          fx: 'Lower the rate; add warmup (best for early instability); clip the global gradient norm.',
          lab: 'raise the learning rate step by step until the loss blows up',
          note: 'At this scale the blow-up did not end in NaN: the loss reached about 10<sup>14</sup> in the first steps, every ReLU died, and the loss then sat at ln 10 = 2.303 for the rest of the run. A loss pinned exactly at ln K after a blow-up is a dead network.'},
        {b: 'loss', t: 'log(0), division by zero or exp overflow inside the loss', run: ['nan_log', 'nan_log_fix'],
          w: 'Taking the log of a softmax that has underflowed to exactly 0 gives -inf, and its gradient NaN. In float32, softmax underflows once a logit trails the largest by about 104.',
          ch: 'Run one bad step with anomaly detection (<code>torch.autograd.set_detect_anomaly(True)</code>) to name the operation; check the minimum probability and the largest logit gap.',
          fx: 'Use fused log-space operations (log-softmax plus negative log-likelihood, as <code>F.cross_entropy</code> does); add epsilons to denominators and logs; never feed probabilities to a loss that expects logits.',
          note: 'Recorded: the two runs agree to the printed precision through step 60. At step 70 the hand-written validation loss is already inf (one validation image gets probability exactly 0), and the training loss turns NaN at step 250. The fused run never does, but it is noisy: the rate is still too high, a second problem the NaN was hiding.'},
        {b: 'init', t: 'Initial weights too large', run: ['explode_init', 'explode_fix_he'],
          w: 'With weights drawn from N(0, 1) each 64-wide ReLU layer multiplies the signal by about &radic;(64/2) = 5.7, so 20 layers multiply it by about 10<sup>15</sup>.',
          ch: 'Measure the loss before the first update: it should be -ln(1/K) (2.303 for 10 classes). Print activation standard deviations layer by layer at initialisation.',
          fx: 'Xavier (Glorot) for tanh and sigmoid, He (Kaiming) for ReLU; scale residual branches down.',
          note: 'Recorded: the loss at step 1 is 2.8 &times; 10<sup>16</sup> and NaN at step 2. With He initialisation the same network starts at 4.72 and trains.'},
        {b: 'data', t: 'Non-finite or wildly scaled inputs',
          w: 'A NaN in one input row, a feature divided by a zero standard deviation, or a value 10<sup>6</sup> standard deviations out flows straight into the logits.',
          ch: 'Assert that every batch is finite; print the minimum and maximum of every feature after the pipeline, on validation as well as training data.',
          fx: 'Clean or impute; guard the scaler against constant features (leave them unscaled, or divide by max(std, small)).'},
        {b: 'opt', t: 'Low-precision overflow (fp16, bf16 accumulation)',
          w: 'fp16 tops out at 65,504, so large gradients overflow to inf; bf16 has the range but only 8 bits of mantissa, so long sums lose precision. Llama 3 found that accumulating gradients in bf16 caused numerical instabilities once the image encoder was added and fixed it by accumulating in FP32 (Llama 3 &sect;7.3, on the {{Llama 3 Herd paper page|n:3c65c17b0d0d81aca58ccb9d720b474e}}).',
          ch: 'Rerun the failing step in fp32; count overflowed gradients per step (the loss scaler reports skipped steps).',
          fx: 'Dynamic loss scaling with fp16; bf16 with fp32 master weights and fp32 accumulation of gradients and reductions.'}
      ]},
    {id: 'flat', n: 'Loss flat from the start', run: ['flat_stale_opt', 'healthy'],
      lead: 'If the loss sits at its starting value (about ln K for K classes) the updates are not reaching the weights, are too small to matter, or the target is unlearnable. Overfitting one batch splits code bugs from data bugs in a minute.',
      causes: [
        {b: 'opt', t: 'Learning rate wrong: far too low, or so high the network died at once', run: ['flat_lowlr', 'healthy'],
          w: 'Too low: updates are real but tiny; at 1e-6 Adam moves each weight by about a millionth per step. Too high: the first steps kill the network and the loss sits at ln K (see "The network died after a blow-up" under Loss plateaus).',
          ch: 'Sweep the rate: try 3 times up and 3 times down, and keep going until something changes.',
          fx: 'Move it until the curve changes; for Adam, Karpathy\'s safe starting point is 3e-4.',
          lab: 'set the learning rate to its lowest value'},
        {b: 'code', t: 'Gradients not reaching the weights', run: ['flat_stale_opt', 'healthy'],
          w: 'The optimiser holds parameters of a different copy of the model, layers are accidentally frozen (<code>requires_grad=False</code>), a <code>.detach()</code> or a non-differentiable step cuts the graph, or <code>optimizer.step()</code> is never called.',
          ch: 'Is every layer actually connected to the loss? Overfit one batch: if 8 images cannot be driven to about 0 loss, the bug is in the code. Log the weight norm: if it never changes while the gradient norm is non-zero, the update is going nowhere. Inspect gradient norms per layer.',
          fx: 'Build the optimiser from <code>model.parameters()</code> after the model is final; check which parameters require gradients.'},
        {b: 'data', t: 'Inputs and labels do not match', run: ['flat_shuffled_labels', 'healthy'],
          w: 'Labels shuffled out of order, a broken join, an augmentation applied to the image but not to its mask: there is nothing to learn except memorisation.',
          ch: 'Look at (x, y) pairs by hand immediately before <code>model(x)</code>, after the whole pipeline. Overfit one batch: it still succeeds (the network memorises 8 wrong labels), which tells you the code is fine and the data is not.',
          fx: 'Fix the pipeline; visualise a batch after every change to it.',
          note: 'Recorded: the training loss creeps down by memorisation (1.12 after 600 steps) while validation climbs from 2.32 to 3.55 and accuracy stays at chance (11%).'},
        {b: 'loss', t: 'Wrong loss for the output', run: ['flat_double_softmax', 'healthy'],
          w: 'Logits against probabilities: a model that already ends in softmax fed to a loss that applies log-softmax again; mean squared error on class indices; a binary loss on multi-class targets.',
          ch: 'Does the loss match the task and the output activation? Compute the loss of a perfect prediction: it should be about 0.',
          fx: 'Return raw logits and let the loss apply the softmax.',
          note: 'Recorded: the double softmax still reaches 98% accuracy, but the loss cannot go below ln(e + 9) - 1 = 1.461, the loss of a perfect prediction when every input to the second softmax lies in [0, 1].'},
        {b: 'sched', t: 'The schedule sets the rate to 0', run: ['plateau_decay', 'plateau_decay_fix'],
          w: 'A warmup that never advances, a decay sized in epochs but stepped per batch, a scheduler stepped twice. Karpathy: "do not trust learning rate decay defaults".',
          ch: 'Plot the learning rate actually applied at every step, read back from the optimiser.',
          fx: 'Size the schedule in the unit it is stepped in.'},
        {b: 'act', t: 'Saturated activations from the start', run: ['vanish_sigmoid', 'vanish_fix_relu_he'],
          w: 'A deep stack of sigmoids or tanh squashes the signal; the gradient reaching the first layers is many orders of magnitude smaller than at the last.',
          ch: 'Gradient norm per layer at step 1; fraction of units in the flat part of the activation.',
          fx: 'ReLU-family activations, matched initialisation, residual connections and normalisation.'}
      ]},
    {id: 'osc', n: 'Loss oscillates', run: ['osc_lr', 'osc_lr_fix'],
      lead: 'Some noise in a training curve is normal: every step sees a different batch. Oscillation that does not shrink over time, or a validation curve that never settles, means the steps are too big, too noisy or badly shaped.',
      causes: [
        {b: 'opt', t: 'Learning rate too high', run: ['osc_lr', 'osc_lr_fix'],
          w: 'Each step jumps across the valley instead of down it.',
          ch: 'Learning-rate sweep; plot training loss for the rates just above the best one (the Tuning Playbook\'s test for instability).',
          fx: 'Lower the rate, or decay it.',
          lab: 'raise the learning rate a few notches above its default',
          note: 'Recorded: at 0.03 the training loss swings over two orders of magnitude and validation never gets below 0.19; at 1e-3 the same model reaches 0.058.'},
        {b: 'opt', t: 'Batch too small (noisy gradients)', run: ['osc_bs', 'healthy'],
          w: 'The gradient of a batch of 2 is a very noisy estimate of the true gradient.',
          ch: 'Does the noise shrink when the batch grows (or with gradient accumulation)?',
          fx: 'Larger batch, or a lower rate for the same batch; averaging weights (Polyak or EMA).',
          lab: 'set the batch size to its smallest value'},
        {b: 'data', t: 'Features on very different scales', run: ['osc_unscaled', 'healthy'],
          w: 'Unscaled features stretch the loss surface into a narrow valley: a rate small enough for the steep direction crawls along the shallow one, and anything larger zigzags. Scaling makes every feature contribute comparably, so large-range features do not dominate, and rounds the contours so gradient descent converges faster; it usually improves the final model as well.',
          ch: 'Per-feature mean and standard deviation after the pipeline.',
          fx: 'Standardise or min-max scale, with statistics from the training split only. Scaling is mandatory for distance-based methods (kNN, SVM, k-means); formulas on the {{Normalisation and initialisation|' + NP.norm + '}} page.'},
        {b: 'opt', t: 'Optimiser without momentum or an adaptive rate',
          w: 'Plain SGD follows every wiggle of the noisy gradient; momentum averages it, adaptive methods rescale each coordinate.',
          ch: 'Same run with SGD plus momentum 0.9, or with Adam.',
          fx: 'Momentum or Adam(W); see {{Optimisers|' + NP.opt + '}}.'},
        {b: 'sched', t: 'Rate too high late in training',
          w: 'The Tuning Playbook lists three likely causes of step-to-step variance late in training: batch variance, small validation sets, and a learning rate that is too high late in training.',
          ch: 'Does the noise level stay constant to the end of the run?',
          fx: 'Learning-rate decay; a larger batch; Polyak averaging.'},
        {b: 'metric', t: 'Validation set too small',
          w: 'A wiggling validation curve can be the measurement, not the model.',
          ch: 'Standard error of the validation metric: for accuracy p on n examples it is about &radic;(p(1-p)/n).',
          fx: 'A bigger validation set; see {{Metrics|' + NP.met + '}}.'}
      ]},
    {id: 'plat', n: 'Loss plateaus', run: ['plateau_dead', 'plateau_dead_fix'],
      lead: 'A plateau is not always a bug. First ask whether the model is simply done; then whether the rate went to zero, units died, or a loss floor is built into the setup.',
      causes: [
        {b: 'metric', t: 'It is done (a minimum was reached)',
          w: 'Training loss stops falling because there is little left to learn at this capacity.',
          ch: 'Check validation metrics: if they are good and flat too, stop.',
          fx: 'Nothing; or more capacity or data if the metrics are not good enough.'},
        {b: 'sched', t: 'Learning rate decayed too early, or too small', run: ['plateau_decay', 'plateau_decay_fix'],
          w: 'The optimiser is still running but the rate is close to 0.',
          ch: 'Plot the applied rate.',
          fx: 'Increase it, fix the schedule length, or restart with warm restarts.',
          note: 'Recorded: the rate reaches 0 at step 30 and the loss freezes at 2.20 (37% accuracy); sized to the run, the same schedule reaches 0.099.'},
        {b: 'act', t: 'Dead ReLUs', run: ['plateau_dead', 'plateau_dead_fix'],
          w: 'A ReLU whose input is negative for every example outputs 0 and passes no gradient, so it never recovers. A high rate or a negative bias can kill most of a layer.',
          ch: 'Fraction of units that are zero on every example, per layer.',
          fx: 'Leaky ReLU or GELU; a lower rate; zero or small positive biases; see {{Activations|' + NP.act + '}}.',
          lab: 'switch the activation and compare',
          note: 'Recorded: with biases at -3, 42% of the second layer\'s units are zero on every training image at step 1, and validation loss sits between 2.27 and 2.31 for the first 150 steps before Adam pulls the biases up and it falls (0.56 at step 600, with 15% of those units still dead). He initialisation with zero biases does not stall.'},
        {b: 'opt', t: 'Saddle point',
          w: 'In high dimensions most flat regions are saddles, not minima: flat in most directions, downhill in a few.',
          ch: 'Does a small perturbation or a different optimiser move it?',
          fx: 'Momentum or an adaptive optimiser escapes; see {{Optimisers|' + NP.opt + '}}.'},
        {b: 'loss', t: 'A loss floor built into the setup', run: ['flat_double_softmax', 'healthy'],
          w: 'Double softmax, label smoothing, a regulariser in the reported loss: the loss cannot reach 0 even for perfect predictions.',
          ch: 'Work out the loss of a perfect prediction under your exact setup.',
          fx: 'Report the plain data loss separately from penalties.'},
        {b: 'opt', t: 'The network died after a blow-up', run: ['nan_lr', 'nan_lr_fix'],
          w: 'A huge early step pushes every ReLU negative; the model then predicts the same thing for every input.',
          ch: 'A loss pinned at exactly ln K (2.303 for 10 classes) is the loss of uniform predictions.',
          fx: 'Lower rate, warmup, clipping.'},
        {b: 'act', t: 'Vanishing gradients',
          w: 'See "Gradients vanish": the early layers stop learning, so the loss stops improving.',
          ch: 'Per-layer gradient norms.', fx: 'See that symptom.'}
      ]},
    {id: 'over', n: 'Train falls, validation rises', run: ['overfit', 'overfit_fix_data'],
      lead: 'Overfitting: the model is learning the training set rather than the task. Check first that validation is measured the same way as training; a validation loss that is wrong from step 0 is a pipeline bug, not overfitting.',
      causes: [
        {b: 'data', t: 'Too little data, or noisy labels', run: ['overfit', 'overfit_fix_data'],
          w: 'A large model can memorise every training example, wrong labels included.',
          ch: 'Train-validation gap over time; the best validation step.',
          fx: 'More data (including augmentation) comes first; Karpathy calls adding real data "by far the best and preferred way to regularize".',
          note: 'Recorded: with 300 images and 30% wrong labels, validation loss is lowest at step 40 (0.69) and climbs to 1.75 while training loss reaches 0.0002. Four times the images (same noise) brings the best validation loss to 0.46.'},
        {b: 'reg', t: 'Too little regularisation', run: ['overfit', 'overfit_fix_reg'],
          w: 'Nothing penalises a complicated fit.',
          ch: 'Does the gap shrink with L2 or weight decay, dropout, or label smoothing?',
          fx: 'L1 or L2 penalties, weight decay, dropout; see {{Regularisation|' + NP.reg + '}}.',
          lab: 'turn on weight decay or dropout and compare the validation curve',
          note: 'Recorded: dropout 0.5 plus weight decay 0.5 lowers the best validation loss only a little (0.64) and the curve still rises: regularisation helps, but with 30% wrong labels it does not replace early stopping or cleaner data.'},
        {b: 'reg', t: 'Trained past the best point',
          w: 'Validation loss has a minimum; every step after it fits noise.',
          ch: 'Keep checkpoints; find the step with the lowest validation loss.',
          fx: 'Early stopping: keep the best checkpoint and stop when validation has not improved for a while.'},
        {b: 'reg', t: 'Model too complex for the data',
          w: 'Capacity far beyond what the data supports.',
          ch: 'Does a smaller model reach the same validation loss?',
          fx: 'Reduce width or depth (after trying the fixes above).'},
        {b: 'data', t: 'Validation is computed differently from training', run: ['val_scaler_bug', 'healthy'],
          w: 'Different preprocessing, leaked or shifted statistics, a different distribution. Not overfitting: the gap is there from step 0.',
          ch: 'Is the validation loss at step 0 about the same as the training loss at step 0? Run validation through the training pipeline and compare.',
          fx: 'One preprocessing function for every split, fitted on the training split only.',
          note: 'Recorded by accident while building this tab: a few border pixels are always 0 in the training split, so the scaler divided by 1e-6 and any nonzero value in validation became about 10<sup>6</sup> standard deviations. Validation loss was 39 at step 0 and 425 at the end while accuracy stayed at 98%: a handful of absurd inputs dominate the mean loss.'}
      ]},
    {id: 'under', n: 'Train and validation both high', run: ['underfit_tiny', 'underfit_fix'],
      lead: 'Underfitting: the model cannot even fit the training set. Fix training loss before touching validation.',
      causes: [
        {b: 'reg', t: 'Model too small', run: ['underfit_tiny', 'underfit_fix'],
          w: 'Not enough capacity for the task.',
          ch: 'Does a wider or deeper model lower the training loss?',
          fx: 'Increase model complexity.',
          note: 'Recorded: a 2-unit bottleneck ends at training loss 0.81 and 60% accuracy; the 128-wide model reaches 98%.'},
        {b: 'sched', t: 'Not trained long enough',
          w: 'The curves are still falling at the end.',
          ch: 'Is the loss still improving at the last step?',
          fx: 'Train longer.'},
        {b: 'reg', t: 'Too much regularisation', run: ['underfit_wd', 'underfit_fix'],
          w: 'Weight decay or dropout so strong the model cannot fit.',
          ch: 'Halve it and compare training loss.',
          fx: 'Decrease regularisation.',
          lab: 'set weight decay to its largest value',
          note: 'Recorded: weight decay 30 holds both losses near 1.5 (58% accuracy).'},
        {b: 'opt', t: 'Optimisation, not capacity',
          w: 'A rate too low or decayed too early, or a plateau, looks like underfitting.',
          ch: 'See "Loss plateaus" and "Loss flat from the start".', fx: 'Fix the optimisation first.'}
      ]},
    {id: 'imb', n: 'Good accuracy, useless on the minority class', run: null,
      lead: 'On imbalanced data the model struggles to learn the minority class, and accuracy hides it: always saying "no" scores the share of negatives.',
      causes: [
        {b: 'metric', t: 'Accuracy on imbalanced data',
          w: 'With 1 positive in 21, "always no" scores 95.2%.',
          ch: 'Precision, recall, F1 and the area under the precision-recall curve (AUPRC), per class.',
          fx: 'Evaluate with precision, recall, F1 or AUPRC, never plain accuracy; see {{Metrics|' + NP.met + '}}.'},
        {b: 'loss', t: 'The majority dominates the loss',
          w: 'Most of the gradient comes from easy majority examples.',
          ch: 'Recall on the minority class during training.',
          fx: 'Re-weighting: higher weights on minority-class terms. Focal loss, FL(p<sub>t</sub>) = -&alpha;<sub>t</sub>(1 - p<sub>t</sub>)<sup>&gamma;</sup> log p<sub>t</sub>, down-weights easy examples so hard, misclassified ones dominate; it was built for extreme imbalance in dense detection (about 100k candidate locations per image, foreground to background up to 1:1000; &gamma; = 2, &alpha; = 0.25 worked best there). See {{Loss functions|' + NP.loss + '}}.'},
        {b: 'data', t: 'The minority is rarely seen',
          w: 'Few minority examples per batch.',
          ch: 'Count classes per batch.',
          fx: 'Re-sampling: oversample the minority (or synthesise, SMOTE-style), undersample the majority; data augmentation to enlarge the minority with realistic transforms.'},
        {b: 'init', t: 'Output bias starts at 50:50',
          w: 'The first steps are spent learning the base rate.',
          ch: 'Loss at step 0 against the entropy of the class prior.',
          fx: 'Initialise the output bias to the prior, b = -log((1 - &pi;)/&pi;): Lin et al. used &pi; = 0.01 to avoid instability early in training; Karpathy, for a 1:10 dataset, sets the bias so the network predicts 0.1 at initialisation.'},
        {b: 'metric', t: 'The 0.5 threshold',
          w: 'Re-weighting and re-sampling mostly move the decision threshold; a threshold chosen on validation can do the same.',
          ch: 'Precision-recall curve on validation.',
          fx: 'Pick the threshold for the precision and recall you need.'}
      ]},
    {id: 'spike', n: 'Loss spikes mid-run', run: null,
      lead: 'Sudden spikes after a long healthy stretch are the large-model failure. They often show first in the gradient norm, can grow more frequent with scale, and may or may not recover. Most fixes now ship by default in open recipes.',
      causes: [
        {b: 'opt', t: 'Learning rate at the edge of stability',
          w: 'Wortsman et al. (2023) show that the instabilities of large runs also appear in small models trained at high learning rates, and that the large-scale mitigations work there too (reproduced at toy scale below).',
          ch: 'Learning-rate sweep; the Tuning Playbook: plot the loss for rates just above the best.',
          fx: 'Lower the peak rate, longer warmup.',
          lab: 'raise the learning rate and watch for spikes'},
        {b: 'norm', t: 'Attention logits grow without bound',
          w: 'Query-key dot products grow until attention becomes one-hot and the loss diverges (Dehghani et al. 2023, Wortsman et al. 2023).',
          ch: 'Log the largest attention logit per layer.',
          fx: 'QK-norm: normalise queries and keys (RMSNorm or LayerNorm) before the dot product; OLMo 2 adopted it together with a reordered norm.'},
        {b: 'loss', t: 'Output logits drift',
          w: 'The softmax normaliser log Z drifts far from 0 (Chowdhery et al. 2022, PaLM).',
          ch: 'Log the mean log Z of the output softmax.',
          fx: 'z-loss: add 10<sup>-4</sup> &middot; log<sup>2</sup> Z to the loss (PaLM; adopted by OLMo 2).'},
        {b: 'opt', t: 'Outlier gradients',
          w: 'One batch produces a gradient far larger than typical.',
          ch: 'Log the unclipped gradient norm; plot it against the step and as a histogram.',
          fx: 'Clip the global norm; the Tuning Playbook suggests starting at the 90th percentile of observed norms, and calls more than 50% of steps clipped extreme (lower the rate instead). PaLM and OLMo 2 clip at 1.0.'},
        {b: 'data', t: 'Particular batches',
          w: 'OLMo 2 found spikes in batches full of long repeated sequences and filters repeated n-grams; PaLM found that spikes came from particular batches combined with a particular model state, not from bad data alone.',
          ch: 'Inspect the batches just before the spike; replay them from an earlier checkpoint.',
          fx: 'Filter repeated n-grams; restart from a checkpoint before the spike and skip the batches around it (PaLM).'},
        {b: 'init', t: 'Initialisation and per-parameter settings',
          w: 'OLMo 2\'s scaled initialisation, AdamW epsilon of 10<sup>-5</sup> and weight decay on embeddings each made spikes more frequent.',
          ch: 'The spike score of the gradient norm over a test run, before and after each change.',
          fx: 'OLMo 2: every weight from N(0, 0.02), &epsilon; = 10<sup>-8</sup>, no weight decay on embeddings.'},
        {b: 'code', t: 'Hardware and silent data corruption',
          w: 'A flipped bit can corrupt values without crashing.',
          ch: 'Deterministic replay of the step on another machine.',
          fx: 'See {{Training Infrastructure|n:3c65c17b0d0d81c9b2cac997583bf572}} (silent data corruption, Llama 3\'s interruptions).'}
      ]},
    {id: 'van', n: 'Gradients vanish', run: ['vanish_sigmoid', 'vanish_fix_relu_he'],
      lead: 'Early-layer gradients near 0: a deep network learns slowly or not at all, and the loss looks flat or plateaued.',
      causes: [
        {b: 'act', t: 'Saturating activations', run: ['vanish_sigmoid', 'vanish_fix_relu_he'],
          w: 'The sigmoid\'s derivative is at most 0.25, so every sigmoid layer shrinks the backward signal by at least 4 times.',
          ch: 'Per-layer gradient norms: a slope across the layers on a log scale.',
          fx: 'ReLU family over sigmoid and tanh; see {{Activations|' + NP.act + '}}.',
          lab: 'switch the activation to sigmoid and add depth'},
        {b: 'init', t: 'Initial weights too small',
          w: 'Each layer shrinks the signal in both directions.',
          ch: 'Activation and gradient standard deviations per layer at step 0.',
          fx: 'Xavier or He initialisation, matched to the activation.'},
        {b: 'norm', t: 'No residual connections or normalisation',
          w: 'Without a skip path every gradient must pass through every layer\'s Jacobian.',
          ch: 'Does the network have residual connections and normalisation layers?',
          fx: 'Add them; the Tuning Playbook puts the norm inside the residual, x + f(Norm(x)); see {{Normalisation and initialisation|' + NP.norm + '}}.'},
        {b: 'code', t: 'Network deeper than it needs to be',
          w: 'Each extra layer is another factor in the product.', ch: 'Does a shallower network do as well?', fx: 'Make the network shallower.'}
      ]},
    {id: 'exp', n: 'Gradients explode', run: ['explode_init', 'explode_fix_he'],
      lead: 'Gradients or weights blow up; the loss spikes or turns NaN.',
      causes: [
        {b: 'init', t: 'Initial weights too large', run: ['explode_init', 'explode_fix_he'],
          w: 'Each layer multiplies the signal by more than 1.',
          ch: 'Activation and gradient norms per layer at step 0; the loss before the first update.',
          fx: 'Better initialisation: He for ReLU, Xavier for tanh.'},
        {b: 'opt', t: 'No gradient clipping',
          w: 'One outsized gradient is applied in full.',
          ch: 'Unclipped gradient norm per step.',
          fx: 'Gradient clipping by global norm.',
          lab: 'turn gradient clipping off and raise the learning rate'},
        {b: 'opt', t: 'Learning rate too high',
          w: 'Large updates make the next gradients larger still.', ch: 'Does a third of the rate fix it?', fx: 'Lower it; add warmup.'},
        {b: 'norm', t: 'No residual connections or normalisation',
          w: 'Nothing keeps the activations at a fixed scale.', ch: 'Activation norms by layer over training.', fx: 'Residual connections and normalisation layers.'},
        {b: 'code', t: 'Network deeper than it needs to be',
          w: 'More layers, more multiplications.', ch: 'Does a shallower network do as well?', fx: 'Make the network shallower.'}
      ]}
  ];
})(window.DG);
