// ---- Toy tab: learning curves, failure reasons, and routes from each checkpoint ----
(function(){
  const $=id=>document.getElementById(id);if(!$('ty'))return;
  const Y=DS.toy;if(!Y||!Y.curves){$('tyS').textContent='Toy data not built yet.';return}
  const reg=f=>{(window.TAB_RENDER=window.TAB_RENDER||{});(window.TAB_RENDER['t-toy']=window.TAB_RENDER['t-toy']||[]).push(f)};
  const G=Y.graph,NM=G.names,ms=TOYM.order.filter(m=>Y.curves[m]);
  const on={};ms.forEach(m=>on[m]=true);
  const st=Y.student,tc=Y.teacher;
  $('tyS').innerHTML='<b>Task.</b> A fixed graph of '+G.n+' nodes and '+G.edges.length+' edges. A prompt is a start and a target node (all '+G.pairs+' ordered pairs); a correct answer is a route along edges that reaches the target in at most the shortest distance plus '+G.slack+' steps, then stops. A prompt has a median of '+G.routes_median+' correct routes, so the right next-token distribution often has several modes. '+
    '<b>Teacher.</b> A '+tc.cfg.L+'-layer transformer (width '+tc.cfg.d+', '+PF.comma(tc.params)+' parameters) trained on routes sampled uniformly from all correct ones: '+PF.pct(tc.succ,1)+' of its sampled routes are correct (greedy: '+PF.pct(tc.greedy,1)+'), and its next-token distribution is within '+tc.kl_exact.toFixed(3)+' nats per token of the exact one. '+
    '<b>Student.</b> The same architecture with '+st.cfg.L+' layers of width '+st.cfg.d+': '+PF.comma(st.params)+' parameters, '+(tc.params/st.params).toFixed(0)+' times smaller, too small to hold the whole graph perfectly. '+
    '<b>Protocol.</b> Every method starts from the same random student (per seed), draws '+st.batch+' prompts per step, and trains for '+PF.comma(st.steps)+' steps with Adam at '+st.lr+'; every '+(Y.curves[ms[0]][1][1][0]-Y.curves[ms[0]][1][0][0])+' steps it is tested on all '+G.pairs+' prompts. Losses are exact over the whole vocabulary (on-policy reverse KL uses the full distribution, as GKD and Qwen3 do, not Thinking Machines\' one-sample estimate). '+
    '<b>Compute</b> is counted as model FLOPs: 6 × parameters per trained token, 2 × parameters per token the teacher scores, and 2 × parameters per token generated by whoever writes the routes. On-policy methods generate with the '+(tc.params/st.params).toFixed(0)+'-times-smaller student; off-policy methods generate with the teacher.';
  $('tyMs').innerHTML=ms.map(m=>'<label><input type="checkbox" data-m="'+m+'" checked> <i class="chipk" style="background:var('+TOYM.col[m]+')"></i>'+TOYM.name[m]+'</label>').join('');
  $('tyMs').addEventListener('change',e=>{const c=e.target.closest('input');if(!c)return;on[c.dataset.m]=c.checked;draw()});
  ['tyM','tyX','tyD'].forEach(id=>$(id).addEventListener('change',draw));
  function draw(){
    const el=$('tyC'),W=RD.width(el),H=Math.min(340,Math.max(240,W*0.5)),l=44,r=12,t=10,b=34,pw=W-l-r,ph=H-t-b;
    const mi=+$('tyM').value,xi=+$('tyX').value,each=$('tyD').value==='a',logX=xi===10;
    const shown=ms.filter(m=>on[m]);
    let xmin=Infinity,xmax=0,ymax=0;
    shown.forEach(m=>Object.values(Y.curves[m]).forEach(rows=>rows.forEach(rw=>{const x=rw[xi];if(logX&&x<=0)return;xmin=Math.min(xmin,x);xmax=Math.max(xmax,x);ymax=Math.max(ymax,rw[mi])})));
    if(!shown.length){el.innerHTML='';return}
    if(mi===1||mi===2)ymax=1;if(mi===3)ymax=Math.max(ymax,tc.distinct);
    if(mi>=4)ymax=Math.min(ymax,mi===4?3:1.5);
    if(!logX)xmin=0;
    const X=v=>logX?l+pw*(Math.log10(v)-Math.log10(xmin))/(Math.log10(xmax)-Math.log10(xmin)):l+pw*v/xmax;
    const Yp=v=>t+ph*(1-Math.min(v,ymax)/ymax);
    let s='';
    for(let k=0;k<=4;k++){const v=ymax*k/4;s+='<line x1="'+l+'" x2="'+(W-r)+'" y1="'+Yp(v)+'" y2="'+Yp(v)+'" stroke="var(--line)"/><text x="'+(l-4)+'" y="'+(Yp(v)+4)+'" text-anchor="end" font-size="10.5" fill="var(--mute)">'+(mi<=2?Math.round(v*100)+'%':v.toFixed(mi===3?1:2))+'</text>'}
    if(logX){for(let e=Math.ceil(Math.log10(xmin));e<=Math.floor(Math.log10(xmax));e++)s+='<text x="'+X(Math.pow(10,e))+'" y="'+(H-18)+'" text-anchor="middle" font-size="10.5" fill="var(--mute)">1e'+e+'</text>'}
    else{[0,.25,.5,.75,1].forEach(f=>s+='<text x="'+X(xmax*f)+'" y="'+(H-18)+'" text-anchor="middle" font-size="10.5" fill="var(--mute)">'+PF.comma(xmax*f)+'</text>')}
    s+='<text x="'+(l+pw/2)+'" y="'+(H-3)+'" text-anchor="middle" font-size="10.5" fill="var(--mute)">'+(logX?'model FLOPs, cumulative':'training step')+'</text>';
    if(mi===1||mi===3){const tv=mi===1?tc.succ:tc.distinct;s+='<line x1="'+l+'" x2="'+(W-r)+'" y1="'+Yp(tv)+'" y2="'+Yp(tv)+'" stroke="var(--ink)" stroke-dasharray="4 4"/><text x="'+(W-r)+'" y="'+(Yp(tv)-4)+'" text-anchor="end" font-size="10.5">teacher</text>'}
    shown.forEach(m=>{const runs=Object.values(Y.curves[m]),c='var('+TOYM.col[m]+')';
      const pts=rows=>rows.filter(rw=>!logX||rw[xi]>0);
      if(each){runs.forEach(rows=>{s+='<path d="'+pts(rows).map((rw,i)=>(i?'L':'M')+X(rw[xi]).toFixed(1)+' '+Yp(rw[mi]).toFixed(1)).join('')+'" fill="none" stroke="'+c+'" stroke-width="1.6"/>'})}
      else{const n=runs[0].length;let up='',dn='',mid='';
        for(let i=0;i<n;i++){const vs=runs.map(rw=>rw[i]?rw[i][mi]:null).filter(v=>v!=null),xs=runs.map(rw=>rw[i]?rw[i][xi]:null).filter(v=>v!=null);
          const x=xs.reduce((a,b)=>a+b,0)/xs.length;if(logX&&x<=0)continue;
          const mu=vs.reduce((a,b)=>a+b,0)/vs.length,lo=Math.min(...vs),hi=Math.max(...vs);
          mid+=(mid?'L':'M')+X(x).toFixed(1)+' '+Yp(mu).toFixed(1);up+=(up?'L':'M')+X(x).toFixed(1)+' '+Yp(hi).toFixed(1);dn=X(x).toFixed(1)+' '+Yp(lo).toFixed(1)+(dn?' L'+dn:'')}
        s+='<path d="'+up+' L'+dn+' Z" fill="'+c+'" opacity=".15"/><path d="'+mid+'" fill="none" stroke="'+c+'" stroke-width="2.2"/>'}});
    el.innerHTML=PF.svg(W,H,'Learning curves of the toy student',s);
    $('tyF').innerHTML=(mi===4?'Reverse KL on the student\'s own routes is what on-policy reverse-KL training minimises; lower means the teacher would write what the student writes.':mi===5?'Forward KL on the teacher\'s routes is what logit KD minimises; lower means the student covers what the teacher writes.':mi===3?'Out of 8 routes sampled per prompt, how many different correct ones; the teacher\'s level is the dashed line.':'Share of routes that are correct, over all '+G.pairs+' prompts ('+(mi===1?'8 samples each at temperature 1':'greedy decoding, one route each')+').')+(mi>=4?' The vertical axis is capped at '+(mi===4?3:1.5)+' nats so the end of training is readable.':'');
  }
  // failure reasons at the end of training
  function reasons(){
    const keys=['no such edge','too long','never arrived','went past the target'];
    let h='<div class="tw"><table class="tbl-s"><thead><tr><th>Method</th><th class="num">correct</th>'+keys.map(k=>'<th class="num">'+k+'</th>').join('')+'</tr></thead><tbody>';
    ms.forEach(m=>{const runs=Object.values(Y.curves[m]).map(rows=>rows[rows.length-1]);const mean=f=>runs.reduce((a,rw)=>a+f(rw),0)/runs.length;
      h+='<tr><td><i class="chipk" style="background:var('+TOYM.col[m]+')"></i>'+TOYM.name[m]+'</td><td class="num">'+PF.pct(mean(rw=>rw[1]),1)+'</td>'+keys.map(k=>'<td class="num">'+PF.pct(mean(rw=>rw[9][k]||0),1)+'</td>').join('')+'</tr>'});
    h+='</tbody></table></div><p class="small mute">Share of all sampled routes at the last step, mean of the seeds. "No such edge": a step to a node that is not a neighbour. "Too long": reaches the target, but in more than the shortest distance plus '+G.slack+'. "Never arrived": stopped (or ran out of room) before the target. "Went past the target": reached it and kept going.</p>';
    $('tyR').innerHTML=h;
  }
  // routes from checkpoints
  // sampled routes are stored as strings of node names plus a one-letter verdict; decode to [[nodes], verdict]
  const IDX={};NM.forEach((n,i)=>IDX[n]=i);
  const dec=a=>a.map(x=>typeof x==='string'?[[...x.slice(0,-1)].map(c=>IDX[c]),Y.samples.ver[x.slice(-1)]]:x);
  Y.samples.teacher=Y.samples.teacher.map(dec);Object.values(Y.samples.methods).forEach(o=>Object.keys(o).forEach(c=>{o[c]=o[c].map(dec)}));
  const SM=Y.samples,CK=SM.ck.filter(c=>Object.values(SM.methods).some(o=>o[c]));
  $('twP').innerHTML=SM.prompts.map((p,i)=>'<option value="'+i+'">'+NM[p[0]]+' to '+NM[p[1]]+'</option>').join('');
  $('twM').innerHTML=ms.filter(m=>SM.methods[m]).map(m=>'<option value="'+m+'"'+(m==='rkl_on'?' selected':'')+'>'+TOYM.name[m]+'</option>').join('');
  const okW=w=>w==='ok';
  const rtxt=(p,rs)=>rs.map(([r,w])=>'<div class="'+(okW(w)?'y':'x')+'">'+NM[p[0]]+' '+r.map(v=>NM[v]||'?').join(' ')+'  '+(okW(w)?'correct':w)+'</div>').join('');
  function wdraw(i){
    const pi=+$('twP').value,m=$('twM').value,c=CK[i],p=SM.prompts[pi];
    const rs=(SM.methods[m][c]||[])[pi]||[],trs=SM.teacher[pi];
    const paths=[];const seen={};
    rs.forEach(([r,w])=>{const key=r.join(',');if(seen[key])return;seen[key]=1;const bad=new Set();let prev=p[0];r.forEach((v,j)=>{if(!G.edges.some(e=>(e[0]===prev&&e[1]===v)||(e[1]===prev&&e[0]===v)))bad.add(j);prev=v});
      paths.push({from:p[0],route:r,upto:r.length,col:okW(w)?'--good':'--bad',bad:okW(w)?null:new Set([...Array(r.length).keys()]),w:okW(w)?3:2,op:.75})});
    TOYG.draw($('twG'),G,{s:p[0],t:p[1],paths,label:'Routes sampled from the student at step '+c});
    const nOk=rs.filter(x=>okW(x[1])).length,nD=new Set(rs.filter(x=>okW(x[1])).map(x=>x[0].join(','))).size;
    $('twH').innerHTML='<b>'+TOYM.name[m]+'</b>, step '+PF.comma(c)+': '+nOk+' of '+rs.length+' correct, '+nD+' distinct';
    $('twL').innerHTML=rtxt(p,rs);$('twT').innerHTML=rtxt(p,trs);
    $('twCt').textContent=c===0?'Step 0: random weights':c===CK[CK.length-1]?'End of training, step '+PF.comma(c):'Step '+PF.comma(c);
    $('twCp').textContent=c===0?'Before any training the student writes nonsense: random nodes, usually not even neighbours.':c===CK[CK.length-1]?(nOk===rs.length?'Every sampled route is correct. ':'Still '+(rs.length-nOk)+' wrong of '+rs.length+'. ')+'The teacher found '+new Set(trs.filter(x=>okW(x[1])).map(x=>x[0].join(','))).size+' distinct correct routes in its 8 samples; this student found '+nD+'.':'Partly trained: '+nOk+' of 8 correct.';
  }
  const AN=RD.anim({card:'tw',ctl:'twC',n:CK.length,ms:1500,label:'Checkpoint',draw:wdraw});
  ['twP','twM'].forEach(id=>$(id).addEventListener('change',()=>AN.redraw()));
  reg(()=>{draw();reasons();AN.redraw()});
  addEventListener('resize',()=>{if($('ty').offsetParent){draw();AN.redraw()}});
  draw();reasons();
})();
