"""Extract the authors' released evolution records into a compact inputs/runs.json that the page ships.

Source: https://regularized-rsi.com/data/evolution.js (window.RRSI_DATA, "Generated by build_data.py from the
raw run directories"), fetched 2026-10-03; 1.25 MB, so only this extract is kept in the repository.
usage: curl -sL https://regularized-rsi.com/data/evolution.js -o $SCRATCH/evolution.js
       python3 mk_runs.py $SCRATCH/evolution.js
Every number is copied, never edited; summaries and critic reasons are only shortened (at a word boundary,
marked with an ellipsis) to keep the page small, and the em-dashes of the records are written as commas (house style). nu (structural novelty) is parsed from the decision text."""
import json, re, sys

src = open(sys.argv[1], encoding='utf-8').read()
D = json.loads(src[src.index('{'):src.rstrip().rstrip(';').rindex('}') + 1])


def short(s, n):
    s = re.sub(r'\s+', ' ', (s or '').replace(' \u2014 ', ', ').replace('\u2014', ', ')).strip()
    if len(s) <= n: return s
    return s[:n].rsplit(' ', 1)[0].rstrip(',;:') + ' ...'


out = []
for r in D['runs']:
    rr = {k: r[k] for k in ('id', 'name', 'domain', 'benchmark', 'policy', 'proposer', 'base', 'evolveSet', 'T', 'm', 'delta', 'budget', 'note', 'summary')}
    rr['denom'] = r['metric']['denom']; rr['unit'] = r['metric']['countLabel']
    rr['heldout'] = r.get('heldout', [])
    rr['traj'] = [[p['t'], p['count'], round(p['C']) if p.get('C') else None] for p in r['trajectory']]
    rr['champ'] = {'add': r['champion']['stat']['add'], 'del': r['champion']['stat']['del'], 'files': len(r['champion']['stat']['files'])}
    cs = []
    for rd in r['rounds']:
        for c in rd['candidates']:
            d = c.get('decision') or {}
            reason = d.get('reason') or ''
            m = re.search(r'\(nu=(\d+)\)', reason)
            fr = c.get('criticFirstReject')
            cs.append({
                't': rd['t'], 'id': c['id'], 'st': c['status'], 'sl': c.get('statusLabel', ''),
                'comp': c.get('components') or [], 'ne': len(c.get('edits') or []),
                'sum': short(c.get('summary'), 300),
                'cv': (c.get('critic') or {}).get('verdict'),
                'fr': short(' '.join(fr['reasons']), 260) if fr and fr.get('reasons') else None,
                'S': d.get('S'), 'n': d.get('count'), 'C': round(d['C']) if d.get('C') else None,
                'dS': d.get('dS'), 'dC': d.get('dC'), 'nu': int(m.group(1)) if m else None,
                'why': short(reason, 330),
                'add': (c.get('diffStat') or {}).get('add'), 'del': (c.get('diffStat') or {}).get('del'),
            })
    rr['c'] = cs
    out.append(rr)
json.dump({'source': 'https://regularized-rsi.com/data/evolution.js', 'fetched': '2026-10-03', 'runs': out},
          open('inputs/runs.json', 'w'), ensure_ascii=False, separators=(',', ':'))
print('runs', len(out), 'candidates', sum(len(r['c']) for r in out), 'bytes', len(json.dumps(out, separators=(',', ':'), ensure_ascii=False).encode()))
