// ---- Numbers to know (t-num): latency ladder, time-budget animation, throughput, availability, estimate calculator ----
// Data: window.NUM_DATA (32_js_num_data.js, generated by src/num/build_data.py). Everything is built lazily the first
// time the tab is shown, so the order of the script parts does not matter. Ids are prefixed nm-.
window.NM=(function(){
  const $=id=>document.getElementById(id);
  const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const tab=()=>$('t-num');
  const visible=()=>{const t=tab();return t&&!t.hidden&&t.offsetParent!==null};
  const W=el=>{const w=el&&el.clientWidth;return w&&w>40?w:Math.max(280,Math.min(880,(document.documentElement.clientWidth||900)-40))};
  // significant-figure formatting without trailing zeros
  function sig(x,n){if(!isFinite(x))return '?';if(x===0)return '0';const a=Math.abs(x);const d=Math.max(0,(n||3)-1-Math.floor(Math.log10(a)));
    let s=x.toFixed(Math.min(d,6));if(s.indexOf('.')>=0)s=s.replace(/0+$/,'').replace(/\.$/,'');
    const p=s.split('.');p[0]=p[0].replace(/\B(?=(\d{3})+(?!\d))/g,',');return p.join('.')}
  function fmtT(sec){const a=Math.abs(sec);
    if(a<1e-6)return sig(sec*1e9)+' ns';if(a<1e-3)return sig(sec*1e6)+' µs';if(a<1)return sig(sec*1e3)+' ms';return sig(sec)+' s'}
  function human(sec){const x=sec*1e9; // seconds on the human scale
    if(x<60)return sig(x,2)+' s';if(x<3600)return sig(x/60,2)+' min';if(x<86400)return sig(x/3600,2)+' h';if(x<86400*365)return sig(x/86400,2)+' days';return sig(x/86400/365,2)+' years'}
  const num=(x,d)=>{if(!isFinite(x))return '?';return x.toLocaleString('en-US',{maximumFractionDigits:d==null?0:d})};
  const money=x=>!isFinite(x)?'?':(x>=100?'$'+num(Math.round(x)):'$'+x.toFixed(2));
  // kinds of source, each with a mark
  const KIND={classic:{n:'Classic (2001 to 2012)',c:'var(--mute)',m:'dia',o:1},ind:{n:'Independent measurement',c:'var(--c1)',m:'circ'},
    vendor:{n:'Vendor or project figure',c:'var(--c2)',m:'sq'},local:{n:'Measured for this page (M1 Pro laptop, 2026-10-04)',c:'var(--c3)',m:'tri'},
    derived:{n:'Derived (formula shown)',c:'var(--c4)',m:'circ',o:1},doc:{n:'Provider documentation, price list or standard',c:'var(--c6)',m:'dia'},
    spec:{n:'Vendor peak specification',c:'var(--c5)',m:'sq',o:1}};
  function mark(k,x,y,r){x=+x;y=+y;const K=KIND[k]||KIND.doc,c=K.c,f=K.o?'none':c,sw=K.o?1.6:0;r=r||5;
    if(K.m==='circ')return '<circle cx="'+x+'" cy="'+y+'" r="'+r+'" fill="'+f+'" stroke="'+c+'" stroke-width="'+sw+'"/>';
    if(K.m==='sq')return '<rect x="'+(x-r+.5)+'" y="'+(y-r+.5)+'" width="'+(2*r-1)+'" height="'+(2*r-1)+'" fill="'+f+'" stroke="'+c+'" stroke-width="'+sw+'"/>';
    if(K.m==='tri')return '<path d="M'+x+' '+(y-r-.5)+'L'+(x+r)+' '+(y+r-1)+'L'+(x-r)+' '+(y+r-1)+'Z" fill="'+f+'"/>';
    return '<path d="M'+x+' '+(y-r-.5)+'L'+(x+r)+' '+y+'L'+x+' '+(y+r+.5)+'L'+(x-r)+' '+y+'Z" fill="'+f+'" stroke="'+c+'" stroke-width="'+(K.o?1.6:0)+'"/>'}
  const kchip=k=>'<span class="nm-k" style="border-color:'+(KIND[k]||KIND.doc).c+'">'+esc((KIND[k]||KIND.doc).n)+'</span>';
  function srcLink(id,short){const s=NUM_DATA.sources[id];if(!s)return '';const t=esc(short?s.t.split(/, "| \(|: /)[0]:s.t)+(s.d?' ('+esc(s.d)+')':'');
    return s.u?'<a href="'+esc(s.u)+'" target="_blank" rel="noopener noreferrer">'+t+'</a>':t}
  const seg=(el,f)=>el.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!el.contains(b))return;el.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));f(b.dataset.m)});
  return {$,esc,visible,W,sig,fmtT,human,num,money,KIND,mark,kchip,srcLink,seg};
})();

// ---- the latency ladder ----
NM.ladder=(function(){
  const {$,esc,W,fmtT,human,mark,kchip,srcLink,KIND}=NM;
  const st={grp:'all',cl:true,hu:false,sel:'fsync_consumer'};
  const LO=-10,HI=3; // log10 seconds: 0.1 ns to 1000 s
  function xs(w){const pad=8;return v=>pad+(Math.log10(v)-LO)/(HI-LO)*(w-2*pad)}
  function tickLabel(e){if(st.hu)return human(Math.pow(10,e)).replace('.0 ',' ');const u=['ns','µs','ms','s'];if(e>=0)return Math.pow(10,e)+' s';
    const k=Math.floor((e+9)/3),r=(e+9)-3*k;return Math.pow(10,r)+' '+u[k]}
  function axis(w){const x=xs(w);let s='';const every=w<520?3:(w<760?2:1);
    for(let e=LO;e<=HI;e++){const X=x(Math.pow(10,e)).toFixed(1);s+='<line x1="'+X+'" x2="'+X+'" y1="18" y2="24" stroke="var(--mute)"/>';
      if((e+9)%every===0&&e>-10)s+='<text x="'+X+'" y="13" font-size="10.5" text-anchor="'+(e===HI?'end':'middle')+'" fill="var(--mute)">'+tickLabel(e)+'</text>'}
    return '<svg viewBox="0 0 '+w+' 26" width="'+w+'" height="26" aria-hidden="true">'+s+'<line x1="8" x2="'+(w-8)+'" y1="24" y2="24" stroke="var(--line)"/></svg>'}
  function strip(r,w){const x=xs(w);let s='';
    for(let e=LO;e<=HI;e++){const X=x(Math.pow(10,e)).toFixed(1);s+='<line x1="'+X+'" x2="'+X+'" y1="0" y2="20" stroke="var(--line)"/>'}
    const pts=r.pts.filter(p=>st.cl||p.k!=='classic');
    pts.forEach(p=>{if(p.lo!=null){const c=(KIND[p.k]||KIND.doc).c;s+='<line x1="'+x(p.lo).toFixed(1)+'" x2="'+x(p.hi).toFixed(1)+'" y1="10" y2="10" stroke="'+c+'" stroke-width="3" stroke-linecap="round" opacity=".55"/>'}});
    pts.forEach(p=>{s+=mark(p.k,x(p.v).toFixed(1),10,p.k==='classic'?6:5)});
    return '<svg viewBox="0 0 '+w+' 20" width="'+w+'" height="20" role="img" aria-label="'+esc(r.n)+' on a log time axis">'+s+'</svg>'}
  const val=v=>st.hu?human(v):fmtT(v);
  function summary(r){const cur=r.pts.filter(p=>p.k!=='classic').map(p=>'<b>'+val(p.v)+'</b> '+esc(p.label||''));
    const cl=r.pts.filter(p=>p.k==='classic');let s=cur.join(' · ');
    if(st.cl&&cl.length)s+=(s?' · ':'')+'classic '+cl.map(p=>val(p.v)+' ('+esc(p.label)+')').join(', ');return s}
  function detail(r){
    return '<div class="nm-det" id="nm-lad-det" aria-live="polite"><h3>'+esc(r.n)+'</h3><p>'+esc(r.w)+'</p><ul>'+r.pts.map(p=>'<li>'+kchip(p.k)+'<b>'+fmtT(p.v)+'</b>'+(p.lo!=null?' (range '+fmtT(p.lo)+' to '+fmtT(p.hi)+')':'')+
      ' <span class="mute">('+human(p.v)+' on the human scale)</span>. '+esc(p.note||p.label||'')+' <span class="small">Source: '+srcLink(p.src)+'</span></li>').join('')+'</ul></div>'}
  function render(){const box=$('nm-lad');if(!box)return;const w=Math.round(W(box));let h='<div class="nm-axis">'+axis(w)+'</div>';
    NUM_DATA.groups.forEach(([g,gn])=>{if(st.grp!=='all'&&st.grp!==g)return;h+='<div class="nm-grp">'+esc(gn)+'</div>';
      NUM_DATA.ladder.filter(r=>r.g===g).forEach(r=>{h+='<div class="nm-rung'+(r.id===st.sel?' sel':'')+'" role="button" tabindex="0" data-id="'+r.id+'" aria-pressed="'+(r.id===st.sel)+'"><div class="nm-rn">'+esc(r.n)+'</div>'+strip(r,w)+'<div class="nm-rs">'+summary(r)+'</div></div>'+(r.id===st.sel?detail(r):'')})});
    box.innerHTML=h}
  function init(){
    const pick=e=>{const d=e.target.closest('.nm-rung');if(!d)return;st.sel=st.sel===d.dataset.id?'':d.dataset.id;render();const det=$('nm-lad-det');if(det&&det.getBoundingClientRect().bottom>innerHeight)det.scrollIntoView({block:'nearest'})};
    $('nm-lad').addEventListener('click',pick);
    $('nm-lad').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick(e)}});
    NM.seg($('nm-lad-grp'),m=>{st.grp=m;const r=NUM_DATA.ladder.find(x=>x.id===st.sel);if(m!=='all'&&r&&r.g!==m){st.sel=NUM_DATA.ladder.find(x=>x.g===m).id}render()});
    $('nm-lad-cl').addEventListener('change',e=>{st.cl=e.target.checked;render()});
    $('nm-lad-hu').addEventListener('change',e=>{st.hu=e.target.checked;$('nm-hu-note').hidden=!st.hu;render()});
    // legend
    $('nm-leg').innerHTML=Object.keys(KIND).map(k=>'<span><svg width="14" height="14" viewBox="0 0 14 14" aria-hidden="true">'+NM.mark(k,7,7,k==='classic'?6:5)+'</svg>'+esc(KIND[k].n)+'</span>').join('');
    render()}
  return {init,render,st};
})();

// ---- one request's time budget, before and after (step animation, RD.anim controller) ----
NM.budget=(function(){
  const {$,esc,W,sig}=NM;
  const COL={net:'var(--c1)',app:'var(--dim)',db:'var(--c3)',gpu:'var(--c4)',q:'var(--c6)'};
  const CLN={net:'network',app:'your code',db:'database or cache',gpu:'model',q:'queue'};
  let sc=null,an=null;
  // timeline: request-lane segments laid end to end; worker-lane segments start when the queue write ends
  function lay(list){let t=0,qEnd=0;const out=[];list.forEach(s=>{if(s.lane==='bg')return;out.push(Object.assign({t0:t},s));t+=s.v;if(s.c==='q')qEnd=t});
    let b=qEnd;list.filter(s=>s.lane==='bg').forEach(s=>{out.push(Object.assign({t0:b},s));b+=s.v});return {segs:out,total:t,end:Math.max(t,b)}}
  const steps=()=>1+sc.before.length+sc.after.length+1;
  function draw(i){if(!sc)return;const el=$('nm-bud-svg');const w=Math.round(W(el));const B=lay(sc.before),A=lay(sc.after);
    const nb=sc.before.length,na=sc.after.length;const showB=Math.max(0,Math.min(nb,i)),showA=Math.max(0,Math.min(na,i-nb));
    const hasBg=sc.after.some(s=>s.lane==='bg');const L=w<520?0:64,pad=8,max=Math.max(B.end,A.end)*1.04;const X=t=>L+(t/max)*(w-L-pad);
    const rows=[['Before',B.segs.filter(s=>s.lane!=='bg'),showB,0],['After',A.segs.filter(s=>s.lane!=='bg'),showA,0]];
    if(hasBg)rows.push(['After the reply (worker)',A.segs.filter(s=>s.lane==='bg'),Math.max(0,showA-A.segs.filter(s=>s.lane!=='bg').length),1]);
    const rh=w<520?44:34;let s='',y=8;
    // ms grid
    const stepMs=[10,20,50,100,200,500].find(v=>max/v<=(w<520?5:8))||500;
    for(let t=0;t<=max;t+=stepMs){const x=X(t).toFixed(1);s+='<line x1="'+x+'" x2="'+x+'" y1="4" y2="'+(rows.length*rh+8)+'" stroke="var(--line)"/><text x="'+x+'" y="'+(rows.length*rh+20)+'" font-size="10" text-anchor="'+(t===0?'start':'middle')+'" fill="var(--mute)">'+t+(t===0?' ms':'')+'</text>'}
    rows.forEach(([nm,segs,k,bg],ri)=>{const ty=w<520?y+10:y+16;s+='<text x="'+(w<520?L:0)+'" y="'+(w<520?y+8:ty+4)+'" font-size="11.5" font-weight="600">'+esc(nm)+'</text>';
      const by=w<520?y+13:y+5,bh=w<520?24:24;
      segs.forEach((g,j)=>{const on=j<k;const x0=X(g.t0),x1=X(g.t0+g.v),ww=Math.max(1.5,x1-x0-1);
        s+='<rect x="'+x0.toFixed(1)+'" y="'+by+'" width="'+ww.toFixed(1)+'" height="'+bh+'" rx="3" fill="'+COL[g.c]+'" opacity="'+(on?(bg?.55:1):.08)+'"'+(g.ill&&on?' stroke="var(--mute)" stroke-dasharray="3 2"':'')+'><title>'+esc(g.lab)+': '+sig(g.v)+' ms</title></rect>';
        if(on&&ww>34)s+='<text x="'+(x0+ww/2).toFixed(1)+'" y="'+(by+16)+'" font-size="10.5" text-anchor="middle" fill="var(--bg)">'+sig(g.v,2)+'</text>'});
      if(k>0&&k>=segs.length&&!bg){const tot=segs.reduce((a,g)=>a+g.v,0);const xe=X(tot);s+='<text x="'+Math.min(w-pad,xe+4).toFixed(1)+'" y="'+(by-2)+'" font-size="11" text-anchor="'+(xe+60>w?'end':'start')+'" font-weight="600">'+sig(tot)+' ms</text>'}
      y+=rh});
    el.innerHTML='<svg viewBox="0 0 '+w+' '+(rows.length*rh+26)+'" width="'+w+'" height="'+(rows.length*rh+26)+'" role="img" aria-label="Time budget of one request before and after: '+esc(sc.n)+'">'+s+'</svg>';
    // caption
    let cap;if(i===0)cap='Press play, or step through: each bar is one piece of the wait, first before the change, then after it.';
    else if(i<=nb){const g=sc.before[i-1];cap='<b>Before, step '+i+' of '+nb+': '+esc(g.lab)+'</b> ('+sig(g.v)+' ms, '+CLN[g.c]+(g.ill?', illustrative':'')+'). '+esc(g.note||'')}
    else if(i<=nb+na){const g=sc.after[i-nb-1];cap='<b>After, step '+(i-nb)+' of '+na+': '+esc(g.lab)+'</b> ('+sig(g.v)+' ms, '+CLN[g.c]+(g.ill?', illustrative':'')+(g.lane==='bg'?', not waited for by the user':'')+'). '+esc(g.note||'')}
    else cap='<b>Result.</b> The user waited '+sig(B.total)+' ms before and '+sig(A.total)+' ms after: '+Math.round((1-A.total/B.total)*100)+'% less. '+esc(sc.lesson);
    $('nm-bud-cap').innerHTML=cap;
    const sum=(l,n)=>l.filter(g=>g.lane!=='bg').slice(0,n).reduce((a,g)=>a+g.v,0);
    const bs=sum(sc.before,showB),as=sum(sc.after,showA),done=i>nb+na;
    $('nm-bud-cnt').innerHTML=NM_stat('User waits, before',sig(bs)+' ms',showB===nb?'complete':'so far')+NM_stat('User waits, after',sig(as)+' ms',showA>=sc.after.filter(g=>g.lane!=='bg').length?'complete':'so far')+
      NM_stat('Saved',done?sig(B.total-A.total)+' ms':'...',done?Math.round((1-A.total/B.total)*100)+'% of the wait':'after both are drawn');
    $('nm-bud-card').dataset.totals=JSON.stringify({id:sc.id,before:+B.total.toFixed(2),after:+A.total.toFixed(2)})}
  function NM_stat(k,v,d){return '<div class="stat"><div class="k">'+k+'</div><div class="v">'+v+'</div><div class="d">'+d+'</div></div>'}
  function setSc(id){sc=NUM_DATA.budget.find(b=>b.id===id);$('nm-bud-q').innerHTML='<b>'+esc(sc.n)+'.</b> '+esc(sc.q);$('nm-bud-lesson').innerHTML='<b>Key colours:</b> '+Object.keys(COL).map(c=>'<span style="display:inline-block;width:10px;height:10px;border-radius:2px;background:'+COL[c]+';margin:0 3px 0 6px"></span>'+CLN[c]).join('')+'. Dashed outline: illustrative time for your own code.';
    if(an){an.reset(steps());draw(0)}}
  function init(){sc=NUM_DATA.budget[0];setSc(sc.id);
    an=RD.anim({card:'nm-bud-card',ctl:'nm-bud-ctl',n:steps(),draw:i=>draw(i),ms:1500,label:'Animation step'});
    NM.seg($('nm-bud-sc'),m=>{setSc(m);an.play()})}
  return {init,redraw:()=>an&&an.redraw(),lay};
})();

// ---- throughput, capacity and prices ----
NM.thr=(function(){
  const {$,esc,num,money,sig,kchip,srcLink}=NM;
  let test='db';
  function app(){const D=NUM_DATA.thr.app;const rows=D.rows.filter(r=>r[test]).sort((a,b)=>b[test]-a[test]);const mx=rows[0][test];
    $('nm-app').innerHTML=rows.map(r=>'<div class="row"><span class="nm" title="'+esc(r.fw+', '+r.lang)+'">'+esc(r.fw)+' <span class="mute small">'+esc(r.lang)+'</span></span><span class="track"><span class="fill" style="width:'+(r[test]/mx*100).toFixed(1)+'%;background:var(--c1)"></span></span><span class="val">'+(r[test]>=1e6?sig(r[test]/1e6,3)+' M':Math.round(r[test]/1000)+' k')+'</span></div>').join('')+
      '<p class="small mute">Requests per second at the best of 6 concurrency levels (16 to 512 connections), whole server. '+kchip('ind')+' Source: '+srcLink('te23')+'.</p>';
    const so=D.so;$('nm-app-so').innerHTML='<div class="t">Real endpoints are far heavier</div>A real request authenticates, runs several queries, calls other services and renders a page. Stack Overflow in 2016 served '+num(so.req_day)+' requests in a day with '+so.servers+' primary web servers: '+num(so.req_day/86400)+' a second in total, about '+num(so.per_server)+' per server on average, at low CPU, because servers are sized for peaks and for losing a machine ('+srcLink('so2016')+'). Measure your own endpoint; use these ceilings only to see which frameworks are in the same league.'}
  function dbq(){const T=NUM_DATA.thr;const rows=[].concat(T.pg.map(r=>Object.assign({grp:'PostgreSQL'},r)),T.redis.map(r=>Object.assign({grp:'Redis, Valkey'},r)),T.kafka.map(r=>Object.assign({grp:'Kafka (queue)'},r)));
    $('nm-dbq').innerHTML='<thead><tr><th>What</th><th class="num">Figure</th><th>Kind, source</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+esc(r.lab)+(r.note?'<br><small>'+esc(r.note)+'</small>':'')+'</td><td class="num" data-l="Figure">'+num(r.v)+' '+esc(r.unit)+'</td><td data-l="Source">'+kchip(NUM_DATA.sources[r.src].who)+'<span class="small">'+srcLink(r.src,1)+'</span></td></tr>').join('')+'</tbody>'}
  function gpu(){const P=NUM_DATA.prices;const h100=P.find(p=>/Lambda.*H100/.test(p.lab)).v,b200=P.find(p=>/Lambda.*B200/.test(p.lab)).v;
    const price=lab=>/B200/.test(lab)?b200:(/H100/.test(lab)?h100:null);
    $('nm-gpu').innerHTML='<thead><tr><th>Model, GPUs, request shape</th><th class="num">Output tokens/s per GPU</th><th class="num">Total across the GPUs of the run</th><th class="num">$ per million output tokens if always busy</th></tr></thead><tbody>'+
      NUM_DATA.thr.gpu.map(r=>{const per=r.per,p=price(r.lab);const c=p?p/(per*3600)*1e6:null;
        return '<tr><td>'+esc(r.lab)+(r.note?'<br><small>'+esc(r.note)+'</small>':'')+'<br>'+kchip(NUM_DATA.sources[r.src].who)+'<span class="small">'+srcLink(r.src,1)+'</span></td><td class="num" data-l="Output tokens/s per GPU">'+num(per)+'</td><td class="num" data-l="Total, '+r.gpus+' GPU'+(r.gpus>1?'s':'')+'">'+num(per*r.gpus)+' <small>('+r.gpus+' GPU'+(r.gpus>1?'s':'')+')</small></td><td class="num" data-l="$ per M tokens, always busy">'+(c?money(c)+'<br><small>at '+money(p)+'/GPU-hour</small>':'<small>no on-demand price read</small>')+'</td></tr>'}).join('')+
      '</tbody>';}
  function prices(){const H=NUM_DATA.hours_month;$('nm-price').innerHTML='<thead><tr><th>Machine</th><th class="num">$ / hour</th><th class="num">$ / GPU-hour</th><th class="num">$ / month (730 h)</th><th>Source</th></tr></thead><tbody>'+
      NUM_DATA.prices.map(p=>'<tr><td>'+esc(p.lab)+'</td><td class="num" data-l="$ / hour">'+money(p.v)+'</td><td class="num" data-l="$ / GPU-hour">'+(p.gpu?money(p.v/p.gpu):'n/a')+'</td><td class="num" data-l="$ / month">'+money(p.v*H)+'</td><td class="small" data-l="Source">'+srcLink(p.src,1)+'</td></tr>').join('')+'</tbody>';
    const E=NUM_DATA.egress;$('nm-egress').innerHTML='<b>Egress</b> (data sent out of the cloud to users): '+esc(E.note)+' Source: '+srcLink(E.src)+'. Sending 1 TB a month costs about '+money(NM.egressCost(1000))+'; 100 TB about '+money(NM.egressCost(100000))+'. Data coming in is free, which is why moving data out of a cloud is the expensive direction.'}
  function init(){NM.seg($('nm-app-t'),m=>{test=m;app()});app();dbq();gpu();prices()}
  return {init};
})();
// AWS internet egress, tiered; gb = gigabytes in the month; the first 100 GB a month are free (global free tier)
NM.egressCost=function(gb){const E=NUM_DATA.egress;let rest=Math.max(0,gb-100),prev=0,c=0;
  for(const [end,p] of E.tiers){const cap=end==null?Infinity:end-prev;const take=Math.min(rest,cap);c+=take*p;rest-=take;prev=end;if(rest<=0)break}return c};

// ---- availability arithmetic ----
NM.avail=(function(){
  const {$,esc,num,sig}=NM;
  const Y=365*24*60,M=30*24*60,WK=7*24*60;
  function dur(min){if(min<1)return sig(min*60,2)+' s';if(min<120)return sig(min,3)+' min';if(min<48*60)return sig(min/60,3)+' h';return sig(min/60/24,3)+' days'}
  const pct=a=>(Math.round(a*1e6)/1e4).toString()+'%';
  function nines(){const L=NUM_DATA.avail.levels;$('nm-nines').innerHTML='<thead><tr><th>Availability</th><th class="num">Down per year</th><th class="num">Per 30-day month</th><th class="num">Per week</th></tr></thead><tbody>'+
      L.map(a=>'<tr><td>'+pct(a)+'</td><td class="num">'+dur((1-a)*Y)+'</td><td class="num">'+dur((1-a)*M)+'</td><td class="num">'+dur((1-a)*WK)+'</td></tr>').join('')+'</tbody>';
    const s=$('nm-av');s.max=L.length-1;
    const upd=()=>{const a=L[+s.value];$('nm-av-v').textContent=pct(a);$('nm-av-out').innerHTML=st('Allowed downtime a year',dur((1-a)*Y),'(1 − '+pct(a)+') × 525,600 min')+st('Per 30-day month',dur((1-a)*M),'')+st('Failed requests per million',num((1-a)*1e6,1),'if measured by requests')};
    s.addEventListener('input',upd);upd()}
  const st=(k,v,d)=>'<div class="stat"><div class="k">'+k+'</div><div class="v">'+v+'</div><div class="d">'+(d||'')+'</div></div>';
  const OPTS=[0.99,0.995,0.999,0.9995,0.9999,0.99999];
  function chain(){const C=NUM_DATA.avail.chain;const box=$('nm-chain');
    box.innerHTML='<b class="small">Component (in series)</b><b class="small">Availability</b><b class="small">Copies</b>'+C.map((c,i)=>'<label><input type="checkbox" data-i="'+i+'" class="nm-cin" checked> '+esc(c.n)+'</label><select data-i="'+i+'" class="nm-ca" aria-label="Availability of '+esc(c.n)+'">'+OPTS.map(o=>'<option value="'+o+'"'+(o===c.a?' selected':'')+'>'+pct(o)+'</option>').join('')+'</select><select data-i="'+i+'" class="nm-cr" aria-label="Copies of '+esc(c.n)+'"><option>1</option><option>2</option><option>3</option></select>').join('');
    box.addEventListener('change',calc);calc()}
  function chainResult(){const C=NUM_DATA.avail.chain;const box=$('nm-chain');let tot=1;const parts=[];
    C.forEach((c,i)=>{if(!box.querySelector('.nm-cin[data-i="'+i+'"]').checked)return;const a=+box.querySelector('.nm-ca[data-i="'+i+'"]').value,n=+box.querySelector('.nm-cr[data-i="'+i+'"]').value;
      const e=1-Math.pow(1-a,n);tot*=e;parts.push(n>1?'(1 − (1 − '+pct(a)+')<sup>'+n+'</sup>)':pct(a))});return {tot,parts}}
  function calc(){const r=chainResult();$('nm-chain-out').innerHTML=st('Whole request',pct(r.tot),r.parts.length+' components in series')+st('Down per year',dur((1-r.tot)*Y),'')+st('Nines',sig(-Math.log10(1-r.tot),2),'−log10(1 − availability)');
    $('nm-chain-f').innerHTML='<div class="eq">'+(r.parts.join(' × ')||'1')+' = '+pct(r.tot)+'</div>';$('nm-chain-out').dataset.tot=r.tot}
  function budget(){const upd=()=>{const slo=+$('nm-eb-slo').value,req=Math.max(0,+$('nm-eb-req').value||0);
      $('nm-eb-out').innerHTML=st('Failures allowed a day',num(req*(1-slo)),num(req)+' × (1 − '+pct(slo)+')')+st('Per 30 days',num(req*(1-slo)*30),'')+st('As full downtime',dur((1-slo)*M)+' a month','if everything failed at once')};
    $('nm-eb-slo').addEventListener('change',upd);$('nm-eb-req').addEventListener('input',upd);upd();
    const S=NUM_DATA.avail.sre,X=NUM_DATA.avail.extra9;const yr=(1-X.slo)*Y,deps=X.deps*(1-X.dep_a)*Y;
    $('nm-eb-ex').innerHTML='<div class="t">Two worked examples from Google</div>'+
      '<p>"A system that serves 2.5M requests in a day with a daily availability target of 99.99% can serve up to 250 errors": '+num(S.req_day)+' × 0.01% = '+num(S.req_day*(1-S.slo))+' ('+NM.srcLink(S.src)+').</p>'+
      '<p><b>The rule of the extra 9:</b> "A service cannot be more available than the intersection of all its critical dependencies", so Google asks each critical dependency for one more nine than the service. A 99.99% service may be down '+sig(yr,4)+' minutes a year; five independent dependencies at 99.999% use '+X.deps+' × 0.001% × 525,600 = '+sig(deps,3)+' minutes of it, leaving about '+Math.round(yr-deps)+' minutes for the service\'s own failures (the article rounds first: 53 − 26 = 27; '+NM.srcLink(X.src)+').</p>'}
  function init(){nines();chain();budget()}
  return {init,chainResult};
})();

// ---- estimate calculator with drills ----
NM.est=(function(){
  const {$,esc,num,money,sig}=NM;
  const F=[ // key, label, group, step
    ['dau','Daily active users (or events a day, with 1 per user)','t',1],['per','Requests per user per day','t',1],['peak','Peak factor (busiest second / average)','t',0.5],
    ['srv','Requests/s one app server handles (0 = skip)','t',10],['srvp','App server price, $/hour','t',0.01],['resp','Average response size, KB (0 = skip)','t',0.1],
    ['wfrac','Share of requests that store data (0 = skip)','s',0.05],['wbytes','Bytes stored per write','s',100],['rep','Copies kept (replication)','s',1],
    ['msgs','Chat messages per user per day (0 = skip)','g',1],['intok','Input tokens per message (prompt and history)','g',100],['outtok','Output tokens per reply','g',10],
    ['gtok','GPU throughput, output tokens/s per GPU','g',10],['derate','Share of that throughput usable at chat speed','g',0.05],['gpup','GPU price, $/GPU-hour','g',0.01]];
  const G={t:'Traffic and servers',s:'Storage',g:'Chat on GPUs'};
  let cur='chat';
  function inputs(){let h='';Object.keys(G).forEach(g=>{h+='<fieldset class="nm-fs"><legend>'+G[g]+'</legend><div class="nm-est">'+F.filter(f=>f[2]===g).map(f=>'<label>'+esc(f[1])+'<input type="number" id="nm-i-'+f[0]+'" step="'+f[3]+'" min="0"></label>').join('')+'</div></fieldset>'});$('nm-est-in').innerHTML=h;
    F.forEach(f=>$('nm-i-'+f[0]).addEventListener('input',calc))}
  function read(){const v={};F.forEach(f=>{const x=parseFloat($('nm-i-'+f[0]).value);v[f[0]]=isFinite(x)&&x>=0?x:0});return v}
  function load(id){cur=id;const d=NUM_DATA.drills.find(x=>x.id===id);const v=Object.assign({},NUM_DATA.defaults,d.set);F.forEach(f=>{$('nm-i-'+f[0]).value=v[f[0]]});
    $('nm-drills').querySelectorAll('button').forEach(b=>b.classList.toggle('on',b.dataset.id===id));
    $('nm-drill-q').innerHTML='<div class="t">Drill: '+esc(d.n)+'</div>'+esc(d.ask)+' <span class="mute small">Try it on paper first, then read the steps.</span>';calc()}
  // the model; recompute.py implements the same formulas
  function model(v){const r={};const H=NUM_DATA.hours_month;
    r.daily=v.dau*v.per;r.avg=r.daily/86400;r.peak=r.avg*v.peak;
    r.servers=v.srv>0?Math.ceil(r.peak/v.srv):0;r.srvCost=r.servers*v.srvp*H;
    r.storeYr=v.dau*v.per*v.wfrac*v.wbytes*365*v.rep;
    r.bwAvg=r.avg*v.resp*1000*8;r.bwPeak=r.bwAvg*v.peak;r.gbMonth=r.avg*v.resp*1000*86400*30/1e9;r.egress=NM.egressCost(r.gbMonth);
    r.outDay=v.dau*v.msgs*v.outtok;r.inDay=v.dau*v.msgs*v.intok;r.outAvg=r.outDay/86400;r.outPeak=r.outAvg*v.peak;
    r.perGpu=v.gtok*v.derate;r.gpus=v.msgs>0&&r.perGpu>0?Math.ceil(r.outPeak/r.perGpu):0;r.gpuCost=r.gpus*v.gpup*H;
    r.outMonthM=r.outDay*H/24/1e6;r.costPerM=r.outMonthM>0?r.gpuCost/r.outMonthM:0;r.costPerMFull=v.gtok>0?v.gpup/(v.gtok*3600)*1e6:0;r.gpusAvgFull=v.gtok>0?r.outAvg/v.gtok:0;
    r.total=r.srvCost+r.egress+r.gpuCost;return r}
  const st=(k,v,d)=>'<div class="stat"><div class="k">'+k+'</div><div class="v">'+v+'</div><div class="d">'+(d||'')+'</div></div>';
  const bits=b=>b>=1e9?sig(b/1e9,3)+' Gbit/s':sig(b/1e6,3)+' Mbit/s';
  const bytes=b=>b>=1e12?sig(b/1e12,3)+' TB':(b>=1e9?sig(b/1e9,3)+' GB':sig(b/1e6,3)+' MB');
  const f=s=>'<span class="nm-f">'+s+'</span>';
  function calc(){const v=read(),r=model(v);const out=[],S=[];
    out.push(st('Average requests/s',num(r.avg,r.avg<10?1:0),num(r.daily)+' a day / 86,400 s'),st('Peak requests/s',num(r.peak),'× '+v.peak+' peak factor'));
    S.push('Requests a day: '+f(num(v.dau)+' users × '+v.per+' = '+num(r.daily))+'.');
    S.push('Average per second: '+f(num(r.daily)+' / 86,400 s = '+num(r.avg,1)+' req/s')+'. A day has 86,400 seconds; about 100,000 is a handy round number for mental arithmetic.');
    S.push('Peak: traffic is not flat (people sleep, events spike), so size for the busiest second: '+f(num(r.avg,1)+' × '+v.peak+' = '+num(r.peak)+' req/s')+'.');
    if(v.srv>0){out.push(st('App servers at peak',num(r.servers),money(r.srvCost)+' a month'));S.push('Servers: '+f('ceil('+num(r.peak)+' / '+num(v.srv)+') = '+r.servers)+', costing '+f(r.servers+' × '+money(v.srvp)+'/h × 730 h = '+money(r.srvCost)+' a month')+'. Add at least one spare so losing a machine at peak is survivable.')}
    if(v.wfrac>0){out.push(st('Storage per year',bytes(r.storeYr),v.rep+' copies'));S.push('Storage: '+f(num(v.dau)+' × '+v.per+' × '+v.wfrac+' writes × '+num(v.wbytes)+' B × 365 × '+v.rep+' copies = '+bytes(r.storeYr)+' a year')+'.')}
    if(v.resp>0){out.push(st('Bandwidth out',bits(r.bwAvg)+' avg',bits(r.bwPeak)+' at peak'),st('Egress bill (AWS list)',money(r.egress)+'/month',sig(r.gbMonth,3)+' GB a month'));
      S.push('Bandwidth: '+f(num(r.avg,1)+' req/s × '+v.resp+' KB × 8 bits = '+bits(r.bwAvg))+' on average, '+bits(r.bwPeak)+' at peak.');
      S.push('Egress: '+f(sig(r.gbMonth,4)+' GB a month')+' sent to the internet; AWS charges nothing for the first 100 GB, then $0.09/GB up to 10 TB, $0.085 to 50 TB, $0.07 to 150 TB, $0.05 beyond: '+f(money(r.egress)+' a month')+'.')}
    if(v.msgs>0){out.push(st('Output tokens/s at peak',num(r.outPeak),num(r.outAvg)+' on average'),st('GPUs at peak',num(r.gpus),money(r.gpuCost)+' a month'),st('Cost per million output tokens',money(r.costPerM),'provisioned for peak, all month'));
      S.push('Tokens: '+f(num(v.dau)+' × '+v.msgs+' messages × '+v.outtok+' output tokens = '+num(r.outDay)+' a day')+' ('+num(r.inDay)+' input tokens a day ride along: the GPU figure used assumes requests of a similar shape), so '+f(num(r.outAvg)+' tokens/s')+' on average and '+f(num(r.outPeak))+' at peak.');
      S.push('Per GPU at chat speed: '+f(num(v.gtok)+' × '+v.derate+' = '+num(r.perGpu)+' tokens/s')+'. The maximum-throughput figure runs the GPU flat out with slow per-user streams; the derate keeps replies quick.');
      S.push('GPUs: '+f('ceil('+num(r.outPeak)+' / '+num(r.perGpu)+') = '+r.gpus)+', costing '+f(r.gpus+' × '+money(v.gpup)+' × 730 h = '+money(r.gpuCost)+' a month')+'.');
      S.push('Cost per million output tokens: '+f(money(r.gpuCost)+' / '+sig(r.outMonthM,4)+' M tokens = '+money(r.costPerM))+'. If every GPU ran flat out all month it would be '+f(money(v.gpup)+' / ('+num(v.gtok)+' × 3,600) × 10⁶ = '+money(r.costPerMFull))+'.')}
    if(r.total>0)out.push(st('Total, per month',money(r.total),'servers + egress + GPUs; storage and staff not included'));
    $('nm-est-out').innerHTML=out.join('');$('nm-est-steps').innerHTML=S.map(s=>'<li>'+s+'</li>').join('');
    $('nm-est-out').dataset.json=JSON.stringify(Object.assign({drill:cur},r));check(v,r)}
  function check(v,r){const d=NUM_DATA.drills.find(x=>x.id===cur);const c=d.check;let h='<div class="t">Sanity check against a real figure</div><p>'+esc(c.text)+' Source: '+NM.srcLink(c.src)+'.</p>';
    const vs=(mine,real,what)=>{const ratio=mine/real;const ok=ratio>0.7&&ratio<1.4;return '<p>'+what+': this estimate gives <b>'+num(mine)+'</b>, the published figure is <b>'+num(real)+'</b> ('+sig(ratio,2)+'×): <span class="'+(ok?'nm-ok':'nm-bad')+'">'+(ok?'within 30 to 40%, a good estimate':'far off: find the assumption that is wrong')+'</span>.</p>'};
    if(cur==='tw'){h+=vs(r.avg,c.avg,'Average tweets per second')+vs(r.peak,c.peak,'Peak')}
    else if(cur==='so'){h+=vs(r.servers,c.servers,'Web servers')+'<p>Bandwidth: '+bits(r.bwAvg)+' on average for HTTP responses; the whole site sent 3.08 TB that day, '+bits(3.084e12*8/86400)+' on average, so the HTTP responses are about '+Math.round(1.24/3.08*100)+'% of what left the building.</p>'}
    else if(cur==='chat'){const A=NUM_DATA.api;const inR=r.costPerM>=A.out_lo&&r.costPerM<=A.out_hi;
      h+='<p>Your cost per million output tokens: <b>'+money(r.costPerM)+'</b> provisioned for peak, <b>'+money(r.costPerMFull)+'</b> if the GPUs were always busy. API providers charge <b>'+money(A.out_lo)+' to '+money(A.out_hi)+'</b> per million output tokens for '+esc(A.model)+' ('+A.n+' providers): <span class="'+(inR?'nm-ok':'nm-bad')+'">'+(inR?'inside the range, though toward its top':'outside the range')+'</span>.</p><p>Why your number is several times the always-busy cost: a provider pools thousands of customers, so its GPUs stay busy around the clock; one product sized for its own peak leaves most GPUs idle at night. Raise the peak factor to 3 and the cost leaves the range. At average load and full throughput you would need only '+sig(r.gpusAvgFull,3)+' GPUs. Utilisation, not the GPU price, decides the bill, which is why a small product usually starts on an API.</p>'}
    else if(cur==='store'){h+='<p>'+bytes(r.storeYr)+' a year fits on a few servers\' disks; the hard part is not size but keeping three copies consistent and backed up. Images, audio or embeddings would change this by orders of magnitude.</p>'}
    else if(cur==='egress'){const flat=r.gbMonth*0.09;h+='<p>Tiered bill '+money(r.egress)+' against '+money(flat)+' at the first-tier price throughout: volume discounts start to matter past 10 TB. Serving the same images from a CDN or a provider with free egress can cut this to near zero, which is why heavy static files rarely leave a cloud directly.</p>'}
    h+='<p class="small mute">'+esc(c.by_construction)+'</p>';$('nm-est-check').innerHTML=h}
  function init(){$('nm-drills').innerHTML=NUM_DATA.drills.map(d=>'<button data-id="'+d.id+'">'+esc(d.n)+'</button>').join('');
    $('nm-drills').addEventListener('click',e=>{const b=e.target.closest('button');if(b)load(b.dataset.id)});inputs();load('chat')}
  return {init,model,load};
})();

// ---- corrections and sources ----
NM.text=function(){const {$,esc,srcLink,fmtT}=NM;const D=NUM_DATA;const L=id=>D.ladder.find(r=>r.id===id);
  const p=(id,i)=>L(id).pts[i].v;const dv=D.derived;
  const items=[
   ['"fsync latency, roughly a millisecond"','It ranges over about four orders of magnitude. Datacenter NVMe with power-loss protection: '+fmtT(p('fsync_plp',0))+' to '+fmtT(p('fsync_plp',1))+'; local NVMe on a cloud VM: '+fmtT(p('fsync_cloud',0))+'; a network block disk: '+fmtT(p('fsync_cloud',1))+'; consumer NVMe: '+fmtT(p('fsync_consumer',0))+' to '+fmtT(p('fsync_consumer',1))+' ('+srcLink('mc_fsync')+'); a 7,200 rpm hard disk: 17 to 25 ms ('+srcLink('percona_fsync')+'). "About a millisecond" is right only for consumer SSDs and network disks. And on macOS plain fsync() does not flush the drive: '+fmtT(p('fsync_mac',0))+' against '+fmtT(p('fsync_mac',1))+' with F_FULLFSYNC (measured here).'],
   ['"GPU memory bandwidth is the ceiling on decode throughput, because generating one token reads the whole weight set once"','True for one request at a time: a 7B model in 3.83 GB on an H100 cannot beat '+dv.decode_floor_ms.toFixed(2)+' ms a token, and llama.cpp measures '+dv.decode_ms.toFixed(2)+' ms ('+srcLink('llamacpp')+'). Not true for the GPU as a whole: a batch shares each weight read among many requests, so Llama 3.1 8B in FP8 (about 8 GB) reaches 14,992 output tokens/s on one H100 (NVIDIA docs, v0.21 data: '+srcLink('trtllm')+'), about 36 times the 3.35 TB/s / 8 GB ≈ 420 tokens/s a single stream could get. Bandwidth caps per-user speed; batching, compute and KV-cache memory cap total throughput.'],
   ['"TCP slow start ... short-lived connections underuse the link"','Right, and it can be put in numbers: a new connection may send 10 segments (about 14.6 KB) in its first round trip and roughly doubles each round trip after ('+srcLink('rfc6928')+'), so a 100 KB response on a fresh connection needs about 3 round trips (14.6 + 29.2 + 58.4 KB) instead of 1, on top of the 2 round trips of TCP and TLS 1.3 setup. Across the Atlantic (78 ms) that is roughly 300 ms of waiting a reused connection avoids.'],
   ['"cold-starts in minutes not milliseconds"','Confirmed with a dated figure: reloading a model takes 30 to 100+ seconds per switch with vLLM ('+srcLink('vllm_sleep')+'), before any new machine has to be provisioned.'],
   ['The popular latency table now has LLM rows','A widely copied gist of Dean\'s table has added rows such as "Frontier LLM, time to first token" dated 2026 without sources, beside the 2009 numbers ('+srcLink('gist')+'). This tab keeps the classic numbers and today\'s measurements as separate marks, each with its own source and year, and never quotes the spliced table.']];
  $('nm-fix').innerHTML=items.map(([a,b])=>'<details class="mist"><summary><b>Old page:</b> '+esc(a)+'</summary><div class="b">'+b+'</div></details>').join('');
  const ids=Object.keys(D.sources);$('nm-src').innerHTML=ids.map(id=>'<li>'+NM.kchip(D.sources[id].who==='classic'?'classic':D.sources[id].who)+srcLink(id)+'</li>').join('')};

// ---- wiring: build lazily on first show; redraw width-dependent pieces on resize ----
(function(){let built=false;
  function build(){if(built||!window.NUM_DATA)return;built=true;NM.ladder.init();NM.budget.init();NM.thr.init();NM.avail.init();NM.est.init();NM.text();
    const nav=document.getElementById('nm-nav');nav.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=document.getElementById(b.dataset.go);if(t)t.scrollIntoView({block:'start',behavior:RD.RM?'auto':'smooth'})})}
  function redraw(){if(!built)return;NM.ladder.render();NM.budget.redraw()}
  (window.TAB_RENDER=window.TAB_RENDER||{});(window.TAB_RENDER['t-num']=window.TAB_RENDER['t-num']||[]).push(()=>{build();redraw()});
  let t=0;addEventListener('resize',()=>{if(!NM.visible())return;clearTimeout(t);t=setTimeout(redraw,80)});
})();
