// Run the toy experiment (parts/22_js_toy.js, the same code the page runs) for eight seeds at the default settings and
// write model/toy_results.json and parts/_gen_toydata.js (window.TOYDATA), which the page shows before any live run.
// usage: node toy_sweep.mjs   (about 20 s)
import { createRequire } from 'node:module'; import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url)); const require = createRequire(import.meta.url);
const T = require(path.join(here, 'parts/22_js_toy.js'));
const r5 = v => Math.round(v * 1e5) / 1e5;
const rnd = o => Array.isArray(o) ? o.map(rnd) : (o && typeof o === 'object') ? Object.fromEntries(Object.entries(o).map(([k, v]) => [k, rnd(v)])) : typeof o === 'number' && !Number.isInteger(o) ? r5(o) : o;
const seeds = [1, 2, 3, 4, 5, 6, 7, 8], runs = []; const t0 = Date.now();
for (const s of seeds) { runs.push(rnd(T.runAll({ seed: s }))); console.log('seed', s, ((Date.now() - t0) / 1000).toFixed(1) + ' s'); }
const out = { engine: 'parts/22_js_toy.js', defaults: T.DEF, entropy: r5(T.task().entropy), seeds, runs };
fs.writeFileSync(path.join(here, 'model/toy_results.json'), JSON.stringify(out));
fs.writeFileSync(path.join(here, 'parts/_gen_toydata.js'), '// Generated by toy_sweep.mjs: eight seeds of the default toy experiment, computed by the same engine the page runs.\nwindow.TOYDATA=' + JSON.stringify(out) + ';\n');
// summary
const at = (a, b) => (a.find(x => x[0] === b) || [0, NaN])[1], mean = a => a.reduce((x, y) => x + y, 0) / a.length, sd = a => { const m = mean(a); return Math.sqrt(a.reduce((x, y) => x + (y - m) ** 2, 0) / (a.length - 1)) };
const S = {}; const add = (k, v) => (S[k] = S[k] || []).push(v);
for (const R of runs) {
  add('const@1600', at(R.cons, 1600)); for (const k in R.wsd) add('wsd ' + k, R.wsd[k].at(-1)[1]);
  for (const m in R.merge) for (const n in R.merge[m]) { const a = R.merge[m][n]; if (at(a, 1600) === at(a, 1600)) add(m + ' ' + n + ' @1600', at(a, 1600)); add(m + ' ' + n + ' best', Math.min(...a.map(x => x[1]))); }
  for (const g of R.gran) add('gran ' + g[0] + 'x' + g[1], g[2]);
  for (const e of R.equiv) { add('equiv ' + e.m + e.n + ' merged', e.merged); add('equiv ' + e.m + e.n + ' run', e.decayRun); add('equiv ' + e.m + e.n + ' dist/moved', e.dist / e.moved); }
  add('diff mean16@1600 - wsd1sqrt', at(R.merge.mean[16], 1600) - R.wsd['1-sqrt'].at(-1)[1]);
}
const summ = Object.fromEntries(Object.entries(S).map(([k, a]) => [k, { mean: r5(mean(a)), sd: r5(sd(a)), wins: k.startsWith('diff') ? a.filter(x => x < 0).length : undefined }]));
fs.writeFileSync(path.join(here, 'model/toy_summary.json'), JSON.stringify(summ, null, 1));
for (const [k, v] of Object.entries(summ)) console.log(k.padEnd(32), v.mean.toFixed(5), '+-', v.sd.toFixed(5), v.wins != null ? 'wins ' + v.wins + '/8' : '');
