"""Write parts/20b_sweep_data.js (window.SWEEP) from model/sweep.json, the offline sweep the page reproduces."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
d = json.load(open(os.path.join(HERE, 'model', 'sweep.json')))
p = d['pipeline']
r4 = lambda v: round(v, 4)
out = {'base': {k: r4(v) for k, v in p['base'].items()}, 'sft': {k: r4(v) for k, v in p['sft'].items()}, 'rmAcc': {k: (r4(v) if isinstance(v, float) else v) for k, v in p['rmAcc'].items()},
       'sftEpochs': [{'e': e['e'], 'val': r4(e['val']), 'u': r4(e['u'])} for e in p['sftEpochs']], 'runs': d['runs']}
open(os.path.join(HERE, 'parts', '20b_sweep_data.js'), 'w').write('// Generated by mk_sweep_data.py from model/sweep.json (node sweep.cjs)\nwindow.SWEEP=' + json.dumps(out, separators=(',', ':')) + ';\n')
print('20b_sweep_data.js', len(json.dumps(out)))
