"""Write parts/22_js_data.js from meas/out/*.json: the page's only copy of the recorded numbers.

Everything the page draws from a measurement comes from window.NF (set here); check_embed.py confirms the built
page embeds exactly these objects and that the prose quotes them correctly.
"""
import json, os, re

H = os.path.dirname(os.path.abspath(__file__))
O = os.path.join(H, "meas", "out")


def load(n):
    return json.load(open(os.path.join(O, n)))


def ladder(q):
    """Pair each UDP datagram sent with its arrival on the other side, and attach the QUIC packets inside it.

    The qlog lists packets, not datagrams; packets coalesced into one datagram are logged within a few microseconds of
    each other (3 microseconds in this recording), so packets closer than 0.02 ms are grouped. Each group's sizes must add up to the datagram's size, or be
    smaller when the sender padded the datagram (the first flight in each direction); anything else is an error."""
    out = []
    for who, other in (("client", "server"), ("server", "client")):
        sent = [d for d in q["datagrams"] if d["who"] == who and d["dir"] == "sent"]
        recv = [d for d in q["datagrams"] if d["who"] == other and d["dir"] == "recv"]
        pk = [p for p in q[who]["packets"] if p["dir"] == "sent"]
        groups, cur = [], []
        for p in pk:
            if cur and p["t_ms"] - cur[-1]["t_ms"] > 0.02:
                groups.append(cur); cur = []
            cur.append(p)
        if cur: groups.append(cur)
        assert len(groups) == len(sent) == len(recv), (who, len(groups), len(sent), len(recv))
        for g, s, r in zip(groups, sent, recv):
            tot = sum(p["size"] for p in g)
            assert tot <= s["bytes"] and r["bytes"] == s["bytes"], (who, tot, s, r)
            out.append(dict(frm=who, bytes=s["bytes"], padded=s["bytes"] - tot, t_send=s["t_ms"], t_recv=r["t_ms"],
                            port=r.get("from_port") if who == "client" else s.get("from_port"),
                            packets=[dict(type=p["type"], pn=p["pn"], size=p["size"], frames=p["frames"]) for p in g]))
    return sorted(out, key=lambda e: e["t_send"])


def build():
    loc = {r["exp"]: r for r in load("local_sockets.json")}
    tp = load("tcp_path.json")
    runs = [{k: v for k, v in r.items() if k not in ("cum_10ms", "wnd_samples")} for r in tp["runs"]]
    series = next(r for r in tp["runs"] if "wnd_samples" in r)
    q = load("quic_migrate.json")
    mtu = load("path_mtu.json")
    ll = load("loaded_latency.json")
    env = open(os.path.join(O, "env.txt")).read()
    return dict(
        recorded=tp["recorded"],
        env=env,
        path=dict(host=tp["host"], note=tp["note"], runs=runs,
                  series=dict(rcvbuf="auto", wnd=[[s[0], s[1]] for s in series["wnd_samples"]], cum=series["cum_10ms"],
                              first_byte_ms=series["first_byte_ms"])),
        local=loc,
        quic=dict(recorded=q["recorded"], aioquic=q["aioquic"], steps=q["steps"], datagrams=q["datagrams"], ladder=ladder(q)),
        mtu=dict(recorded=mtu["recorded"], en0=mtu["ifconfig_en0_mtu"], v4=mtu["v4"], v6=mtu["v6_dontfrag"], rtt=mtu["ping_rtt_v4"]),
        loaded=ll,
    )


if __name__ == "__main__":
    d = build()
    s = json.dumps(d, separators=(",", ":"), ensure_ascii=False)
    with open(os.path.join(H, "parts", "22_js_data.js"), "w") as f:
        f.write("// Generated by make_data.py from meas/out/*.json. Do not edit.\nwindow.NF=" + s + ";\n")
    print("wrote", len(s), "bytes")
