#!/usr/bin/env python3
"""Harness atlas (tab t-atlas): build parts/33_js_atl_a_data.js from src/atlas/inputs/.

Inputs (all read 2026-10-05):
  r1_vendor_cli.json, r2_ide_cloud.json, r3_open.json  one object per harness, schema in research_schema.md
  r4_scores.json      same-model, different-harness scores, studies, SWE RL environments
  mswe_attempt_2026-10-05.json   the aborted mini-swe-agent run (redacted summary)
  ../../parts/31_js_loop_0data.js, 32_js_trc_a_data.js  (generated by the Loop and Trace labs)
     for the animation: Loop lab run s5_haiku and Trace lab run std_haiku_1, per-call tokens.
Usage: python3 src/atlas/build_data.py   (from the page folder or anywhere)
"""
import json, re, getpass
# private strings built at run time so this file does not contain them: home prefix, scratch-dir form, user name, token prefixes, em-dash
PRIVATE = ["/" + "Us" + "ers/", "Us" + "ers-", getpass.getuser(), "gl" + "pat", "sk" + "-ant", "\u2014"]
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
INP = HERE / "inputs"
PARTS = HERE.parent / "parts"
OUT = PARTS / "33_js_atl_a_data.js"

FAMILY = {
    "claude_code": "cli", "openai_codex": "cli", "gemini_cli": "cli", "qwen_code": "cli", "amp": "cli",
    "cursor": "ide", "windsurf": "ide", "cline": "ide", "roo_code": "ide", "kilo_code": "ide", "kiro": "ide",
    "github_copilot": "ide", "devin": "cloud", "google_jules": "cloud",
    "openhands": "oss", "aider": "oss", "opencode": "oss", "swe_agent": "oss", "mini_swe_agent": "oss",
    "goose": "oss", "pi": "oss", "openclaw": "personal", "hermes_agent": "personal",
}
# a short status badge where the product is not plainly active (the cell text carries the evidence)
BADGE = {"windsurf": "renamed", "roo_code": "shut down", "cursor": "acquired", "amp": "spun out",
         "aider": "slowing", "swe_agent": "maintenance", "kilo_code": "acquired"}
# child pages of this topic that go deeper on a product (title, Notion page URL)
_CC = ("Claude Code, taken apart", "https://app.notion.com/p/3c65c17b0d0d81db9c7fc54987c1ab65")
_OTH = ("Other coding harnesses", "https://app.notion.com/p/3c65c17b0d0d819fa3cefdcd2ccff2f7")
_PERS = ("Personal agents", "https://app.notion.com/p/3c75c17b0d0d81bf9462fbeb09593e1c")
DEEPER = {"claude_code": _CC, "openai_codex": _OTH, "gemini_cli": _OTH, "opencode": _OTH, "aider": _OTH,
          "openhands": _OTH, "mini_swe_agent": _OTH, "openclaw": _PERS, "hermes_agent": _PERS}
AXES = ["open", "models", "loop", "edit", "context", "perms", "ext", "where", "price"]


def srcs(x):
    s = x.get("src") if isinstance(x, dict) else None
    if not s:
        return []
    return s if isinstance(s, list) else [s]


def norm_status(h):
    s = h.get("status")
    if isinstance(s, dict):
        return {"v": s.get("v", ""), "d": s.get("d", ""), "src": srcs(s)}
    return {"v": s or "", "d": "", "src": []}


def harnesses():
    out = []
    raw = []
    for f in ["r1_vendor_cli.json", "r2_ide_cloud.json", "r3_open.json"]:
        raw += json.load(open(INP / f))
    by = {h["id"]: h for h in raw}
    # Kiro appears twice (r1: the CLI, formerly Amazon Q Developer CLI; r2: the platform). Keep r2's, carry r1's notes.
    if "kiro_cli" in by and "kiro" in by:
        k = by["kiro"]
        k.setdefault("notes", [])
        k["notes"] = list(k["notes"]) + [f"(Kiro CLI) {n}" for n in by["kiro_cli"].get("notes", [])]
        st = norm_status(by["kiro_cli"])
        if st["v"]:
            k["notes"].append("(Kiro CLI) " + st["v"] + (" " + st["d"] if st["d"] else ""))
        raw = [h for h in raw if h["id"] != "kiro_cli"]
    for h in raw:
        if h["id"] not in FAMILY:
            raise SystemExit("no family for " + h["id"])
        ax = {}
        for a in AXES:
            c = h["axes"].get(a, {})
            ax[a] = {"t": c.get("tags", []), "v": c.get("v", ""), "d": c.get("d", ""), "s": srcs(c)}
        fr = h.get("first_release") or {}
        lt = h.get("latest") or {}
        out.append({
            "id": h["id"], "name": h["name"], "maker": h.get("maker", ""), "kind": h.get("kind", []),
            "fam": FAMILY[h["id"]], "badge": BADGE.get(h["id"], ""), "sum": h.get("summary", ""),
            "st": norm_status(h),
            "first": {"v": fr.get("v", ""), "d": fr.get("d", ""), "s": srcs(fr)},
            "latest": {"v": lt.get("v", ""), "date": lt.get("date", ""), "s": srcs(lt)},
            "ax": ax, "notes": h.get("notes", []),
            "deep": list(DEEPER[h["id"]]) if h["id"] in DEEPER else [],
        })
    order = list(FAMILY)
    out.sort(key=lambda h: order.index(h["id"]))
    return out


def num(s):
    m = re.search(r"-?\d+(\.\d+)?", s or "")
    return float(m.group()) if m else None


def scores():
    d = json.load(open(INP / "r4_scores.json"))
    own = {"Claude": ["Claude Code"], "GPT": ["Codex CLI", "Codex"], "Gemini": ["Gemini CLI"]}

    def kind(model, harness):
        h = harness.lower()
        if "mini-swe-agent" in h:
            return "mini"
        if h.startswith("terminus 2"):
            return "neutral"
        if h.startswith("anthropic") or h.startswith("not stated"):
            return "vendor"
        for k, hs in own.items():
            if k.lower() in model.lower() or (k == "Claude" and re.match(r"(Fable|Opus|Sonnet|Haiku)", model)):
                if harness in hs:
                    return "own"
        return "third"

    sets = {}
    defs = [
        ("tb20", "Terminal-Bench 2.0 (89 tasks)", "Terminal-Bench 2.0 public board: models listed with two or more agents"),
        ("tb21", "Terminal-Bench 2.1 (89 tasks)", "Terminal-Bench 2.1 public board: models listed with two agents"),
        ("swev", "SWE-bench Verified (500)", "SWE-bench Verified: bash-only mini-SWE-agent against submitted scaffolds and vendor launch figures"),
        ("htswe", "SWE-bench Lite (30-task sample, 3 attempts)", "HarnessTax: 7 models x 3 harnesses, SWE-bench Lite sample (controlled study)"),
        ("httb", "Terminal-Bench 2.0 (30-task sample, 3 attempts)", "HarnessTax: 7 models x 3 harnesses, Terminal-Bench 2.0 sample (controlled study)"),
    ]
    for key, bench, title in defs:
        rows = []
        for p in d["pairs"]:
            if p["bench"] != bench or "LEGO" in p["model"] or "before RL" in p["model"]:
                continue
            note = p.get("note") or ""
            r = {"m": p["model"], "h": p["harness"], "v": p["value"], "k": kind(p["model"], p["harness"]),
                 "date": p.get("date"), "src": p.get("src"), "note": note, "ci": p.get("ci")}
            if "verified False" in note:
                r["unv"] = 1
            if key.startswith("ht"):
                r["c"] = num(p.get("cost"))
                lo_hi = re.findall(r"[\d.]+", p.get("ci") or "")
                if len(lo_hi) >= 2:
                    r["lo"], r["hi"] = float(lo_hi[0]), float(lo_hi[1])
                m = re.search(r"turns/attempt ([\d.]+)", note)
                if m:
                    r["turns"] = float(m.group(1))
            elif p.get("ci"):
                hw = num(p["ci"])
                if hw is not None:
                    r["lo"], r["hi"] = round(p["value"] - hw, 2), round(p["value"] + hw, 2)
            rows.append(r)
        # keep models with two or more distinct harnesses
        hs = {}
        for r in rows:
            hs.setdefault(r["m"], set()).add(r["h"])
        rows = [r for r in rows if len(hs[r["m"]]) >= 2]
        # the set's common source and note are stored once; rows keep only what differs
        from collections import Counter
        common_src = Counter(r["src"] for r in rows).most_common(1)[0][0]
        common_note = None
        for r in rows:
            if r["src"] == common_src:
                del r["src"]
            n = r.pop("note")
            m = re.search(r"agent org ([^;]+);", n)
            if m:
                r["org"] = m.group(1)
            if key.startswith("tb"):
                common_note = "The board's date field is the model's date (all agents for one model share it), not the submission date. Unverified rows were submitted by the agent's makers and not verified by the maintainers."
                r.pop("ci", None)
            elif key.startswith("ht"):
                r.pop("ci", None)
                common_note = "Success: share of 90 attempts (30 tasks x 3) resolved, 95% bootstrap interval over tasks. Cost: mean per attempt at the study's fixed 1 September 2026 API price list."
            else:
                r["note"] = n
        sets[key] = {"title": title, "src": common_src, "note": common_note, "rows": rows}
    lego = [p for p in d["pairs"] if "Qwen3.5-35B" in p["model"]]
    return sets, d["studies"], d["rl_envs"], d["rl_build_pattern"], d["harnesstax_meta"], lego


def anim():
    js = ("global.window={};const vm=require('vm'),fs=require('fs');"
          f"vm.runInThisContext(fs.readFileSync('{PARTS/'31_js_loop_0data.js'}','utf8'));"
          f"vm.runInThisContext(fs.readFileSync('{PARTS/'32_js_trc_a_data.js'}','utf8'));"
          "const s=window.LOOPDATA.runs.find(r=>r.id==='s5_haiku');"
          "const c=window.TRC_DATA.find(r=>r.id==='std_haiku_1');"
          "console.log(JSON.stringify({loop:{id:s.id,passed:s.passed,secs:s.tot.secs,calls:s.turns.map(t=>t.u),"
          "who:s.turns.map(t=>t.w),acts:s.turns.map(t=>t.act?t.act.tool:'')},"
          "cc:{id:c.id,passed:c.pass,secs:c.dur/1000,cost:c.cost,calls:c.calls.map(x=>x.slice(0,4)),"
          "acts:c.ev.filter(e=>e.k==='tool').map(e=>e.n||e.name)}}))")
    return json.loads(subprocess.run(["node", "-e", js], capture_output=True, text=True, check=True).stdout)


def main():
    H = harnesses()
    sets, studies, rl, pat, htm, lego = scores()
    x = json.load(open(INP / "mswe_attempt_2026-10-05.json"))
    a = anim()
    data = {"h": H, "sets": sets, "studies": studies, "rl": rl, "rlpat": pat, "htm": htm, "lego": lego,
            "x": x, "anim": a, "read": "2026-10-05"}
    s = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    for bad in PRIVATE:
        if bad in s:
            raise SystemExit("private string or em-dash in data: " + bad)
    OUT.write_text("// Harness atlas data: built by src/atlas/build_data.py from src/atlas/inputs/. Do not edit.\n"
                   "window.ATL=" + s + ";\n")
    print(OUT.name, len(s), "bytes;", len(H), "harnesses;", {k: len(v["rows"]) for k, v in sets.items()})


main()
