"""Write parts/22_js_fgw_data.js (window.FGW) from recordings/fgw_runs.json only. No other input."""
import json, os
H = os.path.dirname(os.path.abspath(__file__))
D = json.load(open(os.path.join(H, "recordings", "fgw_runs.json")))
D["phi"] = {"steady": 0.9965, "burst": 0.0}  # fitted clock offset, see recompute.py
s = json.dumps(D, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
open(os.path.join(H, "parts", "22_js_fgw_data.js"), "w").write(
    "// ---- Recorded data (generated by src/gen_data.py from src/recordings/fgw_runs.json; do not edit) ----\nwindow.FGW=" + s + ";\n")
print(len(s))
