"""Write parts/_gen_toy.js: the toy's precomputed results (inputs/toy.json from toy_sweep.mjs), the paper's
figure data decoded from its SVGs (inputs/figs.json from decode_figs.py) and the PyTorch check summary
(model/check_engine.json from check_engine.py). build.sh runs it."""
import json, os
H = os.path.dirname(os.path.abspath(__file__))
toy = json.load(open(os.path.join(H, 'inputs', 'toy.json')))
figs = json.load(open(os.path.join(H, 'inputs', 'figs.json')))
chk = json.load(open(os.path.join(H, 'model', 'check_engine.json')))
for f in figs.values():
    for s in f['series'].values():
        for k in ('points', 'line', 'bars'):
            if k in s: s[k] = [[round(v, 4) for v in p] for p in s[k]]
c = {'verdict': chk['verdict'], 'worst': chk['worst'], 'cases': [k for k in chk if k not in ('worst', 'verdict')]}
open(os.path.join(H, 'parts', '_gen_toy.js'), 'w').write('// Generated by mk_toydata.py.\nwindow.TOYRES=' + json.dumps(toy, separators=(',', ':')) + ';\nwindow.FIGS=' + json.dumps(figs, separators=(',', ':')) + ';\nwindow.CHK=' + json.dumps(c, separators=(',', ':')) + ';\n')
print('mk_toydata: %d bytes' % os.path.getsize(os.path.join(H, 'parts', '_gen_toy.js')))
