"""Compact the offline data in inputs/ into parts/22_js_data.js for the page.

Lab: the top 100 logits per position are kept exactly; tokens 101 to 200 and the stored histogram of the
rest are merged into a tail of [logit, count] bins (0.25-logit bins), so the page can compute the tail's
softmax mass at any temperature. Run: python3 make_page_data.py
"""
import json, os, collections
H = os.path.dirname(os.path.abspath(__file__))
I = lambda f: json.load(open(os.path.join(H, 'inputs', f)))
NK = 60

lab = I('lab_logits.json')
L = {'model': lab['model'], 'vocab': lab['vocab'], 'prompts': []}
for p in lab['prompts']:
    pos = []
    gen = []  # token ids generated before each position (the greedy reply so far)
    for x in p['pos']:
        tail = collections.defaultdict(int)
        for lg in x['lg'][NK:]:
            tail[round(lg * 20) / 20] += 1
        for lg, c in x['tail']:
            tail[round(lg * 10) / 10] += c
        tl = sorted(tail.items(), key=lambda kv: -kv[0])
        assert sum(c for _, c in tl) + NK == lab['vocab'], (sum(c for _, c in tl), lab['vocab'])
        pos.append({'s': x['so_far'], 't': x['tok'][:NK], 'l': x['lg'][:NK], 'c': x['ctx'][:NK], 'g': [gen.count(i) for i in x['id'][:NK]],
                    'tl': [[a, b] for a, b in tl], 'H': x['H'], 'pt': x['p_top']})
        gen.append(x['id'][0])
    L['prompts'].append({'k': p['key'], 'q': p['text'], 'r': p['greedy_reply'], 'pos': pos})

beam = I('beam_tree.json')
js = I('json_constrained.json')
for st in js['steps'] + js['free_steps']:
    st['top'] = st['top'][:8]
import re
# Samples shown on the page skip any text matching this list (GPT-2 at high temperature produces slurs and
# sexual content); the metrics use all 16 samples.
BLOCK = re.compile(r'\b(jew|jews|masturbat\w*|sex\w*|porn\w*|rape\w*|nigg\w*|fuck\w*|shit\w*|cunt|whore\w*|slut\w*|nazi\w*|kill\w*|gay|fag\w*|dick\w*|cock\w*|pussy|bitch\w*|nude|naked|breast\w*|penis|vagina)\b', re.I)
dg = I('degeneration.json')
# keep 3 samples per passage per setting for the page; deterministic settings have one output per passage.
# Diversity across samples: distinct-2 over the pooled samples of one passage; for greedy and beam all 16
# "samples" would be the same text, so the pooled figure is the single text's distinct-2 divided by 16.
for st in dg['settings']:
    det = 'greedy' in st['kw'] or 'beam' in st['kw']
    st['div'] = st['distinct2'] / dg['n_samples'] if det else st['distinct2']
    st['det'] = det
    keep, seen = [], {}
    for x in st['samples']:
        if BLOCK.search(x['text']):
            st['skipped'] = st.get('skipped', 0) + 1
            continue
        seen[x['p']] = seen.get(x['p'], 0) + 1
        if seen[x['p']] <= 3:
            keep.append({'p': x['p'], 'text': x['text'], 'lp': round(x['lp'], 3), 'rep4': round(x['rep4'], 3)})
    st['samples'] = keep
    for k in ('mean_lp', 'rep4', 'distinct2', 'div'):
        st[k] = round(st[k], 4)
for p in dg['passages']:
    p['human_lp'] = round(p['human_lp'], 4)

def dump(o):
    # no em-dash characters and no '{{' (the build's link syntax) in the page source
    return json.dumps(o, ensure_ascii=False, separators=(',', ':')).replace('\u2014', ' -- ').replace('{{', '{\\u007b')


with open(os.path.join(H, 'parts', '22_js_data.js'), 'w') as f:
    f.write('// Generated by make_page_data.py from inputs/*.json (real model outputs; see make_data.py). Do not edit.\n')
    f.write('window.SD=window.SD||{};\n')
    f.write('SD.LAB=' + dump(L) + ';\n')
    f.write('SD.BEAM=' + dump(beam) + ';\n')
    f.write('SD.JSONC=' + dump(js) + ';\n')
    f.write('SD.DEG=' + dump(dg) + ';\n')
print(os.path.getsize(os.path.join(H, 'parts', '22_js_data.js')))
