"""Write parts/30_js_data.js (window.API_DATA) from the real captures in inputs/ and the service source.
Run from src/: python3 gen_data.py   (stdlib only)"""
import base64, hashlib, hmac, json, os
H = os.path.dirname(os.path.abspath(__file__))
ex = json.load(open(os.path.join(H, 'inputs', 'exchanges.json')))
pg = json.load(open(os.path.join(H, 'inputs', 'pagination_pg.json')))
src = open(os.path.join(H, 'service', 'app.py')).read()

def b64url(b): return base64.urlsafe_b64encode(b).rstrip(b'=').decode()
# A real HS256 JWT made with the standard library (RFC 7519 compact form), secret shown on the page on purpose
hdr = {"alg": "HS256", "typ": "JWT"}
pay = {"iss": "https://auth.chat.example.com", "sub": "user_alice", "aud": "chat-api", "iat": 1790000000, "exp": 1790000900, "scope": "chats:read chats:write"}
signing = b64url(json.dumps(hdr, separators=(',', ':')).encode()) + '.' + b64url(json.dumps(pay, separators=(',', ':')).encode())
jwt = signing + '.' + b64url(hmac.new(b'demo-secret-do-not-use', signing.encode(), hashlib.sha256).digest())
none_hdr = b64url(json.dumps({"alg": "none", "typ": "JWT"}, separators=(',', ':')).encode())
forged = none_hdr + '.' + b64url(json.dumps(dict(pay, sub="user_mallory"), separators=(',', ':')).encode()) + '.'

keys = ['health', 'create_noauth', 'create', 'create_invalid', 'create_invalid_default', 'create_badjson', 'get', 'get_missing',
        'list_p1', 'list_p2', 'list_badlimit', 'msg_nokey', 'msg_first', 'msg_retry', 'msg_mismatch', 'msg_concurrent_first',
        'msg_concurrent', 'stream', 'rate_ok', 'rate_limited']
D = {
    'meta': ex['meta'], 'timing': ex['timing'], 'burst': ex['burst_statuses'],
    'ex': {k: {'req': ex[k]['request'], 'res': ex[k]['response'], 'ms': ex[k]['ms']} for k in keys},
    'stream_ms': ex['stream'].get('arrivals_ms'),
    'openapi': {'version': ex['openapi_version'], 'MessageIn': ex['openapi_MessageIn']},
    'webhook': ex['webhook'],
    'jwt': {'token': jwt, 'secret': 'demo-secret-do-not-use', 'header': hdr, 'payload': pay, 'forged': forged},
    'pg': {'version': pg['postgres'], 'machine': pg['machine'], 'rows': pg['rows'], 'page': pg['page'], 'date': pg['date'],
           'method': pg['method'], 'res': [{'d': r['depth'], 'off': r['offset']['ms'], 'ks': r['keyset']['ms']} for r in pg['results']]},
    'src': src,
}
s = json.dumps(D, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/')
open(os.path.join(H, 'parts', '30_js_data.js'), 'w').write('// generated by gen_data.py from inputs/exchanges.json, inputs/pagination_pg.json and service/app.py\nwindow.API_DATA=' + s + ';\n')
print(len(s), 'bytes')
