// Generated by build.sh from model/check_engine.json (check_engine.py).
window.TOYCHECK={"cases": 20, "max_abs_diff_advantage": 8.881784197001252e-16, "max_abs_diff_gradient": 3.0531133177191805e-16, "verdict": "PASS"};
