// ---- Lineage tab: every MiniMax language model since January 2025 ----
(function(){
  if(!$('lnSvg'))return;
  const R={lin:'var(--c3)',full:'var(--c2)',msa:'var(--acc)',na:'var(--mute)'};
  const L=[
   {n:'MiniMax-Text-01 and VL-01',d:'2025-01-15',r:'lin',tot:456,act:45.9,ctx:'1M trained, 4M claimed at inference',lic:'MiniMax Model Agreement',t:'The 7:1 lightning hybrid at 456B total and 45.9B active, described by MiniMax as the first successful large-scale implementation of linear attention; VL-01 adds vision.',src:'{{release notes|@rel}}; {{report|@p01}}; {{card|@k01}}'},
   {n:'MiniMax-M1',d:'2025-06-16',r:'lin',tot:456,act:45.9,ctx:'1M input; 40K and 80K thinking budgets',lic:'Apache 2.0',t:'An open reasoning model on the same hybrid backbone and the origin of CISPO; the full RL run took three weeks on 512 H800s ($534,700).',src:'{{M1 report|@pm1}}; {{card|@km1}}'},
   {n:'MiniMax-M2',d:'2025-10-27',r:'full',tot:229.9,act:9.8,ctx:'196,608 (config); 204,800 on the API',lic:'Modified MIT',t:'The reversal to full softmax GQA in every layer; positioned on speed and price for agentic work rather than on context length. 3 MTP heads for speculative decoding.',src:'{{release notes|@rel}}; {{M2 report|@pm2}}; {{card|@km2}}'},
   {n:'MiniMax-M2.1',d:'2025-12-22',r:'full',tot:229.9,act:9.8,ctx:'204,800',lic:'Modified MIT',t:'Same backbone; MiniMax\'s notes stress multi-language programming and code refactoring.',src:'{{release notes|@rel}}'},
   {n:'MiniMax-M2.5',d:'2026-02-12',dl:'February 2026',r:'full',tot:229.9,act:9.8,ctx:'204,800',lic:'Modified MIT',t:'Same backbone, with a highspeed variant; still trained with CISPO.',src:'{{release notes|@rel}}; {{card|@km25}}'},
   {n:'MiniMax-M2.7',d:'2026-03-18',r:'full',tot:229.9,act:9.8,ctx:'204,800',lic:'Modified MIT',t:'Same backbone, adding what MiniMax call "self-evolution": during development the model debugged its own RL runs, built skills for its experiments and modified its own scaffold. The current fast, cheap agentic workhorse.',src:'{{release notes|@rel}}; {{M2 report|@pm2}}; {{card|@km27}}'},
   {n:'MiniMax-M3',d:'2026-06-01',r:'msa',tot:428,act:23,ctx:'1,000,000 (512K on the standard price tier)',lic:'MiniMax Community License',t:'GQA (4 KV heads) plus block-sparse MSA in every layer after the first three; native multimodality (text, image and video in, vision encoder trained in from pretraining). MiniMax call it the first open-weight model to combine frontier-level coding, a 1M context and native multimodality.',src:'{{release notes|@rel}}; {{announcement|@m3b}}; {{card|@km3}}; {{MSA paper|@pmsa}}'},
   {n:'MiniMax-M3.1-Flash-Preview',d:'2026-09-27',r:'na',tot:null,act:null,ctx:'1,000,000',lic:'not open (MiniMax Code and M Plan only)',t:'The first M3.1-branded model, shipped only inside MiniMax\'s own coding agent: five effort levels (low to max, default max), thinking cannot be switched off, and no published price, speed, benchmark or architecture.',src:'{{DataNorth|@dn}}; {{MiniMax docs|@tg}}'}];
  let sel=6;
  const t0=Date.UTC(2024,11,1),t1=Date.UTC(2026,9,31),W=760,H=170,pl=20,pr=20,X=d=>pl+(W-pl-pr)*(Date.parse(d)-t0)/(t1-t0);
  function draw(){
    let s='<line x1="'+pl+'" x2="'+(W-pr)+'" y1="120" y2="120" stroke="var(--line)"/>';
    for(let y=2025;y<=2026;y++)for(let q=0;q<12;q+=3){const d=y+'-'+String(q+1).padStart(2,'0')+'-01',x=X(d);if(x<pl||x>W-pr)continue;s+='<line x1="'+x+'" x2="'+x+'" y1="116" y2="124" stroke="var(--mute)"/><text x="'+x+'" y="140" font-size="10.5" text-anchor="middle" fill="var(--mute)">'+['Jan','Apr','Jul','Oct'][q/3]+(q===0?' '+y:'')+'</text>'}
    [['lin','2025-01-01','2025-10-27'],['full','2025-10-27','2026-06-01'],['msa','2026-06-01','2026-10-31']].forEach(([r,a,b])=>{s+='<rect x="'+X(a)+'" y="154" width="'+(X(b)-X(a))+'" height="8" rx="2" fill="'+R[r]+'" opacity=".7"/>'});
    L.forEach((m,i)=>{const x=X(m.d),rad=m.tot?3+Math.sqrt(m.tot)*0.55:6,y=120-(i%2?52:22)-(m.r==='na'?0:0);
      s+='<g class="lnd" data-i="'+i+'"><line x1="'+x+'" x2="'+x+'" y1="'+y+'" y2="120" stroke="var(--line)"/><circle cx="'+x+'" cy="120" r="'+rad+'" fill="'+R[m.r]+'" opacity="'+(i===sel?1:.6)+'" stroke="'+(i===sel?'var(--ink)':'none')+'" stroke-width="2"/><text x="'+x+'" y="'+(y-4)+'" font-size="11" text-anchor="middle"'+(i===sel?' font-weight="600"':'')+'>'+m.n.replace('MiniMax-','').replace(' and VL-01','')+'</text></g>'});
    $('lnSvg').innerHTML=svgEl(W,H,s,'Timeline of MiniMax language models by attention route');
    $('lnSvg').querySelectorAll('.lnd').forEach(g=>g.addEventListener('click',()=>{sel=+g.dataset.i;draw()}));
    $('lnCards').innerHTML=L.map((m,i)=>'<div class="detail" data-i="'+i+'" style="'+(i===sel?'':'display:none')+'"><h3>'+m.n+'</h3><span class="tag" style="color:'+R[m.r]+';border-color:'+R[m.r]+'">'+({lin:'lightning hybrid',full:'full softmax GQA',msa:'GQA + MSA',na:'architecture not published'})[m.r]+'</span><dl class="kv"><dt>Released</dt><dd>'+(m.dl||new Date(m.d).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}))+'</dd><dt>Total / active</dt><dd>'+(m.tot?(m.r==='msa'?'~':'')+m.tot+'B / '+(m.r==='msa'?'~':'')+m.act+'B':'not published')+'</dd><dt>Context</dt><dd>'+m.ctx+'</dd><dt>Licence</dt><dd>'+m.lic+'</dd></dl><p>'+m.t+'</p><p class="small mute">Sources: '+m.src+'</p></div>').join('')+'<div class="chips">'+L.map((m,i)=>'<button data-i="'+i+'" class="'+(i===sel?'on':'')+'">'+m.n.replace('MiniMax-','')+'</button>').join('')+'</div>';
    $('lnCards').querySelectorAll('.chips button').forEach(b=>b.addEventListener('click',()=>{sel=+b.dataset.i;draw()}))}
  onTab('t-line',draw);
})();
