// ---- Reading tab (Topic: agentic-harnesses): harness map, loop replay, permission gate, trifecta, measured table ----
// Data: window.AHREAD from 22_js_rd_data.js (generated by src/read/extract_read.py from the redacted recordings).
(function(){
const D=window.AHREAD;if(!D||!window.RD)return;
const esc=RD.esc;
const fmt=n=>Number(n).toLocaleString('en-US');
const usd=x=>'$'+x.toFixed(x<0.1?4:3);
// Haiku 4.5 list prices per million tokens (platform.claude.com pricing, read 2026-10-05): input 1, 1h cache write 2, cache read 0.10, output 5.
const HAIKU={in:1,cw:2,cr:0.1,out:5};
const callCost=c=>(c.in*HAIKU.in+c.cw*HAIKU.cw+c.cr*HAIKU.cr+c.out*HAIKU.out)/1e6;

// ---------- 0. the harness map ----------
(function(){
  const grid=document.getElementById('ahread-grid'),det=document.getElementById('ahread-det');if(!grid)return;
  const P=[
    ['tools','Tools','Functions the model may call, each a name, a description and a JSON schema; the harness runs them and returns the result.','rd-s2','2 Tools'],
    ['ctx','Context assembly','Builds every request: system prompt, tool definitions, memory files, history. Decides what the model can know.','rd-s3','3 Context'],
    ['mem','Memory','Files loaded at start (CLAUDE.md, AGENTS.md), notes and progress files that outlive a context window or a session.','rd-s3','3 Context'],
    ['loop','The loop','Call the model, run the tool call it asks for, append the result, call again; stop when it answers without a tool call.','rd-s1','1 Chat to agent'],
    null,
    ['stop','Control','Stop conditions and limits, plan mode, todo lists, subagents, hooks that run your code at fixed points.','rd-s4','4 Control'],
    ['perm','Permissions','Allow, deny or ask a person before each tool call, by rule or mode.','rd-s5','5 Safety'],
    ['box','Sandbox','An operating-system boundary around what does run: files it may write, hosts it may reach.','rd-s5','5 Safety'],
    ['ui','Interface','Terminal, editor, cloud machine or chat app: where you watch, steer and review the work.','rd-s6','6 Products']
  ];
  grid.innerHTML=P.map((p,i)=>p?'<button data-i="'+i+'" aria-label="'+esc(p[1])+'">'+esc(p[1])+'</button>':'<div class="mdl">Model<br><span style="font-weight:400;font-size:11.5px">text in, text out</span></div>').join('');
  function pick(i){grid.querySelectorAll('button').forEach(b=>b.classList.toggle('on',+b.dataset.i===i));const p=P[i];
    det.innerHTML='<b>'+esc(p[1])+'.</b> '+esc(p[2])+' <a href="#'+p[3]+'">Section '+esc(p[4])+'</a>';}
  grid.addEventListener('click',e=>{const b=e.target.closest('button');if(b)pick(+b.dataset.i)});
  pick(3);
})();

// ---------- 1. one call against the loop ----------
(function(){
  const card=document.getElementById('ahread-c1');if(!card)return;
  const cc=D.cc,s0=D.s0,calls=cc.calls;
  const maxIn=Math.max(...calls.map(c=>c.in+c.cw+c.cr));
  const scale=Math.ceil(maxIn/5000)*5000;
  let mode='cc';
  const cap=document.getElementById('ahread-c1-cap'),cnt=document.getElementById('ahread-c1-cnt'),win=document.getElementById('ahread-c1-win'),run=document.getElementById('ahread-c1-run');
  function blocksHtml(c){return c.b.map(b=>{
    if(b.k==='think')return '<span class="mute">(thinks)</span> ';
    if(b.k==='text')return '<span>'+esc(b.s)+'</span> ';
    return '<span><b>'+esc(b.name)+'</b> <code>'+esc(b.s)+'</code></span><span class="r'+(b.err?' err':'')+'">'+esc(b.r)+'</span>';}).join('')}
  function buildRows(){
    if(mode==='cc'){
      run.innerHTML='<div class="ahread-ev" data-i="0"><span class="n">0</span><div>Prompt sent with six tool definitions. Nothing read yet.</div></div>'+
        calls.map((c,i)=>'<div class="ahread-ev" data-i="'+(i+1)+'"><span class="n">'+(i+1)+'</span><div>'+blocksHtml(c)+'</div></div>').join('')+
        '<div class="ahread-ev" data-i="'+(calls.length+1)+'"><span class="n">&#10003;</span><div>Tests run again after the session: <span class="r">'+esc(cc.post)+'</span></div></div>';
    }else{
      run.innerHTML='<div class="ahread-ev" data-i="0"><span class="n">0</span><div>One prompt: the task plus the whole of <code>textstats/core.py</code>. No tools, no tests.</div></div>'+
        '<div class="ahread-ev" data-i="1"><span class="n">1</span><div>The reply: a corrected file and an explanation. <span class="r">'+esc(s0.expl)+'</span></div></div>'+
        '<div class="ahread-ev" data-i="2"><span class="n">&#10003;</span><div>The harness writes the file back and runs the tests once to grade it: <span class="r err">'+esc(s0.post)+'</span></div></div>';
    }}
  function caption(i){
    if(mode==='s0'){
      return [['Step 0: no loop','The source file is pasted into one prompt: '+fmt(s0.in)+' input tokens. The model has never seen the tests.'],
        ['One answer','Haiku 4.5 replies in '+s0.sec.toFixed(1)+' s with '+fmt(s0.out)+' output tokens ('+fmt(s0.th)+' of them thinking). It fixes the tie-breaking in top_words.'],
        ['Graded afterwards','The apostrophe bug is still there: nothing in the prompt said apostrophes must survive, and the model had no way to run anything and find out.']][i];}
    const n=calls.length;
    if(i===0)return ['Enter','The harness sends the system prompt, six tool definitions and the task. The window already holds '+fmt(calls[0].in+calls[0].cw+calls[0].cr)+' tokens on the first call.'];
    if(i===n+1)return ['Done',n+' model calls, '+cc.wall+' s, '+usd(cc.cost)+' at list prices. Both bugs fixed, verified by the tests.'];
    const c=calls[i-1],t=c.b.find(b=>b.k==='tool');
    const tin=c.in+c.cw+c.cr;
    let why='';
    if(t&&t.err)why=' The result is an error, sent back to the model as is.';
    else if(t&&t.name==='Edit')why=' An exact-string edit to the library.';
    else if(t&&t.name==='Read')why=' Reading a file puts its whole text into the history.';
    else if(!t)why=' No tool call: the model answers in text, so the loop ends.';
    return ['Call '+i+(t?': '+t.name:': final answer'),'Input '+fmt(tin)+' tokens ('+fmt(c.cr)+' read from cache, '+fmt(c.cw)+' newly cached, '+fmt(c.in)+' fresh), output '+fmt(c.out)+'.'+why];}
  function draw(i){
    run.querySelectorAll('.ahread-ev').forEach(el=>{const k=+el.dataset.i;el.classList.toggle('on',k===i);el.classList.toggle('past',k<i)});
    const on=run.querySelector('.ahread-ev.on');if(on&&run.scrollHeight>run.clientHeight){const t=on.offsetTop-run.clientHeight/2+on.offsetHeight/2;run.scrollTop=Math.max(0,t)}
    const c=caption(i);cap.innerHTML='<div class="t">'+esc(c[0])+'</div><p>'+c[1]+'</p>';
    if(mode==='cc'){
      const k=Math.min(i,calls.length);let cost=0;for(let j=0;j<k;j++)cost+=callCost(calls[j]);
      const cur=k>0?calls[k-1]:null;
      let tests='not run yet';for(let j=0;j<k;j++)calls[j].b.forEach(b=>{const m=b.k==='tool'&&/(\d+) failed/.exec(b.r);if(m)tests=m[1]+' failed'});
      cnt.innerHTML=RD.stat('Model calls',k,'of '+calls.length)+RD.stat('Input on this call',cur?fmt(cur.in+cur.cw+cur.cr):'0','tokens')+RD.stat('Cost so far',usd(cost),'list prices, Haiku 4.5')+RD.stat('Tests',tests,'as the model last saw them');
      const seg=cur?[[cur.cr,'var(--c1)'],[cur.cw,'var(--c5)'],[cur.in,'var(--c2)']]:[];
      win.innerHTML='<div class="bar">'+seg.map(s=>'<span style="width:'+(100*s[0]/scale).toFixed(2)+'%;background:'+s[1]+'"></span>').join('')+'</div>'+
        '<div class="leg"><span style="--sw:var(--c1)">cache read</span><span style="--sw:var(--c5)">cache write</span><span style="--sw:var(--c2)">fresh input</span><span>bar = '+fmt(scale)+' tokens; the window is '+fmt(cc.ctxwin)+'</span></div>';
    }else{
      cnt.innerHTML=RD.stat('Model calls',i>=1?1:0,'of 1')+RD.stat('Input',fmt(s0.in),'tokens')+RD.stat('Tests',i>=2?'1 failed':'never seen','');
      win.innerHTML='<div class="bar"><span style="width:'+(100*s0.in/scale).toFixed(2)+'%;background:var(--c2)"></span></div><div class="leg"><span style="--sw:var(--c2)">fresh input</span><span>same scale as the loop: '+fmt(scale)+' tokens</span></div>';
    }}
  buildRows();
  const A=RD.anim({card:'ahread-c1',ctl:'ahread-c1-ctl',n:calls.length+2,draw,ms:1500,label:'Step of the run'});
  RD.seg(document.getElementById('ahread-c1-seg'),m=>{mode=m;buildRows();A.reset(m==='cc'?calls.length+2:3);A.play()});
})();

// ---------- 5. the permission gate, with and without ----------
(function(){
  const card=document.getElementById('ahread-c2');if(!card)return;
  const G=D.gates;
  // what each action would do if nothing checked it (illustrative, written for these eleven actions)
  const NOGATE=['reads the file','edits the library','edits the tests: the one rule of the task is broken','runs the tests','runs the tests (harmless)','searches (harmless)','downloads and runs a stranger\'s script','prints the README, then deletes the library','prints the README (harmless here; substitution can run anything)','runs a one-line experiment (harmless)','publishes to the remote repository'];
  let mode='gate';
  const list=document.getElementById('ahread-c2-list'),cap=document.getElementById('ahread-c2-cap'),cnt=document.getElementById('ahread-c2-cnt');
  const argStr=g=>g.args.cmd||g.args.path||'';
  function rows(){list.innerHTML=G.map((g,i)=>'<div class="ahread-act" data-i="'+(i+1)+'"><span><b>'+esc(g.tool)+'</b> <code>'+esc(argStr(g))+'</code></span><span class="v"></span><span class="why"></span></div>').join('')}
  function draw(i){
    let run=0,den=0,bad=0;
    list.querySelectorAll('.ahread-act').forEach(el=>{const k=+el.dataset.i,g=G[k-1];el.classList.toggle('on',k===i);el.classList.toggle('past',k<i);
      const v=el.querySelector('.v'),w=el.querySelector('.why');
      if(k>i){v.innerHTML='';w.textContent=g.note;return}
      if(mode==='gate'){const ok=g.v==='allow';v.innerHTML='<span class="pill '+(ok?'ok':'bad')+'">'+(ok?'runs':'denied')+'</span>';w.textContent=g.note+'. '+g.why+'.';ok?run++:den++}
      else{const harm=/broken|stranger|deletes|publishes/.test(NOGATE[k-1]);v.innerHTML='<span class="pill '+(harm?'bad':'ok')+'">runs</span>';w.textContent=NOGATE[k-1]+'.';run++;if(harm)bad++}});
    if(i===0)cap.innerHTML='<div class="t">'+(mode==='gate'?'The gate: deny rules, then allow rules, then ask':'No gate: the harness runs whatever the model asks')+'</div><p>Eleven actions a coding agent might request on the running example, one per step.</p>';
    else{const g=G[i-1];cap.innerHTML='<div class="t">Action '+i+': '+esc(g.note)+'</div><p>'+(mode==='gate'?esc(g.why)+'.':esc(NOGATE[i-1])+'.')+'</p>'}
    cnt.innerHTML=mode==='gate'?RD.stat('Ran',run,i?'of '+i+' so far':'none yet')+RD.stat('Denied',den,'including asks nobody could answer'):RD.stat('Ran',run,i?'of '+i+' so far':'none yet')+RD.stat('Harmful',bad,'illustrative consequences');}
  rows();
  const A=RD.anim({card:'ahread-c2',ctl:'ahread-c2-ctl',n:G.length+1,draw,ms:1300,label:'Action'});
  RD.seg(document.getElementById('ahread-c2-seg'),m=>{mode=m;rows();A.reset(G.length+1);A.play()});
})();

// ---------- 5. the lethal trifecta ----------
(function(){
  const box=document.getElementById('ahread-tri'),out=document.getElementById('ahread-tri-out');if(!box)return;
  function upd(){const v={};box.querySelectorAll('input').forEach(x=>v[x.dataset.k]=x.checked);
    const all=v.p&&v.u&&v.e;out.classList.toggle('bad',all);
    if(all)out.innerHTML='<b>All three present.</b> Text planted in the untrusted content can tell the agent to read the private data and send it out. Remove one leg: usually the way out (network allowlist by destination, no arbitrary fetches) or the untrusted input.';
    else{const miss=[!v.p&&'private data',!v.u&&'untrusted content',!v.e&&'a way out'].filter(Boolean);
      out.innerHTML='<b>The trifecta is broken</b> (missing: '+miss.join(', ')+'). Injection can still make the agent do damage inside its own scope, so the gate and sandbox still matter.'}}
  box.addEventListener('change',upd);upd();
})();

// ---------- 7. measured comparisons ----------
(function(){
  const tb=document.getElementById('ahread-meas');if(!tb)return;
  const R=D.runs,h=R.filter(r=>r.label.indexOf('haiku')>=0),s=R.filter(r=>r.label.indexOf('sonnet')>=0);
  const rng=(a,f,d)=>{const v=a.map(f);const lo=Math.min(...v),hi=Math.max(...v);return lo===hi?d(lo):d(lo)+' to '+d(hi)};
  const L=D.loopcmp,c=D.cc;
  const rows=[
    ['One call against the loop','Haiku 4.5, task','Step 0 (one call, no tools) against Claude Code',D.s0.post.split('\n').pop()+' after 1 call; '+c.post.split('\n').pop()+' after '+c.calls.length+' calls'],
    ['Same settings, three runs','Haiku 4.5, Claude Code, all flags','Nothing',h.length+' of '+h.length+' pass; '+rng(h,r=>r.calls,x=>x)+' calls; '+rng(h,r=>r.cost,usd)],
    ['Same settings, three runs','Sonnet 5.5, Claude Code, all flags','Nothing',s.length+' of '+s.length+' pass; '+rng(s,r=>r.calls,x=>x)+' calls; '+rng(s,r=>r.cost,usd)+'; '+rng(s,r=>r.wall,x=>x+' s')],
    ['Our harness against Claude Code','Sonnet 5.5, task','Loop lab step 5 against Claude Code (python allowed)','both pass; '+usd(L.ours_cost)+' ('+L.ours_calls+' calls) against '+usd(L.cc_cost)]
  ];
  tb.innerHTML=rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('');
})();
})();
