"""Write parts/25_js_lab_data.js from inputs/lab_measured.json and inputs/lab_outbox_batch1.json (the measured lab)."""
import json, os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
m = json.load(open('inputs/lab_measured.json'))
b1 = json.load(open('inputs/lab_outbox_batch1.json'))
keep = ('mode', 'name', 'seed', 'crashes', 'effects', 'distinct_orders', 'duplicates', 'lost', 'dedup_hits', 'jobs', 'vt', 'p_crash')
d = {'date': m['date'], 'postgres': m['postgres'], 'machine': m['machine'],
     'throughput': m['throughput'],
     'redelivery': [{k: r[k] for k in keep if k in r} for r in m['redelivery']],
     'outbox': m['outbox'] + b1}
open('parts/25_js_lab_data.js', 'w').write('// ---- Generated by src/gen_lab_js.py from inputs/lab_measured.json and inputs/lab_outbox_batch1.json: do not edit ----\n'
                                          'window.LABDATA=' + json.dumps(d, separators=(',', ':')) + ';\n')
print('ok', len(d['redelivery']), len(d['outbox']))
