// ---- Then and now: the LoRA recipe from 2021 to 2025, one sourced step at a time ----
(function(){
const S=[
 {t:'2021, the paper',y:'Jun 2021',ad:['Wq','Wv'],base:'FP16',scale:'α / r',lr:'40× FT (GPT-3)',serve:'merge one adapter',c:'LoRA on W<sub>q</sub> and W<sub>v</sub> only, MLP frozen; α/r with α fixed; FP16 base; merge for zero latency (§4.1, §4.2, Table 12).'},
 {t:'Feb 2023: Hugging Face PEFT',y:'Feb 2023',ad:['Wq','Wv'],base:'FP16',scale:'α / r',lr:'40× FT (GPT-3)',serve:'merge or keep separate',c:'The repository points to PEFT, which becomes the standard interface (LoraConfig, target_modules) ('+A('https://github.com/microsoft/LoRA','repository README')+').'},
 {t:'May 2023: QLoRA',y:'May 2023',ad:['Wq','Wk','Wv','Wo','W1','W2','W3'],base:'4-bit NF4',scale:'α / r (r 64, α 16)',lr:'tuned',serve:'merge or keep separate',c:'Attention-only LoRA could not match full fine-tuning on large models; LoRA on all linear layers could. A frozen 4-bit NormalFloat base with double quantisation and paged optimisers fine-tunes 65B on one 48 GB GPU ('+A('https://arxiv.org/abs/2305.14314','QLoRA')+').'},
 {t:'Nov 2023: S-LoRA, then vLLM and SGLang',y:'Nov 2023',ad:['Wq','Wk','Wv','Wo','W1','W2','W3'],base:'4-bit or 16-bit',scale:'α / r',lr:'tuned',serve:'thousands of adapters, unmerged, batched',c:'Instead of merging, serve many adapters over one base in one batch: up to 4× the throughput of naive serving, thousands of adapters on one GPU ('+A('https://arxiv.org/abs/2311.03285','S-LoRA')+'); the paper\'s "hard to batch" limitation, solved by not merging.'},
 {t:'Nov 2023: rsLoRA',y:'Nov 2023',ad:['Wq','Wk','Wv','Wo','W1','W2','W3'],base:'4-bit or 16-bit',scale:'α / √r (option)',lr:'tuned',serve:'unmerged, batched',c:'Dividing by r stunts high ranks; dividing by √r lets larger r help ('+A('https://arxiv.org/abs/2312.03732','rsLoRA')+'); PEFT\'s use_rslora. The Train a LoRA tab compares both at one learning rate.'},
 {t:'Feb 2024: DoRA',y:'Feb 2024',ad:['Wq','Wk','Wv','Wo','W1','W2','W3'],base:'4-bit or 16-bit',scale:'magnitude + LoRA on direction',lr:'tuned',serve:'merge (no overhead)',c:'Decompose each weight into a magnitude and a direction and apply LoRA to the direction; consistently better than LoRA on LLaMA, LLaVA and VL-BART ('+A('https://arxiv.org/abs/2402.09353','DoRA')+').'},
 {t:'Jun 2024: adapters on a phone',y:'Jun 2024',ad:['Wq','Wk','Wv','Wo','W1','W2','W3'],base:'about 3.7 bits per weight',scale:'rank 16',lr:'n/a',serve:'swap per feature on device',c:'Apple\'s about 3B on-device model loads, caches and swaps rank-16 adapters of tens of megabytes per feature, and uses LoRA adapters to recover accuracy after compressing the base ('+A('https://machinelearning.apple.com/research/introducing-apple-foundation-models','Apple')+').'},
 {t:'Sep 2025: LoRA Without Regret',y:'Sep 2025',ad:['Wq','Wk','Wv','Wo','W1','W2','W3'],base:'16-bit',scale:'α / r (α = 32)',lr:'about 10× FT',serve:'LoRA-based fine-tuning service (Tinker)',c:'All layers, especially MLP; the optimal LoRA learning rate is about 10× full fine-tuning\'s; RL matches even at rank 1; large batches cost LoRA more ('+A('https://thinkingmachines.ai/blog/lora/','Thinking Machines')+'); their '+A('https://thinkingmachines.ai/tinker/','Tinker')+' service is LoRA underneath.'}];
const M=[['Wq','W<tspan dy="3" font-size="11">q</tspan>'],['Wk','W<tspan dy="3" font-size="11">k</tspan>'],['Wv','W<tspan dy="3" font-size="11">v</tspan>'],['Wo','W<tspan dy="3" font-size="11">o</tspan>'],['W1','W<tspan dy="3" font-size="11">gate</tspan>'],['W3','W<tspan dy="3" font-size="11">up</tspan>'],['W2','W<tspan dy="3" font-size="11">down</tspan>']];
function draw(m,k,e,W){const s0=S[k],sp=S[Math.max(0,k-1)];const bw=Math.min(74,(W-30)/7-8),bh=44,y0=36;let s=tx(10,18,'attention',{fs:11,c:'var(--mute)'})+tx(10+4*(bw+8)+14,18,'MLP',{fs:11,c:'var(--mute)'});
  M.forEach(([id,lab],i)=>{const x=10+i*(bw+8)+(i>=4?14:0);const on=s0.ad.includes(id),was=sp.ad.includes(id);const op=on?(was?1:e):(was?1-e:0);
    s+=rc(x,y0,bw,bh,'var(--soft)',{s:'var(--line)'})+'<text x="'+(x+bw/2)+'" y="'+(y0+bh/2+5)+'" font-size="13" text-anchor="middle">'+lab+'</text>';
    if(op>0)s+=G(op,rc(x,y0+bh+4,bw,8,'var(--c2)',{r:2})+rc(x,y0,bw,bh,'none',{s:'var(--c2)',sw:2})+tx(x+bw/2,y0+bh+24,'+BA',{fs:11,a:'middle',c:'var(--c2)'}))});
  s+=tx(10,y0+bh+46,'base stored as: '+s0.base,{fs:12,w:600});return svgW(W,y0+bh+56,s,'Where adapters go')}
const cnt=(m,k)=>{const s=S[k];return stat('when',s.y,'')+stat('matrices adapted',String(s.ad.length)+' of 7','per block')+stat('scale',s.scale,'')+stat('learning rate',s.lr,'against full fine-tuning')+stat('serving',s.serve,'')};
makeAnim({id:'tn',modes:{now:S.map(x=>({t:x.t,c:x.c}))},mode:'now',draw,counters:cnt,dur:3600});
})();
