"""Writes parts/22_js_data.js (window.SC) from the measured inputs/*.json. Run: python3 build_data.py"""
import json, os
H = os.path.dirname(os.path.abspath(__file__)); I = lambda f: json.load(open(os.path.join(H, 'inputs', f)))
P, C, L = I('part.json'), I('citus.json'), I('lab_data.json')
CR = I('crdb.json') if os.path.exists(os.path.join(H, 'inputs', 'crdb.json')) else None
m = P['m']
part = {k: {'ms': v['ms'], 'plan': v['planning_ms'], 'pages': v['shared_hit'] + v['shared_read'], 'rels': sorted({s['rel'] for s in v['scans']}), 'rows': v['rows']}
        for k, v in m.items()}
SC = {
 'part': part, 'partNames': [p['name'] for p in P['parts']], 'partRows': [p['rows'] for p in P['parts']],
 'q': P['q'], 'chatId': P['chat_id'], 'retDel': P['ret_delete'], 'retDrop': P['ret_drop'], 'planning': P['planning'],
 'cold': m['dash|messages']['all_ms'][0] if 'all_ms' in m['dash|messages'] else None,
 'citus': {'point': C['point'], 'heavy': C['heavy'], 'tx': C['tx'], 'repart': C['repartition_join'], 'joinBig': C['join_big'],
           'shards': [s['rows'] for s in C['shards_before']], 'shardPort': [s['port'] for s in C['shards_before']], 'user4242': C['explain_router'].split('port=')[1].split()[0], 'user1': [s['rows'] for s in C['shards_before'] if s['shardid'] == C['user1_shard']][0],
           'load': C['load_s'], 'rebalance': C['rebalance'], 'drain': C.get('drain'), 'hits': int(C['mention_hits'])},
 'lab': {'total': L['total_msgs'], 'week': L['total_week'], 'users': L['users'], 'chats': L['chats'], 'top': L['top'],
         'byN': {n: {k: [v['stored'], v['week']] for k, v in d.items()} for n, d in L['by_n'].items()}},
 'reshard': L['reshard'], 'keyChange': L['key_change_3'],
}
if CR:
    SC['crdb'] = {'lat': CR['insert_latency'], 'events': CR['events'], 'tl': [[s['ok'], s['err'], s['max_ms']] for s in CR['timeline']],
                  'stale': round(float(CR['follower_staleness_s'].split()[-1]), 2), 'errors': CR['errors'], 'version': CR['version'], 'ranges': CR['ranges_after']}
out = '// generated by src/build_data.py from src/inputs/*.json (measured 5 Oct 2026); do not edit\nwindow.SC=' + json.dumps(SC, separators=(',', ':')) + ';\n'
open(os.path.join(H, 'parts', '22_js_data.js'), 'w').write(out); print(len(out), 'bytes')
