"""Join the recordings in raw/ (and the root's HTTP/1.1 bytes) into parts/20_js_data.js, embedded verbatim except
for the trims listed here: DATA frame text is kept whole; header blocks keep their parsed fields; SDK attempt
headers keep only the retry-related ones. check_embed.py proves the page carries these values.
Usage: python3 make_data.py   (from src/)
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, "raw")
ROOT_RAW = os.path.join(HERE, "../../src/wire/raw")
sys.path.insert(0, os.path.join(HERE, "../../src"))
from private_patterns import alternation  # noqa: E402

J = lambda n: json.load(open(os.path.join(RAW, n)))
T = lambda n: open(os.path.join(RAW, n)).read()

h2 = J("h2_frames.json")
for f in h2["frames"]:
    f.pop("head_hex", None)
h3 = J("h3_frames.json")
sdk = J("sdk_retries.json")
keep = ("x-stainless-retry-count", "x-stainless-timeout", "x-stainless-read-timeout", "idempotency-key")
for c in sdk["cases"]:
    for a in c["server_saw"]:
        a["headers"] = {k: v for k, v in a["headers"].items() if k in keep}
data = {
    "h1": {"request": open(os.path.join(ROOT_RAW, "h1_request.bin"), "rb").read().decode("latin-1"),
           "response": open(os.path.join(ROOT_RAW, "h1_response.bin"), "rb").read().decode("latin-1"),
           "arrivals": json.load(open(os.path.join(ROOT_RAW, "h1_arrivals.json")))},
    "h2": h2, "h3": h3,
    "hol": J("hol_app.json"), "hpack": J("hpack_sizes.json"), "flow": J("flow_h2.json"),
    "proxy": J("proxy_rewrite.json"), "amb": J("ambiguous.json"), "timeouts": J("timeouts.json"), "sdk": sdk, "sdk_version": J("sdk_version.json"),
    "public": T("public_headers.txt"), "conditional": T("conditional.txt"), "sdk_request": T("sdk_request_anthropic.txt"),
}
s = json.dumps(data, separators=(",", ":"), ensure_ascii=False)
bad = re.findall(alternation(), s) + re.findall(r"/Users/|/private/tmp|g[l]pat|s[k]-ant", s)
if bad:
    sys.exit("private or secret-looking text in data: %r" % bad[:5])
s = s.replace("</", "<\\/")
open(os.path.join(HERE, "parts", "20_js_data.js"), "w").write("// generated by make_data.py from raw/ (do not edit)\nwindow.HD=" + s + ";\n")
print("parts/20_js_data.js", len(s), "bytes")
