"""Write tables.json: the paper's Tables 1 to 3 transcribed at printed precision from inputs/table_*.txt (parsed, not
retyped), Figure 4 and Figure 5 transcribed from their printed labels (raster figures; every number is a printed label,
not read off a curve), Figures 6 to 8 decoded from the vector SVGs (inputs/figs.json), and the released package and
leaderboard data the page uses (inputs/task_catalog.json, inputs/lb_bench.json, inputs/lb_iter.json,
inputs/a3_manifest_extract.json, inputs/agent_timeouts.json).
usage: python3 mk_tables.py   (build.sh runs it)"""
import json, re

MODELS = ['Claude Opus 5', 'Kimi K3', 'Qwen3.8 Max', 'GPT 5.6 Sol', 'GLM 5.2', 'Claude Sonnet 5', 'Qwen3.7 Max', 'DeepSeek V4Pro']
CATS = ['Training', 'Inference & Serving', 'Compression', 'Kernel', 'I/O', 'Hardware & Edge', 'Data Infrastructure', 'System Optimization', 'System Assurance']
LBKEY = {'Claude Opus 5': 'opus-5', 'Kimi K3': 'kimi-k3', 'Qwen3.8 Max': 'qwen3.8', 'GPT 5.6 Sol': 'gpt-5.6', 'GLM 5.2': 'glm-5.2',
         'Claude Sonnet 5': 'sonnet-5', 'Qwen3.7 Max': 'qwen3.7', 'DeepSeek V4Pro': 'deepseek'}


def parse(fn, ncol):
    """Rows of a printed table: a model name followed by ncol numbers."""
    toks = [t.strip() for t in re.split(r'[\t\n]', open(fn).read()) if t.strip()]
    out = {}
    for i, t in enumerate(toks):
        if t in MODELS:
            vals = toks[i + 1:i + 1 + ncol]
            out[t] = [float(v) for v in vals]
    assert list(out) == MODELS, list(out)
    return out


T2 = parse('inputs/table_Sx3_T2.txt', 10)
T3 = parse('inputs/table_Sx5_T3.txt', 4)
# Figure 4 (raster, temp.png): printed cell labels, KFC / LHI / E2E rows by the nine categories (blank cells are 0)
F4 = {'KFC': [15, 7, 2, 19, 5, 2, 1, 3, 1], 'LHI': [1, 2, 4, 8, 0, 1, 0, 1, 3], 'E2EO': [3, 2, 0, 1, 2, 0, 1, 1, 0]}
# Figure 5 (raster, ablation2.png): printed point labels; Kimi K3 has no medium or xhigh point
F5 = {'tiers': ['low', 'medium', 'high', 'xhigh', 'max'],
      'Claude Opus 5': [31.33, 31.43, 31.91, 34.69, 35.38], 'Kimi K3': [17.45, None, 29.35, None, 31.83], 'GPT 5.6 Sol': [16.02, 22.18, 18.27, 21.59, 22.76]}
figs = json.load(open('inputs/figs.json'))
cat = json.load(open('inputs/task_catalog.json'))['tasks']
lb = json.load(open('inputs/lb_bench.json'))
it = json.load(open('inputs/lb_iter.json'))
a3 = json.load(open('inputs/a3_manifest_extract.json'))
tmo = json.load(open('inputs/agent_timeouts.json'))

F6 = {m: [[p[0], p[1]] for p in s['points']] for m, s in figs['iteration_best']['series'].items()}
F8 = {m: {'pts': [[p[0], p[1]] for p in s['points']], 'failed': [round(x) for x in s['failed_rounds']]} for m, s in figs['iteration_current']['series'].items()}
F7 = {}
names7 = {'Claude Opus 5': 'Claude Opus 5', 'Kimi K3': 'Kimi K3', 'Qwen3.8-Max': 'Qwen3.8 Max', 'GPT-5.6 Sol': 'GPT 5.6 Sol', 'GLM-5.2': 'GLM 5.2',
          'Claude Sonnet 5': 'Claude Sonnet 5', 'Qwen3.7-Max': 'Qwen3.7 Max', 'DeepSeek-V4-Pro': 'DeepSeek V4Pro'}
for k, v in figs['error'].items():
    F7[names7[k]] = {'n': v['n'], 'count': {c: round(x) for c, x in v['count'].items()}}

tasks = [{'b': t['bench'], 'id': t['task_dir'], 'cls': t['reward_class'][0], 'ref': t['ref_speedup'], 'gpu': t['gpus'], 'sub': t['max_submissions']} for t in cat]

out = {
    '_doc': 'Generated by mk_tables.py. Tables 1 to 3 parsed from the arXiv HTML; Figures 4 and 5 from printed labels; Figures 6 to 8 decoded from vector SVG; package and leaderboard data as released.',
    'models': MODELS, 'cats': CATS,
    'T1': [{'f': 'KFC', 'obj': 'Specified', 'edit': 'Single file', 'sub': 'Single'},
           {'f': 'LHI', 'obj': 'Specified', 'edit': 'Multiple files', 'sub': 'Multiple'},
           {'f': 'E2EO', 'obj': 'Free', 'edit': 'Whole repository', 'sub': 'Multiple'}],
    'T2': {m: v for m, v in T2.items()}, 'T3': {m: v for m, v in T3.items()},
    'F4': F4, 'F5': F5, 'F6': F6, 'F8': F8, 'F7': F7,
    'lb_max_topics': {m: [lb['topic_matrix']['max'][LBKEY[m]][c] for c in 'ABCDEFGHI'] for m in MODELS},
    'lb_high': [{'m': r['name'], 'kfc': r['kfc'], 'lh': r['lh'], 'e2e': r['e2e'], 'total': r['total'], 'n_e2e': r['counts']['e2e']} for r in lb['leaderboard']['high']],
    'lb_rules': {k: lb['meta'][k] for k in ('selection_e2e_perf', 'selection_exception', 'weighting_note', 'formula_perf', 'generated_utc')},
    'lb_effort_n': lb['effort']['n_tasks'],
    'lb_iter': {'title': it['title'], 'blurb': it['blurb'].replace(' \u2014 ', ': '), 'series': it['series']},
    'tasks': tasks,
    'a3': {'baseline_bpb': a3['reward_model']['baseline_bpb'], 'ref': a3['reward_model']['ref_speedup'], 'oracle_bpb': a3['reward_model']['oracle_bpb_median'],
           'baseline_cv': a3['reward_model']['baseline_cv'], 'oracle_cv': a3['reward_model']['oracle_cv'],
           'floor_bpb': a3['quality_gate']['min_plausible_val_bpb'], 'ceiling_bpb': 1.22, 'wallclock': a3['budget']['wallclock_sec'], 'param_floor': a3['quality_gate']['param_floor']},
    'timeouts': [[t['bench'], t['agent_timeout_sec']] for t in tmo],
}
json.dump(out, open('tables.json', 'w'), indent=None, separators=(',', ':'), ensure_ascii=False)
print('tables.json', len(json.dumps(out)), 'bytes')
