"""Writes parts/23_js_data.js (window.CPD): the measured results, the Wikipedia day shapes and the
recomputed defaults the page displays. Run after lab/summarize.py and recompute.py."""
import json, os
H = os.path.dirname(os.path.abspath(__file__))
j = lambda *p: json.load(open(os.path.join(H, *p)))
m = j('inputs', 'measured.json')
w = j('inputs', 'wiki_hourly.json')
r = j('recompute_out.json')['out']
d = dict(
    hockey=[{k: h[k] for k in ('util', 'rate', 'n', 'mean_service_ms', 'p50', 'p90', 'p99', 'mean', 'duration_s', 'late_send_p99')} for h in m['hockey']],
    co={k: dict(n=v['n'], send=v['measured_from_send'], sched=v['measured_from_schedule'], pts=v['points']) for k, v in m['co'].items()},
    lb=[{k: x[k] for k in ('tag', 'policy', 'rate', 'slow_server', 'util', 'typical_service_ms', 'n', 'p50', 'p90', 'p99', 'p999', 'mean', 'share_slowest', 'mean_service_ms')} for x in m['lb']],
    wiki={p: dict(shape=v['shape_utc'], month=v['peak_over_mean_month'], daily=v['peak_over_mean_daily_median'],
                  dmax=v['peak_over_mean_daily_max'], trough=v['trough_over_mean_shape'], peak=v['peak_over_mean_shape'])
          for p, v in w['projects'].items()},
    gil=r.get('gil'), simlab={k: v for k, v in r['lab'].items()}, pool=r['pool_erlang'],
)
s = json.dumps(d, separators=(',', ':'))
open(os.path.join(H, 'parts', '23_js_data.js'), 'w').write(
    '// ---- Data for the page, generated by src/gen_data.py from inputs/measured.json, inputs/wiki_hourly.json,\n'
    '// inputs/gil_*.json and recompute_out.json. Do not edit by hand. ----\nwindow.CPD=' + s + ';\n')
print(len(s))
