"""Slim the real rollouts into the page's data part and a small committed extract.
Usage (from src/): python3 rollouts/mk_data.py <dir with rollouts.json, rollouts_rp.json, mc_values.json>
Writes parts/23_js_data.js (window.LLD) and inputs/rollouts_extract.json.
The full rollouts.json (several MB, every token's log-probabilities) stays out of the repository; rerun rollouts.py to regenerate it.
"""
import json, math, sys, os
d = sys.argv[1]
R = json.load(open(os.path.join(d, 'rollouts.json')))
RP = json.load(open(os.path.join(d, 'rollouts_rp.json')))
MC = json.load(open(os.path.join(d, 'mc_values.json')))
NOTES = json.load(open('inputs/ver_notes.json')) if os.path.exists('inputs/ver_notes.json') else {}

groups = []
for P in R['problems']:
    g = P['group']
    groups.append(dict(pid=P['pid'], q=P['question'], gold=int(P['gold']) if P['gold'] == int(P['gold']) else P['gold'],
        r=[x['v_boxed'] for x in g], last=[x['v_last'] for x in g], any=[x['v_any'] for x in g],
        L=[x['len'] for x in g], tr=[1 if x['truncated'] else 0 for x in g], rm=[round(x['rm'], 3) for x in g],
        kl=[round(sum(a - b for a, b in zip(x['lp_train'], x['lp_ref'])) / x['len'], 4) for x in g],
        tail=[x['text'][-240:] for x in g]))

def hist(vals, lo, bin_, K):
    c = [0] * K
    for v in vals:
        k = int(math.floor((v - lo) / bin_)); k = max(0, min(K - 1, k)); c[k] += 1
    return c

def mis(pairs_list, lo, bin_, K):
    allv = []; seq = []
    for lt, lr in pairs_list:
        dl = [a - b for a, b in zip(lt, lr)]
        allv += dl
        seq.append([round(sum(dl), 5), round(sum(dl) / len(dl), 7)])  # log of the product ratio, log of GSPO's ratio
    return dict(lo=lo, bin=bin_, c=hist(allv, lo, bin_, K), n=len(allv), mabs=sum(abs(v) for v in allv) / len(allv),
                max=max(abs(v) for v in allv), seq=seq,
                out=sum(1 for v in allv if v < lo or v >= lo + K * bin_))

allx = [x for P in R['problems'] for x in P['group']]
M = dict(f16=mis([(x['lp_train'], x['lp_roll']) for x in allx], -0.12, 0.0005, 480),
         bf=mis([(x['lp_train'], x['lp_bf16']) for x in allx], -0.5, 0.004, 250),
         rp=mis([(x['lp_train'], x['lp_roll']) for P in RP['problems'] for x in P['group']], -4.0, 0.05, 160))
for k, v in M.items(): print('mis', k, 'n', v['n'], 'mabs %.5f max %.4f out %d' % (v['mabs'], v['max'], v['out']))

byid = {P['pid']: (j, P) for j, P in enumerate(R['problems'])}
feat = []
for key, m in MC.items():
    j, P = byid[m['pid']]; x = P['group'][m['i']]
    feat.append(dict(pid=m['pid'], g=j, i=m['i'], L=x['len'], pass_=x['v_boxed'], rm=round(x['rm'], 4), toks=x['toks'],
        lr=[round(a - b, 4) for a, b in zip(x['lp_train'], x['lp_ref'])],
        cuts=[v['cut'] for v in m['vals']], vpass=[v['v'] for v in m['vals']], vrm=[round(v['vrm'], 4) for v in m['vals']]))
feat.sort(key=lambda f: -f['pass_'])
for f in feat: f['pass'] = f.pop('pass_')

ver = []
for j, G in enumerate(groups):
    for i in range(16):
        b, l, a = G['r'][i], G['last'][i], G['any'][i]
        if not (b == l == a):
            ver.append(dict(pid=G['pid'], i=i, gold=G['gold'], b=b, l=l, a=a, tail=G['tail'][i], note=NOTES.get(f"{G['pid']}:{i}", '')))
print('disagreements', len(ver))
keep = [v for v in ver if v['note']] or ver[:8]

LLD = dict(groups=groups, feat=feat, ver=keep, mis={k: {kk: (round(vv, 6) if isinstance(vv, float) else vv) for kk, vv in v.items()} for k, v in M.items()})
js = '// ---- Real data, generated by src/rollouts/mk_data.py from the rollouts (do not edit by hand) ----\nwindow.LLD=' + json.dumps(LLD, separators=(',', ':'), ensure_ascii=False) + ';\n'
open('parts/23_js_data.js', 'w').write(js)
ext = dict(model=R['model'], ref=R['ref'], rm=R.get('rm_model'), G=R['G'], maxnew=R['maxnew'], suffix=R['suffix'],
           groups=[{k: v for k, v in G.items() if k != 'tail'} for G in groups],
           mc=MC, mismatch={k: {kk: vv for kk, vv in v.items() if kk != 'c'} for k, v in M.items()},
           disagreements=[{k: v for k, v in x.items() if k != 'tail'} for x in ver])
json.dump(ext, open('inputs/rollouts_extract.json', 'w'), separators=(',', ':'))
print('23_js_data.js', len(js), 'bytes; extract', os.path.getsize('inputs/rollouts_extract.json'))
