"""Join the recordings in raw/ into parts/22_js_data.js (window.SA). Run after run_all.sh's lab scripts.
Only reshaping happens here (selection, relative times); no number is changed. check_embed.py proves it."""
import json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "src"))
import private_patterns  # noqa: E402  (git-ignored patterns; used to refuse leaking them)

R = lambda n: json.load(open(os.path.join(HERE, "raw", n)))
pb, fr, dl, lb, st, gq = R("pb.json"), R("frames.json"), R("deadline.json"), R("lb.json"), R("status.json"), R("graphql.json")


def data():
    t0 = st["retry_server_log"][0]["t"]
    return dict(
        meta=dict(grpcio=fr["grpcio"], protobuf=pb["protobuf_python"], graphql_core=gq["graphql_core"], nginx="1.31.6",
                  recorded=fr["recorded"][:10], machine="Apple M1 Pro, macOS 27"),
        pb=dict(request=pb["request"], tokens=pb["tokens"], varints=pb["varints"], zigzag=pb["zigzag"], evolve_add=pb["evolve_add"],
                evolve_reuse=pb["evolve_reuse"], evolve_silent=pb["evolve_silent"], packed=pb["packed"], tensor=pb["tensor"]),
        frames=dict(app=fr["app"], conns=fr["conns"]),
        deadline=[dict(label=r["label"], mode=r["mode"], deadline=r["client_deadline_s"], cancel_at=r["client_cancel_at_s"], client=r["client"],
                       gateway=r["gateway"][0], inference=r["inference"][0],
                       hop2_timeout=next((v for h in r["hop2_request_headers"] for k, v in h if k == "grpc-timeout"), None),
                       hop2_end=r["hop2_end"]) for r in dl["runs"]],
        lb=dict(counts=lb["counts"], timelines=lb["timelines"]),
        status=dict(cases=st["cases"], services=st["reflection_services"],
                    retry=[dict(ms=round((x["t"] - t0) * 1000), header=x["attempt_header"], failed=x["failed"]) for x in st["retry_server_log"]],
                    pings=[f for f in st["keepalive_frames"] if f["conn"] == max(g["conn"] for g in st["keepalive_frames"])]),
        gql=gq)


if __name__ == "__main__":
    d = data()
    s = json.dumps(d, separators=(",", ":"), ensure_ascii=False)
    import re
    assert not re.search(private_patterns.alternation(), s, re.I), "private pattern in data"
    open(os.path.join(HERE, "parts", "22_js_data.js"), "w").write(
        "// Generated by make_data.py from raw/*.json (recorded " + d["meta"]["recorded"] + "). Do not edit.\nwindow.SA=" + s + ";\n")
    print("22_js_data.js", len(s), "bytes")
