"""Compact the recorded runs (src/inputs/*.json) into the page's data part, parts/22_js_data.js (window.TXD).
Run: python3 build_data.py   (plain Python, no packages)"""
import json, os, re
HERE = os.path.dirname(os.path.abspath(__file__)); IN = os.path.join(HERE, '..', 'inputs'); OUTF = os.path.join(HERE, '..', 'parts', '22_js_data.js')
load = lambda f: json.load(open(os.path.join(IN, f)))

def sv(x):
    return ('true' if x else 'false') if isinstance(x, bool) else str(x)

def out_text(kind, f):
    """one line saying what a finished statement returned"""
    if f.get('error'):
        code = f.get('code'); msg = f['error']
        return {'err': 1, 't': ('ERROR %s: %s' % (code, msg)) if kind == 'postgres' else ('ERROR %s: %s' % (code, msg)),
                'd': (f.get('detail') or '').split('\n')}
    rows = f.get('rows')
    if rows is not None:
        if len(rows) == 1 and len(rows[0]) == 1: t = sv(rows[0][0])
        elif len(rows) == 0: t = '(no rows)'
        else: t = ', '.join('(' + ', '.join(sv(x) for x in r) + ')' if len(r) > 1 else sv(r[0]) for r in rows)
        return {'t': 'returns ' + t}
    st = f.get('status')
    if st: return {'t': st}
    if 'rowcount' in f: return {'t': '%s row%s affected' % (f['rowcount'], '' if f['rowcount'] == 1 else 's')}
    return {'t': 'OK'}

def compact(kind, steps, tx_fail_note=True):
    o = []
    for st in steps:
        r = {'s': st['s'], 'q': st['sql'], 'n': st.get('note', '')}
        if st.get('blocked'): r['b'] = 1
        if st.get('queued_behind') is not None: r['qb'] = st['queued_behind']
        w = st.get('wait')
        if w and w.get('wait_event'): r['w'] = w['wait_event_type'] + ': ' + w['wait_event']
        fs = []
        for f in st.get('finished', []):
            x = out_text(kind, f); x['i'] = f['i']; x['s'] = f['s']
            q = steps[f['i']]['sql'] if f['i'] < len(steps) else ''
            if kind == 'mysql' and not f.get('error') and re.match(r'(COMMIT|ROLLBACK|SET |START )', q): x['t'] = 'OK'
            if f.get('ms', 0) >= 100: x['ms'] = round(f['ms'])
            if f.get('tx_failed'): x['tf'] = 1
            fs.append(x)
        r['f'] = fs
        o.append(r)
    return o

D = {'engines': {}}
for eng, f in (('pg', 'matrix_pg.json'), ('my', 'matrix_mysql.json')):
    m = load(f)
    E = {'version': m['version'], 'date': m['date'], 'runs': {}}
    for k, run in m['runs'].items():
        E['runs'][k] = {'occ': int(run['occurred']), 'why': run['why'],
                        'how': sorted(set(e['code'] for e in run['errors'])), 'nb': len(run['blocks']),
                        'tr': compact(m['server'], run['trace'])}
    E['defaults'] = m.get('defaults'); E['deadlock_timeout'] = m.get('deadlock_timeout')
    D['engines'][eng] = E
    D['scenarios'] = m['scenarios']
import sys; sys.path.insert(0, HERE)
from scenarios import S as _S
for _k, _v in D['scenarios'].items(): _v['story'] = _S[_k]['story']   # current wording (the stories are not part of the measurement)

x = load('extras_pg.json')
D['extras'] = {'version': x['version'], 'date': x['date'], 'long_tx': x['long_tx'], 'durability': x['durability'], 'traces': {}}
for k in ('deadlock', 'deadlock_ordered', 'lock_queue', 'lock_queue_timeout', 'jobs_plain', 'jobs_skip', 'jobs_nowait', 'optimistic', 'advisory'):
    D['extras']['traces'][k] = {'tr': compact('postgres', x[k]['steps']), 'final': x[k].get('final')}

b = load('bench_pg.json')
D['bench'] = {'date': b['date'], 'version': b['version'], 'secs': b['seconds_per_run'], 'machine': b['machine'],
              'runs': [{k: r[k] for k in ('mode', 'clients', 'contention', 'commits_per_s', 'retries_per_commit', 'gave_up', 'p50_ms', 'p99_ms', 'lost_updates', 'messages_saved', 'commits')} for r in b['runs']]}

mv = load('mvcc_trace.json')
SNAP = re.compile(r', pg_current_snapshot\(\)::text AS snap, pg_current_xact_id_if_assigned\(\)::text AS xid')
M = {'version': mv['version'], 'date': mv['date'], 'runs': {}}
for k, run in mv['runs'].items():
    steps = []
    for st in run['steps']:
        r = {'s': st['s'], 'q': SNAP.sub('', st['sql']).replace(' RETURNING balance', ''), 'n': st.get('note', ''), 'b': int(bool(st.get('blocked'))),
             'page': st.get('probe'), 'f': []}
        for f in st.get('finished', []):
            y = {'i': f['i'], 's': f['s']}
            if f.get('error'): y['err'] = 'ERROR %s: %s' % (f['code'], f['error'])
            elif f.get('rows'):
                row = f['rows'][0]; y['bal'] = row[0]; y['snap'] = row[1]; y['xid'] = row[2]
            else: y['st'] = f.get('status')
            if f.get('tx_failed'): y['tf'] = 1
            r['f'].append(y)
        steps.append(r)
    M['runs'][k] = {'steps': steps, 'final': run['final']['balance'][0][0]}
D['mvcc'] = M

js = '// ---- Recorded runs (generated by src/measure/build_data.py from src/inputs/*.json; do not edit) ----\nwindow.TXD=' + json.dumps(D, separators=(',', ':'), ensure_ascii=False) + ';\n'
open(OUTF, 'w').write(js)
print('wrote', OUTF, len(js), 'bytes')
