"""Write parts/24_js_pmd.js (window.PMD) from out/recompute.json. Run after recompute.py."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
R = json.load(open(os.path.join(HERE, "..", "out", "recompute.json")))
R.pop("anim", None)
js = "// ---- Performance math: data generated by src/code/gen_data.py from out/recompute.json; do not edit by hand ----\nwindow.PMD=" + json.dumps(R, separators=(",", ":")) + ";\n"
open(os.path.join(HERE, "..", "parts", "24_js_pmd.js"), "w").write(js)
print("24_js_pmd.js", len(js))
