// ---- Reading sections 0 and 5: the findings, written from the recordings ----
(function(){
  const F=FM.F,V=F.V,s=(k,r)=>{const x=FM.score(k,r);return x?x[0]:null};
  const pick=(k,r,ids)=>ids.filter(q=>F.A[k+'|'+r]&&F.A[k+'|'+r][q]&&!F.A[k+'|'+r][q][1]).length;
  const items=[];
  items.push('<b>Pasting the whole history is the bar.</b> With everything in the prompt Haiku got '+s('full','haiku')+' of 25'+(s('full','local')!=null?' (the local 4B model '+s('full','local')+')':'')+'; no memory at all, '+s('none','haiku')+' (the abstention questions). At about 1,400 tokens of history, a memory layer can at best match it on correctness (one-question differences are noise at this size); its case is cost once history stops fitting.');
  items.push('<b>The paper\'s small fact store matched it</b>: '+s('paper_haiku','haiku')+' of 25 with Haiku writing and reading, from '+V['pa.haiku.n']+' facts pasted whole (no search step at this size). It lost only what UPDATE overwrote.');
  items.push('<b>Mem0 2.2.1</b>: '+s('mem0','haiku')+' of 25 with Haiku reading. ADD-only kept old and new versions; '+V['m0.carry']+' of its '+V['m0.n']+' memories were re-extractions of earlier sessions with new dates, which produced a wrong date and a double-counted total.');
  items.push('<b>Graphiti</b>: '+s('graphiti_haiku','haiku')+' of 25 with Haiku writing and reading; the right evidence reached the prompt for '+V['ev.graphiti_haiku']+' of '+V['ev.n']+' answerable questions. Numbers and attributes never became edges, and '+V['gr.haiku.wrong']+' of '+V['gr.haiku.closed']+' closed edges were closed wrongly. With the 4B writer it lost both episodes after the first before the run was stopped.');
  if(F.A['letta|local'])items.push('<b>Letta</b> (local 4B, its own loop): '+s('letta','local')+' of 25. It filed one diary note per session and searched on '+V['lt.searched']+' of '+V['lt.nans']+' questions, mostly finding nothing; the same notes pasted whole gave '+s('lettastore','haiku')+' with Haiku reading. The write side worked; the read side, left to a small model, did not.');
  {const pairs=FM.SYS.map(x=>[x.l+(x.w?' ('+x.w+')':''),s(x.k,'haiku'),s(x.k,'local')]).filter(p=>p[1]!=null&&p[2]!=null);const md=Math.max(...pairs.map(p=>Math.abs(p[1]-p[2])));
  items.push('<b>The store mattered more than the reader.</b> On the same memory text the Haiku and 4B readers differed by at most '+md+' questions, while the stores ranged from '+Math.min(...pairs.map(p=>Math.min(p[1],p[2])))+' to '+Math.max(...pairs.map(p=>Math.max(p[1],p[2])))+' right. Temporal questions failed for every design, the full history included.');}
  const f0=document.getElementById('fmem-find');if(f0)f0.innerHTML='<div class="co key"><div class="t">What the runs showed</div><ul class="tight">'+items.map(x=>'<li>'+x+'</li>').join('')+'</ul></div>';
  const f5=document.getElementById('fmem-resfind');
  if(f5){const ku=['q_tests','q_gateway_now','q_report_day','q_eval_size','q_budget','q_planner'];
    f5.innerHTML='<div class="co"><div class="t">Reading the table</div><p>Compare a row\'s evidence column with its score. Where evidence is high and the score lower, the reader failed (wrong date arithmetic, a sum over duplicates); where evidence is low, the memory never wrote the fact or did not retrieve it, and no reader can recover. Knowledge updates are the design difference: wrong on update questions with Haiku reading, full history '+pick('full','haiku',ku)+' of 6, Mem0 2.2.1 '+pick('mem0','haiku',ku)+', paper loop '+pick('paper_haiku','haiku',ku)+', Graphiti '+pick('graphiti_haiku','haiku',ku)+'.</p></div>';}
})();
