// ---- Reading sections 6 and 7: failure cards built from the recordings, and the cost table ----
(function(){
  const F=FM.F,esc=FM.esc,V=F.V;
  const ans=(k,q)=>{const a=F.A[k]&&F.A[k][q];return a?'<div class="small"><b>'+esc(F.Q.find(x=>x.id===q).q)+'</b> ('+k.replace('|',', read by ').replace('_',' ')+'): <i>'+esc(a[0].slice(0,300))+'</i> <span class="pill '+(a[1]?'ok':'bad')+'">'+(a[1]?'right':'wrong')+'</span></div>':''};
  const card=(t,body,fix)=>'<div class="card"><h3 style="margin-top:0">'+t+'</h3>'+body+'<p class="small"><b>Prevent it:</b> '+fix+'</p></div>';
  const el=document.getElementById('fmem-fail');
  if(el){let h='';
    if(F.M0){const ex=F.M0.mem.filter(m=>m.c).slice(0,3);
      h+=card('Duplicates, re-dated (Mem0 2.2.1)','<p>'+V['m0.carry']+' of '+V['m0.n']+' memories restate a fact from an earlier session. The extraction prompt includes the last messages of the previous session "to resolve references"; Haiku extracted them again, and each copy was stamped with the later session\'s date. Hash deduplication only catches identical text. Examples:</p><ul class="tight">'+ex.map(m=>'<li>'+esc(m.t)+' <span class="mute">(stored with session '+(m.s+1)+', '+F.S[m.s].d+')</span></li>').join('')+'</ul>'+ans('mem0|haiku','q_incident_when')+ans('mem0|haiku','q_fallback_total'),
        'deduplicate by meaning (embedding similarity plus a model check), keep the source message id and date on every memory, and do not extract from context messages that were already processed.')}
    if(F.PA.haiku){const ups=[];F.PA.haiku.s.forEach((s,k)=>s.ops.forEach(o=>{if(o.op==='UPDATE')ups.push([k,o])}));const tu=ups.find(u=>/test/i.test(u[1].old||''))||ups[0];
      h+=card('History overwritten (the paper\'s UPDATE)','<p>The paper loop keeps only the current text of a fact. '+(tu?'In session '+(tu[0]+1)+' it rewrote "'+esc(tu[1].old)+'" as "'+esc(tu[1].text)+'".':'')+' A question about the old value then has nothing to read, unless another fact happens to mention it.</p>'+ans('paper_haiku|haiku','q_old_tests'),
        'keep superseded facts with a validity window (the graph design), or log every UPDATE in a history table that the read path can search.')}
    if(F.PA.local&&F.PA.local.lost.length){const l=F.PA.local.lost;
      h+=card('Silent write loss (paper loop, local 4B writer)','<p>In '+l.length+' session'+(l.length>1?'s':'')+' ('+l.map(x=>x[0]+1).join(', ')+') the 4B model answered the extraction prompt with a bulleted list instead of the JSON list it asked for. The parser found no JSON, so nothing was extracted, the update call got an empty list, and nothing was stored; no error anywhere. Session '+(l[0][0]+1)+'\'s reply, verbatim:</p><pre class="code">'+esc(l[0][1])+'</pre>'+ans('paper_local|haiku','q_tests'),
        'count extracted facts per conversation and alert on zero for a non-trivial conversation; use constrained output; keep the raw conversation for replay.')}
    if(F.GR.haiku){h+=card('Facts never written (Graphiti)','<p>Graphiti stores facts as relations between two entities. Facts that are attributes or numbers (the $200 budget, $143 spent, four engineers, the original test command, the Friday CSV report, the talk outline) became no edge at all; the raw episode still holds them, but edge search never returns episodes.</p>'+ans('graphiti_haiku|haiku','q_budget')+ans('graphiti_haiku|haiku','q_team'),
        'search episodes as well as edges (or use a search recipe that returns them), define custom entity and edge types for the facts you care about, and test recall on attribute-style questions.');
      const wr=F.GR.haiku.e.filter(e=>e.v==='wrong');
      h+=card('Wrong invalidation (Graphiti)','<p>'+wr.length+' of '+V['gr.haiku.closed']+' closed edges were closed wrongly, each by a model\'s "contradicts" judgement:</p><ul class="tight">'+wr.map(e=>'<li>'+esc(e.f)+' <span class="mute">(valid '+(e.va||'undated')+' to '+e.ia+')</span></li>').join('')+'</ul><p>And '+V['gr.haiku.nodated']+' edges have no valid_at, so the closing rule can never retire them: "user\'s eval set has 40 tasks" stayed current after the set grew to 60.</p>'+ans('graphiti_haiku|haiku','q_eval_size'),
        'review closures on a sample, ask the model for the reason with each contradiction, and require a date (fall back to the episode\'s time) so every fact can be retired.')}
    if(F.GR.local){const lost=F.GR.local.err.map((e,i)=>e?i:-1).filter(i=>i>=0);
      h+=card('Episodes lost on a parse error (Graphiti, local writer)','<p>With the 4B model writing, '+lost.length+' of the first '+F.GR.local.err.length+' episodes failed after Graphiti\'s retries'+(lost.length?' (sessions '+lost.map(i=>i+1).join(', ')+')':'')+'. The local server ignores <code>response_format</code>, so the JSON schema was only appended to the prompt; asked whether a new fact duplicates or contradicts an old one, the model answered by echoing that schema back, with one closing brace too many ("Extra data"), identically on every retry at temperature 0. Every episode that has an older fact to compare against therefore fails, so the run was stopped after three. <code>add_episode</code> raised, so a caller that logs and continues has lost those facts for good. Mem0\'s code takes the quieter route: when the extraction reply does not parse it logs an error and stores nothing, returning an empty list ({{main.py|m0:mem0/memory/main.py#L973-L991}}); not observed here because Haiku always returned valid JSON.</p>',
        'use a writer that supports constrained output, alert on every failed write, and keep the raw conversation so a failed extraction can be replayed.')}
    if(F.LT&&F.LT.ans&&Object.keys(F.LT.ans).length){const A=F.LT.ans,qs=F.Q.filter(q=>A[q.id]),ns=qs.filter(q=>!A[q.id].calls.some(c=>/search/.test(c[0])));const ex=ns.find(q=>q.t!=='ABS'&&F.A['letta|local'][q.id]&&!F.A['letta|local'][q.id][1]);
      h+=card('Never searching (Letta, local model)','<p>Everything Sam said after session 1 lived in archival notes, outside the prompt. On '+ns.length+' of '+qs.length+' questions the agent answered without calling a search tool.</p>'+(ex?ans('letta|local',ex.id):''),
        'put the facts that matter in the always-visible block (instruct the model to), tell it when to search, or let the harness search before the model answers; the sibling page {{Personal agents|n:3c75c17b0d0d81bf9462fbeb09593e1c}} measured the same failure and the one-sentence fix.')}
    h+=card('Wrong day arithmetic, even with everything in the window','<p>Temporal questions failed for every design, including the full-history baseline: "yesterday" resolved to the day Sam said it, and "Saturday" to the wrong Saturday. Memory layers that store a resolved date make this worse when they resolve it wrongly once, because the wrong date is then repeated as fact.</p>'+ans('full|haiku','q_incident_when')+ans('full|haiku','q_order'),
      'resolve relative dates at write time against the message timestamp, store both the phrase and the resolved date, and include date arithmetic in your test set.');
    el.innerHTML=h;RD.tabLinks(el)}
  // costs
  const tb=document.getElementById('fmem-cost');
  if(tb&&F.COST){const lab=k=>{const s=FM.SYS.find(x=>x.k===k);return s?s.l+(s.w?' ('+s.w+')':''):k};
    const n=v=>v==null?'<span class="mute">-</span>':Number(v).toLocaleString();
    tb.innerHTML='<tr><th>Memory (writer)</th><th class="num">Write calls, 12 sessions</th><th class="num">Tokens in</th><th class="num">Tokens out</th><th class="num">Model time (s)</th><th class="num">API-price equivalent</th><th class="num">Search per question (ms)</th><th class="num">Memory text per question (chars)</th></tr>'+
      F.COST.map(c=>'<tr><td>'+lab(c.k)+'</td><td class="num">'+(c.w?n(c.w.n):'0')+'</td><td class="num">'+(c.w?n(c.w.in):'-')+'</td><td class="num">'+(c.w?n(c.w.out):'-')+'</td><td class="num">'+(c.w?n(c.w.s):'-')+'</td><td class="num">'+(c.w&&c.w.cost!=null?'$'+c.w.cost.toFixed(3):'<span class="mute">local</span>')+'</td><td class="num">'+(c.rs==null?'<span class="mute">in-agent</span>':n(c.rs))+'</td><td class="num">'+n(c.ctx)+'</td></tr>').join('');
    const lt=F.COST.find(c=>c.k==='letta'),f=document.getElementById('fmem-costfind');
    if(f&&lt&&lt.rd)f.innerHTML='<p class="small">Letta has no separate search step: answering the 25 questions took '+n(lt.rd.n)+' model calls ('+n(lt.rd.in)+' tokens in) inside its own loop, '+(lt.rd.n/25).toFixed(1)+' per question, against one call per question for every other design. Mem0\'s token count is dominated by its extraction prompt (7,924 tokens with the Qwen tokenizer; Claude counts its own way), which Claude\'s prompt cache served from the second session on.</p>';}
})();
