"""Write ../parts/32_js_calc_0data.js from model.py (models recounted from config.json, chips, recipes) and recompute.json checks."""
import json, os
from model import MODELS, CHIPS, RECIPES, FMT, lora_params, HERE
rc = json.load(open(os.path.join(HERE, "recompute.json")))
keep = ("name", "src", "L", "h", "nh", "nkv", "hd", "V", "P", "Pact", "Pexp", "E", "k", "moeL", "exp1", "kv_full", "kv_slide", "window", "kv_el", "dqk", "dv", "layer_params", "fmt", "fmt_note")
M = {k: {kk: m.get(kk, 0) for kk in keep} for k, m in MODELS.items()}
for k in M: M[k]["lora"] = lora_params(MODELS[k])
def fmt_of(c):
    w = c["what"]
    if w.startswith("Old page: 8B"): return "days"
    if w.startswith("Old page:"): return "tps"
    if "MFU" in w or "share" in w: return "pct"
    if "cost" in w or "price" in w: return "usd"
    if "KV" in w or "cache" in w: return "bytes"
    if "parameters" in w: return "params"
    if "weights as released" in w: return "gb"
    if "days" in w or "176" in c["pub"]: return "days"
    if "ceiling" in w or "context" in w: return "tps"
    return "flops"
for c in rc["checks"]: c["fmt"] = fmt_of(c)
D = dict(models=M, chips=CHIPS, recipes=RECIPES, fmt=FMT, checks=rc["checks"])
js = "// ---- Performance calculator (t-calc): data generated by src/calc/gen_data.py from model.py; do not edit by hand ----\nwindow.CALCD=" + json.dumps(D, separators=(",", ":")) + ";\n"
open(os.path.join(HERE, "..", "parts", "32_js_calc_0data.js"), "w").write(js)
print(len(js))
