"""Write parts/33_js_plan_0data.js (window.PLND) from plan.py, sources.json, out/calib.json, out/validate.json
and the MLPerf extract, and out/plan_ref.json (cases the page's JavaScript must reproduce)."""
import csv, json, os
from plan import *

H = os.path.dirname(os.path.abspath(__file__))
PARTS = os.path.join(H, "..", "parts")
CAL = json.load(open(os.path.join(H, "out", "calib.json")))
VAL = json.load(open(os.path.join(H, "out", "validate.json")))
BENCH = os.path.join(H, "inputs", "m1_bench.json")
M1 = json.load(open(BENCH)) if os.path.exists(BENCH) else None

MK = ("name", "src", "L", "h", "nh", "nkv", "hd", "V", "P", "Pact", "Pexp", "E", "k", "moeL", "exp1", "kv_full", "kv_slide",
      "window", "kv_el", "dqk", "dv", "fmt", "fmt_note", "ffa", "mla", "emb", "api")
ORDER = ["l8", "l70", "l405", "q06", "q17", "q4", "q8", "q32", "q30", "q235", "dsv3", "dsr1", "oss20", "oss120"]
models = {k: {f: MODELS[k].get(f, 0) for f in MK} for k in ORDER}
CK = ("name", "peak", "mem", "bw", "up", "upN", "out", "price", "price_src", "pcie", "lat", "tpmax", "util")
CORDER = ["h100", "h200", "b200", "mi300x", "l40s", "rtx5090", "m1pro"]
chips = {k: {f: CHIPS[k].get(f) for f in CK} for k in CORDER}
for k in CORDER:
    p = SRC["gpu_prices_usd_per_gpu_hour"][k]
    chips[k]["price_url"] = p.get("url")
    chips[k]["price_also"] = p.get("also")

F = CAL["fits"]
engines = {
    "vllm": dict(name="vLLM, fitted to MLPerf v5.1 on one H100", eff_c=F["h100"]["eff_c"], tovh=F["h100"]["tovh"], eff_m=0.8, tseq=0.0),
    "trt": dict(name="TensorRT-LLM, fitted to MLPerf v5.1 on 8x H200", eff_c=F["h200"]["eff_c"], tovh=F["h200"]["tovh"], eff_m=0.8, tseq=0.0),
    "vllm_l40s": dict(name="vLLM, fitted to MLPerf v5.1 on one L40S", eff_c=F["l40s"]["eff_c"], tovh=F["l40s"]["tovh"], eff_m=0.8, tseq=0.0),
    "roof": dict(name="Roofline ceiling (100%, no overhead)", eff_c=1.0, tovh=0.0, eff_m=1.0, tseq=0.0),
}
if M1 and M1.get("fit"):
    engines["m1"] = dict(name=M1["fit"]["name"], eff_c=M1["fit"]["eff_c"], tovh=M1["fit"]["tovh"], eff_m=M1["fit"]["eff_m"], tseq=M1["fit"]["tseq"])

mlp = []
for r in csv.DictReader(open(os.path.join(H, "inputs", "mlperf_llm_single_node.csv"))):
    mlp.append(dict(v=r["version"], who=r["submitter"], model=r["model"], sc=r["scenario"], tps=float(r["result"]),
                    acc=r["accelerator"], n=int(r["per_node"]), sw=r["software"], w=r["weights"]))

D = dict(models=models, chips=chips, order=ORDER, corder=CORDER, engines=engines, int4_bits=INT4_BITS, q4km_bits=Q4KM_BITS, block=BLOCK,
         fmt=HW.FMT, api=SRC["api_prices_usd_per_million"], vllm=SRC["vllm_defaults"], rules=SRC["mlperf_rules"],
         calib=CAL, validate=VAL, mlperf=mlp, m1=M1, default=DEFAULT,
         redhat=SRC["redhat_mlperf51"], sglang=SRC["sglang_dsv3"], nref=12)
os.makedirs(PARTS, exist_ok=True)
with open(os.path.join(PARTS, "33_js_plan_0data.js"), "w") as f:
    f.write("// ---- Capacity planner data (t-plan), generated by src/plan/gen_data.py from plan.py and inputs/; do not edit ----\n")
    f.write("window.PLND=" + json.dumps(D, separators=(",", ":"), ensure_ascii=False) + ";\n")

# ---------- reference cases for the JavaScript check ----------
CASES = [
    DEFAULT,
    dict(DEFAULT, model="l8", chip="h100", fmt="fp8", kvb=1, P=778, O=128, share=0.0, tb=1024, seqs=512, util=0.91, slo_tpot=0.1),
    dict(DEFAULT, model="l70", chip="h100", fmt="bf16", tp=2, kvb=2),
    dict(DEFAULT, model="l70", chip="h100", fmt="bf16", tp=4, pp=2, kvb=1, lam=50),
    dict(DEFAULT, model="dsv3", chip="h200", fmt="native", tp=8, kvb=2, lam=10, api="median"),
    dict(DEFAULT, model="dsv3", chip="h100", fmt="native", tp=72, ep=1, kvb=1, overlap=1, P=2000, O=1000, share=0.0, lam=200, tb=16384, seqs=256),
    dict(DEFAULT, model="oss120", chip="h100", fmt="native", tp=1, kvb=2, P=1000, O=1000, share=0.2, lam=5),
    dict(DEFAULT, model="q30", chip="l40s", fmt="fp8", kvb=1, P=6000, O=500, share=0.3, tb=2048, seqs=256, eff_c=0.248, tovh=18.0, lam=1),
    dict(DEFAULT, model="q17", chip="m1pro", fmt="int4", kvb=2, P=500, O=200, share=0.0, tb=512, seqs=8, lam=0.2, price=0),
    dict(DEFAULT, model="l405", chip="b200", fmt="fp8", tp=8, kvb=1, lam=3, price=6.69),
    dict(DEFAULT, model="q235", chip="mi300x", fmt="fp8", tp=4, kvb=1, lam=8, price=2.59),
    dict(DEFAULT, model="oss20", chip="rtx5090", fmt="native", tp=1, kvb=2, lam=2, price=0.99),
]


def slim(r):
    if r is None:
        return None
    if isinstance(r, dict):
        return {k: slim(v) for k, v in r.items() if not isinstance(v, str)}
    return r


ref = []
for o in CASES:
    r = plan(o)
    s = r["setup"]
    one = dict(inp=o, out=slim(r))
    one["steps"] = [dict(B=B, c=c, out=slim(step(o, s, B, c))) for B, c in ((1, 0), (16, 512), (64, 0), (8, 2000))]
    ref.append(one)
u = rng(7)
ref.append(dict(rng=[u() for _ in range(5)]))
json.dump(ref, open(os.path.join(H, "out", "plan_ref.json"), "w"), indent=0)
print("wrote data", os.path.getsize(os.path.join(PARTS, "33_js_plan_0data.js")), "bytes;", len(ref), "cases")
