"""Slim the toy's measured results into parts/_gen_toydata.js (window.TOYR) for the page.

  python3 mk_toydata.py      (build.sh runs it; needs model/results.json, model/check_forward.json, model/distill.json if present)
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
M = lambda f: os.path.join(HERE, 'model', f)
R = json.load(open(M('results.json')))
out = {'test': R['test'], 'budgets': R['budgets'], 'variants': {}}
for v, V in R['variants'].items():
    out['variants'][v] = {
        'params': V['params'], 'overlap': V['overlap'],
        'modes': {m: {'acc': x['acc'], 'mean_think': x['mean_think'], 'per_n': x['per_n']} for m, x in V['modes'].items()},
        'sweep': [{k: s[k] for k in ('b', 'acc', 'cut', 'finished', 'acc_finished', 'acc_cut', 'cut_eq_last', 'cut_eq_nothink', 'mean_think')} for s in V['sweep']],
        'log': [{k: r[k] for k in r if k in ('step', 'loss', 'think', 'nothink')} for r in V['log']]}
out['check'] = json.load(open(M('check_forward.json'))) if os.path.exists(M('check_forward.json')) else None
if os.path.exists(M('distill.json')):
    D = json.load(open(M('distill.json')))
    keep = ('step', 'pass1_greedy', 'pass16', 'trace_pass16', 'student_fwd', 'student_bwd', 'teacher_fwd')
    out['distill'] = {'runs': [{'seed': r['seed'], 'cfg': r['cfg'], 'steps': r['steps'], 'student_params': r['student_params'],
                                'off': r['off']['eval'], 'off_seconds': r['off']['seconds'],
                                'rl': [{k: c[k] for k in keep if k in c} for c in r['rl']['curve']], 'rl_seconds': r['rl']['seconds'],
                                'od': [{k: c[k] for k in keep if k in c} for c in r['od']['curve']], 'od_seconds': r['od']['seconds']} for r in D['runs']]}
js = '// Generated by mk_toydata.py from model/results.json, model/check_forward.json and model/distill.json.\nwindow.TOYR=' + json.dumps(out, separators=(',', ':')) + ';\n'
open(os.path.join(HERE, 'parts', '_gen_toydata.js'), 'w').write(js)
print('mk_toydata:', len(js), 'bytes')
