// ---- Section 6: agent forwarding against ProxyJump, on the lab topology, from the recorded runs.
(function(){
  const fig=document.getElementById('ag-fig'),cap=document.getElementById('ag-cap');let mode='forward';
  const L=SSHD.logs;
  const got=(k,h)=>new RegExp('logged in to '+h).test(L['agent_'+k]||'');
  const S={
    forward:[
      {t:'1. Laptop logs in to the bastion with -A',p:'The laptop authenticates to the bastion with its key. Because of <code>ForwardAgent yes</code>, the bastion’s sshd creates a socket for this session that relays signing requests back to the laptop’s agent.',paths:[{a:'lap',b:'bas',label:'session + agent channel'}],badges:{bas:'agent socket'},hl:{bas:'on'}},
      {t:'2. The bastion’s ssh uses the forwarded agent',p:'Typed on the bastion, <code>ssh gpu-node-01</code> asks the socket to sign; the request travels back to the laptop, which signs. It worked: <code>gpu-node-01</code>.',paths:[{a:'lap',b:'bas',label:'sign request'},{a:'bas',b:'n1',label:'login as khalid',c:'var(--good)'}],hl:{n1:'good'},badges:{bas:'agent socket'}},
      {t:'3. Root on the bastion finds the socket',p:'Root lists sockets under <code>/home/khalid/.ssh/agent/</code> and runs <code>ssh-add -l</code> with it: the laptop’s key is listed. Root needs no file and no passphrase.',paths:[{a:'lap',b:'bas',label:'sign requests',c:'var(--bad)'}],hl:{bas:'bad'},badges:{bas:'root uses socket'},bc:{bas:'var(--bad)'}},
      {t:'4. Root logs in to the nodes as Khalid',p:'With the socket, root ran <code>ssh khalid@gpu-node-01</code> and <code>ssh khalid@gpu-node-02</code>. Recorded: gpu-node-01 '+(got('forward','gpu-node-01')?'<b>logged in</b>':'refused')+', gpu-node-02 '+(got('forward','gpu-node-02')?'<b>logged in</b>':'refused')+'.',paths:[{a:'lap',b:'bas',c:'var(--bad)'},{a:'bas',b:'n1',label:'root as khalid',c:'var(--bad)'},{a:'bas',b:'n2',label:'root as khalid',c:'var(--bad)'}],hl:{n1:got('forward','gpu-node-01')?'bad':'good',n2:got('forward','gpu-node-02')?'bad':'good',bas:'bad'}}],
    constrained:[
      {t:'1. Load the key with destination constraints',p:'<code>ssh-add -h bastion -h "bastion&gt;gpu-node-01"</code>: the agent may sign for the laptop-to-bastion login and for the bastion-to-gpu-node-01 hop only, identified by host keys (OpenSSH 8.9 and later).',paths:[],hl:{lap:'on'},badges:{lap:'agent: 2 allowed hops'}},
      {t:'2. Log in with -A; the bastion hops to gpu-node-01',p:'Each login binds the session to the server’s host key (<code>session-bind@openssh.com</code>), so the agent knows which hop is asking. The allowed hop worked: <code>gpu-node-01</code>; the session’s own attempt at gpu-node-02 got <code>Permission denied (publickey)</code>.',paths:[{a:'lap',b:'bas',label:'session + agent'},{a:'bas',b:'n1',label:'allowed',c:'var(--good)'},{a:'bas',b:'n2',label:'refused',c:'var(--bad)',dash:1}],hl:{n1:'good',n2:'bad'}},
      {t:'3. Root tries the same trick',p:'Root found the socket and listed the key. Recorded: gpu-node-01 '+(got('constrained','gpu-node-01')?'<b>logged in</b> (the allowed hop is still usable by anyone on the bastion)':'refused')+', gpu-node-02 '+(got('constrained','gpu-node-02')?'logged in':'<b>refused</b>')+'. Constraints narrow the damage; they do not remove it.',paths:[{a:'lap',b:'bas',c:'var(--bad)'},{a:'bas',b:'n1',label:'root: allowed hop',c:'var(--bad)'},{a:'bas',b:'n2',label:'root: refused',c:'var(--good)',dash:1}],hl:{bas:'bad',n1:got('constrained','gpu-node-01')?'bad':'good',n2:got('constrained','gpu-node-02')?'bad':'good'}}],
    proxyjump:[
      {t:'1. Laptop logs in to the bastion, asks for a stream',p:'The laptop authenticates to the bastion and opens one <code>direct-tcpip</code> channel to <code>gpu-node-01:22</code>. No agent channel exists.',paths:[{a:'lap',b:'bas',label:'outer session'}],hl:{bas:'on'}},
      {t:'2. A second SSH session runs end to end',p:'The laptop runs a complete handshake and login with gpu-node-01 inside that stream: host key checked by the laptop, signature made by the laptop. The bastion relays ciphertext.',paths:[{a:'lap',b:'bas',label:'outer'},{a:'lap',b:'bas',label:'',c:'var(--good)',off:1.2},{a:'bas',b:'n1',label:'inner session (end to end)',c:'var(--good)'}],hl:{n1:'good'}},
      {t:'3. Root on the bastion looks for an agent socket',p:'Recorded: nothing found, so nothing to use: <code>'+(/\nsocket: \//.test(L.agent_proxyjump||'')?'a socket was found':'no socket')+'</code>. Root can see that a connection to gpu-node-01:22 exists and how many bytes cross it, nothing more.',paths:[{a:'lap',b:'bas'},{a:'bas',b:'n1',c:'var(--good)'}],hl:{bas:'good'},badges:{bas:'no socket to steal'},bc:{bas:'var(--open2)'}}]};
  function draw(i){const st=S[mode][Math.min(i,S[mode].length-1)];TOPO.draw(fig,st);cap.innerHTML='<div class="t">'+st.t+'</div><p>'+st.p+'</p>'}
  const A=RD.anim({card:'ag-card',ctl:'ag-ctl',n:S.forward.length,draw,ms:2600,label:'Step'});
  RD.seg(document.getElementById('ag-seg'),m=>{mode=m;A.reset(S[m].length)});
  RD.onResize(()=>A.redraw());
})();
