// ---- Error decoder tab: recorded error messages, what they mean, how to dig, how to fix.
(function(){
  const L=SSHD.logs;
  const E=[
   {m:'ssh: connect to host ... port ...: Connection refused',log:'errors_extra',re:/Connection refused/,mean:'TCP reached the machine and nothing was listening on that port (or a firewall actively rejected it). SSH never started.',dig:'<code>ssh -v</code> (the "Connecting to" line shows the address and port actually used); <code>nc -vz host port</code>.',fix:'Right host and port? Is sshd running? For a compute node: are you going through the bastion (ProxyJump)?',sec:'s-dbg'},
   {m:'Unable to negotiate with ...: no matching key exchange method found. Their offer: ...',log:'errors_extra',re:/Unable to negotiate/,mean:'The two KEXINIT lists have nothing in common for one category. The message prints the server\u2019s offer.',dig:'<code>ssh -vv</code> shows both lists; <code>ssh -Q kex</code> lists what your client supports.',fix:'Upgrade the server or fix its hand-written algorithm list. As a last resort enable one algorithm for that host only (<code>Host old</code> then <code>KexAlgorithms +...</code>).',sec:'s-pq'},
   {m:'** WARNING: connection is not using a post-quantum key exchange algorithm.',log:'pq_warning',re:/WARNING|store now|upgraded/,mean:'Since OpenSSH 10.1 the client warns when the negotiated key exchange is classic only: recorded sessions could be decrypted by a future quantum computer.',dig:'<code>ssh -v host true 2&gt;&amp;1 | grep "kex: algorithm"</code>',fix:'Server: OpenSSH 9.0+ (sntrup761) or 9.9+ (ML-KEM) with default KexAlgorithms. Client, if you accept the risk for one host: <code>Match host X</code> then <code>WarnWeakCrypto no-pq-kex</code>.',sec:'s-pq'},
   {m:'WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!',log:'hk_changed_acceptnew',re:/WARNING|Offending|fingerprint|SHA256|changed/,mean:'The server presented a different host key from the one in known_hosts. Either the machine was rebuilt or re-keyed, or someone is in the middle.',dig:'Compare the printed SHA256 fingerprint with the real one obtained another way (console, admin, <code>ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub</code> on the machine).',fix:'Only after the fingerprints match: <code>ssh-keygen -R host</code>. For fleets that rebuild often: host certificates.',sec:'s-hk'},
   {m:'No ED25519 host key is known for ... and you have requested strict checking. Host key verification failed.',log:'hk_strict_unknown',re:/No ED25519|verification failed/,mean:'The host is unknown and StrictHostKeyChecking is yes (or BatchMode prevented the question).',dig:'<code>ssh-keygen -F host -f known_hosts</code>; <code>ssh -G host | grep -i stricthost</code>.',fix:'Add the verified key (or an @cert-authority line), or use accept-new for genuinely ephemeral hosts in their own known_hosts file.',sec:'s-hk'},
   {m:'Certificate invalid: name is not a listed principal (host certificate)',log:'hk_cert_wrong_name',re:/invalid|No ED25519|failed/,mean:'The node\u2019s host certificate was issued for a different name than the one you connected to, so the CA line does not vouch for it, and no plain key is known either.',dig:'<code>ssh -v</code> shows "Server host certificate: ... ID ..."; on the node <code>ssh-keygen -L -f /etc/ssh/ssh_host_ed25519_key-cert.pub</code>.',fix:'Re-sign the host key with the names clients use (<code>-n gpu-node-01,gpu-node-01.cluster.internal</code>).',sec:'s-cert'},
   {m:'Permission denied (publickey). (certificate expired, wrong principal, no principals, revoked)',log:'cert_expired',re:/Refusing|denied/,mean:'The server refused every key offered. The client is never told why; the server log is.',dig:'<code>ssh -v</code> (which keys were offered); <code>ssh-keygen -L -f id-cert.pub</code> (validity, principals); then the node\u2019s auth log: "Refusing certificate ID ... Certificate invalid: expired" or "name is not a listed principal" or "revoked by file".',fix:'Get a fresh certificate for the right principal; check the account name; check the KRL.',sec:'s-cert'},
   {m:'Permission denied (publickey). (user that does not exist)',log:'errors_extra',re:/nobody2|Permission denied/,mean:'Same message for a user that does not exist, deliberately, so attackers cannot enumerate accounts.',dig:'<code>ssh -G host | grep "^user"</code>; the server log says "Invalid user".',fix:'Set <code>User</code> for that host in your config.',sec:'s-keys'},
   {m:'Received disconnect from ...: Too many authentication failures',log:'too_many_auth',re:/Offering|Too many/,mean:'Each key offered and refused counts against MaxAuthTries (6 by default); the agent offered six wrong keys first.',dig:'<code>ssh -v</code> (count the Offering lines); <code>ssh -Z host</code> on 10.5+.',fix:'<code>IdentitiesOnly yes</code> and an explicit <code>IdentityFile</code> per host.',sec:'s-keys'},
   {m:'stdio forwarding failed',log:'errors_extra',re:/stdio forwarding failed/,mean:'ProxyJump\u2019s helper on the bastion could not open a connection to the target (unknown name, host down, port closed, or forwarding not allowed).',dig:'<code>ssh -v</code> shows the helper; log in to the bastion and try <code>nc -vz node 22</code> or <code>getent hosts node</code>.',fix:'Correct name as the <i>bastion</i> resolves it; node up; bastion allows TCP forwarding.',sec:'s-jump'},
   {m:'bind [127.0.0.1]:...: Address already in use / Could not request local forwarding.',log:'fwd_port_taken',re:/bind|Could not|exit/,mean:'The local port of a -L forward is taken. By default ssh carries on without the tunnel.',dig:'<code>lsof -nP -iTCP:PORT -sTCP:LISTEN</code>',fix:'Use another port, bind <code>127.0.0.1</code> explicitly, set <code>ExitOnForwardFailure yes</code>.',sec:'s-fwd'},
   {m:'curl: (97) Could not resolve host (through ssh -D)',log:'fwd_D',re:/resolve|exit 97|closed/,mean:'With plain socks5 the name is resolved on your laptop, which does not know cluster names.',dig:'Which proxy scheme did the tool use?',fix:'<code>socks5h://</code> or <code>--socks5-hostname</code> so the far side resolves; for services bound to a node\u2019s loopback use -L to that node.',sec:'s-fwd'},
   {m:'(no message: the terminal hangs)',log:'keepalive',re:/waiting|exited/,mean:'The path died silently (VPN, NAT timeout, frozen server). Without keepalives TCP waits for hours.',dig:'Type <code>~.</code> at the start of a line to kill the session.',fix:'<code>ServerAliveInterval 30</code>, <code>ServerAliveCountMax 3</code>.',sec:'s-alive'},
   {m:'(connection closed before the banner, after several failed logins)',log:'penalties',re:/penalty|drop connection/,mean:'PerSourcePenalties (OpenSSH 9.8+) is refusing your source address for a while after failed authentications. Behind a bastion or NAT, everyone shares that address.',dig:'Server log: "drop connection ... penalty: failed authentication".',fix:'Wait it out; fix the failing script; on internal nodes exempt the bastion with <code>PerSourcePenaltyExemptList</code>.',sec:'s-sec'},
   {m:'Killed by signal 1.',log:'hk_cert_ok',re:/Killed by signal/,mean:'Harmless: printed by the ProxyJump helper when the main session ends and closes it.',dig:'Nothing to do.',fix:'Add <code>-q</code> or <code>LogLevel ERROR</code> to the jump if it bothers you.',sec:'s-jump'}];
  const list=document.getElementById('err-list'),det=document.getElementById('err-detail'),q=document.getElementById('err-q');let cur=0;
  function show(i){cur=i;const e=E[i];list.querySelectorAll('button').forEach(b=>b.classList.toggle('on',+b.dataset.i===i));
    const t=(L[e.log]||'').split('\n');const keep=t.map(l=>e.re.test(l)?'<mark>'+RD.esc(l)+'</mark>':RD.esc(l)).join('\n');
    det.innerHTML='<h3>'+RD.esc(e.m)+'</h3><dl class="kv"><dt>Means</dt><dd>'+e.mean+'</dd><dt>Dig</dt><dd>'+e.dig+'</dd><dt>Fix</dt><dd>'+e.fix+'</dd></dl><p class="small">Reading: <a href="#'+e.sec+'" class="err-sec">section</a></p><div class="small mute">Recorded: src/raw/'+e.log+'.txt</div><pre class="blk log">'+keep+'</pre>';
    const mk=det.querySelector('mark'),pre=det.querySelector('pre');if(mk&&pre&&pre.offsetParent)pre.scrollTop=Math.max(0,mk.offsetTop-pre.offsetTop-20);
    det.querySelector('.err-sec').addEventListener('click',ev=>{ev.preventDefault();document.querySelector('#tabs button[data-t="t-read"]').click();const s=document.getElementById(e.sec);if(s)s.scrollIntoView({block:'start'})});}
  function render(){const f=(q.value||'').toLowerCase();list.innerHTML=E.map((e,i)=>(!f||(e.m+' '+e.mean).toLowerCase().includes(f))?'<button data-i="'+i+'"'+(i===cur?' class="on"':'')+'>'+RD.esc(e.m)+'</button>':'').join('')||'<p class="small mute">No recorded message matches.</p>'}
  list.addEventListener('click',ev=>{const b=ev.target.closest('button');if(b)show(+b.dataset.i)});
  q.addEventListener('input',render);render();show(0);
  RD.onRender(()=>show(cur),'t-err');
})();
