"""Parse raw/ into parts/22_js_data.js (window.ST_DATA). Every number the page draws comes from here."""
import json, re, pathlib
R = pathlib.Path("raw"); D = {}
txt = lambda n: (R / n).read_text()
# environment
env = txt("env.txt"); D["env_txt"] = env
kv = dict(re.findall(r"^([a-z_]+): (.+)$", env, re.M)); D["env"] = kv
D["jbd2"] = re.search(r"### jbd2[^\n]*\n(.*?)\n\n", env, re.S).group(1)
D["ext4_opts"] = re.search(r"### ext4 mount options[^\n]*\n(.*?)\n", env).group(1).strip()
# durability calls
sc = txt("synccost.txt"); rows = []
for part in sc.split("### ")[1:]:
    fs = "ext4" if part.startswith("durability") else "tmpfs" if part.startswith("the same") else None
    if not fs: continue
    for m in re.finditer(r"^(append|overwrite)\s+(\w+)\s+n (\d+) median_us ([\d.]+) p99_us ([\d.]+)", part, re.M):
        rows.append(dict(fs=fs, shape=m[1], mode=m[2], med=float(m[4]), p99=float(m[5])))
D["sync"] = rows
D["direct_txt"] = sc[sc.index("### O_DIRECT alignment"):].strip()
# readahead
ra = []
for b in txt("readahead.txt").split("## ")[1:]:
    head, *lines = b.strip().splitlines()
    m = re.match(r"(.*?): (\d+) reads of (\d+) B, ([\d.]+) ms, device (\d+) pages in (\d+) requests", head)
    ev = [list(map(int, l.split())) for l in lines[1:]]
    ra.append(dict(label=m[1], reads=int(m[2]), ms=float(m[4]), pages=int(m[5]), reqs=int(m[6]), ev=ev))
D["ra"] = ra
# writeback timelines
wb = {}
for p in sorted(R.glob("wb_*.txt")):
    s = p.read_text(); name = p.stem[3:]
    hdr = re.search(r"^scenario \w+: (.*?);", s, re.M).group(1)
    fs = re.search(r"fsync took ([\d.]+) s", s)
    rows = []
    for l in s.splitlines():
        f = l.split()
        if len(f) == 6 and re.match(r"^[\d.]+$", f[0]):
            rows.append([float(f[0]), float(f[1]), float(f[2]), float(f[3]), int(f[4]), f[5]])
    last = max([r[0] for r in rows if r[1] > 1] or [0])
    keep = [r for i, r in enumerate(rows) if r[0] < 3 or i % 5 == 0 or abs(r[0] - last) < 0.11]
    wb[name] = dict(head=hdr, fsync_s=float(fs[1]) if fs else None, last_dirty_s=last, rows=keep,
                    wchans=sorted(set(r[5] for r in rows)))
D["wb"] = wb
# fio
fio = {}
for m in re.finditer(r"^(\S+)\s+(read|write)\s+iops\s+([\d.]+)\s+MiB/s\s+([\d.]+)\s+clat_mean_us\s+([\d.]+)\s+clat_p99_us\s+([\d.]+)", txt("fio.txt"), re.M):
    fio[m[1]] = dict(dir=m[2], iops=float(m[3]), mibs=float(m[4]), mean=float(m[5]), p99=float(m[6]))
D["fio"] = fio
u = txt("uring.txt")
m = re.search(r"randread_4k_qd16_iouring\s+read\s+iops\s+([\d.]+)\s+MiB/s\s+([\d.]+)\s+clat_mean_us\s+([\d.]+)\s+clat_p99_us\s+([\d.]+)", u)
fio["randread_4k_qd16_iouring"] = dict(dir="read", iops=float(m[1]), mibs=float(m[2]), mean=float(m[3]), p99=float(m[4]))
D["uring_txt"] = u
D["fio_fail"] = re.findall(r"^(\S+ failed: .*)$", txt("fio.txt"), re.M)
# metadata
D["meta"] = [dict(label=m[1].strip(), ms=float(m[2]), note=(m[3] or "")) for m in re.finditer(r"^(.+?) {2,}([\d.]+) ms(?:  \((.*)\))?$", txt("meta.txt"), re.M)]
D["fsimage_txt"] = txt("fsimage.txt")
# checkpoints
ck = []
for m in re.finditer(r"^(.+?)\s+median\s+([\d.]+) ms\s+min\s+([\d.]+)\s+max\s+([\d.]+)\s+dirty after\s+([\d.]+) MiB ?(.*)$", txt("ckpt_time.txt"), re.M):
    ck.append(dict(label=m[1].strip(), med=float(m[2]), mn=float(m[3]), mx=float(m[4]), dirty=float(m[5]), note=m[6].strip()))
D["ckpt"] = ck
D["ckpt_state"] = re.search(r"^state: (.*)$", txt("ckpt_time.txt"), re.M).group(1)
tr = {}
for b in txt("ckpt_trace.txt").split("### ")[1:]:
    name, *lines = b.strip().splitlines(); tr[name] = "\n".join(lines)
D["trace"] = tr
s = "window.ST_DATA=" + json.dumps(D, separators=(",", ":")) + ";\n"
pathlib.Path("parts/22_js_data.js").write_text("// ---- Generated by gen_data.py from raw/: do not edit ----\n" + s)
print("22_js_data.js", len(s), "bytes")
