# Write coverage.json: every fact of the old page (live.md, fetched 2026-09-30) and where this page carries it, or which sibling owns it.
# Section ids: rd-one, rd-der, rd-rules, rd-grad, rd-tay, rd-loss, rd-hess, rd-gd, rd-rate, rd-mom, rd-newton, rd-qn, rd-xgb, rd-cvx, rd-lag, rd-lagml, rd-sgd, rd-land, rd-which, rd-mist; tabs t-lab, t-more.
import json
MC = 'matrix_calculus_and_backprop (sibling #2; handoff_matrix_calculus_and_backprop.md); linked from'
C = [
 ('Embed calculus-and-optimisation-for-ml.html (interactive built outside the repo)', 'replaced by this page (Reading figures and animation, Optimisation lab)', 'element'),
 ('25 min read, +8h 45m resources', 'about 45 min Reading (rd-time); resources timed one by one in t-more', 'updated'),
 ('Training = choose theta to make scalar loss L small; calculus says which way is down and how sharply it curves', 'rd-one lead', 'verified'),
 ('Four questions: which way is down (gradient, p - y at output), how to get the gradient of a billion parameters (reverse-mode AD), how far to step (curvature, Hessian), when is the answer guaranteed (convexity, Lagrange)', 'rd-one table and one-idea box; reverse-mode AD: ' + MC + ' rd-one', 'verified'),
 ('Picture: gradient = local linear model, Hessian = local quadratic model, optimiser = how far to trust the model', 'rd-one key box, rd-tay table "every optimiser is a Taylor model plus a trust rule"', 'verified; extended'),
 ('Definition: gradient g_i = dL/dtheta_i; points to steepest increase; L(theta+delta) ~ L + g^T delta', 'rd-grad (with steepest-ascent proof via the cosine), rd-der (linear approximation)', 'verified'),
 ('Definition: Jacobian m x n, row i = gradient of output i; layouts on the linear-algebra page; autograd returns gradient in the shape of the parameter', 'rd-grad paragraph linking ' + MC.split(';')[0], 'owned by matrix_calculus_and_backprop'),
 ('Definition: Hessian H_ij = d2L/dtheta_i dtheta_j, symmetric when continuous; eigenvalues = curvatures (large steep, small flat, negative downward)', 'rd-hess (Schwarz, spectral theorem, x^2 y example)', 'verified; also the sibling handoff text'),
 ('Definition: logit z, raw score before sigmoid/softmax', 'rd-loss setup', 'verified'),
 ('Definition: stationary (critical) point g = 0: min, max or saddle', 'rd-hess', 'verified'),
 ('Definition: gradient descent theta <- theta - eta g, learning rate eta > 0', 'rd-gd (derived)', 'verified'),
 ('Definition: condition number kappa = lambda_max/lambda_min of H at a minimum', 'rd-rate', 'verified'),
 ('Flagged question: differentiation of each cost function; all give prediction minus target', 'rd-loss', 'verified'),
 ('MSE L = (1/n) sum (yhat - y)^2, dL/dz_i = (2/n)(yhat_i - y_i); 2/n absorbed by learning rate', 'rd-loss "Mean squared error, and the factor of a half" (both conventions, PyTorch MSELoss has no half)', 'verified; convention made explicit as the root Gradient lab corrected'),
 ('Linear regression gradient (2/n) X^T (Xw - y); normal equations X^T X w = X^T y; residual orthogonal to columns', 'rd-loss', 'verified'),
 ('Worked normal equations: (1,1),(2,3),(3,4); X^TX [[3,6],[6,14]], X^Ty (8,19), det 6, w = (-1/3, 3/2), residuals (0.167,-0.333,0.167) orthogonal', 'rd-loss', 'verified (recompute.py ne_w, ne_res)'),
 ('BCE L = -[y log p + (1-y) log(1-p)], p = sigma(z)', 'rd-loss', 'verified'),
 ('dL/dp = (p - y)/(p(1-p)); sigma\' = p(1-p); product p - y; factors cancel exactly', 'rd-loss; sigma\' derived in rd-rules', 'verified'),
 ('Compute BCE on logits: log(1+e^z) - yz = max(z,0) - yz + log(1+e^-|z|); BCEWithLogitsLoss', 'rd-loss', 'verified'),
 ('Worked BCE z = -6, y = 1: p 0.0025, loss 6.0025, grad -0.9975; z = 2: p 0.8808, loss 0.1269, grad -0.1192', 'rd-loss', 'verified'),
 ('Softmax CE L = -log p_y; softmax Jacobian p_k(delta_kj - p_j) = diag(p) - pp^T; gradient p - 1_y', 'rd-loss (two derivations: via log-sum-exp and via the Jacobian)', 'verified'),
 ('Soft labels: L = -sum q_k log p_k, gradient p - q (distillation, label smoothing)', 'rd-loss (with a tiny-model example)', 'verified'),
 ('Worked CE z = (2,1,0.1): e^z (7.389,2.718,1.105) sum 11.212, p (0.659,0.242,0.099), loss 0.417, grad (-0.341,0.242,0.099); components sum to 0; finite differences reproduce to four decimals', 'rd-loss numbers box', 'corrected: sum 11.2125 rounds to 11.213 (11.212 printed); the rest verified. Finite-difference check: root Gradient lab panel 1 and rd-der use box'),
 ('Why the simplification matters 1: numerical stability, fused CrossEntropyLoss, log-sum-exp trick; (1000, 1001) -> 1001.313; e^1001 overflows float64', 'rd-loss "Why the cancellation matters" 2', 'verified'),
 ('Why 2: no vanishing gradient; MSE on sigmoid 2(p-y)p(1-p); at z=-6: -0.0049, about 200 times smaller', 'rd-loss "Why the cancellation matters" 1', 'verified; ratio 202.7, written "about 203 times"'),
 ('Why 3: K x K softmax Jacobian never materialised, O(K) fused gradient; K = vocabulary', 'rd-loss item 3', 'verified'),
 ('Why 4: GLM view, canonical link, gradient mean minus target; Bernoulli/categorical/Gaussian instances; NLL derivation on probability page', 'rd-loss "canonical link" (plus a Poisson worked example)', 'verified; extended'),
 ('Chain rule: Jacobians multiply; reverse mode carries a row vector, VJPs, never builds J; one backward pass gives all gradients', MC + ' rd-loss last paragraph, rd-which', 'owned by sibling; verbatim in handoff'),
 ('Backward costs about twice forward; training step about three forwards; 6N FLOPs per token, 2N forward 4N backward (Kaplan et al. 2020 sec 2.1)', MC + ' t-more (Matrix calculus card)', 'owned by sibling; verbatim in handoff'),
 ('Memory not compute binds; activation checkpointing; Chen et al. 2016 O(sqrt n) memory for one extra forward', MC + ' t-more (Distributed training card)', 'owned by sibling; verbatim in handoff'),
 ('Reverse mode right when outputs far fewer than inputs; forward mode JVPs, efficient for few inputs, n passes for a gradient', MC + ' rd-which last paragraph', 'owned by sibling'),
 ('Hessian-vector products Hv = grad(grad L . v), cost a small multiple of a gradient, never form H', 'rd-hess use box (link to sibling section 12); used in rd-land power iteration (measured)', 'verified; mechanics owned by sibling'),
 ('Example VJPs: Y = XW, Xbar = Ybar W^T, Wbar = X^T Ybar; elementwise phi\'; ReLU mask; bias sums rows', MC, 'owned by sibling; verbatim in handoff'),
 ('Worked logistic unit: x (1,2), w (0.5,-0.25), b 0.1, y 1; z 0.1, p 0.525, loss 0.644; zbar -0.475; wbar (-0.475,-0.950); bbar -0.475; xbar (-0.2375, 0.1188); step 0.1 -> w (0.5475,-0.155), b 0.1475, z 0.385, p 0.595', 'rd-loss last paragraph names the numbers and links the sibling (its section 5a carries the full example)', 'verified (recompute.py lu_*); full example owned by sibling'),
 ('Flagged question: second-order differentiation; Taylor L(theta+delta) ~ L + g^T delta + 1/2 delta^T H delta; along eigenvector curves like 1/2 lambda t^2', 'rd-tay, rd-hess', 'verified'),
 ('Newton: minimise quadratic model, gradient g + H delta, delta = -H^-1 g; divides each eigendirection by curvature; one step on a quadratic; invariant to linear reparameterisation', 'rd-newton (derived, animation, affine invariance); t-lab (one step on any quadratic, checked)', 'verified'),
 ('Newton needs H positive definite; negative eigenvalue heads to max or saddle; damping or trust region', 'rd-newton (with Dauphin quote and saddle-free Newton); t-lab', 'verified'),
 ('Impractical at n = 1e9: 1e18 entries, O(n^2) memory, O(n^3) solve', 'rd-newton (2 exabytes in 16-bit numbers)', 'verified'),
 ('Approximations: quasi-Newton L-BFGS from last few gradient differences', 'rd-qn (BFGS update formula, two-loop recursion, real race)', 'verified; extended'),
 ('K-FAC: per-layer Kronecker product of two small matrices', 'rd-newton list (Martens and Grosse 2015)', 'verified'),
 ('Hessian-free: solve H delta = -g by conjugate gradient with HVPs', 'rd-newton list (Martens 2010)', 'verified'),
 ('Adam second moment: running mean of squared gradients, closer to empirical Fisher diagonal than Hessian diagonal; divides by square root; crude diagonal proxy, not Newton; mechanics on Optimisers page', 'rd-newton list, rd-mist', 'corrected: exponential moving average, not running mean; Fisher link is the Adam paper\'s own remark (section 5, verified in text)'),
 ('XGBoost: one tree per round, second-order Taylor of the loss per example, g_i, h_i (XGBoost docs)', 'rd-xgb (Chen and Guestrin 2016, equations 2, 3 checked in the paper)', 'verified against the paper'),
 ('Leaf sums G_j, H_j; minimise G w + 1/2 (H + lambda) w^2; w* = -G/(H+lambda); obj* = -1/2 sum G^2/(H+lambda) + gamma T', 'rd-xgb (derived; equations 5, 6)', 'verified'),
 ('Split gain formula with gamma; lambda L2 on leaf values, gamma per leaf; w* is a damped Newton step; XGBoost needs second derivatives', 'rd-xgb (equation 7)', 'verified'),
 ('Worked XGBoost: labels 1,1,1,0 at prediction 0, lambda 1; g (-0.5,-0.5,-0.5,0.5), h 0.25; one leaf G -1, H 1, w* 0.5; split G_L -1.5 H_L 0.75 G_R 0.5 H_R 0.25; gain 0.493 - gamma; w_L 0.857, w_R -0.4', 'rd-xgb (numbers box and interactive)', 'verified (recompute.py xgb_*)'),
 ('Quadratic L = 1/2 theta^T H theta: GD per eigendirection theta_i^(t) = (1 - eta lambda_i)^t theta_i^(0)', 'rd-rate step 1', 'verified'),
 ('Stability: diverges if eta > 2/lambda_max', 'rd-rate step 2', 'verified'),
 ('Rate: best fixed step eta = 2/(lambda_max+lambda_min), contraction (kappa-1)/(kappa+1); ill-conditioning zig-zags', 'rd-rate step 3 (derived) and figure; real-data check 0.974 vs 0.977', 'verified; condition "at the best fixed step" stated (linear-algebra correction)'),
 ('Heavy-ball momentum with tuned settings: (sqrt kappa - 1)/(sqrt kappa + 1)', 'rd-mom (Goh 2017 formulas checked)', 'verified'),
 ('Normalisation layers and good initialisation are largely conditioning fixes', 'rd-rate use box', 'verified (as an explanation; linked Normalisation page)'),
 ('Edge of stability: full-batch GD, top Hessian eigenvalue rises until it hovers just above 2/eta; loss falls long-term, oscillates short-term (Cohen et al. 2021)', 'rd-land with the paper quoted and reproduced on a real network', 'verified; reproduced'),
 ('Worked conditioning: H = diag(1,10), kappa 10; diverges above 0.2; best step 2/11 = 0.182, contraction 0.818; 34.4 -> 35 steps for 1000x; momentum 0.519, about 11 steps; Newton one', 'rd-rate, rd-mom numbers boxes', 'verified (recompute.py q_*, hb_*); momentum 10.5 steps exactly'),
 ('Classifying critical points: H > 0 min, H < 0 max, mixed saddle, zero eigenvalue inconclusive; x^2 - y^2 saddle diag(2,-2)', 'rd-hess table and gallery (plus x^2 + y^4 vs x^2 - y^4)', 'verified'),
 ('In high dimensions saddles not local minima are the main obstacle (Dauphin et al. 2014); SGD noise helps escape; saddle unstable along negative curvature', 'rd-land, rd-sgd use box, t-lab saddle', 'verified (quote checked)'),
 ('Gauss-Newton and Fisher: PSD approximations of H; natural gradient preconditions by inverse Fisher; K-FAC approximates it', 'rd-newton list', 'verified; scope as in the root correction (Fisher = Gauss-Newton part, Martens 2020)'),
 ('Influence functions use H^-1', 'rd-land list (Koh and Liang 2017)', 'verified'),
 ('SAM seeks flat minima by minimising worst-case loss in a ball', 'rd-land (Foret et al. 2021; Dinh et al. 2017 caveat)', 'verified'),
 ('Optimal Brain Damage scores 1/2 H_ii w_i^2', 'rd-land list (LeCun et al. 1989), rd-hess use box', 'verified'),
 ('Convexity: chord definition; tangent condition, gradient zero is global min; H >= 0; consequences: local = global, first-order stationarity suffices, minimiser set convex', 'rd-cvx (three tests, Boyd 3.1.3, 3.1.4)', 'verified'),
 ('Worked convexity: x^2 between -1 and 3 at t 0.5: f(1) = 1 <= 5', 'rd-cvx and chord figure', 'verified'),
 ('Convex: least squares, logistic regression, SVMs, lasso; deep nets not (permutation symmetry, average of two minima not a minimum)', 'rd-cvx table and permutation argument', 'verified'),
 ('CE convex in logits, Hessian diag(p) - pp^T >= 0; last layer well behaved; convex function of a linear map is convex', 'rd-cvx, rd-hess', 'verified'),
 ('Strong convexity mu I <= H <= beta I; GD at eta = 1/beta shrinks gap by 1 - mu/beta = 1 - 1/kappa', 'rd-rate numbers box (Boyd equation 9.18), rd-cvx', 'verified'),
 ('Lagrange: optimise f subject to g = 0; gradients parallel; Lagrangian f - lambda g; stationary points in x and lambda; dL/dlambda = 0 is the constraint', 'rd-lag (with interactive circle figure)', 'verified'),
 ('Multiplier is a shadow price lambda = df*/dc', 'rd-lag', 'verified'),
 ('Worked Lagrange: max x + y on unit circle: x = y = 0.707, lambda 0.707, f* 1.414; f* = sqrt(2c), derivative 0.707 at c 1', 'rd-lag numbers box and figure', 'verified'),
 ('KKT: stationarity, feasibility, mu >= 0, complementary slackness; necessary and sufficient for convex problems with Slater', 'rd-lag (Boyd 5.5.3; plus a worked inequality example)', 'verified'),
 ('Softmax as maximum entropy, p_k proportional to e^{beta s_k}, inverse temperature set by the multiplier', 'rd-lagml (full derivation)', 'verified'),
 ('Regularisation as constraint: ||w||^2 <= t equivalent to loss + lambda ||w||^2', 'rd-lagml', 'verified'),
 ('SVM duality: one multiplier per example, zero except support vectors', 'rd-lagml, rd-lag duality paragraph', 'verified'),
 ('TRPO: maximise surrogate subject to average KL bound; constraint curvature is the Fisher; natural-gradient step via conjugate gradient; PPO replaced it', 'rd-lagml (derived from TRPO appendix C, equation 55; Bernoulli worked example)', 'verified against the paper; old link to the deleted "Deep RL" page replaced by Policy gradients and actor-critic'),
 ('Trade-offs table: GD/SGD, momentum/Adam, Newton, L-BFGS, Hessian-free/K-FAC, XGBoost leaves with uses, cost, when', 'rd-which', 'verified; Lagrange row added'),
 ('Derivatives: reverse mode for few outputs, forward mode for few inputs, HVPs for curvature', 'rd-which last paragraph (linked to sibling section 7)', 'owned by sibling'),
 ('Mistake: squashing twice', 'rd-mist', 'verified'),
 ('Mistake: log of softmax in two steps underflows; fused log-softmax', 'rd-mist', 'verified'),
 ('Mistake: MSE for classification, 200 times smaller', 'rd-mist (203 times)', 'verified'),
 ('Mistake: transposed gradients (paper vs autograd shape)', MC + ' (layouts)', 'owned by sibling'),
 ('Mistake: backprop costs the same as forward', MC, 'owned by sibling'),
 ('Mistake: Adam is a second-order method', 'rd-mist', 'verified'),
 ('Mistake: blaming the data for a learning-rate blow-up (2/lambda_max)', 'rd-mist', 'verified'),
 ('Mistake: treating g = 0 as a minimum', 'rd-mist', 'verified'),
 ('Mistake: Newton with an indefinite Hessian', 'rd-mist', 'verified'),
 ('Mistake: assuming the whole network is convex', 'rd-mist', 'verified'),
 ('Mistake: mixing up the lambdas (eigenvalue, multiplier, XGBoost L2)', 'rd-mist', 'verified'),
 ('How it connects: Topic: math, Linear algebra, Probability, Information theory, Loss functions, Optimisers, Classical ML, Distributed training, Deep RL (TRPO, PPO)', 't-more (all linked); Deep RL page replaced by Policy gradients and actor-critic and RL for LLMs', 'updated'),
 ('Resource: Parr and Howard, Matrix Calculus You Need (1h 30m)', 't-more', 'verified'),
 ('Resource: MML book ch. 5 and 7 (1h 45m)', 't-more', 'corrected time: about 6 h for the two chapters (the root re-estimated MML times)'),
 ('Resource: Boyd and Vandenberghe ch. 2-5 (5h)', 't-more (ch. 3, 5, 9: about 15 h)', 'corrected time (root: 20-30 h for ch. 2-5)'),
 ('Resource: CS231n backprop notes (30 min)', MC, 'owned by sibling (backprop)'),
 ('Further reading: XGBoost docs tutorial (20 min)', 't-more (with the Chen and Guestrin paper)', 'verified'),
 ('Further reading: Cohen et al. 2021 (1 h)', 't-more', 'verified'),
 ('Further reading: Dauphin et al. 2014 (45 min)', 't-more', 'verified'),
 ('Further reading: Chen et al. 2016 checkpointing (40 min)', MC, 'owned by sibling'),
 ('Further reading: Kaplan et al. 2020 sec. 2.1 (10 min)', MC, 'owned by sibling'),
]
out = [{'fact': f, 'where': w, 'note': n} for f, w, n in C]
json.dump(out, open('coverage.json', 'w'), indent=1)
print(len(out), 'facts;', sum('owned by' in o['note'] for o in out), 'owned by a sibling;', sum('corrected' in o['note'] for o in out), 'corrected')
