# Write parts/20_js_data.js from inputs/ (the real runs), compactly. usage: python3 mk_data.py
import json
E = json.load(open('inputs/eos_out.json'))['runs']
R = json.load(open('inputs/lr_out.json'))
D = json.load(open('inputs/lr_data.json'))
g = lambda v, s=4: float('%.*g' % (s, v))
eos = {}
for eta, r in E.items():
    every = r['every']; L = r['loss_each_step']
    eos[eta] = {'every': every, 'sharp': [round(q['sharp'], 3) for q in r['rec']],
                'loss': [g(L[min(i * every, len(L) - 1)]) for i in range(len(r['rec']))]}
# per-step zoom for the oscillation picture
eos['zoom'] = {'from': 3260, 'eta': '0.2', 'loss': [g(v, 6) for v in E['0.2']['loss_each_step'][3260:3361]]}  # the 100-step window with the most up-down changes
cur = {k: ([g(max(x, 1e-16), 3) for x in v] if k not in ('lbfgs_nfev', 'gd_armijo_nfev') else v) for k, v in R['curves'].items()}
cur['gd'] = cur['gd'][:501]; cur['gd_armijo_nfev'] = R['curves']['gd_armijo_nfev']
sgd = {k: [g(x, 3) for x in v] for k, v in R['sgd'].items()}
noise = {B: [g(v['measured']), g(v['formula'])] for B, v in R['summary']['noise_w0']['by_B'].items()}
data = {'eos': eos, 'lr': cur, 'sgd': sgd, 'noise': noise, 'x1': D['x1'], 's': D['s'], 'X2': D['X2'], 'lam': D['lam']}
s = json.dumps(data, separators=(',', ':'))
open('parts/20_js_data.js', 'w').write('// generated by mk_data.py from inputs/ (eos_out.json, lr_out.json, lr_data.json); do not edit\nwindow.CO_DATA=' + s + ';\n')
print(len(s), 'bytes')
