"""Thin the decoded figure curves (inputs/figs.json) for the page: Ramer-Douglas-Peucker in axis-normalised
units (tolerance 0.15% of each axis range; log axes in decades), so every kept point is a decoded vertex.
Writes parts/_gen_figs.js (window.FIGS). build.sh runs it."""
import json, math, os
HERE = os.path.dirname(os.path.abspath(__file__))
F = json.load(open(os.path.join(HERE, 'inputs', 'figs.json')))
TOL = 0.0015


def rdp(pts, tol, nx, ny):
    if len(pts) < 3: return pts
    P = [(nx(x), ny(y)) for x, y in pts]
    keep = [False] * len(pts); keep[0] = keep[-1] = True
    st = [(0, len(pts) - 1)]
    while st:
        a, b = st.pop(); (x1, y1), (x2, y2) = P[a], P[b]; dmax, im = 0, -1
        L = math.hypot(x2 - x1, y2 - y1) or 1e-12
        for i in range(a + 1, b):
            d = abs((y2 - y1) * P[i][0] - (x2 - x1) * P[i][1] + x2 * y1 - y2 * x1) / L
            if d > dmax: dmax, im = d, i
        if dmax > tol: keep[im] = True; st += [(a, im), (im, b)]
    return [p for p, k in zip(pts, keep) if k]


def thin(pts, xlog=False, ylog=False, nd=4, tol=TOL):
    if not pts: return pts
    xs = [math.log10(max(p[0], 1e-9)) if xlog else p[0] for p in pts]; ys = [p[1] for p in pts]
    xr = (max(xs) - min(xs)) or 1; yr = (max(ys) - min(ys)) or 1
    nx = (lambda x: (math.log10(max(x, 1e-9)) if xlog else x) / xr); ny = lambda y: y / yr
    out = rdp(pts, tol, nx, ny)
    return [[round(x, nd), round(y, nd)] for x, y in out]

O = {}
for k in ('fig2', 'fig7', 'fig8'):
    O[k] = {n: thin(v, xlog=True) for n, v in F[k]['series'].items()}
O['fig5'] = {n: thin(v) for n, v in F['fig5']['series'].items()}
O['fig6'] = {n: thin(v, nd=1, tol=0.006) for n, v in F['fig6']['series'].items()}
O['fig3'] = {n: {kk: thin(vv, nd=3) for kk, vv in v.items()} for n, v in F['fig3']['series'].items()}
O['fig3_phases'] = F['fig3']['phases']
O['fig10'] = {n: {kk: thin(vv, nd=1, tol=0.004) for kk, vv in v.items()} for n, v in F['fig10']['series'].items()}
O['fig11'] = {n: {kk: thin(vv, nd=1) for kk, vv in v.items()} for n, v in F['fig11']['series'].items()}
O['fig12'] = {n: dict(mem=thin([p for p in v['mem_line'] if p[0] >= -0.5], nd=1), cpu=thin(v['cpu_line_early'], nd=2), cpu_late=thin(v['cpu_line_late'], nd=2)) for n, v in F['fig12']['series'].items()}
O['fig13'] = dict(series=F['fig13']['series'], no_load=F['fig13']['no_load'])
s = '// Generated by mk_figdata.py from inputs/figs.json (decode_figs.py).\nwindow.FIGS=' + json.dumps(O, separators=(',', ':')) + ';\n'
open(os.path.join(HERE, 'parts', '_gen_figs.js'), 'w').write(s)
print('mk_figdata: %d bytes' % len(s), {k: sum(len(x) if isinstance(x, list) else 0 for x in (v.values() if isinstance(v, dict) else [])) for k, v in O.items()})
