// ---- Tables tab: Table 2 (sortable, deltas), Table 3 (metric switch), Figure 4, Figure 6 small multiples, Table 4, noise, granularity, overlap, checks ----
(function(){let view='raw',sortCol=-1,desc=true;
 const short=['BC+','DSQA','xBench','AgentIF','Pinch','Shop','Travel','Office','Odyssey'];
 function draw(){const rows=PT.t2.map(r=>{let v=r.v.slice();if(view==='d'){const b=r.model.startsWith('JIT-Agent + ')?T2[r.model.slice(12)]:null;v=b?v.map((x,i)=>x-b[i]):null}else if(view==='gpt'){v=v.map((x,i)=>x-T2['GPT-5.6'][i])}return {m:r.model,v,raw:r.v}}).filter(r=>r.v);
  rows.forEach(r=>r.avg=r.v.reduce((a,b)=>a+b,0)/9);
  if(sortCol>=0)rows.sort((a,b)=>desc?(sortCol===9?b.avg-a.avg:b.v[sortCol]-a.v[sortCol]):(sortCol===9?a.avg-b.avg:a.v[sortCol]-b.v[sortCol]));
  const rank=i=>PT.t2.map(r=>r.v[i]).sort((a,b)=>b-a);
  const sh=(raw,i)=>{if(view!=='raw')return '';const rk=rank(i).indexOf(raw[i]);return rk===0?' style="background:var(--open2);font-weight:700"':rk<3?' style="background:var(--soft)"':''};
  const fm=v=>view==='raw'?v.toFixed(1):(v>0?'+':v<0?'−':'')+Math.abs(v).toFixed(1);
  $('t2Tab').innerHTML='<thead><tr><th data-c="-1">Model</th>'+short.map((s,i)=>'<th class="num" data-c="'+i+'" style="cursor:pointer">'+s+(sortCol===i?(desc?' ▾':' ▴'):'')+'</th>').join('')+'<th class="num" data-c="9" style="cursor:pointer">Avg'+(sortCol===9?(desc?' ▾':' ▴'):'')+'</th></tr></thead><tbody>'+
   rows.map(r=>'<tr><td>'+(r.m.startsWith('JIT')?'<b>'+esc(r.m)+'</b>':esc(r.m))+'</td>'+r.v.map((x,i)=>'<td class="num"'+sh(r.raw,i)+'>'+fm(x)+'</td>').join('')+'<td class="num">'+fm(r.avg)+'</td></tr>').join('')+'</tbody>';
  $('t2Tab').querySelectorAll('th').forEach(th=>th.addEventListener('click',()=>{const c=+th.dataset.c;if(c<0)return;if(sortCol===c)desc=!desc;else{sortCol=c;desc=true}draw()}))}
 segBind('t2V',m=>{view=m;$('t2V').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.m===m?'true':'false'));draw()});
 onTab('t-tables',draw)})();

(function(){let mi=0;const B=['DSQA','xBench','AgentIF'],BL={DSQA:'DeepSearchQA',xBench:'xBench-DS',AgentIF:'AgentIF'};
 function draw(){const cell=(r,b)=>mi===3?(r[b][2]/r[b][1]*1000).toFixed(3):mi===2?'$'+r[b][2].toFixed(3):mi===1?fmt(r[b][1]):r[b][0].toFixed(1);
  const best=(bb,b)=>{const rs=PT.t3.filter(r=>r.backbone===bb),vs=rs.map(r=>mi===3?r[b][2]/r[b][1]:r[b][Math.min(mi,2)]);return mi===0?Math.max(...vs):Math.min(...vs)};
  let h='<thead><tr><th>Backbone</th><th>Harness</th>'+B.map(b=>'<th class="num">'+BL[b]+'</th>').join('')+'</tr></thead><tbody>';
  PT.t3.forEach(r=>{h+='<tr'+(r.harness==='JIT-Agent'?' style="background:var(--soft)"':'')+'><td class="small">'+r.backbone+'</td><td>'+(r.harness==='JIT-Agent'?'<b>JIT-Agent</b>':r.harness)+'</td>'+B.map(b=>{const v=mi===3?r[b][2]/r[b][1]:r[b][Math.min(mi,2)];return '<td class="num">'+(mi<3&&v===best(r.backbone,b)?'<b>'+cell(r,b)+'</b>':cell(r,b))+'</td>'}).join('')+'</tr>'});
  $('t3Tab').innerHTML=h+'</tbody>'}
 segBind('t3V',m=>{mi=+m;$('t3V').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.m===m?'true':'false'));draw()});onTab('t-tables',draw)})();

onTab('t-tables',()=>{
 const F4=PT.fig4,names=Object.keys(F4);
 $('f4Tab').innerHTML='<thead><tr><th>Backbone</th>'+names.map(n=>'<th class="num">'+n.replace('DeepPlanning-','').replace('-Oneday','')+'<br><span class="small mute">ReAct → JIT</span></th>').join('')+'</tr></thead><tbody>'+F4[names[0]].map((r,i)=>'<tr><td>'+r.backbone+'</td>'+names.map(n=>{const x=F4[n][i];return '<td class="num">'+x.react.toFixed(1)+' → '+x.jit.toFixed(1)+' <span class="small" style="color:var(--good)">+'+x.gain.toFixed(1)+'</span></td>'}).join('')+'</tr>').join('')+'</tbody>';
 const host=$('f6All');if(!host.dataset.done){host.dataset.done=1;let h='<div class="f6g">';Object.keys(PT.fig6).forEach(b=>Object.keys(F6L).forEach(m=>{h+='<div class="f6c" id="f6_'+b.replace(/\W/g,'')+'_'+m+'"></div>'}));host.innerHTML=h+'</div>'}
 Object.keys(PT.fig6).forEach(b=>Object.keys(F6L).forEach(m=>f6Chart($('f6_'+b.replace(/\W/g,'')+'_'+m),b,m,true)));
 $('t4Tab').innerHTML='<thead><tr><th>Method</th><th>Construction</th><th>Instance synthesis</th><th>Harness model</th><th>Learned repair</th><th>Online evolution</th></tr></thead><tbody>'+PT.t4.map(r=>'<tr><td>'+esc(r.cite)+'</td><td>'+esc(r.construction)+'</td>'+r.flags.map(f=>'<td>'+(f?'<span class="ok">yes</span>':'<span class="mute">no</span>')+'</td>').join('')+'</tr>').join('')+'</tbody>';
 $('noiseTab').innerHTML='<thead><tr><th>Comparison</th><th class="num">Tasks</th><th class="num">Scores</th><th class="num">Difference</th><th class="num">SE</th><th class="num">z</th></tr></thead><tbody>'+RC.noise.map(r=>'<tr><td>'+esc(r.label)+'</td><td class="num">'+r.n+'</td><td class="num">'+r.a+' → '+r.b+'</td><td class="num">'+(r.diff>0?'+':'')+r.diff+'</td><td class="num">'+r.se+'</td><td class="num">'+(Math.abs(r.z)>=2?'<b>'+r.z+'</b>':r.z)+'</td></tr>').join('')+'</tbody>';
 $('granTab').innerHTML='<thead><tr><th>Where</th><th>Benchmark</th><th class="num">N (released)</th><th>Not k/N</th></tr></thead><tbody>'+RC.granularity.map(g=>'<tr><td>'+g.table+'</td><td>'+g.bench+'</td><td class="num">'+g.n+'</td><td class="small">'+(g.unreachable.length?g.unreachable.length+' of '+g.cells+': '+g.unreachable.map(u=>esc(u[0])+' '+u[1].toFixed(1)).join(', '):'none of '+g.cells)+'</td></tr>').join('')+'</tbody>';
 const OV=window.PAPER.ov,ob=OV.benchmarks;
 $('ovOut').innerHTML='<p>The released training data has '+fmt(OV.training_rows)+' rows for '+fmt(OV.unique_instructions)+' distinct task instructions. Where they come from (by the workspace path in each instruction): '+Object.entries(OV.sources).filter(([k,v])=>v>3).map(([k,v])=>esc(k.replace('other','no workspace path (short QA or web-app tasks)'))+' '+fmt(v)).join(', ')+'.</p>'+
  '<div class="tw"><table><thead><tr><th>Test set (released repo)</th><th class="num">Test queries</th><th class="num">Found in training</th><th class="num">Training rows, same environment</th><th class="num">Closest training row shares</th></tr></thead><tbody>'+Object.entries(ob).map(([k,v])=>'<tr><td>'+esc(k)+'</td><td class="num">'+v.test_items+'</td><td class="num">'+v.found_in_training+'</td><td class="num">'+(v.training_rows_same_env!=null?v.training_rows_same_env:'')+'</td><td class="num">'+(v.max_shared_ngram_share!=null?(100*v.max_shared_ngram_share).toFixed(0)+'%':'')+'</td></tr>').join('')+'</tbody></table></div>'+
  '<p class="small">"Found": any of four 60-character windows of the test query occurs in a training instruction. "Shares": the largest fraction of a test query\'s six-word sequences (twelve-character sequences for Chinese) found in any one training instruction of the same environment. No test query is copied. But the DeepPlanning training tasks were run in workspaces named after test cases, and the one checked item by item, <code>'+OV.shopping_example.workspace+'</code>, asks for four products that appear together only in '+OV.shopping_example.cases_with_all_four_items.join(', ')+' of the '+OV.shopping_example.cases_checked+' level-1 test databases. Across all '+OV.shopping_namesake.rows+' Shopping rows, the brand and colour pairs a request names are found '+OV.shopping_namesake.mean_pairs_in_own_case_db+' times on average in its namesake case\'s database against '+OV.shopping_namesake.mean_pairs_in_other_case_db+' in other cases\'; across '+OV.travel_namesake.rows+' Travel rows, the namesake test query is the closest one for '+OV.travel_namesake.rows_most_similar_to_namesake+' (chance: about 2). Scripts: <code>overlap.py</code>, <code>harness_stats.py</code> in this page\'s source.</p>';
 const C=RC.checks,pr=C.filter(c=>c.printed!==null);
 $('chkSum').innerHTML='<b>'+pr.filter(c=>c.ok).length+' of '+pr.length+'</b> printed numbers reproduce; '+(C.length-pr.length)+' further derived numbers are this page\'s own. Source: <code>recompute.py</code>.';
 $('chkTab').innerHTML='<thead><tr><th>Claim</th><th>Where</th><th class="num">Printed</th><th class="num">Recomputed</th><th>Note</th></tr></thead><tbody>'+C.map(c=>'<tr><td>'+esc(c.claim)+'</td><td class="small">'+esc(c.where)+'</td><td class="num">'+(c.printed===null?'':c.printed)+'</td><td class="num">'+(c.printed===null?'':(c.ok?'<span class="ok">':'<span class="no">'))+esc(c.got)+(c.printed===null?'':'</span>')+'</td><td class="small">'+esc(c.note||'')+'</td></tr>').join('')+'</tbody>'});
