// Collects every snippet (as compiled: directive lines removed), its recorded output, the drills,
// the narrowing programs, the LLM JSON lab and the timings into ../parts/40_js_tb_0data.js.
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
const here = new URL(".", import.meta.url).pathname;
const DIR = /^\/\/\s*(run|check|cfg|cmd|file|nm|data):\s*(.*)$/;
function snippet(dir, f) {
  const name = f.replace(/\.(ts|mts)$/, "");
  const raw = readFileSync(here + dir + "/" + f, "utf8").replace(/\n$/, "");
  const dirs = {}; const code = [];
  for (const ln of raw.split("\n")) { const m = ln.match(DIR); if (m) dirs[m[1]] = m[2]; else code.push(ln); }
  const file = dirs.file || f.replace(/^[a-z]?[0-9]+[a-z]?_/, "");
  const helpers = readdirSync(here + dir).filter(h => h.startsWith(name + "__")).sort()
    .map(h => ({ file: h.slice(name.length + 2), code: readFileSync(here + dir + "/" + h, "utf8").replace(/\n$/, "").split("\n").filter(l => !DIR.test(l)).join("\n") }));
  const out = readFileSync(here + "outputs/" + name + ".txt", "utf8").replace(/\n$/, "");
  const s = { file, out, helpers };
  if (code.join("").trim()) s.code = code.join("\n");
  if (dirs.cfg) s.cfg = dirs.cfg;
  return [name, s];
}
const S = {};
for (const dir of ["code", "drill"]) for (const f of readdirSync(here + dir).filter(f => /\.(ts|mts)$/.test(f) && !f.includes("__")).sort()) {
  const [n, s] = snippet(dir, f); S[n] = s;
}
S["83_eresolve"] = { file: "", out: readFileSync(here + "outputs/83_eresolve.txt", "utf8").replace(/\n$/, ""), helpers: [] };
const data = {
  snip: S,
  narrow: JSON.parse(readFileSync(here + "outputs/narrow.json", "utf8")),
  zodlab: JSON.parse(readFileSync(here + "outputs/zodlab.json", "utf8")),
  zodlabSrc: readFileSync(here + "zodlab/lab.ts", "utf8"),
  bench: { tsc: readFileSync(here + "outputs/tsc_bench.txt", "utf8"), startup: readFileSync(here + "outputs/startup_bench.txt", "utf8") },
  tsconfig: readFileSync(here + "tsconfig.base.json", "utf8"),
};
const js = "// Generated by src/tb/gen_data.mjs from src/tb/outputs (real tsc 7.0.2 / node 22.22.2 runs). Do not edit by hand.\nwindow.TB=" + JSON.stringify(data).replace(/<\/(script)/gi, "<\\/$1") + ";\n";
writeFileSync(here + "../parts/40_js_tb_0data.js", js);
console.log("snippets", Object.keys(S).length, "bytes", js.length);
