"""parts/20_lib_data.js (window.LIB) from the release extracts in inputs/: the router tree with page sizes and
memberships, every repository graph's size, the released session's skill reads, the vLLM and SGLang graphs
file by file, and the FrontierCS graph.  usage: python3 mk_libdata.py (build.sh runs it)"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
I = lambda f: json.load(open(os.path.join(HERE, 'inputs', f)))
L, S, F, M, H = I('release_library.json'), I('release_session.json'), I('release_frontiercs.json'), I('release_meta.json'), I('release_creator_hub.json')
out = {
 'commit': L['commit'][:7],
 'repos': [[r[1], r[2], r[3], r[4]] for r in L['repos']],
 'areas': [{'n': a['n'], 'p': a['page'], 'f': [{'n': f['n'], 'p': f['page'], 's': f['scope'], 'm': f['m']} for f in a['f']]} for a in L['areas']],
 'router': L['router_bytes'],
 'detail': L['detail'],
 'examples': L['examples'],
 'reads': [[r['t'], r['path'], r['bytes'] if r['bytes'] is not None else r['chars'], 1 if r['path'].startswith('repositories/') else 0] for r in S['reads']],
 'session': {k: S[k] for k in ('seconds', 'tool_calls', 'output_tokens', 'uncached_input_tokens', 'assistant_turns', 'model', 'tokens_before_compaction')},
 'fcs': {'nodes': F['nodes'], 'sizes': F['sizes'], 'edges': F['edges']},
 'meta': {k: M[k] for k in ('library_files', 'library_bytes', 'skill_md', 'graphs', 'assignments', 'repos_multi_family', 'description_chars_total')},
 'hub': {'checks': H['checks'], 'native': H['native'], 'overall': H['overall']},
}
js = '// Generated by mk_libdata.py from the AREX-Skill release (commit %s); see fetch_release.py.\nwindow.LIB=%s;\n' % (L['commit'], json.dumps(out, separators=(',', ':'), ensure_ascii=False))
open(os.path.join(HERE, 'parts', '20_lib_data.js'), 'w').write(js)
print('lib data bytes', len(js.encode()))
