// ---- Reading: the softmax PTX with feature highlights; old ptxas; ptxas levels ----
(function(){
  const D=window.CSD,E=RD.esc,P=D.ptx_softmax;
  const F={
    head:[/^\.(version|target|address_size)|\.visible \.entry|\.param|Generated by|Based on/,'The header: the author (cicc, "Based on NVVM 7.0.1"), <code>.version 9.4</code> (CUDA 13.4’s PTX), <code>.target sm_90a</code>, 64-bit addresses, then the kernel entry and its three parameters in the <code>.param</code> space.'],
    regs:[/^\s*\.reg/,'Four declarations make '+(D.ptx_regs.pred+D.ptx_regs.f32+D.ptx_regs.b32+D.ptx_regs.b64)+' virtual registers: '+D.ptx_regs.pred+' predicates, '+D.ptx_regs.f32+' floats, '+D.ptx_regs.b32+' 32-bit and '+D.ptx_regs.b64+' 64-bit values. The SASS uses 18 physical registers.'],
    space:[/\b(ld|st)\.(global|shared|param|local|const)/,'Every load and store says where it goes: <code>ld.param</code> for arguments, <code>ld.global</code> / <code>st.global</code> for the rows, <code>st.shared</code> / <code>ld.shared</code> for the eight per-warp partial results.'],
    sreg:[/%(tid|ctaid|ntid|nctaid)\./,'Special registers: <code>%tid.x</code> (threadIdx.x) and <code>%ctaid.x</code> (blockIdx.x).'],
    shfl:[/shfl\.sync/,'<code>__shfl_xor_sync</code> becomes <code>shfl.sync.bfly.b32</code>: five per warp reduction (offsets 16, 8, 4, 2, 1, unrolled), and four reductions (the maximum and the sum, each once inside every warp and once over the eight warps\u2019 partial results), so twenty in all.'],
    bar:[/bar\.sync|barrier/,'<code>__syncthreads()</code> is <code>bar.sync 0</code>: every thread of the block waits here.'],
    pred:[/setp\.|@%p|\bbra\b|^\$L__/,'Loops and the bounds check are a <code>setp</code> writing a predicate and a predicated <code>bra</code> to a label.'],
    math:[/ex2|rcp|div\.|mul\.f32|sub\.f32|max\.f32/,'<code>__expf(v)</code> is a multiply by log2(e) and <code>ex2.approx</code>; <code>1.f / s</code> is <code>rcp.rn.f32</code> (an exactly rounded reciprocal, several SASS instructions).']};
  const pre=document.getElementById('cs-ptx');
  function show(k){const re=F[k][0];let first=-1;
    pre.innerHTML=P.map((l,i)=>{const on=re.test(l);if(on&&first<0)first=i;return '<span class="ln'+(on?' hl':'')+'" style="display:block">'+E(l)+'</span>'}).join('');
    document.getElementById('cs-ptxCap').innerHTML='<p>'+F[k][1]+' <span class="mute">('+P.filter(l=>re.test(l)).length+' lines lit)</span></p>';
    if(first>=0){const el=pre.children[first];pre.scrollTop=Math.max(0,el.offsetTop-pre.offsetTop-30)}}
  RD.seg(document.getElementById('cs-ptxSeg'),show);show('head');
  document.getElementById('cs-ptxRegN').textContent=(D.ptx_regs.pred+D.ptx_regs.f32+D.ptx_regs.b32+D.ptx_regs.b64);
  document.getElementById('cs-resLine').textContent=D.res_sm90a;
  document.getElementById('cs-oldptxas').textContent=D.old_ptxas.slice(0,6).join('\n');
  document.getElementById('cs-tritonHead').textContent=D.triton_ptx_head.filter(l=>/Generated/.test(l))[0].replace(/^\/\/\s*/,'')+' ('+D.triton_ptx_head.filter(l=>/^\.version/.test(l))[0]+')';
  const L=D.ptxas_levels;
  document.getElementById('cs-ptxasLv').innerHTML='<tr><th>ptxas level</th><th class="num">registers</th><th class="num">SASS instructions</th><th class="num">vs -O3</th></tr>'+
    L.map(r=>'<tr><td><code>-O'+r[0]+'</code></td><td class="num">'+r[1]+'</td><td class="num">'+r[2]+'</td><td class="num">'+(r[2]/L[3][2]).toFixed(2)+'x</td></tr>').join('');
  RD.onRender(()=>{const a=document.querySelector('#cs-ptxSeg button.on');if(a)show(a.dataset.m)});
})();
