"""Write parts/20_js_diab.js: the raw diabetes data of Efron et al. (2004), as shipped in scikit-learn
(load_diabetes(scaled=False)), 442 patients x 10 baseline variables + the response. Also inputs/diabetes.csv.
Run: uv run --with scikit-learn --with numpy python mk_diabetes.py"""
from sklearn.datasets import load_diabetes
import json
d = load_diabetes(scaled=False)
X, y = d.data, d.target
def f(v):
    s = ('%.6f' % v).rstrip('0').rstrip('.')
    return s
rows = [','.join(f(v) for v in list(X[i]) + [y[i]]) for i in range(len(y))]
open('inputs/diabetes.csv', 'w').write(','.join(d.feature_names + ['y']) + '\n' + '\n'.join(rows) + '\n')
names = ['age', 'sex', 'bmi', 'bp', 's1 (tc)', 's2 (ldl)', 's3 (hdl)', 's4 (tch)', 's5 (ltg)', 's6 (glu)']
js = ('// generated by mk_diabetes.py: Efron et al. (2004) diabetes data, 442 patients; columns age, sex, bmi, bp, s1..s6, y\n'
      'window.DIAB={names:' + json.dumps(names) + ',raw:"' + ';'.join(rows) + '"};\n')
open('parts/20_js_diab.js', 'w').write(js)
print(len(js))
