"""Write parts/31_js_dd.js from inputs/double_descent.json (run after double_descent.py)."""
import json
d = json.load(open('inputs/double_descent.json'))
keep = {k: d[k] for k in ['D', 'lams', 'n', 'seeds', 'test_mse', 'test_mse_lo', 'test_mse_hi', 'test_err', 'opt_mse', 'opt_err', 'best_lam_index', 'train_mse']}
open('parts/31_js_dd.js', 'w').write('// generated by mk_parts_data.py from inputs/double_descent.json (double_descent.py)\nwindow.DD=' + json.dumps(keep, separators=(',', ':')) + ';\n')
