"""Pack the page's data into parts/20_data.js (window.QD). build.sh runs it.

Inputs: inputs/dtypes.json, inputs/weights_sample.json, model/weights_stats.json, model/quant_ppl.jsonl,
model/train_qlora.jsonl, inputs/eval_compact.json, inputs/eval_recompute.json, inputs/fig_points.json.
Packing (decoded by 22_js_engine.js):
  pairwise verdicts: 4 symbols (0 unparsed, 1 first better, 2 second better, 3 tie), three per base64 character;
  human HITs: three characters each from ALPH (prompt index, ordered-pair index, the three votes as a base-3 number);
  relative scores: one ALPH character per score, half-points 0..20, 21 = missing.
"""
import base64, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
J = lambda p: json.load(open(os.path.join(HERE, p)))
B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
ALPH = ''.join(chr(c) for c in range(35, 127) if chr(c) not in '\\\'"<>&`@{}[]')


def pack4(s):
    s = s + '0' * ((-len(s)) % 3)
    return ''.join(B64[int(s[i]) * 16 + int(s[i + 1]) * 4 + int(s[i + 2])] for i in range(0, len(s), 3))


def main():
    D = J('inputs/dtypes.json')
    E = J('inputs/eval_compact.json')
    ER = J('inputs/eval_recompute.json')
    W = J('inputs/weights_sample.json')
    WS = J('model/weights_stats.json')
    ppl = [json.loads(l) for l in open(os.path.join(HERE, 'model', 'quant_ppl.jsonl'))]
    trp = os.path.join(HERE, 'model', 'train_qlora.jsonl')
    trn = [json.loads(l) for l in open(trp)] if os.path.exists(trp) else []
    sysV = ['gpt4', 'guanaco-65b', 'guanaco-33b', 'vicuna-13b', 'gpt35', 'guanaco-13b', 'bard', 'guanaco-7b']
    pairsV = [(a, b) for a in sysV for b in sysV if a != b]
    vic = ''.join(pack4(E['gpt4_vicuna_pairwise'][a + '|' + b]) for a, b in pairsV)
    sysO = [s for s in sysV if s != 'bard']
    pairsO = [(a, b) for a in sysO for b in sysO if a != b]
    oa = ''.join(pack4(E['gpt4_oa_pairwise'][a + '|' + b]) for a, b in pairsO)
    hum = []
    for q, a, b, v in E['human_vicuna']:
        qi = E['vicuna_qids'].index(q); pi = pairsV.index((a, b))
        code = sum({'a': 0, 'b': 1, 't': 2}[c] * 3 ** k for k, c in enumerate(v))
        hum.append(ALPH[qi] + ALPH[pi] + ALPH[code])
    assert len(ALPH) >= 80
    rel = {}
    for s, v in E['gpt4_vicuna_relative'].items():
        row = {}
        for order, d in v.items():
            byq = dict(zip(d['qids'], d['scores']))
            enc = ''
            for q in E['vicuna_qids']:
                p = byq.get(q)
                enc += (ALPH[int(round(p[0] * 2))] + ALPH[int(round(p[1] * 2))]) if p else ALPH[21] * 2
            row[order] = enc
        rel[s] = row
    cats = [E['vicuna_categories'][str(q)] if str(q) in E['vicuna_categories'] else E['vicuna_categories'].get(q) for q in E['vicuna_qids']]
    ws = {}
    for k, s in WS.items():
        ws[k] = {'std': s['std'], 'kurt': s['kurtosis_excess'], 'shapiro': s['shapiro'],
                 'q': {t: {kk: (round(vv, 6) if isinstance(vv, float) else vv) for kk, vv in q.items() if kk != 'occupancy'} for t, q in s['quant'].items()},
                 'occ': {t: q['occupancy'] for t, q in s['quant'].items() if 'occupancy' in q}}
    def rr(x, d=2):
        if isinstance(x, float): return round(x, d)
        if isinstance(x, dict): return {k: rr(v, d) for k, v in x.items()}
        if isinstance(x, list): return [rr(v, d) for v in x]
        return x
    ev = {k: rr(ER[k], 3) for k in ('rank_agreement', 'order_effect', 'agreement')}
    ev['elo'] = {k: {'n': ER[k]['n_matches'], 'mean': {s: round(v['mean'], 1) for s, v in ER[k]['elo'].items()},
                     'ci': {s: round(v['ci95_of_mean'], 2) for s, v in ER[k]['elo'].items()},
                     'sd': {s: round(v['sd_over_orderings'], 1) for s, v in ER[k]['elo'].items()},
                     'lo': {s: round(v['lo'], 1) for s, v in ER[k]['boot'].items()}, 'hi': {s: round(v['hi'], 1) for s, v in ER[k]['boot'].items()}}
                 for k in ER if k.startswith('elo_')}
    ev['relative'] = rr(ER['relative'], 2)
    ev['t12'] = {k: round(v['net'], 3) for k, v in ER['table12'].items()}
    sig = lambda xs: [float('%.8g' % x) for x in xs]
    QD = {'types': {k: sig(v) for k, v in D['types'].items()}, 'appE': D['appendix_e'], 'dyn8': sig(D['dynamic8']), 'fp8': sig(D['fp8_e4m3']),
          'w': [{'name': t['name'], 'shape': t['shape'], 'w': t['w'], 'absmax': t['absmax']} for t in W['tensors']], 'ws': ws,
          'ppl': [{k: (round(v, 4) if isinstance(v, float) else v) for k, v in r.items() if k != 'seconds'} for r in ppl],
          'trn': trn, 'sysV': sysV, 'sysO': sysO, 'vic': vic, 'oa': oa, 'nO': 953, 'hum': ''.join(hum), 'rel': rel, 'cats': cats, 'ALPH': ALPH,
          'ev': ev, 'fig': {k: v for k, v in J('inputs/fig_points.json').items() if not k.startswith('_')}}
    s = '// Generated by mk_data.py. Real LLaMA-7B weight samples, the released QLoRA judgments, and our offline results.\nwindow.QD=' + json.dumps(QD, separators=(',', ':'), ensure_ascii=False) + ';\n'
    open(os.path.join(HERE, 'parts', '20_data.js'), 'w').write(s)
    print('20_data.js', len(s), 'bytes; vic', len(vic), 'oa', len(oa), 'hum', len(hum) * 3, 'rel', sum(len(x) for r in rel.values() for x in r.values()))


if __name__ == '__main__':
    main()
