"""Primary keys, measured: bigint identity against random UUIDs (version 4, gen_random_uuid()) against time-ordered UUIDs
(version 7). PostgreSQL 16 has no built-in uuidv7() (it arrived in PostgreSQL 18), so version 7 is generated by a small SQL
function that writes the Unix time in milliseconds into the first 48 bits of a random UUID and sets the version and variant
bits, per RFC 9562 section 5.7.
For each key type and size: generate N keys into a temporary table (timed apart), insert them in generation order with one
INSERT ... SELECT, and separately run 20,000 single-row INSERTs in autocommit like an app does; record the insert time,
the primary-key index size, the table size and the WAL written.
Writes ../inputs/keys.json. Run from a scratch directory (see pgc.py)."""
import os, sys, time, datetime, platform, statistics
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pgc import *

UUIDV7 = """CREATE OR REPLACE FUNCTION uuid_v7() RETURNS uuid AS $$
  SELECT encode(set_bit(set_bit(overlay(uuid_send(gen_random_uuid())
           PLACING substring(int8send(floor(extract(epoch FROM clock_timestamp()) * 1000)::bigint) FROM 3)
           FROM 1 FOR 6), 52, 1), 53, 1), 'hex')::uuid
$$ LANGUAGE sql VOLATILE"""
KINDS = {
  'bigint': ('bigint GENERATED ALWAYS AS IDENTITY', None),
  'uuid_v4': ('uuid DEFAULT gen_random_uuid()', None),
  'uuid_v7': ('uuid DEFAULT uuid_v7()', None),
}

GEN = {'bigint': None, 'uuid_v4': 'gen_random_uuid()', 'uuid_v7': 'uuid_v7()'}

def one(c, kind, n, single):
    """Insert n rows into a fresh table keyed by `kind`. For the bulk runs the keys are generated first into a temporary
    table (timed separately as gen_seconds), so the insert time measures only the work of placing keys in the table and
    its primary-key index. The temporary table is read in its physical order, which is generation order (it was written
    once by one statement); an ORDER BY would add a 10M-row sort to every run."""
    typ = KINDS[kind][0]
    c.execute(f'DROP TABLE IF EXISTS k_{kind}')
    c.execute(f'CREATE TABLE k_{kind} (id {typ} PRIMARY KEY, chat_id integer NOT NULL, tokens integer NOT NULL)')
    gen_s = None
    if not single:
        c.execute('DROP TABLE IF EXISTS src')
        t = time.perf_counter()
        if GEN[kind]:
            c.execute(f'CREATE TEMP TABLE src AS SELECT g AS ord, {GEN[kind]} AS id FROM generate_series(1, {n}) g')
        else:
            c.execute(f'CREATE TEMP TABLE src AS SELECT g AS ord FROM generate_series(1, {n}) g')
        gen_s = round(time.perf_counter() - t, 3)
    c.execute('CHECKPOINT')
    w0 = c.execute('SELECT pg_current_wal_lsn()').fetchone()[0]
    t = time.perf_counter()
    if single:
        for i in range(n):
            c.execute(f'INSERT INTO k_{kind} (chat_id, tokens) VALUES (%s, %s)', (i % 200 + 1, i % 900))
    elif GEN[kind]:
        c.execute(f'INSERT INTO k_{kind} (id, chat_id, tokens) SELECT id, ord % 200 + 1, ord % 900 FROM src')
    else:
        c.execute(f'INSERT INTO k_{kind} (chat_id, tokens) SELECT ord % 200 + 1, ord % 900 FROM src')
    dt = time.perf_counter() - t
    wal = c.execute('SELECT pg_wal_lsn_diff(pg_current_wal_lsn(), %s)', (w0,)).fetchone()[0]
    idx = c.execute(f"SELECT pg_relation_size('k_{kind}_pkey'), pg_relation_size('k_{kind}')").fetchone()
    if not single: c.execute('DROP TABLE src')
    return {'seconds': round(dt, 3), 'gen_seconds': gen_s, 'index_bytes': idx[0], 'table_bytes': idx[1], 'wal_bytes': int(wal)}

if __name__ == '__main__':
    start()
    with conn('postgres') as c:
        c.execute('DROP DATABASE IF EXISTS keys WITH (FORCE)'); c.execute('CREATE DATABASE keys')
        ver = c.execute('SHOW server_version').fetchone()[0]
    res = []
    with conn('keys') as c:
        c.execute(UUIDV7)
        sample = [str(r[0]) for r in c.execute('SELECT uuid_v7() FROM generate_series(1, 3)').fetchall()] + \
                 [str(r[0]) for r in c.execute('SELECT gen_random_uuid() FROM generate_series(1, 2)').fetchall()]
        for n, reps in ((1_000_000, 3), (10_000_000, 1)):
            for kind in KINDS:
                runs = [one(c, kind, n, False) for _ in range(reps)]
                r = dict(runs[0]); r['seconds'] = statistics.median(x['seconds'] for x in runs); r['all_seconds'] = [x['seconds'] for x in runs]
                r.update(kind=kind, n=n, mode='bulk'); res.append(r); print(r, flush=True)
                c.execute(f'DROP TABLE k_{kind}')
        for kind in KINDS:
            r = one(c, kind, 20_000, True); r.update(kind=kind, n=20_000, mode='single'); res.append(r); print(r, flush=True)
            c.execute(f'DROP TABLE k_{kind}')
        settings = dict(c.execute("SELECT name, setting FROM pg_settings WHERE name IN ('shared_buffers','max_wal_size','synchronous_commit','fsync','wal_level')").fetchall())
    save('keys.json', {'date': datetime.date.today().isoformat(), 'postgres': ver, 'machine': platform.machine() + ' ' + platform.platform(),
                       'uuidv7_sql': UUIDV7, 'sample_ids': sample, 'settings': settings, 'runs': res})
