"""Shared helpers for this page's PostgreSQL measurements: a local PostgreSQL 16 from the pgserver wheel
(nothing installed system-wide), loaded with the same chat data as the root page's SQL playground
(../../../src/sql/data.json, generated by the root's src/sql/gen_data.py).
The data directory lives outside the repo: env SQLM_DATA (default ./sqlm_pgdata where you run it).
Run every script from a scratch directory with:
  uv run --no-project --python 3.12 --with pgserver --with 'psycopg[binary]' --with 'sqlalchemy>=2' python <script>
"""
import os, json, subprocess, time
import pgserver, psycopg
B = os.path.join(os.path.dirname(pgserver.__file__), 'pginstall', 'bin')
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT_SQL = os.path.join(HERE, '..', '..', '..', 'src', 'sql')
INPUTS = os.path.join(HERE, '..', 'inputs')
ROOT = os.path.abspath(os.environ.get('SQLM_DATA', 'sqlm_pgdata'))
DATA = os.path.join(ROOT, 'data'); PORT = 54351
URL = f'host=127.0.0.1 port={PORT} user=postgres'

def sh(*a):
    return subprocess.run(list(a), capture_output=True, text=True)

def start():
    os.makedirs(ROOT, exist_ok=True)
    if not os.path.exists(DATA):
        sh(f'{B}/initdb', '-D', DATA, '-U', 'postgres', '--auth=trust', '-E', 'UTF8', '--locale=C')
    st = sh(f'{B}/pg_ctl', '-D', DATA, 'status')
    if st.returncode != 0:
        r = sh(f'{B}/pg_ctl', '-D', DATA, '-o', f"-p {PORT} -k '' -h 127.0.0.1", '-l', ROOT + '/log', '-w', 'start')
        print(r.stdout[-200:], r.stderr[-200:])

def stop():
    sh(f'{B}/pg_ctl', '-D', DATA, '-m', 'fast', '-w', 'stop')

def conn(db='chat', autocommit=True):
    return psycopg.connect(URL + ' dbname=' + db, autocommit=autocommit)

def data():
    return json.load(open(os.path.join(ROOT_SQL, 'data.json')))

# The page's one extension of the root dataset: messages.parent_id, the message each one replies to
# (the previous message in the same chat; NULL for a chat's first message). Same in SQLite and Postgres.
PARENT_SQL = """ALTER TABLE messages ADD COLUMN parent_id INTEGER REFERENCES messages(id);
UPDATE messages SET parent_id = (SELECT MAX(p.id) FROM messages p WHERE p.chat_id = messages.chat_id AND p.id < messages.id);"""

def load_base(db='chat'):
    """(Re)create database db with the root's schema and rows plus parent_id; ids continue after the loaded rows."""
    D = data()
    with conn('postgres') as c:
        c.execute(f'DROP DATABASE IF EXISTS {db} WITH (FORCE)'); c.execute(f'CREATE DATABASE {db}')
        ver = c.execute('SHOW server_version').fetchone()[0]
    schema = open(os.path.join(ROOT_SQL, 'schema_pg.sql')).read()
    with conn(db) as c:
        c.execute(schema)
        with c.cursor() as cur:
            for t in ('users', 'chats', 'messages', 'credits'):
                cols = D['cols'][t]
                cur.executemany(f'INSERT INTO {t} ({",".join(cols)}) VALUES ({",".join(["%s"] * len(cols))})', D[t])
            for t in ('users', 'chats', 'messages'):
                cur.execute(f"SELECT setval(pg_get_serial_sequence('{t}', 'id'), (SELECT MAX(id) FROM {t}))")
            for s in PARENT_SQL.split(';'):
                if s.strip(): cur.execute(s)
        c.execute('VACUUM ANALYZE')
    return ver

def save(name, obj):
    p = os.path.join(INPUTS, name)
    json.dump(obj, open(p, 'w'), indent=1, default=str)
    print('wrote', p, os.path.getsize(p))
