# Write parts/20_js_data.js from the measured inputs (inputs/out_a.json, inputs/out_b.json). Run: python3 mk_data.py
import json
A = json.load(open("inputs/out_a.json")); B = json.load(open("inputs/out_b.json"))
summ = [{k: r.get(k) for k in ["fmt", "N", "exact", "naive_relerr", "pairwise_relerr", "kahan_relerr", "acc32_relerr", "torch_sum_relerr"]} for r in A["summation"]]
def clean(v):
    if isinstance(v, float) and v != v: return "nan"
    if isinstance(v, float) and v in (float("inf"), float("-inf")): return "inf"
    return v
summ = [{k: clean(v) for k, v in r.items()} for r in summ]
D = {
    "meta": A["meta"],
    "summation": summ,
    "hist": {"lo": B["fp32"]["exp_min"], "counts": B["fp32"]["hist"], "n": B["fp32"]["nonzero"]},
    "runs": B["runs16"], "smol": {k: B["fp32"][k] for k in ["loss", "n_params", "frac_below_2m24", "frac_below_2m25", "frac_below_2m14", "max_abs", "median_abs"]},
}
open("parts/20_js_data.js", "w").write("// generated by mk_data.py from inputs/out_a.json and inputs/out_b.json (measured; do not edit)\nwindow.NCDATA=" + json.dumps(D, separators=(",", ":")) + ";\n")
print("ok", len(json.dumps(D)))
