// Default learning rate of every optimiser on every surface: the best of a log grid (10^(k/4), 1e-4 to 10) by the mean of
// log10(loss) over the whole run (rewards getting low fast), among rates whose path never leaves the plotted box (a rate that
// throws the point far away and lets it fall back is not one anybody would pick); the noisy surface averages seeds 1 to 5. Constant schedule. Writes ../parts/31_js_race_lr.js (window.RACE_LR) and checks/tuned_lr.json.
import fs from 'fs';import vm from 'vm';
const here=new URL('.',import.meta.url).pathname;
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(here+'../parts/30_js_engine.js','utf8'),ctx);const E=ctx.OPTE;
const grid=[];for(let k=-16;k<=4;k++)grid.push(+Math.pow(10,k/4).toPrecision(3));
function score(sk,ok,lr){const sf=E.S[sk];const seeds=sf.noise?[1,2,3,4,5]:[1];let tot=0;
  for(const sd of seeds){const r=E.run(sk,ok,lr,{seed:sd});if(r.diverged)return Infinity;const b=sf.box;for(let i=0;i<=r.T;i++){if(r.xs[i]<b[0]||r.xs[i]>b[1]||r.ys[i]<b[2]||r.ys[i]>b[3])return Infinity}let s=0;for(const l of r.ls)s+=Math.log10(Math.max(l,1e-12));tot+=s/r.ls.length}
  return tot/seeds.length}
const out={},detail={};
for(const sk of Object.keys(E.S)){out[sk]={};detail[sk]={};for(const ok of Object.keys(E.O)){let best=null,bs=Infinity;const row=[];
  for(const lr of grid){const s=score(sk,ok,lr);row.push([lr,isFinite(s)?+s.toFixed(3):null]);if(s<bs){bs=s;best=lr}}
  out[sk][ok]=best;detail[sk][ok]={best,score:+bs.toFixed(3),grid:row};}}
fs.writeFileSync(here+'../parts/31_js_race_lr.js','// generated by checks/tune.mjs: best learning rate of a log grid per surface and optimiser\nwindow.RACE_LR='+JSON.stringify(out)+';\n');
fs.writeFileSync(here+'tuned_lr.json',JSON.stringify(detail));
for(const sk in out){console.log(sk,Object.entries(out[sk]).map(([k,v])=>k+'='+v+'('+detail[sk][k].score+')').join(' '))}
