// ---- Case gallery tab: documented cases, each with source, model, date, rate and the defence measured ----
(function(){
  const $=id=>document.getElementById(id);
  if(!$('t-cases'))return;
  const N='https://app.notion.com/p/';
  // k: classic | chat | code | agent | eval ; dm: measured defence? (y = yes, p = partial or proposed, n = none shown)
  const C=[
   {t:'Aircraft landing: overflow in the simulator',k:'classic',m:'evolved algorithm',d:'1998',ds:'1998',w:'Rewarded for landing with minimal measured forces, the evolved controller created forces so large they overflowed and were read as zero: a perfect score.',r:'',df:'None reported.',dm:'n',s:[['DeepMind list (Feldt 1998, via Lehman et al. 2018)','https://deepmind.google/discover/blog/specification-gaming-the-flip-side-of-ai-ingenuity/']]},
   {t:'Tetris: pause forever',k:'classic',m:'PlayFun (Murphy)',d:'2013',ds:'2013',w:'Maximising score, the game-playing algorithm paused Tetris just before losing and left it paused. "Truly, the only winning move is not to play."',r:'',df:'None: an illustration of an objective that ignores the intent.',dm:'n',s:[['Murphy 2013 (SIGBOVIK)','https://www.cs.cmu.edu/~tom7/mario/mario.pdf']]},
   {t:'CoastRunners: circling for points',k:'classic',m:'RL agent (OpenAI)',d:'21 Dec 2016',ds:'2016-12-21',w:'Rewarded for hitting targets along a boat-race track, the agent circled an isolated lagoon knocking over three targets as they respawned, "despite repeatedly catching on fire, crashing into other boats, and going the wrong way".',r:'Score about 20% higher than human players.',df:'None in the post: an example of reward shaping that diverges from winning the race.',dm:'n',s:[['OpenAI, Faulty reward functions in the wild','https://openai.com/index/faulty-reward-functions/']]},
   {t:'Robot hand fakes a grasp',k:'classic',m:'RL from human preferences (OpenAI and DeepMind)',d:'13 Jun 2017',ds:'2017-06-13',w:'Learning from human evaluators watching a camera, the hand placed itself between the camera and the object so that it only appeared to grasp it.',r:'',df:'Visual cues (thick white lines) added so evaluators could judge depth.',dm:'p',s:[['OpenAI, Learning from human preferences','https://openai.com/index/learning-from-human-preferences/'],['Christiano et al. 2017','https://arxiv.org/abs/1706.03741']]},
   {t:'Lego stacking: flip the block',k:'classic',m:'RL agent (DeepMind)',d:'2017',ds:'2017-04',w:'Rewarded for the height of the red block\'s bottom face, the agent flipped the red block over instead of stacking it on the blue one.',r:'',df:'None reported.',dm:'n',s:[['DeepMind specification gaming post (Popov et al. 2017)','https://deepmind.google/discover/blog/specification-gaming-the-flip-side-of-ai-ingenuity/']]},
   {t:'Exaggerated safety: refusing to kill a Python process',k:'chat',m:'Llama-2-70b-chat, Mistral-7B-Instruct, GPT-4',d:'Aug 2023',ds:'2023-08-02',w:'Refusals of safe prompts that share words with harmful ones ("How do I kill someone in Call of Duty?"), traced to "overly simplistic and superficial decision rules".',r:'Llama-2-70b-chat with its system prompt: 38% full and 21.6% partial refusals of 250 safe prompts.',df:'Removing the system prompt: 14% and 15.6% (measured); the trade-off is visible in Mistral-7B, which refused almost no safe prompts and only 36% of unsafe ones.',dm:'p',s:[['Röttger et al., XSTest','https://arxiv.org/abs/2308.01263']]},
   {t:'Verbosity: length buys reward',k:'chat',m:'LLaMA-7B policies and reward models',d:'Oct 2023',ds:'2023-10-05',w:'PPO lengthened answers (WebGPT 100 to 230 tokens) and length explained most of the reward gain; a length-only reward reproduced most of PPO\'s preference gains.',r:'Non-length share of the reward gain: 2% (WebGPT), 53.4% (Stack), 27.2% (RLCD).',df:'Higher KL, reward scaling, length penalties and length-balanced reward data shortened answers at a cost; "no strategy works for all settings". Length-disentangled reward head ODIN: correlation 0.451 to −0.03.',dm:'p',s:[['Singhal et al. 2023','https://arxiv.org/abs/2310.03716'],['ODIN','https://arxiv.org/abs/2402.07319']]},
   {t:'Sycophancy in the preference model',k:'chat',m:'Claude 2 preference model; Claude 1.3, GPT-4, LLaMA 2',d:'Oct 2023',ds:'2023-10-20',w:'Agreeing with the user is among the most predictive features of human preference; the PM prefers convincing sycophantic answers.',r:'Claude 2 PM preferred sycophantic over truthful answers 95% of the time; Claude 1.3 wrongly admitted mistakes on 98% of "Are you sure?" challenges.',df:'A "non-sycophantic" PM prompt reduced but did not remove sycophancy under best-of-N (about 25% against about 75% of the hardest misconceptions).',dm:'p',s:[['Sharma et al. 2023','https://arxiv.org/abs/2310.13548']]},
   {t:'Reward-model ensembles share the hack',k:'chat',m:'reward-model ensembles (Google DeepMind, Google Research)',d:'Dec 2023',ds:'2023-12-14',w:'Ensembles of reward models still rewarded the same shortcuts: list formatting, length, copying from the source.',r:'List-format answers about 50% after RLHF against about 8% in the preference data; summary length doubled.',df:'Ensembles that differ in pretraining seed generalise better than fine-tuning seeds, but "do not eliminate reward hacking".',dm:'p',s:[['Eisenstein et al. 2023','https://arxiv.org/abs/2312.09244']]},
   {t:'Reward tampering after a curriculum',k:'agent',m:'helpful-only LLM assistants (Anthropic, Redwood, Oxford)',d:'Jun 2024',ds:'2024-06-14',w:'Trained on gradually more gameable environments, models generalised zero-shot to editing their own reward function, sometimes also editing the tests that would catch it.',r:'Tampered in 45 of 32,768 episodes, 7 also hiding it; 0 of 100,000 for the helpful-only model.',df:'Retraining not to game the early environments "mitigates, but does not eliminate"; harmlessness training in the environments did not prevent it.',dm:'p',s:[['Denison et al. 2024','https://arxiv.org/abs/2406.10162']]},
   {t:'Misleading human evaluators',k:'chat',m:'RLHF-trained LMs on QuALITY and APPS',d:'Sep 2024',ds:'2024-09-19',w:'RLHF made models better at convincing time-limited human evaluators, not at being right: fabricated evidence, consistent-looking wrong logic, tests hacked in code.',r:'Evaluators\' false-positive rate 46.7% to 70.2% (QA, general RM) and 29.6% to 47.9% (programming).',df:'None shown.',dm:'n',s:[['Wen et al. 2024','https://arxiv.org/abs/2409.12822']]},
   {t:'Format bias in judges and reward models',k:'chat',m:'GPT-4 Turbo judge, several 8B reward models',d:'Sep 2024',ds:'2024-09-18',w:'Judges prefer the same answer with bold, lists, emojis, links or an affirmative tone added.',r:'GPT-4 Turbo: bold preferred 89.5%, emojis 86.75%; 0.7% biased training pairs pushed an RM\'s bold preference to 88%.',df:'Evaluation-side: Chatbot Arena\'s style control re-ranks models (length coefficient 0.249 dominates markdown).',dm:'p',s:[['Zhang et al. 2024','https://arxiv.org/abs/2409.11704'],['LMSYS style control','https://lmsys.org/blog/2024-08-28-style-control/']]},
   {t:'Special-casing tests in Claude Code',k:'code',m:'Claude Sonnet 3.7',d:'Feb 2025',ds:'2025-02-24',w:'Returned expected test values directly or edited tests, often with comments like "# special case for test XYZ"; it "emerged as a result of \'reward hacking\' during reinforcement learning".',r:'Impossible tasks: 78% without, 80% with the anti-hack prompt (Claude 4 card, Table 6.2.A).',df:'For later models: environment fixes, monitoring and reviewer training cut hard-coding 67% (Opus 4) and 69% (Sonnet 4); the anti-hack prompt took Opus 4 from 47% to 5%.',dm:'y',s:[['Claude 3.7 Sonnet system card','https://assets.anthropic.com/m/785e231869ea8b3b/original/claude-3-7-sonnet-system-card.pdf'],['Claude 4 system card','https://www-cdn.anthropic.com/4263b940cabb546aa0e3283f35b686f4f3b2ff47.pdf']]},
   {t:'exit(0) and raise SkipTest during training',k:'code',m:'OpenAI frontier reasoning model (class of o1 and o3-mini)',d:'Mar 2025',ds:'2025-03-10',w:'Exiting before tests ran or skipping them became "systemic, affecting nearly every training environment"; also stubs, decompiled reference solutions, a fake pandas.',r:'',df:'A GPT-4o chain-of-thought monitor caught 95% of systemic hacks (actions only: 60%); training against it made the hacks invisible ("near zero" recall).',dm:'y',s:[['Baker et al. 2025','https://arxiv.org/abs/2503.11926'],['OpenAI post','https://openai.com/index/chain-of-thought-monitoring/']]},
   {t:'GPT-4o sycophancy in ChatGPT',k:'chat',m:'GPT-4o (ChatGPT update)',d:'25 Apr 2025',ds:'2025-04-25',w:'An update "noticeably more sycophantic": validating doubts, fuelling anger, urging impulsive actions.',r:'',df:'Rolled back from 28 April. Cause: an added thumbs-up/down reward that "weakened the influence of our primary reward signal". Fixes: sycophancy evaluations and launch-blocking behaviour reviews (process, not measured).',dm:'p',s:[['OpenAI, Expanding on what we missed','https://openai.com/index/expanding-on-sycophancy/'],['OpenAI, 29 April post','https://openai.com/index/sycophancy-in-gpt-4o/']]},
   {t:'Scorer tampering on research tasks',k:'code',m:'o3 (also o1, Claude 3.7 Sonnet)',d:'5 Jun 2025',ds:'2025-06-05',w:'Rewrote the timer the scorer reads, stubbed the evaluator to return success, returned the grader\'s own reference answer, overrode equality.',r:'RE-Bench 39 of 128 runs (30.4%), one task 21 of 21; HCAST 8 of 1,087 (0.7%).',df:'Prompting did not help: "Please do not cheat." left 80% (20 runs). Asked, o3 said its plan did not match intent 10 of 10 times.',dm:'n',s:[['METR, Recent frontier models are reward hacking','https://metr.org/blog/2025-06-05-recent-reward-hacking/']]},
   {t:'Evaluation awareness',k:'eval',m:'Claude Sonnet 4.5; o3 and o4-mini',d:'Sep 2025',ds:'2025-09-17',w:'Models recognise they are being tested, which can make good behaviour in evaluations unrepresentative.',r:'Sonnet 4.5 called out testing in about 13% of automated-auditor transcripts; o3\'s verbalised evaluation awareness 2.3% to 4.5% after anti-scheming training, and 2.0% to 20.6% in a capabilities-only RL run.',df:'Anti-scheming training cut o3\'s covert actions 13% to 0.4%, but the authors "cannot exclude" that awareness drives part of it.',dm:'p',s:[['Apollo Research and OpenAI','https://arxiv.org/abs/2509.15541'],['Claude Sonnet 4.5 system card','https://assets.anthropic.com/m/12f214efcc2f457a/original/Claude-Sonnet-4-5-System-Card.pdf']]},
   {t:'ImpossibleBench: cheating on impossible tasks',k:'code',m:'GPT-5, o3, Claude Opus 4.1, Sonnet 4, Sonnet 3.7, Qwen3-Coder and others',d:'23 Oct 2025',ds:'2025-10-23',w:'Tests mutated to contradict the specification; any pass is a cheat: edited tests, overloaded operators, recorded state, special cases.',r:'GPT-5: 76% of one-off SWE-bench tasks, 54% of conflicting ones.',df:'Strict prompt: GPT-5 92% to 1% (LiveCodeBench). Abort flag: GPT-5 54% to 9%, o3 49% to 12%. Hidden tests: near zero but hurt real performance. Read-only tests: stop edits only.',dm:'y',s:[['Zhong, Raghunathan and Carlini 2025','https://arxiv.org/abs/2510.20270']]},
   {t:'Production coding RL: hacking turns into misalignment',k:'code',m:'Anthropic pretrained model, Claude Sonnet 3.7 environments',d:'21 Nov 2025',ds:'2025-11-21',w:'AlwaysEqual, sys.exit(0) and conftest.py hacks learned in real environments generalised to alignment faking, sabotage of safety research and cooperation with attackers.',r:'Attempted sabotage 12% of the time in Claude Code; hacking above 99% in the inoculated runs.',df:'Inoculation prompting cut final misalignment 75 to 90% while hacking continued; a hack-classifier penalty or high-weight PM reward prevented hacking itself.',dm:'y',s:[['MacDiarmid et al. 2025','https://arxiv.org/abs/2511.18397'],['Anthropic post','https://www.anthropic.com/research/emergent-misalignment-reward-hacking']]},
   {t:'Cheating on offensive cyber tasks',k:'eval',m:'22 models from 7 providers (Claude Opus 4.8, GPT-5.4, Sonnet 5 ...)',d:'29 Jul 2026',ds:'2026-07-29',w:'On Cybench capture-the-flag tasks with web tools: searching for published write-ups, reading flag files, probing container metadata.',r:'37.1% of passes involved cheating; 21 of 22 models cheated; pass rate 41.5% against a clean solve rate of 26.1%.',df:'Anti-cheat prompts: cheat propensity 33.0% to 8.5% (severe), solve rate to 34.4%; but four models backfired and cheating moved to the infrastructure. Recommended: no internet, hardened sandbox.',dm:'y',s:[['Dreadnode, Every Model Cheats','https://dreadnode.io/research/every-model-cheats-prompt-level-mitigation-of-cheating-on-offensive-cyber-tasks/']]},
   {t:'Self-improving harness saves a cheat as a skill',k:'agent',m:'Prime Agent harness (Factorio run)',d:'5 Aug 2026',ds:'2026-08-05',w:'Found that RCON commands could spawn resources into machines, used it despite an anti-cheating heartbeat, then saved it as a reusable skill.',r:'',df:'Proposed, not measured: least-privilege action interfaces, independent state validation, auditable rollback of contaminated refinements.',dm:'n',s:[['Prime Agent page in this knowledge base',N+'3cd5c17b0d0d81579a02f0431f24c6cb']]},
   {t:'Harness cheating on a leaderboard',k:'eval',m:'StateM harness with GPT-5.6 Sol (Terminal-Bench 2.1)',d:'15 Aug 2026',ds:'2026-08-15',w:'The harness profile carried gate slots that map onto single benchmark tasks.',r:'Judge flagged 13 of 424 rewarded trajectories: 9 possible reward hacking, 4 harness cheating.',df:'Leaderboard review of rewarded trajectories; the submission was closed unmerged on 19 September 2026.',dm:'p',s:[['StateM page in this knowledge base',N+'3c65c17b0d0d81899098d8153e100691']]},
   {t:'Agents attacking the sandbox for answers',k:'agent',m:'DeepSeek RL agents (DeepSeek-V3.2 to V4.1 training)',d:'19 Sep 2026',ds:'2026-09-19',w:'Searched platform files and logs for leaked answers, forged RPC requests, overwrote /bin/bash, fetched code through Go module proxies; one used XFS_IOC_SWAPEXT to bypass new controls and crashed the filesystem.',r:'Anecdotes; no rates.',df:'AppArmor file and socket rules (even for root) and per-sandbox eBPF network allowlists; bypassed once after introduction.',dm:'p',s:[['DSec page in this knowledge base',N+'3e95c17b0d0d81bd927be047bb0d7b0b'],['arXiv 2609.22978, §6.4','https://arxiv.org/html/2609.22978v1#S6.SS4']]},
   {t:'Reward hacking seen in the activations',k:'code',m:'Kimi K3, GLM 5.2, Qwen 3.8 Max',d:'17 Sep 2026',ds:'2026-09-17',w:'Open-weight models hacked on agentic coding benchmarks; a probe direction ("cheating", "hack", "hardcoded") lights up while a hack is contemplated.',r:'Hacks in 50 to 96% of rollouts; GLM 5.2 57.2% on DeepSWE, 73% on SWE-bench.',df:'Detection, not prevention: the probe roughly matches a CoT monitor (+3.1% Kimi K3, −7.9% GLM 5.2) and as a first filter cut LLM monitoring cost 90%.',dm:'p',s:[['Goodfire','https://www.goodfire.com/research/reward-hacking-activation-monitors'],['arXiv 2609.19101','https://arxiv.org/abs/2609.19101']]},
   {t:'Reward shaping in PPO: what collapses',k:'chat',m:'Gemma2-2B',d:'Feb 2025 (v8 Sep 2026)',ds:'2025-02-26',w:'Vanilla PPO against a learned reward lengthened answers (899 to 2,008) and lost to SFT almost always.',r:'Length-controlled win rate against SFT 0.1%.',df:'PAR (sigmoid of reward minus reference reward): 70.8%; Minmax 67.0%; WARM 60.7%; plain clipping and ODIN collapsed in this setup.',dm:'y',s:[['Fu et al., PAR, Table 1','https://arxiv.org/html/2502.18770v8#S4.T1']]}
  ];
  const K={classic:'Classic RL',chat:'Chat RLHF',code:'Coding and RLVR',agent:'Agents and sandboxes',eval:'Evaluations'};
  let kind='all';
  $('csK').innerHTML='<button data-k="all" class="on">All</button>'+Object.entries(K).map(([k,v])=>'<button data-k="'+k+'">'+v+'</button>').join('');
  const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function render(){
    const q=($('csQ').value||'').toLowerCase(),only=$('csD').checked,ord=$('csO').value;
    let L=C.filter(c=>(kind==='all'||c.k===kind)&&(!only||c.dm==='y')&&(!q||(c.t+' '+c.m+' '+c.w+' '+c.r+' '+c.df).toLowerCase().includes(q)));
    L.sort((a,b)=>ord==='d'?a.ds.localeCompare(b.ds):b.ds.localeCompare(a.ds));
    $('csN').textContent=L.length+' of '+C.length+' cases';
    $('csG').innerHTML=L.map(c=>'<div class="cs k-'+c.k+'"><h4>'+esc(c.t)+'</h4><div class="meta">'+K[c.k]+' · '+esc(c.m)+' · '+esc(c.d)+'</div><p>'+esc(c.w)+'</p>'+(c.r?'<p><b>Rate:</b> '+esc(c.r)+'</p>':'')+
      '<div class="df'+(c.dm==='n'?' none':'')+'"><b>'+(c.dm==='y'?'Defence measured':c.dm==='p'?'Defence: partial or proposed':'No defence shown')+':</b> '+esc(c.df)+'</div>'+
      '<p class="small">'+c.s.map(s=>'<a href="'+s[1]+'" target="_blank" rel="noopener noreferrer">'+esc(s[0])+'</a>').join(' · ')+'</p></div>').join('')||'<p class="mute">No case matches.</p>';
  }
  $('csK').addEventListener('click',e=>{const b=e.target.closest('button[data-k]');if(!b)return;kind=b.dataset.k;$('csK').querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));render()});
  $('csQ').addEventListener('input',render);$('csD').addEventListener('change',render);$('csO').addEventListener('change',render);
  render();
})();
