// ---- Tables tab ----
(function(){const T=PAPER.tables,V=RCV,esc=t=>String(t==null?'':t).replace(/&/g,'&amp;').replace(/</g,'&lt;');
  // Table 4, sortable, with the gain over the same model's reference
  const ref={},rsc={};T.t4.rows.forEach(r=>{if(r[5]==='ref'||r[5]==='base'){ref[r[6]]=r[3];rsc[r[6]]=r[2]}});const dp=v=>{const d=(String(v).split('.')[1]||'').length;return fmt(v,Math.max(1,d))};
  let sk=-1,sd=1;
  function t4(){let rows=T.t4.rows.map(r=>r.concat([r[5]==='ours'&&ref[r[6]]!=null&&rsc[r[6]]===r[2]?r[3]-ref[r[6]]:null]));
    if(sk>=0)rows.sort((a,b)=>{const x=a[sk],y=b[sk];return (typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y)))*sd});
    const H=['System','Source / profile','Scope','Score (%)','Coverage','gain'];const idx=[0,1,2,3,4,7];
    $('t4').innerHTML='<table><thead><tr>'+H.map((h,i)=>'<th class="'+(i>=3&&i!==4?'num':'')+'"><button class="small" data-k="'+idx[i]+'" style="padding:1px 6px">'+h+(sk===idx[i]?(sd>0?' ▲':' ▼'):'')+'</button></th>').join('')+'</tr></thead><tbody>'+
      rows.map(r=>'<tr><td>'+(r[5]==='ours'?'<b>'+esc(r[0])+'</b>':esc(r[0]))+'</td><td>'+esc(r[1])+'</td><td>'+esc(r[2])+'</td><td class="num">'+dp(r[3])+'</td><td>'+esc(r[4])+'</td><td class="num">'+(r[7]==null?'':(r[7]>=0?'+':'')+fmt(r[7],2))+'</td></tr>').join('')+'</tbody></table>';
    $('t4').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const k=+b.dataset.k;sd=sk===k?-sd:1;sk=k;t4()}))}
  t4();
  // leaderboard
  const subs=[['142','StateM, GPT-5.6 Sol xhigh'],['45','GPT-5.5 xhigh + Codex'],['47','GPT-5.5 xhigh + Terminus 2'],['102','GPT-5.6 Sol max + Codex'],['106','GPT-5.6 Terra max (1st)'],['115','GPT-5.6 Terra max (2nd)'],['105','GPT-5.6 Luna max (1st)'],['112','GPT-5.6 Luna max (2nd)']];
  let lm='raw';
  function lb(){const rows=subs.map(([k,n])=>{const e=T.lb[k];if(k==='142')return {n,b:lm==='raw'?e.raw_acc:V.all13,c:'var(--good)',bold:1,note:lm==='raw'?'raw':'review not completed; all 13 flags zeroed'};return {n,b:lm==='raw'?e.raw_acc:e.adj_acc,note:(e.dq_trials||0)+' zeroed'}});
    hbars($('lbPlot'),rows,60,100,{one:1,unit:'%',d:2,label:'Leaderboard submissions'})}
  segBind('lbM',m=>{lm=m;lb()});onTab('t-tables',lb);
  $('lbTab').innerHTML='<table><thead><tr><th>PR</th><th>Submission</th><th class="num">Raw</th><th class="num">SE</th><th class="num">After review</th><th class="num">Zeroed</th><th class="num">Tokens</th><th class="num">Cost</th><th>Status</th></tr></thead><tbody>'+subs.map(([k,n])=>{const e=T.lb[k];
    return '<tr><td><a href="https://github.com/harbor-framework/terminal-bench-2-1/pull/'+k+'" target="_blank" rel="noopener noreferrer">#'+k+'</a></td><td>'+esc(n)+'<br><span class="small mute">'+esc(e.note)+'</span></td><td class="num">'+fmt(e.raw_acc,2)+'%</td><td class="num">'+fmt(e.raw_se,2)+'</td><td class="num">'+(e.adj_acc!=null?fmt(e.adj_acc,2)+'%':'not reviewed')+'</td><td class="num">'+(e.dq_trials!=null?e.dq_trials:(k==='142'?'13 flagged':''))+'</td><td class="num">'+fmt(e.tokens/1e6,0)+'M</td><td class="num">'+usd(e.cost,2)+'</td><td>'+(e.merged?'merged':'closed, not merged '+e.closed)+'</td></tr>'}).join('')+'</tbody></table>'+
    '<p class="small mute">StateM\'s PR: the judge read '+T.lb['142'].judged[0]+' rewarded trajectories and flagged '+T.lb['142'].judged[1]+': harness cheating on '+T.lb['142'].flags.harness_cheating.join(', ')+'; possible reward hacking on '+T.lb['142'].flags.reward_hacking.join(', ')+'. Several earlier PRs for the same configuration were closed in favour of a resubmission; only the final ones are listed.</p>';
  // Table 3 joined with the DeepSeek run, gates and flags
  const flagged=new Set(T.lb['142'].flags.harness_cheating),gated=new Set(V.t3_gated);
  $('t3').innerHTML='<table><thead><tr><th>Task</th><th class="num">Codex CLI</th><th class="num">StateM-Codex</th><th class="num">Δ</th><th>Associated control (paper)</th><th class="num">DeepSeek + StateM</th><th>gate selected</th><th>judge flag (GPT-5.6)</th></tr></thead><tbody>'+
    T.t3.rows.map(r=>'<tr><td class="mono">'+r[0]+'</td><td class="num">'+r[1]+'/5</td><td class="num">'+r[2]+'/5</td><td class="num">+'+(r[2]-r[1])+'</td><td>'+esc(r[3])+'</td><td class="num">'+V.t3_ds[r[0]]+'/5</td><td>'+(gated.has(r[0])?'yes':'')+'</td><td>'+(flagged.has(r[0])?'<b>harness cheating</b>':'')+'</td></tr>').join('')+'</tbody></table>';
  $('t3Note').innerHTML='The twelve deltas sum to '+V.t3_trials+' trials, '+fmt(V.t3_pts,2)+' points of the 9.0-point gain (formula: 35 / 445). '+V.t3_gated.length+' of the 12 tasks had a task-family gate selected in the DeepSeek run; '+V.t3_flagged.length+' were flagged as harness cheating on the GPT-5.6 submission (the fourth flagged task, extract-elf, is not in Table 3). The paper selects these rows as "representative" of the largest gains; it does not list the tasks that got worse.';
  // Tables 1 and 2
  function t12(m){if(m==='t1'){$('t12').innerHTML='<table><thead><tr><th>Scope / family</th><th class="num">Codex CLI</th><th class="num">StateM-Codex</th><th class="num">Δ printed</th><th class="num">Δ recomputed</th></tr></thead><tbody>'+T.t1.groups.map(([h,rs])=>'<tr><td colspan="5" class="small mute"><i>'+esc(h)+'</i></td></tr>'+rs.map(r=>'<tr><td>'+esc(r[0])+'</td><td class="num">'+fmt(r[1],2)+'</td><td class="num">'+(r[2]==null?'abstained':fmt(r[2],2))+'</td><td class="num">'+(r[3]==null?'n/a':(r[3]>0?'+':'')+fmt(r[3],2))+'</td><td class="num">'+(r[2]==null?'':(r[2]-r[1]>0?'+':'')+fmt(r[2]-r[1],2))+'</td></tr>').join('')).join('')+'</tbody></table><p class="small mute">The subgroup prints +10.04 from unrounded values; the rounded entries differ by 10.03, as the table note says.</p>'}
    else $('t12').innerHTML='<table><thead><tr><th>Scope</th><th class="num">Codex / prior arm</th><th class="num">Refined StateM</th><th>Interpretation</th></tr></thead><tbody>'+T.t2.rows.map(r=>'<tr><td>'+esc(r[0])+'</td><td class="num">'+(r[1]==null?'n/a':fmt(r[1],2))+'</td><td class="num">'+fmt(r[2],2)+'</td><td>'+esc(r[3])+'</td></tr>').join('')+'</tbody></table><p class="small mute">The 80.56 RefactorBench Round-1 baseline in Table 1 and the 80.56 StateM development score here are different runs and splits (Table 1 note).</p>'}
  segBind('bbM',t12);t12('t1');
  // Table 5
  $('t5').innerHTML='<table><thead><tr><th>Failure mode</th><th>Control</th><th>Applies to</th></tr></thead><tbody>'+T.t5.rows.map((r,i)=>'<tr><td><b>'+esc(r[0])+'</b></td><td><details><summary>'+esc(r[1].split('. ')[0].replace(/\.$/,''))+'</summary><p class="small">'+esc(r[1])+'</p><p class="small"><b>Enforcement and evidence:</b> '+esc(r[2])+'</p></details></td><td class="small">'+esc(r[3])+'</td></tr>').join('')+'</tbody></table>';
  // checks
  const C=PAPER.rc.checks;$('rcSum').innerHTML='<b>'+C.filter(c=>c.ok).length+' of '+C.length+' checks reproduce</b>, independently from the printed counts, the leaderboard and the released trials. Not a check but a contradiction: the Introduction\'s "38.9×" cheaper (§1) against §4.4\'s 1/37.8 ($574.68 / $15.20 = '+fmt(V.ratio_final,2)+').';
  $('rcTab').innerHTML='<table><thead><tr><th>Check</th><th class="num">Recomputed</th><th class="num">Printed</th><th>Where</th><th></th></tr></thead><tbody>'+C.map(c=>'<tr><td>'+esc(c.n)+'</td><td class="num">'+fmt(c.got,c.got%1||String(c.want).indexOf('.')>=0?Math.max(1,(String(c.want).split('.')[1]||'').length):0)+'</td><td class="num">'+(c.want>=1000?fmt(c.want):c.want)+'</td><td class="small">'+esc(c.src)+'</td><td>'+(c.ok?'<span class="ok">ok</span>':'<span class="no">no</span>')+'</td></tr>').join('')+'</tbody></table>';
})();
