"""Write parts/33_js_a_data.js from recordings/ only (the redacted copies).
Usage: python3 build_data.py
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
R = os.path.join(HERE, "recordings")
OUT = os.path.join(HERE, "..", "parts", "33_js_a_data.js")


def load(fn):
    p = os.path.join(R, fn)
    return json.load(open(p)) if os.path.exists(p) else None


def r2(x):
    return round(x, 3)


def gateway():
    out = {}
    for s in load("gateway.json"):
        t0 = s["requests"][0]["t0"]
        reqs = []
        for q in s["requests"]:
            b = q["body"]
            reqs.append({"t0": r2(q["t0"] - t0), "t1": r2(q["t1"] - t0), "status": q["status"], "key": q.get("key"),
                         "spend": q.get("spend_after"), "hdr": q["headers"],
                         "who": (b.get("model") if isinstance(b, dict) and "model" in b else None),
                         "err": (b["error"] if isinstance(b, dict) and "error" in b else None),
                         "usage": (b.get("usage") if isinstance(b, dict) else None)})
        out[s["scenario"]] = {"req": reqs, "keys": s.get("key_settings"),
                              "up": [{"t0": r2(u["t0"] - t0), "t1": r2(u["t1"] - t0), "beh": u["behaviour"], "status": u["status"]} for u in s["upstream"]],
                              "bk": [{"t0": r2(b["t0"] - t0), "t1": r2(b["t1"] - t0), "status": b["status"]} for b in s["backup"]]}
    return out


def spans(fn):
    sp = load(fn)
    if sp is None:
        return None
    return [{"id": s["id"], "p": s["parent"], "n": s["name"], "k": s["kind"], "t0": round(s["t0"], 3), "t1": round(s["t1"], 3),
             "st": s["status"], "a": s["attrs"], "ev": s.get("events", [])} for s in sp]


def main():
    D = {"date": "2026-10-05", "litellm": "1.104.0", "gw": gateway(), "gw_lesson": load("gateway_lesson.json"),
         "cc_spans": spans("cc_otel_spans.json"), "cc_events": load("cc_otel_events.json"),
         "loop_manual": spans("loop_manual_spans.json"), "loop_auto": spans("loop_auto_spans.json"),
         "loop_manual_res": load("loop_manual_result.json"), "loop_auto_res": load("loop_auto_result.json"),
         "memory": load("memory.json"), "evals": load("evals.json"), "redaction": load("redaction.json")}
    if D["memory"]:
        import sys
        sys.path.insert(0, os.path.join(HERE, "code"))
        import mem_data
        D["memory"]["sessions"] = mem_data.SESSIONS
        D["memory"]["questions"] = [{k: q[k] for k in ("id", "q", "kind")} for q in mem_data.QUESTIONS]
        D["memory"]["ask_date"] = mem_data.ASK_DATE
    # the Claude Code result record of the traced run
    for line in open(os.path.join(R, "cc_otel_haiku.jsonl")):
        d = json.loads(line)
        if d.get("type") == "result":
            D["cc_result"] = {k: d.get(k) for k in ("num_turns", "duration_ms", "total_cost_usd", "usage", "modelUsage")}
        if d.get("type") == "system" and d.get("subtype") == "init":
            D["cc_init"] = d
    js = "// generated by src/ops/build_data.py from src/ops/recordings (redacted); do not edit\nwindow.OPS=" + json.dumps(D, ensure_ascii=False, separators=(",", ":")) + ";\n"
    open(OUT, "w").write(js)
    print("wrote", OUT, len(js), "bytes")


main()
