"""Turn the training logs (model/runs/*.json), the export report and the forward check into parts/_gen_runs.js (window.RUNS)."""
import glob, json, os
HERE = os.path.dirname(os.path.abspath(__file__))
runs = []
for f in sorted(glob.glob(os.path.join(HERE, 'model', 'runs', '*.json'))):
    r = json.load(open(f))
    tr = next((l[2] for l in r['log'] if l[0] == r['best_step']), None)
    runs.append({k: r[k] for k in ('arch', 'n', 'seed', 'params', 'macs', 'steps', 'batch', 'lr', 'best_step', 'val', 'test', 'epochs', 'secs', 'log')} | {'train_at_best': tr})
ld = lambda p: json.load(open(os.path.join(HERE, 'model', p))) if os.path.exists(os.path.join(HERE, 'model', p)) else {}
out = {'runs': runs, 'report': ld('report.json'), 'check': ld('check_forward.json'), 'pos': ld('pos_check.json')}
open(os.path.join(HERE, 'parts', '_gen_runs.js'), 'w').write('// Generated by mk_runs.py from model/runs/*.json, model/report.json and model/check_forward.json.\nwindow.RUNS=' + json.dumps(out, separators=(',', ':')) + ';\n')
print('mk_runs:', len(runs), 'runs', 'wall-clock training minutes %.1f' % (sum(r['secs'] for r in runs) / 60))
