// A local stand-in for a model API. It speaks the real wire formats (Anthropic Messages, OpenAI Responses),
// so the official SDKs talk to it unchanged, but its "model" is a short script: every answer below is
// SYNTHETIC, chosen by rules in decide(), never generated by a language model. Usage numbers are a
// mock estimate (characters / 4), not a real tokenizer.
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";

type Block = { type: "text"; text: string } | { type: "tool_use"; id: string; name: string; input: Record<string, unknown> };
export type LogEntry = { n: number; path: string; scenario: string; stream: boolean; headers: Record<string, string>; request: any; response?: any; sse?: string; closedEarly?: string };

let seq = 0;
const id = (p: string) => `${p}_mock_${String(++seq).padStart(3, "0")}`;
const est = (x: unknown) => Math.ceil(JSON.stringify(x).length / 4);   // mock token estimate

// The scripted "model". It reads the conversation the way a real model would see it and picks the next turn.
function decide(scenario: string, messages: any[]): { blocks: Block[]; stop: string } {
  const results = messages.flatMap(m => Array.isArray(m.content) ? m.content.filter((b: any) => b.type === "tool_result") : []);
  const text = (t: string): Block => ({ type: "text", text: t });
  const call = (name: string, input: Record<string, unknown>): Block => ({ type: "tool_use", id: id("toolu"), name, input });
  const last = results.at(-1);
  const body = (r: any) => typeof r.content === "string" ? r.content : r.content?.map((c: any) => c.text).join("") ?? "";
  if (scenario === "chat") {
    const q = String(messages.at(-1)?.content ?? "");
    if (/my name is/i.test(q)) return { blocks: [text("Nice to meet you.")], stop: "end_turn" };
    if (/name/i.test(q)) {
      const named = messages.map(m => String(m.content)).join(" ").match(/my name is (\w+)/i);
      return { blocks: [text(named ? `Your name is ${named[1]}.` : "I don't know your name: it is not in this conversation.")], stop: "end_turn" };
    }
    return { blocks: [text("TypeScript is JavaScript with static types that are checked before the program runs and erased when it runs.")], stop: "end_turn" };
  }
  if (scenario === "long") {   // a long answer, to have something to cancel
    return { blocks: [text(Array.from({ length: 12 }, (_, i) => `Sentence ${i + 1} of a long synthetic answer about TypeScript.`).join(" "))], stop: "end_turn" };
  }
  if (scenario === "extract") {   // structured output: answer with JSON only
    return { blocks: [text(JSON.stringify({ user: "u0029", tokens: 9491, share_pct: 21.2 }))], stop: "end_turn" };
  }
  if (scenario === "extract_bad") {   // a plausible but wrong shape: tokens as a string, a field missing
    return { blocks: [text('{"user": "u0029", "tokens": "9491"}')], stop: "end_turn" };
  }
  // Agent scenarios: the task is "Who are the 3 heaviest users in chat.jsonl and what share of all tokens do they have?"
  if (scenario === "runaway") {   // a model that never decides it has enough: asks for one more user every time
    return { blocks: [call("count_tokens", { path: "chat.jsonl", top: results.length + 1 })], stop: "tool_use" };
  }
  if (results.length === 0) {
    const path = scenario === "typo" ? "chats.jsonl" : "chat.jsonl";
    return { blocks: [text("I'll count the tokens per user first."), call("count_tokens", { path, top: 3 })], stop: "tool_use" };
  }
  if (last.is_error && /cannot open/.test(body(last))) {
    return { blocks: [text("That file does not exist; the log is chat.jsonl."), call("count_tokens", { path: "chat.jsonl", top: 3 })], stop: "tool_use" };
  }
  const counted = results.map(body).find(s => s.startsWith("{") && s.includes('"top"'));
  const stats = counted ? JSON.parse(counted) : null;
  const askedProfiles = messages.some(m => Array.isArray(m.content) && m.content.some((b: any) => b.type === "tool_use" && b.name === "user_profile"));
  if (stats && !askedProfiles && (scenario === "happy" || scenario === "timeout")) {
    // two calls in one turn: the caller should run them concurrently
    return { blocks: [text("Now the teams of the top two users."), ...stats.top.slice(0, 2).map((u: any) => call("user_profile", { user: u.user }))], stop: "tool_use" };
  }
  const sum = stats.top.reduce((a: number, u: any) => a + u.tokens, 0);
  const share = (100 * sum / stats.tokens).toFixed(1);
  const teams = results.filter(r => body(r).startsWith('{"user"')).map(r => JSON.parse(body(r))).map((p: any) => `${p.user} is on ${p.team}`);
  const failed = results.filter(r => r.is_error && !/cannot open/.test(body(r))).length;
  return { blocks: [text(`The three heaviest users are ${stats.top.map((u: any) => `${u.user} (${u.tokens})`).join(", ")}: ${sum} of ${stats.tokens} tokens, ${share}%.` +
    (teams.length ? ` ${teams.join("; ")}.` : "") + (failed ? ` ${failed} profile lookup${failed > 1 ? "s" : ""} timed out, so I left the team out.` : ""))], stop: "end_turn" };
}

// Split text the way a token stream arrives: a word (with its leading space) at a time.
const pieces = (s: string) => s.match(/\s*\S+/g) ?? [s];
const chunks = (s: string, n: number) => Array.from({ length: Math.ceil(s.length / n) }, (_, i) => s.slice(i * n, i * n + n));
const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

async function readJson(req: IncomingMessage) {
  let s = ""; for await (const c of req) s += c;
  try { return JSON.parse(s); } catch { return {}; }          // GET requests and junk: no body
}

export async function startMock(opts: { delayMs?: number; port?: number } = {}) {
  const log: LogEntry[] = [];
  const server = createServer(async (req: IncomingMessage, res: ServerResponse) => {
    const body = await readJson(req);
    const scenario = String(req.headers["x-mock-scenario"] ?? "chat");
    const path = new URL(req.url ?? "", "http://x").pathname;     // the tool runner adds ?beta=true
    const headers = Object.fromEntries(["anthropic-version", "anthropic-beta", "content-type", "x-stainless-retry-count", "x-stainless-timeout", "user-agent"]
      .filter(h => req.headers[h]).map(h => [h, String(req.headers[h])]));
    const entry: LogEntry = { n: log.length + 1, path: req.url ?? "", scenario, stream: !!body.stream, headers, request: body };
    log.push(entry);
    let closed = false; res.on("close", () => { if (!res.writableFinished) closed = true; });
    const send = async (events: [string, any][]) => {        // one SSE event per write, delayMs apart
      res.writeHead(200, { "content-type": "text/event-stream", "cache-control": "no-cache" });
      let sse = "", i = 0;
      for (const [ev, data] of events) {
        if (closed) { entry.closedEarly = `client went away after ${i} of ${events.length} events`; break; }
        const frame = `event: ${ev}\ndata: ${JSON.stringify(data)}\n\n`;
        sse += frame; res.write(frame); i++;
        if (opts.delayMs) await sleep(opts.delayMs);
      }
      entry.sse = sse; res.end();
    };
    if (path === "/v1/messages") {
      const { blocks, stop } = decide(scenario, body.messages ?? []);
      const usage = { input_tokens: est([body.system, body.messages, body.tools]), output_tokens: est(blocks) };
      const msg = { id: id("msg"), type: "message", role: "assistant", model: body.model, content: blocks, stop_reason: stop, stop_sequence: null, usage };
      if (!body.stream) { entry.response = msg; res.writeHead(200, { "content-type": "application/json", "request-id": id("req") }); res.end(JSON.stringify(msg)); return; }
      const ev: [string, any][] = [["message_start", { type: "message_start", message: { ...msg, content: [], stop_reason: null, usage: { ...usage, output_tokens: 1 } } }]];
      blocks.forEach((b, index) => {
        if (b.type === "text") {
          ev.push(["content_block_start", { type: "content_block_start", index, content_block: { type: "text", text: "" } }]);
          if (index === 0) ev.push(["ping", { type: "ping" }]);
          for (const t of pieces(b.text)) ev.push(["content_block_delta", { type: "content_block_delta", index, delta: { type: "text_delta", text: t } }]);
        } else {
          ev.push(["content_block_start", { type: "content_block_start", index, content_block: { type: "tool_use", id: b.id, name: b.name, input: {} } }]);
          for (const p of chunks(JSON.stringify(b.input), 12)) ev.push(["content_block_delta", { type: "content_block_delta", index, delta: { type: "input_json_delta", partial_json: p } }]);
        }
        ev.push(["content_block_stop", { type: "content_block_stop", index }]);
      });
      ev.push(["message_delta", { type: "message_delta", delta: { stop_reason: stop, stop_sequence: null }, usage: { output_tokens: usage.output_tokens } }]);
      ev.push(["message_stop", { type: "message_stop" }]);
      await send(ev); return;
    }
    if (path === "/v1/responses") {   // OpenAI Responses API: same brain, OpenAI's shapes
      const input = typeof body.input === "string" ? [{ role: "user", content: body.input }] : body.input;
      const { blocks } = decide(scenario, input);
      const text = blocks.filter(b => b.type === "text").map(b => (b as any).text).join(" ");
      const item = { type: "message", id: id("msg"), status: "completed", role: "assistant", content: [{ type: "output_text", text, annotations: [] }] };
      const usage = { input_tokens: est(input), output_tokens: est(text), total_tokens: est(input) + est(text) };
      const resp = { id: id("resp"), object: "response", created_at: 1759650000, status: "completed", model: body.model, output: [item], usage };
      if (!body.stream) { entry.response = resp; res.writeHead(200, { "content-type": "application/json" }); res.end(JSON.stringify(resp)); return; }
      let n = 0; const e = (type: string, x: any): [string, any] => [type, { type, sequence_number: n++, ...x }];
      const ev: [string, any][] = [e("response.created", { response: { ...resp, status: "in_progress", output: [] } }),
        e("response.output_item.added", { output_index: 0, item: { ...item, status: "in_progress", content: [] } }),
        e("response.content_part.added", { item_id: item.id, output_index: 0, content_index: 0, part: { type: "output_text", text: "", annotations: [] } })];
      for (const t of pieces(text)) ev.push(e("response.output_text.delta", { item_id: item.id, output_index: 0, content_index: 0, delta: t, logprobs: [] }));
      ev.push(e("response.output_text.done", { item_id: item.id, output_index: 0, content_index: 0, text, logprobs: [] }),
        e("response.content_part.done", { item_id: item.id, output_index: 0, content_index: 0, part: item.content[0] }),
        e("response.output_item.done", { output_index: 0, item }), e("response.completed", { response: resp }));
      await send(ev); return;
    }
    res.writeHead(404).end();
  });
  await new Promise<void>(r => server.listen(opts.port ?? 0, "127.0.0.1", r));
  const port = (server.address() as any).port;
  return { url: `http://127.0.0.1:${port}`, log, close: () => new Promise(r => { server.closeAllConnections(); server.close(r); }) };
}

if (import.meta.main) {   // run on its own: node mock_model.ts 8787
  const m = await startMock({ port: Number(process.argv[2] ?? 8787), delayMs: 30 });
  console.log(`mock model API on ${m.url} (synthetic answers)`);
}
