// ---- SGLang on the M1 (t-sgm1): renders SGD.m1 (src/m1/summarise.py) ----
(function(){
  const root=document.getElementById('t-sgm1');if(!root)return;const $=id=>document.getElementById(id),f=(n,d)=>n.toLocaleString('en-US',{maximumFractionDigits:d||0,minimumFractionDigits:d||0});
  function render(){if(root.hidden)return;const m=window.SGD&&SGD.m1;if(!m)return;
    if(m.load_range)$('sgm-load').textContent=f(m.load_range[0],1)+' to '+f(m.load_range[1],1);
    const rp=m.repro||{};let h='<table><thead><tr><th>Request</th><th class="num">Cached tokens</th><th>v0.5.21 + start-up fix only</th><th>+ cache fix (PR #42542)</th></tr></thead><tbody>';
    const a=rp.repro_overlap_on,b=rp.repro_pr42542_overlap_on;
    if(a&&b){a.runs.forEach((r,i)=>{const r2=b.runs[i];h+='<tr><td>'+r.req+'</td><td class="num">'+r.cached+' of '+r.prompt+'</td><td'+(r.req==='A'&&i>0&&r.text!==a.runs[0].text?' class="bad"':'')+'>'+RD.esc(r.text.slice(0,60))+'…</td><td>'+RD.esc(r2.text.slice(0,60))+'…</td></tr>'});
      $('sgm-repro').innerHTML=h+'</tbody></table><p class="small">Without the fix the second and third A answer a different question. With it they are consistent with each other; that they differ from the first A after a few tokens is rounding (next paragraph).</p>'}
    const sp=rp.split;if(sp){const k=Object.keys(sp.runs);$('sgm-split').innerHTML='<b>Split prefill in MLX-LM alone</b> (no SGLang), same weights, prompt A of '+sp.n_prompt+' tokens computed in one piece or in two: '+k.map(x=>(x==='0'?'one piece':'split after '+x+' tokens')+': <i>'+RD.esc(sp.runs[x].text.slice(0,48))+'…</i>').join('; ')+'. At the ninth generated token, where the texts part, the gap between the two best candidates was '+k.map(x=>sp.runs[x].first8_margins[8].toFixed(3)).join(', ')+' in logit in the three runs: a near-tie that a different rounding order flips.'}
    if(m.sched){let t='<div class="tw"><table><thead><tr><th>Policy</th><th class="num">Prompt tokens from cache</th><th class="num">Batch time, s (min to max)</th><th class="num">Mean TTFT, s</th><th class="num">Runs</th></tr></thead><tbody>';
      for(const p of ['fcfs','lpm','dfs-weight','random']){const r=m.sched[p];if(!r)continue;t+='<tr><td>'+p+'</td><td class="num">'+f(r.cached_pct,1)+'% ('+f(r.cached_min,1)+' to '+f(r.cached_max,1)+')</td><td class="num">'+f(r.makespan,1)+' ('+f(r.makespan_min,1)+' to '+f(r.makespan_max,1)+')</td><td class="num">'+f(r.ttft_mean,2)+'</td><td class="num">'+r.reps+'</td></tr>'}
      $('sgm-sched').innerHTML='<p class="small">64 questions of 40 tokens about 8 documents of 800 tokens, sent at once in one fixed shuffled order; 16 output tokens each; <code>--max-total-tokens 24000</code> (roomy: eviction crashed this backend) and at most 8 running; <code>--schedule-policy</code> as listed.</p>'+t+'</tbody></table></div>'}
    const mt=m.multiturn;if(mt&&mt.radix_on&&mt.radix_off){const el=$('sgm-mt'),w=RD.width(el),h=190,x0=44,pw=w-x0-10,ph=140;const mx=Math.max(...['radix_on','radix_off'].flatMap(k=>mt[k].by_turn.map(t=>t.ttft.max)))*1.1;
      let b='';for(let v=0;v<=mx;v+=mx>2?0.5:0.1){const y=8+ph*(1-v/mx);b+='<line x1="'+x0+'" x2="'+(x0+pw)+'" y1="'+y+'" y2="'+y+'" stroke="var(--line)"/>'+RD.t(x0-4,y+4,f(v,1)+' s',{a:'end',fs:10,fill:'var(--mute)'})}
      const gw=pw/4,bw=gw*0.32;mt.radix_on.by_turn.forEach((t,i)=>{[['radix_on','var(--good)',0],['radix_off','var(--bad)',1]].forEach(([k,c,j])=>{const v=mt[k].by_turn[i].ttft,x=x0+i*gw+gw*0.16+j*bw,y=8+ph*(1-v.mean/mx);
          b+='<rect x="'+x.toFixed(1)+'" y="'+y.toFixed(1)+'" width="'+(bw-2).toFixed(1)+'" height="'+(8+ph-y).toFixed(1)+'" fill="'+c+'"><title>'+k+', turn '+(i+1)+': '+f(v.mean,3)+' s ('+f(v.min,3)+' to '+f(v.max,3)+')</title></rect>';
          b+='<line x1="'+(x+bw/2-1)+'" x2="'+(x+bw/2-1)+'" y1="'+(8+ph*(1-v.min/mx)).toFixed(1)+'" y2="'+(8+ph*(1-v.max/mx)).toFixed(1)+'" stroke="var(--ink)"/>'});
        b+=RD.t(x0+i*gw+gw/2,h-26,'turn '+(i+1),{a:'middle',fs:11})+RD.t(x0+i*gw+gw/2,h-12,'~'+f(t.prompt)+' tokens',{a:'middle',fs:10,fill:'var(--mute)'})});
      el.innerHTML=RD.svg(w,h,b,'Mean time to first token by turn, cache on and off');
      let t='<div class="tw"><table><thead><tr><th>Turn</th><th class="num">Prompt tokens</th><th class="num">Cached, on</th><th class="num">TTFT on, s</th><th class="num">TTFT off, s</th><th class="num">Off / on</th></tr></thead><tbody>';
      mt.radix_on.by_turn.forEach((x,i)=>{const y=mt.radix_off.by_turn[i];t+='<tr><td>'+x.turn+'</td><td class="num">'+f(x.prompt)+'</td><td class="num">'+f(x.cached)+'</td><td class="num">'+f(x.ttft.mean,3)+'</td><td class="num">'+f(y.ttft.mean,3)+'</td><td class="num">'+f(y.ttft.mean/x.ttft.mean,1)+'×</td></tr>'});
      $('sgm-mt-t').innerHTML=t+'</tbody></table></div><p class="small">Mean over the 8 conversations, then over '+mt.radix_on.reps+' runs (whiskers: min and max run). Time per output token: '+f(mt.radix_on.tpot_ms.mean,0)+' ms with the cache ('+f(mt.radix_on.tpot_ms.min,0)+' to '+f(mt.radix_on.tpot_ms.max,0)+'), '+f(mt.radix_off.tpot_ms.mean,0)+' ms without ('+f(mt.radix_off.tpot_ms.min,0)+' to '+f(mt.radix_off.tpot_ms.max,0)+'). Whole job: '+f(mt.radix_on.makespan.mean,1)+' s with the cache, '+f(mt.radix_off.makespan.mean,1)+' s without: the first token comes sooner, the rest more slowly, on this backend.</p>'}
    const o=m.overlap;if(!(o&&o.on))$('sgm-ovl').innerHTML='<p class="small">No result: every run crashed (6 configurations, each retried once on a fresh server). With the overlap loop on, the Metal out-of-memory error inside the chained-decode path; with it off, an error in the overlap bookkeeping (<code>overlap_utils.py</code>, <code>stash</code>). A short decode (32 tokens) had worked in the first smoke tests; 128-token outputs in sequence did not.</p>';
    if(o&&o.on&&o.off){let t='<table><thead><tr><th class="num">Concurrency</th><th class="num">Overlap on, tok/s</th><th class="num">Overlap off, tok/s</th><th class="num">On / off</th><th class="num">ms per token on / off</th></tr></thead><tbody>';
      for(const c of ['1','4','8']){const a=o.on[c],b=o.off[c];t+='<tr><td class="num">'+c+'</td><td class="num">'+f(a.tok_s,1)+' ('+f(a.tok_s_min,1)+' to '+f(a.tok_s_max,1)+')</td><td class="num">'+f(b.tok_s,1)+' ('+f(b.tok_s_min,1)+' to '+f(b.tok_s_max,1)+')</td><td class="num">'+f(a.tok_s/b.tok_s,2)+'</td><td class="num">'+f(a.ms_per_token,2)+' / '+f(b.ms_per_token,2)+'</td></tr>'}
      $('sgm-ovl').innerHTML=t+'</tbody></table><p class="small">Mean of '+o.on['1'].reps+' runs per setting (range in brackets).</p>'}
    const j=m.json;if(j&&j.free&&j.schema){let t='<table><thead><tr><th></th><th class="num">Median time per output token, ms</th><th class="num">Median TTFT, ms</th><th class="num">Mean output tokens</th><th class="num">Valid JSON</th></tr></thead><tbody>';
      for(const k of ['free','schema'])t+='<tr><td>'+(k==='free'?'No constraint':'JSON schema (XGrammar)')+'</td><td class="num">'+f(j[k].tpot_ms_median,2)+'</td><td class="num">'+f(j[k].ttft_ms_median,0)+'</td><td class="num">'+f(j[k].tokens_mean,0)+'</td><td class="num">'+j[k].valid+' of '+j[k].n+'</td></tr>';
      $('sgm-json').innerHTML=t+'</tbody></table><p class="small">Server flag <code>--mlx-enable-sampling</code>, without which the Apple backend applies no grammar mask: '+(j.no_sampling?'a run without it gave '+j.no_sampling.valid+' valid of '+j.no_sampling.n+', each ending after about '+f(j.no_sampling.tokens_mean,0)+' tokens (<code>'+RD.esc(j.no_sampling.example.slice(0,20))+'</code>) when the grammar rejected the first token. ':'')+'First request with the new schema (grammar compilation included): TTFT '+j.schema_first_ttft_ms.map(x=>f(x,0)+' ms').join(' and ')+'. One server run; another job was running on the machine (load average '+f(j.loads[0][0],1)+'), so read the ratio, not the absolute times. Unconstrained answers fail a strict parse because the model wraps them in a Markdown fence.</p>';
      $('sgm-json-ex').innerHTML='<p class="small">One constrained answer:</p><pre>'+RD.esc(j.example)+'</pre><p class="small">The same request unconstrained:</p><pre>'+RD.esc(j.example_free)+'</pre>'}}
  (window.TAB_RENDER=window.TAB_RENDER||{})['t-sgm1']=[render];
  addEventListener('resize',()=>{if(!root.hidden){clearTimeout(root._t);root._t=setTimeout(render,80)}});
})();
