"""Write parts/20_js_mb_data.js: the trained tic-tac-toe network checkpoints and training log, the pendulum model
ensemble, and the few results the page quotes from offline runs (games against a perfect player, value accuracy),
all read from inputs/ and expected.json. Run after train_ttt.py, fit_pendulum.py and recompute.py."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
ttt = json.load(open(os.path.join(HERE, "inputs", "ttt_net.json")))
pend = json.load(open(os.path.join(HERE, "inputs", "pendulum_models.json")))
exp = json.load(open(os.path.join(HERE, "expected.json")))
r4 = lambda x: None if x is None else round(float(x), 4)
data = {
    "ttt": {"H": ttt["H"], "c_puct": ttt["c_puct"], "sims": ttt["sims_selfplay"], "games_per_iter": ttt["games_per_iter"],
            "steps_per_iter": ttt["train_steps_per_iter"], "n_states": ttt["n_states"], "seconds": ttt["seconds"],
            "log": [[row["it"], row["games"], r4(row["loss_v"]), r4(row["loss_p"]), r4(row["prior_opt"]), r4(row["v_mae"]), row["x"], row["o"], row["d"]] for row in ttt["log"]],
            "ckpts": {k: v["w"] for k, v in ttt["ckpts"].items()},
            "search_opt": {k: r4(v["metrics_quantised"]["search_opt"]) for k, v in ttt["ckpts"].items()},
            "offline": {k: {"v_class": r4(exp["ttt"][k]["v_class"]), "games": exp["games"][k]} for k in ttt["ckpts"]}},
    "pend": {"out_scale": pend["out_scale"], "n_data": pend["n_data"], "members": pend["members"], "m0_step50": {k: r4(v) for k, v in exp["pend"]["m0_step50"].items()}},
}
js = "// ---- Data: generated by src/mk_data.py from src/inputs/ttt_net.json, src/inputs/pendulum_models.json and src/expected.json; do not edit ----\nwindow.MB_DATA=" + json.dumps(data, separators=(",", ":")) + ";\n"
open(os.path.join(HERE, "parts", "20_js_mb_data.js"), "w").write(js)
print("wrote", len(js), "bytes")
