"""Collect everything the page embeds into parts/23_js_sg_data.js (window.SGD):
iso    isolated cache comparison summary (iso/out/iso.json, from gen_iso.py)
sched  scheduling-round results over 10 arrival orders (iso/out/iso.json)
real   the real-class check summary (iso/out/check_real.json)
m1     the SGLang-on-M1 measurements (m1/results/*.json, summarised by m1/summarise.py into m1/out/m1.json)
ix     SemiAnalysis InferenceX rows for DeepSeek-V4-Pro, vLLM and SGLang (inputs/inferencex_dsv4pro_vllm_sglang.json)
"""
import json, os
H = os.path.dirname(os.path.abspath(__file__))
iso = json.load(open(os.path.join(H, 'iso', 'out', 'iso.json')))
cache = [{'trace': r['trace'], 'cap': r['cap'], 'prompt': r['prompt_tokens'], 'n': r['requests'],
          'rh': r['radix']['hit'], 'bh': r['blocks']['hit'], 're': r['radix']['evicted'], 'be': r['blocks']['evicted'],
          'nodes': r['radix']['nodes'] - 1, 'blocks': r['blocks']['cached_blocks']} for r in iso['cache']]
sched = {}
for s in iso['sched']:
    k = f"{s['nq']}_{s['cap']}_{s['policy']}"
    sched.setdefault(k, []).append([s['seed'], s['hit'], s['rounds'], s['prompt']])
real = None
p = os.path.join(H, 'iso', 'out', 'check_real.json')
if os.path.exists(p):
    real = json.load(open(p))
p = os.path.join(H, 'iso', 'out', 'check_sched.json')
check_sched = json.load(open(p)) if os.path.exists(p) else None
m1 = None
p = os.path.join(H, 'm1', 'out', 'm1.json')
if os.path.exists(p):
    m1 = json.load(open(p))
ix = json.load(open(os.path.join(H, 'inputs', 'inferencex_dsv4pro_vllm_sglang.json')))
ixrows = [[r['hw'], r['fw'], r['prec'], r['isl'], r['osl'], r['conc'], r['tp'], r['ep'], int(bool(r['dpa'])), r['tput_gpu'], r['intvty'], r['ttft_med'], r['date'], r['image']] for r in ix['rows']]
data = {'curve': iso.get('curve'), 'cache': cache, 'sched': sched, 'real': real, 'check_sched': check_sched, 'm1': m1,
        'ix': {'source': ix['source'], 'fetched': ix['fetched'], 'filter': ix['filter'],
               'cols': ['hw', 'fw', 'prec', 'isl', 'osl', 'conc', 'tp', 'ep', 'dpa', 'tput_gpu', 'intvty', 'ttft_med', 'date', 'image'], 'rows': ixrows}}
js = '// generated by src/gen_data.py; do not edit\nwindow.SGD=' + json.dumps(data, separators=(',', ':')) + ';\n'
open(os.path.join(H, 'parts', '23_js_sg_data.js'), 'w').write(js)
print('wrote', len(js), 'bytes')
