// ---- SQL playground: the words of each lesson (goal, why, hint, what the result means, notes per menu choice) ----
// Numbers quoted here are asserted against the recorded runs by src/sql/recompute.py --check.
window.SQ_TEXT={
select:{
goal:`List the users on one plan.`,
why:`A table can hold millions of rows and you almost never want all of them. <code>SELECT</code> names the columns you want, <code>FROM</code> names the table, and <code>WHERE</code> keeps only the rows for which a condition is true. On a big table a <code>WHERE</code> on a column with no index makes the database read every row; the {{Query plans|#t-plan}} tab shows that cost.`,
hint:`Text values go in single quotes: <code>plan = 'pro'</code>. In standard SQL and in Postgres, double quotes mean a column name, not text. <code>ORDER BY id</code> fixes the order of the output; the next lesson explains why that matters.`,
explain:`<p>Each output row is one user whose plan matched; the database tested the condition on every row and dropped the rest. Postgres reports the count in its status line (<code>SELECT 27</code> for the free plan). 27 + 18 + 5 = 50: every user is on exactly one plan, because the schema's <code>CHECK</code> allows only those three values.</p><p><b>Try:</b> change the condition to <code>country = 'BR'</code>, or combine two with <code>AND</code> or <code>OR</code>, or replace the column list with <code>*</code> (all columns).</p>`},
order:{
goal:`Find the longest and the shortest assistant replies.`,
why:`Without <code>ORDER BY</code> a database may return rows in any order, and the order can change when the data or the query plan changes. <code>ORDER BY</code> makes the order part of the question; <code>LIMIT n</code> keeps the first n rows. That is how every "top 10" list and every page of results is built.`,
hint:`Two messages can have the same token count. The second sort key, <code>id</code>, breaks the tie, so both engines must return the same rows in the same order.`,
explain:`<p>Largest first, message 1216 with 899 tokens leads. Smallest first, messages 720 and 724 both have 45 tokens: without <code>, id</code> the engine may return them in either order, and a <code>LIMIT</code> that cuts between tied rows can return different rows on different days. Always end an <code>ORDER BY</code> with something unique when you page through results.</p><p>Paging with <code>LIMIT ... OFFSET ...</code> gets slower the deeper you go, because the skipped rows are still read; the SWE topic's {{Building a backend API|n:3c65c17b0d0d8190ade6c34e8f653e79}} page measures the alternative (cursor pagination) on a 1M-row Postgres table.</p>`},
join:{
goal:`Put each user next to their chats.`,
why:`In a relational database each fact is stored once, in the table it belongs to: the user's name in <code>users</code>, the chat's title in <code>chats</code>, linked by <code>chats.user_id</code>. <code>JOIN</code> puts them back together when you ask. Storing the name once is what makes renaming a user one <code>UPDATE</code> instead of one per chat; the cost is a join at read time.`,
hint:`<code>INNER JOIN</code> keeps only the pairs that satisfy <code>ON</code>. <code>LEFT JOIN</code> keeps every row of the left table (<code>users</code>) and fills the right side with NULL (no value) when nothing matches. <code>u</code> and <code>c</code> are short aliases for the two tables.`,
explain:`<p>Users 2, 4, 5 and 9. User 2 (Xavi Sato) owns three chats, so he appears three times; user 4 (Mo Garcia) owns none. INNER JOIN gives 5 rows and Mo disappears; LEFT JOIN gives 6 rows and keeps Mo with NULL in the chat columns. The animation above runs the same rows.</p><p>The third choice keeps only the unmatched rows (<code>WHERE c.id IS NULL</code> after a LEFT JOIN): the standard way to ask "which users never started a chat?".</p>`},
group:{
goal:`Count messages and tokens per model, or per plan.`,
why:`Dashboards are aggregates: a count, sum or average per group. <code>GROUP BY</code> splits the rows into groups that share a value; an aggregate function (<code>COUNT</code>, <code>SUM</code>, <code>AVG</code>, <code>MIN</code>, <code>MAX</code>) turns each group into one number. Done in the database, three rows travel to your program instead of 2,000.`,
hint:`A message knows its chat and a chat knows its user, so reaching a user's plan from a message takes two joins. Every column in <code>SELECT</code> must either be grouped or sit inside an aggregate; the next lesson shows what happens when it is not.`,
explain:`<p>Grouped by model, the 951 assistant replies split into 432 on <code>mini</code>, 317 on <code>standard</code> and 202 on <code>reasoning</code>. <code>COUNT(*)</code> counts rows; <code>SUM</code> and <code>AVG</code> work on the <code>tokens</code> column.</p><p>The average of whole numbers is a fraction: Postgres computes it as an exact decimal, SQLite as a floating-point number. <code>ROUND(..., 1)</code> makes both print the same.</p>`},
groupbare:{
goal:`See what happens when SELECT names a column that is neither grouped nor aggregated.`,
why:`A common bug. "The user's name per model" has no single answer, because each model was used by many users.`,
hint:`Read the two results side by side. Which one would you rather get in production?`,
explain:`<p>Postgres refuses with an error, because the question is ambiguous (<a href="https://www.postgresql.org/docs/16/sql-select.html#SQL-GROUPBY" target="_blank" rel="noopener noreferrer">Postgres 16 docs, GROUP BY</a>). SQLite runs it and fills <code>name</code> from one row of each group; its documentation calls these "bare columns" and says "you usually do not know which input row is used" (<a href="https://www.sqlite.org/lang_select.html#bareagg" target="_blank" rel="noopener noreferrer">SQLite docs</a>). The answer looks plausible and means nothing.</p><p><b>Lesson:</b> a query written against SQLite can fail on Postgres, and the strict engine is the one protecting you. To get a name per model, decide which one you mean (the most active user, say) and write that query.</p>`},
cte:{
goal:`Find the heavy users: those whose total tokens are above the average user's.`,
why:`Some questions need the answer to a smaller question first (what is the average per user?). A <b>subquery</b> is a query in parentheses used as a value or a table. A <b>CTE</b> (common table expression, <code>WITH name AS (...)</code>) gives the inner query a name, so the whole thing reads top to bottom.`,
hint:`<code>per_user</code> is used twice: once as a table to join, once inside the subquery that computes the average.`,
explain:`<p><code>per_user</code> has one row for each of the 44 users with at least one message; the average is about 11,326 tokens. 22 users are above it, 14 above 1.25 times it and 6 above 1.5 times it.</p><p>Cost: a CTE is not free storage. Postgres may compute it once and reuse it, as here, or fold it into the main query when it is referenced only once (<a href="https://www.postgresql.org/docs/16/queries-with.html" target="_blank" rel="noopener noreferrer">Postgres 16 docs, WITH queries</a>); the result is the same either way.</p>`},
window:{
goal:`Show the latest message of each chat, as the chat list of every chat app does.`,
why:`<code>GROUP BY</code> collapses rows, so it can tell you when the latest message arrived but not which message it was. A <b>window function</b> computes a value for each row from a "window" of related rows without collapsing them. <code>ROW_NUMBER() OVER (PARTITION BY chat_id ORDER BY created_at DESC)</code> numbers each chat's messages 1, 2, 3 from the newest; keep number 1.`,
hint:`<code>PARTITION BY</code> restarts the numbering for each chat. <code>id DESC</code> breaks ties if two messages share a timestamp. The outer query filters on <code>rn</code> because a <code>WHERE</code> cannot see a window function's result in the same query level.`,
explain:`<p>Chat 1's latest message is 1311, an assistant reply. Choosing "latest two" returns the last exchange of each chat. SQLite gained window functions in 3.25.0 (<a href="https://www.sqlite.org/windowfunctions.html" target="_blank" rel="noopener noreferrer">SQLite docs</a>).</p><p>Chats with no messages (8 of them) produce no rows at all here; to list them too, start from <code>chats</code> and <code>LEFT JOIN</code> the latest messages onto it.</p>`},
write:{
goal:`Create a row, change it, delete it, and check after each step.`,
why:`<code>INSERT</code> adds rows; <code>UPDATE</code> changes columns in the rows a <code>WHERE</code> selects; <code>DELETE</code> removes the rows a <code>WHERE</code> selects. <code>RETURNING</code> hands back what was written (here the id the database chose), which saves a second query.`,
hint:`The <code>INSERT</code> leaves out <code>id</code>, so the database picks it.`,
explain:`<p>Both engines picked id 201, one more than the largest. Postgres answers each write with a status line: <code>INSERT 0 1</code> (the 0 is a leftover field that is always 0 now, the 1 is the rows inserted, per the <a href="https://www.postgresql.org/docs/16/sql-insert.html" target="_blank" rel="noopener noreferrer">INSERT docs</a>), <code>UPDATE 1</code>, <code>DELETE 1</code>. Read that count every time: it is the first sign that a statement touched more rows than you meant (see the last lesson). SQLite supports <code>RETURNING</code> since 3.35.0 (<a href="https://www.sqlite.org/lang_returning.html" target="_blank" rel="noopener noreferrer">SQLite docs</a>).</p>`},
constraints:{
goal:`Try to insert bad rows and watch the database refuse them.`,
why:`Application code has bugs, and several programs often write to one database. A <b>constraint</b> is a rule declared in the schema that every write must pass: <code>NOT NULL</code> (a value is required), <code>UNIQUE</code> (no two rows share it), <code>CHECK</code> (a condition must hold), <code>FOREIGN KEY</code> (the row pointed at must exist), and the column's type. The cost is a check on every write (a <code>UNIQUE</code> or foreign key check is an index lookup), small next to cleaning bad data out later.`,
hint:`The <code>SELECT</code> after each <code>INSERT</code> shows whether the row got in.`,
explain:`<p>Postgres rejected all six bad rows. SQLite rejected the first three and accepted two of the others, with its default settings.</p>`,
notes:{
'0':`Both refuse: <code>name</code> is <code>NOT NULL</code>. The count stays at 50.`,
'1':`Both refuse: <code>femi.okafor@example.com</code> already belongs to user 1 and <code>email</code> is <code>UNIQUE</code>. This is also how "sign up twice with one email" is stopped even when two requests arrive at the same moment.`,
'2':`Both refuse: the <code>CHECK</code> allows only free, pro and team.`,
'3':`<b>The engines differ.</b> Postgres refuses: user 999 does not exist. SQLite accepts the orphan chat, because "foreign key constraints are disabled by default (for backwards compatibility), so must be enabled separately for each database connection" (<a href="https://www.sqlite.org/foreignkeys.html" target="_blank" rel="noopener noreferrer">SQLite docs</a>). Every program that opens a SQLite file must switch them on.`,
'4':`With <code>PRAGMA foreign_keys = ON</code> (a SQLite-only command) SQLite refuses too. Postgres does not know <code>PRAGMA</code>, so that line is a syntax error there; its foreign keys are always on.`,
'5':`<b>The engines differ.</b> Postgres refuses the text <code>'lots'</code> for an integer column. SQLite stores it: "the datatype of a value is associated with the value itself, not with its container", and text that does not look like a number is kept as text (<a href="https://www.sqlite.org/datatype3.html" target="_blank" rel="noopener noreferrer">SQLite docs</a>). Even <code>CHECK (tokens &gt;= 0)</code> passes, because SQLite ranks any text above any number. SQLite's <code>STRICT</code> tables (since 3.37.0) enforce types the way Postgres does.`}},
txn:{
goal:`Move credits from user 7 to user 12 so that either both balances change or neither does.`,
why:`A transfer is two writes. If the program crashes, or the second write is refused, between them, credits are created or destroyed. A <b>transaction</b> groups statements: <code>BEGIN</code> starts it, <code>COMMIT</code> makes all its changes permanent together, <code>ROLLBACK</code> throws them all away. This all-or-nothing property is the A (atomicity) of ACID; the {{Reading|#t-read}} tab's transactions section covers the other three letters.`,
hint:`User 7 has 30 credits, user 12 has 20, and <code>balance</code> carries <code>CHECK (balance &gt;= 0)</code>. Try 50 credits under each wrapping.`,
explain:`<p>The receiver is credited first and the sender debited second, the order a careless program might use.</p>`,
notes:{
'0-0':`20 credits, no transaction: both updates succeed, 7 has 10 and 12 has 40. It worked, this time.`,
'0-1':`The same transfer inside <code>BEGIN ... COMMIT</code>: same result, but now a crash between the two updates could not leave half of it behind.`,
'0-2':`Inside the transaction both updates succeeded, then <code>ROLLBACK</code> threw them away: 30 and 20, as before.`,
'1-0':`<b>Credits from nowhere.</b> User 12 was credited 50, then the debit was refused (user 7 would go to -20). With no transaction the first update stays: 12 now has 70 and 7 still has 30. Both engines agree.`,
'1-1':`<b>The engines differ, and it matters.</b> Postgres marks the whole transaction as failed after the error; the later <code>COMMIT</code> was answered with <code>ROLLBACK</code> (see its status line) and nothing changed. SQLite undoes only the failed statement and keeps the transaction open: "changes caused by prior SQL statements within the same transaction are preserved" (<a href="https://www.sqlite.org/lang_conflict.html" target="_blank" rel="noopener noreferrer">SQLite docs</a>), so <code>COMMIT</code> kept the +50. <b>Rule:</b> when a statement in a transaction fails, your code must <code>ROLLBACK</code>. Drivers' transaction helpers do this when an exception escapes (Python's <code>with conn:</code> for sqlite3, psycopg's <code>conn.transaction()</code>).`,
'1-2':`The failure is followed by <code>ROLLBACK</code>: the credit to user 12 is undone too, and both engines end at 30 and 20.`}},
nulls:{
goal:`Meet the ways NULL surprises people.`,
why:`NULL means "unknown or missing": 5 users have no country. It is not a value like 0 or an empty string. A comparison with NULL gives "unknown", and <code>WHERE</code> keeps only rows where the condition is true, so rows disappear without any error.`,
hint:`To test for a missing value write <code>IS NULL</code> or <code>IS NOT NULL</code>, never <code>= NULL</code>.`,
explain:``,
notes:{
'0':`<code>COUNT(*)</code> counts rows (50); <code>COUNT(country)</code> counts rows where <code>country</code> is not NULL (45). An average or a count over a column with NULLs silently uses fewer rows.`,
'1':`<code>= NULL</code> is never true, not even for a NULL: 0 rows. <code>IS NULL</code> finds the 5. Postgres's docs: "Do not write expression = NULL because NULL is not 'equal to' NULL" (<a href="https://www.postgresql.org/docs/16/functions-comparison.html" target="_blank" rel="noopener noreferrer">Postgres 16 docs</a>).`,
'2':`0 rows, although most users live outside the US and GB. <code>x NOT IN (a, b, NULL)</code> means <code>x &lt;&gt; a AND x &lt;&gt; b AND x &lt;&gt; NULL</code>, and the last part is unknown, so the whole test is never true (<a href="https://www.postgresql.org/docs/16/functions-comparisons.html" target="_blank" rel="noopener noreferrer">Postgres 16 docs, NOT IN</a>). In real code the NULL hides inside a subquery: <code>NOT IN (SELECT ...)</code>. Prefer <code>NOT EXISTS</code>.`,
'3':`<b>The engines differ.</b> SQLite sorts NULLs first in ascending order, as "smaller than any other values" (<a href="https://www.sqlite.org/lang_select.html#orderby" target="_blank" rel="noopener noreferrer">SQLite docs</a>); Postgres sorts them "as if larger than any non-null value", so last (<a href="https://www.postgresql.org/docs/16/queries-order.html" target="_blank" rel="noopener noreferrer">Postgres 16 docs</a>). The same query returns different first pages.`,
'4':`Saying <code>NULLS LAST</code> makes both engines agree (SQLite supports it since 3.30.0). When NULLs can appear in a sort column, say where they go.`,
'5':`Chat 10 has no title, so <code>title || ' (' || model || ')'</code> is NULL: joining text with NULL gives NULL. <code>COALESCE(a, b)</code> returns the first value that is not NULL.`}},
danger:{
goal:`See what one missing line does.`,
why:`<code>UPDATE</code> and <code>DELETE</code> without <code>WHERE</code> apply to every row in the table, and once committed there is no undo button. It is one of the classic production incidents.`,
hint:`Outside <code>BEGIN</code>, each statement is its own transaction and commits the moment it succeeds (this is called autocommit).`,
explain:`<p><b>Habits that prevent it:</b> write the <code>WHERE</code> first; run the same <code>WHERE</code> as a <code>SELECT COUNT(*)</code> before changing anything; make changes inside <code>BEGIN</code> and read the row count before <code>COMMIT</code>. MySQL's client even has a <a href="https://dev.mysql.com/doc/refman/8.4/en/mysql-tips.html#safe-updates" target="_blank" rel="noopener noreferrer">safe-updates mode</a> that refuses such statements. Backups with point-in-time recovery are the last line of defence.</p>`,
notes:{
'0-0':`One row changed (<code>UPDATE 1</code>): user 3 moved to team, so free goes from 27 to 26 and team from 5 to 6.`,
'0-1':`The same change, rolled back at the end: back to 27, 18 and 5.`,
'1-0':`<code>UPDATE 50</code>: every user is now on the team plan, and it is committed. The status line was the only warning.`,
'1-1':`Inside <code>BEGIN</code> the damage is visible (50 team users) but not yet permanent; <code>ROLLBACK</code> restores 27, 18 and 5.`,
'2-0':`<b>The engines differ.</b> Postgres refuses to delete chats that messages still point to (the foreign key on <code>messages.chat_id</code>). SQLite, with foreign keys off by default, deletes all 200 chats and leaves 2,000 messages pointing at chats that no longer exist.`,
'2-1':`Postgres: the refused <code>DELETE</code> puts the transaction in a failed state, and every later statement is ignored until <code>ROLLBACK</code>. SQLite deletes the 200 chats and the <code>ROLLBACK</code> brings them back.`}}
};
