// ---- Query plans tab: the case viewer (cases, variants, stats, tree, node detail, reading list, raw text, animation) ----
(function(){
  const Q=window.QP,D=Q.D,T=window.QP_TEXT,{esc,f,fms,kb,mb,gb}=Q;
  const $=id=>document.getElementById(id);
  const st={c:1,v:null,node:0};
  // case 6: DuckDB as a third variant built from its profile
  const c6=D.cases.find(c=>c.id===6),dx=c6.x.duck;
  const duckBytes=dx.parquet_columns.filter(c=>c.column==='model'||c.column==='tokens').reduce((s,c)=>s+c.compressed,0);
  (function mark(x){x.duck=1;(x.k||[]).forEach(mark)})(c6.x.duck_tree);
  c6.v.push({key:'duck',role:'after',g:'',label:'DuckDB, 10 threads, native table',sql:'SELECT model, count(*), sum(tokens), round(avg(tokens), 1) FROM messages GROUP BY model ORDER BY model',pre:'',
    ms:dx.native_threads10.median_ms,times:dx.native_threads10.times_ms,duck:1,tree:c6.x.duck_tree});
  D.cases.forEach(c=>c.v.forEach(v=>Q.prep(v.tree)));
  const byKey=(c,k)=>c.v.find(v=>v.key===k);
  const all=v=>{const a=[];(function w(x){a.push(x);(x.k||[]).forEach(w)})(v.tree);return a};
  const vPages=v=>v.duck?duckBytes/8192:Q.pages(v.tree);
  function helpers(c){
    const V=k=>byKey(c,k);
    return {x:c.x||{},f,kb,mb,gb,duckBytes:()=>duckBytes,
      ms:k=>fms(V(k).ms),pages:k=>Q.pages(V(k).tree),tree:k=>V(k).tree,planms:k=>fms(V(k).plan_ms),io:k=>fms(V(k).tree.io),
      ratio:(a,b)=>{const r=V(a).ms/V(b).ms;return r>=10?f(r):r.toFixed(1)},
      size:n=>D.sizes[n].pages,pct:x=>(x*100).toFixed(1)+'%',
      rows:k=>{const n=all(V(k)).find(x=>x.rel);return f(Q.totalRows(n))},
      est:(k,rel)=>{const n=all(V(k)).find(x=>x.rel===rel);return Math.round(Q.estTotal(n))},
      heap:k=>{const n=all(V(k)).find(x=>Q.info(x,'Heap Fetches')!=null);return n?Q.info(n,'Heap Fetches')*(n.lp||1):0}};
  }
  // ---- environment card ----
  (function(){const e=D.env,s=e.settings,z=D.sizes;
    $('qp-env').innerHTML='<details class="qp-more"><summary>Machine, versions, settings and data (measured '+e.date+')</summary><div class="small" style="padding-bottom:8px">'+
    '<p><b>Machine:</b> '+esc(e.machine)+'. <b>PostgreSQL</b> '+esc(s.server_version)+' from the <a href="https://pypi.org/project/pgserver/" target="_blank" rel="noopener noreferrer">pgserver</a> Python wheel, default settings except <code>track_io_timing = on</code>: shared_buffers '+s.shared_buffers+', work_mem '+s.work_mem+', random_page_cost '+s.random_page_cost+', max_parallel_workers_per_gather '+s.max_parallel_workers_per_gather+', JIT compilation not available in this build. <b>DuckDB</b> '+esc(dx.duckdb)+'.</p>'+
    '<p><b>Data:</b> the chat product\'s three tables, generated by a deterministic script: '+f(z.users.rows)+' users ('+kb(z.users.bytes)+'), '+f(z.chats.rows)+' chats ('+mb(z.chats.bytes)+'), '+f(z.messages.rows)+' messages ('+gb(z.messages.bytes)+', '+f(z.messages.pages)+' pages; each message has a role, a model, a token count, 30 to 130 characters of text and a timestamp every 3 seconds from September 2025). Indexes: every primary key, <code>chats(user_id)</code>, <code>messages(chat_id, created_at)</code> ('+mb(z.messages_chat_created.bytes)+'), and the ones the cases add.</p>'+
    '<p><b>Method:</b> every plan is <code>EXPLAIN (ANALYZE, BUFFERS)</code>, run 5 times, keeping the run with the median time (case 8\'s cold runs: once). Timing every node adds overhead, so the times are a little higher than the bare query. <b>These are laptop timings: read them for ratios between plans, not as server numbers.</b> A production server has more memory, different disks and other queries competing. Page counts do not depend on the machine.</p>'+
    '<p>Scripts and raw JSON outputs: <code>src/plan/</code> in the knowledge base repository (gen.py, measure.py, duck.py, inputs/).</p></div></details>'})();
  // ---- case chips ----
  $('qp-cases').innerHTML=D.cases.map(c=>'<button role="tab" data-c="'+c.id+'"><b>'+T[c.id].nm+'</b><span>'+T[c.id].sub+'</span></button>').join('');
  $('qp-cases').addEventListener('click',e=>{const b=e.target.closest('button');if(b)showCase(+b.dataset.c,true)});
  const anim=window.QPA.create({card:'qp-anim',lanes:'qp-lanes',cap:'qp-cap',ctl:'qp-actl',unit:'qp-unit'});
  const BADGE={2:{alt:'works'},4:{before:'forced',after:'planner',alt:'tuned'},6:{before:'row store',after:'column store'},8:{before:'cold',alt:'OS cache',after:'warm'}};
  function cur(){return D.cases.find(c=>c.id===st.c)}
  function showCase(id,user){st.c=id;const c=cur(),t=T[id],h=helpers(c);
    [...$('qp-cases').children].forEach(b=>{const on=+b.dataset.c===id;b.classList.toggle('on',on);b.setAttribute('aria-selected',on)});
    $('qp-title').textContent=t.title;$('qp-q').innerHTML=t.q(h);$('qp-lesson').innerHTML=t.lesson(h);
    const groups=[...new Set(c.v.map(v=>v.g))];
    $('qp-vars').innerHTML=groups.map(g=>(g?'<div class="qp-grp">'+esc(g)+'</div>':'')+'<div class="qp-vars">'+c.v.filter(v=>v.g===g).map(v=>
      '<button data-k="'+v.key+'"><span class="qp-role '+v.role+'">'+((BADGE[id]||{})[v.role]||{before:'before',after:'after',alt:'also'}[v.role])+'</span>'+esc(v.label)+'<small>'+fms(v.ms)+' ms · '+f(vPages(v))+(v.duck?' 8 KB units':' pages')+'</small></button>').join('')+'</div>').join('');
    // case 4: the planner's choice is the "after", the forced plan the comparison
    showVar((id===4?c.v[0]:c.v.find(v=>v.role==='before')||c.v[0]).key);
    extra(c);
    try{if(user)localStorage.setItem('qp-case',id)}catch(e){}
  }
  $('qp-vars').addEventListener('click',e=>{const b=e.target.closest('button');if(b)showVar(b.dataset.k)});
  function showVar(k){const c=cur(),v=byKey(c,k),h=helpers(c);st.v=k;
    [...$('qp-vars').querySelectorAll('button')].forEach(b=>b.classList.toggle('on',b.dataset.k===k));
    $('qp-sql').innerHTML=(v.pre?'<span class="pre">'+esc(v.pre)+'</span>\n':'')+esc(v.sql)+(v.duck?'\n<span class="pre">-- the same query, in DuckDB</span>':'');
    const note=T[c.id].v[k]||(()=>'');
    // stats
    const r=v.tree,grp=c.v.filter(x=>x.g===v.g),bef=grp.find(x=>x.role==='before');
    let s='';
    if(v.duck){s=RDstat('Time',fms(v.ms)+' ms','median of 5 runs, wall clock')+RDstat('Bytes for the two columns',mb(duckBytes),'model and tokens, compressed (Parquet)')+RDstat('Rows scanned',f(10000000),'only 2 of 7 columns')+RDstat('One thread',fms(dx.native_threads1.median_ms)+' ms','Parquet file: '+fms(dx.parquet_threads10.median_ms)+' ms')}
    else{s=RDstat('Time',fms(v.ms)+' ms',(v.times.length>1?'median of '+v.times.length+' runs':'1 run')+'; planning '+fms(v.plan_ms)+' ms')+
      RDstat('Page visits',f(Q.pages(r)),kb(Q.pages(r)*8192)+' of 8 KB pages')+
      RDstat('Hit / read',f(r.hit)+' / '+f(r.rd),r.io?'waiting for reads: '+fms(r.io)+' ms':'no waiting for reads')+
      RDstat('Rows returned',f(Q.totalRows(r)),'')}
    if(bef&&bef!==v){const pr=vPages(bef)/Math.max(1e-9,vPages(v)),tr=(v.duck?c.x.wall.median_ms:bef.ms)/v.ms;
      s+=RDstat('Against "'+(bef.label.length>26?bef.label.slice(0,24)+'...':bef.label)+'"',(tr>=1?(tr>=10?f(tr):tr.toFixed(1))+'× faster':(1/tr).toFixed(1)+'× slower'),(Math.abs(pr-1)<0.05?'same number of':pr>=1?(pr>=10?f(pr):pr.toFixed(1))+'× fewer':(1/pr).toFixed(1)+'× more')+(v.duck?' bytes; time against PostgreSQL\'s wall clock, '+fms(c.x.wall.median_ms)+' ms':' page visits'))}
    $('qp-stats').innerHTML=s+'<div class="small" style="grid-column:1/-1">'+note(h)+'</div>';
    tree(v);lanes(c,v);
  }
  function RDstat(k,v,d){return '<div class="stat"><div class="k">'+k+'</div><div class="v">'+v+'</div><div class="d">'+(d||'')+'</div></div>'}
  // ---- tree ----
  function tree(v){const nodes=all(v),rootP=Math.max(1,v.duck?1:Q.pages(v.tree));
    // select the node doing the most own work by default
    let best=nodes[0];if(!v.duck)nodes.forEach(x=>{if(Q.ownPages(x)>Q.ownPages(best))best=x});else nodes.forEach(x=>{if(x.tt>best.tt)best=x});
    st.node=best.id;
    function li(x){const o=Q.off(x),T=Q.totalRows(x),E=x.duck?null:Q.estTotal(x);
      const badge=o&&o.r>=3&&!x.duck?'<span class="qp-off '+(o.r>=10?'bad':'mid')+'">est '+(o.under?'under':'over')+' '+(o.r>=10?f(o.r):o.r.toFixed(1))+'×</span>':'';
      const meta=x.duck?'rows '+f(x.ar)+' · CPU '+fms(x.tt)+' ms':
        'rows '+f(T)+' (est '+f(E)+')'+badge+' · '+fms(x.tt)+' ms'+(x.lp>1?' × '+f(x.lp)+' loops':'')+' · '+f(Q.ownPages(x))+' own pages';
      const w=x.duck?0:Math.max(Q.ownPages(x)?0.6:0,Q.ownPages(x)/rootP*100);
      return '<li><button class="qp-n" data-n="'+x.id+'"><span class="nt">'+esc(x.duck?x.t:Q.name(x))+'</span><span class="on">'+esc(x.duck?'':Q.on(x))+'</span><span class="m">'+meta+'</span>'+(x.duck?'':'<span class="pb" aria-hidden="true"><span style="width:'+w.toFixed(1)+'%"></span></span>')+'</button>'+
        ((x.k||[]).length?'<ul>'+x.k.map(li).join('')+'</ul>':'')+'</li>'}
    $('qp-tree').innerHTML='<ul>'+li(v.tree)+'</ul>';
    // bottom-up reading: children before parents
    const post=[];(function w(x){(x.k||[]).forEach(w);post.push(x)})(v.tree);
    $('qp-read').innerHTML=post.map(x=>'<li data-n="'+x.id+'"><b>'+esc(x.duck?x.t:Q.name(x)+Q.on(x))+'</b>: '+Q.sentence(x)+'</li>').join('');
    $('qp-raw').textContent=v.duck?'DuckDB '+dx.duckdb+' profile (EXPLAIN ANALYZE), operators with rows and CPU time summed over threads:\n\n'+duckText(v.tree):Q.text(v);
    detail(v);
  }
  function duckText(x,ind){ind=ind||0;return ' '.repeat(ind)+x.t+'  rows='+x.ar+'  cpu='+fms(x.tt)+' ms'+(x.ex&&x.ex.Projections?'  ['+x.ex.Projections.join(', ')+']':'')+'\n'+(x.k||[]).map(c=>duckText(c,ind+4)).join('')}
  $('qp-tree').addEventListener('click',e=>{const b=e.target.closest('.qp-n');if(!b)return;st.node=+b.dataset.n;detail(byKey(cur(),st.v))});
  $('qp-read').addEventListener('click',e=>{const l=e.target.closest('li');if(!l)return;st.node=+l.dataset.n;detail(byKey(cur(),st.v))});
  function detail(v){const x=all(v).find(n=>n.id===st.node)||v.tree;
    [...$('qp-tree').querySelectorAll('.qp-n')].forEach(b=>b.classList.toggle('sel',+b.dataset.n===x.id));
    [...$('qp-read').children].forEach(l=>l.classList.toggle('sel',+l.dataset.n===x.id));
    const m=Q.MEAN[x.t]||'';let kv='';
    if(x.duck){kv='<dt>Rows out</dt><dd>'+f(x.ar)+'</dd><dt>CPU time</dt><dd>'+fms(x.tt)+' ms, summed over threads</dd>'+
      Object.keys(x.ex||{}).map(k=>'<dt>'+esc(k)+'</dt><dd>'+esc([].concat(x.ex[k]).join(', '))+'</dd>').join('')}
    else{const o=Q.off(x),E=Q.estTotal(x),lp=x.lp||1;
      kv='<dt>Actual rows</dt><dd>'+f(Q.totalRows(x))+(lp>1?' ('+f(x.ar)+' per loop × '+f(lp)+' loops'+(x.pa||Q.inGather(x)?'; the loops are processes working in parallel':'')+')':'')+'</dd>'+
      '<dt>Estimated rows</dt><dd>'+f(E)+(x.er!==E?' ('+f(x.er)+' per '+((lp>1&&lp>Q.workers(x)+1)?'loop':'process')+')':'')+(o&&o.r>=3?' <b style="color:var(--bad)">off by '+(o.r>=10?f(o.r):o.r.toFixed(1))+'×, '+(o.under?'underestimated':'overestimated')+'</b>':o?' (close)':'')+'</dd>'+
      '<dt>Time</dt><dd>'+fms(x.tt)+' ms'+(lp>1?' per loop':'')+', including everything below it</dd>'+
      '<dt>Pages, this node and below</dt><dd>'+f(Q.pages(x))+' ('+f(x.hit)+' hit, '+f(x.rd)+' read'+(x.io?', '+fms(x.io)+' ms waiting':'')+')</dd>'+
      '<dt>Pages, this node alone</dt><dd>'+f(Q.ownPages(x))+'</dd>'+
      '<dt>Planner\'s cost</dt><dd>'+f(x.c)+' (an abstract unit: 1 = reading one page in sequence)</dd>'+
      (x.i||[]).filter(a=>Q.INFO[a[0]]).map(a=>'<dt>'+esc(a[0])+'</dt><dd><code>'+esc([].concat(a[1]).join(', '))+'</code> <span class="mute">'+Q.INFO[a[0]]+'</span></dd>').join('')}
    $('qp-node').innerHTML='<h4>'+esc(x.duck?x.t:Q.name(x)+Q.on(x))+'</h4><p style="margin:2px 0 6px">'+m+'</p><p style="margin:2px 0 6px"><b>Here:</b> '+Q.sentence(x)+'</p><dl class="kv">'+kv+'</dl>';
  }
  // ---- animation lanes and log-scale bars for the variants of the current group ----
  function lanes(c,v){const grp=c.v.filter(x=>x.g===v.g);
    anim.set(grp.map(x=>({label:x.label,short:x.label.split(':')[0],hit:x.duck?duckBytes/8192:x.tree.hit,rd:x.duck?0:x.tree.rd,ms:x.ms,col:!!x.duck})));
    const maxP=Math.max(...grp.map(vPages)),maxT=Math.max(...grp.map(x=>x.ms)),minT=Math.min(...grp.map(x=>x.ms));
    const pHi=Math.ceil(Math.log10(Math.max(10,maxP))),tLo=Math.floor(Math.log10(minT)),tHi=Math.ceil(Math.log10(maxT));
    const bar=(val,lo,hi)=>Math.max(1,(Math.log10(Math.max(val,Math.pow(10,lo)))-lo)/(hi-lo)*100);
    const narrow=($('qp-log').clientWidth||400)<560;
    const ticks=(lo,hi,lab)=>{let t='';const step=narrow&&hi-lo>4?2:1;for(let e=lo;e<=hi;e+=step){const p=(e-lo)/(hi-lo)*100;t+='<span style="position:absolute;left:'+p.toFixed(1)+'%;transform:translateX('+(e===lo?'0':e===hi?'-100%':'-50%')+')">'+lab(Math.pow(10,e))+'</span>'}return t};
    const rows=(fn,lo,hi,fmt,col)=>grp.map(x=>'<div class="row'+(x===v?' hl':'')+'"><span class="nm" title="'+esc(x.label)+'">'+esc(x.label)+'</span><span class="track"><span class="fill" style="width:'+bar(fn(x),lo,hi).toFixed(1)+'%;background:'+col+'"></span></span><span class="val">'+fmt(fn(x))+'</span></div>').join('');
    const axis=(lo,hi,lab)=>'<div class="row"><span class="nm"></span><span style="position:relative;height:14px;font-size:10.5px;color:var(--mute)">'+ticks(lo,hi,lab)+'</span><span></span></div>';
    const tl=x=>x>=1e6?(x/1e6)+'M':x>=1e3?(x/1e3)+'k':x>=1?f(x):String(+x.toPrecision(1));
    $('qp-log').innerHTML='<div class="small" style="font-weight:600;margin-top:6px">Page visits, log scale (each gridline is 10 times the last)</div><div class="bars">'+rows(vPages,0,pHi,x=>f(x),'var(--c2)')+axis(0,pHi,tl)+'</div>'+
      '<div class="small" style="font-weight:600;margin-top:6px">Time in ms, log scale</div><div class="bars">'+rows(x=>x.ms,tLo,tHi===tLo?tLo+1:tHi,fms,'var(--c1)')+axis(tLo,tHi===tLo?tLo+1:tHi,tl)+'</div>';
  }
  // ---- extras per case ----
  function extra(c){let h='';
    if(c.id===6){const cols=dx.parquet_columns;
      h='<details class="qp-more"><summary>Where the bytes are: PostgreSQL pages against DuckDB columns</summary><div class="tw"><table><thead><tr><th>Stored as</th><th class="num">Bytes</th><th>Read by this query?</th></tr></thead><tbody>'+
      '<tr><td>PostgreSQL table <code>messages</code>, all columns in each row</td><td class="num">'+gb(c.x.table_bytes)+'</td><td>all of it</td></tr>'+
      cols.map(k=>'<tr><td>Parquet column <code>'+esc(k.column)+'</code> (compressed)</td><td class="num">'+mb(k.compressed)+'</td><td>'+((k.column==='model'||k.column==='tokens')?'<b>yes</b>':'no')+'</td></tr>').join('')+
      '<tr><td>DuckDB native file, whole table</td><td class="num">'+mb(dx.db_file_bytes)+'</td><td>only the two columns\' blocks</td></tr></tbody></table></div>'+
      '<p class="small">Both systems return the same four rows (tokens per model): '+esc(c.x.pg_result.split('\n').map(r=>r.split('|')[0]+' '+f(+r.split('|')[2])).join(', '))+'. The <code>role</code> column, with only two distinct values, compresses to '+kb(cols.find(k=>k.column==='role').compressed)+' from '+mb(cols.find(k=>k.column==='role').uncompressed)+'; the message text (random hexadecimal characters, 4 bits of information in each 8-bit byte) only about '+(cols.find(k=>k.column==='content').uncompressed/cols.find(k=>k.column==='content').compressed).toFixed(1)+' times.</p></details>'}
    if(c.id===5){const dep=c.x.dependencies;let parsed={};try{parsed=JSON.parse(dep)}catch(e){}
      const nm={'3':'country','4':'city','7':'timezone'},lab=s=>s.split(/\s*=>\s*/).map(p=>p.split(/,\s*/).map(n=>nm[n]||n).join(' + ')).join(' decides ');
      h='<details class="qp-more"><summary>What CREATE STATISTICS learned</summary><p class="small">The <code>dependencies</code> statistic measures, for each pair, the share of rows where knowing the first column fixes the second (1 = always):</p><div class="tw"><table><tbody>'+
      Object.keys(parsed).map(k=>'<tr><td>'+esc(lab(k))+'</td><td class="num">'+(+parsed[k]).toFixed(2)+'</td></tr>').join('')+'</tbody></table></div><p class="small">City decides country and time zone (1.00). Time zone decides city only 0.29 of the time, because a time zone such as Asia/Kolkata covers three cities. The <code>mcv</code> statistic adds the most common combinations of the three values with their real frequencies, which is what fixes this estimate.</p></details>'}
    $('qp-extra').innerHTML=h;
  }
  // ---- claims checked ----
  $('qp-claims').innerHTML='<h3>Two claims about the planner, checked</h3>'+
  '<div class="co key"><div class="t">"Cardinality estimates are systematically wrong on correlated predicates": holds</div>PostgreSQL multiplies per-column selectivities, assuming independence, unless you create extended statistics; its documentation shows a 100× underestimate from two identical columns ({{PostgreSQL 16 documentation, multivariate statistics examples|https://www.postgresql.org/docs/16/multivariate-statistics-examples.html}}). Leis and others, who introduced the Join Order Benchmark (JOB: 113 queries on the IMDb data set), found that estimates are "the most important ingredient for finding a good query plan" and that systems "routinely" misestimate join sizes by a factor of 1000 or more ({{How Good Are Query Optimizers, Really?, PVLDB 9(3), 2015|https://www.vldb.org/pvldb/vol9/p204-leis.pdf}}). Case 5 reproduces it on this data: about 60× under on three correlated columns, fixed by <code>CREATE STATISTICS</code>.</div>'+
  '<div class="co"><div class="t">The learned planner result (QORL): the headline holds, with conditions the old page left out</div>Rohan Bansal\'s write-up, 16 September 2026 ({{rohanbansal.com/qorl|https://rohanbansal.com/qorl}}): a 4B model (Empero\'s Qwen 3.8 4B distillation) trained on about 13.6k Cardinality Estimation Benchmark queries writes <code>pg_hint_plan</code> hints (scan methods, join order, parallelism) rather than whole plans. On the 113 JOB queries:<ul class="tight">'+
  '<li><b>1.81× geometric mean speedup: confirmed</b>, but it is the best of up to 15 candidate plans per query (3 rollouts of up to 5 candidates each), picked using measured times. One rollout with the model\'s own choice gave 1.40× with 7 regressions.</li>'+
  '<li><b>44.7% latency reduction</b>: the post\'s headline; it equals 1 − 1/1.81, the total-workload speedup (also 1.81×).</li>'+
  '<li><b>Zero regressions</b>: true for that best-of-three selection only.</li>'+
  '<li><b>"Base model failed 72% of the time"</b>: the post\'s headline says the untrained model could not produce a plan for 99 of 113 queries (88%); 72% matches only the 81 of 113 trajectories that ended with "no valid candidate" in one table.</li>'+
  '<li><b>Measurement:</b> four Docker containers, <code>shared_buffers</code> raised from 128 MB to 2 GB because at 128 MB pages kept coming back from the Linux page cache and the noise ("no-op error rate") was about 4 times higher; each comparison runs three interleaved candidate and default pairs and compares medians.</li>'+
  '<li><b>Held out?</b> The model trained on CEB, but JOB was also the set every checkpoint was evaluated on during development, so 1.81× is not a clean held-out number.</li></ul>'+
  'What it means for you: the planner\'s weak spot is row estimates, exactly case 5, and a learned model can find better plans for analytic queries that run again and again, where trying several plans pays for itself. For an app\'s small transactional queries, which already run in a millisecond, it is unlikely to pay.</div>';
  // ---- start ----
  let start=1;try{const s=+localStorage.getItem('qp-case');if(s>=1&&s<=8)start=s}catch(e){}
  let first=true;
  (window.TAB_RENDER=window.TAB_RENDER||{});(window.TAB_RENDER['t-plan']=window.TAB_RENDER['t-plan']||[]).push(()=>{if(first){first=false;showCase(start,false)}else anim.redraw()});
})();
