"""Writes parts/23_js_meas_data.js from inputs/lab_measured.json (the measured runs) and
the model's 3-seed results for the same presets (engine.py), so the page can show both."""
import json, engine
d = json.load(open('inputs/lab_measured.json'))
P = {'none': {'att': 1}, 'naive': {'back': 'none'}, 'backoff': {'back': 'full'}, 'budget': {'back': 'full', 'budget': 1},
     'deadline': {'back': 'none', 'drop': 1}, 'shed': {'back': 'none', 'dmaxQ': 8}}
model = {}
for k, c in P.items():
    model[k] = {}
    for s in (1, 2, 3):
        r = engine.sim(dict(c, Ld=28, Ls=103, seed=s))['tot']
        model[k][str(s)] = {x: (round(r[x], 4) if isinstance(r[x], float) else r[x]) for x in ('success', 'attPerA', 'useful', 'recovery')}
out = {'meta': d['meta'], 'runs': d['runs'], 'model': model,
       'baseline': {'n': 2972, 'p50': 27.5, 'p90': 42.5, 'p99': 62.3, 'p999': 72.3, 'max': 77.6}}
open('parts/23_js_meas_data.js', 'w').write('// ---- Measured retry-storm runs (generated by src/gen_meas_js.py from inputs/lab_measured.json; do not edit) ----\nwindow.MEAS=' + json.dumps(out, separators=(',', ':')) + ';\n')
json.dump(model, open('model_vs_measured.json', 'w'), indent=0)
for k in P:
    m = [d['runs'][k][s] for s in ('1', '2', '3')]
    print(k, 'measured', round(sum(x['success'] for x in m) / 3, 3), [x['recovery_s'] for x in m], 'model', round(sum(model[k][s]['success'] for s in model[k]) / 3, 3), [model[k][s]['recovery'] for s in model[k]])
