"""Write parts/22_js_data.js (window.NQ) from the measured inputs/*.json. Run after any measurement: python3 build_data.py"""
import json, os
H = os.path.dirname(os.path.abspath(__file__)); I = os.path.join(H, 'inputs')
def load(n):
    p = os.path.join(I, n)
    return json.load(open(p)) if os.path.exists(p) else None

def ddb_size(item):
    """DynamoDB item size: UTF-8 bytes of each attribute name plus its value; a number is about 1 byte per 2 significant digits plus 1."""
    return sum(len(k.encode()) + (len(v.encode()) if isinstance(v, str) else (len(str(v)) + 1) // 2 + 1) for k, v in item.items())

NQ = {}
r = load('redis.json')
if r:
    NQ['redis'] = {k: r[k] for k in ('version', 'get_us', 'benchmark', 'leaderboard', 'persistence', 'crash', 'replication', 'streams')}
    NQ['redis']['ratelimit'] = r['ratelimit']
NQ['rank'] = load('rank.json')
w = load('wide.json')
if w:
    pg = w['pg']
    NQ['wide'] = {'pg': {k: pg[k] for k in ('rows', 'heap_pages', 'long_chat', 'long_chat_rows', 'long_chat_span_days', 'cluster_seconds')},
                  'runs': [{k: x[k] for k in ('label', 'buffers', 'heap_pages_holding_rows', 'ms_p50', 'blocks', 'explain', 'nodes')} for x in pg['runs']],
                  'chat_blocks': pg['runs'][1]['all_blocks_of_chat'],
                  'pg_version': w.get('pg_version'), 'cass_version': w.get('cass_version'), 'cass': w.get('cass'), 'cass_ddl': w.get('cass_ddl'),
                  'cass_defaults': w.get('cassandra_defaults'), 'cass_compaction': w.get('cass_compaction_default')}
d = load('ddb.json')
if d:
    aps = {a['label']: a for a in d['access_patterns']}
    a4 = aps['AP4 latest 50 messages']; sc = aps['Wrong: latest 50 by Scan + filter (no key)']; full = aps['Wrong: one model across all chats (full Scan)']
    chat = {'PK': 'USER#123', 'SK': 'CHAT#1234', 'type': 'chat', 'title': 'Chat 1234', 'created': '2025-09-01T00:00:00Z', 'GSI1PK': 'USER#123', 'GSI1SK': 'LAST#2025-09-30T12:00:00Z#1234'}
    usage = {'PK': 'USER#123', 'SK': 'USAGE#2025-09-10', 'tokens': 123456, 'type': 'usage'}
    rpm = max(0.5, -(-50 * d['message_item_bytes']['mean'] // 4096) * 0.5)
    NQ['ddb'] = {'load': d['load'], 'items_total': full['scanned'], 'long_chat_messages': w['pg']['long_chat_rows'] if w else 989,
                 'item_bytes': {'msg': d['message_item_bytes']['mean'], 'chat': ddb_size(chat), 'usage': ddb_size(usage), 'avg': d['message_item_bytes']['mean']},
                 'ap4': {'count': a4['count'], 'scanned': a4['scanned'], 'capacity': a4['capacity']},
                 'scan': {'count': sc['count'], 'scanned': sc['scanned'], 'capacity': sc['capacity']}, 'full_scan': full,
                 'access_patterns': d['access_patterns'], 'append_txn_wru': d['append_txn_capacity'][0]['CapacityUnits'], 'put_wru': d['put_message_capacity'],
                 'register': d['register'], 'errors': d['errors'], 'create_table': d['create_table'],
                 'prices': {'date': '2026-10-04', 'od_wru': 0.625e-6, 'od_rru': 0.125e-6, 'pr_wcu_h': 0.00065, 'pr_rcu_h': 0.00013, 'storage_gb_month': 0.25,
                            'wru_per_message': d['append_txn_capacity'][0]['CapacityUnits'], 'rru_per_read': rpm}}
NQ['doc'] = load('doc.json'); NQ['graph'] = load('graph.json'); NQ['ts'] = load('ts.json')
out = '// Generated by build_data.py from inputs/*.json (measured on 2026-10-04); do not edit.\nwindow.NQ=' + json.dumps(NQ, separators=(',', ':'), ensure_ascii=True) + ';\n'
open(os.path.join(H, 'parts', '22_js_data.js'), 'w').write(out)
print('22_js_data.js', len(out), 'bytes')
