"""Compact inputs/demo_data.json (the real run's extracts) into parts/21_js_data.js for the page."""
import json, os
S = os.path.dirname(os.path.abspath(__file__))
d = json.load(open(os.path.join(S, "inputs", "demo_data.json")))
hl = set(d["highlight"].values())
tr = []
for t in d["traces"]:
    idx = {s["id"]: i for i, s in enumerate(t["spans"])}
    full = t["id"] in hl
    sp = []
    for s in t["spans"]:
        row = [s["name"], s["svc"], idx.get(s["parent"], -1), s["start"], s["dur"], 1 if s["status"] == "ERROR" else 0]
        if full:
            row.append({"id": s["id"], "kind": s["kind"], "attrs": s["attrs"], "events": s["events"]})
        sp.append(row)
    tr.append({"id": t["id"], "t": t["t"], "dur": t["dur"], "err": t["err"], "sp": sp})
reqs = [x for r in d["reqs"] for x in r]  # flat: t, ms, status
out = {k: d[k] for k in ("run", "queries", "series", "inst", "raw_example", "buckets_incident", "exact",
                         "highlight", "sampling", "stream", "log_bytes", "metrics_text",
                         "metrics_om", "series_exposed_total")}
out["traces"] = tr
out["bench"] = json.load(open(os.path.join(S, "inputs", "bench.json")))
out["exemplars"] = json.load(open(os.path.join(S, "inputs", "exemplars.json")))
# flame graph tree from the collapsed stacks (frames under 0.5% of samples folded into their parent)
tree = {"n": "all", "v": 0, "c": {}}
for line in open(os.path.join(S, "inputs", "profile_collapsed.txt")):
    st, v = line.rsplit(" ", 1); v = int(v); node = tree; node["v"] += v
    for fr in st.split(";")[1:]:          # drop the <module> frame
        node = node["c"].setdefault(fr, {"n": fr, "v": 0, "c": {}}); node["v"] += v
tot = tree["v"]
def prune(nd):
    kids = [prune(k) for k in nd["c"].values() if k["v"] >= 0.005 * tot]
    kids.sort(key=lambda k: k[0])
    return [nd["n"], nd["v"], kids]
out["flame"] = prune(tree)
out["configs"] = {k: open(os.path.join(S, "demo", f)).read() for k, f in
                  [("rules", "rules/slo_rules.yml"), ("ruletest", "rules/slo_rules_test.yml"), ("otelcol", "otelcol.yaml")]}
out["reqs"] = reqs
out["xlogs"] = json.load(open(os.path.join(S, "inputs", "explorer_logs.json")))
out["replicas"] = json.load(open(os.path.join(S, "inputs", "replica_stats.json")))
js = "// Real data from the local demo run (src/demo/, 2026-10-04). Generated by src/make_data.py; do not edit.\nwindow.DEMO=" + \
     json.dumps(out, separators=(",", ":")).replace("</", "<\\/") + ";\n"
open(os.path.join(S, "parts", "21_js_data.js"), "w").write(js)
print("bytes", len(js))
