// ---- Part 3 (tl): recorded data, generated by src/tl/gen.py from src/tl/outputs/ ----
window.TL={stream:[[json:stream]],agent:[[json:agent]],cancel:[[json:cancel]],bp:[[json:bp]],mcp:[[json:mcp]]};
