// ---- Part 1 (JavaScript and its runtime): recorded data, generated by src/ja/gen.py from src/ja/outputs ----
window.JA={
  tl:[[json:i4_trace]],
  sse:[[json:j1_sse]],
  drills:[[json:drills]],
  loops:[[json:loops]],
  startup:[[json:startup]]
};
