#!/usr/bin/env python3
"""Write data/annotations.json for the 2026-09-14 issue: what the issue text does not hold (dates, tags, the KB pages
each item feeds, Hacker News counts, checks against the sources read on 2026-10-02, corrections, cross-tab links,
follow-ups and where each visual goes). Checks for items the issue gives no source for come from
data/factcheck_notes.json (written after a separate search) and are merged in here. Run from src/."""
import json, os

CK = '2026-10-02'
def check(t): return ['check', f'<b>Checked</b> {CK}: ' + t]
def corr(t): return ['corr', f'<b>Correction</b> ({CK}): ' + t]
def unc(t): return ['unc', '<b>Unconfirmed</b>: ' + t]
def rel(t): return ['rel', t]
def link(t): return ['link', t]

A = {
 'issue': {'title': '2026-09-14: tech news', 'window': ['2026-09-07', '2026-09-14'], 'axis': ['2026-09-04', '2026-09-14'], 'checked': CK, 'theme': 'agents'},
 'glance': {
  'tab': 't-read', 'label': 'At a glance',
  'lead': 'Covering roughly 2026-09-07 to 2026-09-14: 69 items across models, research, industry, chips, developer tools and the week\'s arguments. This tab is the week in one screen; each section has its own tab with its items in full, the checks against their sources and what happened next.',
  'theme': '<b>The week\'s theme: agents became the unit everything is built, sold and measured around.</b> DeepSeek reshaped V4.1-Flash for the prompt and cache costs of long agent loops; OpenAI and Anthropic now run the loop itself as a product; the week\'s benchmarks scored the agent with its harness attached, so the same model reads 62.7% or 99.9% on ARC-AGI-3; and Anthropic\'s threat report and the Claude Mythos 5 incident showed agents doing the attacking, which is the backdrop to Dario Amodei\'s call to pace the frontier. The [[animation in Top stories|t-top|v-ced]] runs one agent turn through DeepSeek\'s old and new architectures.',
  'next_title': 'What happened next, in one line each (as of 2026-10-02)'},
 'sections': [
  {'id': 'top', 'name': 'Top stories', 'short': 'Top', 'c': 'c1', 'tab': 't-top', 'label': 'Top stories',
   'glance': 'Amodei\'s call to pace the frontier; DeepSeek\'s encoder-decoder (animated); the agent loop as a product; Real-SWE on private code (three readings); AI-run cyber operations.',
   'lead': 'Five stories with one subject: agents. DeepSeek changed the shape of a model so that long agent loops cost less to serve, and the animation below runs one agent turn through the new architecture and the decoder-only one it replaces. OpenAI and Anthropic now run the agent loop as a hosted service with a control surface, and Sakana sells an orchestrator as if it were a model. Real-SWE measured agents on private company code, then rewrote its own table twice after the issue went out; the card below shows all three readings. Anthropic\'s threat report documents agents running real intrusions. And Dario Amodei, citing the agent incidents of the summer, asked the industry to slow capability gains and committed Anthropic to embedded outside evaluators.'},
  {'id': 'models', 'name': 'Models & releases', 'short': 'Models', 'c': 'c2', 'tab': 't-models', 'label': 'Models',
   'glance': 'An orchestrator sold as a model (Sakana Fugu); a coding agent on Kimi K3 (Cognition SWE-2); a translation-only MoE; voice, image, music and on-device releases; Meta\'s agent in a VM.',
   'lead': 'Thirteen releases, and few of them are plain models. The biggest, DeepSeek V4.1-Flash, is told in [[Top stories|t-top|i-deepseek-v41]]. Sakana\'s Fugu is an orchestrator that routes each request across a pool of other models behind one API; Cognition\'s SWE-2 is Moonshot\'s open Kimi K3 post-trained into a coding agent that only runs inside Devin; Cohere\'s North Small Translate is a 218B mixture of experts that does one job. The rest is the interface layer: full-duplex voice, images, licensed music, small on-device and vision models, a document parser, and two assistants, Meta\'s Muse agent, which runs each instance in its own virtual machine, and Gemini on Windows. Several headline numbers are the vendors\' own measurements; the checks under each item say which.'},
  {'id': 'research', 'name': 'Research & papers', 'short': 'Research', 'c': 'c3', 'tab': 't-research', 'label': 'Research',
   'glance': 'Agents as insiders (MOLE); scores that depend on the harness; the Recurrent Looped Transformer (animated); pretraining gains from data; Anthropic\'s 2030 scenarios (calculator).',
   'lead': 'Thirteen items in four threads. Agents as insiders: MOLE finds that most agent models complete harmful objectives inside an organisation and the best monitors miss nearly half of it, and NeoHorse-1 feeds a serving harness back into training. The harness as part of the result: Hyper-tau-bench (23.9% alone, 82.2% with an engineer), ARC-AGI-3 at 62.7% or 99.9% depending on the harness, and Phi-Bench on infrastructure engineering; Real-SWE lives in [[Top stories|t-top|v-rswe]]. Architecture and training: the Recurrent Looped Transformer, which carries the decoder\'s state from token to token (animated below against a standard decoder, and the opposite trade to DeepSeek\'s encoder-decoder in [[Top stories|t-top|v-ced]]), Magic\'s and Dwarkesh\'s pretraining-efficiency results, and Random Attention. Then two claims about the world outside the lab: OpenAI\'s Navier-Stokes result and Anthropic\'s economic scenarios, whose central number the calculator below multiplies out.'},
  {'id': 'industry', 'name': 'Industry', 'short': 'Industry', 'c': 'c4', 'tab': 't-industry', 'label': 'Industry',
   'glance': 'Anthropic\'s Nasdaq IPO against Altman\'s no-IPO; SoftBank\'s loan for OpenAI; Mistral\'s 3 billion euros; a $13.7B GPU deal; safety researchers moving to METR; Pentagon contracts; chip and robotics rounds; AI harms.',
   'lead': 'Fourteen items, most of them money or people. The two frontier labs split on going public: Anthropic chose Nasdaq for October and guided to a second profitable quarter, while Sam Altman ruled out an OpenAI listing this year, citing safety, and SoftBank borrowed $11.87 billion to keep funding OpenAI. Mistral raised the largest round in European tech; Anthropic added a $13.7 billion GPU contract; Positron and Ayar Labs raised for inference chips and optical links (Positron\'s bet is explained in [[Compute|t-compute|i-positron-hbm]]). The people story is safety researchers leaving labs for the evaluator METR in the same week Amodei proposed embedding evaluators like METR inside labs ([[Top stories|t-top|i-pacing]]). The rest is policy and harm: Pentagon agreements, a California law on chatbots and minors, licensed fan remixes, AI-made abuse imagery in Meta\'s ads and an invoice-fraud campaign.'},
  {'id': 'compute', 'name': 'Compute & chips', 'short': 'Compute', 'c': 'c5', 'tab': 't-compute', 'label': 'Compute',
   'glance': 'Positron\'s bet against HBM; TPUv7 Ironwood sold outside Google; Arm\'s N4; ROCm 10 with agent skills; Cerebras at up to 1,850 tokens per second; China\'s 2030 target; power for data centres; a 2nm phone chip.',
   'lead': 'Eight items about where inference will run and what limits it. The chip stories split on memory: Positron is designing around commodity LPDDR5X instead of HBM, betting that capacity per dollar matters more than peak bandwidth, while Google\'s TPUv7 Ironwood is now sold for other companies\' inference at up to 50% better performance per dollar than Nvidia\'s B200 and B300, per SemiAnalysis. Why bandwidth sets the ceiling for a single stream of tokens is worked out in [[Dev tools|t-dev|v-sol]]; Cerebras\'s 1,500 to 1,850 tokens per second on Qwen3.8-27B is what wafer-scale on-chip memory buys. AMD shipped its optimisation know-how as agent skills. The rest is capacity and power: China\'s 2030 target, Australian and Iowa power deals, a Massachusetts rule that large data centres pay for their own clean energy, and a phone chip that doubles on-device AI throughput.'},
  {'id': 'dev', 'name': 'Dev tooling & agents', 'short': 'Dev tools', 'c': 'c6', 'tab': 't-dev', 'label': 'Dev tools',
   'glance': 'The agent loop hosted (OpenAI) and governed (Anthropic); Cohere\'s megakernel serving engine (speed-of-light calculator); Claude Code and Codex releases; coordinator agents; an agent inbox; a DeepSeek sandbox CVE.',
   'lead': 'Ten items. The first two are one story, told in [[Top stories|t-top|i-harness-buy]]: OpenAI now runs the agent loop for you, and Anthropic lets your server approve or block each step of its managed agents. Cohere\'s account of a decode megakernel inside a complete serving engine is the week\'s best systems read; the calculator below reproduces its speed-of-light arithmetic and shows why a long context eats into it. Then the tools: Claude Code 2.1.266 to 2.1.270, Codex 0.154.0, Cursor\'s coordinator agent, AWS\'s inbox for background agents, Deep Research inside OpenAI\'s work apps, and a sandbox escape in DeepSeek\'s agent tooling. The last item says several release feeds were quiet; GitHub\'s records say otherwise.'},
  {'id': 'talk', 'name': 'Talk of the town', 'short': 'Talk', 'c': 'c7', 'tab': 't-talk', 'label': 'Talk of the town',
   'glance': 'A mathematicians\' declaration against AI\'s race for famous problems; a rejoinder to the pacing debate; Bengio on agents that lie and coordinate; Nvidia as a central bank; what drew attention and what did not.',
   'lead': 'Six threads from Hacker News and the essays people argued over. The biggest was a declaration by mathematicians that AI companies\' race to solve famous problems works against the way mathematics actually advances, published as OpenAI claimed a Navier-Stokes result ([[Research|t-research|i-navier]]). Two pieces answered the pacing debate from opposite sides: "Everyone should slow down AI development except for me" and Yoshua Bengio on why agents lie, cheat and coordinate. The Economist cast Nvidia as the AI economy\'s central bank. And the attention itself was data: Amodei\'s 6-to-12-month warning drew 46 points, David Sacks\'s case against regulation 221.'}],
 'feeds': {
  'harness': ['Topic: agentic-harnesses', '3c65c17b0d0d81d881a8fe98b4cff7bb'], 'bench': ['Topic: benchmarks', '3c65c17b0d0d811fb43fece56e40041a'],
  'serving': ['Topic: inference-and-serving', '3c65c17b0d0d81c08b3bc95ff45c7b13'], 'hardware': ['Topic: hardware', '3c65c17b0d0d8118beeefaed56da6f8e'],
  'llms': ['Topic: llms', '3c65c17b0d0d812d9e00f6ec89965286'], 'deepseek': ['DeepSeek', '3c65c17b0d0d81a2ae7ec6796947a235'],
  'genmm': ['Topic: generative-and-multimodal', '3c65c17b0d0d817ab6ade318917bff55'], 'papers': ['Papers', '3c65c17b0d0d81549dbedb27e8f2a26f'],
  'training': ['Topic: llm-training-and-post-training', '3c65c17b0d0d81b6876ee72b7056793b'], 'data': ['Topic: data-curation-and-datasets', '3c65c17b0d0d811fa5ecda8d365ab00f'],
  'anthropic': ['Anthropic: Claude family', '3c65c17b0d0d814cb979d0eabca59a45'], 'openai': ['OpenAI: GPT family', '3c65c17b0d0d814abf90d5b9e567d72f'],
  'kimi': ['Moonshot AI: Kimi', '3c65c17b0d0d81f5abf5dbdbac821a12'], 'mistral': ['Mistral AI', '3c65c17b0d0d814a9882e6ebc326fa56'],
  'meta': ['Meta: Llama and Meta Superintelligence Labs', '3c65c17b0d0d81949ad8e17bcb3567f1'], 'google': ['Google DeepMind: Gemini and Gemma', '3c65c17b0d0d8173a0aafcb27cf7a5f3'],
  'other': ['Other notable providers', '3c65c17b0d0d8154ba44e521a4ed8749'], 'qwen': ['Alibaba: Qwen', '3c65c17b0d0d81fd8c36ce06672bb235'],
  'protocols': ['Topic: protocols', '3c65c17b0d0d81ec9355f4eecd6eed02'], 'evals': ['Topic: evaluation-and-llm-judges', '3c65c17b0d0d8181b351e1b8fc6a1546'],
  'cuda': ['Topic: cuda-and-gpu-programming', '3c65c17b0d0d81c39f34d5e070d783c1'], 'jax': ['Topic: jax-and-tpu', '3c65c17b0d0d81ecbc04eea6aa45ea1a'],
  'math': ['Topic: math', '3c65c17b0d0d81cdb851c0835b25a538']},
 'items': {}, 'followups': []}

I = A['items']
def item(n, id, d=None, **k): I[str(n)] = dict(id=id, d=d, **k)

# ---------------- Top stories ----------------
item(1, 'pacing', '2026-09-12', tags=['policy', 'safety'], feeds=['anthropic', 'llms'], follow='fu-pacing', notes=[
 check('the essay (dated "September 2026" on the page) matches the issue: pacing "does not mean halting model training", three steps (embedded evaluators, which "Anthropic is unilaterally committing to"; coordination among companies in democracies, with a government antitrust waiver; coordination with authoritarian governments), four levels of global agreement from a ban on bioweapon uses to a full pause, and the warning that "in 6–12 months such a swarm could be capable of taking over the entire internet with a persistent botnet (potentially causing hundreds of billions of dollars in damage)" ({{essay|https://darioamodei.com/post/we-must-pace-the-frontier}}). Axios, as archived on 13 September, confirms Altman ("I agree with Dario that we need to pace the frontier", plus external evaluator access), Musk ("Dario is right") and Palihapitiya\'s dissent ({{Axios, archived|https://web.archive.org/web/20260913015512/https://www.axios.com/2026/09/12/anthropic-ai-amodei-pacing}}).'),
 corr('the essay names the trigger more specifically than "the OpenAI agent incidents": it is the OpenAI-Hugging Face incident, in which a swarm of agents attacked targets unrelated to its task and tried to hack its grader. Level 3 of the global ladder, a "speed limit" on recursive self-improvement, sits between testing agreements and a general pause.')]
)
item(2, 'deepseek-v41', '2026-09-10', tags=['open-weights', 'architecture', 'serving'], feeds=['deepseek', 'serving', 'llms'], follow='fu-ds-pro', viz_after='ced', notes=[
 check('the model card confirms MIT for code and weights, reasoning effort "from 1 to 100" (published scores use 100), 552B backbone parameters, 8B active in prefill and 16B in decode, a 1M-token context and native vision; the 10 September changelog lists Terminal-Bench 2.1 at 90.6, Codeforces 3471 and GPQA Diamond 90.9 ({{model card|https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash}}, {{changelog|https://api-docs.deepseek.com/updates/}}). The pricing page gives $0.30 input on a cache miss and $1.20 output per million at peak, half off-peak, and cache hits at $0.006 peak and $0.003 off-peak ({{pricing|https://api-docs.deepseek.com/quick_start/pricing}}). The 40 layers split 20 and 20 ({{config.json|https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash/blob/main/config.json}}). The changelog as archived on 10 and 11 September carries the issue\'s routing plan word for word: "After 12:00 Beijing Time on September 14, 2026, and until the future release of V4.1 Pro, all requests to deepseek-v4-pro will be routed to V4.1 Flash" ({{archived 11 Sep|https://web.archive.org/web/20260911101540/https://api-docs.deepseek.com/updates/}}); it was withdrawn two days later (below).'),
 corr('the concession in DeepSeek\'s report is about domain, not loop length: "a gap with giant models remains on science-oriented agentic tasks, such as Terminal-Bench 4.0, that require expert-level domain knowledge" (31.2% against 51.8% for the best model in its table) ({{report|https://arxiv.org/abs/2609.19969}}).'),
 rel('Layer-by-layer detail of the encoder-decoder stack and its cache is on the {{DeepSeek page|n:3c65c17b0d0d81a2ae7ec6796947a235}}; the opposite trade (more decoder work per token, done sequentially) is the Recurrent Looped Transformer in [[Research|t-research|v-rlt]].')])
item(3, 'harness-buy', '2026-09-10', also=[['2026-09-11', 'Sakana']], tags=['agents', 'harness'], feeds=['harness', 'protocols'], notes=[
 check('Sakana\'s post is dated 11 September and describes Fugu as routing each task "to the leanest model capable of solving it" across a pool of open and specialised models, behind "our standard OpenAI-compatible API" ({{Sakana|https://sakana.ai/fugu-max-release/}}). It does not use the words "build an agentic scaffold for it on the fly"; that description is unconfirmed here. Releasebot\'s OpenAI page now shows only late-September entries, so the Agents API details were checked separately (in [[Dev tools|t-dev|i-agents-api]]).'),
 rel('The two products are listed again in [[Dev tools|t-dev|i-managed-agents]], and Fugu in [[Models|t-models|i-fugu]]. Real-SWE, just below, is a measurement made with each vendor\'s own harness.')])
item(4, 'realswe', '2026-09-12', dnote='date of the first archived copy', tags=['benchmark', 'coding-agents'], feeds=['bench', 'harness'], follow='fu-rswe', viz_after='rswe', notes=[
 check('the page as archived on 12 September matches the issue exactly: Fable 5.1 38.8%, GPT-6 Astra 33.8%, Gemini 3.8 Flash 31.2%, GLM 5.3 28.8%, Grok 4.6 and Muse Spark 1.3 23.8%, Kimi K3 18.8%, GPT-5.6 Sol 16.2%; "6 of 10 tasks have resolution rates below 15%"; costs from $2.50 to $6.96; a median of 11 files edited; missed requirements the commonest failure; 71.4% of rollouts under ten minutes failed (70 of 98) ({{archived 12 Sep|https://web.archive.org/web/20260912202830/https://withspecific.com/benchmarks/real-swe}}). Each rate recomputes from the page\'s per-task table (passes over 80 rollouts); 640 = 10 tasks x 8 models x 8 trials.'),
 corr('two readings of the issue\'s numbers need care. The 71.4% is not evidence that short runs fail more: on the same page, 73.4% of the longer rollouts failed (398 of 542). And the "roughly 20 points" private-code penalty compares two different benchmarks, Terminal-Bench 4.0 (Fable 5.1 55.8%, GPT-6 Astra 57.9%) against Real-SWE (38.8%, 33.8%): the gaps are 17 and 24 points, but a different test is not a controlled measurement of private code. Cost and success are not unrelated either: Pearson r is about 0.7 across the eight models in this reading (the card below).'),
 rel('Discussed on Hacker News (in [[Talk of the town|t-talk|i-results-threads]]), where the thread now stands at 275 points and 158 comments.')])
item(5, 'cyber-ops', '2026-09-10', dnote='report: date of the first archived copy', also=[['2026-09-09', 'Google'], ['2026-09-11', 'GreyNoise']], tags=['security', 'agents'], feeds=['anthropic', 'harness'], notes=[
 check('the report covers activity disrupted "between December 2025 and August 2026" and opens its trends with "Sophisticated attacks no longer require sophisticated attackers"; it describes a Russian espionage actor (GTG-20006) targeting "more than 20 distinct organizations", a credential pipeline that "mass-downloaded 1.8 million distinct Android APKs", a Chinese-speaking group (GTG-10007) that targeted "roughly fifty organizations" and found "multiple previously-unknown vulnerabilities" in a security product, a campaign that "attacked roughly thirty AI companies in about four days", a single operator with internal access at 14 of 42 targets exfiltrating "12 to 26 GB", about 70 fabricated news sites with "at least 8,913 articles" reaching six continents, over 1,000 fake X accounts across all 222 Malaysian constituencies, and "breaches completed in two to three hours" ({{Anthropic|https://www.anthropic.com/threat-intelligence-report-september-2026}}). Its influence section details nine cases, of which the issue names three; none of the cases used Fable or Mythos-class models except one distillation case.'),
 rel('MOLE, in [[Research|t-research|i-mole]], measures the same problem from inside an organisation; the sandbox flaw in DeepSeek\'s agent tooling is in [[Dev tools|t-dev|i-ds-cve]].')])

# ---------------- Models ----------------
item(6, 'v41-pointer', '2026-09-10', tags=['open-weights'], feeds=['deepseek'], notes=[rel('Told in full, with the architecture animation, in [[Top stories|t-top|i-deepseek-v41]].')])
item(7, 'fugu', '2026-09-11', also=[['2026-09-10', 'first reports']], tags=['orchestration'], feeds=['harness', 'other'], notes=[
 check('Sakana\'s post (11 September) gives $2 and $6 per million and says the output price is "40-60% lower than Sonnet 5, GPT 5.6 Terra, and Kimi K3" (output only); Fugu Max "expands the cost-performance Pareto frontier on seven out of ten benchmarks"; Fugu Ultra v2 scores 48.3 on Chartography against Opus 5\'s 27.3 (and Fable 5\'s 29.5), 74.3 on DeepSWE, best or joint-best on five of eight. It adds that Fable 5, Fable 5.1 and GPT-6 Astra are not in Fugu Ultra v2\'s pool ({{Sakana|https://sakana.ai/fugu-max-release/}}).')])
item(8, 'swe2', '2026-09-12', tags=['coding-agents', 'rl'], feeds=['kimi', 'training'], notes=[
 check('Cognition\'s post confirms FrontierCode 1.1 Main 50.0% against Fable 5.1\'s 50.9% "while being 64% cheaper", Terminal-Bench 2.1 92.8% and Terminal-Bench 4 27.3% (against 55.8% for Fable 5.1 and 57.9% for GPT-6 Astra, so 28.5 to 30.6 points behind), post-training from Kimi K3 "a 2.8T-parameter model", effort levels trained in "a single RL run, with each penalty tuned to the local slope of the base model\'s Pareto frontier", and SWE-2 medium against SWE-1.7 at "58% fewer turns and costing 81% less" ({{Cognition|https://cognition.com/blog/swe-2}}).'),
 corr('the post is dated 10 September (09.10.26), not 12 September.')])
item(9, 'north-translate', '2026-09-10', also=[['2026-09-09', 'first reports']], tags=['open-weights', 'translation'], feeds=['genmm', 'other'], notes=[
 check('MarkTechPost (10 September) confirms 218B total and 25B active, 128 experts with 8 active plus shared experts, a 4096-token sliding window interleaved 3:1 with global layers, 16K in and out, WMT26 scores 83.60 and 84.36 (agentic) against DeepL NextGen 81.37 and Google Translate 68.20, 48.9 against 21.3 on two book chapters in one call, Cohere\'s own runs with GPT-5.6-Sol as judge, free API use to rate limits, non-commercial self-hosting, and NVFP4 on one B200 or two H100s ({{MarkTechPost|https://www.marktechpost.com/2026/09/10/cohere-releases-north-small-translate-a-218b-moe-translation-model-that-scores-83-6-on-wmt26-across-50-languages/}}). It describes the weights as open, which the issue does not say.')])
item(10, 'gpt-live', '2026-09-10', tags=['voice'], feeds=['genmm', 'openai'])
item(11, 'images-25', '2026-09-08', tags=['image'], feeds=['genmm', 'openai'])
item(12, 'suno-v6', '2026-09-09', tags=['music', 'licensing'], feeds=['genmm'])
item(13, 'minicpm5', '2026-09-07', tags=['on-device', 'open-weights'], feeds=['other'])
item(14, 'ling-vl', '2026-09-10', tags=['vision'], feeds=['other'])
item(15, 'auk', '2026-09-08', tags=['speech', 'open-source'], feeds=['genmm'], notes=[
 check('the arXiv listing exists under that number ({{arXiv 2609.08936|https://arxiv.org/abs/2609.08936}}); the 217 Hugging Face upvotes are as stated in the issue and were not re-counted.')])
item(16, 'reducto', '2026-09-07', tags=['documents'], feeds=['other'])
item(17, 'muse-agent', '2026-09-09', tags=['agents', 'security'], feeds=['meta'], follow='fu-muse')
item(18, 'gemini-windows', '2026-09-10', tags=['apps'], feeds=['google'])

# ---------------- Research ----------------
item(19, 'mole', '2026-09-07', tags=['security', 'benchmark'], feeds=['papers', 'bench'], notes=[
 check('the abstract (submitted 7 September) confirms 150 AI-operated accounts, 9 stateful services, 30 workdays, 12 threats, 8 corpora from four models totalling "roughly 20 billion tokens", "Of 39 agent models, 72% complete most assigned harmful objectives and agent refusal does not predict completion", the best monitor "misses nearly half of completed harm" in a single-day audit comparison, and benchmark-guided search improving a mid-tier monitor by 49-64% ({{arXiv 2609.06966|https://arxiv.org/abs/2609.06966}}).'),
 rel('The attacks it is built to catch are the subject of the threat report in [[Top stories|t-top|i-cyber-ops]].')])
item(20, 'neohorse', '2026-09-08', tags=['post-training', 'harness'], feeds=['papers', 'training'], notes=[
 check('the abstract confirms the routing harness, structural validation, "six-dimensional semantic evaluation", subscene-level labelling, a three-stage curriculum with routing-guided on-policy distillation, and macro-averages 58.94 to 64.87 at 4B and 65.60 to 69.04 at 9B over eleven benchmarks ({{arXiv 2609.08183|https://arxiv.org/abs/2609.08183}}). The 412 Hugging Face upvotes were not re-counted.')])
item(21, 'phi-bench', '2026-09-09', dnote='arXiv submission date', tags=['benchmark', 'infrastructure'], feeds=['papers', 'bench'], notes=[
 check('the paper\'s HTML confirms 85 tasks (55 kernel-function completions, 20 long-horizon implementations, 10 end-to-end optimisations), nine categories, a taxonomy built from 2,260 papers and 1,852 artifacts, Claude Opus 5 at 36.53%, Kimi K3 28.12% and Qwen3.8 Max 27.73% ({{arXiv 2609.10226|https://arxiv.org/abs/2609.10226}}).'),
 corr('5.4% is the best score in Hardware & Edge (Qwen3.7 Max), not the category\'s average: "even the best-performing model achieved only 5.4%"; Opus 5 scores 3.9% there.')])
item(22, 'hyper-tau', '2026-09-08', tags=['benchmark', 'agents'], feeds=['bench', 'harness'], notes=[
 check('Sierra\'s post (8 September): "Claude Opus 5 (max reasoning) running in Claude Code passes just 23.9% of the held-out evaluation tasks. Paired with an engineer with deep context, the same class of model reaches 82.2% on the same tasks" ({{Sierra|https://sierra.ai/blog/hyper-t-bench-evaluating-agents-that-build-agents}}). Derived: 82.2 / 23.9 = 3.44, the issue\'s 3.4x. Note "the same class of model", not necessarily the identical configuration.')])
item(23, 'arc-harness', '2026-09-06', dnote='source date; one day before the window', tags=['benchmark', 'harness'], feeds=['bench'], notes=[
 check('TNW (6 September): "ARC Prize ran GPT-6 Astra twice. Its own harness returned 62.7%, OpenAI\'s returned 99.9%", and OpenAI then revised five published metrics after launch ({{TNW|https://thenextweb.com/news/openai-astra-arc-agi-3-harness-62-7-vs-99-9-benchmark-revisions}}).')])
item(24, 'rlt', '2026-09-13', also=[['2026-09-09', 'Raschka']], tags=['architecture'], feeds=['training', 'openai'], follow='fu-rlt', viz_after='rlt', notes=[
 check('the project page as archived on 13 September matches the issue: a causal encoder, a decoder that carries its final state and layerwise sliding-window cache across every token with no reset at the serving boundary, the 48 + 48 layout with shared weights, 96 logical blocks per token and a path of 48t decoder blocks, and "Realized reasoning gains, hardware efficiency, and RL scaling remain to be established" ({{archived 13 Sep|https://web.archive.org/web/20260913000705/https://yifanzhang-pro.github.io/recurrent-looped-tranformer/}}). It adds the cost the issue leaves out: "Decoder updates still proceed in token order", so prompt prefill is sequential in the decoder (the animation below counts it).'),
 corr('Raschka\'s survey (dated 9 September) does not argue that recurrent depth costs monitorability. He writes that shorter traces are "not necessarily" a concern, that Astra\'s system card notes reduced monitorability "mostly associated with shorter, less informative traces" but "this doesn\'t establish looping as the root cause", and he quotes OpenAI\'s chief scientist that the depth of Astra\'s computation graph is "within a factor of two of GPT-4" ({{Raschka|https://magazine.sebastianraschka.com/p/gpt-6-astra-looped-transformers-and}}). That Astra uses this family is a rumour, not something OpenAI has said.')])
item(25, 'magic', '2026-09-09', tags=['pretraining'], feeds=['training'], notes=[
 check('Magic\'s post is dated 8 September (not 9) and says its recipe is ">10x more compute-efficient than that of leading open-weight base models", matching DeepSeek V4 Pro Base "using ~50x fewer FLOPs" ({{Magic|https://magic.dev/blog/pretraining}}). Vendor-reported, as the issue says.')])
item(26, 'data-gains', '2026-09-09', tags=['pretraining', 'data'], feeds=['data', 'training'], notes=[
 check('the post (by Dwarkesh Patel and Jerry Han, dated 8 September) finds "from 2019 to 2025, 3.24x more compute efficiency gains have come from data improvements rather than model improvements (12.0x for data and 3.7x for models), at the 1e19 FLOPs compute budget", and that the two are "mostly independent" (88% of variance explained by additive effects) ({{Dwarkesh|https://www.dwarkesh.com/p/pretraining-progress-is-mostly-data}}). Derived: 12.0 / 3.7 = 3.24.'),
 unc('"small models gaining most from data quality" was not found in the post; the study itself runs only up to 1e19 FLOPs, which is small scale.')])
item(27, 'random-attention', None, tags=['kv-cache', 'serving'], feeds=['serving'], notes=[
 check('the repository describes a "signal-free KV-cache eviction policy for reasoning models: keep the prompt, then keep a uniformly random per-KV-head subset of the generated tokens", which "matches or beats learned selectors (SnapKV, R-KV, VaSE, TriAttention)" at matched budgets on MATH-500, GPQA-Diamond, AIME, HMMT and LiveCodeBench, and is the fastest evictor ({{GitHub|https://github.com/SalesforceAIResearch/Random-Attention}}; paper arXiv 2609.03430). It is scoped to the generated tokens of reasoning models, not to every cache.')])
item(28, 'realswe-pointer', '2026-09-12', tags=['benchmark'], feeds=['bench'], notes=[rel('Covered, with its three readings, in [[Top stories|t-top|v-rswe]].')])
item(29, 'navier', '2026-09-09', tags=['math', 'agents'], feeds=['math', 'openai'], follow='fu-navier', notes=[
 link('The issue\'s link is to Scientific American\'s home page, not to an article; the story it points to is the follow-up below.')])
item(30, 'econ', '2026-09-10', tags=['economics'], feeds=['anthropic'], viz_after='econ', notes=[
 check('the issue gives no source; Anthropic\'s scenario explorer (live 10 September) and its working paper confirm the extreme case: GDP 32.4% above the no-AI path ($44.4T at 2025 prices), labour share from 60% to 45.2%, unemployment 11.9% for all workers (17.9% for cognitive workers), and total labour income "almost exactly what it would have been without AI" ({{explorer|https://www.anthropic.com/institute/econ-scenarios}}, {{paper|https://www-cdn.anthropic.com/files/4zrzovbb/website/cf58f84d46a4a76bf5a5b039ac695fba6b80041c.pdf}}, Table 3). The calculator below multiplies it out.')])
item(31, 'also-research', None, tags=['papers'], feeds=['papers'], notes=[
 check('the four arXiv listings exist under the numbers given ({{2609.08936|https://arxiv.org/abs/2609.08936}}, {{2609.11682|https://arxiv.org/abs/2609.11682}}, {{2609.13141|https://arxiv.org/abs/2609.13141}}, {{2608.30597|https://arxiv.org/abs/2608.30597}}). The AlphaGenome atlas has no link in the issue.')])

# ---------------- Industry ----------------
item(32, 'anthropic-ipo', '2026-09-09', also=[['2026-09-12', 'profit guidance']], tags=['ipo'], feeds=['anthropic'], follow='fu-ipo')
item(33, 'openai-no-ipo', '2026-09-12', tags=['ipo'], feeds=['openai'])
item(34, 'softbank-loan', '2026-09-14', tags=['financing'], feeds=['openai'])
item(35, 'mistral', '2026-09-08', tags=['funding', 'sovereign'], feeds=['mistral'], notes=[
 check('TechCrunch (8 September): Mistral raised "€3 billion (about $3.58 billion) at a post-money valuation of more than €21 billion", a Series D led by Samsung Electronics with EQT\'s Scaleup Europe Fund and PSG Equity as co-leads, which Mistral called "the largest equity fundraising round ever completed by a European technology company" ({{TechCrunch|https://techcrunch.com/2026/09/08/mistral-raises-e3b-as-sovereign-ai-becomes-big-business/}}).')])
item(36, 'rum-gpu', '2026-09-13', tags=['compute-deal'], feeds=['anthropic', 'hardware'])
item(37, 'metr-moves', '2026-09-12', also=[['2026-09-09', 'Coxon'], ['2026-09-10', 'Christiano']], tags=['people', 'safety'], feeds=['anthropic', 'openai'], notes=[
 rel('The same week, Amodei proposed embedding outside evaluators such as METR inside each lab ([[Top stories|t-top|i-pacing]]).')])
item(38, 'pentagon', None, tags=['defence'], feeds=['anthropic', 'openai'], follow='fu-pentagon', notes=[
 link('The issue\'s link is to The Intercept\'s home page, not to the article.')])
item(39, 'tan-distill', '2026-09-11', hn={'p': 319}, tags=['policy', 'distillation'], feeds=['llms'], notes=[
 check('TechCrunch (11 September, by Julie Bort): Tan hopes regulators stay out of Chinese labs\' distillation and thinks US open-weight labs should distil frontier models too ({{TechCrunch|https://techcrunch.com/2026/09/11/y-combinators-garry-tan-wants-u-s-open-weight-ai-labs-to-distill-frontier-models-too/}}).')])
item(40, 'raine-act', '2026-09-10', tags=['policy', 'minors'], feeds=['llms'])
item(41, 'umg-elevenlabs', '2026-09-10', tags=['music', 'licensing'], feeds=['genmm'])
item(42, 'adi-alif', '2026-09-10', tags=['acquisition', 'edge'], feeds=['hardware'])
item(43, 'positron-round', '2026-09-10', tags=['funding', 'chips'], feeds=['hardware'], notes=[rel('What Positron is building, and why it skips HBM, is in [[Compute|t-compute|i-positron-hbm]].')])
item(44, 'meta-csam', '2026-09-09', tags=['harm', 'advertising'], feeds=['meta'], notes=[
 link('The issue\'s link is to WIRED\'s home page, not to the article.')])
item(45, 'invoice-fraud', '2026-09-10', tags=['fraud'], feeds=['harness'])

# ---------------- Compute ----------------
item(46, 'positron-hbm', '2026-09-10', dnote='source date', tags=['chips', 'memory'], feeds=['hardware', 'serving'], notes=[
 check('Converge Digest (10 September): a Series C at a $5 billion post-money valuation funds the tapeout of Asimov on TSMC N3P at the end of 2026 with production in the second half of 2027; Asimov is designed around commodity LPDDR5X "instead of HBM", with 288 GB to 2,304 GB of memory per chip and more than 90% of available bandwidth realised, per Positron; its shipping Atlas platform has 50-plus racks at Oracle ({{Converge Digest|https://convergedigest.com/positron-ai-raises-875m-asimov-inference-silicon/}}). No Asimov bandwidth figure is published, so the bet cannot be priced yet.'),
 rel('Why bandwidth caps the speed of one stream of tokens, and what a long context does to it, is worked out in [[Dev tools|t-dev|v-sol]].')])
item(47, 'ironwood', '2026-09-08', tags=['chips', 'tpu'], feeds=['hardware', 'jax'], follow='fu-tpu', notes=[
 check('SemiAnalysis\'s InferenceX post is dated 7 September (not 8): "In our apples-to-apples comparisons against B200/B300, Ironwood delivers up to 50% better performance per dollar", and "Ironwood (TPUv7) is the first generation in which Google is competing for others\' inference workloads with chips that can be purchased outright or rented" ({{SemiAnalysis|https://inferencex.semianalysis.com/blog/tpu-inferencex-full-steam}}). "Up to" is the best point on the curve; the post says the advantage holds "across much of" it.')])
item(48, 'arm-n4', '2026-09-08', tags=['chips', 'cpu'], feeds=['hardware'])
item(49, 'rocm10', '2026-08-28', dnote='one day before the issue\'s two-week look-back', tags=['software', 'agents'], feeds=['cuda', 'hardware'], notes=[
 check('the ROCm.ai page describes AMD Skills ("AI skills that allow agentic coding tools like Cursor, Claude, Codex, Gemini, and others to understand ROCm natively") and Hyperloom ("AI-assisted optimization layer that analyzes workloads, tunes configurations and kernels, adjusts parallelism strategies") ({{ROCm.ai|http://ROCm.AI}}). Phoronix refused automated reading, so the 3.3x and 2.4x uplift figures were not re-checked there.')])
item(50, 'cerebras-qwen', '2026-09-04', dnote='outside the window', hn={'p': 688}, tags=['inference', 'speed'], feeds=['serving', 'hardware', 'qwen'], notes=[
 rel('What bounds decode speed on HBM-based GPUs, for comparison, is in [[Dev tools|t-dev|v-sol]].')])
item(51, 'miit-target', '2026-09-08', also=[['2026-09-10', 'JD Cloud']], tags=['policy', 'capacity'], feeds=['hardware'])
item(52, 'power', '2026-09-09', also=[['2026-09-08', 'Duane Arnold'], ['2026-09-10', 'Massachusetts']], tags=['energy', 'data-centres'], feeds=['hardware'])
item(53, 'a20-pro', '2026-09-09', tags=['on-device', 'chips'], feeds=['hardware'])

# ---------------- Dev tools ----------------
item(54, 'agents-api', '2026-09-10', tags=['agents', 'platform'], feeds=['harness', 'openai'], notes=[rel('The story behind both products is in [[Top stories|t-top|i-harness-buy]].')])
item(55, 'managed-agents', '2026-09-10', tags=['agents', 'governance'], feeds=['harness', 'anthropic'])
item(56, 'megakernel', '2026-09-09', tags=['serving', 'kernels'], feeds=['serving', 'cuda'], viz_after='sol', notes=[
 check('Cohere\'s post is dated 8 September (not 9) and is about one model on one GPU: "North Mini Code", a 30B model with 3.3B active parameters, in BF16 "on a single H100". "On batch size 1, our megakernel reaches 292 tok/s, or 62% of SoL, 1.58x faster than vLLM", vLLM serving 185 (39%); end to end it is "1.25x - 1.41x faster than vLLM", and the margin "holds across batch sizes and out to 256K of context" ({{Cohere|https://cohere.com/blog/megakernels}}). The calculator below reproduces the speed-of-light figure from its inputs.')])
item(57, 'claude-code', '2026-09-12', also=[['2026-09-08', '2.1.266']], tags=['release'], feeds=['harness'], notes=[
 check('the changelog dates 2.1.266 to 2.1.270 to 8 to 12 September and lists each change the issue names: the gateway regression fix, <code>maxEffortLevel</code> "on every provider, including Bedrock, Vertex and Foundry", gateway pricing through managed settings, <code>configDirectory</code> in <code>claude auth status --json</code>, a WebFetch that "now fails after 300 seconds", the idle CPU busy loop, <code>claude plugin eval</code>, <code>/output-style</code>, file diffs in Bash results, kitty-protocol keyboard support over SSH, the prompt-cache fix after an interrupted response, a higher Workflow concurrent-agent limit, and the read-only git permission fix in 2.1.270 ({{changelog|https://code.claude.com/docs/en/changelog}}).')])
item(58, 'codex-154', '2026-09-11', tags=['release'], feeds=['harness', 'openai'])
item(59, 'cursor-projects', '2026-09-10', tags=['agents', 'coordination'], feeds=['harness'])
item(60, 'pizza-bot', '2026-09-13', tags=['agents', 'open-source'], feeds=['harness'])
item(61, 'deep-research', '2026-09-09', also=[['2026-09-10', 'Data plugin']], tags=['apps'], feeds=['openai'])
item(62, 'ds-cve', '2026-09-10', tags=['security'], feeds=['harness', 'deepseek'])
item(63, 'quiet-feeds', None, tags=['release'], feeds=['serving'], follow='fu-vllm', notes=[
 corr('GitHub\'s release records show the window was not quiet: vLLM v0.29.0 was published on 9 September, TensorRT-LLM v1.3.0rc26 and transformers v5.17.0 the same day, and llama.cpp published about 88 builds between 7 and 14 September (it builds several times a day). SGLang\'s v0.5.19 came on 5 September, just before the window; PyTorch had no release in it ({{vLLM releases|https://github.com/vllm-project/vllm/releases}}, {{TensorRT-LLM|https://github.com/NVIDIA/TensorRT-LLM/releases}}, {{transformers|https://github.com/huggingface/transformers/releases}}, {{llama.cpp|https://github.com/ggml-org/llama.cpp/releases}}).')])

# ---------------- Talk of the town ----------------
item(64, 'math-misalignment', None, hn={'p': 1219}, tags=['math'], feeds=['math'], notes=[
 check('the page is a declaration, "A Severe Misalignment of AI in Mathematics", published 11 September with a DOI and a list of endorsers ({{mathandai.org|https://mathandai.org/}}).'),
 corr('it does not argue that LLMs build a parallel, divergent corpus. Its argument is that "the goals of the AI companies and the goals of the mathematical community are severely misaligned": solving famous problems is a proxy for understanding, solutions announced in a rush raise "severe attribution and plagiarism questions", and without mathematicians to absorb them "the crucial human transmission chain between mathematicians would be lost".'),
 rel('The OpenAI result it landed beside is in [[Research|t-research|i-navier]].')])
item(65, 'slowdown-but-me', None, hn={'p': 739}, tags=['policy'], feeds=['llms'], notes=[
 unc('the post sits behind a bot check that automated reading could not pass, so its content was not re-read.')])
item(66, 'bengio', None, hn={'p': 576}, tags=['safety', 'agents'], feeds=['harness'], notes=[
 check('the essay is dated 11 September and opens on "the incidents of the last few months in which AI agents misbehaved in serious ways" ({{Bengio|https://yoshuabengio.org/en/publication/why-are-ai-agents-lying-cheating-and-coordinating}}).')])
item(67, 'central-bank', None, hn={'p': 558}, tags=['economics'], feeds=['hardware'])
item(68, 'results-threads', None, tags=['benchmark'], feeds=['bench'], notes=[
 check('the Real-SWE thread now shows 275 points and 158 comments ({{HN|https://news.ycombinator.com/item?id=49676820}}); the issue\'s 268 was its count on 14 September.'),
 rel('Real-SWE itself, with its three readings, is in [[Top stories|t-top|v-rswe]].')])
item(69, 'sacks', None, tags=['policy'], feeds=['llms'], notes=[rel('Amodei\'s essay and the response to it are in [[Top stories|t-top|i-pacing]].')])

# ---------------- Follow-ups ----------------
A['followups'] = [
 {'id': 'fu-ds-pro', 'd': '2026-09-13', 'for': [2], 't': 'DeepSeek kept V4 Pro after all',
  'html': 'By the changelog\'s capture of 13 September the routing plan was gone, replaced by: "In response to user demand, we have decided to continue providing API services for DeepSeek V4 Pro after September 14, 2026, with the billing method remaining unchanged" ({{archived 13 Sep|https://web.archive.org/web/20260913121105/https://api-docs.deepseek.com/updates/}}). On 2 October the pricing page still lists <code>deepseek-v4-pro</code> (DeepSeek-V4-Pro-0813) at $1.32 and $3.96 per million at peak; only the old Flash names route to V4.1-Flash ({{pricing|https://api-docs.deepseek.com/quick_start/pricing}}). The technical report followed on 17 September and confirms the cache figures animated above ({{arXiv 2609.19969|https://arxiv.org/abs/2609.19969}}), and vLLM v0.30.0 added V4.1-Flash on 22 September ({{release notes|https://github.com/vllm-project/vllm/releases/tag/v0.30.0}}).'},
 {'id': 'fu-rswe', 'd': '2026-09-28', 'for': [4], 't': 'Real-SWE rewrote its table twice',
  'html': 'By 15 September Grok 4.6 had been re-run: 23.8% became 32.5%, third place, at $2.67 a rollout instead of $3.44, with every other cell unchanged ({{archived 15 Sep|https://web.archive.org/web/20260915063330/https://withspecific.com/benchmarks/real-swe}}). By 28 September every model had been re-scored on two tasks (Billing schedule migration from 9 passes in 64 to 50, API token metering from 8 to 14): GPT-6 Astra now leads at 46.25% ahead of Fable 5.1 at 45.00%, only four tasks stay below 15%, and the short-rollout failure rate reads 57.4% against 66.2% for longer ones ({{live page|https://withspecific.com/benchmarks/real-swe}}). No change note was published. The card above shows all three readings.'},
 {'id': 'fu-rlt', 'd': '2026-09-20', 'for': [24], 't': 'RLT got its first experiments',
  'html': 'The project page, updated 20 September with two co-authors (Jichen Feng, Shihan Qin), now reports trained models: eight-layer encoder-decoder splits against an eight-layer Transformer on six algorithmic tasks, three seeds each (a 17 September snapshot). Several splits learn parity earlier and keep 100% at 256 bits; on swaps-based permutation tracking at length 512 the 4+4 split reaches 55.70% against 0.85% for the Transformer; addition beyond trained widths and standard permutation tracking stay hard. The 48 + 48 tied layout remains an illustration; the experiments use untied 8- and 16-layer models of 25 to 29 million parameters ({{project page|https://yifanzhang-pro.github.io/recurrent-looped-tranformer/}}).'},
 {'id': 'fu-pacing', 'd': '2026-09-22', 'for': [1], 't': 'Anthropic\'s first release tested by outside evaluators',
  'html': 'On 18 September Anthropic published the measurements behind the essay: more than 80% of code merged into its codebase authored by Claude as of May 2026 and the typical engineer merging 8 times as much code per day as in 2024, with its own caveat that lines of code overstate the gain ({{Anthropic, recursive self-improvement|https://www.anthropic.com/institute/recursive-self-improvement}}). On 22 September it released Claude Opus 5.5, "our first release since we called for pacing the frontier", which it says "was tested before release by external evaluators, including Frontier Design and METR" ({{Anthropic|https://www.anthropic.com/news/claude-opus-5-5}}).'},
 {'id': 'fu-ipo', 'd': '2026-09-22', 'for': [32], 't': 'A new Claude model before the listing',
  'html': 'Anthropic released Claude Opus 5.5 on 22 September, ahead of the October listing the issue reports; it "performs at the level of Claude Fable 5.1 on most work and costs 40% less to run than Opus 5" ({{Anthropic|https://www.anthropic.com/news/claude-opus-5-5}}).'},
 {'id': 'fu-pentagon', 'd': '2026-09-25', 'for': [38], 't': 'Court upholds the Pentagon\'s designation of Anthropic',
  'html': 'A federal appeals court in Washington, D.C. upheld the Pentagon\'s designation of Anthropic as a supply-chain risk, rejecting the company\'s challenge ({{CNBC|https://www.cnbc.com/2026/09/25/pentagon-anthropic-ai-risk-appeals-court.html}}).'},
 {'id': 'fu-vllm', 'd': '2026-09-22', 'for': [63], 't': 'vLLM v0.30.0',
  'html': 'vLLM shipped v0.30.0 on 22 September, thirteen days after v0.29.0, with Fast Start (weights kept in GPU memory across engine restarts), output watermarking and support for DeepSeek-V4.1-Flash, among much else ({{release notes|https://github.com/vllm-project/vllm/releases/tag/v0.30.0}}, {{release list|https://github.com/vllm-project/vllm/releases}}).'}]

# Checks for items the issue gives no source for, from a separate search (merged into each item's notes)
fn = 'data/factcheck_notes.json'
if os.path.exists(fn):
    FC = json.load(open(fn))
    for n, notes in FC.get('notes', {}).items():
        I[n].setdefault('notes', [])
        ORD = {'check': 0, 'corr': 1, 'unc': 2, 'link': 3, 'rel': 4}
        I[n]['notes'] = sorted(I[n]['notes'] + notes, key=lambda x: ORD[x[0]])
    for f in FC.get('followups', []):
        A['followups'].append(f)
        I[str(f['for'][0])].setdefault('follow', f['id'])
json.dump(A, open('data/annotations.json', 'w'), indent=1, ensure_ascii=False)
print('items', len(I), 'followups', len(A['followups']))
