#!/usr/bin/env python3
"""Write data/factcheck_notes.json: the checks for items the issue gives no source for (or only a home-page link),
from a separate search run on 2026-10-02 (raw results in inputs/factcheck_raw.json). mk_annotations.py merges these
notes into each item. Only article-level URLs are linked; where only a site was found, the note says so. Run from src/."""
import json
CK = '2026-10-02'
def check(t): return ['check', f'<b>Checked</b> {CK}: ' + t]
def corr(t): return ['corr', f'<b>Correction</b> ({CK}): ' + t]
def unc(t): return ['unc', '<b>Unconfirmed</b>: ' + t]
N = {
 '1': [check('Nadella\'s words were that Microsoft welcomes "the research, focus, and deliberate pacing needed to get alignment right" (13 September); Microsoft\'s Code of Conduct for its MAI models followed on 14 September as a draft for public consultation ({{GeekWire|https://www.geekwire.com/2026/microsoft-floats-rules-for-its-own-ai-models-as-industry-debates-a-slowdown/}}). Sacks\'s point (14 September) was that the labs do not need Washington\'s permission to slow down, which is close to, but not the same as, "voluntary commitments make regulation unnecessary" ({{Townhall|https://townhall.com/news/dmitri-bolt/2026/09/14/david-sacks-why-do-ai-companies-need-government-permission-to-slow-down-n2682937}}).')],
 '5': [check('GreyNoise\'s count is 440 PaperCut systems at 395 organisations in 48 countries, first remote code execution in under four hours ({{BankInfoSecurity, 11 Sep|https://www.bankinfosecurity.com/ai-agents-used-in-papercut-attacks-on-395-organizations-a-32801}}). Google\'s credential-theft report was published on 8 September, not 9 ({{SiliconANGLE|https://siliconangle.com/2026/09/08/google-says-attackers-used-ai-agents-to-steal-credentials-in-under-six-hours/}}).'),
       corr('the Claude Mythos 5 PyPI upload was first disclosed on 30 July, as one of three incidents in cybersecurity evaluations ({{Anthropic, 30 Jul|https://www.anthropic.com/news/investigating-incidents-cybersecurity-evals}}); the 9 to 10 September publication is a follow-up assessment that adds a fourth incident and a signed agreement with METR ({{TNW|https://thenextweb.com/news/anthropic-alignment-assessment-cybersecurity-incidents-481-million-transcripts}}). Per that coverage the cause was a partner\'s misconfigured sandbox connected to the open internet; "pre-release audits had not caught" is not how the sources put it. The report details nine influence operations, of which the issue names three.')],
 '6': [],
 '7': [check('Sakana\'s Fugu page says the service is not yet available in the EU and EEA, and the release post cites both ICLR 2026 papers: "TRINITY: An Evolved LLM Coordinator" (Xu et al.) and "Learning to Orchestrate Agents in Natural Language with the Conductor" (Nielsen et al.) ({{Fugu|https://sakana.ai/fugu/}}). "Closed weights" is an inference: Fugu is offered only as an API and no weights are published.')],
 '8': [corr('Cognition says SWE-2 is available "in Devin Desktop and CLI" and is "also rolling it out on Devin Web and Fusion", so not only Desktop and CLI. The free period to 10 October for paid plans comes from secondary coverage, not from Cognition\'s post.')],
 '10': [check('coverage of the 10 September launch confirms full-duplex speech, 12 voices, $0.05 per minute for the voice layer (tools and model calls billed separately) and telephony ({{tbreak|https://tbreak.com/openai-gpt-live-1-api/}}). OpenAI\'s own page could not be read; WebRTC, WebSockets and SIP are unconfirmed, as is "new" for the voices.')],
 '11': [corr('OpenAI\'s post (8 September) describes Sketch as using a rough drawing as a visual reference for the image, not converting it into a text prompt, and the two API models as tiers: gpt-image-2.5-flare for fast everyday generation and gpt-image-2.5-sunburst for extra precision; region editing and reference preservation are improvements of Images 2.5 as a whole. Latency is "up to 50% lower" than Images 2.0 ({{OpenAI|https://openai.com/index/introducing-chatgpt-images-2-5/}}).')],
 '12': [check('Suno launched v6 (with v6-wild and v6-mini) on 9 September, trained on music licensed from Warner Music Group, BMG and Believe ({{Axios|https://www.axios.com/2026/09/09/suno-v6-ai-music-warner-bmg}}).'),
        corr('the opt-in is described for Believe and TuneCore artists and labels, not all participating repertoire; and the licences did not replace lawsuits so much as end one: Warner\'s November 2025 deal settled its own suit against Suno ({{Music Ally|https://musically.com/2026/09/09/suno-launches-its-v6-ai-music-models-heres-what-you-need-to-know/}}).')],
 '13': [check('MiniCPM5-2B (7 September) is a dense, text-only model of 2.52B parameters with a 128K context under Apache-2.0, averaging 53.9 on OpenBMB\'s 34-benchmark table ({{AI Weekly|https://aiweekly.co/alerts/openbmb-ships-minicpm5-2b-a-25b-apache-20-on-device-model-averaging-539-across}}).')],
 '14': [check('OpenRouter lists inclusionai/ling-3.0-flash-vl with a free variant: a 124B-total, 5.5B-active mixture of experts with a 262,144-token context taking text, image and video ({{OpenRouter|https://openrouter.ai/inclusionai}}). The 10 September date was not confirmed.')],
 '16': [corr('Reducto announced r-1 on 1 September (7 September is MarkTechPost\'s write-up); the claim is "up to 20%" fewer errors, at 1 cent per page ({{PR Newswire|https://www.morningstar.com/news/pr-newswire/20260901sf37626/reducto-unveils-a-frontier-parsing-model-that-makes-the-worlds-hardest-documents-ai-ready-for-1-a-page}}).')],
 '17': [corr('Meta introduced Muse on 8 September, not 9. It runs on "Muse Secure VM, a dedicated, virtual machine (VM) that houses both the agent and a person\'s data", with a separate Sentinel agent approving internet access; Meta lists email, travel, forms, shopping and connected apps, and health and smart home were not confirmed ({{Meta|https://about.fb.com/news/2026/09/introducing-muse-personal-ai-agent/}}).')],
 '18': [check('Google\'s Gemini app for Windows 10 and 11 began a global rollout on 10 September, summoned with Alt+Space ({{TechEngage|https://techengage.com/google-gemini-desktop-app-windows/}}).')],
 '29': [corr('OpenAI announced the result on 8 September; 9 September is the date of the MIT quantum post. The run used about 10,000 coordinating agents over 88 hours and produced a 166-page paper with a Lean formalisation. The dispute is over priority and credit: NYU\'s Tristan Buckmaster says he and Levent Alpoge had a solution by 22 August ({{Implicator|https://www.implicator.ai/clay-institute-navier-stokes-openai-proof-claim/}}). In the MIT run, GPT-5.6 Sol completed 40 target measurements with researchers stepping in on four ({{The Quantum Insider|https://thequantuminsider.com/2026/09/09/openai-says-ai-agents-may-make-great-quantum-lab-assistants/}}).')],
 '32': [corr('the $559 million adjusted operating profit on more than $11.5 billion of revenue is the second quarter, already completed and Anthropic\'s first profitable one; the "second profitable quarter" is guidance for the third quarter, with no figure given (FT, via {{Investing.com|https://ng.investing.com/news/stock-market-news/anthropic-tells-investors-it-will-post-second-straight-quarterly-profit--ft-2693905}}). The Nasdaq choice was reported from 12 September with the profit guidance; a 9 September date was not confirmed. All of it is press reporting, not a company announcement ({{Benzinga|https://www.benzinga.com/markets/tech/26/09/61756404/anthropic-nasdaq-2-trillion-ipo-second-consecutive-profitable-quarter}}).')],
 '33': [check('Altman told Fortune on 12 September that "given everything that\'s happening with safety... right now would be an ill-advised moment to go public" ({{Fortune|https://fortune.com/2026/09/15/sam-altman-says-openai-ipo-window-pushed-2027-but-markets-arent-the-culprit/}}).')],
 '34': [check('Bloomberg (14 September): an upsized $11.9 billion ($11.87 billion) two-year loan from about 20 banks, above an initial $10 billion target, sealed the week before ({{Bloomberg|https://www.bloomberg.com/news/articles/2026-09-14/softbank-gets-upsized-11-9-billion-loan-in-openai-funding-push}}).')],
 '36': [corr('RUM Group (formerly Rumble) signed and disclosed the agreement, worth "up to" about $13.7 billion over six years for its Georgia data centre, in an SEC filing on 24 August without naming the customer; The Information named Anthropic on 13 September and neither company has confirmed it. The $364 million is the whole warrant at one day\'s closing price ({{Benzinga|https://www.benzinga.com/trading-ideas/movers/26/09/61761845/anthropic-is-reportedly-rums-13-7-billion-mystery-customer}}). The previous issue\'s 14.8 GW and $517 billion were not re-checked here.')],
 '37': [corr('Benton announced his move on 11 September and Engels on 13 September, not both on 12 September; Christiano\'s appointment was announced on 9 September, not 10 ({{OpenAI|https://openai.com/index/paul-christiano-joins-openai-foundation-board/}}). Coxon\'s resignation was reported on 9 September ({{TIME|https://time.com/article/2026/09/09/ai-anthropic-openai-jacob-coxon/}}). Whether Benton and Engels argued for "mandatory reporting" specifically was not confirmed.')],
 '38': [check('the article is The Intercept\'s of 8 September: FOIA-released paperwork for July 2025 agreements, "each worth up to $200 million", to build prototype AI tools to "improve military advantage, military utility, or enhance military decision making" ({{The Intercept|https://theintercept.com/2026/09/08/military-ai-weapons-contracts-openai-anthropic-google/}}).')],
 '40': [corr('the law is SB 1119, Adam\'s Law, signed on 10 September and effective July 2027; its chatbot rules (time limits, mental-health resources, age verification, parental alerts on self-harm) cover all minors. The under-16 threshold belongs to a separate social-media bill signed the same day ({{CalMatters|https://calmatters.org/economy/technology/2026/09/california-enacts-laws-restricting-chatbots-protecting-kids-online/}}).')],
 '41': [check('announced 10 September: a multi-year licensing and product deal anchored by a licensed fan-remix platform, artists opting in track by track; ElevenLabs\' first major-label deal ({{TNW|https://thenextweb.com/news/umg-elevenlabs-licensed-ai-music-platform}}).')],
 '42': [corr('announced on 9 September, not 10: $1.35 billion in cash plus an earn-out of up to $200 million, expected to close before the end of 2026 ({{ADI 8-K exhibit|https://www.sec.gov/Archives/edgar/data/0000006281/000119312526385938/d924057dex991.htm}}).')],
 '43': [check('all three on 10 September: Positron\'s $875 million is a $375 million Series C plus a Series C-1 of up to $500 million ({{Converge Digest|https://convergedigest.com/positron-ai-raises-875m-asimov-inference-silicon/}}); Ayar Labs\' $150 million extension took its 2026 primary capital to $650 million, its above-$5 billion price set by a concurrent secondary sale ({{SiliconANGLE|https://siliconangle.com/2026/09/10/ayar-labs-bags-150m-in-additional-series-e-funding-to-help-make-bigger-ai-chip-clusters/}}); Maven Robotics\' $100 million Series A ({{TechCrunch|https://techcrunch.com/2026/09/10/maven-robotics-wants-to-steal-your-robot-deployment-deal/}}).')],
 '44': [corr('the San Francisco City Attorney\'s cease-and-desist letter, dated 9 September, cites 332 ads, not "more than 350" ({{letter|https://media.api.sf.gov/documents/Meta_AI-Gen_CSAM_Ads_Ltr_from_D_Chiu_2026-09-09_Signed.pdf}}), from the Tech Transparency Project\'s report of 8 September ({{TTP|https://www.techtransparencyproject.org/articles/meta-ran-hundreds-of-paid-ads-with-child-sexual-abuse-imagery}}). The nine-month window, Meta\'s "minimal reach" reply and its jurisdiction dispute were not confirmed.')],
 '45': [corr('"nearly $50,000" is the single ACH payment each target was asked to make, not the campaign\'s total; the campaign was more than a million emails sent between 3 and 5 August, and Microsoft says its AI indicators do not establish how much of the content was generated ({{Microsoft Security|https://www.microsoft.com/en-us/security/blog/2026/09/10/protecting-organizations-ai-assisted-executive-impersonation-invoice-fraud/}}).')],
 '48': [corr('Arm claims up to 2x performance and 1.25x performance per watt over CSS N3, not specifically on inference-heavy workloads ({{Arm|https://newsroom.arm.com/news/arm-agi-cpu-neoverse-css-n4-agentic-ai}}); TSMC N3P and 3.8GHz are from coverage ({{Tom\'s Hardware|https://www.tomshardware.com/pc-components/cpus/arm-debuts-next-gen-semi-custom-neoverse-css-n4-ranger-platform-compute-subsystem-packs-up-to-128-cores-per-die-on-tsmc-n3p}}).')],
 '49': [corr('AMD\'s post is dated 27 August, not 28; the 3.3x and 2.4x compare ROCm 7.0 against a preview ROCm.AI build on ROCm 7.2.2, on MI355X, in AMD\'s testing of 7 July ({{AMD|https://newsroom.amd.com/news/rocm-10-software-ai-native-developer-experiences/}}).')],
 '50': [check('the Hacker News story of 4 September was headlined at 1,500 tokens per second; about 1,850 comes from other coverage ({{AlphaSignal|https://alphasignal.ai/news/cerebras-runs-alibaba-s-qwen-3-8-27b-at-1-850-tokens-per-second}}). The 688 points were not re-counted.')],
 '51': [corr('MIIT published its plan on Monday 7 September (coverage on 8 September): 9,800 EFLOPS by 2030, from 2,185, and 3.8 trillion yuan of information infrastructure over 2026 to 2030 ({{TechNode|https://technode.com/2026/09/11/china-targets-9800-eflops-of-intelligent-computing-capacity-by-2030/}}). JD Cloud\'s cluster was announced on 9 September, not 10 ({{TechNode|https://technode.com/2026/09/09/jd-cloud-moore-threads-100000-gpu-computing-cluster/}}).')],
 '52': [corr('Massachusetts Executive Order 658 was signed on 8 September, not 10 ({{TechCrunch|https://techcrunch.com/2026/09/09/massachusetts-hits-data-centers-with-new-clean-power-rules/}}). The Department of Energy loan to NextEra for Duane Arnold is "up to" $1.9 billion (8 September), and the 25-year term of Google\'s agreement was not confirmed ({{Utility Dive|https://www.utilitydive.com/news/nextera-doe-loan-duane-arnold-nuclear-restart/}}). Nvidia\'s Australian announcement was dated 9 September in the US; its article address was not found.')],
 '53': [corr('Apple says the A20 Pro\'s dual 16-core Neural Engine gives "double the AI processing power" of the A19 Pro, but does not say FP8; the FP8 doubling in coverage refers to the GPU ({{Apple|https://www.apple.com/newsroom/2026/09/apple-debuts-iphone-18-pro-and-iphone-18-pro-max/}}).')],
 '54': [corr('OpenAI\'s Agents API (10 September) puts the Codex harness behind one API and lists nine sandbox partners, not four: Blaxel, Cloudflare, Daytona, DigitalOcean, E2B, Modal, Oracle, Runloop and Vercel ({{MarkTechPost|https://www.marktechpost.com/2026/09/10/openai-launches-the-agents-api-in-public-beta-putting-the-codex-harness-behind-one-api-call/}}).')],
 '55': [check('the Claude Developer Platform release notes for 10 September add the auto permission policy for Managed Agents (the server runs, denies or pauses each agent or MCP tool call) and, in ant CLI 1.32.0, <code>ant beta:sessions connect</code> ({{release notes|https://platform.claude.com/docs/en/release-notes/overview}}).')],
 '58': [corr('Codex 0.154.0 was published on 9 September, not 11 ({{GitHub|https://github.com/openai/codex/releases/tag/rust-v0.154.0}}); its notes list GPT-6 Astra in the model picker, experimental worktrees, inline answers while Codex works and a shared background server on Windows, but not <code>max</code> and <code>ultra</code> effort values, ExternalMessage or per-turn service tiers. Floating quick chats and app-window sharing came on 11 September in the ChatGPT desktop app, not a Codex release ({{Codex changelog|https://developers.openai.com/codex/changelog}}).')],
 '59': [unc('Cursor published "Cursor Projects" (beta) on 10 September; the coordinator design and the "four harnesses" count were not checked, and the article address was not found.')],
 '60': [corr('AWS published Pizza Bot on 10 September (13 September is MarkTechPost\'s write-up), an Apache 2.0 inbox for background agents built on DeepAgents and LangGraph ({{MarkTechPost|https://www.marktechpost.com/2026/09/13/aws-introduces-pizza-bot-an-open-source-inbox-for-background-ai-agents/}}).')],
 '61': [corr('OpenAI calls the 10 September launch a Data agent, not a "Data plugin", alongside ChatGPT for financial services on GPT-6 Astra. The 9 September Deep Research release, the voice model selection change, library permissions and the exact list of data partners were not confirmed, and no article address was found.')],
 '62': [corr('CVE-2026-82533 (CVSS 9.4) was disclosed by OX Security on 8 September and reported on 9 September, not 10: a sandboxed agent could call DeepSeek Harness\'s unauthenticated local web interface and switch its own session to full access, turning off the sandbox and the approval prompts (not "safety prompts"). The fix is in 0.1.2-rc.1, not 0.1.2-alpha.1 ({{The Hacker News|https://thehackernews.com/2026/09/deepseek-harness-flaw-let-ai-agents.html}}).')],
 '67': [unc('The Economist\'s piece was published on 3 September, before the window; its address and the 558 points were not checked.')],
 '68': [unc('Fable 5.1\'s cipher result was first reported on 2 September, before the window; the 289 points were not re-counted.')],
 '69': [unc('Sacks\'s remark was reported on 13 and 14 September; the 221 and 46 points were not re-counted.')],
}
FU = [{'id': 'fu-navier', 'd': '2026-09-21', 'for': [29], 't': 'Scientific American: did OpenAI solve the wrong problem?',
       'html': 'Scientific American argues that OpenAI used the Clay problem\'s option that allows an external force, which most mathematicians regard as the less natural version, quoting Luis Silvestre: "The Clay problem is settled, but the main problem for the Navier-Stokes equations is not"; three mathematicians have posted a proof that the forced method cannot extend to the unforced problem ({{Scientific American|https://www.scientificamerican.com/article/did-openai-solve-the-wrong-navier-stokes-problem/}}). The Clay Institute has not accepted the claim, and the paper is not peer reviewed ({{Implicator|https://www.implicator.ai/clay-institute-navier-stokes-openai-proof-claim/}}).'}]
json.dump({'notes': {k: v for k, v in N.items() if v}, 'followups': FU}, open('data/factcheck_notes.json', 'w'), indent=1, ensure_ascii=False)
print('notes for', len([v for v in N.values() if v]), 'items')
