"""The one dataset of the Release history tab.

Source of truth: ../data/release_history.json (140 rows, one per significant release, with kind tags,
licences, date notes, the conflicts list and the compiler's notes). This script
1. applies the five sourced corrections made when the LLM release history page was rebuilt (idempotent;
   each corrected row carries `fix` and `fix_url`, Grok-1 also `active_derived`), and
2. writes ../parts/30_js_time_a_data.js, the rows every view of the tab draws from.
Run from anywhere: python3 src/history/mk_data.py
"""
import json, os
H = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(H, '..', 'data', 'release_history.json')
OUT = os.path.join(H, '..', 'parts', '30_js_time_a_data.js')

FIX = {
 'Aya Expanse': dict(licence='CC-BY-NC 4.0', total_params_B=32, active_params_B=32, date_note=None,
   fix='Licence confirmed and size filled (the old table said "unverified" and "n/a"): the model card gives CC-BY-NC and "32 billion parameters" for the larger of the 8B and 32B models.',
   fix_url='https://huggingface.co/CohereLabs/aya-expanse-32b'),
 'GLM-4.7': dict(total_params_B=355, active_params_B=32,
   fix="Size filled (the old table said \"n/a\"), by construction: every size field of its config.json matches GLM-4.5's, the 355B / 32B row.",
   fix_url='https://huggingface.co/zai-org/GLM-4.7/raw/main/config.json'),
 'Gemma 4': dict(total_params_B=31, active_params_B=31,
   fix='Size filled (the old table said "n/a"): 31B is the largest, dense; the 26B MoE activates 3.8B, so "26B-A4B" is the rounded name.',
   fix_url='https://blog.google/innovation-and-ai/technology/developers-tools/gemma-4/'),
 'GLM-5.3': dict(total_params_B=744, active_params_B=40,
   fix="Size filled (the old table said \"n/a\"), by construction: the model card says it \"uses the same base model as GLM-5.2\" (744 / 40); the Hub's tensor count reads 753B.",
   fix_url='https://huggingface.co/zai-org/GLM-5.3'),
 'Grok-1': dict(active_params_B=78.5, active_derived=True,
   fix='Active size derived here: xAI says "25% of the weights active on a given token", so 0.25 × 314 = 78.5B (the old table gave the total only).',
   fix_url='https://x.ai/news/grok-os'),
}

def fmtsz(t, a):
    f = lambda v: (('%g' % (v / 1000)) + 'T') if v >= 1000 else '%g' % v
    return f(t) if (a is None or a == t) else f(t) + ' / ' + f(a)

def main():
    D = json.load(open(SRC))
    seen = set()
    for r in D['rows']:
        if r['model'] in FIX:
            r.update(FIX[r['model']]); seen.add(r['model'])
            if r.get('date_note') is None: r.pop('date_note', None)
    assert seen == set(FIX), seen
    new = json.dumps(D, indent=2, ensure_ascii=False)
    if open(SRC).read().rstrip('\n') != new:
        open(SRC, 'w').write(new + '\n'); print('applied corrections to', os.path.relpath(SRC))
    out = []
    for r in D['rows']:
        t, a = r['total_params_B'], r['active_params_B']
        x = dict(d=r['date'], m=r['model'], l=r['lab'], o=r['open_weights'], lic=r['licence'],
                 sz=fmtsz(t, a) if t is not None else ('n/a' if r['open_weights'] else 'not disclosed'),
                 t=t, a=a, n=r['note'], u=r['source_url'], k=[k for k in r['kind'] if k != 'open'])
        if r.get('date_note'): x['dn'] = r['date_note']
        if r.get('active_derived'): x['da'] = 1
        if r.get('fix'): x['fix'], x['fu'] = r['fix'], r['fix_url']
        out.append(x)
    js = ('// Generated by src/history/mk_data.py from src/data/release_history.json: the 140 rows every view of the\n'
          '// Release history tab draws from. dn = date note, da = active size derived, fix/fu = a correction and its source.\n'
          '(window.RH=window.RH||{}).ROWS=' + json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ';\n')
    open(OUT, 'w').write(js)
    print(len(out), 'rows,', len(js.encode()), 'bytes ->', os.path.relpath(OUT))

if __name__ == '__main__':
    main()
