"""Atlas entries, part A: network, transport, naming, security.

Conventions (resolved by build_data.py):
- ("rfc", n) or ("rfc", n, "§x.y") in `srcs` or `versions` is filled from sources/rfc_meta.json
  (title, publication month, status, URL), so no RFC date is typed by hand.
- ("draft", name) is filled from sources/drafts.json.
- ("gh", "owner/repo", tag) is filled from sources/github.json (release date and URL).
- Plain (label, url) pairs are other primary sources, all checked on CHECKED (build_data.py).
- `wire` names a recording in wire/out/<id>.txt; the page shows it verbatim.
- Text fields use `code` and [text](url) inline markdown, rendered by the page.
"""

A = [
 dict(id="ip", name="IP", full="Internet Protocol, versions 4 and 6", group="net", year=1981, body="IETF",
  cur="IPv4 (RFC 791) and IPv6 (RFC 8200)", status="Internet Standard (both)",
  plain="The postal system of the internet: every machine has an address, and IP carries a **packet** (a chunk of bytes with a header saying where it came from and where it goes) from one address towards another, hop by hop through routers, with no promise that it arrives.",
  problem="Get a packet from any machine to any other machine across many independent networks.",
  how="Each packet carries a source and destination address (32 bits in IPv4, 128 bits in IPv6). Routers forward it one hop closer; packets can be dropped, duplicated or reordered, and a packet bigger than a link's **MTU** (maximum transmission unit, usually 1500 bytes on Ethernet) must be split or rejected.",
  runs_on=[], uses=[],
  adds="An IP header (20 bytes for IPv4 without options, 40 for IPv6) with the two addresses.",
  costs="Nothing is guaranteed: delivery, order and integrity are left to the layers above.",
  not_when="You never choose IP; you choose what runs on it. What you do choose is IPv4 or IPv6 reachability and the MTU of your network.",
  replaces="IPv6 was meant to replace IPv4 (address exhaustion); both run side by side, and clients race them (Happy Eyeballs, RFC 8305).",
  competes="Nothing at this layer on the public internet.",
  meet=["Every request you send: the `A` (IPv4) and `AAAA` (IPv6) records DNS returns are IP addresses.",
        "Kubernetes pod and service IPs; private ranges such as `10.0.0.0/8` (RFC 1918) inside a VPC.",
        "MTU problems on overlay networks (VXLAN, VPN tunnels) and on cloud links that allow jumbo frames (9001 bytes inside an AWS VPC)."],
  fail=dict(symptom="Small requests work, large ones hang forever (a TLS handshake or a big POST stalls).",
            cause="A path MTU black hole: a link on the path has a smaller MTU, the router drops the big packets, and the ICMP message that should say so is filtered by a firewall.",
            see="`ping -D -s 1472 host` (macOS, don't-fragment) or `ping -M do -s 1472 host` (Linux) finds the largest packet that gets through."),
  wire=["ip", "ipv6"],
  wire_note="Three echo requests to Cloudflare's resolver over IPv4 and over IPv6 from the recording machine: about 18 to 20 ms per round trip either way.",
  srcs=[("rfc", 791), ("rfc", 8200), ("rfc", 1918), ("rfc", 8305),
        ("AWS: network MTU for EC2 instances (9001 inside a VPC)", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/network_mtu.html")],
  versions=[("rfc", 791, "IPv4 specified"), ("rfc", 2460, "IPv6 first specified"), ("rfc", 8200, "IPv6 becomes an Internet Standard")]),

 dict(id="tcp", name="TCP", full="Transmission Control Protocol", group="transport", year=1981, body="IETF",
  cur="RFC 9293 (August 2022), which obsoletes RFC 793", status="Internet Standard",
  plain="Turns IP's unreliable packets into a reliable, ordered **byte stream** between two programs: what one side writes, the other reads, in order, with nothing missing.",
  problem="Applications want a pipe, not loose packets: reliable, ordered delivery that slows down when the network is congested.",
  how="A **connection** between two **sockets** (IP address plus **port**, a 16-bit number naming the program) starts with a three-way **handshake** (SYN, SYN-ACK, ACK: one **round trip**, the time for a packet to go and an answer to return). Every byte is numbered; the receiver acknowledges what arrived and the sender retransmits what did not. **Flow control** (the receive window) stops a fast sender from flooding a slow reader; **congestion control** (for example CUBIC, RFC 9438) backs off when packets are lost.",
  runs_on=["ip"], uses=[],
  adds="A TCP header (20 bytes minimum) with ports, sequence and acknowledgement numbers, and the window.",
  costs="One round trip before any data; one lost packet stalls every byte behind it (**head-of-line blocking**); throughput of one connection is at most window divided by round-trip time.",
  not_when="Real-time media or games where a late packet is worthless (use UDP); many independent streams over a lossy path (QUIC avoids cross-stream stalls).",
  replaces="Nothing older survives; QUIC re-implements its job on top of UDP.",
  competes="QUIC for web traffic; RDMA transports inside GPU clusters.",
  meet=["Under every HTTP/1.1 and HTTP/2 call: the LLM API, vLLM's OpenAI-compatible server, Triton's HTTP and gRPC ports.",
        "NCCL's socket transport when no InfiniBand or RoCE is available, and `torch.distributed` rendezvous (the TCP store on `MASTER_PORT`).",
        "Checkpoint uploads to object storage, where one connection cannot fill a fast long link."],
  fail=dict(symptom="`Connection refused` instantly, or a connect that hangs then times out.",
            cause="Refused: the host answered with a reset because nothing listens on that port. Hang: a firewall or security group silently drops the SYN, so the client retries until its timeout.",
            see="`nc -vz host 443` (refused versus timeout), `ss -tn` or `lsof -iTCP` for the connection states."),
  wire=["tcp", "timing"],
  wire_note="`nc` only opens and closes a TCP connection. The curl timing line splits one request to the API into DNS, TCP connect, TLS and first byte, cumulative seconds from the start.",
  srcs=[("rfc", 9293), ("rfc", 793), ("rfc", 9438)],
  versions=[("rfc", 793, "TCP specified"), ("rfc", 9293, "TCP respecified, RFC 793 obsoleted"), ("rfc", 9438, "CUBIC congestion control standardised")]),

 dict(id="udp", name="UDP", full="User Datagram Protocol", group="transport", year=1980, body="IETF",
  cur="RFC 768 (August 1980), updated by RFC 9868 (UDP options, October 2025)", status="Internet Standard",
  plain="Ports on top of IP and nothing else: send a **datagram** (one self-contained message), maybe it arrives, maybe not, no connection.",
  problem="Let applications send messages with no setup cost and no retransmission delay, and build their own reliability if they want it.",
  how="An 8-byte header (source port, destination port, length, checksum) on an IP packet. No handshake, no ordering, no retransmission, no congestion control.",
  runs_on=["ip"], uses=[],
  adds="8 bytes: two ports, a length and a checksum.",
  costs="Everything TCP does for you, you must do yourself (or accept loss). Middleboxes and NATs forget idle UDP flows quickly.",
  not_when="When you need a reliable stream and are not using a library (QUIC, RTP) that provides one.",
  replaces="Nothing; it is the minimal transport.",
  competes="TCP for anything that needs reliability by default.",
  meet=["Classic DNS queries go over UDP port 53.",
        "QUIC and therefore HTTP/3 run on UDP port 443.",
        "RoCEv2 carries RDMA traffic between GPU nodes in UDP datagrams to port 4791."],
  fail=dict(symptom="DNS answers occasionally take seconds, or large DNS answers fail.",
            cause="A lost UDP query is only retried after the resolver's timeout (5 s by default in glibc); large answers are truncated and must be retried over TCP, which some firewalls block.",
            see="`dig +stats` shows the query time; `dig +tcp` retries over TCP."),
  wire=["udp"],
  wire_note="One DNS question and answer in two UDP datagrams to 1.1.1.1 (62 bytes back).",
  srcs=[("rfc", 768), ("rfc", 9868),
        ("IANA service names and port numbers: 4791/udp, IP Routable RoCE (registered 2014-10-17)", "https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=4791")],
  versions=[("rfc", 768, "UDP specified"), ("rfc", 9868, "UDP options standardised")]),

 dict(id="quic", name="QUIC", full="QUIC: a UDP-based multiplexed and secure transport", group="transport", year=2021, body="IETF (started at Google)",
  cur="QUIC version 1 (RFC 9000, 9001, 9002, May 2021); QUIC version 2 (RFC 9369, May 2023)", status="Proposed Standard",
  plain="A new TCP built on UDP with TLS 1.3 inside it and many independent streams in one connection, so a lost packet only stalls the stream it belonged to.",
  problem="TCP plus TLS costs two round trips before data, stalls every stream on one loss, and is frozen inside operating systems and middleboxes.",
  how="QUIC packets ride in UDP datagrams. The TLS 1.3 handshake is carried inside QUIC (RFC 9001), so transport and encryption are set up in one round trip (zero with 0-RTT resumption). Streams are numbered and flow-controlled separately; loss recovery is per packet with per-stream delivery (RFC 9002). Connections have IDs, so they survive a change of IP address (Wi-Fi to mobile).",
  runs_on=["udp"], uses=["tls"],
  adds="A short QUIC header (connection ID, packet number) and frames; nearly everything is encrypted, including most of the header.",
  costs="Runs in user space, so more CPU per byte than kernel TCP; UDP is blocked or rate-limited on some corporate networks, so clients must fall back to TCP.",
  not_when="Inside a data centre on a clean network where kernel TCP is cheaper; networks that block UDP 443.",
  replaces="TCP plus TLS for HTTP/3.",
  competes="TCP with TLS 1.3 (HTTP/2).",
  meet=["Browsers reaching Google, Cloudflare and other CDNs over HTTP/3.",
        "Rarely between your own services: gRPC and most inference servers still use HTTP/2 over TCP."],
  fail=dict(symptom="HTTP/3 works at home but the same client is slow or falls back on the office network.",
            cause="A firewall drops or throttles UDP 443; the client waits for QUIC to fail before using TCP.",
            see="`curl --http3-only -v https://host/` (needs a curl built with HTTP/3) fails fast where UDP is blocked; `curl -sI` shows the `alt-svc: h3` advertisement."),
  wire=["http3"],
  wire_note="A server advertises QUIC with an `alt-svc` header over HTTP/2; the next connection may switch. The recording machine's curl 8.7.1 has no HTTP/3, so the QUIC handshake itself is in the On the wire tab.",
  srcs=[("rfc", 9000), ("rfc", 9001), ("rfc", 9002), ("rfc", 9369)],
  versions=[("rfc", 9000, "QUIC v1 published"), ("rfc", 9369, "QUIC v2 published")]),

 dict(id="dns", name="DNS", full="Domain Name System, with DoT, DoH and DoQ", group="naming", year=1987, body="IETF",
  cur="RFC 1034 and 1035 (November 1987) plus many updates; encrypted transports DoT (RFC 7858, 2016), DoH (RFC 8484, 2018), DoQ (RFC 9250, 2022)", status="Internet Standard (core)",
  plain="The phone book: turns a name like `api.anthropic.com` into IP addresses, through a chain of servers that each know part of the answer, with every answer cached for a number of seconds (its **TTL**, time to live).",
  problem="Humans and configs use names; IP needs addresses; addresses change.",
  how="Your machine asks a **recursive resolver** (your ISP's, 1.1.1.1, or the cluster's CoreDNS). On a cache miss it asks a root server, then the `.com` servers, then the domain's own servers, and caches each answer for its TTL. Records: `A` (IPv4), `AAAA` (IPv6), `CNAME` (alias), `SRV`, `TXT`, `HTTPS` (RFC 9460: tells clients the server speaks HTTP/3). **DoT** wraps queries in TLS on port 853, **DoH** sends them as HTTPS requests, **DoQ** over QUIC, so the network cannot read or alter them.",
  runs_on=["udp", "tcp"], uses=["tls", "http2"],
  adds="A question and answer section; classic DNS is plain text on UDP 53.",
  costs="One more lookup before any connection (cheap when cached); stale answers until the TTL expires; plain DNS can be read and rewritten by the network.",
  not_when="Service discovery that must react in milliseconds (TTLs and client caches lag); use a service mesh or client-side registry.",
  replaces="The HOSTS.TXT file of the 1970s and 1980s.",
  competes="For encryption: DoT versus DoH versus DoQ.",
  meet=["Every API call starts with a lookup; in Kubernetes each pod's `/etc/resolv.conf` points at CoreDNS with `ndots:5`, so a short name triggers several searches first.",
        "Multi-node training finds the master by a DNS name of a headless service.",
        "A deploy that moves an endpoint, while clients still hold the old address until the TTL runs out."],
  fail=dict(symptom="Some requests take exactly 5 s longer than others, or a new endpoint is unreachable for some clients for minutes.",
            cause="5 s: a lost UDP query waits for the resolver's retry timeout (5 s by default in the glibc resolver). Minutes: a cached old answer lives until its TTL, and negative answers and resolution failures are cached too (RFC 9520).",
            see="`dig +noall +answer name` shows the answer and its remaining TTL; `dig +trace` follows the delegation from the root."),
  wire=["dns", "doh", "dohwho"],
  wire_note="The plain lookup returns both an IPv4 and an IPv6 address with their remaining TTL in seconds. The DoH attempt failed on the recording machine: a device-management DNS filter answers for `cloudflare-dns.com` with its own certificate, and curl refuses it (exit 60). That is encrypted DNS doing its job: the interception is visible instead of silent.",
  srcs=[("rfc", 1034), ("rfc", 1035), ("rfc", 7858), ("rfc", 8484), ("rfc", 9250), ("rfc", 9460), ("rfc", 9520),
        ("Kubernetes: DNS for services and pods (ndots:5 in pod resolv.conf)", "https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/"),
        ("resolv.conf(5): `timeout:n`, default RES_TIMEOUT, currently 5 s", "https://man7.org/linux/man-pages/man5/resolv.conf.5.html")],
  versions=[("rfc", 1035, "DNS specified"), ("rfc", 7858, "DNS over TLS"), ("rfc", 8484, "DNS over HTTPS"), ("rfc", 9250, "DNS over QUIC"), ("rfc", 9460, "SVCB and HTTPS records")]),

 dict(id="tls", name="TLS 1.3", full="Transport Layer Security 1.3 (and the status of 1.2)", group="security", year=2018, body="IETF",
  cur="RFC 9846 (July 2026), which obsoletes RFC 8446 (August 2018) and RFC 5246 (TLS 1.2)", status="Proposed Standard",
  plain="The sealed envelope around your bytes: it proves you reached the real server (with a **certificate**) and encrypts everything after the first exchange, in one round trip.",
  problem="Anyone on the path can read and alter plain TCP; you also need to know that `api.anthropic.com` is really Anthropic.",
  how="The client's first message (ClientHello) carries a key share and the name it wants (**SNI**, server name indication) and the protocols it speaks (**ALPN**: `h2`, `http/1.1`). The server answers with its key share, then sends its certificate chain and a signature, all already encrypted. Both sides derive keys; application data flows after one round trip. Hybrid post-quantum key exchange (`X25519MLKEM768`) is now an RFC (RFC 10024, August 2026). TLS 1.2 still works but is frozen (RFC 9851), and new protocols must require 1.3 (RFC 9852).",
  runs_on=["tcp"], uses=["x509"],
  adds="Record framing (a 5-byte header per record, RFC 9846 §5.1, plus the AEAD tag, 16 bytes with AES-GCM) and one round trip of handshake.",
  costs="One round trip (two with TLS 1.2), some CPU, and certificates to issue, renew and trust.",
  not_when="Almost never skip it; inside a trusted host (localhost, a Unix socket) it adds nothing.",
  replaces="SSL 3.0, TLS 1.0 and 1.1 (deprecated by RFC 8996), and in new protocols TLS 1.2.",
  competes="Within its job, nothing; SSH secures shells with its own protocol.",
  meet=["Every HTTPS call to an LLM API; the recording shows `api.anthropic.com` negotiating TLS 1.3 with the hybrid post-quantum group `X25519MLKEM768`.",
        "`SSL: CERTIFICATE_VERIFY_FAILED` from Python behind a corporate proxy that re-signs traffic.",
        "Terminating TLS at a load balancer in front of vLLM or Triton."],
  fail=dict(symptom="`certificate verify failed: unable to get local issuer certificate` (Python, curl exit 60).",
            cause="The client does not trust the CA that signed the server's chain: a corporate interception proxy, a private CA not installed in the client's bundle (`certifi` in Python ships its own), or a server that forgot to send its intermediate certificate.",
            see="`openssl s_client -connect host:443 -servername host -showcerts` shows the chain the server sends; `-brief` shows version, cipher and group."),
  wire=["tls13", "tls12"],
  wire_note="The same server negotiated TLS 1.3 with the hybrid post-quantum group when allowed, and still accepts TLS 1.2 (plain X25519) when the client forces it. Recorded with OpenSSL 3.6.5.",
  srcs=[("rfc", 9846), ("rfc", 8446), ("rfc", 5246), ("rfc", 8996), ("rfc", 9851), ("rfc", 9852), ("rfc", 10024), ("rfc", 9849), ("rfc", 9850), ("rfc", 7301)],
  versions=[("rfc", 5246, "TLS 1.2 published"), ("rfc", 8446, "TLS 1.3 published"), ("rfc", 8996, "TLS 1.0 and 1.1 deprecated"),
            ("rfc", 9849, "Encrypted Client Hello (ECH)"), ("rfc", 9846, "TLS 1.3 respecified (RFC 8446 obsoleted)"), ("rfc", 9851, "TLS 1.2 in feature freeze"),
            ("rfc", 9852, "New protocols must require TLS 1.3"), ("rfc", 10024, "Hybrid ML-KEM key agreement for TLS 1.3")]),

 dict(id="x509", name="X.509, PKI, ACME", full="X.509 certificates, the public key infrastructure, and ACME automation", group="security", year=2008, body="ITU-T X.509; IETF profile (RFC 5280); CA/Browser Forum rules; IETF ACME",
  cur="RFC 5280 profile; CA/Browser Forum Baseline Requirements 2.3.1 (4 October 2026); ACME RFC 8555 (2019)", status="Proposed Standard (5280, 8555); BRs are binding on public CAs",
  plain="A certificate is a signed statement: 'the public key K belongs to `api.anthropic.com`, valid from date A to date B, signed by authority C'. Your machine trusts a few hundred root authorities, and trust flows down a **chain** to the server's certificate.",
  problem="TLS can encrypt to a key, but you need to know whose key it is.",
  how="A CA verifies that an applicant controls a domain (ACME automates this with an HTTP or DNS challenge) and signs a certificate for it, usually through an intermediate CA. Clients check the chain up to a trusted root, the name, and the dates. Public certificate lifetimes are shrinking by CA/Browser Forum rule: 200 days from 15 March 2026, 100 days from 15 March 2027, 47 days from 15 March 2029 (domain validation reuse falls to 10 days). Let's Encrypt stopped OCSP in 2025 in favour of CRLs and offers a short-lived profile.",
  runs_on=[], uses=["tls"],
  adds="Nothing on the wire beyond the certificate chain sent in the TLS handshake (a few kilobytes).",
  costs="Renewal is now continuous work: with 47-day certificates, anything renewed by hand will expire.",
  not_when="Internal service identity: use a private CA or SPIFFE rather than public certificates.",
  replaces="Manual certificate purchase and installation (ACME); OCSP checks (CRLs, short lifetimes).",
  competes="Within the web PKI, nothing; inside organisations, private CAs and SPIFFE.",
  meet=["The certificate of every API you call; the recording shows `api.anthropic.com` with a 90-day certificate from Google Trust Services.",
        "cert-manager in Kubernetes speaking ACME to Let's Encrypt for your ingress.",
        "An outage the day a certificate expires because renewal silently failed."],
  fail=dict(symptom="Everything breaks at once with `certificate has expired`.",
            cause="A renewal job failed weeks ago and nobody was alerted; shorter lifetimes make this more frequent unless renewal is automated and monitored (ACME Renewal Information, RFC 9773, lets the CA tell clients when to renew).",
            see="`openssl s_client -connect host:443 </dev/null | openssl x509 -noout -dates`."),
  wire=["x509", "acme"],
  wire_note="The API's certificate is valid 21 September to 20 December 2026 (90 days, well inside the 200-day cap). The Let's Encrypt ACME directory lists its endpoints, the `renewalInfo` URL (RFC 9773) and three profiles including `shortlived`.",
  srcs=[("rfc", 5280), ("rfc", 8555), ("rfc", 9773), ("rfc", 9162),
        ("CA/Browser Forum Baseline Requirements v2.3.1, §6.3.2 validity schedule and §4.2.1 reuse", "https://cabforum.org/working-groups/server/baseline-requirements/requirements/"),
        ("Let's Encrypt: Ending OCSP support in 2025 (5 December 2024)", "https://letsencrypt.org/2024/12/05/ending-ocsp/")],
  versions=[("rfc", 5280, "X.509 profile for the internet"), ("rfc", 8555, "ACME published"), ("rfc", 9773, "ACME Renewal Information"),
            ("2026-03", "Public TLS certificates capped at 200 days (CA/B Forum)", "https://cabforum.org/working-groups/server/baseline-requirements/requirements/")]),

 dict(id="mtls", name="mTLS and SPIFFE", full="Mutual TLS, with SPIFFE workload identities", group="security", year=2018, body="IETF (TLS client certificates; RFC 8705 for OAuth); CNCF (SPIFFE, graduated 2022)",
  cur="TLS 1.3 client authentication; SPIFFE standards in github.com/spiffe/spiffe; RFC 8705 (OAuth certificate-bound tokens)", status="TLS: Proposed Standard; SPIFFE: CNCF graduated project (23 August 2022)",
  plain="Ordinary TLS proves the server's identity; mutual TLS also makes the client present a certificate, so each side knows who the other is. SPIFFE gives every workload a name like `spiffe://prod.example/ns/inference/sa/router` and short-lived certificates carrying it.",
  problem="Service-to-service calls inside a network need identity that is stronger than 'it came from an internal IP'.",
  how="In the TLS handshake the server sends a CertificateRequest; the client answers with its certificate and proves it holds the private key. A SPIFFE implementation (SPIRE, or a service mesh such as Istio or Linkerd) issues each workload an X.509 certificate (an SVID) with its SPIFFE ID and rotates it automatically before it expires.",
  runs_on=["tls"], uses=["x509"],
  adds="The client's certificate chain and a signature in the handshake.",
  costs="Certificate issuance, rotation and trust distribution for every workload: the reason meshes exist.",
  not_when="Public clients you do not control (browsers, customers' scripts): use OAuth or API keys.",
  replaces="IP allow-lists and shared secrets between services.",
  competes="Signed tokens (JWTs) on every request; cloud IAM (SigV4).",
  meet=["A service mesh that wraps calls between your gateway and the inference pods.",
        "A2A and MCP deployments inside a company: A2A Agent Cards can declare a `MutualTlsSecurityScheme`.",
        "OAuth tokens bound to a client certificate (RFC 8705), so a stolen token is useless elsewhere."],
  fail=dict(symptom="`tls: certificate required` or `bad certificate` between two services that worked yesterday.",
            cause="A workload certificate expired because the rotation agent stopped, or the two sides trust different CA bundles after a rotation.",
            see="`openssl s_client -connect svc:443 -cert client.pem -key client.key` shows whether the server asks for and accepts the certificate."),
  wire=[], wire_note="Not recorded here: no public endpoint asks for client certificates. The Failure lab tab reproduces certificate errors with a local CA.",
  srcs=[("rfc", 8705), ("rfc", 9846, "§4.4.2"),
        ("SPIFFE ID standard", "https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE-ID.md"),
        ("CNCF: SPIFFE project page (accepted 2018-03-29, graduated 2022-08-23)", "https://www.cncf.io/projects/spiffe/"),
        ("A2A v1.0.1 specification §4.5.6 MutualTlsSecurityScheme", "https://github.com/a2aproject/A2A/blob/v1.0.1/docs/specification.md")],
  versions=[("rfc", 8705, "OAuth mTLS client authentication"), ("2022-08", "SPIFFE graduates in CNCF", "https://www.cncf.io/projects/spiffe/")]),

 dict(id="ssh", name="SSH", full="Secure Shell, protocol version 2", group="security", year=2006, body="IETF",
  cur="RFC 4251 to 4254 (January 2006) plus updates; OpenSSH 10.5 (11 August 2026)", status="Proposed Standard",
  plain="An encrypted remote terminal and tunnel: log in to a GPU box, copy files, or forward a port (a Jupyter notebook) through one authenticated connection.",
  problem="Remote shells and file copies over an untrusted network, authenticated by keys rather than passwords sent in clear.",
  how="Three layers: the transport (key exchange, server host key, encryption), user authentication (public key, certificate, password) and the connection protocol, which multiplexes **channels** (shells, port forwards, `scp`/`sftp`) over one TCP connection. OpenSSH has used a hybrid post-quantum key exchange by default since 9.0 (2022, `sntrup761x25519`) and `mlkem768x25519-sha256` since 10.0 (2025); the ML-KEM method is RFC 10042 (August 2026).",
  runs_on=["tcp"], uses=[],
  adds="Its own packet format with encryption and a MAC; port 22.",
  costs="Long-lived keys copied onto many machines (key sprawl); host-key prompts that people click through.",
  not_when="Service-to-service APIs (use TLS); browser access.",
  replaces="telnet, rlogin, rsh, ftp.",
  competes="Cloud session managers (AWS SSM, IAP tunnels) that avoid open port 22.",
  meet=["`ssh -J bastion gpu-node` to reach a training node behind a jump host; `ssh -L 8888:localhost:8888` for a notebook.",
        "VS Code Remote and `git` over SSH to GitHub.",
        "SSH certificates signed by a CA instead of `authorized_keys` on every node."],
  fail=dict(symptom="`WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!` after a node is rebuilt.",
            cause="The new machine has a new host key; the client remembers the old one in `known_hosts`. Usually benign on recreated cloud nodes, and exactly what a man-in-the-middle would also produce.",
            see="`ssh -v host` shows the key exchange and host key; `ssh -Q kex` lists the key exchanges your client supports."),
  wire=["ssh", "sshkex"],
  wire_note="The first line a server sends is its protocol banner (`SSH-2.0-...`). The local OpenSSH 10.3p1 lists both hybrid post-quantum key exchanges.",
  srcs=[("rfc", 4251), ("rfc", 4253), ("rfc", 4254), ("rfc", 9941), ("rfc", 9987), ("rfc", 10042),
        ("OpenSSH release notes (9.0: 2022-04-08 sntrup761x25519 default; 10.0: 2025-04-09 mlkem768x25519 default; 10.5: 2026-08-11)", "https://www.openssh.com/releasenotes.html")],
  versions=[("rfc", 4253, "SSH-2 published"), ("2022-04", "OpenSSH 9.0: hybrid post-quantum key exchange by default", "https://www.openssh.com/releasenotes.html"),
            ("2025-04", "OpenSSH 10.0: mlkem768x25519 by default", "https://www.openssh.com/releasenotes.html"),
            ("rfc", 9987, "SSH agent protocol standardised"), ("rfc", 10042, "ML-KEM hybrid key exchange for SSH")]),
]
