"""Atlas entries, part C: who is calling (auth), agent protocols, and GPU fabric one-liners. Conventions as in data_a.py."""

MCP_SPEC = "https://modelcontextprotocol.io/specification/2026-07-28"
MCP_CHANGELOG = "https://modelcontextprotocol.io/specification/2026-07-28/changelog"
A2A_SPEC = "https://github.com/a2aproject/A2A/blob/v1.0.1/docs/specification.md"

C = [
 dict(id="oauth", name="OAuth 2.1", full="OAuth 2.1 authorization framework (IETF draft) and OAuth 2.0", group="auth", year=2012, body="IETF",
  cur="OAuth 2.0 is RFC 6749 (2012); OAuth 2.1 is draft-ietf-oauth-v2-1, revision 16 (3 September 2026), still an Internet-Draft", status="2.0: Proposed Standard; 2.1: Internet-Draft",
  plain="A way for a program to get a short-lived, limited **access token** to act on someone's behalf, without ever seeing their password: you log in at the provider, the provider hands the program a token scoped to what you approved.",
  problem="Delegated authorization: let an app (or an agent) use your account at another service, for some things, for a while, revocably.",
  how="**Authorization code with PKCE**: the app sends you to the authorization server with a random challenge; you log in and approve; the app gets a one-time code and swaps it, with the secret behind the challenge, for an access token (and maybe a refresh token). **Client credentials**: a service authenticates as itself. **Device grant** (RFC 8628): a headless box shows a code you approve on your phone. OAuth 2.1 folds PKCE, the security BCP (RFC 9700) and bearer token rules into one document and drops the implicit and password grants.",
  runs_on=["http11"], uses=["jwt", "tls"],
  adds="Redirects and token requests over HTTPS; then an `Authorization: Bearer <token>` header on each API call.",
  costs="Several parties and redirects to get right; bearer tokens work for whoever holds them unless sender-constrained (DPoP, RFC 9449; mTLS, RFC 8705).",
  not_when="Your own backend calling a provider with its own account (an API key or workload identity is simpler).",
  replaces="Password sharing and OAuth 1.0's request signing.",
  competes="API keys for simple server-to-provider calls; cloud IAM inside one cloud.",
  meet=["Connecting a remote MCP server: the client discovers the authorization server from the server's protected resource metadata (RFC 9728) and runs the code flow with PKCE.",
        "Command line tools that log you in by opening a browser on a loopback redirect, or by showing a device code.",
        "An agent acting for a user in Gmail, Slack or GitHub."],
  fail=dict(symptom="`invalid_grant` on refresh, so the agent is logged out overnight; or a token accepted by a service it was not meant for.",
            cause="Refresh tokens rotated or expired (public clients must rotate them under OAuth 2.1); or no audience check, so a token for service A is replayed at service B. Resource indicators (RFC 8707) bind a token to one audience.",
            see="Decode the access token if it is a JWT and check `aud`, `exp`, `scope`; read the authorization server metadata at `/.well-known/oauth-authorization-server` (RFC 8414)."),
  wire=["mcpprm"],
  wire_note="A real remote MCP server's protected resource metadata (RFC 9728): it names the authorization server a client must use and how to send the token.",
  srcs=[("draft", "draft-ietf-oauth-v2-1"), ("rfc", 6749), ("rfc", 6750), ("rfc", 7636), ("rfc", 8628), ("rfc", 9700), ("rfc", 9728), ("rfc", 8707), ("rfc", 8414), ("rfc", 9449), ("rfc", 10017),
        ("OAuth 2.1 draft-16 §10: differences from OAuth 2.0", "https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-16.txt")],
  versions=[("rfc", 6749, "OAuth 2.0"), ("rfc", 7636, "PKCE"), ("rfc", 8628, "Device authorization grant"), ("rfc", 9700, "OAuth 2.0 security BCP"),
            ("rfc", 9728, "Protected resource metadata"), ("rfc", 10017, "OAuth for browser-based apps BCP"), ("draft", "draft-ietf-oauth-v2-1", "OAuth 2.1 draft revision 16")]),

 dict(id="oidc", name="OIDC", full="OpenID Connect", group="auth", year=2014, body="OpenID Foundation",
  cur="OpenID Connect Core 1.0 incorporating errata set 2 (15 December 2023); first final February 2014", status="Final specification",
  plain="Login on top of OAuth: besides the access token, the provider returns an **ID token**, a signed statement of who just logged in and when.",
  problem="OAuth says what an app may do, not who the user is; every provider used to invent its own 'get user' call.",
  how="Add the `openid` scope to an OAuth code flow; the token response includes an ID token (a JWT with `iss`, `sub`, `aud`, `exp`, `nonce`). Clients find endpoints and signing keys from `/.well-known/openid-configuration` and the `jwks_uri` it points to.",
  runs_on=["oauth"], uses=["jwt"],
  adds="An ID token (a signed JWT) in the token response.",
  costs="All of OAuth's moving parts plus token validation (signature, issuer, audience, expiry, nonce).",
  not_when="Machine-to-machine calls with no user (client credentials or workload identity).",
  replaces="OpenID 2.0 and SAML for most new web and mobile logins.",
  competes="SAML in enterprise single sign-on.",
  meet=["'Sign in with Google' on your tool's dashboard.",
        "Cloud workload identity federation: a GitHub Actions job presents an OIDC token to AWS or GCP instead of a stored key.",
        "A2A Agent Cards can declare an `OpenIdConnectSecurityScheme`."],
  fail=dict(symptom="Login works locally and fails in production with `invalid audience` or `invalid issuer`.",
            cause="The ID token's `aud` is a different client id, or the issuer URL differs by a trailing slash or host; validation must match them exactly.",
            see="Fetch `/.well-known/openid-configuration` and compare `issuer` with the token's `iss`."),
  wire=["oidc", "jwks"],
  wire_note="Google's discovery document (first 420 bytes) and the start of its published signing keys, the keys a client uses to check an ID token offline.",
  srcs=[("OpenID Connect Core 1.0 incorporating errata set 2", "https://openid.net/specs/openid-connect-core-1_0.html"),
        ("GitHub docs: OpenID Connect in GitHub Actions", "https://docs.github.com/en/actions/concepts/security/openid-connect"),
        ("A2A v1.0.1 specification §4.5.5 OpenIdConnectSecurityScheme", A2A_SPEC)],
  versions=[("2014-02", "OpenID Connect Core 1.0 final", "https://openid.net/specs/openid-connect-core-1_0.html"), ("2023-12", "Core 1.0 errata set 2", "https://openid.net/specs/openid-connect-core-1_0.html")]),

 dict(id="jwt", name="JWT, JWS, JWK", full="JSON Web Token, JSON Web Signature, JSON Web Key", group="auth", year=2015, body="IETF (JOSE)",
  cur="RFC 7519, 7515, 7517, 7518 (May 2015); best practices RFC 8725 (2020), whose revision is in the RFC Editor queue", status="Proposed Standard; BCP",
  plain="A token you can check without calling anyone: three base64url pieces, `header.payload.signature`. Anyone can read the payload; only the issuer's key could have produced the signature.",
  problem="Let many services check a caller's identity and permissions locally, without a database lookup on every request.",
  how="The header names the algorithm (`RS256`, `ES256`, `HS256`) and key id (`kid`); the payload holds **claims** (`iss` issuer, `sub` subject, `aud` audience, `exp` expiry, `scope`). The issuer signs `header.payload` (JWS). Verifiers fetch the issuer's public keys as a JWK Set and check signature, issuer, audience and expiry.",
  runs_on=[], uses=[],
  adds="Usually a few hundred bytes to a kilobyte in an `Authorization` header.",
  costs="Cannot be revoked before `exp` without extra machinery; the payload is readable by anyone (never put secrets in it); validation mistakes are common.",
  not_when="You need instant revocation (use opaque tokens and introspection) or confidentiality of the claims.",
  replaces="Opaque session tokens that every service had to look up.",
  competes="Opaque tokens with introspection; PASETO; macaroons.",
  meet=["OAuth access tokens and OIDC ID tokens (RFC 9068 profiles JWT access tokens).",
        "Kubernetes service account tokens, mounted into pods and presented to cloud IAM.",
        "ACME signs every request to the CA as a JWS (RFC 8555 §6.2)."],
  fail=dict(symptom="A forged token is accepted.",
            cause="The verifier trusted the token's own `alg` (accepting `none`, or treating an RSA public key as an HMAC secret), or skipped the audience or issuer check (RFC 8725 §2 lists these attacks).",
            see="Decode the two first parts with base64 (as in the recording) and check what the verifier pins: algorithm, issuer, audience, key source."),
  wire=["jwt"],
  wire_note="A token made locally with a made-up secret: the header and payload decode to plain JSON, which is why a JWT must never carry secrets.",
  srcs=[("rfc", 7519), ("rfc", 7515), ("rfc", 7517), ("rfc", 7518), ("rfc", 8725, "§2"), ("draft", "draft-ietf-oauth-rfc8725bis"), ("rfc", 9068), ("rfc", 9901), ("rfc", 8555, "§6.2"),
        ("Kubernetes docs: service accounts (tokens are JSON Web Tokens)", "https://kubernetes.io/docs/concepts/security/service-accounts/")],
  versions=[("rfc", 7519, "JWT, JWS, JWK, JWA published"), ("rfc", 8725, "JWT best current practices"), ("rfc", 9068, "JWT profile for OAuth access tokens"), ("rfc", 9901, "Selective disclosure JWT (SD-JWT)")]),

 dict(id="apikey", name="API keys", full="API keys (static bearer secrets)", group="auth", year=None, body="No standard; each provider defines its own",
  cur="Provider conventions, e.g. Anthropic's `x-api-key` header; OpenAPI can describe them as an `apiKey` security scheme", status="Convention",
  plain="A long random secret that identifies your account; whoever sends it is you.",
  problem="The simplest way for a server program to authenticate to a provider.",
  how="The provider generates a key; you send it on every request in a header (`x-api-key`, or `Authorization: Bearer`). The provider looks it up, applies your limits and bills you.",
  runs_on=["http11"], uses=["tls"],
  adds="One header per request.",
  costs="Long-lived and all-powerful: if it leaks (a commit, a log line, a notebook output, an agent's context window) it works for the attacker until revoked.",
  not_when="End users acting for themselves (OAuth); workloads inside a cloud (IAM roles, workload identity).",
  replaces="Username and password for APIs.",
  competes="OAuth client credentials; short-lived workload tokens.",
  meet=["Every LLM provider SDK reads one from an environment variable.",
        "Agents that are handed a key in their tool configuration, where prompt injection can try to make them print it."],
  fail=dict(symptom="A surprise bill or a `401` after the provider auto-revokes a key found in a public repository.",
            cause="The key was committed or logged. Keep keys in a secrets manager, scope them per environment, and rotate.",
            see="The recording shows what the API returns without a key."),
  wire=["apikey"],
  wire_note="Without the header, the API refuses with an `authentication_error` naming the header it wants.",
  srcs=[("Anthropic API docs: authentication with the x-api-key header", "https://docs.claude.com/en/api/overview"),
        ("OpenAPI 3.2.0 specification: security scheme type apiKey", "https://spec.openapis.org/oas/v3.2.0.html")],
  versions=[]),

 dict(id="sigv4", name="SigV4", full="AWS Signature Version 4 (cloud request signing)", group="auth", year=None, body="AWS (proprietary, documented)",
  cur="SigV4, plus SigV4a for multi-region signing (AWS IAM documentation)", status="Vendor specification",
  plain="Instead of sending a secret, sign each request: an HMAC over the method, path, headers, body hash and time, with a key derived from your secret, the date, the region and the service.",
  problem="Authenticate every API call without ever sending the secret, so a captured request cannot be reused for long or altered.",
  how="Build a canonical request, hash it, derive a signing key from the secret plus date, region and service, and send the signature in `Authorization: AWS4-HMAC-SHA256 Credential=..., SignedHeaders=..., Signature=...` with `X-Amz-Date`. AWS recomputes it. Credentials usually come from a role (temporary), not a stored key.",
  runs_on=["http11"], uses=["tls"],
  adds="Two headers per request.",
  costs="Clock skew breaks signatures; anything that rewrites headers or the path in between breaks them too.",
  not_when="Outside AWS (other clouds have their own schemes; HTTP Message Signatures, RFC 9421, is the IETF's general version).",
  replaces="Earlier AWS signature versions.",
  competes="Bearer tokens (OAuth, JWT) and RFC 9421 HTTP message signatures.",
  meet=["Every boto3 call: S3 checkpoint uploads, Bedrock model invocations, SageMaker endpoints.",
        "IAM roles for service accounts on EKS, which turn a Kubernetes OIDC token into temporary AWS credentials."],
  fail=dict(symptom="`SignatureDoesNotMatch` or `RequestTimeTooSkewed`.",
            cause="The machine's clock is off, or a proxy changed a signed header or re-encoded the path.",
            see="Compare the client's clock with an NTP source; the recording shows the two headers botocore adds."),
  wire=["sigv4"],
  wire_note="Signed locally by botocore with AWS's documented example credentials (`AKIDEXAMPLE`); nothing was sent.",
  srcs=[("AWS IAM docs: AWS Signature Version 4 for API requests (SigV4 and SigV4a)", "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv.html"), ("rfc", 9421),
        ("Amazon EKS docs: IAM roles for service accounts", "https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html")],
  versions=[("rfc", 9421, "HTTP Message Signatures (IETF)")]),

 dict(id="mcp", name="MCP", full="Model Context Protocol", group="agent", year=2024, body="Anthropic (November 2024); Agentic AI Foundation under the Linux Foundation since 9 December 2025",
  cur="Specification 2026-07-28 (released 28 July 2026)", status="Open specification, dated revisions",
  plain="A standard plug between an AI application and the tools and data it uses: a server written once (GitHub, a database, your internal API) works in every MCP-speaking app.",
  problem="Every agent harness used to need its own integration for every tool.",
  how="A **host** (the app) runs a **client** per **server**. Messages are JSON-RPC 2.0. Servers expose **tools** (functions the model may call), **resources** (data to read) and **prompts**. Two transports: **stdio** (the host starts the server as a subprocess and talks over its stdin and stdout) and **Streamable HTTP** (POSTs to one endpoint, answered with JSON or an SSE stream). Remote servers act as OAuth resource servers: clients discover the authorization server via protected resource metadata (RFC 9728) and must request audience-bound tokens; passing a client's token through to another service is forbidden. The 2026-07-28 revision removed the initialize handshake and sessions (each request carries its protocol version), added `server/discover`, moved tasks into an extension, and deprecated Roots, Sampling, Logging and Dynamic Client Registration (in favour of Client ID Metadata Documents).",
  runs_on=["jsonrpc", "sse"], uses=["oauth"],
  adds="JSON-RPC messages; on HTTP, `Mcp-Method` and `Mcp-Name` headers (2026-07-28).",
  costs="Every tool result is untrusted text entering the model's context: the main prompt-injection surface. A server with broad credentials acting for many users is a confused-deputy risk.",
  not_when="Agent-to-agent delegation between organisations (A2A); a single fixed integration where a direct API call is simpler.",
  replaces="Per-harness plugin and function-calling glue.",
  competes="Vendor tool and plugin formats; it is complemented by A2A rather than competing with it.",
  meet=["Agent harnesses such as Claude Code connecting to local (stdio) and remote (HTTP) servers.",
        "Writing a server over your team's internal API so every agent can use it.",
        "UCP merchants expose their shopping service over MCP (the UCP recording shows `\"transport\":\"mcp\"`)."],
  fail=dict(symptom="The agent follows instructions hidden in a web page, issue or document a tool returned, and uses another tool to leak data.",
            cause="Tool output is treated as trusted input (prompt injection through a tool surface). Mitigations: least-privilege tokens per server, human approval for irreversible actions, never passing tokens through.",
            see="Log every tool call and result; the recording shows a real server's first answer, including the `instructions` text it injects into the model's context."),
  wire=["mcp"],
  wire_note="A real public MCP server (DeepWiki) answered `initialize` (protocol 2025-11-25) as one SSE event on Streamable HTTP. Note the `instructions` field: text the server asks the host to put in front of the model. Under 2026-07-28 a client would call `server/discover` instead.",
  srcs=[("Anthropic: Introducing the Model Context Protocol (25 November 2024)", "https://www.anthropic.com/news/model-context-protocol"),
        ("Anthropic: Donating MCP and establishing the Agentic AI Foundation (9 December 2025)", "https://www.anthropic.com/news/donating-the-model-context-protocol-and-establishing-of-the-agentic-ai-foundation"),
        ("MCP specification 2026-07-28", MCP_SPEC), ("MCP 2026-07-28 changelog (key changes)", MCP_CHANGELOG),
        ("MCP blog: The 2026-07-28 specification (28 July 2026)", "https://blog.modelcontextprotocol.io/"),
        ("MCP 2026-07-28 authorization: security considerations (OAuth 2.1, RFC 8707, token passthrough)", "https://modelcontextprotocol.io/specification/2026-07-28/basic/authorization/security-considerations"),
        ("MCP schema versions on GitHub", "https://github.com/modelcontextprotocol/modelcontextprotocol/tree/main/schema")],
  versions=[("2024-11", "MCP 2024-11-05 (first revision)", "https://modelcontextprotocol.io/specification/2024-11-05"),
            ("2025-03", "MCP 2025-03-26: Streamable HTTP replaces HTTP+SSE", MCP_CHANGELOG),
            ("2025-06", "MCP 2025-06-18", "https://modelcontextprotocol.io/specification/2025-06-18"),
            ("2025-11", "MCP 2025-11-25", "https://modelcontextprotocol.io/specification/2025-11-25"),
            ("2025-12", "MCP donated to the Agentic AI Foundation (Linux Foundation)", "https://www.anthropic.com/news/donating-the-model-context-protocol-and-establishing-of-the-agentic-ai-foundation"),
            ("2026-07", "MCP 2026-07-28: stateless core, extensions", MCP_CHANGELOG)]),

 dict(id="a2a", name="A2A", full="Agent2Agent protocol", group="agent", year=2025, body="Google (April 2025); Linux Foundation project since 23 June 2025",
  cur="v1.0.1 (28 May 2026); v1.0.0 released 12 March 2026", status="Open specification, semver releases",
  plain="A way for one agent to hand a task to another agent it cannot see inside (another team's, another company's), follow the task's progress and get the results back.",
  problem="Delegation between opaque agents: neither side exposes its tools, prompts or memory, only what it can do.",
  how="An agent publishes an **Agent Card** (JSON at `/.well-known/agent-card.json`) with its skills, endpoints, supported bindings and security schemes. A client sends a message; the work becomes a **task** with states (submitted, working, input-required, auth-required, completed, failed, canceled, rejected). Updates arrive by streaming (SSE), polling or push notifications (webhooks). v1.0 separates the protocol from three bindings: JSON-RPC 2.0, gRPC, and HTTP+JSON/REST; clients send an `A2A-Version` header.",
  runs_on=["jsonrpc", "grpc", "rest"], uses=["sse", "oauth", "oidc", "mtls"],
  adds="Agent Card discovery plus task messages in the chosen binding.",
  costs="Another trust boundary: the remote agent's output is untrusted input to yours; authentication must be agreed per agent.",
  not_when="Giving one agent tools or data (MCP).",
  replaces="IBM's Agent Communication Protocol (ACP), which joined A2A under the Linux Foundation (its archived repository says so).",
  competes="Bespoke agent APIs; it complements MCP (agent-to-tool) rather than replacing it.",
  meet=["A planner agent in your company delegating to a vendor's research agent.",
        "UCP lists A2A among the transports it supports for agentic commerce."],
  fail=dict(symptom="Tasks hang in `working` forever after a client restart.",
            cause="The client relied on one SSE stream and lost it; it must resubscribe to the task or poll `GetTask`.",
            see="`curl https://agent.example/.well-known/agent-card.json` shows the bindings and auth an agent supports."),
  wire=[], wire_note="Not recorded: no stable public A2A agent was found to query. The command shown fetches any agent's card.",
  srcs=[("Google Developers Blog: A2A, a new era of agent interoperability (9 April 2025)", "https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/"),
        ("Linux Foundation: launch of the Agent2Agent protocol project (23 June 2025)", "https://www.linuxfoundation.org/press/linux-foundation-launches-the-agent2agent-protocol-project-to-enable-secure-intelligent-communication-between-ai-agents"),
        ("A2A v1.0.1 specification (§4.1.3 task states, §8.2 discovery, §9 to §11 bindings, §3.6 versioning)", A2A_SPEC),
        ("gh", "a2aproject/A2A", "v1.0.0"), ("gh", "a2aproject/A2A", "v1.0.1"),
        ("IBM ACP repository: 'ACP is now part of A2A under the Linux Foundation' (archived)", "https://github.com/i-am-bee/acp")],
  versions=[("2025-04", "A2A announced by Google", "https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/"),
            ("2025-06", "A2A becomes a Linux Foundation project", "https://www.linuxfoundation.org/press/linux-foundation-launches-the-agent2agent-protocol-project-to-enable-secure-intelligent-communication-between-ai-agents"),
            ("gh", "a2aproject/A2A", "v0.3.0", "A2A v0.3.0"), ("gh", "a2aproject/A2A", "v1.0.0", "A2A v1.0.0"), ("gh", "a2aproject/A2A", "v1.0.1", "A2A v1.0.1")]),

 dict(id="ucp", name="UCP", full="Universal Commerce Protocol (agent to merchant)", group="agent", year=2026, body="Co-developed by Shopify and Google; open source (Apache-2.0)",
  cur="Version 2026-08-25", status="Open specification, dated versions",
  plain="A standard for an agent to shop at any merchant: discover what the merchant supports, negotiate, check out, and hand the buyer to the merchant's own page when the agent cannot finish.",
  problem="Agents buying things need one way to talk to millions of merchants, each with different payment, fulfilment and policy rules.",
  how="Merchants and agents publish capability profiles (merchants at `/.well-known/ucp`); negotiation is the intersection of the two. Capabilities (Catalog, Checkout, Orders) and extensions version independently; extensions use reverse-domain names (`com.loyaltyprovider.points`) so nobody needs central approval. A checkout moves through `incomplete`, `requires_escalation` and `ready_for_complete`; when a human must finish, the Embedded Checkout Protocol opens a JSON-RPC 2.0 channel to the merchant's page. Transports: REST, JSON-RPC, MCP and A2A, with payments through AP2.",
  runs_on=["rest", "jsonrpc", "mcp"], uses=["oauth", "a2a"],
  adds="A discovery document and checkout messages in the chosen transport.",
  costs="Irreversible actions with money; the agent acts for a buyer at a merchant it does not control.",
  not_when="Anything that is not a transaction with a business.",
  replaces="Per-merchant scraping and bespoke checkout integrations.",
  competes="The Agentic Commerce Protocol (ACP) maintained by OpenAI and Stripe; Google's Agent Payments Protocol (AP2) covers payment mandates and is used by UCP.",
  meet=["Building a shopping or booking agent; the recording shows a real Shopify store's profile offering its shopping service over MCP.",
        "The design ideas carry over: well-known discovery, profile intersection, an explicit 'a human must finish this' state."],
  fail=dict(symptom="An agent believes a purchase is complete when the merchant still needs the buyer.",
            cause="The client ignored `requires_escalation` and its `continue_url`.",
            see="`curl -s https://store.example/.well-known/ucp` shows versions, services and transports."),
  wire=["ucp"],
  wire_note="A real merchant profile (first 640 bytes): current version 2026-08-25, older supported versions, and the shopping service offered over MCP and an embedded transport.",
  srcs=[("UCP site (co-developers, transports, capabilities)", "https://ucp.dev/"),
        ("Shopify Engineering: Building the Universal Commerce Protocol", "https://shopify.engineering/UCP"),
        ("gh", "Universal-Commerce-Protocol/ucp", "v2026-01-11"), ("gh", "Universal-Commerce-Protocol/ucp", "v2026-08-25"),
        ("Agentic Commerce Protocol repository (maintained by OpenAI and Stripe)", "https://github.com/agentic-commerce-protocol/agentic-commerce-protocol"),
        ("Agent Payments Protocol (AP2) repository", "https://github.com/google-agentic-commerce/AP2")],
  versions=[("gh", "Universal-Commerce-Protocol/ucp", "v2026-01-11", "UCP first tagged version"), ("gh", "Universal-Commerce-Protocol/ucp", "v2026-08-25", "UCP 2026-08-25")]),

 dict(id="mhs", name="MHS", full="Model Hardware Standard (agent to instrument), research preview", group="agent", year=2026, body="Anthropic (with HHMI Janelia); research preview",
  cur="Research preview opened 27 August 2026; not yet open source", status="Research preview",
  plain="A shared specification for agents to operate physical lab and manufacturing equipment (liquid handlers, plate readers, robotic arms, microscopes) through one interface.",
  problem="Every instrument has its own driver and software; wiring them together for automation takes weeks to months.",
  how="Devices with a programmable interface are described to the agent, which controls them through three mechanisms: MCP, a command line interface and code APIs. It is model-agnostic and reachable from any harness over standard protocols such as MCP, so it sits above MCP as a device layer.",
  runs_on=["mcp"], uses=[],
  adds="Device descriptions and commands; transport via MCP, CLI or code.",
  costs="Physical, irreversible actions: errors are spilt reagents and damaged equipment, not a wrong message.",
  not_when="Anything you cannot supervise; it is a research preview with limited access.",
  replaces="Bespoke per-instrument integrations.",
  competes="Lab automation vendors' own orchestration software.",
  meet=["Rarely, unless you work in lab automation; it is in the atlas as a dated example of where agent protocols are heading."],
  fail=dict(symptom="Not documented publicly yet.",
            cause="Anthropic reports partners had to guide the model to treat foaming in samples as a physical failure, not a software bug.",
            see="No public command; access is by application."),
  wire=[], wire_note="Not recorded: no public endpoint.",
  srcs=[("Anthropic: Previewing the Model Hardware Standard (27 August 2026)", "https://www.anthropic.com/news/model-hardware-standard-research-preview")],
  versions=[("2026-08", "Model Hardware Standard research preview", "https://www.anthropic.com/news/model-hardware-standard-research-preview")]),

 # GPU fabric: one line each, linking out (Distributed Training, Training Infrastructure, Topic: hardware)
 dict(id="rdma", name="RDMA", full="Remote direct memory access", group="fabric", brief=True, year=None, body="InfiniBand Trade Association (verbs); vendors",
  plain="One machine's network card reads and writes another machine's memory directly, without the kernel's network stack copying the data on either side: the reason training traffic avoids TCP when it can.",
  runs_on=[], uses=[], srcs=[("NCCL documentation: environment variables (IB and socket transports)", "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html")]),
 dict(id="roce", name="RoCEv2", full="RDMA over Converged Ethernet, version 2", group="fabric", brief=True, year=2014, body="InfiniBand Trade Association",
  plain="RDMA carried in UDP datagrams to port 4791 over routed Ethernet and IP, so RDMA can use ordinary data-centre switches; fabric tuning is on the Training Infrastructure page.",
  runs_on=["udp"], uses=["rdma"],
  srcs=[("IANA: 4791/udp IP Routable RoCE, InfiniBand Trade Association, 2014-10-17", "https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=4791")]),
 dict(id="ib", name="InfiniBand", full="InfiniBand", group="fabric", brief=True, year=None, body="InfiniBand Trade Association",
  plain="A separate network technology built for RDMA, with its own adapters and switches, common in large GPU training clusters.",
  runs_on=[], uses=["rdma"], srcs=[("InfiniBand Trade Association", "https://www.infinibandta.org/")]),
 dict(id="nccl", name="NCCL", full="NVIDIA Collective Communications Library", group="fabric", brief=True, year=None, body="NVIDIA (open source)",
  plain="The library that runs all-reduce and the other collectives between GPUs over NVLink, InfiniBand, RoCE or plain TCP sockets; on AWS its socket transport defaults to 2 threads with 8 sockets each per connection (NCCL docs). Latest release v2.32.3-1 (17 September 2026).",
  runs_on=["tcp", "ib", "roce"], uses=[],
  srcs=[("NCCL docs: NCCL_SOCKET_NTHREADS and NCCL_NSOCKS_PERTHREAD (AWS defaults 2 and 8; product at most 64)", "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html"),
        ("gh", "NVIDIA/nccl", "v2.32.3-1")]),
]

FABRIC_LINKS = [("Distributed Training", "3c65c17b0d0d8103a916c4824abbd82e"),
                ("Training Infrastructure", "3c65c17b0d0d81c9b2cac997583bf572"),
                ("Topic: hardware", "3c65c17b0d0d8118beeefaed56da6f8e")]
