"""Atlas entries, part B: HTTP versions, streaming and events, service API styles. Conventions as in data_a.py."""

B = [
 dict(id="http11", name="HTTP/1.1", full="Hypertext Transfer Protocol 1.1", group="http", year=1997, body="IETF",
  cur="RFC 9110 (semantics) and RFC 9112 (HTTP/1.1 message syntax), June 2022", status="Internet Standard",
  plain="A request and a response written as text: a method and path (`POST /v1/messages`), header lines, a blank line, a body. One request at a time per connection.",
  problem="A uniform way for any client to ask any server for something, through caches and proxies.",
  how="The **semantics** (methods such as GET and POST, status codes such as 200, 401, 429, headers, caching) live in RFC 9110 and are shared by every HTTP version. HTTP/1.1's wire format (RFC 9112) is text over one TCP or TLS connection; keep-alive reuses the connection, but responses come back strictly in order, so clients open several connections to the same host to work in parallel. Bodies of unknown length are sent in **chunks** (`Transfer-Encoding: chunked`), which is how a streamed answer travels on HTTP/1.1.",
  runs_on=["tls", "tcp"], uses=[],
  adds="Text headers on every request (often hundreds of bytes), repeated in full each time.",
  costs="One outstanding request per connection; header bytes repeated on every call.",
  not_when="Many small parallel calls to the same server (HTTP/2 multiplexes them on one connection).",
  replaces="HTTP/1.0 (one request per connection).",
  competes="HTTP/2 and HTTP/3 carry the same semantics more efficiently.",
  meet=["`curl` without flags to a plain `http://` URL, and many internal health checks.",
        "Proxies and load balancers that speak only HTTP/1.1 to the backend even when the client used HTTP/2.",
        "Streaming LLM answers relayed through older proxies as chunked responses."],
  fail=dict(symptom="A streamed answer arrives all at once at the end, or is cut after exactly 60 s.",
            cause="A proxy buffers the response before forwarding it (nginx `proxy_buffering` is on by default), or an idle or read timeout on a proxy hop is shorter than the generation. RFC 10036 (August 2026) adds an `Incremental` header that asks intermediaries to forward a message as it arrives.",
            see="`curl -N -v` against each hop in turn shows which one buffers or cuts."),
  wire=["http11"],
  wire_note="A real request to the API without a key: the request lines (`>`) and the response headers (`<`), with Cloudflare's own headers filtered out. `Transfer-Encoding: chunked` and `Connection: keep-alive` are HTTP/1.1 at work; the `401` is the API key check (see API keys).",
  srcs=[("rfc", 9110), ("rfc", 9112), ("rfc", 2616), ("rfc", 10036),
        ("nginx: proxy_buffering (default on)", "https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering")],
  versions=[("rfc", 2616, "HTTP/1.1 (the long-lived 1999 text)"), ("rfc", 9112, "HTTP/1.1 respecified; semantics split into RFC 9110"), ("rfc", 10036, "Incremental forwarding header")]),

 dict(id="http2", name="HTTP/2", full="Hypertext Transfer Protocol version 2", group="http", year=2015, body="IETF (from Google's SPDY)",
  cur="RFC 9113 (June 2022), which obsoletes RFC 7540 (May 2015); header compression HPACK, RFC 7541", status="Proposed Standard",
  plain="The same requests and responses, cut into binary **frames** and interleaved on one connection, so many requests are in flight at once.",
  problem="HTTP/1.1 needs many connections for parallelism and resends the same headers every time.",
  how="One TCP plus TLS connection (chosen with ALPN `h2`) carries many numbered **streams**, one per request. Each stream's headers and data are sent as frames that can interleave. HPACK compresses headers against a table both sides remember. Flow control is per stream and per connection. Plain-text HTTP/2 (`h2c`, no TLS) exists and is common inside clusters for gRPC.",
  runs_on=["tls", "tcp"], uses=[],
  adds="A 9-byte frame header per frame; headers HPACK-compressed.",
  costs="Still on TCP: one lost packet stalls every stream on the connection (TCP head-of-line blocking). One long-lived connection defeats connection-level (L4) load balancing.",
  not_when="Lossy mobile links with many parallel streams (HTTP/3 does better).",
  replaces="HTTP/1.1 for most browser and API traffic.",
  competes="HTTP/3.",
  meet=["Calls to most LLM APIs from modern clients: the recording shows curl and the API agreeing on `h2` through ALPN.",
        "Every gRPC call (Triton on port 8001, OTLP on 4317, Ray Serve's gRPC proxy).",
        "Python's `httpx` with `http2=True`; `requests` speaks only HTTP/1.1."],
  fail=dict(symptom="One backend pod is at 100 percent while the others idle, behind a load balancer.",
            cause="A long-lived HTTP/2 (often gRPC) connection is balanced once, when it opens, by an L4 balancer; every later request rides the same connection to the same pod.",
            see="Per-pod request counts; the fix is an L7 balancer that spreads streams, or client-side balancing."),
  wire=["http2"],
  wire_note="curl offered `h2` and `http/1.1` in the TLS handshake, the server picked `h2`, and the request became stream 1 with its pseudo-headers (`:method`, `:path`, ...).",
  srcs=[("rfc", 9113), ("rfc", 7540), ("rfc", 7541), ("rfc", 7301),
        ("gRPC blog: gRPC load balancing (L3/L4 versus L7)", "https://grpc.io/blog/grpc-load-balancing/")],
  versions=[("rfc", 7540, "HTTP/2 published"), ("rfc", 9113, "HTTP/2 respecified")]),

 dict(id="http3", name="HTTP/3", full="Hypertext Transfer Protocol version 3", group="http", year=2022, body="IETF",
  cur="RFC 9114 (June 2022); header compression QPACK, RFC 9204", status="Proposed Standard",
  plain="HTTP/2's idea (many streams on one connection) moved onto QUIC, so a lost packet only delays its own stream.",
  problem="HTTP/2 still stalls all streams on one TCP loss and pays a TCP plus TLS setup.",
  how="Each request is a QUIC stream; QPACK replaces HPACK because streams can arrive out of order. Servers advertise it with an `Alt-Svc` header or an HTTPS DNS record; clients race it against HTTP/2 and keep whichever works.",
  runs_on=["quic"], uses=[],
  adds="QUIC framing instead of TCP plus TLS records.",
  costs="UDP blocked on some networks; more CPU; fewer debugging tools.",
  not_when="Server-to-server inside a data centre, where HTTP/2 over TCP is simpler and as fast.",
  replaces="HTTP/2 on lossy, high-latency client links.",
  competes="HTTP/2.",
  meet=["Browsers and mobile apps talking to CDNs.",
        "Rarely in ML backends today: inference servers and gRPC use HTTP/2."],
  fail=dict(symptom="Intermittent slowness only on some networks.",
            cause="Clients try QUIC first, UDP is throttled, and they fall back to TCP after a delay.",
            see="`curl -sI https://host/ | grep -i alt-svc` shows the advertisement; `curl --http3-only` tests QUIC alone."),
  wire=["http3"],
  wire_note="`h3=\":443\"; ma=86400`: the server offers HTTP/3 on UDP 443 and asks the client to remember it for a day.",
  srcs=[("rfc", 9114), ("rfc", 9204), ("rfc", 9460)],
  versions=[("rfc", 9114, "HTTP/3 published")]),

 dict(id="ws", name="WebSockets", full="The WebSocket protocol", group="stream", year=2011, body="IETF (protocol), WHATWG (browser API)",
  cur="RFC 6455 (December 2011); over HTTP/2 RFC 8441 (2018), over HTTP/3 RFC 9220 (2022)", status="Proposed Standard",
  plain="An HTTP request that turns into a two-way pipe: after a short handshake, either side can send messages at any time until one closes it.",
  problem="Browsers had no way to receive data the server decides to send, or to send many small messages, without a new request each time.",
  how="The client sends an ordinary HTTP/1.1 GET with `Upgrade: websocket` and a random `Sec-WebSocket-Key`; the server answers `101 Switching Protocols` with `Sec-WebSocket-Accept`, a hash of that key with a fixed GUID (RFC 6455 §1.3), proving it understood. From then on both sides exchange **frames** (text, binary, ping, pong, close); frames from the client are masked.",
  runs_on=["http11", "tcp"], uses=[],
  adds="A 2 to 14 byte frame header per message (plus a 4-byte mask from clients).",
  costs="A long-lived stateful connection per client: load balancers, deploys and reconnects must handle it; no HTTP caching or per-message status codes.",
  not_when="The server only streams to the client (SSE is simpler and works through more proxies); occasional notifications to another service (webhooks).",
  replaces="Long polling and other Comet hacks for two-way browser traffic.",
  competes="SSE (one way), WebRTC (media, peer to peer), WebTransport (IETF draft over HTTP/3).",
  meet=["Realtime voice APIs: OpenAI's Realtime API WebSocket mode and Google's Gemini Live API both use WebSockets.",
        "Agent UIs that push tool progress and accept interruptions."],
  fail=dict(symptom="Connections drop every 60 s or after a deploy, and clients do not come back.",
            cause="A proxy's idle timeout closes quiet connections (send pings), and clients without reconnect-with-backoff logic stay disconnected.",
            see="`curl -si --http1.1 -H 'Connection: Upgrade' -H 'Upgrade: websocket' ...` shows whether the handshake reaches the server and gets a 101."),
  wire=["ws"],
  wire_note="The request used the sample key from RFC 6455 §1.3 (`dGhlIHNhbXBsZSBub25jZQ==`), and the live server returned exactly the accept value printed in the RFC, `s3pPLMBiTxaQ9kYGzzhZRbK+xOo=`.",
  srcs=[("rfc", 6455, "§1.3"), ("rfc", 8441), ("rfc", 9220), ("draft", "draft-ietf-webtrans-http3"),
        ("OpenAI API docs: Realtime API with WebSockets", "https://platform.openai.com/docs/guides/realtime-websocket"),
        ("Google: Gemini Live API (stateful WebSocket connection)", "https://ai.google.dev/gemini-api/docs/live-api")],
  versions=[("rfc", 6455, "WebSocket protocol"), ("rfc", 8441, "WebSockets over HTTP/2"), ("rfc", 9220, "WebSockets over HTTP/3")]),

 dict(id="sse", name="SSE", full="Server-sent events (EventSource, text/event-stream)", group="stream", year=2015, body="WHATWG (HTML Living Standard §9.2); W3C Recommendation 2015",
  cur="HTML Living Standard §9.2, last updated 5 October 2026", status="Living Standard",
  plain="An HTTP response that never finishes: the server keeps writing small text events (`data: ...` followed by a blank line) and the client handles each as it arrives.",
  problem="Push a stream of updates from server to client over plain HTTP, through ordinary proxies, with automatic reconnection.",
  how="The response has `Content-Type: text/event-stream`. Each event is a few lines (`event:`, `data:`, `id:`, `retry:`) ended by a blank line; lines starting with `:` are comments, used as keep-alives. The browser's `EventSource` reconnects on its own and sends `Last-Event-ID`. LLM APIs use the format but not EventSource: the request is a POST with a JSON body (`\"stream\": true`) and the SDK parses the events.",
  runs_on=["http2", "http11", "http3"], uses=[],
  adds="A few bytes of `data:` framing per event, as text.",
  costs="One direction only; text only (binary must be encoded); every proxy on the path must forward bytes as they come instead of buffering.",
  not_when="The client must also stream to the server (voice): use WebSockets.",
  replaces="Long polling for server-to-client streams.",
  competes="WebSockets; gRPC server streaming between services.",
  meet=["Every streaming LLM call: Anthropic's Messages API sends named events (`message_start`, `content_block_delta`, `message_stop`).",
        "vLLM's OpenAI-compatible server (`vllm serve`, port 8000) with `stream=true`.",
        "MCP's Streamable HTTP transport and A2A's JSON-RPC and REST bindings stream with SSE."],
  fail=dict(symptom="Tokens arrive in bursts, or all at the end, or the stream dies at a round number of seconds.",
            cause="A proxy, CDN or compression layer buffers the stream, or an idle timeout fires during a long pause (a model thinking before its first token). The HTML standard itself suggests a comment line about every 15 seconds against such proxies.",
            see="`curl -N` (no buffering) straight at the server, then through each proxy."),
  wire=["sse"],
  wire_note="A local stand-in server on 127.0.0.1 streaming three token events, a keep-alive comment and a done event. The real API's version of this exchange is recorded in the On the wire tab.",
  srcs=[("WHATWG HTML Living Standard §9.2 Server-sent events (authoring notes §9.2.7: comment every 15 seconds)", "https://html.spec.whatwg.org/multipage/server-sent-events.html"),
        ("W3C Server-Sent Events Recommendation, 3 February 2015", "https://www.w3.org/TR/2015/REC-eventsource-20150203/"),
        ("Anthropic docs: streaming Messages with server-sent events", "https://docs.claude.com/en/docs/build-with-claude/streaming"),
        ("vLLM docs: OpenAI-compatible server", "https://github.com/vllm-project/vllm/blob/main/docs/serving/online_serving/openai_compatible_server.md")],
  versions=[("2015-02", "Server-Sent Events becomes a W3C Recommendation", "https://www.w3.org/TR/2015/REC-eventsource-20150203/")]),

 dict(id="webhook", name="Webhooks", full="Webhooks, and the Standard Webhooks specification", group="stream", year=2025, body="Convention; Standard Webhooks (open specification, v1.0.0 December 2025)",
  cur="Standard Webhooks v1.0.2 (February 2026)", status="Community specification",
  plain="A reverse API call: instead of you polling 'is my batch job done?', the provider sends an HTTP POST to a URL you registered when something happens.",
  problem="Tell another system about an event later, without it polling and without a connection held open.",
  how="The sender POSTs a JSON event to your URL. Standard Webhooks fixes the details: headers `webhook-id`, `webhook-timestamp`, `webhook-signature`; the signature is HMAC-SHA256 over `id.timestamp.body` with a shared secret (`whsec_...`), so you can check it came from the sender and was not replayed. Delivery is retried on any non-2xx answer, with exponential backoff over days.",
  runs_on=["http11", "http2"], uses=[],
  adds="Three headers and a signature.",
  costs="At-least-once and unordered: you will see duplicates and must deduplicate on the event id; you need a public HTTPS endpoint.",
  not_when="The caller is waiting for the answer now (return it, or stream it).",
  replaces="Polling a status endpoint.",
  competes="Queues and event buses between your own services; polling for simple cases.",
  meet=["Batch inference and fine-tuning jobs that notify on completion; A2A push notifications are webhooks to a URL the client registers.",
        "Payment and CI providers calling your service."],
  fail=dict(symptom="Signature verification fails on every webhook although the secret is right.",
            cause="The handler parsed the JSON and re-serialised it before verifying; the signature covers the raw bytes, and any change of spacing or key order breaks it.",
            see="Verify against the raw request body; the recording shows the same body verifying and its re-serialised copy failing."),
  wire=["webhook"],
  wire_note="Computed locally with a made-up secret, following the spec's signing scheme and its example message id and timestamp.",
  srcs=[("Standard Webhooks specification", "https://github.com/standard-webhooks/standard-webhooks/blob/main/spec/standard-webhooks.md"),
        ("gh", "standard-webhooks/standard-webhooks", "v1.0.0"), ("gh", "standard-webhooks/standard-webhooks", "v1.0.2"),
        ("A2A v1.0.1 specification §3.5.3 push notification delivery", "https://github.com/a2aproject/A2A/blob/v1.0.1/docs/specification.md")],
  versions=[("gh", "standard-webhooks/standard-webhooks", "v1.0.0", "Standard Webhooks 1.0")]),

 dict(id="rest", name="REST and OpenAPI", full="REST over HTTP, described with OpenAPI", group="api", year=2000, body="Fielding's dissertation (2000); OpenAPI Initiative (Linux Foundation)",
  cur="OpenAPI 3.2.1 (10 September 2026); error bodies RFC 9457", status="OpenAPI: published specification",
  plain="Resources with URLs (`/v1/models`, `/v1/messages`) acted on with HTTP's own verbs and status codes, usually with JSON bodies. OpenAPI is a machine-readable description of such an API, from which docs, clients and tests are generated.",
  problem="An API any client can call with any HTTP library, that caches, proxies and browsers already understand.",
  how="GET reads, POST creates or triggers, PUT and PATCH update, DELETE removes; status codes carry the outcome (200, 201, 400, 401, 404, 409, 429, 5xx); retries are safe for idempotent methods, and an idempotency key makes a POST safe to retry. Errors can follow RFC 9457 problem details. An OpenAPI document lists paths, parameters, schemas and security schemes.",
  runs_on=["http11", "http2"], uses=["jwt"],
  adds="Nothing below HTTP: it is a way of using HTTP.",
  costs="Text JSON is larger and slower to parse than protobuf; no built-in streaming (add SSE) or deadlines.",
  not_when="High-volume internal calls between your own services (gRPC); clients that need many shapes of one data graph (GraphQL).",
  replaces="SOAP and ad hoc RPC over HTTP for public APIs.",
  competes="gRPC, GraphQL, JSON-RPC.",
  meet=["Every public LLM API is REST plus SSE; the recordings show `GET /v1/models` answering `401` with a JSON error.",
        "FastAPI services, which generate an OpenAPI document automatically.",
        "Triton's HTTP port 8000 (the KServe v2 inference protocol)."],
  fail=dict(symptom="A retried POST creates two charges or two jobs.",
            cause="POST is not idempotent; a timeout after the server acted makes the client retry. Send an idempotency key and have the server deduplicate.",
            see="Server logs keyed by request id; the API returns a `request-id` header for this."),
  wire=["apikey"],
  wire_note="A REST error answer: JSON with a type and message, plus a request id for support.",
  srcs=[("Fielding (2000), Architectural Styles and the Design of Network-based Software Architectures", "https://ics.uci.edu/~fielding/pubs/dissertation/top.htm"),
        ("gh", "OAI/OpenAPI-Specification", "3.2.0"), ("gh", "OAI/OpenAPI-Specification", "3.2.1"), ("rfc", 9457), ("rfc", 9110, "§9.2.2"), ("rfc", 10008),
        ("Triton docs: HTTP/REST and GRPC protocols (KServe v2)", "https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/inference_protocols.html")],
  versions=[("2000-01", "Fielding's dissertation defines REST", "https://ics.uci.edu/~fielding/pubs/dissertation/top.htm"),
            ("gh", "OAI/OpenAPI-Specification", "3.2.0", "OpenAPI 3.2.0"), ("rfc", 9457, "Problem Details for HTTP APIs"), ("rfc", 10008, "HTTP QUERY method")]),

 dict(id="grpc", name="gRPC and protobuf", full="gRPC remote procedure calls with Protocol Buffers", group="api", year=2015, body="Google, then CNCF",
  cur="gRPC 1.84.0 (11 September 2026); protobuf v36.2 (17 September 2026)", status="Open source; wire format in PROTOCOL-HTTP2.md",
  plain="Call a function on another machine as if it were local: the service and its messages are declared in a `.proto` file, code is generated for each language, and calls travel as compact binary messages over HTTP/2.",
  problem="Fast, typed, streaming calls between your own services, with timeouts that propagate.",
  how="Each call is an HTTP/2 POST to `/package.Service/Method` with `content-type: application/grpc` and `te: trailers`. Messages are protobuf bytes, each prefixed by 5 bytes (a compression flag and a 4-byte length). The status comes in HTTP **trailers** (`grpc-status`, headers sent after the body). Four shapes: unary, server streaming, client streaming, bidirectional. A **deadline** set by the caller travels as `grpc-timeout` and is meant to be propagated so downstream work stops when nobody is waiting; by default gRPC sets none.",
  runs_on=["http2"], uses=["tls"],
  adds="5 bytes per message plus HTTP/2 framing; protobuf encodes fields by number, so payloads are small.",
  costs="Browsers cannot call it directly (needs gRPC-Web or a gateway); binary payloads are harder to inspect; L4 load balancers pin connections.",
  not_when="Public APIs for arbitrary clients (REST); browsers.",
  replaces="Google's internal Stubby; Thrift and hand-rolled RPC in many shops.",
  competes="REST and JSON over HTTP; Connect; JSON-RPC.",
  meet=["Triton's gRPC port 8001; OTLP traces and metrics to an OpenTelemetry collector on port 4317.",
        "Ray Serve's gRPC proxy.",
        "A2A's gRPC binding (A2A v1.0 §10)."],
  fail=dict(symptom="`DEADLINE_EXCEEDED` deep in a call chain, or GPU work that keeps running after the user gave up.",
            cause="No deadline was set (calls wait forever), or deadlines were not propagated to downstream calls.",
            see="Set a deadline on every call; inspect headers with `grpcurl -v` or curl with `--http2-prior-knowledge` as in the recording."),
  wire=["grpc"],
  wire_note="A real gRPC health check against a local server, made with curl: the request is 5 bytes (flag 0, length 0, an empty message). The answer's last bytes `08 01` are protobuf for field 1 = 1, which is `SERVING`, and `grpc-status: 0` arrives after the body as a trailer.",
  srcs=[("gRPC over HTTP/2 wire specification (PROTOCOL-HTTP2.md)", "https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md"),
        ("gRPC: About (Stubby; open sourced from March 2015)", "https://grpc.io/about/"),
        ("gRPC guide: deadlines (no deadline by default; propagation)", "https://grpc.io/docs/guides/deadlines/"),
        ("gh", "grpc/grpc", "v1.84.0"), ("gh", "protocolbuffers/protobuf", "v36.2"),
        ("OpenTelemetry OTLP specification (gRPC port 4317, HTTP port 4318)", "https://opentelemetry.io/docs/specs/otlp/"),
        ("Triton quickstart (HTTP 8000, gRPC 8001, metrics 8002)", "https://github.com/triton-inference-server/server/blob/main/docs/getting_started/quickstart.md"),
        ("Ray Serve: set up a gRPC service", "https://docs.ray.io/en/latest/serve/advanced-guides/grpc-guide.html")],
  versions=[("2015-03", "Google starts building gRPC as open source", "https://grpc.io/about/"), ("gh", "grpc/grpc", "v1.84.0", "gRPC 1.84.0")]),

 dict(id="graphql", name="GraphQL", full="GraphQL query language and API", group="api", year=2015, body="GraphQL Foundation (Linux Foundation); created at Facebook",
  cur="GraphQL specification, September 2025 edition", status="Published specification edition",
  plain="One endpoint where the client sends a query naming exactly the fields it wants, and gets back JSON of exactly that shape.",
  problem="Many different clients (web, mobile) need different slices of the same data, and REST forces either many calls or bloated responses.",
  how="The server publishes a typed schema. Clients POST a query (`{ country(code: \"FR\") { name capital } }`); resolvers fetch each field. Subscriptions add server push, usually over WebSockets.",
  runs_on=["http11", "http2"], uses=[],
  adds="A query document in the request body; responses are JSON with `data` and `errors`.",
  costs="HTTP caching does not apply to POSTed queries; one query can fan out into many backend calls (the N+1 problem); per-field authorisation.",
  not_when="ML serving and internal RPC; simple public APIs.",
  replaces="Ad hoc 'backend for frontend' REST endpoints.",
  competes="REST, gRPC.",
  meet=["Product and data APIs (GitHub's v4 API is GraphQL) that agents call as tools.",
        "Rarely in model serving."],
  fail=dict(symptom="One innocent-looking query takes seconds and hammers the database.",
            cause="Nested fields resolved one by one (N+1 queries) or an unbounded query depth.",
            see="Query cost limits and resolver tracing; the response's `errors` array, since GraphQL often answers 200 even on failure."),
  wire=["graphql"],
  wire_note="A public demo API answered with exactly the three fields asked for.",
  srcs=[("gh", "graphql/graphql-spec", "September2025"), ("gh", "graphql/graphql-spec", "October2021"),
        ("GraphQL specification (latest edition)", "https://spec.graphql.org/"),
        ("GitHub GraphQL API docs", "https://docs.github.com/en/graphql")],
  versions=[("gh", "graphql/graphql-spec", "October2021", "GraphQL spec, October 2021 edition"), ("gh", "graphql/graphql-spec", "September2025", "GraphQL spec, September 2025 edition")]),

 dict(id="jsonrpc", name="JSON-RPC 2.0", full="JSON-RPC 2.0", group="api", year=2010, body="JSON-RPC Working Group (informal)",
  cur="JSON-RPC 2.0 (origin 2010-03-26, updated 2013-01-04)", status="Stable informal specification",
  plain="The smallest possible remote call format: a JSON object with a method name, parameters and an id, answered by a JSON object with a result or an error and the same id.",
  problem="Call named methods over any channel (a pipe, a socket, HTTP) without designing URLs and verbs.",
  how="Request `{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{...}}`; response `{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":{...}}` or `{\"error\":{\"code\":-32602,\"message\":...}}`. A request without an id is a **notification** (no reply). The spec defines no transport: it runs over stdio, WebSockets or HTTP.",
  runs_on=["http2", "http11"], uses=[],
  adds="A few fields of JSON per message.",
  costs="No schema, no streaming, no transport rules: everything around it must be specified by the protocol that uses it (as MCP and A2A do).",
  not_when="Public resource-shaped APIs (REST); high-volume typed internal calls (gRPC).",
  replaces="XML-RPC and JSON-RPC 1.0.",
  competes="gRPC, REST.",
  meet=["Every MCP message (the recording shows an `initialize` request and its result).",
        "A2A's JSON-RPC binding; the Language Server Protocol between your editor and its language servers."],
  fail=dict(symptom="Responses get matched to the wrong requests, or a client waits forever.",
            cause="Reused or missing ids, or a notification (no id) sent where a reply was expected.",
            see="Log raw messages with their ids; MCP inspectors show the exchange."),
  wire=["mcp"],
  wire_note="A JSON-RPC 2.0 request and its result with the same `id`, here carried by MCP over Streamable HTTP as one SSE event.",
  srcs=[("JSON-RPC 2.0 specification (origin date 2010-03-26, updated 2013-01-04)", "https://www.jsonrpc.org/specification"),
        ("Language Server Protocol 3.17 specification (base protocol is JSON-RPC)", "https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/")],
  versions=[("2010-03", "JSON-RPC 2.0 specification", "https://www.jsonrpc.org/specification")]),
]
