"""Atlas metadata: layer groups for the stack view, the 'which protocol when' chooser, and notes for compare pairs."""

# Stack rows, top to bottom. `adds` is what the layer adds to the same message, in one line.
GROUPS = [
 dict(id="agent", label="Agent protocols", adds="Who the agent may talk to, about what: tools, other agents, merchants, devices."),
 dict(id="auth", label="Who is calling", adds="Proof of identity and permission carried in headers or certificates."),
 dict(id="api", label="Service API styles", adds="How a call is named and its data shaped: resources, procedures, queries."),
 dict(id="stream", label="Streaming and events", adds="How data keeps flowing after the first response, or arrives later."),
 dict(id="http", label="HTTP", adds="Methods, paths, status codes and headers; the wire format depends on the version."),
 dict(id="security", label="Security", adds="Encryption and proof of the server's (and maybe client's) identity."),
 dict(id="naming", label="Naming", adds="Turns a name into addresses before anything else can happen."),
 dict(id="transport", label="Transport", adds="Ports, and either a reliable byte stream (TCP, QUIC) or loose datagrams (UDP)."),
 dict(id="net", label="Network", adds="Addresses, and forwarding of packets hop by hop."),
 dict(id="fabric", label="GPU fabric (brief)", adds="Moving tensors between GPUs, bypassing the kernel network stack."),
]

# Chooser: questions; a question with `only` is asked only when the first answer is in that list.
QUESTIONS = [
 dict(id="who", q="Who talks to whom?", opts=[
   ("user", "An app or browser calls my service"),
   ("internal", "My service calls another of my services"),
   ("provider", "My backend calls an outside API (an LLM provider)"),
   ("event", "Another system must be told later that something happened"),
   ("tools", "A model or agent needs tools or data"),
   ("agent", "My agent hands work to another team's or company's agent"),
   ("commerce", "An agent buys from a merchant"),
   ("gpu", "GPUs exchange tensors during training")]),
 dict(id="flow", q="How does the answer come back?", only=["user", "internal", "provider"], opts=[
   ("once", "One request, one answer"),
   ("server", "The server streams to the client (tokens)"),
   ("both", "Both sides stream at once (voice, interruptions)"),
   ("later", "The work takes minutes: the answer comes later")]),
 dict(id="where", q="Where are the two ends?", only=["user", "internal", "tools", "event", "agent"], opts=[
   ("public", "Across the public internet or between organisations"),
   ("inside", "Inside one network or cluster I control")]),
 dict(id="client", q="Is the caller a web browser?", only=["user", "internal"], opts=[
   ("browser", "Yes, browser code"),
   ("program", "No, a program (SDK, service, CLI)")]),
]

# Rules: the first whose `when` matches all given answers wins. `pick` lists atlas ids, main one first.
RULES = [
 dict(when=dict(who="gpu"), pick=["nccl", "ib", "roce", "tcp"],
      say="NCCL over InfiniBand or RoCEv2 (RDMA); its TCP socket transport only when no RDMA network exists.",
      why="Collectives move gigabytes per step; RDMA lets network cards read and write memory without kernel copies, and NCCL picks the best path per pair of GPUs.",
      avoid="Hand-written TCP or HTTP between workers.",
      auth="None at this layer: the fabric is a private network."),
 dict(when=dict(who="tools", where="inside"), pick=["mcp", "jsonrpc"],
      say="An MCP server: over stdio if it runs on the same machine as the agent, over Streamable HTTP if several agents share it.",
      why="One server works in every MCP harness; stdio needs no network or auth at all.",
      avoid="Passing the user's token through to downstream APIs (forbidden by the MCP spec).",
      auth="stdio: the process boundary. HTTP: OAuth (MCP authorization) or the network's own identity."),
 dict(when=dict(who="tools", where="public"), pick=["mcp", "oauth", "sse"],
      say="A remote MCP server on Streamable HTTP, protected as an OAuth resource server (RFC 9728 metadata, audience-bound tokens).",
      why="The spec defines discovery, token audience and the ban on token passthrough, so clients you never met can connect safely.",
      avoid="Static shared keys in every client's config; trusting tool output as instructions.",
      auth="OAuth 2.1 code flow with PKCE; Client ID Metadata Documents for registration (2026-07-28)."),
 dict(when=dict(who="agent"), pick=["a2a", "jsonrpc", "grpc"],
      say="A2A: publish an Agent Card, exchange tasks over the JSON-RPC binding with SSE streaming (gRPC binding between your own services).",
      why="Neither agent sees the other's tools or prompts; tasks give a shared lifecycle and the card says how to authenticate.",
      avoid="Exposing your internal tools to the other agent through MCP.",
      auth="Whatever the Agent Card declares: OAuth or OIDC across organisations, mTLS inside."),
 dict(when=dict(who="commerce"), pick=["ucp", "mcp", "oauth"],
      say="UCP: read the merchant's `/.well-known/ucp`, negotiate capabilities, and honour `requires_escalation` by handing the buyer to `continue_url`.",
      why="It is the protocol merchants publish; profile intersection lets the agent degrade gracefully.",
      avoid="Scraping checkout pages; treating escalation as failure.",
      auth="OAuth 2.0 identity linking; payments through AP2 mandates."),
 dict(when=dict(who="event", where="public"), pick=["webhook", "http2"],
      say="Webhooks with Standard Webhooks signatures; the receiver verifies the raw body and deduplicates on `webhook-id`.",
      why="The other side may be offline; retries with backoff over days survive that, signatures prove origin.",
      avoid="Holding a connection open for hours; verifying a re-serialised body.",
      auth="HMAC signature with a shared secret (or an asymmetric signature)."),
 dict(when=dict(who="event", where="inside"), pick=["webhook", "grpc"],
      say="A queue or event stream between your own services (see the SWE topic's queues page); webhooks only where the receiver is another team's HTTP service.",
      why="Queues give durable, replayable delivery and backpressure; webhooks are the across-organisation version.",
      avoid="Synchronous chains of calls that all fail when one service is slow.",
      auth="Service identity: mTLS or cloud IAM."),
 dict(when=dict(flow="both"), pick=["ws", "http11", "tls"],
      say="WebSockets (realtime voice APIs use them), with pings and reconnect-with-backoff.",
      why="Both sides send at any time on one connection; audio frames go both ways while the user interrupts.",
      avoid="Opening a new request per audio chunk.",
      auth="A short-lived token obtained over HTTPS first, sent in the handshake, not a long-lived key in browser code."),
 dict(when=dict(flow="later"), pick=["rest", "webhook", "sse"],
      say="Start the job with a REST POST that returns `202 Accepted` and a job id; then poll, receive a webhook, or subscribe to an SSE stream of progress.",
      why="No connection survives every proxy for many minutes; a job id makes the work resumable and idempotent.",
      avoid="One HTTP request held open for the whole job.",
      auth="As for the first call."),
 dict(when=dict(who="provider", flow="server"), pick=["sse", "http2", "apikey"],
      say="The provider's REST API with `stream: true`: a POST answered by an SSE stream, read with the SDK, with an API key from a secrets manager.",
      why="That is how LLM APIs stream tokens; HTTP/2 keeps many concurrent streams on few connections.",
      avoid="Proxies with buffering on, or idle timeouts shorter than the longest pause before a token.",
      auth="API key in a secrets manager; OAuth only when acting for a user."),
 dict(when=dict(who="provider"), pick=["rest", "http2", "apikey"],
      say="The provider's REST API over HTTPS with its SDK, an idempotency key on retried POSTs, and an API key from a secrets manager.",
      why="Public APIs are REST; SDKs handle retries and backoff on 429 and 5xx.",
      avoid="Retrying non-idempotent calls blindly.",
      auth="API key; cloud IAM (SigV4) when the model is served by your cloud (Bedrock)."),
 dict(when=dict(who="user", flow="server"), pick=["sse", "http2", "tls"],
      say="Answer the POST with an SSE stream (`text/event-stream`) over HTTP/2 or HTTP/3; send a comment line every 15 s or so.",
      why="One-way token streaming is exactly what SSE is; it works through ordinary HTTP infrastructure.",
      avoid="WebSockets for one-way streams; any buffering proxy on the path.",
      auth="Browser: OIDC login and a session or short-lived token. Programs: API keys or OAuth."),
 dict(when=dict(who="internal", client="program"), pick=["grpc", "http2", "mtls"],
      say="gRPC with protobuf over HTTP/2, a deadline on every call, and L7 or client-side load balancing.",
      why="Typed contracts, small binary payloads, all four streaming shapes, and deadlines that stop wasted GPU work.",
      avoid="L4 load balancers in front of long-lived gRPC connections; calls without deadlines.",
      auth="mTLS from a mesh or SPIFFE, or cloud workload identity."),
 dict(when=dict(who="internal", client="browser"), pick=["rest", "http2", "oidc"],
      say="REST and JSON over HTTPS (or gRPC-Web through a gateway).",
      why="Browsers cannot speak native gRPC; REST works with every tool.",
      avoid="Exposing internal gRPC services directly to browsers.",
      auth="OIDC login, then a session cookie or short-lived token."),
 dict(when=dict(who="user"), pick=["rest", "http2", "tls"],
      say="REST over HTTPS, described with OpenAPI, with problem-details errors (RFC 9457) and idempotency keys on POST.",
      why="Any client can call it; caches and proxies understand it.",
      avoid="GraphQL unless many different clients need different shapes of the same data.",
      auth="Browser users: OIDC with the code flow and PKCE. Programs: API keys or OAuth client credentials."),
]

# Notes for frequently compared pairs (key: the two ids sorted and joined by '|').
PAIRS = {
 "sse|ws": "SSE is one-way (server to client) over ordinary HTTP and reconnects by itself; WebSockets are two-way after an HTTP upgrade. Token streaming is one-way, so LLM APIs use SSE; voice needs both directions, so realtime APIs use WebSockets.",
 "grpc|rest": "Same HTTP underneath; REST names resources and uses JSON so anything can call it, gRPC names procedures with generated typed clients, protobuf payloads, streaming and deadlines. Public edge: REST. Between your own services: gRPC.",
 "http2|http3": "Same semantics and the same idea of many streams on one connection; HTTP/2 rides TCP (one loss stalls all streams), HTTP/3 rides QUIC on UDP (a loss stalls only its stream) and sets up in fewer round trips.",
 "quic|tcp": "Both give reliable ordered streams with congestion control. TCP is one stream in the kernel, with TLS added on top; QUIC is many streams in user space over UDP, with TLS 1.3 built into its handshake.",
 "tcp|udp": "TCP: connection, ordering, retransmission, congestion control, one round trip to start. UDP: none of that, 8 bytes of header, nothing to set up.",
 "oauth|oidc": "OAuth answers 'what may this app do for the user' (an access token for an API). OIDC adds 'who is the user' (an ID token for the app). Login is OIDC; API access is OAuth.",
 "apikey|jwt": "An API key is an opaque secret looked up by the server and valid until revoked. A JWT is a signed, readable token checked offline and valid until it expires. Both are bearer credentials: whoever holds one can use it.",
 "a2a|mcp": "MCP connects an agent to tools and data it controls (agent to tool); A2A connects an agent to another agent it cannot see inside (agent to agent). Both use JSON-RPC 2.0 and SSE; A2A also has gRPC and REST bindings.",
 "mtls|tls": "TLS proves the server's identity to the client; mTLS adds a client certificate so the server knows the caller too. Same handshake, one more certificate.",
 "jsonrpc|rest": "REST spreads meaning over URLs, methods and status codes; JSON-RPC puts a method name and params in one JSON body sent to one endpoint, so it also works over stdio or WebSockets.",
 "graphql|rest": "REST returns what each endpoint defines; GraphQL returns exactly the fields the client's query asks for, from one endpoint, at the cost of HTTP caching and query cost control.",
 "sse|webhook": "SSE keeps a response open while the client waits; a webhook is a new request from the provider to you later, when nobody is waiting.",
 "ssh|tls": "Both encrypt and authenticate over TCP with their own handshakes. TLS secures other protocols (HTTP, gRPC) and identifies servers by certificates from CAs; SSH is its own protocol for shells, file copies and tunnels, identifying hosts by keys you remember.",
 "mcp|ucp": "UCP is a commerce protocol that can use MCP as one of its transports (the recorded merchant profile offers `\"transport\":\"mcp\"`); MCP itself knows nothing about checkouts or escalation to a human.",
 "oauth|sigv4": "OAuth hands out bearer tokens that are sent as they are; SigV4 never sends the secret and signs each request instead, so a captured request is only replayable briefly and cannot be altered.",
 "http11|http2": "Same requests and responses. HTTP/1.1 is text, one request at a time per connection; HTTP/2 is binary frames with many requests interleaved on one connection and compressed headers.",
}
