"""Pack the recorded runs into ../parts/34_js_debug_a.js (window.DG.R) for the "When training goes wrong" tab.

Inputs: runs_digits.json, runs_imbalance.json, runs_spike.json (this folder).
Per-step series of the spike runs are stored log-quantised: each value v in [lo, hi] becomes round(4095 * log(v/lo) /
log(hi/lo)) written as two base64url characters ('~~' for a missing or non-finite value). The relative error is at
most (hi/lo)^(1/8190) - 1, printed below. Everything else is rounded to 4 significant digits.
usage: python3 mk_data.py
"""
import json, math, os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'parts', '34_js_debug_a.js')
B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_'


def sig(v, p=4):
    if v is None or isinstance(v, str):
        return None
    return float(f'{v:.{p}g}') if math.isfinite(v) else None


def pts(xs, n=200, p=4):
    """[[step, value]] thinned to about n points, keeping each block's first point and its largest value."""
    xs = [[s, (v if isinstance(v, (int, float)) else None)] for s, v in xs]
    if len(xs) > n:
        k = math.ceil(len(xs) / n); out = []
        for i in range(0, len(xs), k):
            blk = xs[i:i + k]; fin = [b for b in blk if b[1] is not None]
            if not fin:
                out.append(blk[0]); continue
            hi = max(fin, key=lambda b: b[1]); lo = min(fin, key=lambda b: b[1])
            for b in sorted({id(lo): lo, id(hi): hi}.values(), key=lambda b: b[0]):
                out.append(b)
        xs = out
    return [[s, sig(v, p)] for s, v in xs]


def enc(vals, lo, hi):
    L = math.log(hi / lo); s = []
    for v in vals:
        if v is None or not math.isfinite(v) or v <= 0:
            s.append('~~'); continue
        q = max(0, min(4095, round(4095 * math.log(max(lo, min(hi, v)) / lo) / L)))
        s.append(B64[q >> 6] + B64[q & 63])
    return ''.join(s)


D = json.load(open(os.path.join(HERE, 'runs_digits.json')))
runs = {}
for k, r in D.items():
    if k.startswith('_'):
        continue
    o = {'tr': pts(r['train'], 75, 3), 'va': pts(r['val'], 90, 3), 'init': r['init_loss'],
         'fin': {kk: (sig(v) if not isinstance(v, str) else v) for kk, v in r['final'].items()}}
    if r.get('diverged_at'):
        o['div'] = r['diverged_at']
    # first step whose validation loss is non-finite
    nf = [s for s, v in r['val'] if isinstance(v, str)]
    if nf:
        o['vdiv'] = nf[0]
    fin_val = [v for v in r['val'] if isinstance(v[1], float)]
    if fin_val:
        b = min(fin_val, key=lambda v: v[1]); o['best'] = [b[0], sig(b[1])]
    if r.get('layers'):
        o['lay'] = [[row[0]] + [sig(x, 2) for x in row[1:]] for row in r['layers']]
    if r.get('dead'):
        o['dead'] = r['dead']
    trv = [v for _, v in r['train'] if isinstance(v, float)]
    o['trmax'] = sig(max(trv)) if trv else None
    runs[k] = o

I = json.load(open(os.path.join(HERE, 'runs_imbalance.json')))
imb = {'always_no': I['always_no_acc'], 'n_train': I['n_train'], 'n_val': I['n_val'],
       'm': {k: {'mean': v['mean'], 'seeds': v['seeds']} for k, v in I['runs'].items()}}

S = json.load(open(os.path.join(HERE, 'runs_spike.json')))
RNG = {'loss': (0.5, 50.0), 'gnorm': (0.01, 1e4), 'maxlogit': (0.1, 1e7)}
for k, (lo, hi) in RNG.items():
    print(k, 'max relative quantisation error %.4f%%' % (100 * ((hi / lo) ** (1 / 8190) - 1)))
main = {}
for k, r in S['main'].items():
    main[k] = {'lr': r['lr'], 'n': len(r['loss']), 'val': [[s, sig(v)] for s, v in r['val']], 'fv': sig(r['final_val']),
               'div': r.get('diverged_at'), 'q': {s: enc(r[s], *RNG[s]) for s in ('loss', 'gnorm', 'maxlogit')},
               'mx': sig(max(v for v in r['maxlogit'] if v is not None), 3)}
sweep = [{'lr': r['lr'], 'qk': r['qk'], 'fv': sig(r['final_val']), 'div': r.get('diverged_at'),
          'mx': sig(max(v for v in r['maxlogit'] if v is not None), 3)} for r in S['sweep']]
R = {'runs': runs, 'imb': imb, 'spike': {'main': main, 'sweep': sweep, 'rng': RNG, 'params': S['_meta']['params'], 'vocab': S['_meta']['vocab']},
     'ln10': math.log(10)}
js = '// Generated by src/debug/mk_data.py from the recorded runs in src/debug/*.json. Do not edit by hand.\nwindow.DG=window.DG||{};window.DG.R=' + json.dumps(R, separators=(',', ':')) + ';\n'
open(OUT, 'w').write(js)
print('wrote', OUT, len(js), 'bytes')
