// ---- Part 2: Narrowing stepper (t-tb-narrow). Data: TB.narrow, generated by src/tb/gen_narrow.mjs from real tsc 7.0.2 probes ----
(function(){
  if(!window.TB||!document.getElementById('t-tb-narrow'))return;
  const esc=TBX.esc,N=TB.narrow;
  const PROGS=[
    {id:'p1',name:'typeof, == null and a helper',v:{after:'helper returns "v is string"',before:'helper returns boolean'}},
    {id:'p2',name:'Stream events',v:{after:'discriminated union',before:'one type, optional fields'}},
    {id:'p3',name:'in, truthiness, equality',v:{after:'one version'}},
    {id:'p4',name:'Inside a callback',v:{after:'name never reassigned',before:'name reassigned later'}}];
  let prog=PROGS[0],variant='after';
  const progEl=document.getElementById('tbn-prog'),varEl=document.getElementById('tbn-var');
  const codeEl=document.getElementById('tbn-code'),typesEl=document.getElementById('tbn-types'),cap=document.getElementById('tbn-cap');
  progEl.innerHTML=PROGS.map((p,i)=>'<button data-i="'+i+'"'+(i===0?' class="on"':'')+'>'+esc(p.name)+'</button>').join('');
  const key=()=>prog.id+'_'+variant;
  const other=()=>{const o=variant==='after'?'before':'after';return N[prog.id+'_'+o]?{name:o,d:N[prog.id+'_'+o]}:null};
  function renderVar(){varEl.innerHTML=Object.keys(prog.v).map(k=>'<button data-m="'+k+'"'+(k===variant?' class="on"':'')+'>'+(k==='before'?'Before: ':(Object.keys(prog.v).length>1?'After: ':''))+esc(prog.v[k])+'</button>').join('')}
  const errLines=d=>new Set(d.tsc.map(e=>{const m=e.match(/^narrow\.ts\((\d+),/);return m?+m[1]:0}));
  function chips(type,prev){
    const cur=TBX.members(type);const ps=prev?TBX.members(prev):[];
    if(type==='never')return '<span class="tbn-chip never">never (nothing left)</span>';
    let h=cur.map(m=>'<span class="tbn-chip">'+esc(m)+'</span>').join('');
    const gone=ps.filter(m=>!cur.includes(m)&&prev!==type);
    if(gone.length&&!(cur.length===1&&ps.length===1))h+=gone.map(m=>'<span class="tbn-chip out">'+esc(m)+'</span>').join('');
    return h;
  }
  function draw(i){
    const d=N[key()];if(!d)return;const n=d.steps.length;const el=errLines(d);
    const final=i>=n;const s=final?null:d.steps[i];
    codeEl.innerHTML=d.code.map((l,k)=>'<span class="ln'+(s&&s.line===k+1?' cur':'')+(final&&el.has(k+1)?' err':'')+'"><i>'+(k+1)+'</i>'+(TBX.hl(l)||' ')+'</span>').join('');
    if(!final){
      const prev=i>0&&d.steps[i-1].expr===s.expr?d.steps[i-1].type:null;
      let h='<div class="tbn-lab">Line '+s.line+': tsc says</div><div class="tbn-expr">'+esc(s.expr)+'</div><div class="tbn-chips">'+chips(s.type,prev)+'</div>';
      const o=other();
      if(o&&o.d.steps[i]){const os=o.d.steps[i];const op=i>0&&o.d.steps[i-1].expr===os.expr?o.d.steps[i-1].type:null;
        h+='<div class="tbn-other"><div class="tbn-lab">Same line, '+(o.name==='before'?'before':'after')+' version: '+esc(prog.v[o.name])+'</div><div class="tbn-expr">'+esc(os.expr)+'</div><div class="tbn-chips">'+chips(os.type,op)+'</div></div>'}
      typesEl.innerHTML=h;
      cap.innerHTML='<b>Step '+(i+1)+'/'+(n+1)+'.</b> '+esc(s.cap);
    }else{
      typesEl.innerHTML='<div class="tbn-lab">npx tsc on the whole program</div>'+(d.tsc.length?'<div class="tbn-err">'+d.tsc.map(esc).join('\n')+'</div>':'<div class="tbn-ok">No errors.</div>'+(d.run?'<div class="tbn-lab" style="margin-top:6px">node prints</div><pre class="tb-term" style="border-radius:8px">'+esc(d.run)+'</pre>':''));
      cap.innerHTML='<b>Step '+(n+1)+'/'+(n+1)+'. The verdict.</b> '+(d.tsc.length?'The lines underlined in red are the errors: exactly where the narrowing was lost.':'Every use is justified by a check, so the program type-checks.');
    }
  }
  const nSteps=()=>N[key()].steps.length+1;
  const an=RD.anim({card:'tbn-card',ctl:'tbn-ctl',n:nSteps(),ms:1900,draw,label:'Narrowing step'});
  progEl.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;progEl.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));
    prog=PROGS[+b.dataset.i];variant='after';renderVar();an.reset(nSteps());an.play()});
  // a variant switch keeps the current step, so the same line can be compared
  varEl.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;varEl.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));
    variant=b.dataset.m;const i=an.i;an.reset(nSteps());an.go(Math.min(i,nSteps()-1))});
  renderVar();
  TBX.onTab('t-tb-narrow',()=>an.redraw());
})();
