"""Turn model/sweep.json (written by sweep.cjs) into parts/20b_sweep_data.js (window.SWEEP), keeping
per-seed held-out MSE, training drop rate and maximum load, without the curves.
usage: python3 mk_sweep_data.py"""
import json
S = json.load(open('model/sweep.json'))
out = {'base': S['base'], 'steps': S['steps'], 'seeds': S['seeds'], 'groups': {}}
for g, rows in S['groups'].items():
    out['groups'][g] = [{'o': r['o'], 'mean': round(r['mean'], 5), 'sd': round(r['sd'], 5), 'drop': round(r['drop'], 4), 'maxf': round(r['maxf'], 3),
                         'te': [round(x['te'], 5) for x in r['runs']], 'id': round(r['runs'][0]['id'], 5)} for r in rows]
open('parts/20b_sweep_data.js', 'w').write('// Generated by mk_sweep_data.py from model/sweep.json (sweep.cjs: 3 seeds per setting, 1,500 steps).\nwindow.SWEEP=' + json.dumps(out, separators=(',', ':')) + ';\n')
print('ok', len(json.dumps(out)))
