"""Turn the measurements in inputs/ into parts/22_js_data.js (window.D). Run after any measurement script: python3 build_data.py"""
import json, os
H = os.path.dirname(os.path.abspath(__file__)); I = lambda n: json.load(open(os.path.join(H, 'inputs', n)))
lab = I('lab.json'); enc = I('encodings.json'); an = I('anatomy.json'); ice = I('iceberg.json'); dl = I('delta.json')
eng = I('engines.json'); vo = I('vec_ooc.json'); ch = I('clickhouse.json'); rs = I('remote_small.json'); asof = I('ml_asof.json')
D = {}
D['lab'] = {'queries': lab['queries'], 'files': [{k: f[k] for k in ('sort', 'rg', 'comp', 'bytes', 'write_s', 'row_groups', 'rows_per_rg_max')} |
            {'q': {q: {k: v[k] for k in ('rg_kept', 'need_bytes', 'read_bytes', 'ms')} for q, v in f['q'].items()}} for f in lab['files']]}
D['enc'] = [{'col': c['col'], 'order': c['order'], 'arrow': c['arrow_bytes'], 'sizes': c['sizes']} for c in enc['cols']]
t = an['tiny']
D['tiny'] = {k: t[k] for k in ('bytes', 'footer_len', 'footer_start', 'num_rows', 'created_by', 'head_hex', 'tail_hex', 'footer_head_hex', 'regions',
             'role_dictionary', 'role_bit_width', 'role_runs', 'role_first_indices', 'role_first_values', 'schema')}
D['tiny']['chunks'] = t['chunks']
f = an['full']
D['full'] = {k: f[k] for k in ('bytes', 'num_rows', 'row_groups', 'created_by', 'footer_bytes', 'rg0_rows', 'rg0_columns', 'counted')}
D['full']['rgs'] = [{'n': r['rows'], 'ca0': r['created_at_min'], 'ca1': r['created_at_max'], 'c0': int(r['chat_id_min']), 'c1': int(r['chat_id_max']),
                     'cab': r['created_at_bytes'], 'cb': r['chat_id_bytes'], 'tb': r['tokens_bytes']} for r in f['row_groups_detail']]
def trim_ice(s):
    out = {k: s[k] for k in ('step', 'what', 'metadata_location', 'snapshot_id', 'rows_now')}
    out['files'] = s['new_files']; return out
D['ice'] = {'version': ice['pyiceberg'], 'steps': [trim_ice(s) for s in ice['steps']], 'tt': ice['time_travel'], 'plan': ice['scan_plan_one_day'], 'victim': ice['victim_chat']}
D['delta'] = {'version': dl['deltalake'], 'steps': dl['steps'], 'tt': dl['time_travel']}
D['eng'] = {k: {'title': v['title'], 'sql': v['sql'], 'duck': v['duck'][0], 'duck_1': v['duck_1'][0], 'pg': v['pg'][0], 'pg_1': v['pg_1'][0], 'sq': v['sq'][0], 'agree': v['agree'], 'rows': v['result_rows']}
            for k, v in eng['queries'].items()}
D['vec'] = {'python_loop': vo['python_loop'][0], 'numpy': vo['numpy_sum'][0], 'duck_1': vo['duck_sum_1'][0], 'ooc': vo['out_of_core']['runs']}
D['ch'] = {k: ch[k] for k in ('clickhouse', 'chdb', 'parts_after_inserts', 'parts_after_merge', 'explain_before_merge', 'explain_after_merge', 'by_time_query', 'columns', 'settings', 'mv_sample', 'mv_rows_before_merge', 'optimize_s', 'insert_s')}
D['http'] = {k: {kk: (v[kk].replace('s3://bucket/', 'https://host/') if kk == 'sql' else v[kk]) for kk in ('ms', 'requests', 'bytes', 'log', 'sql')} for k, v in rs['http'].items()}
D['http_file'] = rs['file_bytes']
D['small'] = rs['small_files']; D['compaction'] = rs['compaction']
D['asof'] = {k: asof[k] for k in ('examples', 'users_upgraded', 'naive_pro', 'asof_pro', 'leaked', 'sample')}
def big(o):
    if isinstance(o, bool): return o
    if isinstance(o, int) and abs(o) > 2**53: return str(o)
    if isinstance(o, dict): return {k: big(v) for k, v in o.items()}
    if isinstance(o, list): return [big(v) for v in o]
    return o
D = big(D)  # snapshot ids are 64-bit: keep them exact as strings
s = 'window.D=' + json.dumps(D, separators=(',', ':'), ensure_ascii=True) + ';\n'
open(os.path.join(H, 'parts', '22_js_data.js'), 'w').write('// ---- Measured data (generated by build_data.py from inputs/*.json; do not edit) ----\n' + s)
print('22_js_data.js', len(s))
