"""Build parts/22_js_data.js (window.MCPD) from lab/out/*.json. Only trims (long strings cut at a stated length,
marked with "[...]"); never edits a value. check_embed.py re-derives every number the page shows from the same files."""
import json, os, re
H = os.path.dirname(os.path.abspath(__file__)); O = os.path.join(H, "lab", "out")
L = lambda f: json.load(open(os.path.join(O, f)))


def cut(s, n=900):
    s = s or ""
    return s if len(s) <= n else s[:n] + " [...]"


rep = []
for r in L("replicas.json"):
    rep.append({"era": r["era"], "lb": r["balancer"], "key": r["shared_key"], "ok": r["ok"], "n": r["n"],
                "err": r["errors"], "ms": r["median_ms"],
                "trace": [{"rep": t["replica"], "m": t["method"], "st": t["status"], "rh": t["req_headers"],
                           "rb": cut(t["req_body"], 700), "sb": cut(t["resp_body"], 700), "sh": t["resp_headers"]} for t in r["trace"]]})

tr = L("transports.json"); trows = []
for k, v in tr.items():
    if k == "progress_call":
        continue
    cold = v.get("cold_trace") or []
    if cold and "dir" in cold[0]:
        msgs = [{"d": c["dir"], "s": cut(c["line"].strip(), 600)} for c in cold]
    else:
        msgs = []
        for c in cold or []:
            msgs += [{"d": "client->server", "s": cut(c["up"], 1500)}, {"d": "server->client", "s": cut(c["down"], 1500)}]
    trows.append({"name": k, "cold": v["cold_ms"], "med": v["warm_median_ms"], "p90": v["warm_p90_ms"], "n": v["n"],
                  "up": v["one_call"]["up"], "down": v["one_call"]["down"], "coldmsgs": msgs})
pc = tr["progress_call"]
c = next(c for c in pc["text"] if "notifications/progress" in c["down"])
up = c["up"].split("POST /mcp", 2); up = "POST /mcp" + up[1]
dn = c["down"]; dn = dn[:dn.index("\r\n0\r\n") + 7]
prog = {"seen": pc["progress_seen"], "down": dn, "up": up}

comp = [{"c": o["client"], "s": o["server"], "ok": o["ok"], "v": o.get("version"), "d": cut(o["detail"].replace("\n", " "), 220),
         "ms": o.get("ms"), "wire": [{"d": w["dir"], "s": cut(w["line"].strip(), 420)} for w in o["wire"][:6]]} for o in L("compat.json")]

a = L("auth.json"); f = a["flow"]
mw, aw = f["mcp_wire"], f["as_wire"]
order = [("mcp", 0), ("mcp", 1), ("mcp", 2), ("mcp", 3), ("as", 0), ("as", 1), ("cimd", None), ("as", 2), ("as", 3), ("as", 4), ("as", 5),
         ("mcp", 4), ("mcp", 5), ("mcp", 6), ("mcp", 7)]
steps = []
for src, i in order:
    if src == "cimd":
        x = f["as_log"][0]
        steps.append({"src": "as->cimd", "dir": "fetch", "s": "GET " + x["as_fetched_cimd"] + "\n\n" + json.dumps(x["doc"], indent=1)})
    else:
        e = (mw if src == "mcp" else aw)[i]
        steps.append({"src": src, "dir": e["dir"], "s": cut(e["data"], 1300)})
auth = {"steps": steps, "result": f["client_view"].get("result"),
        "fails": {k: {"st": v["status"], "wa": v["www_authenticate"], "b": cut(v["body"], 200)} for k, v in a["failures"].items()},
        "mixup": a["mixup"]["client_view"].get("error")}

wc = [{"case": c["case"], "st": c["status"], "resp": cut(c["resp"], 300),
       "hdr": {k: v for k, v in (c["sent"].get("headers") or {}).items() if k not in ("accept", "content-type")},
       "method": c["sent"]["method"]} for c in L("wire_checks.json")]
ver = open(os.path.join(O, "versions.txt")).read().strip()

D = {"rep": rep, "tr": trows, "prog": prog, "comp": comp, "auth": auth, "wc": wc, "ver": ver}
js = "// generated by gen_data.py from lab/out/*.json; do not edit\nwindow.MCPD=" + json.dumps(D, ensure_ascii=False, separators=(",", ":")) + ";\n"
open(os.path.join(H, "parts", "22_js_data.js"), "w").write(js)
print(len(js), "bytes")
