"""Write parts/31_js_sim_c_data.js: the real outputs (verbatim lines) and the check results the tab shows.
Run after real/run_real.sh, check_ostep.py and check_js.mjs. check_embed.py then confirms index.html carries them."""
import json, os, re
H = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(H, "real", "out")


def lines(p):
    return [l.rstrip("\n") for l in open(p) if l.strip()]


D = {"raw": {}}
for f in sorted(os.listdir(OUT)):
    if f.endswith(".txt"):
        D["raw"][f[:-4]] = lines(os.path.join(OUT, f))
D["checks"] = {"ostep": lines(os.path.join(H, "check_ostep.txt")), "js": lines(os.path.join(H, "check_js.txt"))}
# two-level page table: OSTEP paging-multilevel-translate.py -s 1 (memory dump, PDBR, and its own answers)
t = open(os.path.join(H, "inputs", "ostep_multilevel_s1.txt")).read()
D["ml"] = {"pdbr": int(re.search(r"PDBR: (\d+)", t).group(1)),
           "pages": re.findall(r"^page\s+\d+:([0-9a-f]{64})", t, re.M),
           "answers": [[int(v, 16), (int(pa, 16) if pa else None)] for v, pa in
                       re.findall(r"Virtual Address 0x([0-9a-f]+):\n(?:.*\n)*?.*?(?:Translates to Physical Address 0x([0-9a-f]+)|Fault)", t)]}
js = "// ---- OS simulators: real outputs and check results (generated by src/sim/gen_data.py; do not edit) ----\n"
js += "window.SIMDATA=" + json.dumps(D, separators=(",", ":")) + ";\n"
open(os.path.join(H, "..", "parts", "31_js_sim_c_data.js"), "w").write(js)
print("wrote", len(js), "bytes", {k: len(v) for k, v in D["raw"].items()}, "ml answers", D["ml"]["answers"])
