"""Debug lab cases, part B (CPU, processes and signals)."""
from cases_a import L, DOCKER_RUN, CG2, PT, MAN

K8S_RES = "https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/"
K8S_TERM = "https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination"
STOP = "https://docs.docker.com/reference/cli/docker/container/stop/"

CASES = [
dict(
  id="throttle", seen='Steps are several times slower than on a laptop with the same number of CPUs:', title="Step time quadruples under a CPU limit: cgroup throttling",
  sub=["cpu", "limits"], tools=["cgroup files", "getrusage"], ostep="7 CPU Scheduling; 9 Lottery Scheduling",
  symptom=("cpu_half", r"re:step time: median \d+ ms"),
  rec=[("cpu_2", "host"), ("cpu_2", "torch threads: 2 (0 means the default)"), ("cpu_half", "host"), ("cpu_half", "torch threads: 2 (0 means the default)")],
  cause="A CPU limit is a quota, not fewer CPUs: <code>cpu.max</code> = 50000 100000 lets the cgroup run 50 ms of CPU time in every 100 ms period, on any CPUs (" + L("cgroup v2 cpu.max", CG2) + "). Two threads burn the 50 ms in about 25 ms of wall time and then the whole cgroup is stopped until the next period: <code>cpu.stat</code> shows it throttled in @@cpu_half|nr_throttled (\d+)@@ of @@cpu_half|nr_periods (\d+)@@ periods, @@cpu_half|throttled_usec (\d+)@@ microseconds throttled in a @@cpu_half|total ([\d.]+) s@@ s run (the throttled time adds up over threads). The same work took @@cpu_2|median (\d+) ms@@ ms per step with 2 CPUs and @@cpu_half|median (\d+) ms@@ ms with half a CPU.",
  fix="Give the job the CPUs it uses, or use fewer threads than the quota allows (next case). In Kubernetes a CPU limit becomes exactly this quota (" + L("resource limits", K8S_RES) + "); some clusters set requests without limits for training pods for this reason.",
  ml="DataLoader workers, the main loop and the framework's thread pool all share the pod's quota; a GPU waits while its feeding CPU is throttled. <code>nr_throttled</code> rising is the signature.",
  first=dict(opts=["cat cpu.stat (nr_throttled, throttled_usec)", "free -m", "df -h", "ulimit -n"], a=0,
             why="Slow steps with a CPU limit: the cgroup's own counters say whether it is being throttled."),
  bars=dict(title="Median step time, ms (same work)",
            src=[("cpu_2", r"step time: median (\d+) ms", "2 CPUs, 2 threads"),
                 ("cpu_half", r"step time: median (\d+) ms", "0.5 CPU, 2 threads")], unit="ms"),
),
dict(
  id="threads", seen='Steps are slow on a small CPU limit, and the job reports more threads than it has CPUs:', title="Too many threads for the CPUs you have: os.cpu_count() sees the whole machine",
  sub=["cpu", "limits"], tools=["cgroup files", "getrusage"], ostep="10 Multi-CPU Scheduling; 26 Concurrency and Threads",
  symptom=("cpu_one", "os.cpu_count() = 5; torch threads = 5"),
  rec=[("cpu_one", "host"), ("cpu_one", "torch threads: 0 (0 means the default)"), ("cpu_one", "torch threads: 1 (0 means the default)")],
  cause="A CPU quota does not change what the process sees: <code>os.cpu_count()</code> and <code>nproc</code> report the machine's 5 CPUs, and PyTorch sizes its intra-op thread pool from them (" + L("torch.set_num_threads", "https://docs.pytorch.org/docs/stable/generated/torch.set_num_threads.html") + "). Five threads on a one-CPU quota take turns, wait for each other at every parallel region, and are throttled in every period: @@cpu_one|torch threads = 5\nstep time: median (\d+) ms@@ ms per step, against @@cpu_one|torch threads = 1\nstep time: median (\d+) ms@@ ms with one thread doing the same work. @@cpu_one|torch threads = 5\n(?:.*\n){2}context switches: voluntary \d+, involuntary (\d+)@@ involuntary context switches (the kernel taking the CPU away, against @@cpu_one|torch threads = 1\n(?:.*\n){2}context switches: voluntary \d+, involuntary (\d+)@@ with one thread) and @@cpu_one|torch threads = 5\n(?:.*\n){1}cpu.stat during the run: .*usage_usec (\d+)@@ microseconds of CPU charged (against @@cpu_one|torch threads = 1\n(?:.*\n){1}cpu.stat during the run: .*usage_usec (\d+)@@) for the same arithmetic are the cost of the contention.",
  fix="Set the thread count from the quota, not from the machine: <code>torch.set_num_threads(n)</code> or <code>OMP_NUM_THREADS</code>, with n = <code>cpu.max</code> quota / period (or the Kubernetes CPU limit); count DataLoader workers in the same budget. Python 3.13 added <code>os.process_cpu_count()</code>, which honours CPU affinity but not a quota.",
  ml="The common Kubernetes case: a pod limited to 4 CPUs on a 128-core node starts 128 threads per process.",
  first=dict(opts=["compare torch.get_num_threads() with cpu.max", "nvidia-smi", "df -h", "cat memory.events"], a=0,
             why="The thread count comes from the machine, the CPU time from the quota: compare the two."),
  bars=dict(title="Median step time on 1 CPU, ms (same work)",
            src=[("cpu_one", r"torch threads = 5\nstep time: median (\d+) ms", "5 threads (default)"),
                 ("cpu_one", r"torch threads = 1\nstep time: median (\d+) ms", "1 thread")], unit="ms"),
),
dict(
  id="starve", seen="Low GPU utilisation; the loop's own timing says:", title="The training loop waits for data: DataLoader-bound",
  sub=["cpu", "process"], tools=["py-spy", "timing"], ostep="26 Concurrency and Threads",
  symptom=("starve", r"re:num_workers=0: .*"),
  rec=[("starve", "host"), ("starve", "same loop, more DataLoader workers"), ("starve", "what py-spy shows in the main process with num_workers=0")],
  cause="With <code>num_workers=0</code> the main process decodes every sample itself, so the model step (here a fixed matmul standing in for the GPU's work, since this VM has none) waits @@starve|num_workers=0: \d+ ms per step; waiting for data (\d+%)@@ of the time. " + L("py-spy", "https://github.com/benfred/py-spy") + " reads the interpreter's stack from outside without stopping it (it needs the ptrace permission, added to this container with CAP_SYS_PTRACE) and shows the main thread inside <code>__getitem__</code> and the FFT, not in the model. Workers move that work to other processes and CPUs; on this 2-CPU container the step time falls from @@starve|num_workers=0: (\d+) ms@@ ms to @@starve|num_workers=2: (\d+) ms@@ ms with 2 workers and @@starve|num_workers=4: (\d+) ms@@ ms with 4: beyond the CPUs the container has, more workers only compete for them.",
  fix="More workers up to the CPUs the job really has (the quota, see the previous case); cheaper decoding; preprocessing offline. Measure the time spent in <code>next(loader)</code> before buying a bigger GPU.",
  ml="Low GPU utilisation with a busy CPU is this case until proven otherwise.",
  first=dict(opts=["py-spy dump of the main process", "df -h /dev/shm", "cat memory.events", "ulimit -n"], a=0,
             why="Where the main thread is waiting tells you whether the input pipeline is the bottleneck."),
  bars=dict(title="Milliseconds per step by number of DataLoader workers (2 CPUs)",
            src=[("starve", r"num_workers=0: (\d+) ms", "0 workers"), ("starve", r"num_workers=1: (\d+) ms", "1 worker"),
                 ("starve", r"num_workers=2: (\d+) ms", "2 workers"), ("starve", r"num_workers=4: (\d+) ms", "4 workers")], unit="ms"),
),
dict(
  id="pids", title="BlockingIOError on fork: the pids limit counts threads too",
  sub=["process", "limits"], tools=["cgroup files", "/proc"], ostep="5 Process API; 27 Thread API",
  symptom=("pids", "BlockingIOError: [Errno 11] Resource temporarily unavailable"),
  rec=[("pids", "host"), ("pids", "the limit"), ("pids", "how many tasks the running job uses with 2 workers and 2 torch threads"),
       ("pids", "the running job with 16 DataLoader workers and 4 torch threads")],
  cause="<code>pids.max</code> limits tasks, and on Linux every thread is a task. The running job with 2 workers already uses @@pids|wc -l\); done\n(\d+)\n@@ (the main process alone has @@pids|pid \d+ threads (\d+)@@ threads). With 16 workers and 4 threads each the cgroup reaches its limit of 48, and <code>fork</code> (<code>clone</code>) fails with EAGAIN, which Python raises as <code>BlockingIOError</code>; <code>pids.events</code> counts the refusals. A thread that cannot be created fails the same way (\"can't start new thread\").",
  fix="Raise the limit (" + L("docker --pids-limit", DOCKER_RUN) + ", Kubernetes <code>podPidsLimit</code>) or start fewer workers and threads.",
  ml="Large worker counts times the thread pools of numpy, OpenMP and tokenizers in every worker.",
  first=dict(opts=["cat pids.max pids.current pids.events", "free -m", "df -h", "nvidia-smi"], a=0,
             why="EAGAIN from fork in a container is usually the pids controller."),
),
dict(
  id="zombie", seen='ps in the container lists processes in state Z that never go away:', title="Zombies pile up when the training script is PID 1",
  sub=["process", "signal"], tools=["ps"], ostep="5 Process API",
  symptom=("zombie", "    8     1 Z    sleep"),
  rec=[("zombie", "host"), ("zombie", "PID 1 is the training script"), ("zombie_init", "host"), ("zombie_init", "PID 1 is the training script")],
  cause="A process that exits stays in the process table as a zombie (state Z, \"defunct\") until its parent collects its exit status with <code>wait</code>. If its parent died first, it is handed to PID 1 of its PID namespace, whose job is to reap such orphans. In a container started with the training script as its command, PID 1 is the training script, which never calls <code>wait</code> for children it did not start: the orphaned <code>sleep</code> stays a zombie. Zombies use no memory but each holds a PID, which counts against <code>pids.max</code>.",
  fix="Run a real init as PID 1: " + L("docker run --init", DOCKER_RUN) + " (a small init, " + L("tini", "https://github.com/krallin/tini") + ") reaps orphans, as the second run shows (PID 1 is <code>docker-init</code> and no zombie remains). In Kubernetes, use an init in the image or share the pod's process namespace.",
  ml="Launch scripts that background helpers (log shippers, monitors) inside a training container.",
  first=dict(opts=["ps -eo pid,ppid,stat,comm (look for Z and PPID 1)", "free -m", "cat cpu.stat", "df -h"], a=0,
             why="State Z with parent 1 means nobody is reaping."),
),
dict(
  id="orphan", seen='After the main process was killed, ps still lists its workers, now with parent PID 1:', title="The main process is SIGKILLed: what happens to its workers",
  sub=["process", "signal"], tools=["ps"], ostep="5 Process API",
  symptom=("orphan", r"re:one second after SIGKILL[\s\S]*?\n( *\d+ +1 Sl +python /job/train.py.*)"),
  rec=[("orphan", "host"), ("orphan", "while training: the main process and its two workers"), ("orphan", "one second after SIGKILL to the main process"), ("orphan", "seven seconds after")],
  cause="SIGKILL gives the main process no chance to stop its workers. They become orphans, re-parented to PID 1 (here the container's shell), and keep running. DataLoader workers check every " + L("MP_STATUS_CHECK_INTERVAL = 5.0 s", PT + "torch/utils/data/_utils/__init__.py#L19") + " whether their parent is still alive and exit when it is not, so they were gone within seven seconds. Child processes that have no such watchdog (your own multiprocessing pools, subprocesses) keep running and keep their memory and GPU.",
  fix="Prefer SIGTERM with a handler (the SIGTERM cases); make your own children check their parent or put them in the same process group; on Linux <code>prctl(PR_SET_PDEATHSIG)</code> asks the kernel to signal a child when its parent dies.",
  ml="After an OOM kill of the main process, leftover workers can hold memory and, on GPU nodes, device memory, making the restart fail.",
  first=dict(opts=["ps -eo pid,ppid,stat,cmd (PPID 1 orphans)", "df -h", "ulimit -n", "cat cpu.stat"], a=0,
             why="Orphans show as PPID 1 with the job's command line."),
),
]
