"""Debug lab cases, part C (signals and shutdown, fork and threads, files and storage)."""
from cases_a import L, DOCKER_RUN, CG2, PT, MAN
from cases_b import K8S_TERM, STOP

CASES = [
dict(
  id="sig_pid1", seen='Stopping the job always takes the full grace period, and it exits with 137:', title="docker stop takes 10 s and ends in 137: SIGTERM ignored by PID 1",
  sub=["signal", "process"], tools=["docker", "exit code"], ostep="5 Process API",
  symptom=("sig_noh", r"re:took [\d.]+ s; container exit code \d+"),
  rec=[("sig_noh", "host"), ("sig_noh", "body"), ("sig_noh", "stop")],
  cause="<code>docker stop</code> sends SIGTERM, waits (10 s by default) and then sends SIGKILL (" + L("docker stop", STOP) + "); Kubernetes does the same with a 30 s grace period (" + L("pod termination", K8S_TERM) + "). A process with no SIGTERM handler normally dies at once (default action: terminate). But this script is PID 1 of the container's PID namespace, and the kernel delivers to PID 1 only the signals it has installed a handler for (" + L("pid_namespaces(7)", MAN + "man7/pid_namespaces.7.html") + ", " + L("kill(2) NOTES", MAN + "man2/kill.2.html") + "). So SIGTERM did nothing, the job kept training for 10 s, and SIGKILL (which PID 1 cannot block from an ancestor namespace) ended it: exit 137, everything since the last periodic checkpoint lost.",
  fix="Install a SIGTERM handler that checkpoints and exits (the handler case below), or run under an init (<code>--init</code>) that forwards signals.",
  ml="Preemptible and spot instances, Slurm and Kubernetes all announce the end with SIGTERM; a job that ignores it loses the grace period it was given to save its state.",
  first=dict(opts=["does PID 1 have a SIGTERM handler? (grep SigCgt /proc/1/status)", "free -m", "df -h", "cat cpu.stat"], a=0,
             why="A 10 s stop is the grace period expiring: the signal was ignored or not forwarded."),
  bars=dict(title="Seconds from docker stop to exit, and the exit code",
            src=[("sig_noh", r"took ([\d.]+) s", "no handler, PID 1"), ("sig_noh_init", r"took ([\d.]+) s", "no handler, --init"),
                 ("sig_train", r"took ([\d.]+) s", "handler, PID 1"), ("sig_wrapper", r"took ([\d.]+) s", "handler, shell is PID 1")], unit="s"),
),
dict(
  id="sig_default", seen='Stopped instantly, but the last checkpoint is old:', title="Stopped at once with 143 and no checkpoint: SIGTERM's default action",
  sub=["signal"], tools=["docker", "exit code"], ostep="5 Process API",
  symptom=("sig_noh_init", "container exit code 143"),
  rec=[("sig_noh_init", "host"), ("sig_noh_init", "body"), ("sig_noh_init", "stop")],
  cause="Under <code>--init</code> the script is not PID 1, so SIGTERM gets its default action: the process is terminated immediately, exit status 128 + 15 = 143. Fast, but the job saved nothing after its last periodic checkpoint.",
  fix="A handler that sets a flag, lets the current step finish, checkpoints and exits 0.",
  ml="143 in a pod's status means it was asked to stop and did not handle it.",
  first=dict(opts=["is there a SIGTERM handler? (signal.getsignal)", "memory.events", "df -h", "ulimit -n"], a=0,
             why="143 = 128 + SIGTERM: the default action ran."),
),
dict(
  id="sig_handler", seen="The good outcome, in the job's log:", title="The fix: a SIGTERM handler that checkpoints (the running job)",
  sub=["signal", "storage"], tools=["docker", "logs"], ostep="5 Process API; 42 FSCK and Journaling",
  symptom=("sig_train", "got signal 15; will checkpoint and exit"),
  rec=[("sig_train", "host"), ("sig_train", "tail"), ("sig_train", "stop")],
  cause="The running job's handler only sets a flag (a Python signal handler runs in the main thread between bytecodes, so it should do as little as possible); the loop sees the flag after the current step, writes the checkpoint with the write-then-rename pattern and exits 0, @@sig_train|took ([\d.]+) s@@ s after <code>docker stop</code>. The handler works as PID 1 because a handler is installed. This run was untraced. The Syscall tracer tab found that under strace the signal can be delivered to another thread first, so Python's handler runs one step later; untraced runs stopped on time.",
  fix="This is the pattern: flag in the handler, checkpoint in the loop, exit well inside the grace period.",
  ml="Graceful preemption. On multi-GPU jobs every rank must agree to stop at the same step before saving.",
  first=dict(opts=["the job's log around the signal", "nvidia-smi", "ulimit -n", "df -h"], a=0,
             why="Confirm the handler ran and the checkpoint finished before the grace period."),
),
dict(
  id="sig_wrapper", seen='The job has a SIGTERM handler, yet stopping it still takes the full grace period and saves nothing:', title="A handler that never runs: the launcher shell does not forward SIGTERM",
  sub=["signal", "process"], tools=["docker", "ps"], ostep="5 Process API",
  symptom=("sig_wrapper", r"re:took [\d.]+ s; container exit code \d+"),
  rec=[("sig_wrapper", "host"), ("sig_wrapper", "head"), ("sig_wrapper", "stop")],
  cause="Here the container's command is a shell script that runs <code>python train.py</code> as a child (piping its output). The shell is PID 1, receives SIGTERM, has no handler, so the kernel drops it; the shell does not pass it on, and Python, whose handler would have saved a checkpoint, never hears of it. After 10 s SIGKILL ends everything: exit 137, no checkpoint, although the job has a perfect handler.",
  fix="<code>exec python train.py</code> as the last line of the script (the shell is replaced, Python becomes PID 1), or <code>--init</code>/tini, which forwards signals to its child, or a shell <code>trap</code> that forwards the signal.",
  ml="Entry-point scripts that set up the environment and then call Python are everywhere in training images.",
  first=dict(opts=["ps -o pid,ppid,cmd: who is PID 1?", "memory.events", "df -h", "nvidia-smi"], a=0,
             why="If PID 1 is a shell, the signal stops there."),
),
dict(
  id="sig_workers", title="pkill -TERM also hits the workers: \"exited unexpectedly\" instead of a checkpoint",
  sub=["signal", "process"], tools=["ps", "logs"], ostep="5 Process API",
  symptom=("sig_pkill", r"re:RuntimeError: DataLoader worker \(pid\(s\) [\d, ]+\) exited unexpectedly"),
  rec=[("sig_pkill", "host"), ("sig_pkill", "body"), ("sig_pkill", "host: docker exec os-dbg-sig_pkill pkill -TERM -f accum.py")],
  cause="<code>pkill -f</code> matches every process whose command line contains the pattern, and forked workers share the main process's command line. At the start of each worker's loop PyTorch installs C-level handlers for SIGSEGV, SIGBUS, SIGFPE and SIGTERM that report the signal and then run its default action (" + L("signal_handling.py, NOTE", PT + "torch/utils/data/_utils/signal_handling.py") + "), so SIGTERM terminates the workers even though the main process handles it. The main process handled SIGTERM by setting a flag checked only at the end of a 64-micro-batch accumulation cycle, so it kept asking the dead workers for data and failed before it could save. Slurm's <code>scancel</code> also signals every process of a job step.",
  fix="Check the flag after every micro-batch (or stop fetching once it is set); signal only the main process (Kubernetes signals PID 1 of each container); never <code>pkill -f</code> a training job.",
  ml="The Syscall tracer tab traces the same signal arriving in the workers.",
  first=dict(opts=["which processes got the signal (pgrep -f lists the workers too)", "df -h", "memory.events", "cpu.stat"], a=0,
             why="The workers died first; ask who sent the signal to them."),
),
dict(
  id="fork_lock", seen='A DataLoader or multiprocessing worker never produces anything; no error, no CPU use:', title="A worker hangs forever: fork while another thread holds a lock",
  sub=["concurrency", "process"], tools=["ps (wchan)", "py-spy"], ostep="27 Thread API; 32 Concurrency Bugs",
  symptom=("fork", "still stuck after 8 s (start method fork)"),
  rec=[("fork", "host"), ("fork", "a lock held by another thread at the moment of fork"), ("fork", "the same program with the spawn start method")],
  cause="<code>fork</code> copies the whole address space but only the calling thread (" + L("fork(2)", MAN + "man2/fork.2.html") + "). A lock held by another thread at that instant is copied in its locked state, and the thread that would release it does not exist in the child. The child blocks forever in <code>futex_wait_queue_me</code> (the kernel's wait for a futex, the primitive under Python's and pthread's locks), and py-spy shows it on the <code>with lock</code> line. With <code>spawn</code> the child starts a fresh interpreter, imports the module and creates its own unlocked lock.",
  fix="Use <code>spawn</code> or <code>forkserver</code> (DataLoader's <code>multiprocessing_context</code>); create threads, thread pools and clients after forking workers. Python 3.12 warns when it detects fork in a multi-threaded process, and 3.14 made <code>forkserver</code> the default start method on POSIX instead of <code>fork</code> (" + L("multiprocessing docs", "https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods") + "); this image runs 3.11, where fork is still the Linux default.",
  ml="Logging handlers, metrics clients, tokenizer and OpenMP thread pools started before the DataLoader forks.",
  first=dict(opts=["ps -o stat,wchan of the stuck worker, then py-spy dump", "df -h", "free -m", "cat cpu.stat"], a=0,
             why="A sleeping child in a futex wait right after fork is the fork-with-threads deadlock."),
),
]
